force-app/main/default/objects/Gest_o_de_Documentos__c/Gest_o_de_Documentos__c.object-meta.xml
<CustomObject>
    <description>Objeto destinado ao controle da qualidade quanto a revisão e renovação dos documenos</description>
    <label>Gestão de Documento</label>
    <nameField>
        <displayFormat>GD - {0000}</displayFormat>
        <label>Nome de Gestão de Documentos</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gestão de Documentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Membro_Interno_do_Evento__c/Membro_Interno_do_Evento__c.object-meta.xml
<CustomObject>
    <label>Membro Interno do Evento</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Membros Internos do Evento</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Membro_Interno_do_Evento__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Apenas quando o participante não tiver acesso ao Salesforce.</inlineHelpText>
    <label>Contato</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>equals</operation>
            <value>HOSPCOM</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Membros Internos do Evento</relationshipLabel>
    <relationshipName>Membros_Internos_do_Evento</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Membro_Interno_do_Evento__c/fields/Evento__c.field-meta.xml
<CustomField>
    <fullName>Evento__c</fullName>
    <label>Evento</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Responsáveis pelo evento</relationshipLabel>
    <relationshipName>Membros_da_Equipe_do_Evento</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/pdfEvento.cls
public class pdfEvento {
    public Campaign evento {get;set;}
    public boolean contido {get;set;}
    public List<Gest_o_de_Documentos__c> documentos {get; set;}
    public List<Id> contatos = new List<Id>();
    
    public pdfEvento(ApexPages.StandardController controller) {
        
        documentos = GestaoDocumentos.obterDocumentosVigentes();       
        User usuario = [SELECT ContactId, ProfileId FROM User WHERE Id =: UserInfo.getUserId()];
        Id contactId = usuario.ContactId;
        contido = false;
        
        List<Membro_Interno_do_Evento__c> membros = [SELECT Contato__c FROM Membro_Interno_do_Evento__c WHERE Evento__c =: ((SObject)controller.getRecord()).Id];
        if(membros.size()>0){
            for(Membro_Interno_do_Evento__c membro : membros){
                contatos.add(membro.Contato__c);       
            }
            if(contatos.contains(contactId) || usuario.ProfileId == '00ei0000000nKA9' || usuario.ProfileId == '00e31000001dwIY'){
                contido = true;
            }
        }
        else{
            if(usuario.ProfileId == '00ei0000000nKA9' || usuario.ProfileId == '00e31000001dwIY'){
                contido = true;
            }

        }
    }
}