force-app/main/default/objects/Order/recordTypes/Hospcom.recordType-meta.xml
<RecordType>
    <fullName>Hospcom</fullName>
    <active>true</active>
    <description>Para faturamento das empresas do grupo Hospcom</description>
    <label>Hospcom</label>
</RecordType>

force-app/main/default/objects/OrderItem/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Novo</fullName>
            </value>
            <value>
                <fullName>Transferência Interna</fullName>
            </value>
            <value>
                <fullName>Pendência Interna</fullName>
            </value>
            <value>
                <fullName>Em Separação</fullName>
            </value>
            <value>
                <fullName>Galpão - Em Separação</fullName>
            </value>
            <value>
                <fullName>Separado</fullName>
            </value>
            <value>
                <fullName>Reservado</fullName>
            </value>
            <value>
                <fullName>OPR - ANALISE DE COMPRA</fullName>
            </value>
            <value>
                <fullName>CMP - COTAÇÃO DE COMPRA</fullName>
            </value>
            <value>
                <fullName>CMP - AG. ENTREGA FORNECEDOR</fullName>
            </value>
            <value>
                <fullName>Recebido Fornecedor</fullName>
            </value>
            <value>
                <fullName>Recebido A.T.</fullName>
            </value>
            <value>
                <fullName>Aguardando Faturamento</fullName>
            </value>
            <value>
                <fullName>Aguardando conferência</fullName>
            </value>
            <value>
                <fullName>Atendido</fullName>
            </value>
            <value>
                <fullName>Faturado</fullName>
            </value>
            <value>
                <fullName>Aguardando Coleta</fullName>
            </value>
            <value>
                <fullName>Em Avaliação Técnica</fullName>
            </value>
            <value>
                <fullName>CMP - AG. COMPRA IMPORTAÇÃO</fullName>
            </value>
            <value>
                <fullName>CMP - AG. COMPRA NACIONAL</fullName>
            </value>
            <value>
                <fullName>Em rota de entrega</fullName>
            </value>
            <value>
                <fullName>Entregue Cliente</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
                <label>OPR - CANCELADO</label>
            </value>
            <value>
                <fullName>Devolvido</fullName>
            </value>
            <value>
                <fullName>Recebido Parcial</fullName>
            </value>
            <value>
                <fullName>Recebido Total</fullName>
            </value>
            <value>
                <fullName>CMP - EM PRODUÇÃO FORN.</fullName>
            </value>
            <value>
                <fullName>CMP - EM COLETA PORTO/FORNECEDOR</fullName>
            </value>
            <value>
                <fullName>Em trânsito</fullName>
            </value>
            <value>
                <fullName>CMP - EM DESEMBARAÇO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Status_OrderItem__mdt/Status_OrderItem__mdt.object-meta.xml
<CustomObject>
    <description>Conjuntos de status disponíveis para o objeto OrderItem.</description>
    <label>Status OrderItem</label>
    <pluralLabel>Status</pluralLabel>
</CustomObject>

force-app/main/default/objects/Status_OrderItem__mdt/fields/Referente_a__c.field-meta.xml
<CustomField>
    <fullName>Referente_a__c</fullName>
    <label>Referente à</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Compras</fullName>
                <default>true</default>
                <label>Compras</label>
            </value>
            <value>
                <fullName>Operações</fullName>
            </value>
            <value>
                <fullName>Logística</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/orderItemService.cls
public with sharing class orderItemService{
    
    public static void recalculaStatusDoPedido(List<orderItem> itensDoPedido){
        
        
        Set<Id> pedidos_id = new Set<Id>();
        for(OrderItem item_ped : itensDoPedido){
            pedidos_id.add(item_ped.OrderId);
        }
        
        
        
        List<Order> pedidos = [
        SELECT  Id, Status, RecordType.Name, (
                    SELECT  Id, Status__c
                    FROM    Orderitems
                )
        FROM    Order
        WHERE   Id IN :pedidos_id
    ];
        
        List<String> status_inativo = new List<String>{'Rascunho','Aguardando Aprovação Comercial','Pendente', 'Aguardando Aprovação Financeira','Reprovado','Aprovado', 'Faturado', 'Cancelado'};
        
        List<Status_OrderItem__mdt> statusCompras = [
            SELECT  Status__c
            FROM    Status_OrderItem__mdt
            WHERE   Referente_a__c = 'Compras'
        ];
        
        if(statusCompras.size() > 0) {
            for(Status_OrderItem__mdt statusMdt : statusCompras) {
                if(String.isNotBlank(statusMdt.Status__c)) {
                    status_inativo.add(statusMdt.Status__c);
                }
            }
        }
        System.debug('Status inativos: ' + status_inativo);
        
        for(Order pedido : pedidos){

             if(pedido.OrderItems == null || pedido.OrderItems.isEmpty()){
                System.debug('Pedido sem itens. Ignorando recalculo: ' + pedido.Id);
                continue;
            }
            
            Integer qtd_novabe = 0,     qtd_entregue = 0,   qtd_atendido = 0,
            qtd_cancelado = 0,          qtd_total = 0,      qtd_faturado = 0;
            
            for(Orderitem item_ped : pedido.OrderItems){
                if(item_ped.Status__c == 'Novo') qtd_novabe++;
                else if(item_ped.Status__c == 'Aberto') qtd_novabe++;
                else if(item_ped.Status__c == 'Entregue Cliente') qtd_entregue++;
                else if(item_ped.Status__c == 'Atendido') qtd_atendido++;
                else if(item_ped.Status__c == 'Faturado') qtd_faturado++;
                else if(item_ped.Status__c == 'Cancelado') qtd_cancelado++;
                qtd_total++;
            }
            
            if(pedido.RecordType.Name=='Hospcom' || pedido.RecordType.Name=='Venda Balcão' || pedido.RecordType.Name == 'Venda Commerce' || pedido.RecordType.Name == 'OPME - Zimmer'){
                if(status_inativo.contains(pedido.Status)){
                    if(qtd_cancelado == qtd_total) pedido.Status = 'Cancelado';
                }else{
                    //if(qtd_total == qtd_novabe) pedido.Status = 'Ativo';
                    if(qtd_cancelado == qtd_total) pedido.Status = 'Cancelado';
                    else if(qtd_entregue>0 && qtd_entregue<(qtd_total-qtd_cancelado)) pedido.Status = 'Entregue Parcial';
                    else if(qtd_entregue == (qtd_total-qtd_cancelado)) pedido.Status = 'Entregue Total';
                    
                    else if(qtd_atendido>0 && qtd_atendido<(qtd_total-qtd_cancelado)) pedido.Status = 'Atendido Parcial';
                    else if(qtd_atendido == (qtd_total-qtd_cancelado)) pedido.Status = 'Atendido Total';
                    else pedido.Status = 'Em Andamento';
                }
            }
            else if(pedido.RecordType.Name=='Representação'){
                if(status_inativo.contains(pedido.Status)){
                    if(qtd_cancelado == qtd_total) pedido.Status = 'Cancelado';
                }else{
                    if(qtd_cancelado == qtd_total) pedido.Status = 'Cancelado';
                    else if(qtd_entregue>0 && qtd_entregue<(qtd_total-qtd_cancelado)) pedido.Status = 'Entregue Parcial';
                    else if(qtd_entregue == (qtd_total-qtd_cancelado)) pedido.Status = 'Entregue Total';
                    
                    else if(qtd_faturado == (qtd_total-qtd_cancelado)) pedido.Status = 'Entregue Total';
                    
                    else if(qtd_atendido>0 && qtd_atendido<(qtd_total-qtd_cancelado)) pedido.Status = 'Atendido Parcial';
                    else if(qtd_atendido == (qtd_total-qtd_cancelado)) pedido.Status = 'Atendido Total';
                    else pedido.Status = 'Em Andamento';
                }
            }
            
        }
        
        
        
        Util.AcaoInterna(true);
        update pedidos;
        Util.AcaoInterna(false);
    }
    
    
}