force-app/main/default/objects/Backlog__c/Backlog__c.object-meta.xml
<CustomObject>
    <label>Backlog</label>
    <nameField>
        <displayFormat>TKT - {0000}</displayFormat>
        <label>Ticket</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Backlogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Backlog__c/fields/Data_Estimada_de_T_rmino__c.field-meta.xml
<CustomField>
    <fullName>Data_Estimada_de_T_rmino__c</fullName>
    <label>Data de Término Prevista</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Backlog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Novo</fullName>
            </value>
            <value>
                <fullName>Em Refinamento</fullName>
            </value>
            <value>
                <fullName>Em Desenvolvimento</fullName>
            </value>
            <value>
                <fullName>Analise de Qualidade</fullName>
            </value>
            <value>
                <fullName>Finalizado</fullName>
            </value>
            <value>
                <fullName>Recusado</fullName>
            </value>
            <value>
                <fullName>Aguardando Validação</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Backlog__c/fields/Tempo_de_Execucao__c.field-meta.xml
<CustomField>
    <fullName>Tempo_de_Execucao__c</fullName>
    <inlineHelpText>Tempo nescessario para execução do ticket, em horas</inlineHelpText>
    <label>Tempo de Execução (Em Horas)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Backlog__c/fields/Ticket_Criado_Em__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Criado_Em__c</fullName>
    <description>Data e hora da criação do ticket</description>
    <label>Ticket Criado Em</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Backlog__c/fields/Ticket_Finalizado_Em__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Finalizado_Em__c</fullName>
    <label>Ticket Finalizado Em</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/BacklogService.cls
public with sharing class BacklogService {

    public static void atualizaDataAbertura(List<Backlog__c> novosTickets){
        
        for(Backlog__c b : novosTickets){
                b.Ticket_Criado_Em__c = Datetime.now(); 
        }      
    }
    
    public static void atualizaDataFinalizacao(List<Backlog__c> novosTickets, Map<Id, Backlog__c> velhosTickets){

        for(Backlog__c b : novosTickets){
            if(b.Status__c == 'Finalizado' && velhosTickets.get(b.Id).Status__c != 'Finalizado'){
                b.Ticket_Finalizado_Em__c = Datetime.now(); 
            }
        }
    }

    public static void atualizadaHorasEstimadas(List<Backlog__c> novosTickets) {
        Id bhId = [SELECT Id FROM BusinessHours WHERE Name = 'Brasilia' LIMIT 1].Id;

        for (Backlog__c ticket : novosTickets) {
            if (ticket.Ticket_Criado_Em__c != null && ticket.Data_Estimada_de_T_rmino__c != null) {
                Long diffMillis = BusinessHours.diff(
                    bhId,
                    ticket.Ticket_Criado_Em__c,
                    ticket.Data_Estimada_de_T_rmino__c
                );

                Decimal horasUteis = diffMillis != null 
                    ? diffMillis / (1000 * 60 * 60) 
                    : 0;

                ticket.Tempo_de_Execucao__c = horasUteis;
            } else {
                ticket.Tempo_de_Execucao__c = 0;
            }
        }
    }
}