force-app/main/default/objects/Backlog__c/Backlog__c.object-meta.xml
<CustomObject>
    <label>Backlog</label>
    <nameField>
        <displayFormat>TKT - {0000}</displayFormat>
        <label>Ticket</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Backlogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Backlog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Novo</fullName>
            </value>
            <value>
                <fullName>Em Refinamento</fullName>
            </value>
            <value>
                <fullName>Em Desenvolvimento</fullName>
            </value>
            <value>
                <fullName>Analise de Qualidade</fullName>
            </value>
            <value>
                <fullName>Finalizado</fullName>
            </value>
            <value>
                <fullName>Recusado</fullName>
            </value>
            <value>
                <fullName>Aguardando Validação</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BacklogTriggerHandlerTest.cls
@isTest
public with sharing class BacklogTriggerHandlerTest {
    
    @isTest
    public static void testInsert(){

        List<Backlog__c> backlogs = new List<Backlog__c>();
        for (Integer i = 0; i < 3; i++) {
            backlogs.add(new Backlog__c(
                Status__c = 'Novo'
            ));
        }

        Test.startTest();
        insert backlogs;
        Test.stopTest();
    }

    @isTest
    public static void testUpdate(){
        List<Backlog__c> backlogs = new List<Backlog__c>();
        for (Integer i = 0; i < 3; i++) {
            backlogs.add(new Backlog__c(
                Status__c = 'Novo'
            ));
        }

        insert backlogs;

        for (Backlog__c b : backlogs) {
            b.Status__c = 'Finalizado';
        }

        Test.startTest();
        update backlogs;
        Test.stopTest();
    }
}