force-app/main/default/objects/Contrato_de_Servi_o__c/Contrato_de_Servi_o__c.object-meta.xml
<CustomObject>
    <label>Contrato de Serviço</label>
    <nameField>
        <label>Nome do Contrato</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contratos de Serviços</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contratos de Locação</relationshipLabel>
    <relationshipName>Contratos_de_Servi_os</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Valor_Global__c.field-meta.xml
<CustomField>
    <fullName>Valor_Global__c</fullName>
    <label>Valor Global</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Valor_Total_do_Contrato__c.field-meta.xml
<CustomField>
    <fullName>Valor_Total_do_Contrato__c</fullName>
    <formula>IF( Proposta_Contrato_Global__c == false, Valor_Mensal_do_Contrato__c * Dura_o_do_Contrato_meses__c,  Valor_Global__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valor Total do Contrato</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/AutentiqueContratosTest.cls
@isTest(seeAllData=true)
public class AutentiqueContratosTest {
	@isTest
    private static void teste(){
        
        Test.setMock(HttpCalloutMock.class, new MockAutentiqueContratos());
        
        
        Contrato_de_Servi_o__c Contrato = [SELECT ID, Name, Cliente__r.Name, Valor_Total_do_Contrato__c, Cliente__r.PersonEmail, Valor_Global__c, idDocAutentique__c FROM Contrato_de_Servi_o__c WHERE ID = 'a1Y5A00000AqOn9'];
        
        AutentiqueContratos AC = new AutentiqueContratos(new ApexPages.StandardController(Contrato));
        
        AC.atualizar();
        AC.inserir();
        
    }
    @isTest
    private static void teste3(){
        
        Test.setMock(HttpCalloutMock.class, new MockAutentiqueContratos());
        
        
        Contrato_de_Servi_o__c Contrato = [SELECT ID, Name, Cliente__r.Name, Cliente__r.PersonEmail, Valor_Total_do_Contrato__c, Valor_Global__c, idDocAutentique__c FROM Contrato_de_Servi_o__c WHERE ID = 'a1Y6e00000C3Ss5'];
        
        AutentiqueContratos AC = new AutentiqueContratos(new ApexPages.StandardController(Contrato));
        
        AC.atualizar();
        AC.inserir();
        AC.enviar();
        
    }
    @isTest
    private static void teste2(){
        
        Test.setMock(HttpCalloutMock.class, new MockAutentiqueContratos2());
        
        
        Contrato_de_Servi_o__c Contrato = [SELECT ID, Name, Cliente__r.Name, Cliente__r.PersonEmail, Valor_Total_do_Contrato__c, Valor_Global__c, idDocAutentique__c FROM Contrato_de_Servi_o__c WHERE ID = 'a1Y5A00000AqOn9'];
        
        AutentiqueContratos AC = new AutentiqueContratos(new ApexPages.StandardController(Contrato));
        
        AC.enviar();
        
    }
    @isTest
    private static void teste4(){
        
        Test.setMock(HttpCalloutMock.class, new MockAutentiqueContratos2());
        
        
        Contrato_de_Servi_o__c Contrato = [SELECT ID, Name, Cliente__r.Name, Cliente__r.PersonEmail, Valor_Total_do_Contrato__c, Valor_Global__c, idDocAutentique__c FROM Contrato_de_Servi_o__c WHERE ID = 'a1Y6e00000C3V6I'];
        
        AutentiqueContratos AC = new AutentiqueContratos(new ApexPages.StandardController(Contrato));
        
        AC.enviar();
        AC.inserir();
        
    }
}