force-app/main/default/objects/Contrato_de_Servi_o__c/Contrato_de_Servi_o__c.object-meta.xml
<CustomObject>
    <label>Contrato de Serviço</label>
    <nameField>
        <label>Nome do Contrato</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contratos de Serviços</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Forma_de_pagamento2__c.field-meta.xml
<CustomField>
    <fullName>Forma_de_pagamento2__c</fullName>
    <label>Forma de pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Formas_de_pagamento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Demonstracao__c/Demonstracao__c.object-meta.xml
<CustomObject>
    <label>Comodato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comodatos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order/fields/Comentarios__c.field-meta.xml
<CustomField>
    <fullName>Comentarios__c</fullName>
    <label>Comentários</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Order/fields/Condicao_de_pagamento__c.field-meta.xml
<CustomField>
    <fullName>Condicao_de_pagamento__c</fullName>
    <label>Condição de pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Natureza_de_Opera_o__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Condicoes_de_pagamento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Contrato_de_Servi_o__c.field-meta.xml
<CustomField>
    <fullName>Contrato_de_Servi_o__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato de Serviço</label>
    <referenceTo>Contrato_de_Servi_o__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Demonstracao__c.field-meta.xml
<CustomField>
    <fullName>Demonstracao__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Comodato</label>
    <referenceTo>Demonstracao__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Departamento3__c.field-meta.xml
<CustomField>
    <fullName>Departamento3__c</fullName>
    <label>Departamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Departamentos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/E_mail_Contato__c.field-meta.xml
<CustomField>
    <fullName>E_mail_Contato__c</fullName>
    <label>E-mail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Order/fields/Entrega_liberada_pelo_financeiro__c.field-meta.xml
<CustomField>
    <fullName>Entrega_liberada_pelo_financeiro__c</fullName>
    <label>Entrega liberada pelo financeiro</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Natureza_de_Opera_o__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SIM</fullName>
            </value>
            <value>
                <fullName>NÃO</fullName>
                <default>true</default>
                <label>NÃO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Entrega_parcial__c.field-meta.xml
<CustomField>
    <fullName>Entrega_parcial__c</fullName>
    <label>Entrega parcial</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Autorizada</fullName>
            </value>
            <value>
                <fullName>Não Autorizada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Faturamento_Feito__c.field-meta.xml
<CustomField>
    <fullName>Faturamento_Feito__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Empresa do grupo Hospcom que irá faturar o pedido.</inlineHelpText>
    <label>Faturamento feito</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Faturamentos Feitos (de pedidos)</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Forma_de_pagamento2__c.field-meta.xml
<CustomField>
    <fullName>Forma_de_pagamento2__c</fullName>
    <label>Forma de pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Natureza_de_Opera_o__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Formas_de_pagamento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Frete__c.field-meta.xml
<CustomField>
    <fullName>Frete__c</fullName>
    <label>Tipo de envio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipos_de_envio</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Locado_em__c.field-meta.xml
<CustomField>
    <fullName>Locado_em__c</fullName>
    <label>Locado em:</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Natureza_de_Opera_o__c.field-meta.xml
<CustomField>
    <fullName>Natureza_de_Opera_o__c</fullName>
    <label>Natureza de Operação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BONIFICAÇÃO</fullName>
            </value>
            <value>
                <fullName>DEMONSTRAÇÃO</fullName>
            </value>
            <value>
                <fullName>LOCAÇÃO</fullName>
            </value>
            <value>
                <fullName>EMPRÉSTIMO</fullName>
            </value>
            <value>
                <fullName>REMESSA DE LOCAÇÃO</fullName>
            </value>
            <value>
                <fullName>REMESSA DE TROCA</fullName>
            </value>
            <value>
                <fullName>REMESSA EM CONSIGNAÇÃO</fullName>
            </value>
            <value>
                <fullName>SERVIÇO</fullName>
            </value>
            <value>
                <fullName>VENDA</fullName>
            </value>
            <value>
                <fullName>VENDA DA CONSIGNAÇÃO</fullName>
            </value>
            <value>
                <fullName>RETORNO DE LOCAÇÃO</fullName>
            </value>
            <value>
                <fullName>EXPORTAÇÃO</fullName>
            </value>
            <value>
                <fullName>Baixa de estoque Interno</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Necess_rio_Treinamento__c.field-meta.xml
<CustomField>
    <fullName>Necess_rio_Treinamento__c</fullName>
    <label>Necessário Treinamento?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SIM</fullName>
            </value>
            <value>
                <fullName>NÃO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Nome_Contato_Financeiro__c.field-meta.xml
<CustomField>
    <fullName>Nome_Contato_Financeiro__c</fullName>
    <label>Nome</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Ordem_de_trabalho__c.field-meta.xml
<CustomField>
    <fullName>Ordem_de_trabalho__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ordem de trabalho</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Pedido_da_Linha_de_OPME__c.field-meta.xml
<CustomField>
    <fullName>Pedido_da_Linha_de_OPME__c</fullName>
    <label>Pedido da Linha de OPME?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SIM</fullName>
            </value>
            <value>
                <fullName>NÃO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Prioridade__c.field-meta.xml
<CustomField>
    <fullName>Prioridade__c</fullName>
    <label>Prioridade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ALTO</fullName>
            </value>
            <value>
                <fullName>NORMAL</fullName>
                <default>true</default>
                <label>NORMAL</label>
            </value>
            <value>
                <fullName>BAIXO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Telefone_Contato__c.field-meta.xml
<CustomField>
    <fullName>Telefone_Contato__c</fullName>
    <label>Telefone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Order/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PedidosVendedor</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Departamentos.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Administrativo</fullName>
    </customValue>
    <customValue>
        <fullName>Comercial</fullName>
    </customValue>
    <customValue>
        <fullName>Compras</fullName>
    </customValue>
    <customValue>
        <fullName>Contabilidade</fullName>
        <label>Contabilidade/Fiscal/DP</label>
    </customValue>
    <customValue>
        <fullName>Controladoria</fullName>
    </customValue>
    <customValue>
        <fullName>Desenvolvimento</fullName>
    </customValue>
    <customValue>
        <fullName>Diretoria Administrativa</fullName>
    </customValue>
    <customValue>
        <fullName>Diretoria de B.I e Growth</fullName>
    </customValue>
    <customValue>
        <fullName>Diretoria de Negocios</fullName>
    </customValue>
    <customValue>
        <fullName>Educação</fullName>
        <label>Educação Continuada</label>
    </customValue>
    <customValue>
        <fullName>Faturamento</fullName>
    </customValue>
    <customValue>
        <fullName>Financeiro</fullName>
    </customValue>
    <customValue>
        <fullName>Governo</fullName>
    </customValue>
    <customValue>
        <fullName>Jurídico</fullName>
    </customValue>
    <customValue>
        <fullName>Locação</fullName>
    </customValue>
    <customValue>
        <fullName>Logística</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Operações</fullName>
    </customValue>
    <customValue>
        <fullName>Outros</fullName>
    </customValue>
    <customValue>
        <fullName>Qualidade</fullName>
    </customValue>
    <customValue>
        <fullName>RH</fullName>
    </customValue>
    <customValue>
        <fullName>Serviço</fullName>
    </customValue>
    <customValue>
        <fullName>Departamento Pessoal</fullName>
        <isActive>false</isActive>
        <label>Departamento Pessoal</label>
    </customValue>
    <customValue>
        <fullName>Facilites</fullName>
        <isActive>false</isActive>
        <label>Facilites</label>
    </customValue>
    <customValue>
        <fullName>T.I.</fullName>
        <isActive>false</isActive>
        <label>T.I.</label>
    </customValue>
    <customValue>
        <fullName>OPME</fullName>
        <isActive>false</isActive>
        <label>OPME</label>
    </customValue>
    <customValue>
        <fullName>Manutenção</fullName>
        <isActive>false</isActive>
        <label>Manutenção</label>
    </customValue>
    <customValue>
        <fullName>Limpeza</fullName>
        <isActive>false</isActive>
        <label>Limpeza</label>
    </customValue>
    <customValue>
        <fullName>Fiscal</fullName>
        <isActive>false</isActive>
        <label>Fiscal</label>
    </customValue>
    <masterLabel>Departamentos</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/Tipos_de_envio.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Contratação do Frete por conta do Remetente (CIF)</fullName>
    </customValue>
    <customValue>
        <fullName>Contratação do Frete por conta do Destinatário (FOB)</fullName>
    </customValue>
    <customValue>
        <fullName>Contratação do Frete por conta de Terceiros</fullName>
    </customValue>
    <customValue>
        <fullName>Transporte Próprio por conta do Remetente</fullName>
    </customValue>
    <customValue>
        <fullName>Transporte Próprio por conta do Destinatário</fullName>
    </customValue>
    <customValue>
        <fullName>Sem Ocorrência de Transporte.</fullName>
    </customValue>
    <masterLabel>Tipos de envio</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PedidoPreenchimentoTest2.cls
@isTest(seeAllData=true)
public class PedidoPreenchimentoTest2 {
    @isTest
    public static void teste1(){
        Order order = new Order(
            AccountId = '0016e00003FBzFGAA1',
            Contrato_de_Servi_o__c = 'a1YU4000000lOF0MAM',
            EffectiveDate = system.today(),
            Status = 'Rascunho',
            Comentarios__c = 'Pedido criado automaticamente a partir da aprovação do contrato.',
            Condicao_de_pagamento__c = '30 dias',
            Departamento3__c = 'Locação',
            E_mail_Contato__c = 'teste@dev.com',
            Entrega_parcial__c = 'Não Autorizada',
            Faturamento_Feito__c = '001i00000085QYbAAM',
            Forma_de_pagamento2__c = 'Cob. Boleto - Banco do Brasil - Ag: 1610-1 Cc: 128057-0 - GDB',
            Frete__c = 'Transporte Próprio por conta do Destinatário',
            Locado_em__c = '-',
            Natureza_de_Opera_o__c = 'LOCAÇÃO',
            Necess_rio_Treinamento__c = 'NÃO',
            Nome_Contato_Financeiro__c = 'Nome Contato',
            Pricebook2Id = '01s5A000004fbcR',
            Telefone_Contato__c = '62991004477',
            Vendedor__c = '005i0000005d2fF',
            Prioridade__c = 'NORMAL',
            Entrega_liberada_pelo_financeiro__c = 'NÃO',
            Pedido_da_Linha_de_OPME__c = 'NÃO'
        );
        insert order;
    }
    @isTest
    public static void teste2(){
        Order order = new Order(
            AccountId = '0016e00003FBzFGAA1',
            OpportunityId = '006U400000E57C9IAJ',
            Departamento3__c = 'Governo',
            EffectiveDate = system.today(),
            Status = 'Rascunho',
            Comentarios__c = 'Pedido criado automaticamente a partir da aprovação do contrato.',
            Condicao_de_pagamento__c = '30 dias',
            E_mail_Contato__c = 'teste@dev.com',
            Entrega_parcial__c = 'Não Autorizada',
            Faturamento_Feito__c = '001i00000085QYbAAM',
            Forma_de_pagamento2__c = 'Cob. Boleto - Banco do Brasil - Ag: 1610-1 Cc: 128057-0 - GDB',
            Frete__c = 'Transporte Próprio por conta do Destinatário',
            Locado_em__c = '-',
            Natureza_de_Opera_o__c = 'VENDA',
            Necess_rio_Treinamento__c = 'NÃO',
            Nome_Contato_Financeiro__c = 'Nome Contato',
            Pricebook2Id = '01s5A000004fbcR',
            Telefone_Contato__c = '62991004477',
            Vendedor__c = '005i0000005d2fF',
            Prioridade__c = 'NORMAL',
            Entrega_liberada_pelo_financeiro__c = 'NÃO',
            Pedido_da_Linha_de_OPME__c = 'NÃO'
        );
        insert order;
    }
    @isTest
    public static void teste3(){
        Order order = new Order(
            AccountId = '0016e00003FBzFGAA1',
            Contrato_de_Servi_o__c = 'a1YU4000000lOF0MAM',
            Departamento3__c = 'Governo',
            EffectiveDate = system.today(),
            Status = 'Rascunho',
            Comentarios__c = 'Pedido criado automaticamente a partir da aprovação do contrato.',
            Condicao_de_pagamento__c = '30 dias',
            E_mail_Contato__c = 'teste@dev.com',
            Entrega_parcial__c = 'Não Autorizada',
            Faturamento_Feito__c = '001i00000085QYbAAM',
            Forma_de_pagamento2__c = 'Cob. Boleto - Banco do Brasil - Ag: 1610-1 Cc: 128057-0 - GDB',
            Frete__c = 'Transporte Próprio por conta do Destinatário',
            Locado_em__c = '-',
            Natureza_de_Opera_o__c = 'LOCAÇÃO',
            Necess_rio_Treinamento__c = 'NÃO',
            Nome_Contato_Financeiro__c = 'Nome Contato',
            Pricebook2Id = '01s5A000004fbcR',
            Telefone_Contato__c = '62991004477',
            Vendedor__c = '005i0000005d2fF',
            Prioridade__c = 'NORMAL',
            Entrega_liberada_pelo_financeiro__c = 'NÃO',
            Pedido_da_Linha_de_OPME__c = 'NÃO'
        );
        insert order;
    }
    @isTest
    public static void teste4(){
        Order order = new Order(
            AccountId = '0016e00003FBzFGAA1',
            OpportunityId = '006U400000E57C9IAJ',
            QuoteId = '0Q06e00000407WACAY',
            Departamento3__c = 'Comercial',
            EffectiveDate = system.today(),
            Status = 'Rascunho',
            Comentarios__c = 'Pedido criado automaticamente a partir da aprovação do contrato.',
            Condicao_de_pagamento__c = '30 dias',
            E_mail_Contato__c = 'teste@dev.com',
            Entrega_parcial__c = 'Não Autorizada',
            Faturamento_Feito__c = '001i00000085QYbAAM',
            Forma_de_pagamento2__c = 'Cob. Boleto - Banco do Brasil - Ag: 1610-1 Cc: 128057-0 - GDB',
            Frete__c = 'Transporte Próprio por conta do Destinatário',
            Locado_em__c = '-',
            Natureza_de_Opera_o__c = 'VENDA',
            Necess_rio_Treinamento__c = 'NÃO',
            Nome_Contato_Financeiro__c = 'Nome Contato',
            Pricebook2Id = '01s5A000004fbcR',
            Telefone_Contato__c = '62991004477',
            Vendedor__c = '005i0000005d2fF',
            Prioridade__c = 'NORMAL',
            Entrega_liberada_pelo_financeiro__c = 'NÃO',
            Pedido_da_Linha_de_OPME__c = 'NÃO'
        );
        insert order;
    }
    @isTest
    public static void teste5(){
        Order order = new Order(
            AccountId = '0016e00003FBzFGAA1',
            Ordem_de_trabalho__c = '0WOU4000000mwkrOAA',
            Departamento3__c = 'Comercial',
            EffectiveDate = system.today(),
            Status = 'Rascunho',
            Comentarios__c = 'Pedido criado automaticamente a partir da aprovação do contrato.',
            Condicao_de_pagamento__c = '30 dias',
            E_mail_Contato__c = 'teste@dev.com',
            Entrega_parcial__c = 'Não Autorizada',
            Faturamento_Feito__c = '001i00000085QYbAAM',
            Forma_de_pagamento2__c = 'Cob. Boleto - Banco do Brasil - Ag: 1610-1 Cc: 128057-0 - GDB',
            Frete__c = 'Transporte Próprio por conta do Destinatário',
            Locado_em__c = '-',
            Natureza_de_Opera_o__c = 'SERVIÇO',
            Necess_rio_Treinamento__c = 'NÃO',
            Nome_Contato_Financeiro__c = 'Nome Contato',
            Pricebook2Id = '01s5A000004fbcR',
            Telefone_Contato__c = '62991004477',
            Vendedor__c = '005i0000005d2fF',
            Prioridade__c = 'NORMAL',
            Entrega_liberada_pelo_financeiro__c = 'NÃO',
            Pedido_da_Linha_de_OPME__c = 'NÃO'
        );
        insert order;
    }
    @isTest
    public static void teste6(){
        Order order = new Order(
            AccountId = '0016e00003FBzFGAA1',
            Demonstracao__c = 'a0KU400001cjShhMAE',
            Departamento3__c = 'Comercial',
            EffectiveDate = system.today(),
            Status = 'Rascunho',
            Comentarios__c = 'Pedido criado automaticamente a partir da aprovação do contrato.',
            Condicao_de_pagamento__c = '30 dias',
            E_mail_Contato__c = 'teste@dev.com',
            Entrega_parcial__c = 'Não Autorizada',
            Faturamento_Feito__c = '001i00000085QYbAAM',
            Forma_de_pagamento2__c = 'Cob. Boleto - Banco do Brasil - Ag: 1610-1 Cc: 128057-0 - GDB',
            Frete__c = 'Transporte Próprio por conta do Destinatário',
            Locado_em__c = '-',
            Natureza_de_Opera_o__c = 'VENDA',
            Necess_rio_Treinamento__c = 'NÃO',
            Nome_Contato_Financeiro__c = 'Nome Contato',
            Pricebook2Id = '01s5A000004fbcR',
            Telefone_Contato__c = '62991004477',
            Vendedor__c = '005i0000005d2fF',
            Prioridade__c = 'NORMAL',
            Entrega_liberada_pelo_financeiro__c = 'NÃO',
            Pedido_da_Linha_de_OPME__c = 'NÃO'
        );
        insert order;
    }
}