force-app/main/default/objects/Contrato_de_Servi_o__c/Contrato_de_Servi_o__c.object-meta.xml
<CustomObject>
    <label>Contrato de Serviço</label>
    <nameField>
        <label>Nome do Contrato</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contratos de Serviços</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Calibra_o__c.field-meta.xml
<CustomField>
    <fullName>Calibra_o__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Calibração</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Ensaio_de_Seguran_a_El_trica__c.field-meta.xml
<CustomField>
    <fullName>Ensaio_de_Seguran_a_El_trica__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ensaio de Segurança Elétrica</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Locador_a__c.field-meta.xml
<CustomField>
    <fullName>Locador_a__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Locador(a)/Contratada</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contratos de Serviços (Locador(a))</relationshipLabel>
    <relationshipName>Contratos_de_Servi_os1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Locat_rio_a__c.field-meta.xml
<CustomField>
    <fullName>Locat_rio_a__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Locatário(a)/Contratante</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contratos de Locação</relationshipLabel>
    <relationshipName>Contratos_de_Servi_os2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Manut_Corretiva_Apenas_Mao_de_Obra__c.field-meta.xml
<CustomField>
    <fullName>Manut_Corretiva_Apenas_Mao_de_Obra__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Manut. Corretiva (Apenas Mão de Obra)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Manut_Corretiva_Mao_de_Obra_e_Pecas__c.field-meta.xml
<CustomField>
    <fullName>Manut_Corretiva_Mao_de_Obra_e_Pecas__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Manut. Corretiva (Mão de Obra e Peças)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Manut_Preventiva_Apenas_Mao_de_Obra__c.field-meta.xml
<CustomField>
    <fullName>Manut_Preventiva_Apenas_Mao_de_Obra__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Manut Preventiva (Apenas Mão de Obra)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Manut_Preventiva_Mao_de_Obra_e_Pecas__c.field-meta.xml
<CustomField>
    <fullName>Manut_Preventiva_Mao_de_Obra_e_Pecas__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Manut. Preventiva (Mão de Obra e Peças)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TestedeContratodeServicos.cls
@isTest(seeAllData=true)
private class TestedeContratodeServicos {
    
    // Teste de classes
    
    @isTest static void TestedeContratodeServicos(){
        Contrato_de_Servi_o__c testecontrato = new Contrato_de_Servi_o__c(
            Locador_a__c = '0015A00001yGbVZQA0', //Teste:001W000000mOVSw Prod: 0015A00001yGbVZQA0
            Locat_rio_a__c = '0015A00001yGbVZQA0' //Teste:001W000000mOVSw Prod: 0015A00001yGbVZQA0
         
        );
        insert testecontrato;
        testecontrato.Locador_a__c = '001i00000085QYbAAM'; //Teste: 001W000000mLBpY Prod: 001i00000085QYbAAM 
        testecontrato.Manut_Corretiva_Apenas_Mao_de_Obra__c = true;
        testecontrato.Manut_Corretiva_Mao_de_Obra_e_Pecas__c = true;
        testecontrato.Manut_Preventiva_Apenas_Mao_de_Obra__c = true;
        testecontrato.Manut_Preventiva_Mao_de_Obra_e_Pecas__c=true;
        testecontrato.Calibra_o__c=true;
        testecontrato.Ensaio_de_Seguran_a_El_trica__c=true;
          testecontrato.RecordTypeId = '0125A000001Qydf'; 
        update testecontrato;
        
         testecontrato.RecordTypeId = '0125A000001QydL'; 
        update testecontrato;
    }   
}