force-app/main/default/objects/Contrato_de_Servi_o__c/Contrato_de_Servi_o__c.object-meta.xml
<CustomObject>
    <label>Contrato de Serviço</label>
    <nameField>
        <label>Nome do Contrato</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contratos de Serviços</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contratos de Serviços</relationshipLabel>
    <relationshipName>Contratos_de_Servi_os</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Faturamento__c/Faturamento__c.object-meta.xml
<CustomObject>
    <label>Faturamento</label>
    <nameField>
        <label>Número</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Faturamentos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Faturamento__c/fields/Contrato_de_servico__c.field-meta.xml
<CustomField>
    <fullName>Contrato_de_servico__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato</label>
    <referenceTo>Contrato_de_Servi_o__c</referenceTo>
    <relationshipLabel>Faturamento</relationshipLabel>
    <relationshipName>Faturamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Faturamento__c/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Se Oportunidade:
- Contrato de Serviços Corretiva/Preventiva/Metrologia (Serviço+Peça)
- Assistência : Preventiva : Avulso Pacote (Serviço+Peça)
- Assistência : Metrologia : Avulso Pacote (Serviço)</description>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Pagamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Faturamento__c/fields/Ordem_de_Trabalho__c.field-meta.xml
<CustomField>
    <fullName>Ordem_de_Trabalho__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Se Ordem de Trab.:
- Assistência : Corretiva : Avulso Unitário/Pacote/AddContrato (Serviço)
-*Assistência : Preventiva : Avulso Unitário (Serviço+Peça)
-*Assistência : Metrologia : Avulso Unitário (Serviço)</description>
    <label>Ordem de trabalho</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipName>Faturamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Faturamento__c/fields/Pedido__c.field-meta.xml
<CustomField>
    <fullName>Pedido__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Se Pedido de Oportunidade:
- Comercial Público (Produtos)
- Comercial Privado (Produtos)

Se Pedido de Ordem de Trab.:
- Assistência : Corretiva : Avulso Unitário/Pacote/AddContrato (Peças)</description>
    <label>Pedido</label>
    <referenceTo>Order</referenceTo>
    <relationshipName>Faturamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Faturamento__c/fields/Procedencia__c.field-meta.xml
<CustomField>
    <fullName>Procedencia__c</fullName>
    <label>Procedência (automático)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contrato de Serviço</fullName>
            </value>
            <value>
                <fullName>Contrato de Locação</fullName>
            </value>
            <value>
                <fullName>Serviço Avulso (Contrato de Serviço)</fullName>
            </value>
            <value>
                <fullName>Serviço Avulso (Contrato de Locação)</fullName>
            </value>
            <value>
                <fullName>Serviço Avulso</fullName>
            </value>
            <value>
                <fullName>Comercial</fullName>
            </value>
            <value>
                <fullName>Governo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contrato_de_Servico__c.field-meta.xml
<CustomField>
    <fullName>Contrato_de_Servico__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato de serviço (excluir)</label>
    <referenceTo>ServiceContract</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Comercial.recordType-meta.xml
<RecordType>
    <fullName>Comercial</fullName>
    <active>true</active>
    <businessProcess>Padrão</businessProcess>
    <description>Processo de vendas comercial</description>
    <label>Comercial</label>
</RecordType>

force-app/main/default/objects/Order/fields/Ordem_de_trabalho__c.field-meta.xml
<CustomField>
    <fullName>Ordem_de_trabalho__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ordem de trabalho</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Faturamento__c.field-meta.xml
<CustomField>
    <fullName>Faturamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Faturamento (Representação)</label>
    <referenceTo>Faturamento__c</referenceTo>
    <relationshipLabel>Ordens de trabalho</relationshipLabel>
    <relationshipName>Ordens_de_trabalho</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Oportunidade_Relacionada__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade_Relacionada__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Ordens de trabalho</relationshipLabel>
    <relationshipName>Ordens_de_trabalho</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FatuObtProcClass.cls
public class FatuObtProcClass {
    
    public static Void FluxoInicial(Faturamento__c faturamento){
        
        // Cria registros associados
        Opportunity oportunidade = new Opportunity();
        WorkOrder ordem_de_trabalho = new WorkOrder();
        Order pedido = new Order();
        
        System.debug(LoggingLevel.INFO, 'faturamento.Oportunidade__c: ' + faturamento.Oportunidade__c);        
        
        // pesquisa registros associados
        If(faturamento.Oportunidade__c != null){
            oportunidade = [
                SELECT 	RecordType.Name, Contrato_de_Servico__r.RecordType.Name
                FROM	Opportunity
                WHERE	Id = :faturamento.Oportunidade__c
            ];
            System.debug(LoggingLevel.INFO, 'oportunidade.RecordType.Name: ' + oportunidade.RecordType.Name);
            System.debug(LoggingLevel.INFO, 'oportunidade.Contrato_de_Servico__r.RecordType.Name: ' + oportunidade.Contrato_de_Servico__r.RecordType.Name);
        }
        else if (faturamento.Ordem_de_Trabalho__c != null){
            ordem_de_trabalho = [
                SELECT	Id, Oportunidade_Relacionada__c, Oportunidade_Relacionada__r.Contrato_de_Servico__r.RecordType.Name,
                		ServiceContract.RecordType.Name
                FROM	WorkOrder
                WHERE	Id = :faturamento.Ordem_de_Trabalho__c
            ];
        }
        else if(faturamento.Pedido__c != null){
            pedido = [
                SELECT	Opportunity.RecordType.Name, Ordem_de_Trabalho__c,  Ordem_de_Trabalho__r.Oportunidade_Relacionada__c,
                		Ordem_de_Trabalho__r.Oportunidade_Relacionada__r.Contrato_de_Servico__r.RecordType.Name,
                		Ordem_de_Trabalho__r.ServiceContract.RecordType.Name,
                		Opportunity.Contrato_de_Servico__r.RecordType.Name
                FROM	Order
                WHERE	Id = :faturamento.Pedido__c
            ];
        }
                
		// Inspeciona associações
        if(oportunidade.Contrato_de_Servico__r.RecordType.Name == 'SERVIÇOS' ||
           pedido.Opportunity.Contrato_de_Servico__r.RecordType.Name == 'SERVIÇOS')
            faturamento.Procedencia__c = 'Contrato de Serviço';
            
        else if(oportunidade.Contrato_de_Servico__r.RecordType.Name == 'LOCAÇÃO' ||
               	pedido.Opportunity.Contrato_de_Servico__r.RecordType.Name == 'LOCAÇÃO')
            faturamento.Procedencia__c = 'Contrato de Locação';
        
        else if(ordem_de_trabalho.ServiceContract.RecordType.Name == 'SERVIÇOS' ||
                pedido.Ordem_de_Trabalho__r.ServiceContract.RecordType.Name == 'SERVIÇOS' ||
                ordem_de_trabalho.Oportunidade_Relacionada__r.Contrato_de_Servico__r.RecordType.Name == 'SERVIÇOS' || 
                pedido.Ordem_de_Trabalho__r.Oportunidade_Relacionada__r.Contrato_de_Servico__r.RecordType.Name == 'SERVIÇOS')
        	faturamento.Procedencia__c = 'Serviço Avulso (Contrato de Serviço)';
            
        else if(ordem_de_trabalho.ServiceContract.RecordType.Name == 'LOCAÇÃO' || 
                pedido.Ordem_de_Trabalho__r.ServiceContract.RecordType.Name == 'LOCAÇÃO' ||
                ordem_de_trabalho.Oportunidade_Relacionada__r.Contrato_de_Servico__r.RecordType.Name == 'LOCAÇÃO' || 
                pedido.Ordem_de_Trabalho__r.Oportunidade_Relacionada__r.Contrato_de_Servico__r.RecordType.Name == 'LOCAÇÃO')
            faturamento.Procedencia__c = 'Serviço Avulso (Contrato de Locação)';
            
        else if(ordem_de_trabalho.Oportunidade_Relacionada__c != null || 
                pedido.Ordem_de_Trabalho__r.Oportunidade_Relacionada__c != null ||
            	pedido.Opportunity.RecordType.Name == 'Serviço' ||
                oportunidade.RecordType.Name == 'Serviço' || 
                ordem_de_trabalho.Id != null ||
                pedido.Ordem_de_Trabalho__c != null)
            faturamento.Procedencia__c = 'Serviço Avulso';
        
        else if(pedido.Opportunity.RecordType.Name == 'Comercial' ||
            	oportunidade.RecordType.Name == 'Comercial')
            faturamento.Procedencia__c = 'Comercial';
        
        else if(pedido.Opportunity.RecordType.Name == 'Governo' ||
                pedido.Opportunity.RecordType.Name == 'Governo Estimativa' ||
            	oportunidade.RecordType.Name == 'Governo'  ||
                oportunidade.RecordType.Name == 'Governo Estimativa')
            faturamento.Procedencia__c = 'Governo';
        else 
            faturamento.Procedencia__c = null;
            
    }
    
}