force-app/main/default/objects/Contrato_de_Servi_o__c/Contrato_de_Servi_o__c.object-meta.xml
<CustomObject>
    <label>Contrato de Serviço</label>
    <nameField>
        <label>Nome do Contrato</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contratos de Serviços</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Contratos de Serviços</relationshipLabel>
    <relationshipName>Contratos_de_Servi_os</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Faturamento__c/Faturamento__c.object-meta.xml
<CustomObject>
    <label>Faturamento</label>
    <nameField>
        <label>Número</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Faturamentos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Faturamento__c/fields/Contrato_de_Servi_o__c.field-meta.xml
<CustomField>
    <fullName>Contrato_de_Servi_o__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>contrato (old)</label>
    <referenceTo>ServiceContract</referenceTo>
    <relationshipLabel>Faturamento</relationshipLabel>
    <relationshipName>Faturamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Faturamento__c/fields/Contrato_de_servico__c.field-meta.xml
<CustomField>
    <fullName>Contrato_de_servico__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato</label>
    <referenceTo>Contrato_de_Servi_o__c</referenceTo>
    <relationshipLabel>Faturamento</relationshipLabel>
    <relationshipName>Faturamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Faturamento__c/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Se Oportunidade:
- Contrato de Serviços Corretiva/Preventiva/Metrologia (Serviço+Peça)
- Assistência : Preventiva : Avulso Pacote (Serviço+Peça)
- Assistência : Metrologia : Avulso Pacote (Serviço)</description>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Pagamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contrato_de_Servico__c.field-meta.xml
<CustomField>
    <fullName>Contrato_de_Servico__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato de serviço (excluir)</label>
    <referenceTo>ServiceContract</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FatuLinkContrClass.cls
public class FatuLinkContrClass {
    
    public static Void FluxoInicial(Faturamento__c faturamento){
        if(faturamento.Oportunidade__c != null){
            Opportunity oportunidade = new Opportunity();
            oportunidade = ObtemOpp(faturamento.Oportunidade__c);
            if(oportunidade.Contrato_de_Servico__c != null){
                faturamento.Contrato_de_Servi_o__c = oportunidade.Contrato_de_Servico__c;
            }
        }
        else{
            faturamento.Contrato_de_Servi_o__c = null;
        }
    }
    
    public static Opportunity ObtemOpp(Id oportunidade_id){
    	Opportunity oportunidade = new Opportunity();
        oportunidade = [
            SELECT	Id, Contrato_de_servico__c
            FROM 	Opportunity
            WHERE	Id = :oportunidade_id
        ];
        return oportunidade;
    }
    
}