force-app/main/default/objects/WorkOrder/fields/Acess_rios_que_Acompanham_o_Equipamento__c.field-meta.xml
<CustomField>
    <fullName>Acess_rios_que_Acompanham_o_Equipamento__c</fullName>
    <label>Itens que Acompanham o Equipamento</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AVULSO</fullName>
            </value>
            <value>
                <fullName>CONTRATO DE LOCAÇÃO</fullName>
                <default>true</default>
                <label>CONTRATO DE LOCAÇÃO</label>
            </value>
            <value>
                <fullName>CONTRATO DE SERVIÇO</fullName>
            </value>
            <value>
                <fullName>GARANTIA DE FABRICA</fullName>
            </value>
            <value>
                <fullName>GARANTIA DE FÁBRICA</fullName>
            </value>
            <value>
                <fullName>GARANTIA DE SERVIÇO</fullName>
            </value>
            <value>
                <fullName>INSTALAÇÃO</fullName>
            </value>
            <value>
                <fullName>COMODATO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Data_Agendada_para_Servi_o__c.field-meta.xml
<CustomField>
    <fullName>Data_Agendada_para_Servi_o__c</fullName>
    <label>Data Agendada para Serviço</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Data_Prevista_para_o_Fim_do_Servi_o__c.field-meta.xml
<CustomField>
    <fullName>Data_Prevista_para_o_Fim_do_Servi_o__c</fullName>
    <label>Data Prevista para o Fim do Serviço</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Local_de_Atendimento__c.field-meta.xml
<CustomField>
    <fullName>Local_de_Atendimento__c</fullName>
    <label>Local de Atendimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INTERNO</fullName>
            </value>
            <value>
                <fullName>EXTERNO</fullName>
            </value>
            <value>
                <fullName>INTERNO E EXTERNO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/T_cnico_Respons_vel__c.field-meta.xml
<CustomField>
    <fullName>T_cnico_Respons_vel__c</fullName>
    <inlineHelpText>Esse campo foi descontinuado. Selecione o técnico no campo Técnico executor</inlineHelpText>
    <label>Responsável pela O.T (LEGADO)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ALEXANDRE AMARAL</fullName>
            </value>
            <value>
                <fullName>ALON ROCHA DA SILVA</fullName>
            </value>
            <value>
                <fullName>AMANDA JORDÃO</fullName>
            </value>
            <value>
                <fullName>ANA CAROLINE</fullName>
                <label>ANA CAROLINE TALAVERA</label>
            </value>
            <value>
                <fullName>ANDRE BRANDAO</fullName>
            </value>
            <value>
                <fullName>ANDRESSA PETRILLA</fullName>
            </value>
            <value>
                <fullName>ANTONIO LEVI</fullName>
            </value>
            <value>
                <fullName>BEATRIZ MARIANO</fullName>
            </value>
            <value>
                <fullName>BRUNO VINICIUS</fullName>
            </value>
            <value>
                <fullName>CAIO AUGUSTO</fullName>
            </value>
            <value>
                <fullName>CARLA BREVIGLIERO</fullName>
            </value>
            <value>
                <fullName>CARLOS ALBERTO SANTANA</fullName>
            </value>
            <value>
                <fullName>CASSIANO SILVA</fullName>
            </value>
            <value>
                <fullName>CLEITON RIBEIRO</fullName>
            </value>
            <value>
                <fullName>CYLL RODRIGUES</fullName>
            </value>
            <value>
                <fullName>DANIEL BORGES</fullName>
            </value>
            <value>
                <fullName>DANIEL NOGUEIRA DE OLIVEIRA</fullName>
            </value>
            <value>
                <fullName>DANILO GUIMARÃES</fullName>
            </value>
            <value>
                <fullName>DANILO SUSANO</fullName>
            </value>
            <value>
                <fullName>DAVID QUEIROZ</fullName>
            </value>
            <value>
                <fullName>DEIBLY ARAUJO</fullName>
            </value>
            <value>
                <fullName>DENY REYNER</fullName>
            </value>
            <value>
                <fullName>DIMAS RODRIGUES</fullName>
            </value>
            <value>
                <fullName>DOUGLAS CARVALHO</fullName>
            </value>
            <value>
                <fullName>DOUGLAS SANTOS</fullName>
            </value>
            <value>
                <fullName>EDER VIEIRA</fullName>
            </value>
            <value>
                <fullName>EDMUNDO BUBLIZ</fullName>
            </value>
            <value>
                <fullName>EDUARDO RIBEIRO</fullName>
            </value>
            <value>
                <fullName>EMERSON CÉSAR</fullName>
            </value>
            <value>
                <fullName>FHELIPE AUGUSTO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OtAgendaTeste.cls
@isTest(SeeAllData=true)
public class OtAgendaTeste {
    
    
    static testMethod void OtAgendaTesteGeral1(){ 
        WorkOrder ot = new WorkOrder();
        ot = [
            SELECT	AccountId, AssetId, Acess_rios_que_Acompanham_o_Equipamento__c, ContactId, Subject, Data_Agendada_para_Servi_o__c, Data_Prevista_para_o_Fim_do_Servi_o__c, Categoria__c, Status, Priority, T_cnico_Respons_vel__c, Local_de_Atendimento__c, Description, RecordTypeId
           	FROM	WorkOrder
            //WHERE   Id = '0WO0q00000003Wi'
            WHERE	Id = '0WO5A000000XezU'
        ];        

        test.startTest();       
            ot.Status = 'AGUARDANDO ATENDIMENTO';
            update ot;
        test.stopTest();
    }
    
    
    static testMethod void OtAgendaTesteGeral2(){ 
        WorkOrder ot = new WorkOrder();
        ot = [
            SELECT	AccountId, AssetId, Acess_rios_que_Acompanham_o_Equipamento__c, ContactId, Subject, Data_Agendada_para_Servi_o__c, Data_Prevista_para_o_Fim_do_Servi_o__c, Categoria__c, Status, Priority, T_cnico_Respons_vel__c, Local_de_Atendimento__c, Description, RecordTypeId
           	FROM	WorkOrder
            //WHERE   Id = '0WO0q0000008iB1'
            WHERE	Id = '0WO5A000000XfDv'
        ];        
        
        test.startTest();       
            ot.Data_Prevista_para_o_Fim_do_Servi_o__c += 1;
            update ot;
        test.stopTest();
    }
    
    static testMethod void OtAgendaTesteGeral3(){ 
        WorkOrder ot = new WorkOrder();
        ot = [
            SELECT	AccountId, AssetId, Acess_rios_que_Acompanham_o_Equipamento__c, ContactId, Subject, Data_Agendada_para_Servi_o__c, Data_Prevista_para_o_Fim_do_Servi_o__c, Categoria__c, Status, Priority, T_cnico_Respons_vel__c, Local_de_Atendimento__c, Description, RecordTypeId
           	FROM	WorkOrder
            //WHERE   Id = '0WO0q0000008iB1'
            WHERE	Id = '0WO5A000000XfDv'
        ];        
        
        test.startTest();       
            ot.OwnerId = '00531000007iKqT';
            update ot;
        test.stopTest();
    }
    

}