force-app/main/default/objects/WorkOrder/fields/Acess_rios_que_Acompanham_o_Equipamento__c.field-meta.xml
<CustomField>
    <fullName>Acess_rios_que_Acompanham_o_Equipamento__c</fullName>
    <label>Itens que Acompanham o Equipamento</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AVULSO</fullName>
            </value>
            <value>
                <fullName>CONTRATO DE LOCAÇÃO</fullName>
                <default>true</default>
                <label>CONTRATO DE LOCAÇÃO</label>
            </value>
            <value>
                <fullName>CONTRATO DE SERVIÇO</fullName>
            </value>
            <value>
                <fullName>GARANTIA DE FABRICA</fullName>
            </value>
            <value>
                <fullName>GARANTIA DE FÁBRICA</fullName>
            </value>
            <value>
                <fullName>GARANTIA DE SERVIÇO</fullName>
            </value>
            <value>
                <fullName>INSTALAÇÃO</fullName>
            </value>
            <value>
                <fullName>COMODATO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Contrato_de_Servi_o_Relacionado_v2__c.field-meta.xml
<CustomField>
    <fullName>Contrato_de_Servi_o_Relacionado_v2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato de Serviço Relacionado v2</label>
    <referenceTo>Contrato_de_Servi_o__c</referenceTo>
    <relationshipLabel>Ordens de trabalho</relationshipLabel>
    <relationshipName>Ordens_de_trabalho</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Data_Agendada_para_Servi_o__c.field-meta.xml
<CustomField>
    <fullName>Data_Agendada_para_Servi_o__c</fullName>
    <label>Data Agendada para Serviço</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Data_Prevista_para_o_Fim_do_Servi_o__c.field-meta.xml
<CustomField>
    <fullName>Data_Prevista_para_o_Fim_do_Servi_o__c</fullName>
    <label>Data Prevista para o Fim do Serviço</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Equipamento_Pertence_ao__c.field-meta.xml
<CustomField>
    <fullName>Equipamento_Pertence_ao__c</fullName>
    <label>Equipamento Pertence ao:</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Faturamento_Feito2__c.field-meta.xml
<CustomField>
    <fullName>Faturamento_Feito2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Faturado por (empresa)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Faturamentos Feitos (de ordens de trabalho)</relationshipLabel>
    <relationshipName>Ordens_de_trabalho</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Ignorar_fluxos__c.field-meta.xml
<CustomField>
    <fullName>Ignorar_fluxos__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ignorar fluxos</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Local_de_Atendimento__c.field-meta.xml
<CustomField>
    <fullName>Local_de_Atendimento__c</fullName>
    <label>Local de Atendimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INTERNO</fullName>
            </value>
            <value>
                <fullName>EXTERNO</fullName>
            </value>
            <value>
                <fullName>INTERNO E EXTERNO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/T_cnico_Respons_vel__c.field-meta.xml
<CustomField>
    <fullName>T_cnico_Respons_vel__c</fullName>
    <inlineHelpText>Esse campo foi descontinuado. Selecione o técnico no campo Técnico executor</inlineHelpText>
    <label>Responsável pela O.T (LEGADO)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ALEXANDRE AMARAL</fullName>
            </value>
            <value>
                <fullName>ALON ROCHA DA SILVA</fullName>
            </value>
            <value>
                <fullName>AMANDA JORDÃO</fullName>
            </value>
            <value>
                <fullName>ANA CAROLINE</fullName>
                <label>ANA CAROLINE TALAVERA</label>
            </value>
            <value>
                <fullName>ANDRE BRANDAO</fullName>
            </value>
            <value>
                <fullName>ANDRESSA PETRILLA</fullName>
            </value>
            <value>
                <fullName>ANTONIO LEVI</fullName>
            </value>
            <value>
                <fullName>BEATRIZ MARIANO</fullName>
            </value>
            <value>
                <fullName>BRUNO VINICIUS</fullName>
            </value>
            <value>
                <fullName>CAIO AUGUSTO</fullName>
            </value>
            <value>
                <fullName>CARLA BREVIGLIERO</fullName>
            </value>
            <value>
                <fullName>CARLOS ALBERTO SANTANA</fullName>
            </value>
            <value>
                <fullName>CASSIANO SILVA</fullName>
            </value>
            <value>
                <fullName>CLEITON RIBEIRO</fullName>
            </value>
            <value>
                <fullName>CYLL RODRIGUES</fullName>
            </value>
            <value>
                <fullName>DANIEL BORGES</fullName>
            </value>
            <value>
                <fullName>DANIEL NOGUEIRA DE OLIVEIRA</fullName>
            </value>
            <value>
                <fullName>DANILO GUIMARÃES</fullName>
            </value>
            <value>
                <fullName>DANILO SUSANO</fullName>
            </value>
            <value>
                <fullName>DAVID QUEIROZ</fullName>
            </value>
            <value>
                <fullName>DEIBLY ARAUJO</fullName>
            </value>
            <value>
                <fullName>DENY REYNER</fullName>
            </value>
            <value>
                <fullName>DIMAS RODRIGUES</fullName>
            </value>
            <value>
                <fullName>DOUGLAS CARVALHO</fullName>
            </value>
            <value>
                <fullName>DOUGLAS SANTOS</fullName>
            </value>
            <value>
                <fullName>EDER VIEIRA</fullName>
            </value>
            <value>
                <fullName>EDMUNDO BUBLIZ</fullName>
            </value>
            <value>
                <fullName>EDUARDO RIBEIRO</fullName>
            </value>
            <value>
                <fullName>EMERSON CÉSAR</fullName>
            </value>
            <value>
                <fullName>FHELIPE AUGUSTO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Tecnico_executor__c.field-meta.xml
<CustomField>
    <fullName>Tecnico_executor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Técnico executor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Account.Id</field>
            <operation>equals</operation>
            <value>001i00000085QYbAAM</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Ordens de trabalho</relationshipLabel>
    <relationshipName>Ordens_de_trabalho</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GeraOTs.cls
public class GeraOTs {
    @AuraEnabled 
    public static string gerar(string conta, string faturamento, string local, string contato, string tecnico, string responsavel, string status, string tipoRegistro, string categoria, string assunto, string pertence, string SN, string contrato, string itensAcompanham, string problemaRelatado, dateTime dataPrevista, dateTime dataAgendada){
        
        List<String> lstString = SN.split(','); //Separa cada SN e adiciona em Lista
        List<Asset> ativos = [SELECT ID FROM Asset WHERE SerialNumber in : lstString];

        // User usuario = [SELECT ID, ContactId FROM USER WHERE ID = : responsavel];
        // Contact contatoOwner = [SELECT ID FROM Contact WHERE ID =: usuario.ContactId];
        
        List<WorkOrder> OTS = new List<WorkOrder>();
        
        Integer quantidade = 0;

        //Cria a OT para cada número de série
        for(Asset ativo : ativos){
            WorkOrder ot = new WorkOrder();
            ot.AssetId = ativo.Id;
            ot.Ignorar_fluxos__c = true;
            ot.AccountId = conta;
            // ot.Tecnico_executor__c = contatoOwner.Id;
            ot.Tecnico_executor__c = responsavel; //ADICIONADA
            ot.ContactId = contato;
            // ot.T_cnico_Respons_vel__c = tecnico;
            // ot.OwnerId = responsavel;
            ot.Status = status;
            ot.RecordTypeId = tipoRegistro;
            ot.Categoria__c = categoria;
            ot.Subject = assunto;
            ot.Equipamento_Pertence_ao__c = pertence;
            ot.Faturamento_feito2__c = faturamento;
            ot.Local_de_Atendimento__c = local;
            ot.Data_Agendada_para_Servi_o__c = dataAgendada;
            ot.Data_Prevista_para_o_Fim_do_Servi_o__c = dataPrevista;
            ot.Acess_rios_que_Acompanham_o_Equipamento__c = itensAcompanham;
            ot.Description = problemaRelatado;
            if(contrato != ''){
            ot.Contrato_de_Servi_o_Relacionado_v2__c = contrato;
            }
            OTS.add(ot);
            quantidade ++;
        }
        try{
            insert OTS;
            return('Foram criadas ' + quantidade + ' OTs com sucesso.');
        }
        catch(Exception e){
            return(e.getMessage());
        }
    }
}