force-app/main/default/objects/WorkOrder/fields/Acess_rios_que_Acompanham_o_Equipamento__c.field-meta.xml
<CustomField>
    <fullName>Acess_rios_que_Acompanham_o_Equipamento__c</fullName>
    <label>Itens que Acompanham o Equipamento</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AVULSO</fullName>
            </value>
            <value>
                <fullName>CONTRATO DE LOCAÇÃO</fullName>
                <default>true</default>
                <label>CONTRATO DE LOCAÇÃO</label>
            </value>
            <value>
                <fullName>CONTRATO DE SERVIÇO</fullName>
            </value>
            <value>
                <fullName>GARANTIA DE FABRICA</fullName>
            </value>
            <value>
                <fullName>GARANTIA DE FÁBRICA</fullName>
            </value>
            <value>
                <fullName>GARANTIA DE SERVIÇO</fullName>
            </value>
            <value>
                <fullName>INSTALAÇÃO</fullName>
            </value>
            <value>
                <fullName>COMODATO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Data_Agendada_para_Servi_o__c.field-meta.xml
<CustomField>
    <fullName>Data_Agendada_para_Servi_o__c</fullName>
    <label>Data Agendada para Serviço</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Data_Prevista_para_o_Fim_do_Servi_o__c.field-meta.xml
<CustomField>
    <fullName>Data_Prevista_para_o_Fim_do_Servi_o__c</fullName>
    <label>Data Prevista para o Fim do Serviço</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Local_de_Atendimento__c.field-meta.xml
<CustomField>
    <fullName>Local_de_Atendimento__c</fullName>
    <label>Local de Atendimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INTERNO</fullName>
            </value>
            <value>
                <fullName>EXTERNO</fullName>
            </value>
            <value>
                <fullName>INTERNO E EXTERNO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Or_amento_Re__c.field-meta.xml
<CustomField>
    <fullName>Or_amento_Re__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Orçamento Realizado?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/T_cnico_Respons_vel__c.field-meta.xml
<CustomField>
    <fullName>T_cnico_Respons_vel__c</fullName>
    <inlineHelpText>Esse campo foi descontinuado. Selecione o técnico no campo Técnico executor</inlineHelpText>
    <label>Responsável pela O.T (LEGADO)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ALEXANDRE AMARAL</fullName>
            </value>
            <value>
                <fullName>ALON ROCHA DA SILVA</fullName>
            </value>
            <value>
                <fullName>AMANDA JORDÃO</fullName>
            </value>
            <value>
                <fullName>ANA CAROLINE</fullName>
                <label>ANA CAROLINE TALAVERA</label>
            </value>
            <value>
                <fullName>ANDRE BRANDAO</fullName>
            </value>
            <value>
                <fullName>ANDRESSA PETRILLA</fullName>
            </value>
            <value>
                <fullName>ANTONIO LEVI</fullName>
            </value>
            <value>
                <fullName>BEATRIZ MARIANO</fullName>
            </value>
            <value>
                <fullName>BRUNO VINICIUS</fullName>
            </value>
            <value>
                <fullName>CAIO AUGUSTO</fullName>
            </value>
            <value>
                <fullName>CARLA BREVIGLIERO</fullName>
            </value>
            <value>
                <fullName>CARLOS ALBERTO SANTANA</fullName>
            </value>
            <value>
                <fullName>CASSIANO SILVA</fullName>
            </value>
            <value>
                <fullName>CLEITON RIBEIRO</fullName>
            </value>
            <value>
                <fullName>CYLL RODRIGUES</fullName>
            </value>
            <value>
                <fullName>DANIEL BORGES</fullName>
            </value>
            <value>
                <fullName>DANIEL NOGUEIRA DE OLIVEIRA</fullName>
            </value>
            <value>
                <fullName>DANILO GUIMARÃES</fullName>
            </value>
            <value>
                <fullName>DANILO SUSANO</fullName>
            </value>
            <value>
                <fullName>DAVID QUEIROZ</fullName>
            </value>
            <value>
                <fullName>DEIBLY ARAUJO</fullName>
            </value>
            <value>
                <fullName>DENY REYNER</fullName>
            </value>
            <value>
                <fullName>DIMAS RODRIGUES</fullName>
            </value>
            <value>
                <fullName>DOUGLAS CARVALHO</fullName>
            </value>
            <value>
                <fullName>DOUGLAS SANTOS</fullName>
            </value>
            <value>
                <fullName>EDER VIEIRA</fullName>
            </value>
            <value>
                <fullName>EDMUNDO BUBLIZ</fullName>
            </value>
            <value>
                <fullName>EDUARDO RIBEIRO</fullName>
            </value>
            <value>
                <fullName>EMERSON CÉSAR</fullName>
            </value>
            <value>
                <fullName>FHELIPE AUGUSTO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Tipo_de_Servi_o__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Servi_o__c</fullName>
    <label>Tipo de Serviço</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CALIBRAÇÃO</fullName>
            </value>
            <value>
                <fullName>ENSAIO DE SEGURANÇA ELÉTRICA</fullName>
            </value>
            <value>
                <fullName>ENTREGA</fullName>
            </value>
            <value>
                <fullName>INSTALAÇÃO</fullName>
            </value>
            <value>
                <fullName>MANUTENÇÃO CORRETIVA</fullName>
            </value>
            <value>
                <fullName>MANUTENÇÃO PREVENTIVA</fullName>
            </value>
            <value>
                <fullName>OUTROS</fullName>
            </value>
            <value>
                <fullName>QUALIFICAÇÃO</fullName>
            </value>
            <value>
                <fullName>VERIFICAÇÃO FUNCIONAL</fullName>
            </value>
            <value>
                <fullName>DEMONSTRAÇÃO DE PRODUTOS</fullName>
            </value>
            <value>
                <fullName>TREINAMENTO DE ATIVOS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/X4_Manuten_o_Realizada__c.field-meta.xml
<CustomField>
    <fullName>X4_Manuten_o_Realizada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Manutenção Realizada?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/OtAgendaTeste2.cls
@isTest(SeeAllData=true)
public class OtAgendaTeste2 {

    static testMethod void OtAgendaTesteGeral3(){ 
		test.startTest();
        
            WorkOrder ordem = new WorkOrder(
                RECORDTYPEID =                                '01231000000tb6AAAQ',
                ACCOUNTID =                                   '0015A00001uB5OMQA0', 		// prod=0015A00001uB5OMQA0 dev=0010q000002LDCd
                CONTACTID =                                   '0035A00003DHWrGQAX',			// prod=0035A00003DHWrGQAX dev=0030q000001x1YN
                //SERVICECONTRACTID =                         '8105A0000032oYdQAI',
                ASSETID =                                     '02i5A000007zqPoQAI',			// prod=02i5A000007zqPoQAI dev=02i0q000000Dqa1
                COUNTRY =                                     'Brasil',
                COUNTRYCODE =                                 'BR',
                DESCRIPTION =                                 'nali liga (testeee)',
                SUBJECT =                                     '### teste insert ###',
                STATUS =                                      'AGUARDANDO ATENDIMENTO',
                PRIORITY =                                    'MÉDIA',
                DURATIONTYPE =                                'Hours',
                TIPO_DE_SERVI_O__C =                          'MANUTENÇÃO CORRETIVA',
                T_CNICO_RESPONS_VEL__C =                      'CLEITON RIBEIRO',
                OR_AMENTO_RE__C =                             false,
                X4_MANUTEN_O_REALIZADA__C =                   false,
                ACESS_RIOS_QUE_ACOMPANHAM_O_EQUIPAMENTO__C =  'nenhum',
                LOCAL_DE_ATENDIMENTO__C =                     'EXTERNO',
                CATEGORIA__C =                                'AVULSO',
                STARTDATE =                                   System.now(),
                DATA_AGENDADA_PARA_SERVI_O__C =               System.now(),
                DATA_PREVISTA_PARA_O_FIM_DO_SERVI_O__C =      System.now()+2
            );
        
               
            insert ordem;
        
        test.stopTest();
    }
    
    
}