force-app/main/default/objects/WorkOrder/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AVULSO</fullName>
            </value>
            <value>
                <fullName>CONTRATO DE LOCAÇÃO</fullName>
                <default>true</default>
                <label>CONTRATO DE LOCAÇÃO</label>
            </value>
            <value>
                <fullName>CONTRATO DE SERVIÇO</fullName>
            </value>
            <value>
                <fullName>GARANTIA DE FABRICA</fullName>
            </value>
            <value>
                <fullName>GARANTIA DE FÁBRICA</fullName>
            </value>
            <value>
                <fullName>GARANTIA DE SERVIÇO</fullName>
            </value>
            <value>
                <fullName>INSTALAÇÃO</fullName>
            </value>
            <value>
                <fullName>COMODATO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Data_Agendada_para_Servi_o__c.field-meta.xml
<CustomField>
    <fullName>Data_Agendada_para_Servi_o__c</fullName>
    <label>Data Agendada para Serviço</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Data_Entrada_Equipamento__c.field-meta.xml
<CustomField>
    <fullName>Data_Entrada_Equipamento__c</fullName>
    <description>Data de Entrada do equipamento.</description>
    <inlineHelpText>Data de Entrada do equipamento.</inlineHelpText>
    <label>Data Entrada Equipamento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Data_Prevista_para_o_Fim_do_Servi_o__c.field-meta.xml
<CustomField>
    <fullName>Data_Prevista_para_o_Fim_do_Servi_o__c</fullName>
    <label>Data Prevista para o Fim do Serviço</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Faturamento_Feito2__c.field-meta.xml
<CustomField>
    <fullName>Faturamento_Feito2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Faturado por (empresa)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Faturamentos Feitos (de ordens de trabalho)</relationshipLabel>
    <relationshipName>Ordens_de_trabalho</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Local_de_Atendimento__c.field-meta.xml
<CustomField>
    <fullName>Local_de_Atendimento__c</fullName>
    <label>Local de Atendimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INTERNO</fullName>
            </value>
            <value>
                <fullName>EXTERNO</fullName>
            </value>
            <value>
                <fullName>INTERNO E EXTERNO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/T_cnico_Respons_vel__c.field-meta.xml
<CustomField>
    <fullName>T_cnico_Respons_vel__c</fullName>
    <inlineHelpText>Esse campo foi descontinuado. Selecione o técnico no campo Técnico executor</inlineHelpText>
    <label>Responsável pela O.T (LEGADO)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ALEXANDRE AMARAL</fullName>
            </value>
            <value>
                <fullName>ALON ROCHA DA SILVA</fullName>
            </value>
            <value>
                <fullName>AMANDA JORDÃO</fullName>
            </value>
            <value>
                <fullName>ANA CAROLINE</fullName>
                <label>ANA CAROLINE TALAVERA</label>
            </value>
            <value>
                <fullName>ANDRE BRANDAO</fullName>
            </value>
            <value>
                <fullName>ANDRESSA PETRILLA</fullName>
            </value>
            <value>
                <fullName>ANTONIO LEVI</fullName>
            </value>
            <value>
                <fullName>BEATRIZ MARIANO</fullName>
            </value>
            <value>
                <fullName>BRUNO VINICIUS</fullName>
            </value>
            <value>
                <fullName>CAIO AUGUSTO</fullName>
            </value>
            <value>
                <fullName>CARLA BREVIGLIERO</fullName>
            </value>
            <value>
                <fullName>CARLOS ALBERTO SANTANA</fullName>
            </value>
            <value>
                <fullName>CASSIANO SILVA</fullName>
            </value>
            <value>
                <fullName>CLEITON RIBEIRO</fullName>
            </value>
            <value>
                <fullName>CYLL RODRIGUES</fullName>
            </value>
            <value>
                <fullName>DANIEL BORGES</fullName>
            </value>
            <value>
                <fullName>DANIEL NOGUEIRA DE OLIVEIRA</fullName>
            </value>
            <value>
                <fullName>DANILO GUIMARÃES</fullName>
            </value>
            <value>
                <fullName>DANILO SUSANO</fullName>
            </value>
            <value>
                <fullName>DAVID QUEIROZ</fullName>
            </value>
            <value>
                <fullName>DEIBLY ARAUJO</fullName>
            </value>
            <value>
                <fullName>DENY REYNER</fullName>
            </value>
            <value>
                <fullName>DIMAS RODRIGUES</fullName>
            </value>
            <value>
                <fullName>DOUGLAS CARVALHO</fullName>
            </value>
            <value>
                <fullName>DOUGLAS SANTOS</fullName>
            </value>
            <value>
                <fullName>EDER VIEIRA</fullName>
            </value>
            <value>
                <fullName>EDMUNDO BUBLIZ</fullName>
            </value>
            <value>
                <fullName>EDUARDO RIBEIRO</fullName>
            </value>
            <value>
                <fullName>EMERSON CÉSAR</fullName>
            </value>
            <value>
                <fullName>FHELIPE AUGUSTO</fullName>
            </value>
            <value>
                <fullName>TATIANE ALVES</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OrdemDeTrabalhoTeste.cls
@isTest(seeAllData=true)
public class OrdemDeTrabalhoTeste { 
	
    static testMethod void Teste1(){ 
        test.startTest();
		
		WorkOrder ordem_de_trabalho = new WorkOrder(
			AccountId = '001i00000087gnb',
			// ContactId = '00331000038okC5',
			Faturamento_Feito2__c = '001i00000085QYb',
			AssetId = '02i6e00000N7iqu',
			Data_Entrada_Equipamento__c = System.Today()-2,
			Subject = 'ot de teste',
			CreatedDate = System.Today(),
			Data_Agendada_para_Servi_o__c = System.Now()+1,
			Data_Prevista_para_o_Fim_do_Servi_o__c = System.Now()+2,
			RecordTypeId = '01231000000tb5gAAA',
			Categoria__c = 'AVULSO',
			Status = 'AGENDADO',
			Priority = 'MÉDIA',
			T_cnico_Respons_vel__c = 'TATIANE ALVES',
			Local_de_Atendimento__c = 'INTERNO'
		);
		insert ordem_de_trabalho;
        
        test.stopTest();
    }
	
    static testMethod void Teste2(){ 
        test.startTest();
		
		WorkOrder ordem_de_trabalho = new WorkOrder();
		ordem_de_trabalho = [select id from workorder where id = '0WO5A000002CmLV'];
		ordem_de_trabalho.ContactId = null;
		update ordem_de_trabalho;
        
        test.stopTest();
    }
	
    static testMethod void Teste3(){ 
        test.startTest();
		
		WorkOrder ordem_de_trabalho = new WorkOrder();
		ordem_de_trabalho = [select id from workorder where id = '0WO5A000000XfNg'];
		delete ordem_de_trabalho;
        
        test.stopTest();
    }
	
}