force-app/main/default/objects/WorkOrder/fields/Data_Agendada_para_Servi_o__c.field-meta.xml
<CustomField>
    <fullName>Data_Agendada_para_Servi_o__c</fullName>
    <label>Data Agendada para Serviço</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Data_Prevista_para_o_Fim_do_Servi_o__c.field-meta.xml
<CustomField>
    <fullName>Data_Prevista_para_o_Fim_do_Servi_o__c</fullName>
    <label>Data Prevista para o Fim do Serviço</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Local_de_Atendimento__c.field-meta.xml
<CustomField>
    <fullName>Local_de_Atendimento__c</fullName>
    <label>Local de Atendimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INTERNO</fullName>
            </value>
            <value>
                <fullName>EXTERNO</fullName>
            </value>
            <value>
                <fullName>INTERNO E EXTERNO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OtAgendaClass.cls
public with sharing class OtAgendaClass {
    
    public static void InsereCompromisso(WorkOrder OrdemTrabalho){
        Event compromisso = new Event(
            RECORDTYPEID = '01231000000tb28AAA',
            WHATID = OrdemTrabalho.Id,
            SUBJECT = 'OT ' + OrdemTrabalho.WorkOrderNumber + ': ' + OrdemTrabalho.Status,
            LOCATION = OrdemTrabalho.Local_de_Atendimento__c,
            ISALLDAYEVENT = false,
            ACTIVITYDATETIME = OrdemTrabalho.Data_Agendada_para_Servi_o__c,
            STARTDATETIME = OrdemTrabalho.Data_Agendada_para_Servi_o__c,
            ENDDATETIME = OrdemTrabalho.Data_Prevista_para_o_Fim_do_Servi_o__c,	
            DESCRIPTION = 'OT ' + OrdemTrabalho.WorkOrderNumber + ': ' + OrdemTrabalho.Status,
            OWNERID = OrdemTrabalho.OwnerId,
            TYPE = 'Atendimento de O.T',
            ISPRIVATE = false,
            SHOWAS = 'Busy',
            ISVISIBLEINSELFSERVICE = false,
            ISRECURRENCE = false,
            REMINDERDATETIME = OrdemTrabalho.Data_Agendada_para_Servi_o__c.addMinutes(-30),
            ISREMINDERSET = true,
            EVENTSUBTYPE = 'Event' 
        );
        insert compromisso;
    }
    
    public static void AtualizaCompromisso(WorkOrder OrdemTrabalho, Event Compromisso){
        Compromisso.ActivityDateTime = OrdemTrabalho.Data_Agendada_para_Servi_o__c;
        Compromisso.StartDateTime = OrdemTrabalho.Data_Agendada_para_Servi_o__c;
        Compromisso.EndDateTime = OrdemTrabalho.Data_Prevista_para_o_Fim_do_Servi_o__c;
        Compromisso.ReminderDateTime = OrdemTrabalho.Data_Agendada_para_Servi_o__c.addMinutes(-30);
        
        Update Compromisso;
    }
    
    
}