force-app/main/default/objects/MktMidia__c/MktMidia__c.object-meta.xml
<CustomObject>
    <label>Mídia</label>
    <nameField>
        <label>Título</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mídias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MktMidia__c/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Categoria</label>
    <referenceTo>MktCategoria__c</referenceTo>
    <relationshipLabel>Mídias</relationshipLabel>
    <relationshipName>Midias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MktMidia__c/fields/Extensao__c.field-meta.xml
<CustomField>
    <fullName>Extensao__c</fullName>
    <label>Extensao</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/MktMidia__c/fields/Formato__c.field-meta.xml
<CustomField>
    <fullName>Formato__c</fullName>
    <label>Formato</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/MktMidia__c/fields/Icone_url__c.field-meta.xml
<CustomField>
    <fullName>Icone_url__c</fullName>
    <label>Icone</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/MktMidia__c/fields/Interno__c.field-meta.xml
<CustomField>
    <fullName>Interno__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Interno</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MktMidia__c/fields/Quantidade_de_anexos__c.field-meta.xml
<CustomField>
    <fullName>Quantidade_de_anexos__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quantidade de anexos</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MktMidia__c/fields/Tamanho__c.field-meta.xml
<CustomField>
    <fullName>Tamanho__c</fullName>
    <label>Tamanho</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/MktMidia__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Atestado de Capacidade Técnica</fullName>
            </value>
            <value>
                <fullName>Catálogo</fullName>
            </value>
            <value>
                <fullName>Documentação Geral</fullName>
            </value>
            <value>
                <fullName>Especificação</fullName>
            </value>
            <value>
                <fullName>Estudo</fullName>
            </value>
            <value>
                <fullName>Extensão</fullName>
            </value>
            <value>
                <fullName>Imagem</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Registro na Anvisa</fullName>
            </value>
            <value>
                <fullName>Vídeo</fullName>
            </value>
            <value>
                <fullName>Manual do Usuário</fullName>
            </value>
            <value>
                <fullName>Acessório</fullName>
                <isActive>false</isActive>
                <label>Acessório</label>
            </value>
            <value>
                <fullName>Módulo</fullName>
                <isActive>false</isActive>
                <label>Módulo</label>
            </value>
            <value>
                <fullName>Transdutor</fullName>
                <isActive>false</isActive>
                <label>Transdutor</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MktMidia__c/fields/URL_do_Arquivo__c.field-meta.xml
<CustomField>
    <fullName>URL_do_Arquivo__c</fullName>
    <label>Download URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/MidiaTeste.cls
@isTest(seeAllData=true)
private class MidiaTeste {
	
    @isTest 
	static void TesteMidia(){
		System.Debug(LoggingLevel.INFO,'TesteMidia inicio');
		
		MktMidia__c midia = new MktMidia__c(
			Categoria__c = 'a1RU4000000q05ZMAQ',
			Tipo__c = 'Catálogo',
			Name = 'teste1'
		);
		
		// insert : excessão arquivo com link + propriedades manual
		try {
			midia.Tamanho__c='10 MB';
			midia.Formato__c='PDF';
			midia.Extensao__c='pdf';
			midia.Icone_url__c='https://www.google.com';
			insert midia;
		} catch(Exception error) {
			System.assert(error.getMessage().contains('O tipo selecionado'));
		}
		
		// midia : insert normal
		midia.Tamanho__c=null;
		midia.Formato__c=null;
		midia.Extensao__c=null;
		midia.Icone_url__c=null;
		insert midia;
		
		// midia : update normal
		midia.name = 'teste2';
		update midia;
		

		// update : excessão video com anexo
		try {
			midia.Tipo__c='Vídeo';
			midia.Quantidade_de_anexos__c=1;
			update midia;
		} catch(Exception error) {
			System.assert(error.getMessage().contains('O tipo selecionado '));
		}
		midia.Tipo__c='Catálogo';
		midia.Quantidade_de_anexos__c=0;
		
		// update : excessão video sem link e propriedades
		try {
			midia.Tipo__c='Vídeo';
			update midia;
		} catch(Exception error) {
			System.assert(error.getMessage().contains('O tipo selecionado'));
		}
		midia.Tipo__c='Catálogo';
		
		// update : excessão arquivo com link + propriedades manual
		try {
			midia.URL_do_Arquivo__c='https://www.google.com';
			midia.Tamanho__c='10 MB';
			midia.Formato__c='PDF';
			midia.Extensao__c='pdf';
			midia.Icone_url__c='https://www.google.com';
			update midia;
		} catch(Exception error) {
			System.assert(error.getMessage().contains('O tipo selecionado '));
		}
		midia.URL_do_Arquivo__c=null;
		midia.Tamanho__c=null;
		midia.Formato__c=null;
		midia.Extensao__c=null;
		midia.Icone_url__c=null;
		
		// update : operações com imagens
		midia.Interno__c=true;
		midia.Icone_url__c='https://hospcom--douglas--c.cs41.content.force.com/servlet/servlet.ImageServer?id=0155A000009yGk2&oid=00D550000000Qcs&lastMod=1545321940000';
		update midia;
		
		// link : delete
		delete midia;
		
		System.Debug(LoggingLevel.INFO,'TesteMidia fim');
	}
	
    @isTest 
	static void TesteLink(){
		System.Debug(LoggingLevel.INFO,'TesteLink inicio');
		
		// midia : insert
		MktMidia__c midia = new MktMidia__c(
			Categoria__c = 'a1RU4000000q05ZMAQ',
			Tipo__c = 'Catálogo',
			Name = 'test3'
		);
		insert midia;
		
		// link : insert 
		ContentDocumentLink link = new ContentDocumentLink(
			LinkedEntityId = midia.Id, 
			ContentDocumentId = '0695A000004xPsj',
			Visibility = 'AllUsers',
			ShareType = 'V'
		);
		insert link;
		
		// teste botão
		ApexPages.StandardController controlador = new ApexPages.StandardController(midia);
		LinkMiniatura botao = new LinkMiniatura(controlador);
		botao.GerarMiniatura();
		
		
		// link : delete
		delete link;
		
		System.Debug(LoggingLevel.INFO,'TesteLink fim');
	}	
	
}