force-app/main/default/objects/MktCategoria__c/MktCategoria__c.object-meta.xml
<CustomObject>
    <label>Categoria</label>
    <nameField>
        <label>Categoria</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categorias</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MktCategoria__c/fields/Categoria_Pai__c.field-meta.xml
<CustomField>
    <fullName>Categoria_Pai__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Categoria Pai</label>
    <referenceTo>MktCategoria__c</referenceTo>
    <relationshipLabel>Sub Categorias</relationshipLabel>
    <relationshipName>Categorias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MktParte__c/MktParte__c.object-meta.xml
<CustomObject>
    <label>Parte</label>
    <nameField>
        <displayFormat>PART{0}</displayFormat>
        <label>Identificação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MktParte__c/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Categoria</label>
    <referenceTo>MktCategoria__c</referenceTo>
    <relationshipLabel>Partes</relationshipLabel>
    <relationshipName>Partes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MktParte__c/fields/Categoria_pai__c.field-meta.xml
<CustomField>
    <fullName>Categoria_pai__c</fullName>
    <formula>Categoria__r.Categoria_Pai__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Categoria pai</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MktParte__c/fields/Modelo__c.field-meta.xml
<CustomField>
    <fullName>Modelo__c</fullName>
    <formula>Parte__r.Modelo__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Modelo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MktParte__c/fields/Nome__c.field-meta.xml
<CustomField>
    <fullName>Nome__c</fullName>
    <formula>Parte__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nome (Produto)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MktParte__c/fields/Ordem__c.field-meta.xml
<CustomField>
    <fullName>Ordem__c</fullName>
    <label>Ordem</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MktParte__c/fields/Parte__c.field-meta.xml
<CustomField>
    <fullName>Parte__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parte</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Product2.Tipo_do_Produto__c</field>
            <operation>equals</operation>
            <value>ACESSÓRIO, PEÇA</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Partes</relationshipLabel>
    <relationshipName>Partes_de_Produto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Modelo__c.field-meta.xml
<CustomField>
    <fullName>Modelo__c</fullName>
    <label>Modelo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Tipo_do_Produto__c.field-meta.xml
<CustomField>
    <fullName>Tipo_do_Produto__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CONSUMÍVEL</fullName>
            </value>
            <value>
                <fullName>EQUIPAMENTO</fullName>
            </value>
            <value>
                <fullName>FERRAMENTA</fullName>
            </value>
            <value>
                <fullName>IMPLANTE</fullName>
            </value>
            <value>
                <fullName>INSTRUMENTAL</fullName>
            </value>
            <value>
                <fullName>INSUMO</fullName>
            </value>
            <value>
                <fullName>KIT SERVIÇO</fullName>
            </value>
            <value>
                <fullName>MÓDULO</fullName>
            </value>
            <value>
                <fullName>MOVEIS</fullName>
            </value>
            <value>
                <fullName>OPCIONAL</fullName>
            </value>
            <value>
                <fullName>PEÇA</fullName>
            </value>
            <value>
                <fullName>SERVIÇO</fullName>
            </value>
            <value>
                <fullName>SET CIRURGICO</fullName>
            </value>
            <value>
                <fullName>SOFTWARE</fullName>
            </value>
            <value>
                <fullName>ACESSÓRIO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MktOrdeCate.cls
public with sharing class MktOrdeCate{
    
    Public String				        mensagem            {get;set;}
    Public String 						objNome				{get;set;}
    Public Id							objId				{get;set;}
    Public MktCategoria__c              categoria           {get;set;}
    Public List<MktCategoria__c>		listaCategoria   	{get;set;}
    Public List<MktParte__c>		    listaParte   	    {get;set;}
    Public Boolean                      temListaCategoria   {get;set;}
    Public Boolean                      temListaParte       {get;set;}
	
    Public String					    stringFilhaNova		{get;set;}
    Public List<String>					listaFilhaNova		{get;set;}
    
    public MktOrdeCate(ApexPages.StandardController controller) {
        Inicializa(controller);
        BuscaCategorias();
		BuscaPartes();
	}

    public void Inicializa(ApexPages.StandardController controller){
		temListaCategoria = false;
		temListaParte = false;
        objNome = controller.getRecord().Id.getSObjectType().getDescribe().getName();
        if(objNome == 'MktCategoria__c'){
            categoria 		= (MktCategoria__c)controller.getRecord(); 
            objId 			= categoria.Id;
        }
        mensagem            = '';
        stringFilhaNova      = '';
    }
    
    public void BuscaCategorias(){
        listaCategoria = [
            SELECT   Id, name, Ordem__c
            FROM     MktCategoria__c
            WHERE    Categoria_Pai__c 	= :objId
            ORDER BY Ordem__c ASC, Name ASC
        ];
        temListaCategoria = (listaCategoria.size() > 0 ? true : false);
    }
        
    public void BuscaPartes(){
        listaParte = [
            SELECT   Id, Nome__c, Modelo__c, Ordem__c, Parte__r.Tipo_do_Produto__c, Parte__r.StockKeepingUnit, Parte__r.ProductCode	
            FROM     MktParte__c
            WHERE    Categoria__c = :objId
            ORDER BY Ordem__c ASC, Name ASC
        ];
        temlistaParte = (listaParte.size() > 0 ? true : false);
    }
    
    public void SalvarOrdem(){
        listaFilhaNova = stringFilhaNova.split('\\,');
		System.Debug(LoggingLevel.INFO,'listaFilhaNova: '+listaFilhaNova);
        if(temListaCategoria){
            for(integer cont=0; cont<listaFilhaNova.size(); cont++)
            	for(MktCategoria__c categoria : listaCategoria){
                    if(listaFilhaNova[cont] == String.valueOf(categoria.Id))
                    	categoria.Ordem__c = cont+1;
				}
            for(MktCategoria__c categoria2 : listaCategoria)
				if(!listaFilhaNova.contains(categoria2.Id))
					categoria2.Ordem__c = null;
            update listaCategoria;
            BuscaCategorias();			
        }
        else if(temlistaParte){
            for(integer cont=0; cont<listaFilhaNova.size(); cont++)
            	for(MktParte__c parte : listaParte){
                    if(listaFilhaNova[cont] == String.valueOf(parte.Id))
                    	parte.Ordem__c = cont+1;
				}
            for(MktParte__c parte2 : listaParte)
				if(!listaFilhaNova.contains(parte2.Id))
					parte2.Ordem__c = null;
            update ListaParte;
            BuscaPartes();
        }
        mensagem = 'sucesso';
    }
    
}