force-app/main/default/objects/MktCategoria__c/MktCategoria__c.object-meta.xml
<CustomObject>
    <label>Categoria</label>
    <nameField>
        <label>Categoria</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categorias</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/MktCategoria__c/fields/Ativo__c.field-meta.xml
<CustomField>
    <fullName>Ativo__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Ativo em Marketing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MktCategoria__c/fields/Categoria_Pai__c.field-meta.xml
<CustomField>
    <fullName>Categoria_Pai__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Categoria Pai</label>
    <referenceTo>MktCategoria__c</referenceTo>
    <relationshipLabel>Sub Categorias</relationshipLabel>
    <relationshipName>Categorias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MktCategoria__c/fields/Descricao__c.field-meta.xml
<CustomField>
    <fullName>Descricao__c</fullName>
    <label>Descrição</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/MktCategoria__c/fields/Icone__c.field-meta.xml
<CustomField>
    <fullName>Icone__c</fullName>
    <label>Icone</label>
    <length>1000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/MktCategoria__c/fields/Icone_url__c.field-meta.xml
<CustomField>
    <fullName>Icone_url__c</fullName>
    <label>Icone</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/MktMidia__c/MktMidia__c.object-meta.xml
<CustomObject>
    <label>Mídia</label>
    <nameField>
        <label>Título</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mídias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MktMidia__c/fields/Ativo__c.field-meta.xml
<CustomField>
    <fullName>Ativo__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Ativo em Marketing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/MktMidia__c/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Categoria</label>
    <referenceTo>MktCategoria__c</referenceTo>
    <relationshipLabel>Mídias</relationshipLabel>
    <relationshipName>Midias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MktMidia__c/fields/DownloadId__c.field-meta.xml
<CustomField>
    <fullName>DownloadId__c</fullName>
    <label>Download ID</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/MktMidia__c/fields/Formato__c.field-meta.xml
<CustomField>
    <fullName>Formato__c</fullName>
    <label>Formato</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/MktMidia__c/fields/Icone_url__c.field-meta.xml
<CustomField>
    <fullName>Icone_url__c</fullName>
    <label>Icone</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/MktMidia__c/fields/Tamanho__c.field-meta.xml
<CustomField>
    <fullName>Tamanho__c</fullName>
    <label>Tamanho</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/MktMidia__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Atestado de Capacidade Técnica</fullName>
            </value>
            <value>
                <fullName>Catálogo</fullName>
            </value>
            <value>
                <fullName>Documentação Geral</fullName>
            </value>
            <value>
                <fullName>Especificação</fullName>
            </value>
            <value>
                <fullName>Estudo</fullName>
            </value>
            <value>
                <fullName>Extensão</fullName>
            </value>
            <value>
                <fullName>Imagem</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Registro na Anvisa</fullName>
            </value>
            <value>
                <fullName>Vídeo</fullName>
            </value>
            <value>
                <fullName>Manual do Usuário</fullName>
            </value>
            <value>
                <fullName>Acessório</fullName>
                <isActive>false</isActive>
                <label>Acessório</label>
            </value>
            <value>
                <fullName>Módulo</fullName>
                <isActive>false</isActive>
                <label>Módulo</label>
            </value>
            <value>
                <fullName>Transdutor</fullName>
                <isActive>false</isActive>
                <label>Transdutor</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MktMidia__c/fields/URL_do_Arquivo__c.field-meta.xml
<CustomField>
    <fullName>URL_do_Arquivo__c</fullName>
    <label>Download URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/MktParte__c/MktParte__c.object-meta.xml
<CustomObject>
    <label>Parte</label>
    <nameField>
        <displayFormat>PART{0}</displayFormat>
        <label>Identificação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MktParte__c/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Categoria</label>
    <referenceTo>MktCategoria__c</referenceTo>
    <relationshipLabel>Partes</relationshipLabel>
    <relationshipName>Partes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MktParte__c/fields/Categoria_pai__c.field-meta.xml
<CustomField>
    <fullName>Categoria_pai__c</fullName>
    <formula>Categoria__r.Categoria_Pai__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Categoria pai</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MktParte__c/fields/Codigo__c.field-meta.xml
<CustomField>
    <fullName>Codigo__c</fullName>
    <formula>Parte__r.ProductCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Código fornecedor</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MktParte__c/fields/Descricao__c.field-meta.xml
<CustomField>
    <fullName>Descricao__c</fullName>
    <formula>Parte__r.Description</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Descrição</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MktParte__c/fields/Icone__c.field-meta.xml
<CustomField>
    <fullName>Icone__c</fullName>
    <formula>Parte__r.URL_da_Imagem__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Icone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MktParte__c/fields/Modelo__c.field-meta.xml
<CustomField>
    <fullName>Modelo__c</fullName>
    <formula>Parte__r.Modelo__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Modelo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MktParte__c/fields/Nome__c.field-meta.xml
<CustomField>
    <fullName>Nome__c</fullName>
    <formula>Parte__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nome (Produto)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MktParte__c/fields/Ordem__c.field-meta.xml
<CustomField>
    <fullName>Ordem__c</fullName>
    <label>Ordem</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MktParte__c/fields/Parte__c.field-meta.xml
<CustomField>
    <fullName>Parte__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parte</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Product2.Tipo_do_Produto__c</field>
            <operation>equals</operation>
            <value>ACESSÓRIO, PEÇA</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Partes</relationshipLabel>
    <relationshipName>Partes_de_Produto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MktParte__c/fields/Quantidade_em_Estoque_Oficial__c.field-meta.xml
<CustomField>
    <fullName>Quantidade_em_Estoque_Oficial__c</fullName>
    <formula>Parte__r.Quantidade_em_Estoque_Oficial__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quantidade em Estoque Oficial</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MktParte__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <formula>TEXT(Parte__r.Tipo_do_Produto__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MktParte__c/fields/Valor__c.field-meta.xml
<CustomField>
    <fullName>Valor__c</fullName>
    <label>Valor</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MktParte__c/fields/ValorKit__c.field-meta.xml
<CustomField>
    <fullName>ValorKit__c</fullName>
    <formula>Parte__r.Valor_de_Venda__c + Parte__r.Valor_dos_Acessorios__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ValorKit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/MktVisualizacao__c/MktVisualizacao__c.object-meta.xml
<CustomObject>
    <label>Visualização</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visualizações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MktVisualizacao__c/fields/Midia__c.field-meta.xml
<CustomField>
    <fullName>Midia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mídia</label>
    <referenceTo>MktMidia__c</referenceTo>
    <relationshipLabel>Visualizações</relationshipLabel>
    <relationshipName>Visualizacoes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/MktVisualizacao__c/fields/Usuario__c.field-meta.xml
<CustomField>
    <fullName>Usuario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuário</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Visualizacoes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>_Tipo (del)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Usuario__c.field-meta.xml
<CustomField>
    <fullName>Usuario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuário</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Pedidos3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MktFluxo.cls
public with sharing class MktFluxo {

    Public Id                           navegacaoId         {get;set;}
    Public String                       navegacaoObjeto     {get;set;}
    
    Public String                       quebraLinha         {get;set;}
    Public String                       urlBase             {get;set;}
    Public List<Navegacao>              navegacoes          {get;set;} 
    Public Integer                      navegacaoQtd        {get;set;}  
    
    Public List<MktCategoria__c>        listaCategoria      {get;set;}
    Public List<MktMidia__c>            listaMidia          {get;set;}
    Public List<MktParte__c>            listaParte          {get;set;}
    Public List<Map<String, String>>    listaMidiaTipo      {get;set;}
    Public List<Map<String, String>>    listaParteTipo      {get;set;}
    Public List<Visualizacao>           listaVisualizacao   {get;set;}
    Public Boolean                      temListaCategoria   {get;set;}
    Public Boolean                      temListaMidia       {get;set;}
    Public Boolean                      temListaParte       {get;set;}
    
    public MktFluxo(){
        Inicializa();
        PopulaNavegacao();
        PopulaObjeto();
        PopulaMidia();
        PopulaParte();
    }
    
    public void Inicializa(){
        quebraLinha         = '</div><div class=\"row\">';
        urlBase             = URL.getSalesforceBaseUrl().toExternalForm() + Site.getPathPrefix();
        navegacaoId         = (System.currentPageReference().getParameters().containsKey('Id') && System.currentPageReference().getParameters().get('Id') != '') 
                            ? System.currentPageReference().getParameters().get('Id') : null;
        navegacaoObjeto     = (navegacaoId == null) ? 'MktInicio' : navegacaoId.getSObjectType().getDescribe().getName();
        navegacoes          = new List<Navegacao>();
        listaCategoria      = new List<MktCategoria__c>();
        listaMidia          = new List<MktMidia__c>();  
        listaParte          = new List<MktParte__c>();  
        listaMidiaTipo      = new List<Map<String, String>>();
        listaParteTipo      = new List<Map<String, String>>();
        listaVisualizacao   = new List<Visualizacao>();
        temListaCategoria   = false;
        temListaMidia       = false;
        temListaParte       = false;
    }
    
    public void PopulaNavegacao(){
        if(navegacaoObjeto == 'MktInicio'){
            navegacoes.add(new Navegacao(null, 'Home', ''));
        }
        else if(navegacaoObjeto == 'MktCategoria__c'){
            List<Navegacao>     lista_cat       = new List<Navegacao>();
            List<Navegacao>     lista_cat_inv   = new List<Navegacao>();
            MktCategoria__c     categoria       = new MktCategoria__c();

            categoria = [
                SELECT  Id, Name, Icone_url__c, Categoria_Pai__c
                FROM    MktCategoria__c
                WHERE   Id = :navegacaoId
            ];
            lista_cat.add(new Navegacao(categoria.Id, categoria.Name, categoria.Icone_url__c));
            
            while(categoria.Categoria_Pai__c != null){
                categoria = [
                    SELECT  Id, Name, Icone_url__c, Categoria_Pai__c
                    FROM    MktCategoria__c
                    Where   Id = :categoria.Categoria_Pai__c
                ];
                lista_cat.add(new Navegacao(categoria.Id, categoria.Name, categoria.Icone_url__c));
            }
            
            for(Integer cont = lista_cat.size()-1; cont >= 0; cont--)
                lista_cat_inv.add(lista_cat[cont]);
                  
            navegacoes.add(new Navegacao(null, 'Home', ''));
            navegacoes.addAll(lista_cat_inv);
        }      
        navegacaoQtd = navegacoes.size();
    }

    public void PopulaObjeto(){
        if(navegacaoObjeto == 'MktInicio'){
            listaCategoria = [
                SELECT      Id, Name, Icone_url__c
                FROM        MktCategoria__c
                WHERE       Ativo__c = true AND Categoria_pai__c = null
                ORDER BY    Name ASC
            ];
            temListaCategoria = (listaCategoria.size() > 0 ? true : false);
        }
        else if(navegacaoObjeto == 'MktCategoria__c'){
            listaCategoria = [
                SELECT      Id, Name, Icone_url__c
                FROM        MktCategoria__c
                WHERE       Categoria_Pai__c = :navegacaoId AND
                            Ativo__c = true
                ORDER BY    Ordem__c ASC NULLS LAST
            ];
            temListaCategoria = (listaCategoria.size() > 0 ? true : false);
        }
    }
    
    public void PopulaMidia(){
        
        // popula mídias ----
        if(navegacaoObjeto == 'MktCategoria__c'){
            listaMidia = [
                SELECT      Id, Name, Icone_url__c, Tipo__c, URL_do_Arquivo__c, DownloadId__c, Tamanho__c, Formato__c, CreatedDate 
                FROM        MktMidia__c
                WHERE       Categoria__c = :navegacaoId AND
                            Ativo__c = true
                ORDER BY    Tipo__c, Name
            ];
        }
        
        temListaMidia = (listaMidia.size() > 0 ? true : false);
        
        // popula tipos/qtds ----
        if(listaMidia.size() > 0){
            String  midiaTipo = '';
            Integer midiaTipoQtd = 0;
            for(Integer cont = 0; cont < listaMidia.size(); cont++){
                if((midiaTipo != listaMidia[cont].Tipo__c) && (midiaTipoQtd != 0)){
                    listaMidiaTipo.add(new Map<String, String>{'tipo'=> midiaTipo, 'qtd'=> String.valueOf(midiaTipoQtd)});
                    midiaTipoQtd = 0;
                }
                midiaTipo = listaMidia[cont].Tipo__c;
                midiaTipoQtd ++;
            }
            listaMidiaTipo.add(new Map<String, String>{'tipo'=> midiaTipo, 'qtd'=> String.valueOf(midiaTipoQtd)});
        }
        
        // popula visualizadores ----
        if(listaMidia.size() > 0){
            List<Id> listaMidiaId = new List<Id>();            
            for(Integer cont=0; cont<listaMidia.size(); cont++)
                listaMidiaId.add(listaMidia[cont].Id);
            
            List<AggregateResult> listaVisualizacaoAgreg = new List<AggregateResult>();
            listaVisualizacaoAgreg = [
                SELECT      Midia__c, Usuario__c, MAX(Usuario__r.Name) Usuario_Name, 
                            MAX(Usuario__r.SmallPhotoUrl) Usuario_Photo, MAX(CreatedDate) CreatedDate
                FROM        MktVisualizacao__c
                WHERE       Midia__c IN :listaMidiaId
                GROUP BY    Midia__c, Usuario__c
            ];
            for(Integer cont=0; cont < listaVisualizacaoAgreg.size(); cont++){
                listaVisualizacao.add(new Visualizacao(
                    (Id)listaVisualizacaoAgreg[cont].get('Midia__c'),
                    (Id)listaVisualizacaoAgreg[cont].get('Usuario__c'),
                    (String)listaVisualizacaoAgreg[cont].get('Usuario_Name'),
                    (String)listaVisualizacaoAgreg[cont].get('Usuario_Photo'),
                    String.valueOf(Datetime.valueOf(listaVisualizacaoAgreg[cont].get('CreatedDate')).format('dd/MM/yyyy HH:mm'))
                ));
            }

        }
    }
    
    public void PopulaParte(){
        
        // popula partes ----
        if(navegacaoObjeto == 'MktCategoria__c'){
            listaParte = [
                SELECT      Id, Tipo__c, Parte__c, Codigo__c, Nome__c, Modelo__c, Descricao__c, Icone__c, Valor__c, ValorKit__c, Quantidade_em_Estoque_Oficial__c
                FROM        MktParte__c
                WHERE       Categoria__c = :navegacaoId AND
                            Ativo__c = true
                ORDER BY    Tipo__c, Ordem__c NULLS LAST
            ];
        }
        
        temListaParte = (listaParte.size() > 0 ? true : false);
        
        // popula tipos/qtds ----
        if(listaParte.size() > 0){
            String  parteTipo = '';
            Integer parteTipoQtd = 0;
            for(Integer cont = 0; cont < listaParte.size(); cont++){
                if((parteTipo != listaParte[cont].Tipo__c) && (parteTipoQtd != 0)){
                    listaParteTipo.add(new Map<String, String>{'tipo'=> parteTipo, 'qtd'=> String.valueOf(parteTipoQtd)});
                    parteTipoQtd = 0;
                }
                parteTipo = listaParte[cont].Tipo__c;
                parteTipoQtd ++;
            }
            listaParteTipo.add(new Map<String, String>{'tipo'=> parteTipo, 'qtd'=> String.valueOf(parteTipoQtd)});
        }
        
        // popula valores
        if(listaParte.size() > 0){
            List<Id> listaParteProdId = new List<Id>();
            for(Integer cont = 0; cont < listaParte.size(); cont++){
                listaParteProdId.Add(listaParte[cont].Parte__c);
            }
            
            List<PriceBookEntry> entradas = new List<PriceBookEntry>(); // FY18
            entradas = [
                SELECT  Product2Id, UnitPrice
                FROM    PriceBookEntry
                WHERE   Product2Id IN :listaParteProdId AND
                        Pricebook2.Name = 'Padrão' AND PriceBookEntry.CurrencyIsoCode = 'BRL'        
            ];
            
            for(Integer cont = 0; cont < listaParte.size(); cont++){
                for(Integer cont2 = 0; cont2 < entradas.size(); cont2++){
                    if(listaParte[cont].Parte__c == entradas[cont2].Product2Id){
                        listaParte[cont].Valor__c = entradas[cont2].UnitPrice;
                    }
                }
            }
            
        }
        
    }

    public PageReference Baixar(){
        MktVisualizacao__c visualizacao = new MktVisualizacao__c();
        visualizacao.Usuario__c = UserInfo.getUserId();
        visualizacao.Midia__c = navegacaoId;
        insert visualizacao;
        
        String urlPath = null;
        for(Integer cont=0; cont<listaMidia.size(); cont++){
            if(listaMidia[cont].Id == navegacaoId){
                if(listaMidia[cont].URL_do_Arquivo__c != NULL)
                    urlPath = listaMidia[cont].URL_do_Arquivo__c;
                else
                    urlPath = '/sfc/servlet.shepherd/version/download/' + listaMidia[cont].DownloadId__c;
                break;
            }
        }
        return new PageReference(urlPath);
    }
    
    public void Abrir(){ 
        MktVisualizacao__c visualizacao = new MktVisualizacao__c();
        visualizacao.Usuario__c = UserInfo.getUserId();
        visualizacao.Midia__c = navegacaoId;
        insert visualizacao;
    }
    
    public class Navegacao{
        public Id id {get;set;}
        public String nome {get;set;}
        public String imagem {get;set;}
        
        public Navegacao(Id id_parm, String nome_parm, String imagem_parm){
            id = id_parm;
            nome = nome_parm;
            imagem = imagem_parm;
        }
    }
    
    public class Visualizacao{
        public Id midia_id {get;set;}
        public Id usuario_id {get;set;}
        public String usuario_nome {get;set;}
        public String usuario_foto {get;set;}
        public String ultimo_acesso {get;set;}
        
        public Visualizacao(Id midia_id_parm, Id usuario_id_parm, String usuario_nome_parm,
                            String usuario_foto_parm, String ultimo_acesso_parm){
            midia_id = midia_id_parm;
            usuario_id = usuario_id_parm;
            usuario_nome = usuario_nome_parm;
            usuario_foto = usuario_foto_parm;
            ultimo_acesso = ultimo_acesso_parm;
        }
    }
    
}