force-app/main/default/objects/Medida_de_Temperatura_e_Umidade__c/Medida_de_Temperatura_e_Umidade__c.object-meta.xml
<CustomObject>
    <label>Medida de Temperatura e Umidade</label>
    <nameField>
        <displayFormat>MTU-{000000}</displayFormat>
        <label>Medida de Temperatura e Umidade</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Medidas de Temperatura e Umidade</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Medida_de_Temperatura_e_Umidade__c/fields/Endereco_Mac__c.field-meta.xml
<CustomField>
    <fullName>Endereco_Mac__c</fullName>
    <label>Endereço Mac</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Medida_de_Temperatura_e_Umidade__c/fields/Temperatura__c.field-meta.xml
<CustomField>
    <fullName>Temperatura__c</fullName>
    <label>Última temperatura lida</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Medida_de_Temperatura_e_Umidade__c/fields/Umidade__c.field-meta.xml
<CustomField>
    <fullName>Umidade__c</fullName>
    <label>Umidade</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Sensores.cls
@RestResource(urlMapping='/sensors')
global class Sensores{
@HttpPost
    global static void doPost() {
        // Obtém os dados da requisição
        String requestBody = RestContext.request.requestBody.toString();
        
        system.debug(requestBody);
       
        string temperatura = requestBody.substringAfter('"Temperatura__c":"').substringBefore('","Umidade__c"');
        
		Decimal temperatura2 = Decimal.valueOf(temperatura);

        string umidade = requestBody.substringAfter('"Umidade__c":"').substringBefore('","Endereco');
        
        Decimal umidade2 = Decimal.valueOf(umidade);
        
        string endereco = requestBody.substringAfter('"Endereco_Mac__c":"').substringBefore('"');
        
        Medida_de_Temperatura_e_Umidade__c medida = new Medida_de_Temperatura_e_Umidade__c(
            													Endereco_Mac__c = endereco,
        														Temperatura__c	= temperatura2,
            													Umidade__c = umidade2);
        try{
            insert medida;
        }
        catch(DMLException e){
            
        }
    }
}