force-app/main/default/objects/Item_de_pedido_de_compra__c/Item_de_pedido_de_compra__c.object-meta.xml
<CustomObject>
    <label>Item de cotação</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número do item de cotação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens de cotação</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Item_de_pedido_de_compra__c/fields/Data_de_requisicao__c.field-meta.xml
<CustomField>
    <fullName>Data_de_requisicao__c</fullName>
    <label>Data de requisição</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Item_de_pedido_de_compra__c/fields/Quantidade_requisitada__c.field-meta.xml
<CustomField>
    <fullName>Quantidade_requisitada__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quantidade requisitada</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Requisicao_de_item__c/Requisicao_de_item__c.object-meta.xml
<CustomObject>
    <label>Destinação de item</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número da requisição de item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Destinações de item</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Requisicao_de_item__c/fields/Data_de_requisicao__c.field-meta.xml
<CustomField>
    <fullName>Data_de_requisicao__c</fullName>
    <label>Data de requisição</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Requisicao_de_item__c/fields/Item_de_pedido_de_compra__c.field-meta.xml
<CustomField>
    <fullName>Item_de_pedido_de_compra__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Item de cotação</label>
    <referenceTo>Item_de_pedido_de_compra__c</referenceTo>
    <relationshipName>Requisicoes_de_Itens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Requisicao_de_item__c/fields/Quantidade_requisitada__c.field-meta.xml
<CustomField>
    <fullName>Quantidade_requisitada__c</fullName>
    <label>Quantidade destinada</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/RequisicaoDeItemTEST.cls
@isTest
public class RequisicaoDeItemTEST {

    @isTest
    public static void teste(){
        //Requisicao_de_item__c ri = new Requisicao_de_item__c();
        //insert ri;
        
        //Requisicao_de_item__c rq = new Requisicao_de_item__c(Quantidade_requisitada__c = 4, Data_de_requisicao__c = System.today());
        //insert rq;
 
        //rq.Quantidade_requisitada__c = 2;
        //update rq;
        //delete rq;
        Requisicao_de_item__c rq = new Requisicao_de_item__c(Quantidade_requisitada__c = 5, Data_de_requisicao__c = System.today(), Item_de_pedido_de_compra__c = 'a1d5A0000095Ut7');
        insert rq;
        PageReference testPage = Page.Requisicao;
        Test.setCurrentPage(testPage);
        testPage.getParameters().put('Id', String.valueOf(rq.Id));
        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(rq);
        //RequisicaoController obj = new RequisicaoController(sc);
        //obj.pvendaId= '8025A000009I4qAQAS';
        //obj.pegarpvendaid();
        //obj.quantidadedirec=2;
        //obj.novarequisicao();
        Test.stopTest();

    }
    
}