force-app/main/default/objects/Aditivo_Relacionado__c/Aditivo_Relacionado__c.object-meta.xml
<CustomObject>
    <label>Aditivo Relacionado</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Nome de Aditivo Relacionado</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Aditivos Relacionados</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Aditivo_Relacionado__c/fields/Aditivo_Contratual_Relacionado__c.field-meta.xml
<CustomField>
    <fullName>Aditivo_Contratual_Relacionado__c</fullName>
    <label>Aditivo Contratual Relacionado</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Aditivos_Contratuais__c.Contrato_de_Servi_o_Relacionado__r.Id</field>
            <operation>equals</operation>
            <valueField>Aditivos_Contratuais__c.Contrato_de_Servi_o_Relacionado__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Aditivos_Contratuais__c</referenceTo>
    <relationshipLabel>Aditivos Relacionados</relationshipLabel>
    <relationshipName>Aditivos_Relacionados</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Aditivo_Relacionado__c/fields/Ativo_do_Contrato_Relacionado__c.field-meta.xml
<CustomField>
    <fullName>Ativo_do_Contrato_Relacionado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ativo do Contrato Relacionado</label>
    <referenceTo>Ativos_do_Contrato__c</referenceTo>
    <relationshipLabel>Aditivos Relacionados</relationshipLabel>
    <relationshipName>Aditivos_Relacionados</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Aditivos_Contratuais__c/Aditivos_Contratuais__c.object-meta.xml
<CustomObject>
    <label>Aditivo Contratual</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Nome de Aditivos Contratuais</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Aditivos Contratuais</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ativos_do_Contrato__c/Ativos_do_Contrato__c.object-meta.xml
<CustomObject>
    <label>Ativo do Contrato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>N° de Registro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ativos do Contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ativos_do_Contrato__c/fields/Aditivo_Contratual_Relacionado__c.field-meta.xml
<CustomField>
    <fullName>Aditivo_Contratual_Relacionado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Aditivo Contratual Relacionado</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Aditivos_Contratuais__c.Contrato_de_Servi_o_Relacionado__c</field>
            <operation>equals</operation>
            <valueField>$Source.Contrato_de_Servico__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Aditivos_Contratuais__c</referenceTo>
    <relationshipLabel>Ativos do Contrato</relationshipLabel>
    <relationshipName>Ativos_do_Contrato</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ativos_do_Contrato__c/fields/Ativo_Locado__c.field-meta.xml
<CustomField>
    <fullName>Ativo_Locado__c</fullName>
    <label>Ativo Locado</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Ativos do Contrato</relationshipLabel>
    <relationshipName>Ativos_do_Contrato</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Checklist_de_Aditivo_Test.cls
@isTest(seeAllData=true)
public class Checklist_de_Aditivo_Test {
 static testMethod void test_listagem_cs(){ 
        Aditivos_Contratuais__c ac = new Aditivos_Contratuais__c();
        ac = [
            SELECT 	Id
            FROM	Aditivos_Contratuais__c
            WHERE	Id = 'a1j6e000008duk6'	// test:0WO3D000000D2R7 prod:0WO5A000000XezU
        ];


        List<Aditivo_Relacionado__c> Ativosdocontrato = [
            SELECT  Ativo_do_Contrato_Relacionado__r.Ativo_Locado__c
            FROM    Aditivo_Relacionado__c
            WHERE   Aditivo_Contratual_Relacionado__c = 'a1j6e000008duk6'
        ];

        test.startTest();
            ApexPages.StandardController stdCtrl = new ApexPages.StandardController(ac);
            CheckList_de_Aditivo_Controller registro = new CheckList_de_Aditivo_Controller(stdCtrl);
		test.stopTest();
    }
    
    
}