force-app/main/default/objects/Demonstracao__c/Demonstracao__c.object-meta.xml
<CustomObject>
    <label>Comodato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comodatos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Demonstracao__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Rascunho&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rascunho</fullName>
            </value>
            <value>
                <fullName>Em aprovação</fullName>
            </value>
            <value>
                <fullName>Reprovado</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Em calibração</fullName>
            </value>
            <value>
                <fullName>Agendado</fullName>
            </value>
            <value>
                <fullName>Em comodato</fullName>
            </value>
            <value>
                <fullName>Retorno da demo</fullName>
                <label>Retorno</label>
            </value>
            <value>
                <fullName>Pendente de retorno</fullName>
            </value>
            <value>
                <fullName>Em Verificação Funcional</fullName>
            </value>
            <value>
                <fullName>Finalizado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Finalizado com Pendência</fullName>
                <isActive>false</isActive>
                <label>Finalizado com Pendência</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Demonstracao__c/recordTypes/Comodato.recordType-meta.xml
<RecordType>
    <fullName>Comodato</fullName>
    <active>true</active>
    <label>Comodato</label>
</RecordType>

force-app/main/default/classes/DemonstracaoValidacaoTest.cls
@isTest(seeAllData=true)
public class DemonstracaoValidacaoTest {
    @isTest
    static void teste() {
        
        Demonstracao__c comodato = [SELECT ID FROM Demonstracao__c WHERE ID = 'a0KU400000EJnHu'];
        
        comodato.Status__c = 'Retorno';
        
        Test.startTest();
        
        try{
            update comodato;
        }
        catch(DmlException e){
            
        }
        Test.stopTest();
    }
    @isTest
    static void teste2() {
        
        Demonstracao__c comodato = [SELECT ID FROM Demonstracao__c WHERE ID = 'a0KU400000EJnHu'];
        
        comodato.Status__c = 'Retorno';
        
        Test.startTest();
        
        try{
            delete comodato;
        }
        catch(DmlException e){
            
        }
        Test.stopTest();
    }
    @isTest
    static void teste3() {
        
        Demonstracao__c comodato = [SELECT ID FROM Demonstracao__c WHERE ID = 'a0KU400000EJnHu'];
        
        comodato.Status__c = 'Em demonstração';
        
        Test.startTest();
        
        try{
            update comodato;
        }
        catch(DmlException e){
            
        }
        Test.stopTest();
    }
    @isTest
    static void teste4() {
        
        Demonstracao__c comodato = [SELECT ID FROM Demonstracao__c WHERE ID = 'a0KU400000EJnHu'];
        
        comodato.Status__c = 'Finalizado';
        
        Test.startTest();
        
        try{
            update comodato;
        }
        catch(DmlException e){
            
        }
        Test.stopTest();
    }
    @isTest
    static void teste5() {
        
        Demonstracao__c comodato = [SELECT ID FROM Demonstracao__c WHERE ID = 'a0KU400000EJnHu'];
        
        comodato.Acao_interna__c = true;
        comodato.Status__c = 'Agendado';
        update comodato;
        
        comodato.Status__c = 'Em demonstração';
        Test.startTest();
        
        try{
        }
        catch(DmlException e){
            
        }
        Test.stopTest();
    }
    @isTest
    static void teste6() {
        
        Demonstracao__c comodato = [SELECT ID FROM Demonstracao__c WHERE ID = 'a0KU400000EJnHu'];
        
        comodato.Acao_interna__c = false;
        comodato.Status__c = 'Agendado';
        update comodato;
        
        comodato.Status__c = 'Em demonstração';
        Test.startTest();
        
        try{
        }
        catch(DmlException e){
            
        }
        Test.stopTest();
    }
}