force-app/main/default/objects/Demonstracao__c/Demonstracao__c.object-meta.xml
<CustomObject>
    <label>Comodato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comodatos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Demonstracao__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Demonstracoes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demonstracao__c/fields/Documento_Assinado__c.field-meta.xml
<CustomField>
    <fullName>Documento_Assinado__c</fullName>
    <label>Documento Assinado</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Demonstracao__c/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Demonstracoes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Oportunidades (Contato)</relationshipLabel>
    <relationshipName>Oportunidades2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Faturamento_Feito2__c.field-meta.xml
<CustomField>
    <fullName>Faturamento_Feito2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Faturamento feito</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>FORNECEDOR, DISTRIBUIDOR</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Faturamentos Feitos (de oportunidades)</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AutentiqueDemoTest.cls
@isTest(seeAllData=true)
public class AutentiqueDemoTest {
	@isTest
    private static void teste(){
        
        Test.setMock(HttpCalloutMock.class, new MockAutentiqueContratos());
        
        
        Demonstracao__c Contrato = [SELECT Name, Contato__r.Name, RecordTypeId, Contato__r.Email, idDocAutentique__c, Oportunidade__r.Faturamento_Feito2__r.CNPJ__c, Nome_da_Testemunha__c, E_mail_da_Testemunha__c, Documento_Assinado__c FROM Demonstracao__c WHERE ID= 'a0K5A00000MVAKZ' ];
        
        AutentiqueDemo AC = new AutentiqueDemo(new ApexPages.StandardController(Contrato));
        
        AC.atualizar();
        AC.inserir();
        
    }
    @isTest
    private static void teste3(){
        
        Test.setMock(HttpCalloutMock.class, new MockAutentiqueContratos());
        
        
        Demonstracao__c Contrato = [SELECT Name, Contato__r.Name, RecordTypeId, Contato__r.Email, idDocAutentique__c, Oportunidade__r.Faturamento_Feito2__r.CNPJ__c, Nome_da_Testemunha__c, E_mail_da_Testemunha__c, Documento_Assinado__c FROM Demonstracao__c WHERE ID= 'a0K5A00000MVAKZ' ];
        
        AutentiqueDemo AC = new AutentiqueDemo(new ApexPages.StandardController(Contrato));
        
        AC.atualizar();
        AC.inserir();
        AC.enviar();
        
    }
    @isTest
    private static void teste2(){
        
        Test.setMock(HttpCalloutMock.class, new MockAutentiqueContratos2());
        
        
        Demonstracao__c Contrato = [SELECT Name, Contato__r.Name, RecordTypeId, Contato__r.Email, idDocAutentique__c, Oportunidade__r.Faturamento_Feito2__r.CNPJ__c, Nome_da_Testemunha__c, E_mail_da_Testemunha__c, Documento_Assinado__c FROM Demonstracao__c WHERE ID= 'a0K5A00000MVAKZ' ];
        
        AutentiqueDemo AC = new AutentiqueDemo(new ApexPages.StandardController(Contrato));
        
        AC.enviar();
        
    }
   // @isTest
   // private static void teste4(){
        
     //   Test.setMock(HttpCalloutMock.class, new MockAutentiqueContratos2());
        
        
     //l   Demonstracao__c Contrato = [SELECT Name, Contato__r.Name, RecordTypeId, Contato__r.Email, idDocAutentique__c, Oportunidade__r.Faturamento_Feito2__r.CNPJ__c, Nome_da_Testemunha__c, E_mail_da_Testemunha__c, Documento_Assinado__c FROM Demonstracao__c WHERE ID= 'a0K6e00000qEHwnEAG' ];
        
     //   AutentiqueDemo AC = new AutentiqueDemo(new ApexPages.StandardController(Contrato));
        
        //AC.enviar();
        
    //}
}