force-app/main/default/objects/Demonstracao__c/Demonstracao__c.object-meta.xml
<CustomObject>
    <label>Comodato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comodatos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order/fields/Condicao_de_pagamento__c.field-meta.xml
<CustomField>
    <fullName>Condicao_de_pagamento__c</fullName>
    <label>Condição de pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Natureza_de_Opera_o__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Condicoes_de_pagamento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Demonstracao__c.field-meta.xml
<CustomField>
    <fullName>Demonstracao__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Comodato</label>
    <referenceTo>Demonstracao__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Entrega_parcial__c.field-meta.xml
<CustomField>
    <fullName>Entrega_parcial__c</fullName>
    <label>Entrega parcial</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Autorizada</fullName>
            </value>
            <value>
                <fullName>Não Autorizada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Faturamento_Feito__c.field-meta.xml
<CustomField>
    <fullName>Faturamento_Feito__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Empresa do grupo Hospcom que irá faturar o pedido.</inlineHelpText>
    <label>Faturamento feito</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Faturamentos Feitos (de pedidos)</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Forma_de_pagamento2__c.field-meta.xml
<CustomField>
    <fullName>Forma_de_pagamento2__c</fullName>
    <label>Forma de pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Natureza_de_Opera_o__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Formas_de_pagamento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Frete__c.field-meta.xml
<CustomField>
    <fullName>Frete__c</fullName>
    <label>Tipo de envio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipos_de_envio</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Necess_rio_Treinamento__c.field-meta.xml
<CustomField>
    <fullName>Necess_rio_Treinamento__c</fullName>
    <label>Necessário Treinamento?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SIM</fullName>
            </value>
            <value>
                <fullName>NÃO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Ordem_de_trabalho__c.field-meta.xml
<CustomField>
    <fullName>Ordem_de_trabalho__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ordem de trabalho</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Pedido_da_Linha_de_OPME__c.field-meta.xml
<CustomField>
    <fullName>Pedido_da_Linha_de_OPME__c</fullName>
    <label>Pedido da Linha de OPME?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SIM</fullName>
            </value>
            <value>
                <fullName>NÃO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Prazo_de_entrega__c.field-meta.xml
<CustomField>
    <fullName>Prazo_de_entrega__c</fullName>
    <label>Prazo de entrega</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PedidosVendedor</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/recordTypes/Hospcom.recordType-meta.xml
<RecordType>
    <fullName>Hospcom</fullName>
    <active>true</active>
    <description>Para faturamento das empresas do grupo Hospcom</description>
    <label>Hospcom</label>
</RecordType>

force-app/main/default/globalValueSets/Tipos_de_envio.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Contratação do Frete por conta do Remetente (CIF)</fullName>
    </customValue>
    <customValue>
        <fullName>Contratação do Frete por conta do Destinatário (FOB)</fullName>
    </customValue>
    <customValue>
        <fullName>Contratação do Frete por conta de Terceiros</fullName>
    </customValue>
    <customValue>
        <fullName>Transporte Próprio por conta do Remetente</fullName>
    </customValue>
    <customValue>
        <fullName>Transporte Próprio por conta do Destinatário</fullName>
    </customValue>
    <customValue>
        <fullName>Sem Ocorrência de Transporte.</fullName>
    </customValue>
    <masterLabel>Tipos de envio</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PedidoPreenchimentoTest.cls
@isTest(seeAllData=true)
public class PedidoPreenchimentoTest {
@isTest static void Teste2(){
    Order pedidoOriginal = [
      SELECT   Ordem_de_trabalho__c, AccountId, EffectiveDate, Status,  Necess_rio_Treinamento__c, Pedido_da_Linha_de_OPME__c, 
          Entrega_parcial__c, Prazo_de_entrega__c, Faturamento_Feito__c, Vendedor__c, Condicao_de_pagamento__c,
          Forma_de_pagamento2__c, Frete__c
      FROM  Order
      WHERE   Id = '8015A000001ZCgQQAW'
    ];
    Order pedidoNovo = pedidoOriginal.clone(false, false, false, false);
    pedidoNovo.RecordTypeId = Schema.getGlobalDescribe().get('Order').getDescribe().getRecordTypeInfosByName().get('Hospcom').getRecordTypeId();
    pedidoNovo.Pesq_Satisfacao_Enviada__c = true;
    insert pedidoNovo;
  }
@isTest static void Teste3(){
    Order pedidoOriginal = [
      SELECT   Ordem_de_trabalho__c, AccountId, EffectiveDate, Status,  Necess_rio_Treinamento__c, Pedido_da_Linha_de_OPME__c, 
          Entrega_parcial__c, Prazo_de_entrega__c, Faturamento_Feito__c, Vendedor__c, Condicao_de_pagamento__c,
          Forma_de_pagamento2__c, Frete__c
      FROM  Order
      WHERE   Id = '8016e00000769BJ'
    ];
    pedidoOriginal.Pesq_Satisfacao_Enviada__c = true;
    update pedidoOriginal;
    Order pedidoNovo = pedidoOriginal.clone(false, false, false, false);
    pedidoNovo.RecordTypeId = Schema.getGlobalDescribe().get('Order').getDescribe().getRecordTypeInfosByName().get('Hospcom').getRecordTypeId();
    pedidoNovo.Pesq_Satisfacao_Enviada__c = true;
    insert pedidoNovo;
  }
@isTest static void Teste4(){
    Order pedidoOriginal = [
      SELECT   Ordem_de_trabalho__c, AccountId, EffectiveDate, Status,  Necess_rio_Treinamento__c, Pedido_da_Linha_de_OPME__c, 
          Entrega_parcial__c, Prazo_de_entrega__c, Faturamento_Feito__c, Vendedor__c, Condicao_de_pagamento__c,
          Forma_de_pagamento2__c, Frete__c, QuoteId
      FROM  Order
      WHERE   Id = '8015A000002jdzK'
    ];
    pedidoOriginal.Pesq_Satisfacao_Enviada__c = true;
    update pedidoOriginal;
    Order pedidoNovo = pedidoOriginal.clone(false, false, false, false);
    pedidoNovo.RecordTypeId = Schema.getGlobalDescribe().get('Order').getDescribe().getRecordTypeInfosByName().get('Hospcom').getRecordTypeId();
    pedidoNovo.Pesq_Satisfacao_Enviada__c = true;
    insert pedidoNovo;
  }
@isTest static void Teste5(){
    Order pedidoOriginal = [
      SELECT   AccountId, EffectiveDate, Status,  Necess_rio_Treinamento__c, Pedido_da_Linha_de_OPME__c, 
          Entrega_parcial__c, Prazo_de_entrega__c, Faturamento_Feito__c, Vendedor__c, Condicao_de_pagamento__c,
          Forma_de_pagamento2__c, Frete__c, QuoteId, Demonstracao__c
      FROM  Order
      WHERE   Id = '8016e000005JQlS'
    ];
    pedidoOriginal.Pesq_Satisfacao_Enviada__c = true;
    update pedidoOriginal;
    Order pedidoNovo = pedidoOriginal.clone(false, false, false, false);
    pedidoNovo.RecordTypeId = Schema.getGlobalDescribe().get('Order').getDescribe().getRecordTypeInfosByName().get('Hospcom').getRecordTypeId();
    pedidoNovo.Pesq_Satisfacao_Enviada__c = true;
    insert pedidoNovo;
  }
    @isTest static void Teste6(){
    Order pedidoOriginal = [
      SELECT   AccountId, EffectiveDate, Status,  Necess_rio_Treinamento__c, Pedido_da_Linha_de_OPME__c, 
          Entrega_parcial__c, Prazo_de_entrega__c, Faturamento_Feito__c, Vendedor__c, Condicao_de_pagamento__c,
          Forma_de_pagamento2__c, Frete__c, QuoteId, Demonstracao__c
      FROM  Order
      WHERE   Id = '8016e000005JQlS'
    ];
    pedidoOriginal.Pesq_Satisfacao_Enviada__c = true;
    update pedidoOriginal;
    Order pedidoNovo = pedidoOriginal.clone(false, false, false, false);
    pedidoNovo.RecordTypeId = Schema.getGlobalDescribe().get('Order').getDescribe().getRecordTypeInfosByName().get('Hospcom').getRecordTypeId();
    pedidoNovo.Pesq_Satisfacao_Enviada__c = true;
    insert pedidoNovo;
  }
}