force-app/main/default/objects/Demonstracao__c/Demonstracao__c.object-meta.xml
<CustomObject>
    <label>Comodato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comodatos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Produto_da_demonstracao__c/Produto_da_demonstracao__c.object-meta.xml
<CustomObject>
    <label>Ativo do comodato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ativos do comodato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Produto_da_demonstracao__c/fields/Demonstracao__c.field-meta.xml
<CustomField>
    <fullName>Demonstracao__c</fullName>
    <label>Comodato</label>
    <referenceTo>Demonstracao__c</referenceTo>
    <relationshipName>Produtos_da_demonstracao</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DemonstracaoItemValidacaoTest.cls
@isTest(seeAllData=true)
public class DemonstracaoItemValidacaoTest {
    @isTest
    static void teste() {
        
       Produto_da_demonstracao__c pd = new Produto_da_demonstracao__c(Demonstracao__c = 'a0K6e00001ngmJI');
        
        Test.startTest();
        
        try{
            insert pd;
        }
        catch(DmlException e){
            
        }
        Test.stopTest();
    }
}