force-app/main/default/objects/Demonstracao__c/Demonstracao__c.object-meta.xml
<CustomObject>
    <label>Comodato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comodatos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Demonstracao__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Demonstracoes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demonstracao__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Rascunho&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rascunho</fullName>
            </value>
            <value>
                <fullName>Em aprovação</fullName>
            </value>
            <value>
                <fullName>Reprovado</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Em calibração</fullName>
            </value>
            <value>
                <fullName>Agendado</fullName>
            </value>
            <value>
                <fullName>Em comodato</fullName>
            </value>
            <value>
                <fullName>Retorno da demo</fullName>
                <label>Retorno</label>
            </value>
            <value>
                <fullName>Pendente de retorno</fullName>
            </value>
            <value>
                <fullName>Em Verificação Funcional</fullName>
            </value>
            <value>
                <fullName>Finalizado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Finalizado com Pendência</fullName>
                <isActive>false</isActive>
                <label>Finalizado com Pendência</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Demonstracao__c/recordTypes/Comodato.recordType-meta.xml
<RecordType>
    <fullName>Comodato</fullName>
    <active>true</active>
    <label>Comodato</label>
</RecordType>

force-app/main/default/classes/DemonstracaoPreenchimentoTest.cls
@isTest(seeAllData=true)
public class DemonstracaoPreenchimentoTest {
    @isTest
    static void teste() {
        
        Demonstracao__c comodato = new Demonstracao__c(Conta__c = '001i00000085QYbAAM');
        
        comodato.Status__c = 'Retorno da demo';
        
        Test.startTest();
        
        try{
            insert comodato;
        }
        catch(DmlException e){
            
        }
        Test.stopTest();
    }
}