force-app/main/default/objects/Demonstracao__c/Demonstracao__c.object-meta.xml
<CustomObject>
    <label>Comodato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comodatos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Demonstracao__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Rascunho&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rascunho</fullName>
            </value>
            <value>
                <fullName>Em aprovação</fullName>
            </value>
            <value>
                <fullName>Reprovado</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Em calibração</fullName>
            </value>
            <value>
                <fullName>Agendado</fullName>
            </value>
            <value>
                <fullName>Em comodato</fullName>
            </value>
            <value>
                <fullName>Retorno da demo</fullName>
                <label>Retorno</label>
            </value>
            <value>
                <fullName>Pendente de retorno</fullName>
            </value>
            <value>
                <fullName>Em Verificação Funcional</fullName>
            </value>
            <value>
                <fullName>Finalizado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Finalizado com Pendência</fullName>
                <isActive>false</isActive>
                <label>Finalizado com Pendência</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/criaPedidosDeConsumivelTest.cls
@IsTest(seeAllData=true)
public class criaPedidosDeConsumivelTest {
    
    @IsTest
    static void teste1(){
        Demonstracao__c demo = [SELECT ID, Status__c FROM Demonstracao__c WHERE ID = 'a0K6e00001ngJ4u'];
        demo.Status__c = 'Aprovado';
        update demo;
    }
    @IsTest
    static void teste2(){
        Demonstracao__c demo = [SELECT ID, Status__c FROM Demonstracao__c WHERE ID = 'a0KU400001HKYmQ'];
        demo.Status__c = 'Aprovado';
        update demo;
    }
}