force-app/main/default/objects/Compra_vinculada_ao_comodato__c/Compra_vinculada_ao_comodato__c.object-meta.xml
<CustomObject>
    <label>Venda vinculada ao comodato</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vendas vinculadas ao comodato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Compra_vinculada_ao_comodato__c/fields/Data_da_compra__c.field-meta.xml
<CustomField>
    <fullName>Data_da_compra__c</fullName>
    <label>Data da compra</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Compra_vinculada_ao_comodato__c/fields/M_s__c.field-meta.xml
<CustomField>
    <fullName>M_s__c</fullName>
    <label>Mês</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Compra_vinculada_ao_comodato__c/fields/Mes__c.field-meta.xml
<CustomField>
    <fullName>Mes__c</fullName>
    <label>Mês</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CompraVinculadaAoComodato.cls
public class CompraVinculadaAoComodato implements Schedulable {
    public void execute(SchedulableContext context) {
        // Realize sua consulta genérica aqui
        // Substitua esse código pelo seu próprio

        // Exemplo de consulta genérica
        List<Compra_vinculada_ao_comodato__c> CVCs = [SELECT Id, Mes__c, Data_da_compra__c FROM Compra_vinculada_ao_comodato__c WHERE M_s__c = 'Atual'];
        
        // Faça o processamento dos resultados da consulta
        // Substitua esse código pelo seu próprio

        for (Compra_vinculada_ao_comodato__c cvc : CVCs) {
            IF(cvc.Data_da_compra__c.month() != system.Today().month()){
                cvc.M_s__c = 'Passado';
            }
        }
        try{
            update CVCs;
        }
        catch(DmlException e){
            system.debug(e.getMessage());
        }
    }
}