force-app/main/default/objects/Ativos_do_Contrato__c/Ativos_do_Contrato__c.object-meta.xml
<CustomObject>
    <label>Ativo do Contrato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>N° de Registro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ativos do Contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ativos_do_Contrato__c/fields/Ativo_Locado__c.field-meta.xml
<CustomField>
    <fullName>Ativo_Locado__c</fullName>
    <label>Ativo Locado</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Ativos do Contrato</relationshipLabel>
    <relationshipName>Ativos_do_Contrato</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/Contrato_de_Servi_o__c.object-meta.xml
<CustomObject>
    <label>Contrato de Serviço</label>
    <nameField>
        <label>Nome do Contrato</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contratos de Serviços</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/TestCheckListContrato.cls
@isTest(seeAllData=true)
public class TestCheckListContrato {
 static testMethod void test_listagem_cs(){ 
        Contrato_de_Servi_o__c cs = new Contrato_de_Servi_o__c();
       /* cs = [
            SELECT 	Id
            FROM	Contrato_de_Servi_o__c
            WHERE	Id = '0WO3D000000D2R7'	// test:0WO3D000000D2R7 prod:0WO5A000000XezU
        ];
*/

        List<Ativos_do_Contrato__c> Ativosdocontrato = [
            SELECT  Ativo_Locado__c
            FROM    Ativos_do_Contrato__c
            WHERE   Id = 'a1h5A00000Dqt6W'
        ];

        test.startTest();
            ApexPages.StandardController stdCtrl = new ApexPages.StandardController(cs);
            ContratoChecklist registro = new ContratoChecklist(stdCtrl);
		test.stopTest();
    }
    
    
}