force-app/main/default/objects/Ativos_do_Contrato__c/Ativos_do_Contrato__c.object-meta.xml
<CustomObject>
    <label>Ativo do Contrato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>N° de Registro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ativos do Contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ativos_do_Contrato__c/fields/Ativo_Locado__c.field-meta.xml
<CustomField>
    <fullName>Ativo_Locado__c</fullName>
    <label>Ativo Locado</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Ativos do Contrato</relationshipLabel>
    <relationshipName>Ativos_do_Contrato</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ativos_do_Contrato__c/fields/Contrato_de_Servico__c.field-meta.xml
<CustomField>
    <fullName>Contrato_de_Servico__c</fullName>
    <label>Contrato de Serviço</label>
    <referenceTo>Contrato_de_Servi_o__c</referenceTo>
    <relationshipLabel>Ativos do Contrato</relationshipLabel>
    <relationshipName>Ativos_do_Contrato</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ativos_do_Contrato__c/fields/Data_de_entrega__c.field-meta.xml
<CustomField>
    <fullName>Data_de_entrega__c</fullName>
    <label>Data de entrega</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Ativos_do_Contrato__c/fields/Item_do_Contrato__c.field-meta.xml
<CustomField>
    <fullName>Item_do_Contrato__c</fullName>
    <label>Item do Contrato</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ativos_do_Contrato__c/fields/Local_de_Entrega__c.field-meta.xml
<CustomField>
    <fullName>Local_de_Entrega__c</fullName>
    <label>Local de Entrega</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Ativos_do_Contrato__c/fields/Valor_Unitario_Mensal__c.field-meta.xml
<CustomField>
    <fullName>Valor_Unitario_Mensal__c</fullName>
    <label>Valor Unitário Periódico</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Quantidade__c.field-meta.xml
<CustomField>
    <fullName>Quantidade__c</fullName>
    <label>Quantidade</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Valor_de_Venda__c.field-meta.xml
<CustomField>
    <fullName>Valor_de_Venda__c</fullName>
    <label>Valor de Venda</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/AtivosContratoLocacao.cls
public class AtivosContratoLocacao {
    @AuraEnabled
    public static string gerar(string SN, string contrato, decimal valor, integer quantidadeAtivo, string data, string local){
        
        List<String> lstString = SN.split(','); //Separa cada SN e adiciona em Lista
        List<Asset> ativos = [SELECT ID, Product2.Valor_de_venda__c FROM Asset WHERE SerialNumber in : lstString AND SerialNumber != ''];
        
        // Consultar o valor máximo de Item_do_Contrato__c
        AggregateResult result = [SELECT MAX(Item_do_Contrato__c) maxItem FROM Ativos_do_Contrato__c WHERE Contrato_de_Servico__c = :contrato];
        
        Integer maxItemContrato;
        if (result != null && result.get('maxItem') != null) {
            maxItemContrato = ((Decimal)result.get('maxItem')).intValue();
        }
        else{
            maxItemContrato = 0;
        }
        
        // Agora maxItemContrato contém o valor máximo de Item_do_Contrato__c
        System.debug('Máximo Item do Contrato: ' + maxItemContrato);        
        LIST<Ativos_do_Contrato__c> pds = new List<Ativos_do_Contrato__c>();
        
        Integer quantidade = 0;
        
        date dataEntrega;
        
        if(data != '')
            dataEntrega = Date.valueOf(data);
        else
            dataEntrega = null;
        
        //Cria a OT para cada número de série
        for(Asset ativo : ativos){
            Ativos_do_Contrato__c pContrato = new Ativos_do_Contrato__c(Contrato_de_Servico__c = contrato, Ativo_Locado__c = ativo.Id, Valor_Unitario_Mensal__c = valor, 
                                                                        Item_do_Contrato__c = maxItemContrato, Quantidade__c = 1, Data_de_entrega__c = dataEntrega, Local_de_Entrega__c = local);
            pds.add(pContrato);
            quantidade ++;
            maxItemContrato++;
        }
        try{
			insert pds;            
            return('Foram inseridos ' + quantidade + ' ativos com sucesso.');
        }
        catch(Exception e){
            return(e.getMessage());
        }
    }
}