force-app/main/default/objects/Ativos_do_Contrato__c/Ativos_do_Contrato__c.object-meta.xml
<CustomObject>
    <label>Ativo do Contrato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>N° de Registro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ativos do Contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ativos_do_Contrato__c/fields/Ativo_Locado__c.field-meta.xml
<CustomField>
    <fullName>Ativo_Locado__c</fullName>
    <label>Ativo Locado</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Ativos do Contrato</relationshipLabel>
    <relationshipName>Ativos_do_Contrato</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ativos_do_Contrato__c/fields/Contrato_de_Servico__c.field-meta.xml
<CustomField>
    <fullName>Contrato_de_Servico__c</fullName>
    <label>Contrato de Serviço</label>
    <referenceTo>Contrato_de_Servi_o__c</referenceTo>
    <relationshipLabel>Ativos do Contrato</relationshipLabel>
    <relationshipName>Ativos_do_Contrato</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ativos_do_Contrato__c/fields/Data_de_entrega__c.field-meta.xml
<CustomField>
    <fullName>Data_de_entrega__c</fullName>
    <label>Data de entrega</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Ativos_do_Contrato__c/fields/Item_do_Contrato__c.field-meta.xml
<CustomField>
    <fullName>Item_do_Contrato__c</fullName>
    <label>Item do Contrato</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ativos_do_Contrato__c/fields/Local_de_Entrega__c.field-meta.xml
<CustomField>
    <fullName>Local_de_Entrega__c</fullName>
    <label>Local de Entrega</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Ativos_do_Contrato__c/fields/Valor_Unitario_Mensal__c.field-meta.xml
<CustomField>
    <fullName>Valor_Unitario_Mensal__c</fullName>
    <label>Valor Unitário Periódico</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/AtivoDoContratoDuplicadoTest.cls
@isTest(SeeAllData=true)
private class AtivoDoContratoDuplicadoTest {
    
    static testMethod void testAdder() {
        Ativos_do_Contrato__c Atv = New Ativos_do_Contrato__c(Ativo_Locado__c='02i6e00000N5nRa', Contrato_de_Servico__c='a1Y6e00000BXtSd', Item_do_Contrato__c = 3, Valor_Unitario_Mensal__c = 1, Quantidade__c = 1, Data_de_entrega__c = system.today(), Local_de_Entrega__c = 'Teste' );
		insert Atv;
}
}