force-app/main/default/objects/Ativos_do_Contrato__c/Ativos_do_Contrato__c.object-meta.xml
<CustomObject>
    <label>Ativo do Contrato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>N° de Registro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ativos do Contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ativos_do_Contrato__c/fields/Ativo_Locado__c.field-meta.xml
<CustomField>
    <fullName>Ativo_Locado__c</fullName>
    <label>Ativo Locado</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Ativos do Contrato</relationshipLabel>
    <relationshipName>Ativos_do_Contrato</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ativos_do_Contrato__c/fields/Contrato_de_Servico__c.field-meta.xml
<CustomField>
    <fullName>Contrato_de_Servico__c</fullName>
    <label>Contrato de Serviço</label>
    <referenceTo>Contrato_de_Servi_o__c</referenceTo>
    <relationshipLabel>Ativos do Contrato</relationshipLabel>
    <relationshipName>Ativos_do_Contrato</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Checklist_do_Ativo__c/Checklist_do_Ativo__c.object-meta.xml
<CustomObject>
    <label>Item de Checklist do Ativo</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Nome de Checklist do Ativo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens de Checklist do Ativo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Checklist_do_Ativo__c/fields/Ativo_Relacionado__c.field-meta.xml
<CustomField>
    <fullName>Ativo_Relacionado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ativo Relacionado</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Itens de Checklist do Ativo</relationshipLabel>
    <relationshipName>Itens_de_Checklist_do_Ativo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Checklist_do_Ativo__c/fields/Conforme__c.field-meta.xml
<CustomField>
    <fullName>Conforme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Conforme</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Checklist_do_Ativo__c/fields/N_o_Conforme__c.field-meta.xml
<CustomField>
    <fullName>N_o_Conforme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Não Conforme</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Checklist_do_Ativo__c/fields/Nome_do_Item__c.field-meta.xml
<CustomField>
    <fullName>Nome_do_Item__c</fullName>
    <label>Nome do Item</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Checklist_do_Ativo__c/fields/Quantidade__c.field-meta.xml
<CustomField>
    <fullName>Quantidade__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Quantidade</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Gest_o_de_Documentos__c/Gest_o_de_Documentos__c.object-meta.xml
<CustomObject>
    <description>Objeto destinado ao controle da qualidade quanto a revisão e renovação dos documenos</description>
    <label>Gestão de Documento</label>
    <nameField>
        <displayFormat>GD - {0000}</displayFormat>
        <label>Nome de Gestão de Documentos</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gestão de Documentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ContratoChecklist.cls
public class ContratoChecklist{
    

    public List<Asset> Ativos {get;set;}
    public List<Gest_o_de_Documentos__c> documentos { get; set; }
    
    public ContratoChecklist(ApexPages.StandardController controlador){
        
        
		documentos = GestaoDocumentos.obterDocumentosVigentes();
        
        // Ativos do Contrato
        List<Ativos_do_Contrato__c> Ativosdocontrato = [
            SELECT  Ativo_Locado__c
            FROM    Ativos_do_Contrato__c
            WHERE   Contrato_de_Servico__c = :((SObject)controlador.getRecord()).Id
        ];
        
        List<Id> ListaAtivosdeContratoId = new List<Id>();
        
        for(Ativos_do_Contrato__c ativocontrato : Ativosdocontrato ){
        ListaAtivosdeContratoId.add(ativocontrato.Ativo_Locado__c);
        
        }
        
         Ativos = [
        SELECT Id, Name, (
            SELECT Nome_do_Item__c, Conforme__c, N_o_Conforme__c, Quantidade__c, N_de_Rastreio__c, Ativo_Relacionado__c
            FROM Itens_de_Checklist_do_Ativo__r
            
            )
        FROM Asset
        WHERE Id IN :ListaAtivosdeContratoId 
        ];
        
        
        
        
    }
  
    
}