force-app/main/default/objects/OpportunityLineItem/fields/Descricao_a_linha__c.field-meta.xml
<CustomField>
    <fullName>Descricao_a_linha__c</fullName>
    <label>Descrição da linha</label>
    <length>16000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Item_Pai__c.field-meta.xml
<CustomField>
    <fullName>Item_Pai__c</fullName>
    <label>Item pai</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Tipo_do_produto__c.field-meta.xml
<CustomField>
    <fullName>Tipo_do_produto__c</fullName>
    <formula>TEXT(PricebookEntry.Product2.Tipo_do_Produto__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo do produto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Ordem_de_trabalho__c.field-meta.xml
<CustomField>
    <fullName>Ordem_de_trabalho__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ordem de trabalho</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>_Tipo (del)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Descricao_da_linha__c.field-meta.xml
<CustomField>
    <fullName>Descricao_da_linha__c</fullName>
    <label>Descrição da linha</label>
    <length>16000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Item_Pai__c.field-meta.xml
<CustomField>
    <fullName>Item_Pai__c</fullName>
    <label>Item Pai</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Produto_Principal__c.field-meta.xml
<CustomField>
    <fullName>Produto_Principal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>_Produto Principal (del)</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Acessórios</relationshipLabel>
    <relationshipName>Produtos_do_pedido</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Novo</fullName>
            </value>
            <value>
                <fullName>Transferência Interna</fullName>
            </value>
            <value>
                <fullName>Pendência Interna</fullName>
            </value>
            <value>
                <fullName>Em Separação</fullName>
            </value>
            <value>
                <fullName>Galpão - Em Separação</fullName>
            </value>
            <value>
                <fullName>Separado</fullName>
            </value>
            <value>
                <fullName>Reservado</fullName>
            </value>
            <value>
                <fullName>OPR - ANALISE DE COMPRA</fullName>
            </value>
            <value>
                <fullName>CMP - COTAÇÃO DE COMPRA</fullName>
            </value>
            <value>
                <fullName>CMP - AG. ENTREGA FORNECEDOR</fullName>
            </value>
            <value>
                <fullName>Recebido Fornecedor</fullName>
            </value>
            <value>
                <fullName>Recebido A.T.</fullName>
            </value>
            <value>
                <fullName>Aguardando Faturamento</fullName>
            </value>
            <value>
                <fullName>Aguardando conferência</fullName>
            </value>
            <value>
                <fullName>Atendido</fullName>
            </value>
            <value>
                <fullName>Faturado</fullName>
            </value>
            <value>
                <fullName>Aguardando Coleta</fullName>
            </value>
            <value>
                <fullName>Em Avaliação Técnica</fullName>
            </value>
            <value>
                <fullName>CMP - AG. COMPRA IMPORTAÇÃO</fullName>
            </value>
            <value>
                <fullName>CMP - AG. COMPRA NACIONAL</fullName>
            </value>
            <value>
                <fullName>Em rota de entrega</fullName>
            </value>
            <value>
                <fullName>Entregue Cliente</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
                <label>OPR - CANCELADO</label>
            </value>
            <value>
                <fullName>Devolvido</fullName>
            </value>
            <value>
                <fullName>Recebido Parcial</fullName>
            </value>
            <value>
                <fullName>Recebido Total</fullName>
            </value>
            <value>
                <fullName>CMP - EM PRODUÇÃO FORN.</fullName>
            </value>
            <value>
                <fullName>CMP - EM COLETA PORTO/FORNECEDOR</fullName>
            </value>
            <value>
                <fullName>Em trânsito</fullName>
            </value>
            <value>
                <fullName>CMP - EM DESEMBARAÇO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Tipo_do_Produto__c.field-meta.xml
<CustomField>
    <fullName>Tipo_do_Produto__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CONSUMÍVEL</fullName>
            </value>
            <value>
                <fullName>EQUIPAMENTO</fullName>
            </value>
            <value>
                <fullName>FERRAMENTA</fullName>
            </value>
            <value>
                <fullName>IMPLANTE</fullName>
            </value>
            <value>
                <fullName>INSTRUMENTAL</fullName>
            </value>
            <value>
                <fullName>INSUMO</fullName>
            </value>
            <value>
                <fullName>KIT SERVIÇO</fullName>
            </value>
            <value>
                <fullName>MÓDULO</fullName>
            </value>
            <value>
                <fullName>MOVEIS</fullName>
            </value>
            <value>
                <fullName>OPCIONAL</fullName>
            </value>
            <value>
                <fullName>PEÇA</fullName>
            </value>
            <value>
                <fullName>SERVIÇO</fullName>
            </value>
            <value>
                <fullName>SET CIRURGICO</fullName>
            </value>
            <value>
                <fullName>SOFTWARE</fullName>
            </value>
            <value>
                <fullName>ACESSÓRIO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Item_Pai__c.field-meta.xml
<CustomField>
    <fullName>Item_Pai__c</fullName>
    <label>Item Pai</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACESSÓRIO</fullName>
            </value>
            <value>
                <fullName>CONSUMÍVEL</fullName>
            </value>
            <value>
                <fullName>EQUIPAMENTO</fullName>
            </value>
            <value>
                <fullName>KIT SERVIÇO</fullName>
            </value>
            <value>
                <fullName>MÓDULO</fullName>
            </value>
            <value>
                <fullName>MOVEIS</fullName>
            </value>
            <value>
                <fullName>OPCIONAL</fullName>
            </value>
            <value>
                <fullName>PEÇA</fullName>
            </value>
            <value>
                <fullName>SERVIÇO</fullName>
            </value>
            <value>
                <fullName>SOFTWARE</fullName>
            </value>
            <value>
                <fullName>OUTROS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PedImpPrdClass.cls
public class PedImpPrdClass {
    
    public static String FluxoInicial(Order pedido){
        String retorno = null;
        if (pedido.OpportunityId != null){
            retorno = ImpPrdOpp(pedido.OpportunityId, pedido);
        }else if(pedido.Ordem_de_trabalho__c != null){
            retorno = ImpPrdOt(pedido.Ordem_de_trabalho__c, pedido);
        }
        return retorno;
    }
    
    public static String ImpPrdOpp(Id oportunidade_id, Order pedido){
        
        String retorno = null;
        
        // obtém produtos da opp pai
        LIST<OpportunityLineItem> itens_opp = new LIST<OpportunityLineItem>();
        itens_opp = [
            SELECT	Item__c, Item_Pai__c, Product2Id, PriceBookEntryId, Descricao_a_linha__c, UnitPrice, Discount, Quantity, Product2.Tipo_do_Produto__c
            FROM    OpportunityLineItem
            WHERE	OpportunityId = :oportunidade_id
        ];
        
        // converte "produtos de opp" em "produtos de pedido" (!= serviço)
        List<OrderItem> itens_pedido = new LIST<OrderItem>();
        for(OpportunityLineItem item_opp : itens_opp){
            OrderItem item_pedido = new OrderItem(
                OrderId 				= pedido.Id,
                Item__c					= item_opp.Item__c,
                Item_Pai__c				= item_opp.Item_Pai__c,
                PriceBookEntryId		= item_opp.PriceBookEntryId,
                Descricao_da_linha__c 	= item_opp.Descricao_a_linha__c,
                UnitPrice 				= (item_opp.UnitPrice-((item_opp.UnitPrice/100)*(item_opp.Discount!=null?item_opp.Discount:0))),
                Quantity				= item_opp.Quantity,
                Status__c				= (pedido.Tipo__c=='Serviço')?'Aberto':'Novo'
            );
            itens_pedido.add(item_pedido);
        }
        
        // se NÃO tem produto != serviço
        if(itens_pedido.size() == 0){
            retorno = 'Essa Oportunidade não possui itens para pedido!!!';
        }
        
        // se TEM produto != serviço
        else{
            
            // insere "produtos de pedido"
            insert itens_pedido;
            
            // atualiza "produto pai" de "itens de pedido"
            for(Integer cont_1=0; cont_1<itens_pedido.size(); cont_1++){
                if(itens_pedido[cont_1].Item_Pai__c != null && itens_pedido[cont_1].Item_Pai__c != 0)
                for(Integer cont_2=0; cont_2<itens_pedido.size(); cont_2++)
                    if(itens_pedido[cont_1].Item_Pai__c == itens_pedido[cont_2].Item__c)
                        itens_pedido[cont_1].Produto_Principal__c = itens_pedido[cont_2].Id;
            } 
            update itens_pedido;
        }
        
        return retorno;
    }
    
    public static String ImpPrdOt(Id ordem_de_trabalho_id, Order pedido){
        String retorno = null;
        
        // obtém produtos da ot pai
        LIST<WorkOrderLineItem> itens_ot = new LIST<WorkOrderLineItem>();
        itens_ot = [
            SELECT	Product2Id, PriceBookEntryId, UnitPrice, Discount, Quantity, Product2.Tipo_do_Produto__c
            FROM    WorkOrderLineItem
            WHERE	WorkOrderId = :ordem_de_trabalho_id
        ];
        
        // converte "produtos de ot" em "produtos de pedido" (!= serviço)
        List<OrderItem> itens_pedido = new LIST<OrderItem>();
        for(WorkOrderLineItem item_ot : itens_ot){
            OrderItem item_pedido = new OrderItem(
                OrderId 				= pedido.Id,
                PriceBookEntryId		= item_ot.PriceBookEntryId,
                UnitPrice 				= (item_ot.UnitPrice-((item_ot.UnitPrice/100)*(item_ot.Discount!=null?item_ot.Discount:0))),
                Quantity				= item_ot.Quantity,
                Status__c				= (pedido.Tipo__c=='Serviço')?'Aberto':'Novo'
            );
            itens_pedido.add(item_pedido);
        }
        
        // se NÃO tem produto != serviço
        if(itens_pedido.size() == 0){
            retorno = 'Essa Ordem de Trabalho não possui itens para pedido!!!';
        }
        
        // se TEM produto != serviço
        else{
            
            // insere "produtos de pedido"
            insert itens_pedido;
        }
        
        return retorno;
    }
    
}