force-app/main/default/objects/Entrega_de_item__c/Entrega_de_item__c.object-meta.xml
<CustomObject>
    <label>Entrega de item</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número da entrega de item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Entregas de item</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Entrega_de_item__c/fields/Data_de_entrega__c.field-meta.xml
<CustomField>
    <fullName>Data_de_entrega__c</fullName>
    <label>Data de entrega</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Entrega_de_item__c/fields/Item_de_pedido_de_venda__c.field-meta.xml
<CustomField>
    <fullName>Item_de_pedido_de_venda__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Item de pedido de venda</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Entregas de item</relationshipLabel>
    <relationshipName>Entregas_de_produto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Entrega_de_item__c/fields/Quantidade_entregue__c.field-meta.xml
<CustomField>
    <fullName>Quantidade_entregue__c</fullName>
    <label>Quantidade entregue</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Data_de_entrega__c.field-meta.xml
<CustomField>
    <fullName>Data_de_entrega__c</fullName>
    <inlineHelpText>Da Hospcom ao Cliente, maior data dentre os itens.</inlineHelpText>
    <label>_Data de entrega (del)</label>
    <summarizedField>OrderItem.Data_de_entrega__c</summarizedField>
    <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Data_de_entrega__c.field-meta.xml
<CustomField>
    <fullName>Data_de_entrega__c</fullName>
    <inlineHelpText>Da Hospcom ao cliente, maior data dentre as entregas do item.</inlineHelpText>
    <label>_Data de entrega (del)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Data_de_requisicao__c.field-meta.xml
<CustomField>
    <fullName>Data_de_requisicao__c</fullName>
    <inlineHelpText>Ao Compras/Estoque, maior data dentre as requisições do item.</inlineHelpText>
    <label>_Data de requisição (del)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Descricao_da_linha__c.field-meta.xml
<CustomField>
    <fullName>Descricao_da_linha__c</fullName>
    <label>Descrição da linha</label>
    <length>16000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <formula>TEXT(PricebookEntry.Product2.Marca__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Marca</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Modelo__c.field-meta.xml
<CustomField>
    <fullName>Modelo__c</fullName>
    <formula>PricebookEntry.Modelo__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Modelo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Quantidade_entregue__c.field-meta.xml
<CustomField>
    <fullName>Quantidade_entregue__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Ao Cliente, soma total das entregas do item.</inlineHelpText>
    <label>_Quantidade entregue (del)</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Quantidade_requisitada__c.field-meta.xml
<CustomField>
    <fullName>Quantidade_requisitada__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Ao Compras/Estoque, soma total das requisições do item.</inlineHelpText>
    <label>_Quantidade requisitada (del)</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Novo</fullName>
            </value>
            <value>
                <fullName>Transferência Interna</fullName>
            </value>
            <value>
                <fullName>Pendência Interna</fullName>
            </value>
            <value>
                <fullName>Em Separação</fullName>
            </value>
            <value>
                <fullName>Galpão - Em Separação</fullName>
            </value>
            <value>
                <fullName>Separado</fullName>
            </value>
            <value>
                <fullName>Reservado</fullName>
            </value>
            <value>
                <fullName>OPR - ANALISE DE COMPRA</fullName>
            </value>
            <value>
                <fullName>CMP - COTAÇÃO DE COMPRA</fullName>
            </value>
            <value>
                <fullName>CMP - AG. ENTREGA FORNECEDOR</fullName>
            </value>
            <value>
                <fullName>Recebido Fornecedor</fullName>
            </value>
            <value>
                <fullName>Recebido A.T.</fullName>
            </value>
            <value>
                <fullName>Aguardando Faturamento</fullName>
            </value>
            <value>
                <fullName>Aguardando conferência</fullName>
            </value>
            <value>
                <fullName>Atendido</fullName>
            </value>
            <value>
                <fullName>Faturado</fullName>
            </value>
            <value>
                <fullName>Aguardando Coleta</fullName>
            </value>
            <value>
                <fullName>Em Avaliação Técnica</fullName>
            </value>
            <value>
                <fullName>CMP - AG. COMPRA IMPORTAÇÃO</fullName>
            </value>
            <value>
                <fullName>CMP - AG. COMPRA NACIONAL</fullName>
            </value>
            <value>
                <fullName>Em rota de entrega</fullName>
            </value>
            <value>
                <fullName>Entregue Cliente</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
                <label>OPR - CANCELADO</label>
            </value>
            <value>
                <fullName>Devolvido</fullName>
            </value>
            <value>
                <fullName>Recebido Parcial</fullName>
            </value>
            <value>
                <fullName>Recebido Total</fullName>
            </value>
            <value>
                <fullName>CMP - EM PRODUÇÃO FORN.</fullName>
            </value>
            <value>
                <fullName>CMP - EM COLETA PORTO/FORNECEDOR</fullName>
            </value>
            <value>
                <fullName>Em trânsito</fullName>
            </value>
            <value>
                <fullName>CMP - EM DESEMBARAÇO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>3GREEN</fullName>
            </value>
            <value>
                <fullName>7LIVES</fullName>
            </value>
            <value>
                <fullName>ABC</fullName>
            </value>
            <value>
                <fullName>ACCUMED</fullName>
            </value>
            <value>
                <fullName>ACROSS</fullName>
            </value>
            <value>
                <fullName>ACTE</fullName>
            </value>
            <value>
                <fullName>AEROGEN</fullName>
            </value>
            <value>
                <fullName>AGATA</fullName>
            </value>
            <value>
                <fullName>AGILE MED</fullName>
            </value>
            <value>
                <fullName>AIR LIQUIDE</fullName>
            </value>
            <value>
                <fullName>AIR SHIELD</fullName>
            </value>
            <value>
                <fullName>AJEL</fullName>
            </value>
            <value>
                <fullName>ALBAN</fullName>
            </value>
            <value>
                <fullName>ALIVE HEART</fullName>
            </value>
            <value>
                <fullName>ALLIAGE</fullName>
            </value>
            <value>
                <fullName>ALPHARAD</fullName>
            </value>
            <value>
                <fullName>ALVFLOR</fullName>
            </value>
            <value>
                <fullName>ALVIMÉDICA</fullName>
            </value>
            <value>
                <fullName>ANALYSER</fullName>
            </value>
            <value>
                <fullName>ANATONIC</fullName>
            </value>
            <value>
                <fullName>ANESTHESIA</fullName>
            </value>
            <value>
                <fullName>AOC</fullName>
            </value>
            <value>
                <fullName>APC</fullName>
            </value>
            <value>
                <fullName>APK</fullName>
            </value>
            <value>
                <fullName>APPLE</fullName>
            </value>
            <value>
                <fullName>ARJO</fullName>
            </value>
            <value>
                <fullName>ARJOHUNTLEIGH</fullName>
            </value>
            <value>
                <fullName>ARKTUS</fullName>
            </value>
            <value>
                <fullName>ARTIS</fullName>
            </value>
            <value>
                <fullName>ARTROCORP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Modelo__c.field-meta.xml
<CustomField>
    <fullName>Modelo__c</fullName>
    <label>Modelo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/URL_da_Imagem__c.field-meta.xml
<CustomField>
    <fullName>URL_da_Imagem__c</fullName>
    <defaultValue>&quot;https://hospcom.my.site.com/servlet/servlet.ImageServer?id=015310000080hog&amp;oid=00Di0000000JVhH&amp;lastMod=1502888568000&quot;</defaultValue>
    <label>URL da Imagem</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Requisicao_de_item__c/Requisicao_de_item__c.object-meta.xml
<CustomObject>
    <label>Destinação de item</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número da requisição de item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Destinações de item</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Requisicao_de_item__c/fields/Data_de_requisicao__c.field-meta.xml
<CustomField>
    <fullName>Data_de_requisicao__c</fullName>
    <label>Data de requisição</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Requisicao_de_item__c/fields/Item_de_pedido_de_venda__c.field-meta.xml
<CustomField>
    <fullName>Item_de_pedido_de_venda__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Item de pedido de venda</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipName>Requisicoes_de_Produtos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Requisicao_de_item__c/fields/Quantidade_requisitada__c.field-meta.xml
<CustomField>
    <fullName>Quantidade_requisitada__c</fullName>
    <label>Quantidade destinada</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Requisicao_de_item__c/recordTypes/Atender_venda_com_compra.recordType-meta.xml
<RecordType>
    <fullName>Atender_venda_com_compra</fullName>
    <active>true</active>
    <description>Suprir demanda de venda com compra.</description>
    <label>Suprir venda com compra</label>
</RecordType>

force-app/main/default/objects/Requisicao_de_item__c/recordTypes/Atender_venda_com_estoque.recordType-meta.xml
<RecordType>
    <fullName>Atender_venda_com_estoque</fullName>
    <active>true</active>
    <description>Suprir demanda de venda com estoque.</description>
    <label>Suprir venda com estoque</label>
</RecordType>

force-app/main/default/objects/Requisicao_de_item__c/recordTypes/Suprir_estoque_com_compra.recordType-meta.xml
<RecordType>
    <fullName>Suprir_estoque_com_compra</fullName>
    <active>true</active>
    <description>Suprir demanda de estoque com compra.</description>
    <label>Suprir estoque com compra</label>
</RecordType>

force-app/main/default/classes/AssistenteEdicaoMassa.cls
public class AssistenteEdicaoMassa {

	public Id 								registro_pai_id {get;set;}
	public Order							pedido{get;set;}
	public List<CItemVenda>					c_itens_venda{get;set;}
	
	public List<SelectOption>				status_todos {get;set;}
	public String							status {get;set;}
	
	public Boolean 							tem_erros {get;set;}
	public List<String> 					erros {get;set;}
	
	public AssistenteEdicaoMassa(ApexPages.StandardController controller) {
		Inicializa(controller);
		ObtemItensVenda();
	}
	
	public void Inicializa(ApexPages.StandardController controller){
		registro_pai_id = ((SObject)controller.getRecord()).Id;
		pedido = new Order();
		c_itens_venda = new List<CItemVenda>();
				
		status_todos = new List<SelectOption>();
		status_todos.add(new SelectOption('','Selecione o status...'));
		for(Schema.PicklistEntry valor_temp : OrderItem.Status__c.getDescribe().getPicklistValues())
			status_todos.add(new SelectOption(valor_temp.getLabel(),valor_temp.getLabel()));
		
		tem_erros = false;
	}
	
	public void ObtemItensVenda(){
        System.debug(registro_pai_id);
		pedido = [
			SELECT 	Id, OrderNumber
			FROM 	Order
			WHERE	Id = :registro_pai_id
		];
		
		List<OrderItem> itens_venda = new List<OrderItem>();
		itens_venda = [
			SELECT	Id, PriceBookEntry.Product2.Name, PriceBookEntry.Product2.ProductCode, Marca__c, Modelo__c, PriceBookEntry.Product2.URL_da_Imagem__c,
					Status__c, Descricao_da_linha__c, Quantity, UnitPrice, OrderId
			FROM	OrderItem
			WHERE	OrderId = :registro_pai_id
			ORDER BY PriceBookEntry.Product2.Name ASC, PriceBookEntry.Product2.Id ASC
		];
		
		// trabalha bordas de itens divididos e adiciona a lista GUI
		for(Integer cont=0; cont<itens_venda.size(); cont++){
			String antes = null, depois = null, borda = null;
			
			if(cont>0){
				if(itens_venda[cont-1].PriceBookEntry.Product2.Id == itens_venda[cont].PriceBookEntry.Product2.Id)
					antes = 'igual';
				else
					antes = 'diferente';
			}else
				antes = 'diferente';
			if((cont+1)<itens_venda.size()){
				if(itens_venda[cont+1].PriceBookEntry.Product2.Id == itens_venda[cont].PriceBookEntry.Product2.Id)
					depois = 'igual';
				else
					depois = 'diferente';
			}else
				depois = 'diferente';
			
			if(antes == 'igual' && depois == 'igual')
				borda = 'lateral';
			else if(antes == 'igual' && depois == 'diferente')
				borda = 'baixo';
			else if(antes == 'diferente' && depois == 'igual')
				borda = 'cima';
			else if(antes == 'diferente' && depois == 'diferente')
				borda = null;
			
			c_itens_venda.add(new CItemVenda(itens_venda[cont], false, itens_venda[cont].Quantity, itens_venda[cont].Status__c, borda));
		}
		
	}
	
	public pageReference Efetiva(){
		
		// variáveis auxiliares
		Savepoint restorepoint = Database.setSavepoint();
		List<String> status_novo = new list<String> {'Novo','Aberto'};
		List<String> status_divide = new list<String> {'Reservado','Aguardando Faturamento Cliente','Aguardando Faturamento','Aguardando Entrega Cliente','Entregue Cliente','Atendido'};
		List<OrderItem> itens_venda_upd = new List<OrderItem>();
		List<OrderItem> itens_venda_add = new List<OrderItem>();
		List<Requisicao_de_item__c> requisicoes_item = new List<Requisicao_de_item__c>();
		List<Entrega_de_item__c> entregas_item = new List<Entrega_de_item__c>();
		List<RecordType> tipos_registro = new List<RecordType>();
		Id record_estoque_compra, record_venda_compra, record_venda_estoque;
		
		// obtém tipos de registro
		tipos_registro = [
			SELECT	Id, DeveloperName
			FROM 	RecordType
			WHERE	SObjectType = 'Requisicao_de_item__c'
		];
		for(RecordType tipo_registro : tipos_registro){
			if(tipo_registro.DeveloperName == 'Suprir_estoque_com_compra')
				record_estoque_compra = tipo_registro.Id;
			else if (tipo_registro.DeveloperName == 'Atender_venda_com_compra')
				record_venda_compra = tipo_registro.Id;
            //Comentado para não inserir mais deste tipo deregistro
			else if (tipo_registro.DeveloperName == 'Atender_venda_com_estoque')
				record_venda_estoque = tipo_registro.Id;
		}
		
		// atualiza/divide itens, cria requisições
		for(CItemVenda c_item_venda : c_itens_venda){
			if( c_item_venda.status_old != c_item_venda.item_venda.Status__c && status_novo.contains(c_item_venda.status_old) && status_divide.contains(c_item_venda.item_venda.Status__c) && c_item_venda.qtd_atendida < c_item_venda.item_venda.Quantity){
				itens_venda_add.add(new OrderItem( OrderId = c_item_venda.item_venda.OrderId, PricebookEntryId = c_item_venda.item_venda.PricebookEntryId, Status__c = 'OPR - ANALISE DE COMPRA', Quantity = c_item_venda.item_venda.Quantity - c_item_venda.qtd_atendida, UnitPrice = c_item_venda.item_venda.UnitPrice, Descricao_da_linha__c = c_item_venda.item_venda.Descricao_da_linha__c));
				c_item_venda.item_venda.Quantity = c_item_venda.qtd_atendida;
			}
			
			if( c_item_venda.status_old != c_item_venda.item_venda.Status__c && status_novo.contains(c_item_venda.status_old) && !status_novo.contains(c_item_venda.item_venda.Status__c) && c_item_venda.item_venda.Status__c != 'OPR - ANALISE DE COMPRA' && c_item_venda.item_venda.Status__c != 'CMP - AG. ENTREGA FORNECEDOR' && c_item_venda.item_venda.Status__c != 'Cancelado'){
				requisicoes_item.add(new Requisicao_de_item__c(	RecordTypeId = record_venda_estoque, Quantidade_requisitada__c = c_item_venda.qtd_atendida,	Item_de_pedido_de_venda__c = c_item_venda.item_venda.Id, Data_de_requisicao__c = System.Today())); 
			}
			
			if(c_item_venda.status_old != c_item_venda.item_venda.Status__c && (c_item_venda.status_old != 'Entregue' && c_item_venda.status_old != 'Atendido') && (c_item_venda.item_venda.Status__c == 'Entregue' ||  c_item_venda.item_venda.Status__c == 'Atendido')){
				entregas_item.add(new Entrega_de_item__c( Quantidade_entregue__c = c_item_venda.qtd_atendida, Item_de_pedido_de_venda__c = c_item_venda.item_venda.Id, Data_de_entrega__c = System.Today()));
			}
			
			itens_venda_upd.add(c_item_venda.item_venda);
		}
		
		// salva na base de dados
		try{
			update itens_venda_upd;
		} catch(System.DMLException e){ ApexPages.addMessages(e); }
		
		//if(ApexPages.getMessages().size()==0 && requisicoes_item.size()>0){
		//	try{ insert requisicoes_item; }
        //    catch (System.DMLException e){ ApexPages.addMessages(e); }
		//}
		
		if(ApexPages.getMessages().size()==0 && entregas_item.size()>0){
			try{ insert entregas_item; }
			catch (System.DMLException e){ ApexPages.addMessages(e); }
		}
		
		if(ApexPages.getMessages().size()==0 && itens_venda_add.size()>0){
			try { insert itens_venda_add; }
			catch(System.DMLException e){ ApexPages.addMessages(e); }
		}
		
		// tratamento de erros
		
		PreparaErros();
		if(tem_erros){
			Database.rollback(restorepoint);
			return null;
		}
		else{
			PageReference tempPage = ApexPages.currentPage();            
			tempPage.setRedirect(true);
			return tempPage;
		}
	}
	
	public pageReference RetornarRegistro(){
		return new PageReference('/' + String.valueOf(pedido.Id));
	}

	
	public void PreparaErros(){
		tem_erros = ((ApexPages.getMessages().size()>0)?true:false);
        if(tem_erros){
            erros = new List<String>();
            for(Apexpages.Message mensagem: ApexPages.getMessages())
                erros.add(mensagem.getDetail());
        }
	}
	
	public class CItemVenda {
		public OrderItem	item_venda		{get;set;}
		public Boolean 		flag			{get;set;}
		public Decimal		qtd_atendida	{get;set;}
		public String		status_old		{get;set;}
		public String		borda			{get;set;}

		public CItemVenda(OrderItem item_venda_parm, Boolean flag_parm, Decimal qtd_atendida_parm, String status_old_parm, String borda_parm){
			item_venda 		= item_venda_parm;
			flag   			= flag_parm;
			qtd_atendida   	= qtd_atendida_parm;
			status_old   	= status_old_parm;
			borda			= borda_parm;
		}
	}

}