force-app/main/default/objects/Atividade__c/Atividade__c.object-meta.xml
<CustomObject>
    <label>Atividade</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Atividades</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Atividade__c/fields/Departamento__c.field-meta.xml
<CustomField>
    <fullName>Departamento__c</fullName>
    <label>Departamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administrativo</fullName>
            </value>
            <value>
                <fullName>Comercial</fullName>
            </value>
            <value>
                <fullName>Comitê de Operações</fullName>
            </value>
            <value>
                <fullName>Comitê Estratégico</fullName>
            </value>
            <value>
                <fullName>Compras</fullName>
            </value>
            <value>
                <fullName>Desenvolvimento</fullName>
            </value>
            <value>
                <fullName>Diretoria</fullName>
            </value>
            <value>
                <fullName>Financeiro</fullName>
            </value>
            <value>
                <fullName>Gestcom</fullName>
            </value>
            <value>
                <fullName>Governo</fullName>
            </value>
            <value>
                <fullName>Health Solutions</fullName>
            </value>
            <value>
                <fullName>Izu</fullName>
            </value>
            <value>
                <fullName>Logística</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Qualidade</fullName>
            </value>
            <value>
                <fullName>Recursos Humanos</fullName>
            </value>
            <value>
                <fullName>Serviço</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Backlog__c/Backlog__c.object-meta.xml
<CustomObject>
    <label>Backlog</label>
    <nameField>
        <displayFormat>TKT - {0000}</displayFormat>
        <label>Ticket</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Backlogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Backlog__c/fields/Atividade__c.field-meta.xml
<CustomField>
    <fullName>Atividade__c</fullName>
    <label>Atividade</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Backlog__c/fields/Atribuido__c.field-meta.xml
<CustomField>
    <fullName>Atribuido__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Atribuido à</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <value>001i00000085QYbAAM</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Backlogs</relationshipLabel>
    <relationshipName>Backlogs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Backlog__c/fields/Bandeira__c.field-meta.xml
<CustomField>
    <fullName>Bandeira__c</fullName>
    <formula>CASE(
    TEXT(Prioridade__c),
    &quot;Imediato&quot;, &quot;⚫&quot;,  
    &quot;Alto&quot;, &quot;🔴&quot;,      
    &quot;Médio&quot;, &quot;🟡&quot;,     
    &quot;Baixo&quot;, &quot;🟢&quot;,     
    &quot;⚪&quot;               
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Bandeira</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Backlog__c/fields/cssCard__c.field-meta.xml
<CustomField>
    <fullName>cssCard__c</fullName>
    <formula>IF(
   (
     ( IF(
           ISBLANK(Ticket_Finalizado_Em__c), 
           NOW(), 
           Ticket_Finalizado_Em__c
       ) 
     - Ticket_Criado_Em__c
     ) * 24
   ) &gt; Tempo_de_Execucao__c,
   &quot;kanban-card red-card&quot;,
   &quot;kanban-card&quot;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>cssCard</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Backlog__c/fields/Excedeu_Tempo_Estimado__c.field-meta.xml
<CustomField>
    <fullName>Excedeu_Tempo_Estimado__c</fullName>
    <formula>IF(
  NOT(ISBLANK(Data_Estimada_de_T_rmino__c)),
  IF(
    ISBLANK(Ticket_Finalizado_Em__c),
    NOW() &gt; DATETIMEVALUE(Data_Estimada_de_T_rmino__c),
    Ticket_Finalizado_Em__c &gt; DATETIMEVALUE(Data_Estimada_de_T_rmino__c)
  ),
  FALSE
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Excedeu Tempo Estimado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Backlog__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Novo</fullName>
            </value>
            <value>
                <fullName>Em Refinamento</fullName>
            </value>
            <value>
                <fullName>Em Desenvolvimento</fullName>
            </value>
            <value>
                <fullName>Analise de Qualidade</fullName>
            </value>
            <value>
                <fullName>Finalizado</fullName>
            </value>
            <value>
                <fullName>Recusado</fullName>
            </value>
            <value>
                <fullName>Aguardando Validação</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Backlog__c/fields/Tempo_de_Atendimento__c.field-meta.xml
<CustomField>
    <fullName>Tempo_de_Atendimento__c</fullName>
    <formula>IF(
    NOT(ISBLANK(Ticket_Finalizado_Em__c)),

    /* Quando finalizado */
    IF(FLOOR(Ticket_Finalizado_Em__c - Ticket_Criado_Em__c) &gt; 0,
        TEXT(FLOOR(Ticket_Finalizado_Em__c - Ticket_Criado_Em__c)) &amp; &quot; dias, &quot;,
        &quot;&quot;
    ) &amp;
    IF(FLOOR(MOD((Ticket_Finalizado_Em__c - Ticket_Criado_Em__c) * 24, 24)) &gt; 0,
        TEXT(FLOOR(MOD((Ticket_Finalizado_Em__c - Ticket_Criado_Em__c) * 24, 24))) &amp; &quot; horas, &quot;,
        &quot;&quot;
    ) &amp;
    TEXT(FLOOR(MOD((Ticket_Finalizado_Em__c - Ticket_Criado_Em__c) * 24 * 60, 60))) &amp; &quot; minutos&quot;,

    /* Quando ainda aberto */
    IF(FLOOR(TODAY() - DATEVALUE(Ticket_Criado_Em__c)) &gt; 0,
        TEXT(FLOOR(TODAY() - DATEVALUE(Ticket_Criado_Em__c))) &amp; &quot; dias, &quot;,
        &quot;&quot;
    ) &amp;
    IF(FLOOR(MOD((NOW() - Ticket_Criado_Em__c) * 24, 24)) &gt; 0,
        TEXT(FLOOR(MOD((NOW() - Ticket_Criado_Em__c) * 24, 24))) &amp; &quot; horas, &quot;,
        &quot;&quot;
    ) &amp;
    TEXT(FLOOR(MOD((NOW() - Ticket_Criado_Em__c) * 24 * 60, 60))) &amp; &quot; minutos&quot;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tempo de Atendimento</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Backlog__c/fields/Tempo_de_Execucao__c.field-meta.xml
<CustomField>
    <fullName>Tempo_de_Execucao__c</fullName>
    <inlineHelpText>Tempo nescessario para execução do ticket, em horas</inlineHelpText>
    <label>Tempo de Execução (Em Horas)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Backlog__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bug</fullName>
            </value>
            <value>
                <fullName>Melhoria</fullName>
            </value>
            <value>
                <fullName>Novo Recurso</fullName>
            </value>
            <value>
                <fullName>Projeto</fullName>
            </value>
            <value>
                <fullName>Solicitação</fullName>
            </value>
            <value>
                <fullName>Administrativo</fullName>
                <isActive>false</isActive>
                <label>Administrativo</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/KanbanBacklogController.cls
public without sharing class KanbanBacklogController {
    
    @AuraEnabled(cacheable=true)
    public static List<Backlog__c> getBacklog() {
        return [
            SELECT Id, 
                   Name, 
                   Atividade__c, 
                   Atribuido__c, 
                   Atribuido__r.Name, 
                   Status__c, 
                   Bandeira__c, 
                   Tipo__c, 
                   Tempo_de_Atendimento__c,
                   Departamento__c,
                   Tempo_de_Execucao__c,
                   Excedeu_Tempo_Estimado__c,
                   cssCard__c
            FROM Backlog__c
        ];
    }

    @AuraEnabled
    public static void updateStatus(Id recordId, String newStatus) {
        Backlog__c b = [SELECT Id, Status__c FROM Backlog__c WHERE Id = :recordId];
        b.Status__c = newStatus;
        update b;
    }
}