force-app/main/default/objects/Quote/fields/Prazo_de_Entrega__c.field-meta.xml
<CustomField>
    <fullName>Prazo_de_Entrega__c</fullName>
    <label>Prazo de entrega</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Prazo_de_garantia__c.field-meta.xml
<CustomField>
    <fullName>Prazo_de_garantia__c</fullName>
    <defaultValue>&quot;Equipamentos &quot; + TEXT(12) + &quot; meses, acessórios &quot; + TEXT(3) + &quot; meses&quot;</defaultValue>
    <inlineHelpText>Ex: Equipamentos 12 meses, acessórios 3 meses, etc...</inlineHelpText>
    <label>Prazo de garantia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Prazo_de_garantia_acessorios__c.field-meta.xml
<CustomField>
    <fullName>Prazo_de_garantia_acessorios__c</fullName>
    <defaultValue>TEXT(3) + &apos; meses&apos;</defaultValue>
    <inlineHelpText>Ex: 3 meses</inlineHelpText>
    <label>Prazo de garantia dos acessórios</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Prazo_de_garantia_dos_equipamentos__c.field-meta.xml
<CustomField>
    <fullName>Prazo_de_garantia_dos_equipamentos__c</fullName>
    <defaultValue>TEXT(12) + &apos; meses&apos;</defaultValue>
    <inlineHelpText>Ex: 12 meses</inlineHelpText>
    <label>Prazo de garantia dos equipamentos</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CotacaoValidacaoTest.cls
@isTest(seeAllData=true)
public class CotacaoValidacaoTest {
    
	@isTest private static void run(){
        Quote cotacao = new Quote();
        cotacao.OpportunityId = '0065A00001YANlPQAX';
        cotacao.Name = 'Teste';
        cotacao.Data_de_emissao__c = system.today();
        cotacao.Prazo_de_garantia__c = 'Equipamentos 12 meses, acessórios 3 meses';
        cotacao.Prazo_de_Entrega__c = '12 dias';
        cotacao.Prazo_de_garantia_dos_equipamentos__c = '12 meses';
        cotacao.Prazo_de_garantia_acessorios__c = '3 meses';
        insert cotacao;
        
        delete cotacao;
    }
}