force-app/main/default/objects/HISTORICO_DE_REVISAO__c/HISTORICO_DE_REVISAO__c.object-meta.xml
<CustomObject>
    <label>Histórico de Revisão</label>
    <nameField>
        <label>Histórico de Revisão</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Históricos de Revisão</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HISTORICO_DE_REVISAO__c/fields/Empresa__c.field-meta.xml
<CustomField>
    <fullName>Empresa__c</fullName>
    <label>Empresa</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABC1-GO</fullName>
                <label>ABC-GO</label>
            </value>
            <value>
                <fullName>ABC2-MT</fullName>
                <label>ABC-MT</label>
            </value>
            <value>
                <fullName>ABC-TO</fullName>
                <label>ABC3-TO</label>
            </value>
            <value>
                <fullName>HEALTH_SOLUTION</fullName>
                <label>HEALTH SOLUTION</label>
            </value>
            <value>
                <fullName>HOSPCOM1</fullName>
                <label>HOSPCOM</label>
            </value>
            <value>
                <fullName>HOSPCOM2-DF</fullName>
                <label>HOSPCOM-DF</label>
            </value>
            <value>
                <fullName>GDB1</fullName>
                <label>GDB</label>
            </value>
            <value>
                <fullName>HOSPCOM-153</fullName>
            </value>
            <value>
                <fullName>HOSPCOM5MT</fullName>
                <label>HOSPCOM-MT</label>
            </value>
            <value>
                <fullName>HOSPCOM-SOROCABA</fullName>
            </value>
            <value>
                <fullName>GESTCOM</fullName>
            </value>
            <value>
                <fullName>HOSPCOM MG</fullName>
            </value>
            <value>
                <fullName>GDB-GO</fullName>
            </value>
            <value>
                <fullName>HOSPCOM-AM</fullName>
            </value>
            <value>
                <fullName>HOSPCOM-SP CAPITAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HISTORICO_DE_REVISAO__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HISTORICO_DE_REVISAO__c/fields/Natureza_da_Alteracao__c.field-meta.xml
<CustomField>
    <fullName>Natureza_da_Alteracao__c</fullName>
    <label>Natureza da Alteração</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HISTORICO_DE_REVISAO__c/fields/Procedimento_do_Sistema_de_Qualidade__c.field-meta.xml
<CustomField>
    <fullName>Procedimento_do_Sistema_de_Qualidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Procedimento do Sistema de Qualidade</label>
    <referenceTo>PSQ__c</referenceTo>
    <relationshipLabel>HISTÓRICOS DE REVSÃÕES</relationshipLabel>
    <relationshipName>HIST_RICOS_DE_REVS_ES</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PSQ__c/PSQ__c.object-meta.xml
<CustomObject>
    <label>Procedimento do Sistema de Qualidade</label>
    <nameField>
        <label>Título do Documento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Procedimentos do Sistema de Qualidade</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PSQ__c/fields/Procedimento_do_Sistema_de_Qualidade__c.field-meta.xml
<CustomField>
    <fullName>Procedimento_do_Sistema_de_Qualidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Procedimento em vigência</label>
    <referenceTo>PSQ__c</referenceTo>
    <relationshipLabel>Procedimentos do Sistema de Qualidade</relationshipLabel>
    <relationshipName>Procedimentos_do_Sistema_de_Qualidade</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PSQ__c/fields/PSQ__c.field-meta.xml
<CustomField>
    <fullName>PSQ__c</fullName>
    <displayFormat>PSQ - {0000}</displayFormat>
    <label>PSQ</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/PSQ__c/recordTypes/PSQ.recordType-meta.xml
<RecordType>
    <fullName>PSQ</fullName>
    <active>true</active>
    <description>Procedimento do Sistema de Qualidade</description>
    <label>PSQ</label>
</RecordType>

force-app/main/default/classes/PSQControllerTest.cls
@isTest
private class PSQControllerTest {
    
    /*static void testPSQController() {
        // Crie um registro fictício de PSQ__c
        PSQ__c psqRecord = new PSQ__c(Name = 'PSQ Test');
        
        // produção lmd: a0g6e00000JW5s6AAD
        // Sandbox lmd: a0g530000062hwWAAQ
        
        insert psqRecord;

        // Crie alguns registros fictícios de HISTORICO_DE_REVISAO__c associados ao PSQ__c
        List<HISTORICO_DE_REVISAO__c> historicos = new List<HISTORICO_DE_REVISAO__c>();
        historicos.add(new HISTORICO_DE_REVISAO__c(
            Item__c = 'Item 1',
            Natureza_da_Alteracao__c = 'Alteração 1',
            Empresa__c = 'GDB',
            Data__c = System.today(),
            Procedimento_do_Sistema_de_Qualidade__c = psqRecord.Id
        ));
        historicos.add(new HISTORICO_DE_REVISAO__c(
            Item__c = 'Item 2',
            Natureza_da_Alteracao__c = 'Alteração 2',
            Data__c = System.today().addDays(-1),
            
            Empresa__c = 'GDB',
            Procedimento_do_Sistema_de_Qualidade__c = psqRecord.Id
        ));
        insert historicos;

        // Crie uma instância do controlador
       // PSQController controller = new PSQController();

        // Atribua o ID do PSQ__c ao controlador
     //controller.psqId = psqRecord.Id;       

        // Verifique se a lista de historicosOrdenados não está vazia
        //System.assertNotEquals(0, controller.historicosOrdenados.size());
    }*/
    @isTest
    static void testPSQController() { String a ='';}
}