force-app/main/default/objects/HISTORICO_DE_REVISAO__c/HISTORICO_DE_REVISAO__c.object-meta.xml
<CustomObject>
    <label>Histórico de Revisão</label>
    <nameField>
        <label>Histórico de Revisão</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Históricos de Revisão</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HISTORICO_DE_REVISAO__c/fields/Empresa__c.field-meta.xml
<CustomField>
    <fullName>Empresa__c</fullName>
    <label>Empresa</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABC1-GO</fullName>
                <label>ABC-GO</label>
            </value>
            <value>
                <fullName>ABC2-MT</fullName>
                <label>ABC-MT</label>
            </value>
            <value>
                <fullName>ABC-TO</fullName>
                <label>ABC3-TO</label>
            </value>
            <value>
                <fullName>HEALTH_SOLUTION</fullName>
                <label>HEALTH SOLUTION</label>
            </value>
            <value>
                <fullName>HOSPCOM1</fullName>
                <label>HOSPCOM</label>
            </value>
            <value>
                <fullName>HOSPCOM2-DF</fullName>
                <label>HOSPCOM-DF</label>
            </value>
            <value>
                <fullName>GDB1</fullName>
                <label>GDB</label>
            </value>
            <value>
                <fullName>HOSPCOM-153</fullName>
            </value>
            <value>
                <fullName>HOSPCOM5MT</fullName>
                <label>HOSPCOM-MT</label>
            </value>
            <value>
                <fullName>HOSPCOM-SOROCABA</fullName>
            </value>
            <value>
                <fullName>GESTCOM</fullName>
            </value>
            <value>
                <fullName>HOSPCOM MG</fullName>
            </value>
            <value>
                <fullName>GDB-GO</fullName>
            </value>
            <value>
                <fullName>HOSPCOM-AM</fullName>
            </value>
            <value>
                <fullName>HOSPCOM-SP CAPITAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/HISTORICO_DE_REVISAO__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HISTORICO_DE_REVISAO__c/fields/Natureza_da_Alteracao__c.field-meta.xml
<CustomField>
    <fullName>Natureza_da_Alteracao__c</fullName>
    <label>Natureza da Alteração</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HISTORICO_DE_REVISAO__c/fields/Procedimento_Operacional_Padr_o__c.field-meta.xml
<CustomField>
    <fullName>Procedimento_Operacional_Padr_o__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Procedimento Operacional Padrão</label>
    <referenceTo>POP__c</referenceTo>
    <relationshipLabel>Históricos de Revisão</relationshipLabel>
    <relationshipName>Hist_ricos_de_Revis_o</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Usu_rio__c.field-meta.xml
<CustomField>
    <fullName>Usu_rio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Instrutor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Pedidos2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/POP__c/POP__c.object-meta.xml
<CustomObject>
    <description>O Procedimento Operacional Padrão (POP) é um objeto central para a gestão de processos padronizados, garantindo conformidade, rastreabilidade e controle de versões. Segue um ciclo de vida definido por status imutáveis (Elaboração, Em Aprovação, Vigente), com funcionalidades específicas para:
Criação e Edição:
Inicia em Elaboração, permitindo vinculação de Instruções de Serviço via componente PopIsSearch e objeto auxiliar POP com Instrução de Serviço.
Bloqueia edições durante a aprovação e, quando Vigente, só permite alterações via cópias (novo registro em Elaboração).
Gestão de Versões:
Utiliza a classe PopCriaAtualizacao para criar réplicas atualizadas, preservando o histórico e relacionamentos. documentos, instruções vinculadas.
Processo de Aprovação:
Transições automáticas de status garantem imutabilidade do registro aprovado.
Integridade de Dados:
Relacionamentos muitos-para-muitos com Instruções de Serviço são gerenciados por fluxos automatizados, evitando duplicidadade</description>
    <label>Procedimento Operacional Padrão</label>
    <nameField>
        <label>Título do Documento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Procedimentos Operacionais Padrão</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/POP__c/fields/Aplica_o__c.field-meta.xml
<CustomField>
    <fullName>Aplica_o__c</fullName>
    <label>2. Aplicação</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/POP__c/fields/Condi_es_Espec_ficas__c.field-meta.xml
<CustomField>
    <fullName>Condi_es_Espec_ficas__c</fullName>
    <label>6.Condições Específicas</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/POP__c/fields/Condi_es_Gerais__c.field-meta.xml
<CustomField>
    <fullName>Condi_es_Gerais__c</fullName>
    <label>5.Condições Gerais</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/POP__c/fields/Defini_es__c.field-meta.xml
<CustomField>
    <fullName>Defini_es__c</fullName>
    <label>3.Definições</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/POP__c/fields/Equipamentos_e_Softwares__c.field-meta.xml
<CustomField>
    <fullName>Equipamentos_e_Softwares__c</fullName>
    <label>4.Equipamentos e Softwares</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/POP__c/fields/Formul_rios_Anexos_e_Documentos__c.field-meta.xml
<CustomField>
    <fullName>Formul_rios_Anexos_e_Documentos__c</fullName>
    <label>8.Formulários, Anexos e Documentos</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/POP__c/fields/Procedimento_Operacional_Padr_o__c.field-meta.xml
<CustomField>
    <fullName>Procedimento_Operacional_Padr_o__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Procedimento Operacional Padrão</label>
    <referenceTo>POP__c</referenceTo>
    <relationshipLabel>Procedimentos Operacionais Padrão</relationshipLabel>
    <relationshipName>Procedimentos_Operacionais_Padr_o</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/POP__c/fields/Qualidade__c.field-meta.xml
<CustomField>
    <fullName>Qualidade__c</fullName>
    <label>Qualidade</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/POP__c/fields/Recursos_Humanos__c.field-meta.xml
<CustomField>
    <fullName>Recursos_Humanos__c</fullName>
    <label>Recursos Humanos</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/POP__c/fields/Responsabilidade_e_Autoridade__c.field-meta.xml
<CustomField>
    <fullName>Responsabilidade_e_Autoridade__c</fullName>
    <label>7.Responsabilidade e Autoridade</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/POP__c/fields/Revisor__c.field-meta.xml
<CustomField>
    <fullName>Revisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Revisor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Procedimentos_Operacionais_Padr_o1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/POP__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Elaboração</fullName>
                <default>true</default>
                <label>Elaboração</label>
            </value>
            <value>
                <fullName>Revisão</fullName>
            </value>
            <value>
                <fullName>Aprovação</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Em vigência</fullName>
            </value>
            <value>
                <fullName>Obsoleto</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/POP__c/fields/T_tulo_do_Documento__c.field-meta.xml
<CustomField>
    <fullName>T_tulo_do_Documento__c</fullName>
    <label>Título do Documento</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/POP__c/fields/Usu_rio__c.field-meta.xml
<CustomField>
    <fullName>Usu_rio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuário</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Procedimentos_Operacionais_Padr_o2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/listagem_hrPop.cls
public with sharing class listagem_hrPop {
    
    
        public POP__c pop {get; set;}
        public List<HISTORICO_DE_REVISAO__c> historico {get; set;}
    
        public listagem_hrPop(ApexPages.StandardController controller){
           Id objeto_pai = ((SObject)controller.getRecord()).Id;
        
        if(objeto_pai.getSObjectType().getDescribe().getName() == 'POP__c')
            listagem_hr((POP__c)controller.getRecord());
        }
    
       
         
    public void listagem_hr(POP__c pop){
        
                pop = [
                        SELECT  Id, Qualidade__c,Recursos_Humanos__c,Status__c,T_tulo_do_Documento__c,Name,Usu_rio__c, Revisor__c, Aplica_o__c,Defini_es__c, Equipamentos_e_Softwares__c,Condi_es_Gerais__c, Condi_es_Espec_ficas__c, Responsabilidade_e_Autoridade__c, Formul_rios_Anexos_e_Documentos__c        
                        FROM    POP__c
                        WHERE   Id = :pop.Id
                ][0];	
                
        List<HISTORICO_DE_REVISAO__c> itens_hr_ord = new List<HISTORICO_DE_REVISAO__c>();    
        itens_hr_ord = [
            SELECT  Id,Procedimento_Operacional_Padr_o__c, Empresa__c, Name, Item__c, Natureza_da_Alteracao__c, Data__c
            
            FROM  HISTORICO_DE_REVISAO__c
            WHERE    Procedimento_Operacional_Padr_o__c = :pop.Id
                        ORDER BY Data__c ASC
        ];
        
        //Decimal qtd_cont=0;
                historico = new List<HISTORICO_DE_REVISAO__c>(); 
        
                for(integer cont_1=0; cont_1<itens_hr_ord.size(); cont_1++){
                 historico.add(itens_hr_ord[cont_1]);
                }
        
       
    
}
}