force-app/main/default/objects/HISTORICO_DE_REVISAO__c/HISTORICO_DE_REVISAO__c.object-meta.xml
<CustomObject>
    <label>Histórico de Revisão</label>
    <nameField>
        <label>Histórico de Revisão</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Históricos de Revisão</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HISTORICO_DE_REVISAO__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HISTORICO_DE_REVISAO__c/fields/L_M_D__c.field-meta.xml
<CustomField>
    <fullName>L_M_D__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>L.M.D</label>
    <referenceTo>L_M_D__c</referenceTo>
    <relationshipLabel>Históricos de Revisão</relationshipLabel>
    <relationshipName>Hist_ricos_de_Revis_o</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/HISTORICO_DE_REVISAO__c/fields/Natureza_da_Alteracao__c.field-meta.xml
<CustomField>
    <fullName>Natureza_da_Alteracao__c</fullName>
    <label>Natureza da Alteração</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/L_M_D__c/L_M_D__c.object-meta.xml
<CustomObject>
    <description>Lista Mestre de Documentação</description>
    <label>L.M.D</label>
    <nameField>
        <label>Empresa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>L.M.D</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/L_M_D__c/fields/C_digo_do_Documento__c.field-meta.xml
<CustomField>
    <fullName>C_digo_do_Documento__c</fullName>
    <label>Código do Documento</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/L_M_D__c/fields/T_tulo_do_Documento__c.field-meta.xml
<CustomField>
    <fullName>T_tulo_do_Documento__c</fullName>
    <label>Título do Documento</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LMDDetailController.cls
public with sharing class LMDDetailController {
    public L_M_D__c lmDetail { get; set; }

    public List<Historico_de_Revisao__c> getOrderedHistRicos() {
        List<Historico_de_Revisao__c> histRicos = [SELECT Id, Item__c, Natureza_da_Alteracao__c, Data__c
                                                   FROM Historico_de_Revisao__c
                                                   WHERE L_M_D__c = :lmDetail.Id
                                                   ORDER BY Data__c ASC];
        return histRicos;
    }

    public LMDDetailController() {
        // Construtor padrão vazio
    }

    public LMDDetailController(ApexPages.StandardController controller) {
        lmDetail = [SELECT Id, T_tulo_do_Documento__c, C_digo_do_Documento__c FROM L_M_D__c WHERE Id = :controller.getId()];
    }
}