force-app/main/default/objects/HISTORICO_DE_REVISAO__c/HISTORICO_DE_REVISAO__c.object-meta.xml
<CustomObject>
    <label>Histórico de Revisão</label>
    <nameField>
        <label>Histórico de Revisão</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Históricos de Revisão</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HISTORICO_DE_REVISAO__c/fields/Procedimento_do_Sistema_de_Qualidade__c.field-meta.xml
<CustomField>
    <fullName>Procedimento_do_Sistema_de_Qualidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Procedimento do Sistema de Qualidade</label>
    <referenceTo>PSQ__c</referenceTo>
    <relationshipLabel>HISTÓRICOS DE REVSÃÕES</relationshipLabel>
    <relationshipName>HIST_RICOS_DE_REVS_ES</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PSQ__c/PSQ__c.object-meta.xml
<CustomObject>
    <label>Procedimento do Sistema de Qualidade</label>
    <nameField>
        <label>Título do Documento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Procedimentos do Sistema de Qualidade</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PSQ__c/fields/Procedimento_do_Sistema_de_Qualidade__c.field-meta.xml
<CustomField>
    <fullName>Procedimento_do_Sistema_de_Qualidade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Procedimento em vigência</label>
    <referenceTo>PSQ__c</referenceTo>
    <relationshipLabel>Procedimentos do Sistema de Qualidade</relationshipLabel>
    <relationshipName>Procedimentos_do_Sistema_de_Qualidade</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PSQ__c/fields/PSQ__c.field-meta.xml
<CustomField>
    <fullName>PSQ__c</fullName>
    <displayFormat>PSQ - {0000}</displayFormat>
    <label>PSQ</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/PSQ__c/recordTypes/PSQ.recordType-meta.xml
<RecordType>
    <fullName>PSQ</fullName>
    <active>true</active>
    <description>Procedimento do Sistema de Qualidade</description>
    <label>PSQ</label>
</RecordType>

force-app/main/default/classes/listagem_hrTest.cls
@isTest(seealldata = true)

public class listagem_hrTest {

    //LMD Sandbox: a0g530000062hwWAAQ
    //LMD Produção: a0g6e00000J4FLSAA3
    @isTest
    static void testListagem_hr() {
        // Crie um registro de PSQ__c para teste
        PSQ__c psqRecord = new PSQ__c(
            Name = 'Test PSQ Record',
			C_digo_do_Documento__c = '1231232'
            
        );
        insert psqRecord;

        // Crie alguns registros de HISTORICO_DE_REVISAO__c relacionados ao PSQ__c
        HISTORICO_DE_REVISAO__c historico1 = new HISTORICO_DE_REVISAO__c(
            Procedimento_do_Sistema_de_Qualidade__c = psqRecord.Id
        );
        insert historico1;

        HISTORICO_DE_REVISAO__c historico2 = new HISTORICO_DE_REVISAO__c(
            Procedimento_do_Sistema_de_Qualidade__c = psqRecord.Id
            
        );
        insert historico2;

        // Crie um objeto StandardController para o registro de PSQ__c
        ApexPages.StandardController controller = new ApexPages.StandardController(psqRecord);

        // Crie uma instância da classe listagem_hr
        listagem_hr listagem = new listagem_hr(controller);

        // Execute o método listagem_hr(PSQ__c psq) da classe
        listagem.listagem_hr(psqRecord);

      
    }
    
}