force-app/main/default/objects/HISTORICO_DE_REVISAO__c/HISTORICO_DE_REVISAO__c.object-meta.xml
<CustomObject>
    <label>Histórico de Revisão</label>
    <nameField>
        <label>Histórico de Revisão</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Históricos de Revisão</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HISTORICO_DE_REVISAO__c/fields/Procedimento_Operacional_Padr_o__c.field-meta.xml
<CustomField>
    <fullName>Procedimento_Operacional_Padr_o__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Procedimento Operacional Padrão</label>
    <referenceTo>POP__c</referenceTo>
    <relationshipLabel>Históricos de Revisão</relationshipLabel>
    <relationshipName>Hist_ricos_de_Revis_o</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/POP__c/POP__c.object-meta.xml
<CustomObject>
    <description>O Procedimento Operacional Padrão (POP) é um objeto central para a gestão de processos padronizados, garantindo conformidade, rastreabilidade e controle de versões. Segue um ciclo de vida definido por status imutáveis (Elaboração, Em Aprovação, Vigente), com funcionalidades específicas para:
Criação e Edição:
Inicia em Elaboração, permitindo vinculação de Instruções de Serviço via componente PopIsSearch e objeto auxiliar POP com Instrução de Serviço.
Bloqueia edições durante a aprovação e, quando Vigente, só permite alterações via cópias (novo registro em Elaboração).
Gestão de Versões:
Utiliza a classe PopCriaAtualizacao para criar réplicas atualizadas, preservando o histórico e relacionamentos. documentos, instruções vinculadas.
Processo de Aprovação:
Transições automáticas de status garantem imutabilidade do registro aprovado.
Integridade de Dados:
Relacionamentos muitos-para-muitos com Instruções de Serviço são gerenciados por fluxos automatizados, evitando duplicidadade</description>
    <label>Procedimento Operacional Padrão</label>
    <nameField>
        <label>Título do Documento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Procedimentos Operacionais Padrão</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/POP__c/fields/Procedimento_Operacional_Padr_o__c.field-meta.xml
<CustomField>
    <fullName>Procedimento_Operacional_Padr_o__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Procedimento Operacional Padrão</label>
    <referenceTo>POP__c</referenceTo>
    <relationshipLabel>Procedimentos Operacionais Padrão</relationshipLabel>
    <relationshipName>Procedimentos_Operacionais_Padr_o</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PSQ__c/PSQ__c.object-meta.xml
<CustomObject>
    <label>Procedimento do Sistema de Qualidade</label>
    <nameField>
        <label>Título do Documento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Procedimentos do Sistema de Qualidade</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PSQ__c/fields/POP__c.field-meta.xml
<CustomField>
    <fullName>POP__c</fullName>
    <displayFormat>POP - {0000}</displayFormat>
    <label>POP</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/PSQ__c/fields/PSQ__c.field-meta.xml
<CustomField>
    <fullName>PSQ__c</fullName>
    <displayFormat>PSQ - {0000}</displayFormat>
    <label>PSQ</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/PSQ__c/recordTypes/PSQ.recordType-meta.xml
<RecordType>
    <fullName>PSQ</fullName>
    <active>true</active>
    <description>Procedimento do Sistema de Qualidade</description>
    <label>PSQ</label>
</RecordType>

force-app/main/default/classes/listagem_hrPopTest.cls
@isTest(seealldata = true)

public class listagem_hrPopTest {

    //LMD Sandbox: a0g530000062hwWAAQ
    //LMD Produção: a0g6e00000J4FLSAA3
    @isTest
    static void testListagem_hr() {
        // Crie um registro de PSQ__c para teste
        POP__c popRecord = new POP__c(
            Name = 'Test PSQ Record',
      C_digo_do_Documento__c = '1231232'
            
        );
        insert popRecord;

        // Crie alguns registros de HISTORICO_DE_REVISAO__c relacionados ao PSQ__c
        HISTORICO_DE_REVISAO__c historico1 = new HISTORICO_DE_REVISAO__c(
            Procedimento_Operacional_Padr_o__c = popRecord.Id
        );
        insert historico1;

        HISTORICO_DE_REVISAO__c historico2 = new HISTORICO_DE_REVISAO__c(
            Procedimento_Operacional_Padr_o__c = popRecord.Id
            
        );
        insert historico2;

        // Crie um objeto StandardController para o registro de PSQ__c
        ApexPages.StandardController controller = new ApexPages.StandardController(popRecord);

        // Crie uma instância da classe listagem_hr
        listagem_hrPop listagem = new listagem_hrPop(controller);

        // Execute o método listagem_hr(PSQ__c psq) da classe
        listagem.listagem_hr(popRecord);

      
    }
    
}