force-app/main/default/objects/Order/fields/Entrega_parcial__c.field-meta.xml
<CustomField>
    <fullName>Entrega_parcial__c</fullName>
    <label>Entrega parcial</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Autorizada</fullName>
            </value>
            <value>
                <fullName>Não Autorizada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Faturamento_Feito__c.field-meta.xml
<CustomField>
    <fullName>Faturamento_Feito__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Empresa do grupo Hospcom que irá faturar o pedido.</inlineHelpText>
    <label>Faturamento feito</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Faturamentos Feitos (de pedidos)</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Necess_rio_Treinamento__c.field-meta.xml
<CustomField>
    <fullName>Necess_rio_Treinamento__c</fullName>
    <label>Necessário Treinamento?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SIM</fullName>
            </value>
            <value>
                <fullName>NÃO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Pedido_da_Linha_de_OPME__c.field-meta.xml
<CustomField>
    <fullName>Pedido_da_Linha_de_OPME__c</fullName>
    <label>Pedido da Linha de OPME?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SIM</fullName>
            </value>
            <value>
                <fullName>NÃO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Prazo_de_entrega__c.field-meta.xml
<CustomField>
    <fullName>Prazo_de_entrega__c</fullName>
    <label>Prazo de entrega</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PedidosVendedor</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/recordTypes/Representacao.recordType-meta.xml
<RecordType>
    <fullName>Representacao</fullName>
    <active>true</active>
    <description>Para acompanhamento dos pedidos de venda faturados direto pelo fabricante</description>
    <label>Representação</label>
</RecordType>

force-app/main/default/objects/OrderItem/fields/Acao_interna__c.field-meta.xml
<CustomField>
    <fullName>Acao_interna__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ação interna</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Prazo_de_entrega__c.field-meta.xml
<CustomField>
    <fullName>Prazo_de_entrega__c</fullName>
    <label>Prazo de entrega</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Novo</fullName>
            </value>
            <value>
                <fullName>Transferência Interna</fullName>
            </value>
            <value>
                <fullName>Pendência Interna</fullName>
            </value>
            <value>
                <fullName>Em Separação</fullName>
            </value>
            <value>
                <fullName>Galpão - Em Separação</fullName>
            </value>
            <value>
                <fullName>Separado</fullName>
            </value>
            <value>
                <fullName>Reservado</fullName>
            </value>
            <value>
                <fullName>OPR - ANALISE DE COMPRA</fullName>
            </value>
            <value>
                <fullName>CMP - COTAÇÃO DE COMPRA</fullName>
            </value>
            <value>
                <fullName>CMP - AG. ENTREGA FORNECEDOR</fullName>
            </value>
            <value>
                <fullName>Recebido Fornecedor</fullName>
            </value>
            <value>
                <fullName>Recebido A.T.</fullName>
            </value>
            <value>
                <fullName>Aguardando Faturamento</fullName>
            </value>
            <value>
                <fullName>Aguardando conferência</fullName>
            </value>
            <value>
                <fullName>Atendido</fullName>
            </value>
            <value>
                <fullName>Faturado</fullName>
            </value>
            <value>
                <fullName>Aguardando Coleta</fullName>
            </value>
            <value>
                <fullName>Em Avaliação Técnica</fullName>
            </value>
            <value>
                <fullName>CMP - AG. COMPRA IMPORTAÇÃO</fullName>
            </value>
            <value>
                <fullName>CMP - AG. COMPRA NACIONAL</fullName>
            </value>
            <value>
                <fullName>Em rota de entrega</fullName>
            </value>
            <value>
                <fullName>Entregue Cliente</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
                <label>OPR - CANCELADO</label>
            </value>
            <value>
                <fullName>Devolvido</fullName>
            </value>
            <value>
                <fullName>Recebido Parcial</fullName>
            </value>
            <value>
                <fullName>Recebido Total</fullName>
            </value>
            <value>
                <fullName>CMP - EM PRODUÇÃO FORN.</fullName>
            </value>
            <value>
                <fullName>CMP - EM COLETA PORTO/FORNECEDOR</fullName>
            </value>
            <value>
                <fullName>Em trânsito</fullName>
            </value>
            <value>
                <fullName>CMP - EM DESEMBARAÇO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Ignorar_erros__c.field-meta.xml
<CustomField>
    <fullName>Ignorar_erros__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ignorar erros</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TestedoItemPreenchimento.cls
@isTest(seeAllData=true)
    private class TestedoItemPreenchimento {
        @isTest static void Teste4(){
            
            Order pedidoOriginal = [
              SELECT   AccountId, EffectiveDate, Status,  Necess_rio_Treinamento__c, Pedido_da_Linha_de_OPME__c, 
                  Entrega_parcial__c, Prazo_de_entrega__c, Vendedor__c
              FROM  Order
              WHERE   Id = '8015A000002fQTw'
            ];
            Order pedidoNovo = new Order();
            pedidoNovo.AccountId = pedidoOriginal.AccountId;
            pedidoNovo.EffectiveDate = pedidoOriginal.EffectiveDate;
            pedidoNovo.Necess_rio_Treinamento__c= pedidoOriginal.Necess_rio_Treinamento__c;
            pedidoNovo.Pedido_da_Linha_de_OPME__c= pedidoOriginal.Pedido_da_Linha_de_OPME__c;
            pedidoNovo.Prazo_de_entrega__c= pedidoOriginal.Prazo_de_entrega__c;
            pedidoNovo.Vendedor__c= pedidoOriginal.Vendedor__c;
            pedidoNovo.Status = 'Rascunho';
            pedidoNovo.Faturamento_Feito__c = '001i00000084BQy';
            pedidoNovo.RecordTypeId = [SELECT Id FROM RecordType WHERE SObjectType='Order' AND DeveloperName='Representacao'].Id;
            pedidoNovo.Pricebook2Id = '01s5A000004fbcR';
            insert pedidoNovo;
            
            update new User(Id=UserInfo.getUserId(), Ignorar_erros__c=true);
            pedidoNovo.Status = 'Ativo';
            pedidoNovo.Acao_interna__c=  true;
            update pedidoNovo;
        
            List<OrderItem> itensNovosPedido = new List<OrderItem>();
            itensNovosPedido.add(new OrderItem(
              OrderId = pedidoNovo.Id,
              Status__c = 'Novo',
              PricebookEntryId = '01u5A000017V1WBQA0',
              Item__c = 1,
              Quantity = 1,
              UnitPrice = 1
            ));
        
            insert itensNovosPedido;
        
            for(OrderItem itemPedido : itensNovosPedido){
              itemPedido.Status__c = 'Reservado';
            }
            update itensNovosPedido;

           
          }
    }