force-app/main/default/objects/Order/fields/Entrega_parcial__c.field-meta.xml
<CustomField>
    <fullName>Entrega_parcial__c</fullName>
    <label>Entrega parcial</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Autorizada</fullName>
            </value>
            <value>
                <fullName>Não Autorizada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Faturamento_Feito__c.field-meta.xml
<CustomField>
    <fullName>Faturamento_Feito__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Empresa do grupo Hospcom que irá faturar o pedido.</inlineHelpText>
    <label>Faturamento feito</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Faturamentos Feitos (de pedidos)</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Necess_rio_Treinamento__c.field-meta.xml
<CustomField>
    <fullName>Necess_rio_Treinamento__c</fullName>
    <label>Necessário Treinamento?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SIM</fullName>
            </value>
            <value>
                <fullName>NÃO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Pedido_da_Linha_de_OPME__c.field-meta.xml
<CustomField>
    <fullName>Pedido_da_Linha_de_OPME__c</fullName>
    <label>Pedido da Linha de OPME?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SIM</fullName>
            </value>
            <value>
                <fullName>NÃO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Prazo_de_entrega__c.field-meta.xml
<CustomField>
    <fullName>Prazo_de_entrega__c</fullName>
    <label>Prazo de entrega</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PedidosVendedor</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ValidaCriacaoDemoTest.cls
@isTest(seeAllData=true)
public class ValidaCriacaoDemoTest {
  
  @isTest static void Teste1(){
    Order pedidoOriginal = [
      SELECT   QuoteId, AccountId, EffectiveDate, Status,  Necess_rio_Treinamento__c, Pedido_da_Linha_de_OPME__c, 
          Entrega_parcial__c, Prazo_de_entrega__c, Faturamento_Feito__c, Vendedor__c
      FROM  Order
      WHERE   Id = '8016e0000094TLuAAM'
    ];
    Order pedidoNovo = pedidoOriginal.clone(false, false, false, false);
    pedidoNovo.RecordTypeId = Schema.getGlobalDescribe().get('Order').getDescribe().getRecordTypeInfosByName().get('Demonstração').getRecordTypeId();
    pedidoNovo.EffectiveDate = SYSTEM.today();
    pedidoNovo.Status = 'Rascunho';
      try{
          insert pedidoNovo;
      }
      catch(DmlException e){
          
      }

  }
}