force-app/main/default/objects/Order/fields/Nome_completo__c.field-meta.xml
<CustomField>
    <fullName>Nome_completo__c</fullName>
    <label>Nome completo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recrutamento__c/Recrutamento__c.object-meta.xml
<CustomObject>
    <label>Recrutamento</label>
    <nameField>
        <displayFormat>R{0}</displayFormat>
        <label>Número do Recrutamento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recrutamentos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Recrutamento__c/fields/Idade__c.field-meta.xml
<CustomField>
    <fullName>Idade__c</fullName>
    <formula>FLOOR(TODAY() - Data_de_nascimento__c)/ 365</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Idade</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Recrutamento__c/fields/Imagem_del__c.field-meta.xml
<CustomField>
    <fullName>Imagem_del__c</fullName>
    <formula>IMAGE(&apos;/servlet/servlet.FileDownload?file=&apos; + AttachmentId__c, &quot;Imagem&quot;, 130, 130)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Imagem</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recrutamento__c/fields/Nome_Completo__c.field-meta.xml
<CustomField>
    <fullName>Nome_Completo__c</fullName>
    <formula>Nome_do_candidato__c + &apos; &apos; + Sobrenome__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nome Completo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recrutamento__c/fields/Nome_do_candidato__c.field-meta.xml
<CustomField>
    <fullName>Nome_do_candidato__c</fullName>
    <label>Nome</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recrutamento__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em Análise</fullName>
                <default>true</default>
                <label>Em Análise</label>
            </value>
            <value>
                <fullName>Selecionado</fullName>
            </value>
            <value>
                <fullName>Reprovado</fullName>
            </value>
            <value>
                <fullName>Cadastro de Reserva</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recrutamento__c/fields/Telefone_do_Candidato__c.field-meta.xml
<CustomField>
    <fullName>Telefone_do_Candidato__c</fullName>
    <inlineHelpText>Formato: (XX) xXXXX-XXXX</inlineHelpText>
    <label>Telefone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Recrutamento__c/fields/Vaga_Dispon_vel__c.field-meta.xml
<CustomField>
    <fullName>Vaga_Dispon_vel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vaga Concorrida</label>
    <referenceTo>Vagas_Dispon_veis__c</referenceTo>
    <relationshipLabel>Recrutamentos</relationshipLabel>
    <relationshipName>Recrutamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vagas_Dispon_veis__c/Vagas_Dispon_veis__c.object-meta.xml
<CustomObject>
    <label>Vaga Disponível</label>
    <nameField>
        <displayFormat>V{0}</displayFormat>
        <label>Vaga Disponível</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vagas Disponíveis</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vagas_Dispon_veis__c/fields/Cargo_Ofertado__c.field-meta.xml
<CustomField>
    <fullName>Cargo_Ofertado__c</fullName>
    <label>Cargo Ofertado</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vagas_Dispon_veis__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aguardando aprovação</fullName>
                <default>true</default>
                <label>Aguardando aprovação</label>
            </value>
            <value>
                <fullName>Divulgação da Vaga</fullName>
            </value>
            <value>
                <fullName>Triagem de Candidatos</fullName>
            </value>
            <value>
                <fullName>Entrevista com RH</fullName>
            </value>
            <value>
                <fullName>Entrevista com Gestor</fullName>
            </value>
            <value>
                <fullName>Proposta e ASO</fullName>
            </value>
            <value>
                <fullName>Processo Admissional</fullName>
            </value>
            <value>
                <fullName>Assinatura de Documentos</fullName>
            </value>
            <value>
                <fullName>Finalizada</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
            <value>
                <fullName>Análise de Entrevistas</fullName>
                <isActive>false</isActive>
                <label>Análise de Entrevistas</label>
            </value>
            <value>
                <fullName>Período de Contratação</fullName>
                <isActive>false</isActive>
                <label>Período de Contratação</label>
            </value>
            <value>
                <fullName>Período de Entrevistas</fullName>
                <isActive>false</isActive>
                <label>Período de Entrevistas</label>
            </value>
            <value>
                <fullName>Seleção para Entrevistas</fullName>
                <isActive>false</isActive>
                <label>Seleção para Entrevistas</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BuscaCandidato.cls
public with sharing class BuscaCandidato {
    public List<Recrutamento__c> Records{get;set;}
    public String pesquisa {get;set;}
    public String status {get;set;}
    public String searchKey {get;set;}
    public BuscaCandidato() {
    }
    public void search(){
        if (status != null){
        string searchquery='select Id, Name, Nome_do_Candidato__c, Nome_Completo__c, Sobrenome__c, Imagem_del__c, Telefone_do_Candidato__c, Idade__c, Status__c,  Vaga_Dispon_vel__r.Cargo_Ofertado__c FROM Recrutamento__c WHERE (Vaga_Dispon_vel__r.Cargo_Ofertado__c like \'%'+searchKey+'%\'and Nome_Completo__c like \'%'+pesquisa+'%\') and Status__c =:status ORDER BY Name';
            Records = Database.query(searchquery);
        }
        else {
            string searchquery='select Id, Name, Nome_do_Candidato__c, Sobrenome__c, Nome_Completo__c, Imagem_del__c, Telefone_do_Candidato__c, Idade__c, Status__c, Vaga_Dispon_vel__r.Cargo_Ofertado__c FROM Recrutamento__c WHERE (Vaga_Dispon_vel__r.Cargo_Ofertado__c like \'%'+searchKey+'%\'and Nome_Completo__c like \'%'+pesquisa+'%\') ORDER BY Name';
            Records = Database.query(searchquery); 
        }
      }
     public void clear(){
         if (Records != null) {Records.clear();
         status = null;
         searchKey = null;
	     pesquisa = null;
         }                  
         else{ 
         status = null;
         searchKey = null;
         pesquisa = null;
         }
     }
     public void alfabetica(){
        string searchquery= + 'ORDER BY Nome_do_Candidato__c';
            }
}