force-app/main/default/objects/SolicitacaodeCadastro__c/SolicitacaodeCadastro__c.object-meta.xml
<CustomObject>
    <label>Solicitação de Cadastro</label>
    <nameField>
        <displayFormat>S{0}</displayFormat>
        <label>Nome de Solicitação de Cadastro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solicitações de Cadastro</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SolicitacaodeCadastro__c/fields/C_d_Fabricante__c.field-meta.xml
<CustomField>
    <fullName>C_d_Fabricante__c</fullName>
    <label>Cód. Fabricante</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SolicitacaodeCadastro__c/fields/Categoria_de_compra__c.field-meta.xml
<CustomField>
    <fullName>Categoria_de_compra__c</fullName>
    <inlineHelpText>Apenas para produtos de uso/consumo.</inlineHelpText>
    <label>Categoria de compra</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Categoria_de_compra</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SolicitacaodeCadastro__c/fields/Descricao__c.field-meta.xml
<CustomField>
    <fullName>Descricao__c</fullName>
    <label>Descrição</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/SolicitacaodeCadastro__c/fields/Fam_lia__c.field-meta.xml
<CustomField>
    <fullName>Fam_lia__c</fullName>
    <label>Família</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ALTO FLUXO</fullName>
            </value>
            <value>
                <fullName>ANESTESIA</fullName>
            </value>
            <value>
                <fullName>APOIO A MOBILIDADE</fullName>
            </value>
            <value>
                <fullName>ARCO CIRURGICO</fullName>
            </value>
            <value>
                <fullName>ASPIRADORES</fullName>
            </value>
            <value>
                <fullName>BERÇOS</fullName>
            </value>
            <value>
                <fullName>BERÇOS AQUECIDOS</fullName>
            </value>
            <value>
                <fullName>BPAP</fullName>
            </value>
            <value>
                <fullName>CADEIRAS</fullName>
            </value>
            <value>
                <fullName>CAMAS</fullName>
            </value>
            <value>
                <fullName>CAMAS HOSPITALARES</fullName>
            </value>
            <value>
                <fullName>CARDIOLOGIA</fullName>
            </value>
            <value>
                <fullName>CIRURGIA MINIMAMENTE INVASIVA</fullName>
            </value>
            <value>
                <fullName>CIRURGIA ROBÓTICA</fullName>
            </value>
            <value>
                <fullName>CONCENTRADORES</fullName>
            </value>
            <value>
                <fullName>ELETROCIRURGIA</fullName>
            </value>
            <value>
                <fullName>ELETRO CIRURGIA</fullName>
                <isActive>false</isActive>
                <label>ELETRO CIRURGIA</label>
            </value>
            <value>
                <fullName>ELEVADORES</fullName>
            </value>
            <value>
                <fullName>ENDOSCOPIA</fullName>
            </value>
            <value>
                <fullName>FOCOS CIRÚRGICOS</fullName>
            </value>
            <value>
                <fullName>FOTOTERAPIA</fullName>
            </value>
            <value>
                <fullName>GERAL</fullName>
            </value>
            <value>
                <fullName>GINECOLOGIA</fullName>
            </value>
            <value>
                <fullName>HIGIENE</fullName>
            </value>
            <value>
                <fullName>IMAGEM</fullName>
            </value>
            <value>
                <fullName>INALADORES</fullName>
            </value>
            <value>
                <fullName>INCUBADORAS</fullName>
            </value>
            <value>
                <fullName>INFUSÃO</fullName>
            </value>
            <value>
                <fullName>INSTRUMENTAIS CIRURGICOS</fullName>
            </value>
            <value>
                <fullName>INSTRUMENTAIS DESCARTÁVEIS</fullName>
            </value>
            <value>
                <fullName>OUTROS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SolicitacaodeCadastro__c/fields/Linha__c.field-meta.xml
<CustomField>
    <fullName>Linha__c</fullName>
    <label>Linha</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>linha</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SolicitacaodeCadastro__c/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>3GREEN</fullName>
            </value>
            <value>
                <fullName>7LIVES</fullName>
            </value>
            <value>
                <fullName>ABC</fullName>
            </value>
            <value>
                <fullName>ACCUMED</fullName>
            </value>
            <value>
                <fullName>ACROSS</fullName>
            </value>
            <value>
                <fullName>ACTE</fullName>
            </value>
            <value>
                <fullName>AEROGEN</fullName>
            </value>
            <value>
                <fullName>AGATA</fullName>
            </value>
            <value>
                <fullName>AGILE MED</fullName>
            </value>
            <value>
                <fullName>AIR LIQUIDE</fullName>
            </value>
            <value>
                <fullName>AIR SHIELD</fullName>
            </value>
            <value>
                <fullName>AJEL</fullName>
            </value>
            <value>
                <fullName>ALBAN</fullName>
            </value>
            <value>
                <fullName>ALIVE HEART</fullName>
            </value>
            <value>
                <fullName>ALLIAGE</fullName>
            </value>
            <value>
                <fullName>ALPHARAD</fullName>
            </value>
            <value>
                <fullName>ALVIMÉDICA</fullName>
            </value>
            <value>
                <fullName>ANALYSER</fullName>
            </value>
            <value>
                <fullName>ANATONIC</fullName>
            </value>
            <value>
                <fullName>ANESTHESIA</fullName>
            </value>
            <value>
                <fullName>AOC</fullName>
            </value>
            <value>
                <fullName>APC</fullName>
            </value>
            <value>
                <fullName>APK</fullName>
            </value>
            <value>
                <fullName>APPLE</fullName>
            </value>
            <value>
                <fullName>ARJO</fullName>
            </value>
            <value>
                <fullName>ARJOHUNTLEIGH</fullName>
            </value>
            <value>
                <fullName>ARKTUS</fullName>
            </value>
            <value>
                <fullName>ARTIS</fullName>
            </value>
            <value>
                <fullName>ARTROCORP</fullName>
            </value>
            <value>
                <fullName>ASPEN PHARMA</fullName>
            </value>
            <value>
                <fullName>OUTROS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SolicitacaodeCadastro__c/fields/Modelo__c.field-meta.xml
<CustomField>
    <fullName>Modelo__c</fullName>
    <label>Modelo</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SolicitacaodeCadastro__c/fields/Nome__c.field-meta.xml
<CustomField>
    <fullName>Nome__c</fullName>
    <label>Nome</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SolicitacaodeCadastro__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACESSÓRIO</fullName>
            </value>
            <value>
                <fullName>CONSUMÍVEL</fullName>
            </value>
            <value>
                <fullName>EQUIPAMENTO</fullName>
            </value>
            <value>
                <fullName>IMPLANTE</fullName>
            </value>
            <value>
                <fullName>INSTRUMENTAL</fullName>
            </value>
            <value>
                <fullName>INSUMO</fullName>
            </value>
            <value>
                <fullName>KIT SERVIÇO</fullName>
            </value>
            <value>
                <fullName>MÓDULO</fullName>
            </value>
            <value>
                <fullName>MOVEIS</fullName>
            </value>
            <value>
                <fullName>OPCIONAL</fullName>
            </value>
            <value>
                <fullName>PEÇA</fullName>
            </value>
            <value>
                <fullName>SERVIÇO</fullName>
            </value>
            <value>
                <fullName>SOFTWARE</fullName>
            </value>
            <value>
                <fullName>OUTROS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SolicitacaodeCadastro__c/fields/Unidade_de_medida__c.field-meta.xml
<CustomField>
    <fullName>Unidade_de_medida__c</fullName>
    <label>Unidade de medida</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AMPOLA</fullName>
            </value>
            <value>
                <fullName>BALDE</fullName>
            </value>
            <value>
                <fullName>BANDEJ</fullName>
            </value>
            <value>
                <fullName>BARRA</fullName>
            </value>
            <value>
                <fullName>BISNAG</fullName>
            </value>
            <value>
                <fullName>BLOCO</fullName>
            </value>
            <value>
                <fullName>BOBINA</fullName>
            </value>
            <value>
                <fullName>BOMB</fullName>
            </value>
            <value>
                <fullName>CAPS</fullName>
            </value>
            <value>
                <fullName>CART</fullName>
            </value>
            <value>
                <fullName>CENTO</fullName>
            </value>
            <value>
                <fullName>CJ</fullName>
            </value>
            <value>
                <fullName>CM</fullName>
            </value>
            <value>
                <fullName>CM2</fullName>
            </value>
            <value>
                <fullName>CX</fullName>
            </value>
            <value>
                <fullName>CX10</fullName>
            </value>
            <value>
                <fullName>CX100</fullName>
            </value>
            <value>
                <fullName>CX15</fullName>
            </value>
            <value>
                <fullName>CX2</fullName>
            </value>
            <value>
                <fullName>CX20</fullName>
            </value>
            <value>
                <fullName>CX25</fullName>
            </value>
            <value>
                <fullName>CX3</fullName>
            </value>
            <value>
                <fullName>CX5</fullName>
            </value>
            <value>
                <fullName>CX50</fullName>
            </value>
            <value>
                <fullName>DISP</fullName>
            </value>
            <value>
                <fullName>DUZIA</fullName>
            </value>
            <value>
                <fullName>EMBAL</fullName>
            </value>
            <value>
                <fullName>FARDO</fullName>
            </value>
            <value>
                <fullName>FOLHA</fullName>
            </value>
            <value>
                <fullName>FRASCO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SolicitacaodeCadastro__c/fields/Valor_de_Venda__c.field-meta.xml
<CustomField>
    <fullName>Valor_de_Venda__c</fullName>
    <label>Valor de Venda</label>
    <precision>10</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/globalValueSets/Categoria_de_compra.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ALIMENTAÇÃO</fullName>
    </customValue>
    <customValue>
        <fullName>ASSINATURAS JORNAIS, LIVROS E REVISTAS</fullName>
    </customValue>
    <customValue>
        <fullName>BRINDES</fullName>
    </customValue>
    <customValue>
        <fullName>CONFRATERNIZAÇÃO E EVENTOS</fullName>
    </customValue>
    <customValue>
        <fullName>CONSTRUÇÃO CIVIL</fullName>
    </customValue>
    <customValue>
        <fullName>CONSULTORIA E ASSESSORIAS</fullName>
    </customValue>
    <customValue>
        <fullName>CORREIOS E TELEGRÁFOS</fullName>
    </customValue>
    <customValue>
        <fullName>CURSOS E TREINAMENTOS</fullName>
    </customValue>
    <customValue>
        <fullName>DEDETIZAÇÃO, DESRATIZAÇÃO E DESCUPINIZAÇÃO</fullName>
    </customValue>
    <customValue>
        <fullName>EMBALAGEM</fullName>
    </customValue>
    <customValue>
        <fullName>EPIS</fullName>
    </customValue>
    <customValue>
        <fullName>FERRAMENTAS MANUAL</fullName>
    </customValue>
    <customValue>
        <fullName>FRETES E CARRETOS</fullName>
    </customValue>
    <customValue>
        <fullName>GRÁFICA</fullName>
    </customValue>
    <customValue>
        <fullName>HOSPEDAGEM</fullName>
    </customValue>
    <customValue>
        <fullName>IMPRESSÃO E CÓPIAS</fullName>
    </customValue>
    <customValue>
        <fullName>LAZER E ESPORTES</fullName>
    </customValue>
    <customValue>
        <fullName>LIMPEZA E CONSERVAÇÃO</fullName>
    </customValue>
    <customValue>
        <fullName>LOCAÇÃO DE IMOVEIS</fullName>
    </customValue>
    <customValue>
        <fullName>LOCAÇÃO DE MÁQUINAS E EQUIPAMENTOS</fullName>
    </customValue>
    <customValue>
        <fullName>LOCAÇÃO DE VEÍCULOS</fullName>
    </customValue>
    <customValue>
        <fullName>MANUTENÇÃO E MÁQUINAS E EQUIPAMENTOS</fullName>
    </customValue>
    <customValue>
        <fullName>MANUTENÇÃO PREDIAL</fullName>
    </customValue>
    <customValue>
        <fullName>MARKETING</fullName>
    </customValue>
    <customValue>
        <fullName>MATERIAL DE COPA</fullName>
    </customValue>
    <customValue>
        <fullName>MATERIAL DE INFORMÁTICA</fullName>
    </customValue>
    <customValue>
        <fullName>MATERIAL ELÉTRICO</fullName>
    </customValue>
    <customValue>
        <fullName>MATERIAL ELETRÔNICO</fullName>
    </customValue>
    <customValue>
        <fullName>MATERIAL ESCRITÓRIO</fullName>
    </customValue>
    <customValue>
        <fullName>MATERIAL LIMPEZA</fullName>
    </customValue>
    <masterLabel>Categoria de compra</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/linha.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CAMAS HOSPITALARES</fullName>
    </customValue>
    <customValue>
        <fullName>CIRURGIA MINIMAMENTE INVASIVA</fullName>
    </customValue>
    <customValue>
        <fullName>CIRURGIA ROBÓTICA</fullName>
    </customValue>
    <customValue>
        <fullName>ELETROCIRURGIA</fullName>
    </customValue>
    <customValue>
        <fullName>ENDOSCOPIA</fullName>
    </customValue>
    <customValue>
        <fullName>HUAWEI</fullName>
    </customValue>
    <customValue>
        <fullName>IMAGEM</fullName>
    </customValue>
    <customValue>
        <fullName>IMAGEM RAIO-X</fullName>
    </customValue>
    <customValue>
        <fullName>IMAGEM ULTRASSOM</fullName>
    </customValue>
    <customValue>
        <fullName>LOCAÇÃO</fullName>
    </customValue>
    <customValue>
        <fullName>MONITORES DE GRAU MEDICO</fullName>
    </customValue>
    <customValue>
        <fullName>NEONATOLOGIA</fullName>
    </customValue>
    <customValue>
        <fullName>OPME</fullName>
    </customValue>
    <customValue>
        <fullName>OUTROS</fullName>
    </customValue>
    <customValue>
        <fullName>PM</fullName>
    </customValue>
    <customValue>
        <fullName>PMLS</fullName>
    </customValue>
    <customValue>
        <fullName>SERVIÇO</fullName>
    </customValue>
    <customValue>
        <fullName>SURGICAL</fullName>
    </customValue>
    <customValue>
        <fullName>VETERINÁRIA</fullName>
    </customValue>
    <customValue>
        <fullName>VETERINÁRIA IVD</fullName>
    </customValue>
    <customValue>
        <fullName>VETERINÁRIA MIS</fullName>
    </customValue>
    <customValue>
        <fullName>VETERINÁRIA PMLS</fullName>
    </customValue>
    <customValue>
        <fullName>VIAS AÉREAS DIFÍCEIS</fullName>
    </customValue>
    <customValue>
        <fullName>VETQLAB</fullName>
    </customValue>
    <customValue>
        <fullName>INFUSÃO</fullName>
        <isActive>false</isActive>
        <label>INFUSÃO</label>
    </customValue>
    <customValue>
        <fullName>ESTERILIZACAO</fullName>
        <isActive>false</isActive>
        <label>ESTERILIZACAO</label>
    </customValue>
    <customValue>
        <fullName>CUIDADOS PESSOAIS</fullName>
        <isActive>false</isActive>
        <label>CUIDADOS PESSOAIS</label>
    </customValue>
    <customValue>
        <fullName>CMI</fullName>
        <isActive>false</isActive>
        <label>CMI</label>
    </customValue>
    <customValue>
        <fullName>LABORATORIAL</fullName>
        <isActive>false</isActive>
        <label>LABORATORIAL</label>
    </customValue>
    <customValue>
        <fullName>APOIO A MOBILIDADE</fullName>
        <isActive>false</isActive>
        <label>APOIO A MOBILIDADE</label>
    </customValue>
    <masterLabel>linha</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/solicitacaoCadastroProduto.cls
public class solicitacaoCadastroProduto {
    
    @AuraEnabled
    public static void createSolicitacaoDeCadastro(String categoriaCompra, String nome, String descricao, String modelo, String marca, String c_d_Fabricante, String unidadeDeMedida) {
        // Create a new instance of SolicitacaodeCadastro__c
        SolicitacaodeCadastro__c solicitacao = new SolicitacaodeCadastro__c();
        
        // Set the fields with the provided value
        solicitacao.Nome__c = nome;
        solicitacao.Descricao__c = descricao;
        solicitacao.Modelo__c = modelo;
        solicitacao.Marca__c = marca;
        solicitacao.C_d_Fabricante__c = c_d_Fabricante;
        solicitacao.Unidade_de_medida__c = unidadeDeMedida;
        solicitacao.Categoria_de_compra__c = categoriaCompra;
        solicitacao.Fam_lia__c = 'OUTROS';
        solicitacao.Tipo__c = 'OUTROS';
        solicitacao.Valor_de_Venda__c = 0.0;
        solicitacao.Linha__c = 'OUTROS';
        
        try{
            insert solicitacao;
            System.debug('SolicitacaodeCadastro__c record created successfully.');
            
        }
        catch(DMLException e){
            throw new AuraHandledException(e.getMessage());
        }
    
    }
    
}