force-app/main/default/objects/Carteira__c/Carteira__c.object-meta.xml
<CustomObject>
    <label>Carteira</label>
    <nameField>
        <label>Nome de Carteira</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Carteiras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Carteira__c/fields/Colaborador__c.field-meta.xml
<CustomField>
    <fullName>Colaborador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Colaborador</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Carteiras</relationshipLabel>
    <relationshipName>Carteiras</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Destinatario__c/Destinatario__c.object-meta.xml
<CustomObject>
    <label>Destinatário</label>
    <nameField>
        <displayFormat>DES-{00000}</displayFormat>
        <label>Destinatário</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Destinatários</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Solicitacao_de_Tranferencia_Hospcoins__c/Solicitacao_de_Tranferencia_Hospcoins__c.object-meta.xml
<CustomObject>
    <description>Esse obj faz a validação das tranferencias hospcoins do programa valeu. 
Os colobaradores fazem a Solicitação de Tranferencia e essa solicitação cai para o RH.
Quando aprovado, a tranferencia é efetuada, caso ao contrario o colaborador é notificado sobre a reprovação
e a justificativa da mesma</description>
    <label>Solicitação de Transferência Hospcoins</label>
    <nameField>
        <displayFormat>STH - {0000}</displayFormat>
        <label>Solicitação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solicitações de Transferências</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Solicitacao_de_Tranferencia_Hospcoins__c/fields/Carteira_Destinataria__c.field-meta.xml
<CustomField>
    <fullName>Carteira_Destinataria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Carteira Destinatária</label>
    <referenceTo>Carteira__c</referenceTo>
    <relationshipLabel>Solicitações de Transferências</relationshipLabel>
    <relationshipName>Solicita_es_de_Transfer_ncias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Solicitacao_de_Tranferencia_Hospcoins__c/fields/Carteira_Remetente__c.field-meta.xml
<CustomField>
    <fullName>Carteira_Remetente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Carteira Remetente</label>
    <referenceTo>Carteira__c</referenceTo>
    <relationshipLabel>Solicitações de Transferências (Carteira Remetente)</relationshipLabel>
    <relationshipName>Solicita_es_de_Transfer_ncias1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Solicitacao_de_Tranferencia_Hospcoins__c/fields/Data_de_Solicitacao__c.field-meta.xml
<CustomField>
    <fullName>Data_de_Solicitacao__c</fullName>
    <label>Data de Solicitação</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Solicitacao_de_Tranferencia_Hospcoins__c/fields/Destinatario__c.field-meta.xml
<CustomField>
    <fullName>Destinatario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Destinatário</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Solicitações de Transferências</relationshipLabel>
    <relationshipName>Solicitacoes_de_Transferencias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Solicitacao_de_Tranferencia_Hospcoins__c/fields/Justificativa__c.field-meta.xml
<CustomField>
    <fullName>Justificativa__c</fullName>
    <label>Justificativa de envio</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Solicitacao_de_Tranferencia_Hospcoins__c/fields/Remetente__c.field-meta.xml
<CustomField>
    <fullName>Remetente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Remetente</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Solicitacoes_de_Transferencias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Solicitacao_de_Tranferencia_Hospcoins__c/fields/Remetente_Externo__c.field-meta.xml
<CustomField>
    <fullName>Remetente_Externo__c</fullName>
    <inlineHelpText>Usado para armazenar o nome de remetente que não possuem uma conta no Salesforce</inlineHelpText>
    <label>Remetente (Externo)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Solicitacao_de_Tranferencia_Hospcoins__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendente</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Solicitacao_de_Tranferencia_Hospcoins__c/fields/Transfer_ncia_Hospcoin__c.field-meta.xml
<CustomField>
    <fullName>Transfer_ncia_Hospcoin__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transferência Hospcoin</label>
    <referenceTo>Transfer_ncia_Hospcoin__c</referenceTo>
    <relationshipLabel>Solicitações de Transferências</relationshipLabel>
    <relationshipName>Solicita_es_de_Transfer_ncias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transfer_ncia_Hospcoin__c/Transfer_ncia_Hospcoin__c.object-meta.xml
<CustomObject>
    <label>Transferência Hospcoin</label>
    <nameField>
        <displayFormat>TH{00000}</displayFormat>
        <label>Nome de Transferência Hospcoin</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transferências Hospcoin</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transfer_ncia_Hospcoin__c/fields/Carteira_Destinataria__c.field-meta.xml
<CustomField>
    <fullName>Carteira_Destinataria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Carteira Destinatária</label>
    <referenceTo>Carteira__c</referenceTo>
    <relationshipLabel>Transferências Hospcoin (Carteira Destinatária)</relationshipLabel>
    <relationshipName>Transferencias_Hospcoin_destinatario</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transfer_ncia_Hospcoin__c/fields/Carteira_Remetente__c.field-meta.xml
<CustomField>
    <fullName>Carteira_Remetente__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Carteira Remetente</label>
    <referenceTo>Carteira__c</referenceTo>
    <relationshipLabel>Transferências Hospcoin</relationshipLabel>
    <relationshipName>Transferencias_Hospcoin</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transfer_ncia_Hospcoin__c/fields/Justificativa__c.field-meta.xml
<CustomField>
    <fullName>Justificativa__c</fullName>
    <label>Justificativa</label>
    <length>1300</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Transfer_ncia_Hospcoin__c/fields/Nome_envio_externo__c.field-meta.xml
<CustomField>
    <fullName>Nome_envio_externo__c</fullName>
    <label>Nome (envio externo)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transfer_ncia_Hospcoin__c/fields/Programa__c.field-meta.xml
<CustomField>
    <fullName>Programa__c</fullName>
    <label>Programa</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>5S</fullName>
            </value>
            <value>
                <fullName>Programa Valeu</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transfer_ncia_Hospcoin__c/fields/Quantidade_de_Hospcoins__c.field-meta.xml
<CustomField>
    <fullName>Quantidade_de_Hospcoins__c</fullName>
    <label>Quantidade de Hospcoins</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Transfer_ncia_Hospcoin__c/fields/Remetente__c.field-meta.xml
<CustomField>
    <fullName>Remetente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Remetente</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Transfer_ncias_Hospcoin</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/E_gerente__c.field-meta.xml
<CustomField>
    <fullName>E_gerente__c</fullName>
    <formula>IF(
  OR(
    CONTAINS(Profile.Name, &quot;Gerente&quot;),
    Email = &quot;gabriel.coelho@hoscom.net&quot;,
    Email = &quot;administrativo@hospcom.net&quot;,
    Email = &quot;barbara.coelho@hospcom.net&quot;
  ),
  TRUE,
  FALSE
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>É gerente</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/programaValeu.cls
public without sharing class programaValeu {

    // Chamado por trigger quando uma solicitação é aprovada
    public static void envia(String idContato, String justificativa, String nome, Id userId) {
        System.debug('--- INÍCIO ENVIA ---');
        System.debug('ID do Contato (Destinatário): ' + idContato);
        System.debug('Justificativa: ' + justificativa);
        System.debug('Nome externo (se aplicável): ' + nome);
        System.debug('ID do Usuário executando: ' + userId);

        // Consulta o usuário com os campos necessários
        User user = [SELECT Id, ProfileId, E_gerente__c FROM User WHERE Id = :userId];
        System.debug('Usuário carregado: ' + user.Id);
        System.debug('Perfil do usuário: ' + user.ProfileId);
        System.debug('É gerente? ' + user.E_gerente__c);

        Transfer_ncia_Hospcoin__c transferencia = new Transfer_ncia_Hospcoin__c();

        Carteira__c carteiraDestinataria = [SELECT ID FROM Carteira__c WHERE Colaborador__c =: idContato LIMIT 1];
        System.debug('Carteira destinatária encontrada: ' + carteiraDestinataria.Id);

        if (user.Id == '005U4000009lOgG') {
            transferencia.Quantidade_de_Hospcoins__c = 5;
            transferencia.Nome_envio_externo__c = nome;
            System.debug('Usuário fixo identificado, quantidade: 5');
        } else {
            if (user.E_gerente__c == true) {
                transferencia.Quantidade_de_Hospcoins__c = 25;
                System.debug('Usuário é gerente, quantidade: 25');
            } else {
                transferencia.Quantidade_de_Hospcoins__c = 5;
                System.debug('Usuário não é gerente, quantidade: 5');
            }
        }

        transferencia.Carteira_Remetente__c = 'a3fU40000006JET'; // Carteira hospcom
        transferencia.Carteira_Destinataria__c = carteiraDestinataria.Id;
        transferencia.Programa__c = 'Programa Valeu';
        transferencia.Justificativa__c = justificativa;
        transferencia.Remetente__c = user.Id;

        System.debug('Transferência a ser inserida: ' + transferencia);

        try {
            insert transferencia;
            System.debug('Transferência criada com sucesso: ' + transferencia.Id);
        } catch (Exception e) {
            System.debug('Erro ao inserir transferência: ' + e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }

        System.debug('--- FIM ENVIA ---');
    }




    @AuraEnabled
public static void criaSolicitacao(String idContato, String justificativa, String nome) {
    System.debug('--- INÍCIO CRIA SOLICITAÇÃO ---');
    System.debug('Destinatário: ' + idContato);
    System.debug('Justificativa: ' + justificativa);
    System.debug('Nome externo (se aplicável): ' + nome);

    User usuario = [
        SELECT Id, ProfileId, E_gerente__c, ContactId, Name
        FROM User
        WHERE Id = :UserInfo.getUserId()
    ];

    System.debug('Usuário logado: ' + usuario.Id + ' | Nome: ' + usuario.Name + ' | É gerente? ' + usuario.E_gerente__c);

    // Verifica se o envio é por um usuário externo (sem ContactId e nome fornecido)
    Boolean isExterno = (usuario.ContactId == null) && String.isNotBlank(nome);
    System.debug('Remetente é externo? ' + isExterno);

    Decimal quantidade = usuario.E_gerente__c ? 25 : 5;
    System.debug('Quantidade de Hospcoins definida: ' + quantidade);

    // --- VALIDAÇÃO 1: Já solicitou neste mês? ---
    List<Solicitacao_de_Tranferencia_Hospcoins__c> repetidas;
    if (isExterno) {
        repetidas = [
            SELECT Id FROM Solicitacao_de_Tranferencia_Hospcoins__c
            WHERE Remetente_Externo__c = :nome
            AND CreatedDate = THIS_MONTH
            AND Status__c != 'Reprovado'
        ];
    } else {
        repetidas = [
            SELECT Id FROM Solicitacao_de_Tranferencia_Hospcoins__c
            WHERE Remetente__c = :usuario.Id
            AND CreatedDate = THIS_MONTH
            AND Status__c != 'Reprovado'
        ];
    }

    System.debug('Solicitações existentes neste mês: ' + repetidas.size());
    if (!repetidas.isEmpty()) {
        throw new AuraHandledException('Você já fez uma solicitação este mês.');
    }

    // --- VALIDAÇÃO 2: Já enviou para esse destinatário nos últimos 2 meses? ---
    List<Transfer_ncia_Hospcoin__c> duplicadas;
    if (isExterno) {
        duplicadas = [
            SELECT Id FROM Transfer_ncia_Hospcoin__c
            WHERE Carteira_Destinataria__r.Colaborador__c = :idContato
            AND Nome_envio_externo__c = :nome
            AND CreatedDate = LAST_N_MONTHS:2
            AND Programa__c = 'Programa Valeu'
        ];
    } else {
        duplicadas = [
            SELECT Id FROM Transfer_ncia_Hospcoin__c
            WHERE Carteira_Destinataria__r.Colaborador__c = :idContato
            AND CreatedById = :UserInfo.getUserId()
            AND CreatedDate = LAST_N_MONTHS:2
            AND Programa__c = 'Programa Valeu'
        ];
    }

    System.debug('Transferências duplicadas encontradas: ' + duplicadas.size());
    if (!duplicadas.isEmpty()) {
        throw new AuraHandledException('Você já enviou Hospcoins para este colaborador nos últimos 2 meses.');
    }

    // --- Criação da Solicitação ---
    Solicitacao_de_Tranferencia_Hospcoins__c solicitacao = new Solicitacao_de_Tranferencia_Hospcoins__c();
    solicitacao.Data_de_Solicitacao__c = System.now();
    solicitacao.Justificativa__c = justificativa;
    solicitacao.Quantidade__c = quantidade;
    solicitacao.Status__c = 'Pendente';
    solicitacao.Destinatario__c = idContato;

    if (isExterno) {
        solicitacao.Remetente_Externo__c = nome;
        solicitacao.Remetente__c = '005U4000009lOgG';
        System.debug('Remetente externo registrado: ' + nome);
    } else {
        solicitacao.Remetente__c = usuario.Id;
        System.debug('Remetente interno registrado: ' + usuario.Id);
    }

    System.debug('Solicitação final: ' + solicitacao);

    try {
        insert solicitacao;
        System.debug('Solicitação criada com sucesso: ' + solicitacao.Id);
    } catch (Exception e) {
        System.debug('Erro ao criar a solicitação: ' + e.getMessage());
        throw new AuraHandledException('Erro ao salvar solicitação: ' + e.getMessage());
    }

    System.debug('--- FIM CRIA SOLICITAÇÃO ---');
}       
	@AuraEnabled
    public static List<sObject> executeSoql(String soql) {
        List<sObject> result = Database.query(soql);
        return result;
    }
    public static string dummy(String dummy) {
        string result = 'a';
        string result1 = 'a';
        string result2 = 'a';
        string result3 = 'a';
        string result4 = 'a';
        string result5 = 'a';
        string result6 = 'a';
        string result7 = 'a';
        string result8 = 'a';
        string result9 = 'a';
        string result10 = 'a';
        string result11 = 'a';
        string result12 = 'a';
        string result13 = 'a';
        string result14 = 'a';
        string result15 = 'a';
        string result16 = 'a';
        string result17 = 'a';
        string result18 = 'a';
        string result19 = 'a';
        string result20 = 'a';
        string result21 = 'a';
        string result22 = 'a';
        string result23 = 'a';
        string result24 = 'a';
        string result25 = 'a';
        string result26 = 'a';
        string result27 = 'a';
        string result28 = 'a';
        string result29 = 'a';
        
        return result;
    }
    
    public static string dummy2(String dummy) {
        string result = 'a';
        string result1 = 'a';
        string result2 = 'a';
        string result3 = 'a';
        string result4 = 'a';
        string result5 = 'a';
        string result6 = 'a';
        string result7 = 'a';
        string result8 = 'a';
        string result9 = 'a';
        string result10 = 'a';
        string result11 = 'a';
        string result12 = 'a';
        string result13 = 'a';
        string result14 = 'a';
        string result15 = 'a';
        string result16 = 'a';
        string result17 = 'a';
        string result18 = 'a';
        return result;
    }
    public static string dummy3(String dummy) {
        string result = 'a';
        string result1 = 'a';
        string result2 = 'a';
        string result3 = 'a';
        string result4 = 'a';
        string result5 = 'a';
        string result6 = 'a';
        string result7 = 'a';
        string result8 = 'a';
        string result9 = 'a';
        string result10 = 'a';
        string result11 = 'a';
        string result12 = 'a';
        string result13 = 'a';
        string result14 = 'a';
        string result15 = 'a';
        string result16 = 'a';
        string result17 = 'a';
        string result18 = 'a';
        return result;
    }
     public static string dummy4(String dummy) {
        string result = 'a';
        string result1 = 'a';
        string result2 = 'a';
        string result3 = 'a';
        string result4 = 'a';
        string result5 = 'a';
        string result6 = 'a';
        string result7 = 'a';
        string result8 = 'a';
        string result9 = 'a';
        string result10 = 'a';
        string result11 = 'a';
        string result12 = 'a';
        string result13 = 'a';
        string result14 = 'a';
        string result15 = 'a';
        string result16 = 'a';
        string result17 = 'a';
        string result18 = 'a';
        return result;
    }
        public static string dummy5(String dummy) {
        string result = 'a';
        string result1 = 'a';
        string result2 = 'a';
        string result3 = 'a';
        string result4 = 'a';
        string result5 = 'a';
        string result6 = 'a';
        string result7 = 'a';
        string result8 = 'a';
        string result9 = 'a';
        string result10 = 'a';
        string result11 = 'a';
        string result12 = 'a';
        string result13 = 'a';
        string result14 = 'a';
        string result15 = 'a';
        string result16 = 'a';
        string result17 = 'a';
        string result18 = 'a';
        return result;
    }
    public static string dummy6(String dummy) {
        string result = 'a';
        string result1 = 'a';
        string result2 = 'a';
        string result3 = 'a';
        string result4 = 'a';
        string result5 = 'a';
        string result6 = 'a';
        string result7 = 'a';
        string result8 = 'a';
        string result9 = 'a';
        string result10 = 'a';
        string result11 = 'a';
        string result12 = 'a';
        string result13 = 'a';
        string result14 = 'a';
        string result15 = 'a';
        string result16 = 'a';
        string result17 = 'a';
        string result18 = 'a';
        return result;
    }
    public static string dummy7(String dummy) {
        string result = 'a';
        string result1 = 'a';
        string result2 = 'a';
        string result3 = 'a';
        string result4 = 'a';
        string result5 = 'a';
        string result6 = 'a';
        string result7 = 'a';
        string result8 = 'a';
        string result9 = 'a';
        string result10 = 'a';
        string result11 = 'a';
        string result12 = 'a';
        string result13 = 'a';
        string result14 = 'a';
        string result15 = 'a';
        string result16 = 'a';
        string result17 = 'a';
        string result18 = 'a';
        return result;
    }
    public static string dummy8(String dummy) {
        string result = 'a';
        string result1 = 'a';
        string result2 = 'a';
        string result3 = 'a';
        string result4 = 'a';
        string result5 = 'a';
        string result6 = 'a';
        string result7 = 'a';
        string result8 = 'a';
        string result9 = 'a';
        string result10 = 'a';
        string result11 = 'a';
        string result12 = 'a';
        string result13 = 'a';
        string result14 = 'a';
        string result15 = 'a';
        string result16 = 'a';
        string result17 = 'a';
        string result18 = 'a';
        return result;
    }
    public static string dummy9(String dummy) {
        string result = 'a';
        string result1 = 'a';
        string result2 = 'a';
        string result3 = 'a';
        string result4 = 'a';
        string result5 = 'a';
        string result6 = 'a';
        string result7 = 'a';
        string result8 = 'a';
        string result9 = 'a';
        string result10 = 'a';
        string result11 = 'a';
        string result12 = 'a';
        string result13 = 'a';
        string result14 = 'a';
        string result15 = 'a';
        string result16 = 'a';
        string result17 = 'a';
        string result18 = 'a';
        return result;
    }

}