force-app/main/default/objects/Fornecedor__c/Fornecedor__c.object-meta.xml
<CustomObject>
    <label>Pedido de Compra</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número do Pedido de Compra</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pedidos de Compra</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fornecedor__c/fields/Fornecedor__c.field-meta.xml
<CustomField>
    <fullName>Fornecedor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Fornecedor</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Fornecedores1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fornecedor__c/fields/Pedido_de_compra__c.field-meta.xml
<CustomField>
    <fullName>Pedido_de_compra__c</fullName>
    <label>Cotação</label>
    <referenceTo>Pedido_de_compra__c</referenceTo>
    <relationshipName>Fornecedores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Item_de_fornecedor__c/Item_de_fornecedor__c.object-meta.xml
<CustomObject>
    <label>Item de pedido de compra</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Nº do item de pedido de compra</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens de pedido de compra</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Item_de_fornecedor__c/fields/Fornecedor__c.field-meta.xml
<CustomField>
    <fullName>Fornecedor__c</fullName>
    <label>Pedido de Compra</label>
    <referenceTo>Fornecedor__c</referenceTo>
    <relationshipLabel>Itens de pedido de compra</relationshipLabel>
    <relationshipName>Itens_de_fornecedor</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Item_de_fornecedor__c/fields/Item_de_pedido_de_compra__c.field-meta.xml
<CustomField>
    <fullName>Item_de_pedido_de_compra__c</fullName>
    <label>Item de cotação</label>
    <referenceTo>Item_de_pedido_de_compra__c</referenceTo>
    <relationshipName>Itens_de_fornecedor</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Item_de_fornecedor__c/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <formula>Item_de_pedido_de_compra__r.Marca__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Marca</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Item_de_fornecedor__c/fields/Modelo__c.field-meta.xml
<CustomField>
    <fullName>Modelo__c</fullName>
    <formula>Item_de_pedido_de_compra__r.Modelo__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Modelo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Item_de_fornecedor__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <formula>Item_de_pedido_de_compra__r.Produto__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Produto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Item_de_fornecedor__c/fields/Quantidade_disponivel__c.field-meta.xml
<CustomField>
    <fullName>Quantidade_disponivel__c</fullName>
    <formula>Quantidade__c -  Quantidade_destinada__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quantidade disponível</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Item_de_pedido_de_compra__c/Item_de_pedido_de_compra__c.object-meta.xml
<CustomObject>
    <label>Item de cotação</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número do item de cotação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens de cotação</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Item_de_pedido_de_compra__c/fields/Data_de_requisicao__c.field-meta.xml
<CustomField>
    <fullName>Data_de_requisicao__c</fullName>
    <label>Data de requisição</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Item_de_pedido_de_compra__c/fields/Pedido_de_compra__c.field-meta.xml
<CustomField>
    <fullName>Pedido_de_compra__c</fullName>
    <label>Cotação</label>
    <referenceTo>Pedido_de_compra__c</referenceTo>
    <relationshipLabel>Itens de cotação</relationshipLabel>
    <relationshipName>Itens_de_Pedido_de_Compra</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Item_de_pedido_de_compra__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Produtos_do_pedido</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Item_de_pedido_de_compra__c/fields/Quantidade_requisitada__c.field-meta.xml
<CustomField>
    <fullName>Quantidade_requisitada__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quantidade requisitada</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Data_de_requisicao__c.field-meta.xml
<CustomField>
    <fullName>Data_de_requisicao__c</fullName>
    <inlineHelpText>Ao Compras/Estoque, maior data dentre as requisições do item.</inlineHelpText>
    <label>_Data de requisição (del)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <formula>TEXT(PricebookEntry.Product2.Marca__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Marca</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Modelo__c.field-meta.xml
<CustomField>
    <fullName>Modelo__c</fullName>
    <formula>PricebookEntry.Modelo__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Modelo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Quantidade_requisitada__c.field-meta.xml
<CustomField>
    <fullName>Quantidade_requisitada__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Ao Compras/Estoque, soma total das requisições do item.</inlineHelpText>
    <label>_Quantidade requisitada (del)</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pedido_de_compra__c/Pedido_de_compra__c.object-meta.xml
<CustomObject>
    <label>Cotação de compra</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número da cotação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cotações de compra</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Pedido_de_compra__c/fields/Data_de_inicio__c.field-meta.xml
<CustomField>
    <fullName>Data_de_inicio__c</fullName>
    <label>Data de inicio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Pedido_de_compra__c/fields/Quantidade_requisitada__c.field-meta.xml
<CustomField>
    <fullName>Quantidade_requisitada__c</fullName>
    <label>Quantidade requisitada</label>
    <summarizedField>Item_de_pedido_de_compra__c.Quantidade_requisitada__c</summarizedField>
    <summaryForeignKey>Item_de_pedido_de_compra__c.Pedido_de_compra__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Fornecedor__c.field-meta.xml
<CustomField>
    <fullName>Fornecedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fornecedor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Produtos</relationshipLabel>
    <relationshipName>Produtos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>3GREEN</fullName>
            </value>
            <value>
                <fullName>7LIVES</fullName>
            </value>
            <value>
                <fullName>ABC</fullName>
            </value>
            <value>
                <fullName>ACCUMED</fullName>
            </value>
            <value>
                <fullName>ACROSS</fullName>
            </value>
            <value>
                <fullName>ACTE</fullName>
            </value>
            <value>
                <fullName>AEROGEN</fullName>
            </value>
            <value>
                <fullName>AGATA</fullName>
            </value>
            <value>
                <fullName>AGILE MED</fullName>
            </value>
            <value>
                <fullName>AIR LIQUIDE</fullName>
            </value>
            <value>
                <fullName>AIR SHIELD</fullName>
            </value>
            <value>
                <fullName>AJEL</fullName>
            </value>
            <value>
                <fullName>ALBAN</fullName>
            </value>
            <value>
                <fullName>ALIVE HEART</fullName>
            </value>
            <value>
                <fullName>ALLIAGE</fullName>
            </value>
            <value>
                <fullName>ALPHARAD</fullName>
            </value>
            <value>
                <fullName>ALVFLOR</fullName>
            </value>
            <value>
                <fullName>ALVIMÉDICA</fullName>
            </value>
            <value>
                <fullName>ANALYSER</fullName>
            </value>
            <value>
                <fullName>ANATONIC</fullName>
            </value>
            <value>
                <fullName>ANESTHESIA</fullName>
            </value>
            <value>
                <fullName>AOC</fullName>
            </value>
            <value>
                <fullName>APC</fullName>
            </value>
            <value>
                <fullName>APK</fullName>
            </value>
            <value>
                <fullName>APPLE</fullName>
            </value>
            <value>
                <fullName>ARJO</fullName>
            </value>
            <value>
                <fullName>ARJOHUNTLEIGH</fullName>
            </value>
            <value>
                <fullName>ARKTUS</fullName>
            </value>
            <value>
                <fullName>ARTIS</fullName>
            </value>
            <value>
                <fullName>ARTROCORP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Modelo__c.field-meta.xml
<CustomField>
    <fullName>Modelo__c</fullName>
    <label>Modelo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Requisicao_de_item__c/Requisicao_de_item__c.object-meta.xml
<CustomObject>
    <label>Destinação de item</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número da requisição de item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Destinações de item</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Requisicao_de_item__c/fields/Data_de_requisicao__c.field-meta.xml
<CustomField>
    <fullName>Data_de_requisicao__c</fullName>
    <label>Data de requisição</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Requisicao_de_item__c/fields/Item_de_pedido_de_compra__c.field-meta.xml
<CustomField>
    <fullName>Item_de_pedido_de_compra__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Item de cotação</label>
    <referenceTo>Item_de_pedido_de_compra__c</referenceTo>
    <relationshipName>Requisicoes_de_Itens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Requisicao_de_item__c/fields/Item_de_pedido_de_venda__c.field-meta.xml
<CustomField>
    <fullName>Item_de_pedido_de_venda__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Item de pedido de venda</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipName>Requisicoes_de_Produtos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Requisicao_de_item__c/fields/Quantidade_Disponivel__c.field-meta.xml
<CustomField>
    <fullName>Quantidade_Disponivel__c</fullName>
    <formula>Quantidade_requisitada__c - Quantidade_direcionada__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quantidade Disponível</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Requisicao_de_item__c/fields/Quantidade_requisitada__c.field-meta.xml
<CustomField>
    <fullName>Quantidade_requisitada__c</fullName>
    <label>Quantidade destinada</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/DestinacaoController.cls
public class DestinacaoController {
    
    public list <Item_de_pedido_de_compra__c> Records	{get;set;}
    
    public list <Item_de_fornecedor__c> item 			{get;set;}
    public Fornecedor__c PedidoDeCompra 				{get;set;}
     
    public Boolean show 								{get;set;}
    
	public string reqId 								{get;set;}
    
    public ID ide 										{get;set;} 

      
    public DestinacaoController(ApexPages.StandardController controller){
        show=false;
                 ide = ApexPages.currentPage().getParameters().get('id');
        		 PedidoDeCompra = [SELECT Id, Name FROM Fornecedor__c WHERE Id =: ide];

        item = [Select Item_de_pedido_de_compra__c, Fornecedor__r.Name from Item_de_fornecedor__c where Fornecedor__r.Id =: PedidoDeCompra.id];
        show=true;
       		 Records = [SELECT Id, Name, Quantidade_requisitada__c, Data_de_requisicao__c, Produto__r.ProductCode, Produto__r.Modelo__c,
                			   Pedido_de_compra__r.Data_de_inicio__c, Produto__c, Produto__r.Marca__c,
                			   Pedido_de_compra__r.Name, (SELECT Id, Name, Quantidade_requisitada__c, Quantidade_disponivel__c, RecordTypeId, Item_de_pedido_de_venda__c, Item_de_pedido_de_venda__r.Order.OrderNumber FROM Requisicoes_de_Itens__r ORDER by RecordTypeId, Quantidade_requisitada__c )               			    
                        FROM Item_de_pedido_de_compra__c 
                        WHERE Id IN (Select Item_de_pedido_de_compra__c from Item_de_fornecedor__c where Fornecedor__r.Id =: PedidoDeCompra.id)  ORDER BY Name
                       ];
    }
    public pageReference upd(){
         for(Item_de_pedido_de_compra__c pd : Records){
				update pd.Requisicoes_de_itens__r;     
                
            }
        	PageReference pr = new PageReference('/apex/Destinacao2?id=' + ide);
   				pr.setRedirect(true);
   				return pr;
    }
    public PageReference deleteRecord(){
        Requisicao_de_item__c req = [select id from Requisicao_de_item__c where id =: reqId limit 1];        
        if(req != null)
        {
            try{
                delete req;	
            }
            catch(DmlException ex){
                ApexPages.addMessages(ex);
            }
        }
       return null;
   }
}