force-app/main/default/objects/Fornecedor__c/Fornecedor__c.object-meta.xml
<CustomObject>
    <label>Pedido de Compra</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número do Pedido de Compra</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pedidos de Compra</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fornecedor__c/fields/Data_da_Compra__c.field-meta.xml
<CustomField>
    <fullName>Data_da_Compra__c</fullName>
    <label>Data da Compra</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Fornecedor__c/fields/Fornecedor__c.field-meta.xml
<CustomField>
    <fullName>Fornecedor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Fornecedor</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Fornecedores1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fornecedor__c/fields/Prazo_de_recebimento__c.field-meta.xml
<CustomField>
    <fullName>Prazo_de_recebimento__c</fullName>
    <inlineHelpText>Previsão de entrega definida com base na data de aprovação da cotação + quantidade de dias de entrega.</inlineHelpText>
    <label>Previsão de entrega</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Fornecedor__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <formula>TEXT(Pedido_de_compra__r.Tipo__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Item_de_fornecedor__c/Item_de_fornecedor__c.object-meta.xml
<CustomObject>
    <label>Item de pedido de compra</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Nº do item de pedido de compra</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens de pedido de compra</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Item_de_fornecedor__c/fields/Codigo_do_produto__c.field-meta.xml
<CustomField>
    <fullName>Codigo_do_produto__c</fullName>
    <formula>Item_de_pedido_de_compra__r.Codigo_do_produto__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Código do produto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Item_de_fornecedor__c/fields/Comprar__c.field-meta.xml
<CustomField>
    <fullName>Comprar__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Comprar</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Item_de_fornecedor__c/fields/Cotar__c.field-meta.xml
<CustomField>
    <fullName>Cotar__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cotar</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Item_de_fornecedor__c/fields/Data_da_compra__c.field-meta.xml
<CustomField>
    <fullName>Data_da_compra__c</fullName>
    <formula>Fornecedor__r.Data_da_Compra__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Data da compra</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Item_de_fornecedor__c/fields/Data_de_recebimento__c.field-meta.xml
<CustomField>
    <fullName>Data_de_recebimento__c</fullName>
    <formula>Item_de_pedido_de_compra__r.Data_de_recebimento__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Data de recebimento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Item_de_fornecedor__c/fields/Fornecedor__c.field-meta.xml
<CustomField>
    <fullName>Fornecedor__c</fullName>
    <label>Pedido de Compra</label>
    <referenceTo>Fornecedor__c</referenceTo>
    <relationshipLabel>Itens de pedido de compra</relationshipLabel>
    <relationshipName>Itens_de_fornecedor</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Item_de_fornecedor__c/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <formula>Item_de_pedido_de_compra__r.Marca__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Marca</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Item_de_fornecedor__c/fields/Modelo__c.field-meta.xml
<CustomField>
    <fullName>Modelo__c</fullName>
    <formula>Item_de_pedido_de_compra__r.Modelo__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Modelo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Item_de_fornecedor__c/fields/Prazo_de_recebimento2__c.field-meta.xml
<CustomField>
    <fullName>Prazo_de_recebimento2__c</fullName>
    <formula>Fornecedor__r.Prazo_de_recebimento__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Prazo de recebimento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Item_de_fornecedor__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <formula>Item_de_pedido_de_compra__r.Produto__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Produto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Item_de_fornecedor__c/fields/Quantidade__c.field-meta.xml
<CustomField>
    <fullName>Quantidade__c</fullName>
    <label>Quantidade</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Item_de_fornecedor__c/fields/Quantidade_recebida2__c.field-meta.xml
<CustomField>
    <fullName>Quantidade_recebida2__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quantidade recebida*</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Item_de_fornecedor__c/fields/Quantidade_Recebida__c.field-meta.xml
<CustomField>
    <fullName>Quantidade_Recebida__c</fullName>
    <formula>Item_de_pedido_de_compra__r.Quantidade_recebida__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quantidade Recebida</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Item_de_fornecedor__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NOVO</fullName>
                <default>true</default>
                <label>NOVO</label>
            </value>
            <value>
                <fullName>RECEBIDO PARCIAL</fullName>
            </value>
            <value>
                <fullName>RECEBIDO TOTAL</fullName>
            </value>
            <value>
                <fullName>CMP - EM PRODUÇÃO FORN.</fullName>
            </value>
            <value>
                <fullName>CMP - EM COLETA PORTO/FORNECEDOR</fullName>
            </value>
            <value>
                <fullName>EM TRANSITO</fullName>
            </value>
            <value>
                <fullName>CMP - EM DESEMBARAÇO</fullName>
            </value>
            <value>
                <fullName>CMP - EM TRANSITO NACIONAL</fullName>
            </value>
            <value>
                <fullName>CMP - EM TRANSITO INTERNACIONAL</fullName>
            </value>
            <value>
                <fullName>CMP - PRE-EMBARQUE IMPORTAÇÃO</fullName>
            </value>
            <value>
                <fullName>CMP - AG. PAGAMENTO FORN</fullName>
            </value>
            <value>
                <fullName>CMP - AG. CONSOLIDAÇÃO DE CARGA</fullName>
            </value>
            <value>
                <fullName>CMP - AG. DESEMBARAÇO ADUANEIRO</fullName>
            </value>
            <value>
                <fullName>CMP - AG. NFE NACIONALIZAÇÃO</fullName>
            </value>
            <value>
                <fullName>AG APROVAÇÃO PEDIDO</fullName>
            </value>
            <value>
                <fullName>CMP - AG. DADOS TECNICOS</fullName>
            </value>
            <value>
                <fullName>AG. RECEBIMENTO LOGISTICA</fullName>
            </value>
            <value>
                <fullName>CMP - AG. AUTORIZAÇÃO DESEMBARAÇO</fullName>
            </value>
            <value>
                <fullName>CMP - AG. REMOÇAO DE CARGA</fullName>
            </value>
            <value>
                <fullName>CMP - AG. LIBERAÇAO CANAL VERMELHO</fullName>
            </value>
            <value>
                <fullName>CMP - AG. LIBERAÇAO CANAL AMARELO</fullName>
            </value>
            <value>
                <fullName>CMP - AG. LIBERAÇAO CANAL CINZA</fullName>
            </value>
            <value>
                <fullName>CMP - AG. ACEITE DE CARGA DG/BATERIA</fullName>
            </value>
            <value>
                <fullName>AG. PRONTIDÃO</fullName>
            </value>
            <value>
                <fullName>CMP - AG. ENTREGA FORNECEDOR</fullName>
            </value>
            <value>
                <fullName>CANCELADO</fullName>
            </value>
            <value>
                <fullName>CMP - COTAÇÃO DE COMPRA</fullName>
            </value>
            <value>
                <fullName>Devolvido</fullName>
                <isActive>false</isActive>
                <label>Devolvido</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Item_de_fornecedor__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <formula>Item_de_pedido_de_compra__r.Tipo__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Item_de_fornecedor__c/fields/Valor_total__c.field-meta.xml
<CustomField>
    <fullName>Valor_total__c</fullName>
    <formula>Valor_unitario__c *  Quantidade__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valor total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Item_de_fornecedor__c/fields/Valor_unitario__c.field-meta.xml
<CustomField>
    <fullName>Valor_unitario__c</fullName>
    <label>Valor unitário</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ItensPCompraController.cls
public class ItensPCompraController {
    
    public id ide                                                               {get;set;}
    
    public List <Item_de_fornecedor__c> itens     {get;set;}
    
    public ItensPCompraController (ApexPages.StandardController controller){
        
              ide = ApexPages.currentPage().getParameters().get('id');
        
                  itens = [SELECT ID, Name, Produto__c, Cotar__c, Comprar__c, Codigo_do_produto__c, Modelo__c, Marca__c, Valor_unitario__c, Quantidade__c, Quantidade_recebida__c, Quantidade_recebida2__c, Valor_total__c, Status__c, Prazo_de_recebimento__c, Prazo_de_recebimento2__c, Tipo__c, Data_de_recebimento__c, Data_da_compra__c FROM Item_de_fornecedor__c WHERE Fornecedor__c =: ide];

        }
    public void salvar(){
        try{
            update itens;
        }
        catch(DmlException e){
            
        }
    }
    public void todosAg(){
        for(Item_de_fornecedor__c item : itens){
            if(item.Status__c == 'Novo' || item.Status__c == null){
            item.Status__c = 'Aguardando Entrega Fornecedor';
            update item;
                }
        }
    }
}