force-app/main/default/objects/Fornecedor__c/Fornecedor__c.object-meta.xml
<CustomObject>
    <label>Pedido de Compra</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número do Pedido de Compra</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pedidos de Compra</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fornecedor__c/fields/Fornecedor__c.field-meta.xml
<CustomField>
    <fullName>Fornecedor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Fornecedor</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Fornecedores1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Item_de_pedido_de_compra__c/Item_de_pedido_de_compra__c.object-meta.xml
<CustomObject>
    <label>Item de cotação</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número do item de cotação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens de cotação</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Item_de_pedido_de_compra__c/fields/Quantidade_recebida__c.field-meta.xml
<CustomField>
    <fullName>Quantidade_recebida__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quantidade recebida</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Recebimento_de_item__c/Recebimento_de_item__c.object-meta.xml
<CustomObject>
    <label>Recebimento de item</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número do recebimento de item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recebimentos de item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Recebimento_de_item__c/fields/Item_de_pedido_de_compra__c.field-meta.xml
<CustomField>
    <fullName>Item_de_pedido_de_compra__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item de pedido de compra</label>
    <referenceTo>Item_de_fornecedor__c</referenceTo>
    <relationshipLabel>Recebimentos de item</relationshipLabel>
    <relationshipName>Recebimentos_de_item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recebimento_de_item__c/fields/Quantidade_recebida__c.field-meta.xml
<CustomField>
    <fullName>Quantidade_recebida__c</fullName>
    <label>Quantidade recebida</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Requisicao_de_item__c/Requisicao_de_item__c.object-meta.xml
<CustomObject>
    <label>Destinação de item</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número da requisição de item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Destinações de item</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Requisicao_de_item__c/fields/Item_de_pedido_de_compra__c.field-meta.xml
<CustomField>
    <fullName>Item_de_pedido_de_compra__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Item de cotação</label>
    <referenceTo>Item_de_pedido_de_compra__c</referenceTo>
    <relationshipName>Requisicoes_de_Itens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Requisicao_de_item__c/fields/Quantidade_recebida__c.field-meta.xml
<CustomField>
    <fullName>Quantidade_recebida__c</fullName>
    <label>Quantidade recebida</label>
    <summarizedField>Recebimento_de_item__c.Quantidade_recebida__c</summarizedField>
    <summaryForeignKey>Recebimento_de_item__c.Requisicao_de_produto__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/AssistPedCompraPDFTest.cls
@isTest(SeeAllData=true)
public class AssistPedCompraPDFTest {
	@isTest
    public static void up(){
        PageReference testPage = Page.AssistenteRecebimentoProduto;
        Test.setCurrentPage(testPage);
        testPage.getParameters().put('Id', String.valueOf('a1b6e000003nqrs'));
        Test.startTest();
        Fornecedor__c pc = [SELECT ID FROM Fornecedor__c where ID = 'a1b6e000003nqrs'];
     	AssistenteRecebimentoProduto obj = new AssistenteRecebimentoProduto(new ApexPages.StandardController(pc));
        for(AssistenteRecebimentoProduto.ItemCompra item : obj.itens){
            			for(AssistenteRecebimentoProduto.ReqItem req_item : item.reqs_item){
                            req_item.receb_item.Quantidade_recebida__c = 1;
                        }

        }
        obj.Efetiva();
		AssistenteRecebimentoProduto.ItemCompra item_compra = new AssistenteRecebimentoProduto.ItemCompra(new Item_de_pedido_de_compra__c());
		AssistenteRecebimentoProduto.CRecebimentoDeItem c_rec_item = new AssistenteRecebimentoProduto.CRecebimentoDeItem(new Requisicao_de_item__c(), new Recebimento_de_item__c());
        AssistenteRecebimentoProduto.CDivide C_Divide = new AssistenteRecebimentoProduto.CDivide('a1g6e000005GUvP', 'a1c6e000009gHct', 'a1d6e0000095gOI', 2.0, 'a', system.today(), 2.0);
        obj.ObtemDados();
        
        Test.stopTest();
    }
}