force-app/main/default/objects/Fornecedor__c/Fornecedor__c.object-meta.xml
<CustomObject>
    <label>Pedido de Compra</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número do Pedido de Compra</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pedidos de Compra</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fornecedor__c/fields/Fornecedor__c.field-meta.xml
<CustomField>
    <fullName>Fornecedor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Fornecedor</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Fornecedores1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/getAnexoPCTEST.cls
@IsTest(SeeAllData=true)
public class getAnexoPCTEST {
    @isTest
    static void testTrigger() {
        // ID fictício para o campo Fornecedor__c
        Id fornecedorId = 'a1bU4000001lWIPIA2';
        
        //a1bHZ000000hQiPYAU sand
        ////a1bU4000001lWIPIA2 prod

        // Crie um registro Fornecedor__c para teste
        Fornecedor__c fornecedor = new Fornecedor__c(
            Id = fornecedorId
        );

        // Crie um registro ContentVersion para o ContentDocument
        ContentVersion contentVer = new ContentVersion(
            Title = 'Test Document',
            PathOnClient = 'TestDocument.pdf',
            VersionData = Blob.valueOf('Test content')
        );
        insert contentVer;

        // Obtenha o ContentDocumentId a partir do ContentVersion
        ContentDocumentLink contentDocLink = new ContentDocumentLink(
            LinkedEntityId = fornecedor.Id,
            ContentDocumentId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :contentVer.Id LIMIT 1].ContentDocumentId,
            ShareType = 'V'  // 'V' é para Viewer
        );

        Test.startTest();
        insert contentDocLink;
        Test.stopTest();

        // Recarregue o registro Fornecedor__c para verificar se o campo URL_Anexo__c foi atualizado
        fornecedor = [SELECT Id, URL_Anexo__c FROM Fornecedor__c WHERE Id = :fornecedor.Id];

        // Verifique se o campo URL_Anexo__c foi atualizado corretamente
        String expectedUrl = 'https://hospcom.my.site.com/Sales/sfc/servlet.shepherd/document/download/' + contentDocLink.ContentDocumentId;
        System.assertEquals(expectedUrl, fornecedor.URL_Anexo__c, 'A URL do anexo deve estar correta no campo URL_Anexo__c');
    }
}