force-app/main/default/objects/Instrucao_de_Servico__c/Instrucao_de_Servico__c.object-meta.xml
<CustomObject>
    <label>Instrução de Serviço</label>
    <nameField>
        <label>Instrução de Serviço</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instruções de Serviço</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item_da_Instrucao_de_servico__c/Item_da_Instrucao_de_servico__c.object-meta.xml
<CustomObject>
    <label>Tópico Instrução de Serviço</label>
    <nameField>
        <label>Titulo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tópicos das Instruções de Serviço</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Item_da_Instrucao_de_servico__c/fields/Conteudo__c.field-meta.xml
<CustomField>
    <fullName>Conteudo__c</fullName>
    <label>Conteúdo</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Item_da_Instrucao_de_servico__c/fields/Instrucao_de_Servico__c.field-meta.xml
<CustomField>
    <fullName>Instrucao_de_Servico__c</fullName>
    <label>Instrução de Serviço</label>
    <referenceTo>Instrucao_de_Servico__c</referenceTo>
    <relationshipName>Itens_das_Instrucoes_de_servico</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Item_da_Instrucao_de_servico__c/fields/Numero_do_Topico__c.field-meta.xml
<CustomField>
    <fullName>Numero_do_Topico__c</fullName>
    <label>Número do Tópico</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Listagem_InstrucaoDeServico.cls
public with sharing class Listagem_InstrucaoDeServico {
    
    
    public List<Item_da_Instrucao_de_servico__c> topico_instrucao {get; set;}
    
    public Listagem_InstrucaoDeServico(ApexPages.StandardController controller){
        Id objeto_pai = ((SObject)controller.getRecord()).Id;
        
        if(objeto_pai.getSObjectType().getDescribe().getName() == 'Instrucao_de_Servico__c')
            Listagem_InstrucaoDeServico((Instrucao_de_Servico__c)controller.getRecord());
    }
        
    public void Listagem_InstrucaoDeServico(Instrucao_de_Servico__c instucao_Servico){
        
        topico_instrucao = [
            SELECT   id, Name, Conteudo__c, Numero_do_Topico__c
            FROM Item_da_Instrucao_de_servico__c
            WHERE Instrucao_de_Servico__c =:   instucao_Servico.id
            ORDER BY Numero_do_Topico__c ASC  
        ];
    }
}