force-app/main/default/objects/Instrucao_de_Servico__c/Instrucao_de_Servico__c.object-meta.xml
<CustomObject>
    <label>Instrução de Serviço</label>
    <nameField>
        <label>Instrução de Serviço</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Instruções de Serviço</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PSQ__c/PSQ__c.object-meta.xml
<CustomObject>
    <label>Procedimento do Sistema de Qualidade</label>
    <nameField>
        <label>Título do Documento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Procedimentos do Sistema de Qualidade</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PSQ__c/fields/PSQ__c.field-meta.xml
<CustomField>
    <fullName>PSQ__c</fullName>
    <displayFormat>PSQ - {0000}</displayFormat>
    <label>PSQ</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/PSQ__c/recordTypes/PSQ.recordType-meta.xml
<RecordType>
    <fullName>PSQ</fullName>
    <active>true</active>
    <description>Procedimento do Sistema de Qualidade</description>
    <label>PSQ</label>
</RecordType>

force-app/main/default/classes/Listagem_InstrucaoDeServico_Test.cls
@isTest(seealldata = true)
public class Listagem_InstrucaoDeServico_Test{

    @isTest
    static void testListagem_hr() {
        try{
        // Crie um registro de PSQ__c para teste
        Instrucao_de_Servico__c instrucaoServico = new Instrucao_de_Servico__c(
           id = 'a2MU4000001uwS9MAI'
        );
        update instrucaoServico;

        // Crie um objeto StandardController para o registro de PSQ__c
        ApexPages.StandardController controller = new ApexPages.StandardController(instrucaoServico);

        // Crie uma instância da classe listagem_hr
        Listagem_InstrucaoDeServico listagem = new Listagem_InstrucaoDeServico(controller);

        // Execute o método listagem_hr(PSQ__c psq) da classe
        listagem.Listagem_InstrucaoDeServico(instrucaoServico); 
        }catch(Exception e){
            System.debug('Error: ' + e);
        }
    }
}