force-app/main/default/objects/Contrato_de_Fornecimento_de_Insumo__c/Contrato_de_Fornecimento_de_Insumo__c.object-meta.xml
<CustomObject>
    <label>Contrato de Fornecimento de Insumo</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Nº</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contratos de Fornecimento de Insumo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contrato_de_Fornecimento_de_Insumo__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rascunho</fullName>
                <default>true</default>
                <label>Rascunho</label>
            </value>
            <value>
                <fullName>Em aprovação</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Em assinatura</fullName>
            </value>
            <value>
                <fullName>Vigente</fullName>
            </value>
            <value>
                <fullName>Finalizado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Reprovado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/enviaContratoFornecimentoTest.cls
@isTest(seeAllData=true)
public class enviaContratoFornecimentoTest {
    @isTest
    private static void testeCtrFornec(){        
        Test.setMock(HttpCalloutMock.class, new MockClicksign());
        // Call method to test. 
        // This causes a fake response to be sent
        // from the class that implements HttpCalloutMock.
        string ide = 'a0fU4000009WDOL';
        Contrato_de_Fornecimento_de_Insumo__c contrato = [SELECT ID FROM Contrato_de_Fornecimento_de_Insumo__c WHERE ID =: ide];
        contrato.Acao_interna__c = true;
        contrato.Status__c = 'Aprovado';
        update contrato;
    }
}