force-app/main/default/objects/Contrato_de_Fornecimento_de_Insumo__c/Contrato_de_Fornecimento_de_Insumo__c.object-meta.xml
<CustomObject>
    <label>Contrato de Fornecimento de Insumo</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Nº</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contratos de Fornecimento de Insumo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Insumo_do_contrato__c/Insumo_do_contrato__c.object-meta.xml
<CustomObject>
    <label>Insumo do contrato</label>
    <nameField>
        <displayFormat>IC {000}</displayFormat>
        <label>Nº</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Insumos do contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Insumo_do_contrato__c/fields/Contrato_de_Fornecimento_de_Insumo__c.field-meta.xml
<CustomField>
    <fullName>Contrato_de_Fornecimento_de_Insumo__c</fullName>
    <label>Contrato de Fornecimento de Insumo</label>
    <referenceTo>Contrato_de_Fornecimento_de_Insumo__c</referenceTo>
    <relationshipLabel>Insumos do contrato</relationshipLabel>
    <relationshipName>Insumos_do_contrato</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Insumo_do_contrato__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Insumos do contrato</relationshipLabel>
    <relationshipName>Insumos_do_contrato</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Insumo_do_contrato__c/fields/Quantidade__c.field-meta.xml
<CustomField>
    <fullName>Quantidade__c</fullName>
    <label>Quantidade</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>3GREEN</fullName>
            </value>
            <value>
                <fullName>7LIVES</fullName>
            </value>
            <value>
                <fullName>ABC</fullName>
            </value>
            <value>
                <fullName>ACCUMED</fullName>
            </value>
            <value>
                <fullName>ACROSS</fullName>
            </value>
            <value>
                <fullName>ACTE</fullName>
            </value>
            <value>
                <fullName>AEROGEN</fullName>
            </value>
            <value>
                <fullName>AGATA</fullName>
            </value>
            <value>
                <fullName>AGILE MED</fullName>
            </value>
            <value>
                <fullName>AIR LIQUIDE</fullName>
            </value>
            <value>
                <fullName>AIR SHIELD</fullName>
            </value>
            <value>
                <fullName>AJEL</fullName>
            </value>
            <value>
                <fullName>ALBAN</fullName>
            </value>
            <value>
                <fullName>ALIVE HEART</fullName>
            </value>
            <value>
                <fullName>ALLIAGE</fullName>
            </value>
            <value>
                <fullName>ALPHARAD</fullName>
            </value>
            <value>
                <fullName>ALVFLOR</fullName>
            </value>
            <value>
                <fullName>ALVIMÉDICA</fullName>
            </value>
            <value>
                <fullName>ANALYSER</fullName>
            </value>
            <value>
                <fullName>ANATONIC</fullName>
            </value>
            <value>
                <fullName>ANESTHESIA</fullName>
            </value>
            <value>
                <fullName>AOC</fullName>
            </value>
            <value>
                <fullName>APC</fullName>
            </value>
            <value>
                <fullName>APK</fullName>
            </value>
            <value>
                <fullName>APPLE</fullName>
            </value>
            <value>
                <fullName>ARJO</fullName>
            </value>
            <value>
                <fullName>ARJOHUNTLEIGH</fullName>
            </value>
            <value>
                <fullName>ARKTUS</fullName>
            </value>
            <value>
                <fullName>ARTIS</fullName>
            </value>
            <value>
                <fullName>ARTROCORP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Quantidade__c.field-meta.xml
<CustomField>
    <fullName>Quantidade__c</fullName>
    <label>Quantidade</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/URL_da_Imagem__c.field-meta.xml
<CustomField>
    <fullName>URL_da_Imagem__c</fullName>
    <defaultValue>&quot;https://hospcom.my.site.com/servlet/servlet.ImageServer?id=015310000080hog&amp;oid=00Di0000000JVhH&amp;lastMod=1502888568000&quot;</defaultValue>
    <label>URL da Imagem</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Valor_de_Venda__c.field-meta.xml
<CustomField>
    <fullName>Valor_de_Venda__c</fullName>
    <label>Valor de Venda</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/InsumoController.cls
public with sharing class InsumoController {
    
    @AuraEnabled(cacheable=true)
    public static List<Product2> searchProducts(String productCode) {
        String query = 'SELECT Id, ProductCode, Name, Marca__c, URL_da_Imagem__c, Valor_de_Venda__c FROM Product2 WHERE ProductCode = :productCode LIMIT 10';
        return Database.query(query);
    }
    
    @AuraEnabled
    public static void sendSelectedProducts(String productData, String idRegistro) {
        // Desserializa o JSON em uma lista de objetos SelectedProduct
        List<SelectedProduct> selectedProducts = (List<SelectedProduct>) JSON.deserialize(productData, List<SelectedProduct>.class);
        List<Insumo_do_contrato__c> insumos = new List<Insumo_do_contrato__c>();
        
        // Processa os produtos selecionados
        for (SelectedProduct product : selectedProducts) {
            String productId = product.Id;
            Integer quantity = product.quantity;
            Double value = product.value;
            
            // Lógica para lidar com os dados do produto selecionado
            System.debug('Product ID: ' + productId + ', Quantity: ' + quantity + ', Value: ' + value);
            Insumo_do_contrato__c insumo = new Insumo_do_contrato__c();
            insumo.Contrato_de_Fornecimento_de_Insumo__c = idRegistro;
            insumo.Produto__c = productId;
            insumo.Valor_unitario__c = value;
            insumo.Quantidade__c = quantity;
            insumos.add(insumo);
        }
        try{
            insert insumos;
        }
        catch(Exception e){
            system.debug(e.getMessage());
            throw new AuraHandledException('Erro ao inserir produtos: ' + e.getMessage());
        }
    }
    public class SelectedProduct {
        @AuraEnabled public String Id { get; set; }
        @AuraEnabled public Integer quantity { get; set; }
        @AuraEnabled public Double value { get; set; }
        
        // Construtor
        public SelectedProduct(String Id, Integer quantity, Double value) {
            this.Id = Id;
            this.quantity = quantity;
            this.value = value;
        }
    }
    
}