force-app/main/default/objects/Aditivos_Contratuais__c/Aditivos_Contratuais__c.object-meta.xml
<CustomObject>
    <label>Aditivo Contratual</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Nome de Aditivos Contratuais</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Aditivos Contratuais</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Aditivos_Contratuais__c/fields/Contrato_de_Servi_o_Relacionado__c.field-meta.xml
<CustomField>
    <fullName>Contrato_de_Servi_o_Relacionado__c</fullName>
    <label>Contrato de Serviço Relacionado</label>
    <referenceTo>Contrato_de_Servi_o__c</referenceTo>
    <relationshipLabel>Aditivos Contratuais</relationshipLabel>
    <relationshipName>Aditivos_Contratuais</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Aditivos_Contratuais__c/fields/Dura_o_Adicional__c.field-meta.xml
<CustomField>
    <fullName>Dura_o_Adicional__c</fullName>
    <label>Duração Adicional</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Aditivos_Contratuais__c/fields/Editar_Clausulas__c.field-meta.xml
<CustomField>
    <fullName>Editar_Clausulas__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Editar Clausulas</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TestedeAditivosdeContratos.cls
@isTest(seeAllData=true)
private class TestedeAditivosdeContratos {
    @isTest static void TestedeAditivosdeContratos(){
        Aditivos_Contratuais__c testedeaditivocontratual = new Aditivos_Contratuais__c(
        Contrato_de_Servi_o_Relacionado__c = 'a1Y5A000006oSbn',
        Dura_o_Adicional__c = 5,
        Editar_Clausulas__c = false
            
            );
        insert testedeaditivocontratual;
        testedeaditivocontratual.Id = 'a1j5A0000070SUU';
        update testedeaditivocontratual;
    }
}