force-app/main/default/objects/Aditivos_Contratuais__c/Aditivos_Contratuais__c.object-meta.xml
<CustomObject>
    <label>Aditivo Contratual</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Nome de Aditivos Contratuais</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Aditivos Contratuais</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Aditivos_Contratuais__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <formula>Contrato_de_Servi_o_Relacionado__r.Cliente__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cliente</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Aditivos_Contratuais__c/fields/Contrato_de_Servi_o_Relacionado__c.field-meta.xml
<CustomField>
    <fullName>Contrato_de_Servi_o_Relacionado__c</fullName>
    <label>Contrato de Serviço Relacionado</label>
    <referenceTo>Contrato_de_Servi_o__c</referenceTo>
    <relationshipLabel>Aditivos Contratuais</relationshipLabel>
    <relationshipName>Aditivos_Contratuais</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Aditivos_Contratuais__c/fields/Documento_Assinado__c.field-meta.xml
<CustomField>
    <fullName>Documento_Assinado__c</fullName>
    <label>Documento Assinado</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Aditivos_Contratuais__c/fields/idDocAutentique__c.field-meta.xml
<CustomField>
    <fullName>idDocAutentique__c</fullName>
    <label>ID Documento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Aditivos_Contratuais__c/fields/N_do_Aditivo__c.field-meta.xml
<CustomField>
    <fullName>N_do_Aditivo__c</fullName>
    <label>N° do Aditivo</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>14</fullName>
            </value>
            <value>
                <fullName>15</fullName>
            </value>
            <value>
                <fullName>16</fullName>
            </value>
            <value>
                <fullName>17</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>19</fullName>
            </value>
            <value>
                <fullName>20</fullName>
            </value>
            <value>
                <fullName>21</fullName>
            </value>
            <value>
                <fullName>22</fullName>
            </value>
            <value>
                <fullName>23</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>25</fullName>
            </value>
            <value>
                <fullName>26</fullName>
            </value>
            <value>
                <fullName>27</fullName>
            </value>
            <value>
                <fullName>28</fullName>
            </value>
            <value>
                <fullName>29</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/Contrato_de_Servi_o__c.object-meta.xml
<CustomObject>
    <label>Contrato de Serviço</label>
    <nameField>
        <label>Nome do Contrato</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contratos de Serviços</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contratos de Locação</relationshipLabel>
    <relationshipName>Contratos_de_Servi_os</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Contato_do_Locat_rio__c.field-meta.xml
<CustomField>
    <fullName>Contato_do_Locat_rio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contato do Locatário</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contratos de Serviços</relationshipLabel>
    <relationshipName>Contratos_de_Servi_os</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/E_mail_da_Testemunha__c.field-meta.xml
<CustomField>
    <fullName>E_mail_da_Testemunha__c</fullName>
    <label>E-mail da Testemunha</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Locador_a__c.field-meta.xml
<CustomField>
    <fullName>Locador_a__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Locador(a)/Contratada</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contratos de Serviços (Locador(a))</relationshipLabel>
    <relationshipName>Contratos_de_Servi_os1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Nome_da_Testemunha__c.field-meta.xml
<CustomField>
    <fullName>Nome_da_Testemunha__c</fullName>
    <label>Nome da Testemunha</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Timbre__c.field-meta.xml
<CustomField>
    <fullName>Timbre__c</fullName>
    <label>Timbre</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GDB</fullName>
            </value>
            <value>
                <fullName>HEALTH SOLUTION</fullName>
            </value>
            <value>
                <fullName>HOSPCOM</fullName>
            </value>
            <value>
                <fullName>ABC TO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AutentiqueAditivoTest.cls
@isTest(seeAllData=true)
public class AutentiqueAditivoTest {
	@isTest
    private static void teste(){
        
        Test.setMock(HttpCalloutMock.class, new MockAutentiqueContratos());
        
        
        Aditivos_Contratuais__c Contrato = [SELECT Name, N_do_Aditivo__c, Contrato_de_Servi_o_Relacionado__r.Name, Contrato_de_Servi_o_Relacionado__r.Cliente__r.Name, Contrato_de_Servi_o_Relacionado__r.Cliente__r.PersonEmail, Contrato_de_Servi_o_Relacionado__r.Locador_a__r.CNPJ__c, idDocAutentique__c, Contrato_de_Servi_o_Relacionado__r.Nome_da_Testemunha__c, Contrato_de_Servi_o_Relacionado__r.Contato_do_Locat_rio__r.Name, Contrato_de_Servi_o_Relacionado__r.Contato_do_Locat_rio__r.Email, Contrato_de_Servi_o_Relacionado__r.Timbre__c, Contrato_de_Servi_o_Relacionado__r.E_mail_da_Testemunha__c, Contrato_de_Servi_o_Relacionado__r.Documento_Assinado__c FROM Aditivos_Contratuais__c WHERE ID= 'a1j6e000009ti8F'];        
        
        AutentiqueAditivo AC = new AutentiqueAditivo(new ApexPages.StandardController(Contrato));
        
        AC.atualizar();
        AC.inserir();
        
    }
    @isTest
    private static void teste3(){
        
        Test.setMock(HttpCalloutMock.class, new MockAutentiqueContratos());
        
        
        Aditivos_Contratuais__c Contrato = [SELECT Name, N_do_Aditivo__c, Contrato_de_Servi_o_Relacionado__r.Name, Contrato_de_Servi_o_Relacionado__r.Cliente__r.Name, Contrato_de_Servi_o_Relacionado__r.Cliente__r.PersonEmail, Contrato_de_Servi_o_Relacionado__r.Locador_a__r.CNPJ__c, idDocAutentique__c, Contrato_de_Servi_o_Relacionado__r.Nome_da_Testemunha__c, Contrato_de_Servi_o_Relacionado__r.Contato_do_Locat_rio__r.Name, Contrato_de_Servi_o_Relacionado__r.Contato_do_Locat_rio__r.Email, Contrato_de_Servi_o_Relacionado__r.Timbre__c, Contrato_de_Servi_o_Relacionado__r.E_mail_da_Testemunha__c, Contrato_de_Servi_o_Relacionado__r.Documento_Assinado__c FROM Aditivos_Contratuais__c WHERE ID= 'a1j6e000009ti8P'];        
        
        AutentiqueAditivo AC = new AutentiqueAditivo(new ApexPages.StandardController(Contrato));
        
        AC.atualizar();
        AC.inserir();
        AC.enviar();
        
    }
    @isTest
    private static void teste2(){
        
        Test.setMock(HttpCalloutMock.class, new MockAutentiqueContratos2());
        
        
        Aditivos_Contratuais__c Contrato = [SELECT Name, N_do_Aditivo__c, Contrato_de_Servi_o_Relacionado__r.Name, Contrato_de_Servi_o_Relacionado__r.Cliente__r.Name, Contrato_de_Servi_o_Relacionado__r.Cliente__r.PersonEmail, Contrato_de_Servi_o_Relacionado__r.Locador_a__r.CNPJ__c, idDocAutentique__c, Contrato_de_Servi_o_Relacionado__r.Nome_da_Testemunha__c, Contrato_de_Servi_o_Relacionado__r.Contato_do_Locat_rio__r.Name, Contrato_de_Servi_o_Relacionado__r.Contato_do_Locat_rio__r.Email, Contrato_de_Servi_o_Relacionado__r.Timbre__c, Contrato_de_Servi_o_Relacionado__r.E_mail_da_Testemunha__c, Contrato_de_Servi_o_Relacionado__r.Documento_Assinado__c FROM Aditivos_Contratuais__c WHERE ID= 'a1j6e000009ti8P'];        
        
        AutentiqueAditivo AC = new AutentiqueAditivo(new ApexPages.StandardController(Contrato));
        
        AC.enviar();
        
    }
}