force-app/main/default/objects/Historico_do_produto__c/Historico_do_produto__c.object-meta.xml
<CustomObject>
    <label>Atualização do Produto</label>
    <nameField>
        <label>Nome de Histórico do p</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Atualizações do Produto</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Historico_do_produto__c/fields/Ativo_no_commerce__c.field-meta.xml
<CustomField>
    <fullName>Ativo_no_commerce__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ativo no commerce</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Historico_do_produto__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Descrição</label>
    <length>3990</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Historico_do_produto__c/fields/Family__c.field-meta.xml
<CustomField>
    <fullName>Family__c</fullName>
    <label>Família</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ALTO FLUXO</fullName>
            </value>
            <value>
                <fullName>ANESTESIA</fullName>
            </value>
            <value>
                <fullName>APOIO A MOBILIDADE</fullName>
            </value>
            <value>
                <fullName>ARCO CIRURGICO</fullName>
            </value>
            <value>
                <fullName>ASPIRADORES</fullName>
            </value>
            <value>
                <fullName>BERÇOS</fullName>
            </value>
            <value>
                <fullName>BERÇOS AQUECIDOS</fullName>
            </value>
            <value>
                <fullName>BPAP</fullName>
            </value>
            <value>
                <fullName>CADEIRAS</fullName>
            </value>
            <value>
                <fullName>CAMAS</fullName>
            </value>
            <value>
                <fullName>CAMAS HOSPITALARES</fullName>
            </value>
            <value>
                <fullName>CARDIOLOGIA</fullName>
            </value>
            <value>
                <fullName>CIRURGIA MINIMAMENTE INVASIVA</fullName>
            </value>
            <value>
                <fullName>CIRURGIA ROBÓTICA</fullName>
            </value>
            <value>
                <fullName>CONCENTRADORES</fullName>
            </value>
            <value>
                <fullName>ELETROCIRURGIA</fullName>
            </value>
            <value>
                <fullName>ELEVADORES</fullName>
            </value>
            <value>
                <fullName>ENDOSCOPIA</fullName>
            </value>
            <value>
                <fullName>FOCOS CIRÚRGICOS</fullName>
            </value>
            <value>
                <fullName>FOTOTERAPIA</fullName>
            </value>
            <value>
                <fullName>GERAL</fullName>
            </value>
            <value>
                <fullName>GINECOLOGIA</fullName>
            </value>
            <value>
                <fullName>HIGIENE</fullName>
            </value>
            <value>
                <fullName>IMAGEM</fullName>
            </value>
            <value>
                <fullName>INALADORES</fullName>
            </value>
            <value>
                <fullName>INCUBADORAS</fullName>
            </value>
            <value>
                <fullName>INFUSÃO</fullName>
            </value>
            <value>
                <fullName>INSTRUMENTAIS CIRURGICOS</fullName>
            </value>
            <value>
                <fullName>LABORATORIAL</fullName>
            </value>
            <value>
                <fullName>LAPAROSCOPIA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Historico_do_produto__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Historico_do_produto__c/fields/Linha__c.field-meta.xml
<CustomField>
    <fullName>Linha__c</fullName>
    <label>Linha</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>APOIO A MOBILIDADE</fullName>
                <isActive>false</isActive>
                <label>APOIO A MOBILIDADE</label>
            </value>
            <value>
                <fullName>CAMAS HOSPITALARES</fullName>
            </value>
            <value>
                <fullName>CIRURGIA MINIMAMENTE INVASIVA</fullName>
            </value>
            <value>
                <fullName>CIRURGIA ROBÓTICA</fullName>
            </value>
            <value>
                <fullName>CUIDADOS PESSOAIS</fullName>
                <isActive>false</isActive>
                <label>CUIDADOS PESSOAIS</label>
            </value>
            <value>
                <fullName>ELETROCIRURGIA</fullName>
            </value>
            <value>
                <fullName>ENDOSCOPIA</fullName>
            </value>
            <value>
                <fullName>ESTERILIZACAO</fullName>
                <isActive>false</isActive>
                <label>ESTERILIZACAO</label>
            </value>
            <value>
                <fullName>IMAGEM RAIO-X</fullName>
            </value>
            <value>
                <fullName>IMAGEM ULTRASSOM</fullName>
            </value>
            <value>
                <fullName>LABORATORIAL</fullName>
                <isActive>false</isActive>
                <label>LABORATORIAL</label>
            </value>
            <value>
                <fullName>MONITORES DE GRAU MEDICO</fullName>
            </value>
            <value>
                <fullName>NEONATOLOGIA</fullName>
            </value>
            <value>
                <fullName>OPME</fullName>
            </value>
            <value>
                <fullName>OUTROS</fullName>
            </value>
            <value>
                <fullName>PM</fullName>
            </value>
            <value>
                <fullName>PMLS</fullName>
            </value>
            <value>
                <fullName>SURGICAL</fullName>
            </value>
            <value>
                <fullName>VETERINÁRIA</fullName>
                <isActive>false</isActive>
                <label>VETERINÁRIA</label>
            </value>
            <value>
                <fullName>VETERINÁRIA IVD</fullName>
            </value>
            <value>
                <fullName>VETERINÁRIA MIS</fullName>
            </value>
            <value>
                <fullName>VETERINÁRIA PMLS</fullName>
            </value>
            <value>
                <fullName>VIAS AÉREAS DIFÍCEIS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Historico_do_produto__c/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>7LIVES</fullName>
            </value>
            <value>
                <fullName>ABC</fullName>
            </value>
            <value>
                <fullName>ACCUMED</fullName>
            </value>
            <value>
                <fullName>ACTE</fullName>
            </value>
            <value>
                <fullName>AEROGEN</fullName>
            </value>
            <value>
                <fullName>AGATA</fullName>
            </value>
            <value>
                <fullName>AIR LIQUIDE</fullName>
            </value>
            <value>
                <fullName>AIR SHIELD</fullName>
            </value>
            <value>
                <fullName>ALBAN</fullName>
            </value>
            <value>
                <fullName>ALIVE HEART</fullName>
            </value>
            <value>
                <fullName>ALLIAGE</fullName>
            </value>
            <value>
                <fullName>ALVIMÉDICA</fullName>
            </value>
            <value>
                <fullName>ANALYSER</fullName>
            </value>
            <value>
                <fullName>ANESTHESIA</fullName>
            </value>
            <value>
                <fullName>AOC</fullName>
            </value>
            <value>
                <fullName>APK</fullName>
            </value>
            <value>
                <fullName>APPLE</fullName>
            </value>
            <value>
                <fullName>ARJO</fullName>
            </value>
            <value>
                <fullName>ARJOHUNTLEIGH</fullName>
            </value>
            <value>
                <fullName>ARKTUS</fullName>
            </value>
            <value>
                <fullName>Arroyo</fullName>
            </value>
            <value>
                <fullName>ARTROCORP</fullName>
            </value>
            <value>
                <fullName>ASSUT EUROPE</fullName>
            </value>
            <value>
                <fullName>ATHOS</fullName>
            </value>
            <value>
                <fullName>ATRAMAT</fullName>
            </value>
            <value>
                <fullName>AWAREWESS</fullName>
            </value>
            <value>
                <fullName>AXMED</fullName>
            </value>
            <value>
                <fullName>BALT</fullName>
            </value>
            <value>
                <fullName>BAUMER</fullName>
            </value>
            <value>
                <fullName>BEACON</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Historico_do_produto__c/fields/Modelo__c.field-meta.xml
<CustomField>
    <fullName>Modelo__c</fullName>
    <label>Modelo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_do_produto__c/fields/Num_Anvisa__c.field-meta.xml
<CustomField>
    <fullName>Num_Anvisa__c</fullName>
    <label>Num. Anvisa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_do_produto__c/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <label>Cod. fabricante</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_do_produto__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Historicos_do_Produto</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Historico_do_produto__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EM APROVAÇÃO</fullName>
            </value>
            <value>
                <fullName>APROVADO</fullName>
            </value>
            <value>
                <fullName>REPROVADO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Historico_do_produto__c/fields/StockKeepingUnit__c.field-meta.xml
<CustomField>
    <fullName>StockKeepingUnit__c</fullName>
    <label>Cod. Hospcom</label>
    <length>180</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_do_produto__c/fields/Tipo_do_Produto__c.field-meta.xml
<CustomField>
    <fullName>Tipo_do_Produto__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACESSÓRIO</fullName>
            </value>
            <value>
                <fullName>CONSUMÍVEL</fullName>
            </value>
            <value>
                <fullName>EQUIPAMENTO</fullName>
            </value>
            <value>
                <fullName>FERRAMENTA</fullName>
            </value>
            <value>
                <fullName>IMPLANTE</fullName>
            </value>
            <value>
                <fullName>INSTRUMENTAL</fullName>
            </value>
            <value>
                <fullName>INSUMO</fullName>
            </value>
            <value>
                <fullName>KIT SERVIÇO</fullName>
            </value>
            <value>
                <fullName>MÓDULO</fullName>
            </value>
            <value>
                <fullName>MOVEIS</fullName>
            </value>
            <value>
                <fullName>OPCIONAL</fullName>
            </value>
            <value>
                <fullName>PEÇA</fullName>
            </value>
            <value>
                <fullName>SERVIÇO</fullName>
            </value>
            <value>
                <fullName>SET CIRURGICO</fullName>
            </value>
            <value>
                <fullName>SOFTWARE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Historico_do_produto__c/fields/Valor_de_Venda__c.field-meta.xml
<CustomField>
    <fullName>Valor_de_Venda__c</fullName>
    <label>Valor de Venda</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/HistoricoProdutoTriggerTest.cls
@IsTest(seeAllData=true)
public class HistoricoProdutoTriggerTest {
    @IsTest
    public static void testHistoricoProdutoTrigger() {
        
        
        
        String objetoJSON = '{"StockKeepingUnit__c":"00034530","Linha__c":"OUTROS","ProductCode__c":"1265","Family__c":"OUTROS","Name":"TESssssTE","Tipo_do_Produto__c":"EQUIPAMENTO","Marca__c":"OUTROS","Num_Anvisa__c":"456789","Modelo__c":"OUTROS","IsActive__c":"true","Valor_de_Venda__c":"1000","Ativo_no_commerce__c":"true","Description__c":"teste","Observacoes__c":"d", "Produto__c":"01t5A000008BV2c" }';
        
      
        Id recordId = HistoricoProduto.criarHistorico(objetoJSON);
        
        List<Historico_do_produto__c> hpList = [SELECT Id, Status__c FROM Historico_do_produto__c WHERE Id = :recordId];
        
        if (!hpList.isEmpty()) {
            Historico_do_produto__c hp = hpList[0];
            
         
            System.debug('Status antes da alteração: ' +  hp.Status__c);
            hp.Status__c = 'APROVADO';
            
            update hp;
        } else {
            System.debug('Registro Historico_do_produto__c não encontrado.');
        }
    }
}