force-app/main/default/objects/Documento__c/Documento__c.object-meta.xml
<CustomObject>
    <label>Documento (Chat Licitação)</label>
    <nameField>
        <label>Nome de Documento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documetos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Gest_o_de_Documentos__c/Gest_o_de_Documentos__c.object-meta.xml
<CustomObject>
    <description>Objeto destinado ao controle da qualidade quanto a revisão e renovação dos documenos</description>
    <label>Gestão de Documento</label>
    <nameField>
        <displayFormat>GD - {0000}</displayFormat>
        <label>Nome de Gestão de Documentos</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gestão de Documentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Gest_o_de_Documentos__c/fields/Data_de_criacao__c.field-meta.xml
<CustomField>
    <fullName>Data_de_criacao__c</fullName>
    <label>Data de criação</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Gest_o_de_Documentos__c/fields/Documento__c.field-meta.xml
<CustomField>
    <fullName>Documento__c</fullName>
    <label>Documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ata de Reunião</fullName>
            </value>
            <value>
                <fullName>Auditoria de Acuracidade</fullName>
            </value>
            <value>
                <fullName>Checklist de Auditoria</fullName>
            </value>
            <value>
                <fullName>Checklist de Entrega e Recebimento</fullName>
            </value>
            <value>
                <fullName>Checkliste de Auditoria Estrutural Semanal</fullName>
            </value>
            <value>
                <fullName>Contrato de Demonstração e Empréstimo</fullName>
            </value>
            <value>
                <fullName>Contrato de Locação</fullName>
            </value>
            <value>
                <fullName>Ordem de Trabalho - Ordem de Serviço Emergencial</fullName>
            </value>
            <value>
                <fullName>Ordem de Trabalho - Registro de Atendimento</fullName>
            </value>
            <value>
                <fullName>Ordem de Trabalho - Registro de Base Instalada</fullName>
            </value>
            <value>
                <fullName>PAC</fullName>
            </value>
            <value>
                <fullName>Plano de Ação</fullName>
            </value>
            <value>
                <fullName>PMP</fullName>
            </value>
            <value>
                <fullName>Registro de Avaliação de Fornecedores</fullName>
            </value>
            <value>
                <fullName>Registro de Demonstração e Locação</fullName>
            </value>
            <value>
                <fullName>Registro de Limpeza da Piscina</fullName>
            </value>
            <value>
                <fullName>Registro de Limpeza das Áreas</fullName>
            </value>
            <value>
                <fullName>Registro de Reclamação de Clientes</fullName>
            </value>
            <value>
                <fullName>Registro de Temperatura e Umidade</fullName>
            </value>
            <value>
                <fullName>Registro de Treinamento Corporativo</fullName>
            </value>
            <value>
                <fullName>Registro de Verificação de Manutenção</fullName>
            </value>
            <value>
                <fullName>Relatório de Ação Corretiva</fullName>
            </value>
            <value>
                <fullName>Relatório de Auditoria</fullName>
            </value>
            <value>
                <fullName>Relatório de Não Conformidade</fullName>
            </value>
            <value>
                <fullName>Termo de Uso de EPI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gest_o_de_Documentos__c/fields/Empresa__c.field-meta.xml
<CustomField>
    <fullName>Empresa__c</fullName>
    <label>Empresa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABC GO</fullName>
            </value>
            <value>
                <fullName>ABC MT</fullName>
            </value>
            <value>
                <fullName>ABC - SP</fullName>
            </value>
            <value>
                <fullName>ABC TO</fullName>
            </value>
            <value>
                <fullName>GDB</fullName>
            </value>
            <value>
                <fullName>HEALTH</fullName>
            </value>
            <value>
                <fullName>HOSPCOM GO</fullName>
            </value>
            <value>
                <fullName>HOSPCOM 153</fullName>
            </value>
            <value>
                <fullName>HOSPCOM DF</fullName>
            </value>
            <value>
                <fullName>HOSPCOM MT</fullName>
            </value>
            <value>
                <fullName>HOSPCOM SP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gest_o_de_Documentos__c/fields/Empresa_pesquisa__c.field-meta.xml
<CustomField>
    <fullName>Empresa_pesquisa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empresa</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Gestão de Documentos</relationshipLabel>
    <relationshipName>Gest_o_de_Documentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Gest_o_de_Documentos__c/fields/N_mero_de_Revis_o__c.field-meta.xml
<CustomField>
    <fullName>N_mero_de_Revis_o__c</fullName>
    <label>Número de Revisão</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Gest_o_de_Documentos__c/fields/Revisao__c.field-meta.xml
<CustomField>
    <fullName>Revisao__c</fullName>
    <label>Revisão</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Gest_o_de_Documentos__c/fields/SISTEMA__c.field-meta.xml
<CustomField>
    <fullName>SISTEMA__c</fullName>
    <label>SISTEMA</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SIM</fullName>
            </value>
            <value>
                <fullName>NÃO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Gest_o_de_Documentos__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EM ELABORAÇÃO</fullName>
            </value>
            <value>
                <fullName>EM APROVAÇÃO</fullName>
            </value>
            <value>
                <fullName>DESENVOLVIMENTO</fullName>
            </value>
            <value>
                <fullName>VIGENTE</fullName>
            </value>
            <value>
                <fullName>OBSOLETO</fullName>
            </value>
            <value>
                <fullName>CANCELADO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GestaoDocumentos.cls
public class GestaoDocumentos {

    public static List<Gest_o_de_Documentos__c> obterDocumentosVigentes() {
        List<Gest_o_de_Documentos__c> documentos = [SELECT Id, Name, Data_de_criacao__c, Revisao__c, Documento__c, Empresa__c, N_mero_de_Revis_o__c, SISTEMA__c, Status__c, RecordTypeId, Empresa_pesquisa__c
                                                    FROM Gest_o_de_Documentos__c
                                                    WHERE Status__c = 'VIGENTE'];
        return documentos;
    }
}