force-app/main/default/objects/Lancamento_Financeiro__c/Lancamento_Financeiro__c.object-meta.xml
<CustomObject>
    <label>Lançamento Financeiro</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lançamentos Financeiros</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Lancamento_Financeiro__c/fields/Data_Lancamento__c.field-meta.xml
<CustomField>
    <fullName>Data_Lancamento__c</fullName>
    <label>Data Lançamento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lancamento_Financeiro__c/fields/Data_Vencimento__c.field-meta.xml
<CustomField>
    <fullName>Data_Vencimento__c</fullName>
    <label>Data Vencimento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lancamento_Financeiro__c/fields/Processo_Judicial__c.field-meta.xml
<CustomField>
    <fullName>Processo_Judicial__c</fullName>
    <label>Processo Judicial</label>
    <referenceTo>Processo_Judicial__c</referenceTo>
    <relationshipLabel>Lançamentos Financeiros</relationshipLabel>
    <relationshipName>Lan_amentos_Financeiros</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Lancamento_Financeiro__c/fields/Valor__c.field-meta.xml
<CustomField>
    <fullName>Valor__c</fullName>
    <label>Valor</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Lancamento_Financeiro__c/fields/Valor_Baixa__c.field-meta.xml
<CustomField>
    <fullName>Valor_Baixa__c</fullName>
    <label>Valor Baixa</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Processo_Judicial__c/Processo_Judicial__c.object-meta.xml
<CustomObject>
    <label>Processo Judicial</label>
    <nameField>
        <label>Nº</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processos Judiciais</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/FinanceiroProjurisTest.cls
@isTest(seeAllData=true)
public class FinanceiroProjurisTest {

    @isTest
    static void testFutureMethod() {
        // Mockando a resposta da chamada de API de autenticação
        HttpResponse authResponse = new HttpResponse();
        authResponse.setStatusCode(200);
        authResponse.setBody('{"access_token":"mock_token"}');

        // Mockando a resposta da chamada de API de processo
        HttpResponse processoResponse = new HttpResponse();
        processoResponse.setStatusCode(200);
        processoResponse.setBody('{"content":[{"nota":"nota de exemplo","valor":100.0,"dataLancamento":"2023-01-01","valorBaixa":50.0,"dataVencimento":"2023-01-31"}]}');
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(authResponse, processoResponse));
        
        // Iniciar a execução do método @future
        Test.startTest();
        FinanceiroProjuris.pesquisa();
        Test.stopTest();

        // Verificar se os lançamentos financeiros foram criados ou atualizados
        List<Lancamento_Financeiro__c> updatedLancamentos = [SELECT ID, Name, Valor__c, Data_Lancamento__c, Valor_Baixa__c, Data_Vencimento__c, Processo_Judicial__c FROM Lancamento_Financeiro__c];
        

    }
    
    private class MockHttpResponseGenerator implements HttpCalloutMock {
        private HttpResponse authResponse;
        private HttpResponse processoResponse;

        public MockHttpResponseGenerator(HttpResponse authResponse, HttpResponse processoResponse) {
            this.authResponse = authResponse;
            this.processoResponse = processoResponse;
        }

        public HttpResponse respond(HttpRequest req) {
            if (req.getEndpoint().contains('authenticate')) {
                return authResponse;
            } else if (req.getEndpoint().contains('financeiro/pageable')) {
                return processoResponse;
            }
            return null;
        }
    }
}