force-app/main/default/objects/Registro_de_demo_rapida__c/Registro_de_demo_rapida__c.object-meta.xml
<CustomObject>
    <label>Registro de demo rápida</label>
    <nameField>
        <displayFormat>DR {0000}</displayFormat>
        <label>Nº</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Registros de demo rápida</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Registro_de_demo_rapida__c/fields/Comodato__c.field-meta.xml
<CustomField>
    <fullName>Comodato__c</fullName>
    <label>Comodato</label>
    <referenceTo>Demonstracao__c</referenceTo>
    <relationshipLabel>Registros de demo rápida</relationshipLabel>
    <relationshipName>Registros_de_demo_r_pida</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Registro_de_demo_rapida__c/fields/Data_da_demonstracao__c.field-meta.xml
<CustomField>
    <fullName>Data_da_demonstracao__c</fullName>
    <label>Data da demonstração</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Registro_de_demo_rapida__c/fields/Data_de_termino_da_demonstracao__c.field-meta.xml
<CustomField>
    <fullName>Data_de_termino_da_demonstracao__c</fullName>
    <label>Data de término da demonstração</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/RegistroDeDemoRapidaValidaTest.cls
@isTest(seeAllData=true)
public class RegistroDeDemoRapidaValidaTest {
    @isTest
    static void teste1() {

        // Cria um novo registro sem sobreposição
        Registro_de_Demo_Rapida__c record2 = new Registro_de_Demo_Rapida__c(
            Comodato__c = 'a0KU400001HKYmQ',
            Data_da_Demonstracao__c = Date.newInstance(2024, 10, 7),
            Data_de_Termino_da_Demonstracao__c = Date.newInstance(2024, 10, 8)
        );

        Test.startTest();
        insert record2;
        Test.stopTest();

    }

}