force-app/main/default/objects/Transfer_ncia_Hospcoin__c/Transfer_ncia_Hospcoin__c.object-meta.xml
<CustomObject>
    <label>Transferência Hospcoin</label>
    <nameField>
        <displayFormat>TH{00000}</displayFormat>
        <label>Nome de Transferência Hospcoin</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transferências Hospcoin</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transfer_ncia_Hospcoin__c/fields/Carteira_Destinataria__c.field-meta.xml
<CustomField>
    <fullName>Carteira_Destinataria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Carteira Destinatária</label>
    <referenceTo>Carteira__c</referenceTo>
    <relationshipLabel>Transferências Hospcoin (Carteira Destinatária)</relationshipLabel>
    <relationshipName>Transferencias_Hospcoin_destinatario</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transfer_ncia_Hospcoin__c/fields/Carteira_Remetente__c.field-meta.xml
<CustomField>
    <fullName>Carteira_Remetente__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Carteira Remetente</label>
    <referenceTo>Carteira__c</referenceTo>
    <relationshipLabel>Transferências Hospcoin</relationshipLabel>
    <relationshipName>Transferencias_Hospcoin</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transfer_ncia_Hospcoin__c/fields/Programa__c.field-meta.xml
<CustomField>
    <fullName>Programa__c</fullName>
    <label>Programa</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>5S</fullName>
            </value>
            <value>
                <fullName>Programa Valeu</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transfer_ncia_Hospcoin__c/fields/Quantidade_de_Hospcoins__c.field-meta.xml
<CustomField>
    <fullName>Quantidade_de_Hospcoins__c</fullName>
    <label>Quantidade de Hospcoins</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/HospcoinTransferencia.cls
public class HospcoinTransferencia {

	
    @AuraEnabled    
    public static void transderenciaRH(Id idCarteiraDestinataria, Id idCarteiraRemetente, Decimal saldo, String programa){
        	
       Transfer_ncia_Hospcoin__c transferencia = new Transfer_ncia_Hospcoin__c();
        
        
        
        
        transferencia.Carteira_Destinataria__c = idCarteiraDestinataria;
        transferencia.Carteira_Remetente__c = idCarteiraRemetente;
        transferencia.Quantidade_de_Hospcoins__c = saldo;
        transferencia.Programa__c = programa;
        
        try{
        	insert transferencia ;
        }catch(Exception e){
            throw new AuraHandledException('ERROR: ' + e.getMessage());
        }
    }
}