force-app/main/default/objects/Asset/fields/Contrato_de_Servi_o__c.field-meta.xml
<CustomField>
    <fullName>Contrato_de_Servi_o__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato de Serviço</label>
    <referenceTo>ServiceContract</referenceTo>
    <relationshipLabel>Ativos</relationshipLabel>
    <relationshipName>Ativos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Nome_do_Ativo__c.field-meta.xml
<CustomField>
    <fullName>Nome_do_Ativo__c</fullName>
    <label>Nome SOMASUS</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACELERADOR LINEAR</fullName>
            </value>
            <value>
                <fullName>AFIADOR DE FACAS</fullName>
            </value>
            <value>
                <fullName>AGITADOR DE KLINE</fullName>
            </value>
            <value>
                <fullName>AGITADOR DE PLAQUETAS</fullName>
            </value>
            <value>
                <fullName>AGITADOR DE TUBOS (VÓRTEX)</fullName>
            </value>
            <value>
                <fullName>AGITADOR HORIZONTAL</fullName>
            </value>
            <value>
                <fullName>AGITADOR MAGNÉTICO</fullName>
            </value>
            <value>
                <fullName>AGITADOR ROTATIVO</fullName>
            </value>
            <value>
                <fullName>AGLUTINOSCÓPIO</fullName>
            </value>
            <value>
                <fullName>AMACIADOR ELÉTRICO PARA CARNE</fullName>
            </value>
            <value>
                <fullName>AMALGAMADOR ODONTOLÓGICO</fullName>
            </value>
            <value>
                <fullName>AMBULÂNCIA</fullName>
            </value>
            <value>
                <fullName>AMNIOSCÓPIO</fullName>
            </value>
            <value>
                <fullName>ANALISADOR AUTOMÁTICO PARA HEMATOLOGIA</fullName>
            </value>
            <value>
                <fullName>ANALISADOR BIOQUÍMICO</fullName>
            </value>
            <value>
                <fullName>ANALISADOR DE CULTURA SANGUÍNEA</fullName>
            </value>
            <value>
                <fullName>ANALISADOR DE ÍONS/ ELETRÓLITOS</fullName>
            </value>
            <value>
                <fullName>ANALISADOR DE OUVIDO MÉDIO</fullName>
            </value>
            <value>
                <fullName>ANALISADOR DE PH</fullName>
            </value>
            <value>
                <fullName>ANALISADOR PARA CA++ E PH</fullName>
            </value>
            <value>
                <fullName>ANALISADOR PARA IMUNOENSAIO</fullName>
            </value>
            <value>
                <fullName>APARELHO DE ANESTESIA</fullName>
            </value>
            <value>
                <fullName>APARELHO DE ANESTESIA SIMPLES</fullName>
            </value>
            <value>
                <fullName>APARELHO DE BIPAP</fullName>
            </value>
            <value>
                <fullName>APARELHO DE CORRENTE INTERFERENCIAL</fullName>
            </value>
            <value>
                <fullName>APARELHO DE DVD</fullName>
            </value>
            <value>
                <fullName>APARELHO DE FAX</fullName>
            </value>
            <value>
                <fullName>APARELHO DE KARL FISCHER</fullName>
            </value>
            <value>
                <fullName>APARELHO DE LUZ INFRAVERMELHA</fullName>
            </value>
            <value>
                <fullName>APARELHO DE OXIMETRO SPO2 PORTATIL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/URL_da_Imagem__c.field-meta.xml
<CustomField>
    <fullName>URL_da_Imagem__c</fullName>
    <label>URL da Imagem</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Ativos_do_Contrato__c/Ativos_do_Contrato__c.object-meta.xml
<CustomObject>
    <label>Ativo do Contrato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>N° de Registro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ativos do Contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ativos_do_Contrato__c/fields/Ativo_Locado__c.field-meta.xml
<CustomField>
    <fullName>Ativo_Locado__c</fullName>
    <label>Ativo Locado</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Ativos do Contrato</relationshipLabel>
    <relationshipName>Ativos_do_Contrato</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ativos_do_Contrato__c/fields/Contrato_de_Servico__c.field-meta.xml
<CustomField>
    <fullName>Contrato_de_Servico__c</fullName>
    <label>Contrato de Serviço</label>
    <referenceTo>Contrato_de_Servi_o__c</referenceTo>
    <relationshipLabel>Ativos do Contrato</relationshipLabel>
    <relationshipName>Ativos_do_Contrato</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ativos_do_Contrato__c/fields/Data_de_entrega__c.field-meta.xml
<CustomField>
    <fullName>Data_de_entrega__c</fullName>
    <label>Data de entrega</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Ativos_do_Contrato__c/fields/Data_de_Entrega_formatada__c.field-meta.xml
<CustomField>
    <fullName>Data_de_Entrega_formatada__c</fullName>
    <formula>IF(
DAY(DATEVALUE(Data_de_entrega__c)) &lt; 10,
&apos;0&apos; &amp; TEXT(DAY(DATEVALUE(Data_de_entrega__c))),
TEXT(DAY(DATEVALUE(Data_de_entrega__c)))
)
+ &quot;/&quot; +
IF(
MONTH(DATEVALUE(Data_de_entrega__c)) &lt; 10,
&apos;0&apos; &amp; TEXT(MONTH(DATEVALUE(Data_de_entrega__c))),
TEXT(MONTH(DATEVALUE(Data_de_entrega__c)))
)
+ &quot;/&quot; +
TEXT(YEAR(DATEVALUE(Data_de_entrega__c)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Data de Entrega formatada</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ativos_do_Contrato__c/fields/Data_de_retorno__c.field-meta.xml
<CustomField>
    <fullName>Data_de_retorno__c</fullName>
    <label>Data de retorno</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Ativos_do_Contrato__c/fields/Data_de_retorno_formatada__c.field-meta.xml
<CustomField>
    <fullName>Data_de_retorno_formatada__c</fullName>
    <formula>IF(
DAY(Data_de_retorno__c) &lt; 10,
&apos;0&apos; &amp; TEXT(DAY(Data_de_retorno__c)),
TEXT(DAY(Data_de_retorno__c))
)
+ &quot;/&quot; +
IF(
MONTH(Data_de_retorno__c) &lt; 10,
&apos;0&apos; &amp; TEXT(MONTH(Data_de_retorno__c)),
TEXT(MONTH(Data_de_retorno__c))
)
+ &quot;/&quot; +
TEXT(YEAR(Data_de_retorno__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Data de retorno (formatada)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ativos_do_Contrato__c/fields/Equipamento_no_Cliente__c.field-meta.xml
<CustomField>
    <fullName>Equipamento_no_Cliente__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Equipamento no Cliente</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Ativos_do_Contrato__c/fields/N_de_S_rie__c.field-meta.xml
<CustomField>
    <fullName>N_de_S_rie__c</fullName>
    <formula>Ativo_Locado__r.SerialNumber</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>N° de Série</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ativos_do_Contrato__c/fields/Nome_do_ativo__c.field-meta.xml
<CustomField>
    <fullName>Nome_do_ativo__c</fullName>
    <formula>Ativo_Locado__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nome do ativo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ativos_do_Contrato__c/fields/URL_da_Imagem__c.field-meta.xml
<CustomField>
    <fullName>URL_da_Imagem__c</fullName>
    <formula>Ativo_Locado__r.Product2.URL_da_Imagem__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>URL da Imagem</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ativos_do_Contrato__c/fields/Valor_Total_Mensal_Atual__c.field-meta.xml
<CustomField>
    <fullName>Valor_Total_Mensal_Atual__c</fullName>
    <label>Valor Total Mensal Atual</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/Contrato_de_Servi_o__c.object-meta.xml
<CustomObject>
    <label>Contrato de Serviço</label>
    <nameField>
        <label>Nome do Contrato</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contratos de Serviços</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Forma_de_pagamento2__c.field-meta.xml
<CustomField>
    <fullName>Forma_de_pagamento2__c</fullName>
    <label>Forma de pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Formas_de_pagamento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Locat_rio_a__c.field-meta.xml
<CustomField>
    <fullName>Locat_rio_a__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Locatário(a)/Contratante</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contratos de Locação</relationshipLabel>
    <relationshipName>Contratos_de_Servi_os2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Unidade_hospitalar__c.field-meta.xml
<CustomField>
    <fullName>Unidade_hospitalar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unidade hospitalar</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contratos de Serviços (Unidade hospitalar)</relationshipLabel>
    <relationshipName>Contratos_de_Servi_os6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Vendedor_do_Contrato__c.field-meta.xml
<CustomField>
    <fullName>Vendedor_do_Contrato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor do Contrato</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contratos_de_Servi_os</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Condicao_de_pagamento__c.field-meta.xml
<CustomField>
    <fullName>Condicao_de_pagamento__c</fullName>
    <label>Condição de pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Natureza_de_Opera_o__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Condicoes_de_pagamento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Contrato_de_Servi_o__c.field-meta.xml
<CustomField>
    <fullName>Contrato_de_Servi_o__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato de Serviço</label>
    <referenceTo>Contrato_de_Servi_o__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Data_de_entrega__c.field-meta.xml
<CustomField>
    <fullName>Data_de_entrega__c</fullName>
    <inlineHelpText>Da Hospcom ao Cliente, maior data dentre os itens.</inlineHelpText>
    <label>_Data de entrega (del)</label>
    <summarizedField>OrderItem.Data_de_entrega__c</summarizedField>
    <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order/fields/Departamento3__c.field-meta.xml
<CustomField>
    <fullName>Departamento3__c</fullName>
    <label>Departamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Departamentos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Entrega_parcial__c.field-meta.xml
<CustomField>
    <fullName>Entrega_parcial__c</fullName>
    <label>Entrega parcial</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Autorizada</fullName>
            </value>
            <value>
                <fullName>Não Autorizada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Forma_de_pagamento2__c.field-meta.xml
<CustomField>
    <fullName>Forma_de_pagamento2__c</fullName>
    <label>Forma de pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Natureza_de_Opera_o__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Formas_de_pagamento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Frete__c.field-meta.xml
<CustomField>
    <fullName>Frete__c</fullName>
    <label>Tipo de envio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipos_de_envio</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Ignora_validacao__c.field-meta.xml
<CustomField>
    <fullName>Ignora_validacao__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ignora validação</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Locado_em__c.field-meta.xml
<CustomField>
    <fullName>Locado_em__c</fullName>
    <label>Locado em:</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Unidade_Hospitalar__c.field-meta.xml
<CustomField>
    <fullName>Unidade_Hospitalar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unidade Hospitalar</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pedidos (Unidade Hospitalar)</relationshipLabel>
    <relationshipName>Pedidos1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Data_de_entrega__c.field-meta.xml
<CustomField>
    <fullName>Data_de_entrega__c</fullName>
    <inlineHelpText>Da Hospcom ao cliente, maior data dentre as entregas do item.</inlineHelpText>
    <label>_Data de entrega (del)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product2/fields/URL_da_Imagem__c.field-meta.xml
<CustomField>
    <fullName>URL_da_Imagem__c</fullName>
    <defaultValue>&quot;https://hospcom.my.site.com/servlet/servlet.ImageServer?id=015310000080hog&amp;oid=00Di0000000JVhH&amp;lastMod=1502888568000&quot;</defaultValue>
    <label>URL da Imagem</label>
    <type>Url</type>
</CustomField>

force-app/main/default/globalValueSets/Departamentos.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Administrativo</fullName>
    </customValue>
    <customValue>
        <fullName>Comercial</fullName>
    </customValue>
    <customValue>
        <fullName>Compras</fullName>
    </customValue>
    <customValue>
        <fullName>Contabilidade</fullName>
        <label>Contabilidade/Fiscal/DP</label>
    </customValue>
    <customValue>
        <fullName>Controladoria</fullName>
    </customValue>
    <customValue>
        <fullName>Desenvolvimento</fullName>
    </customValue>
    <customValue>
        <fullName>Diretoria Administrativa</fullName>
    </customValue>
    <customValue>
        <fullName>Diretoria de B.I e Growth</fullName>
    </customValue>
    <customValue>
        <fullName>Diretoria de Negocios</fullName>
    </customValue>
    <customValue>
        <fullName>Educação</fullName>
        <label>Educação Continuada</label>
    </customValue>
    <customValue>
        <fullName>Faturamento</fullName>
    </customValue>
    <customValue>
        <fullName>Financeiro</fullName>
    </customValue>
    <customValue>
        <fullName>Governo</fullName>
    </customValue>
    <customValue>
        <fullName>Jurídico</fullName>
    </customValue>
    <customValue>
        <fullName>Locação</fullName>
    </customValue>
    <customValue>
        <fullName>Logística</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Operações</fullName>
    </customValue>
    <customValue>
        <fullName>Outros</fullName>
    </customValue>
    <customValue>
        <fullName>Qualidade</fullName>
    </customValue>
    <customValue>
        <fullName>RH</fullName>
    </customValue>
    <customValue>
        <fullName>Serviço</fullName>
    </customValue>
    <customValue>
        <fullName>Departamento Pessoal</fullName>
        <isActive>false</isActive>
        <label>Departamento Pessoal</label>
    </customValue>
    <customValue>
        <fullName>Facilites</fullName>
        <isActive>false</isActive>
        <label>Facilites</label>
    </customValue>
    <customValue>
        <fullName>T.I.</fullName>
        <isActive>false</isActive>
        <label>T.I.</label>
    </customValue>
    <customValue>
        <fullName>OPME</fullName>
        <isActive>false</isActive>
        <label>OPME</label>
    </customValue>
    <customValue>
        <fullName>Manutenção</fullName>
        <isActive>false</isActive>
        <label>Manutenção</label>
    </customValue>
    <customValue>
        <fullName>Limpeza</fullName>
        <isActive>false</isActive>
        <label>Limpeza</label>
    </customValue>
    <customValue>
        <fullName>Fiscal</fullName>
        <isActive>false</isActive>
        <label>Fiscal</label>
    </customValue>
    <masterLabel>Departamentos</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/Tipos_de_envio.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Contratação do Frete por conta do Remetente (CIF)</fullName>
    </customValue>
    <customValue>
        <fullName>Contratação do Frete por conta do Destinatário (FOB)</fullName>
    </customValue>
    <customValue>
        <fullName>Contratação do Frete por conta de Terceiros</fullName>
    </customValue>
    <customValue>
        <fullName>Transporte Próprio por conta do Remetente</fullName>
    </customValue>
    <customValue>
        <fullName>Transporte Próprio por conta do Destinatário</fullName>
    </customValue>
    <customValue>
        <fullName>Sem Ocorrência de Transporte.</fullName>
    </customValue>
    <masterLabel>Tipos de envio</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AtivosDoContratoController.cls
public with sharing class AtivosDoContratoController {
    @AuraEnabled(cacheable=true)
    public static List<Ativos_do_Contrato__c> getAtivosByContratoId(Id contratoId) {
        return [
            SELECT Id, Ativo_Locado__r.Product2.ProductCode, Ativo_Locado__r.Product2.Name, N_de_S_rie__c, URL_da_Imagem__c, Equipamento_no_Cliente__c, Data_de_Entrega__c, Data_de_retorno__c, Ativo_Locado__r.Product2.URL_da_Imagem__c, Data_de_Entrega_formatada__c, Valor_Total_Mensal_Atual__c, Data_de_retorno_formatada__c, Nome_do_ativo__c
            FROM Ativos_do_Contrato__c
            WHERE Contrato_de_Servico__c = :contratoId
            ORDER BY Ativo_Locado__r.Product2.Name
        ];
    }
    
    @AuraEnabled
    public static void updateEquipamentoStatus(List<Id> ativoIds, Boolean status, Date dataEntregaOuRetorno) {
        // Fetch ativos to update
        List<Ativos_do_Contrato__c> ativosToUpdate = [
            SELECT Id, Equipamento_no_Cliente__c, Data_de_entrega__c, Data_de_retorno__c, Ativo_Locado__r.Product2Id, Contrato_de_Servico__c, N_de_S_rie__c, Nome_do_ativo__c
            FROM Ativos_do_Contrato__c
            WHERE Id IN :ativoIds
        ];
        
        // Fetch related Contrato_de_Servico__c record
        Contrato_de_Servi_o__c contratoRel = [SELECT ID, Locat_rio_a__c, Locat_rio_a__r.BillingCity, Locat_rio_a__r.BillingCountry, Locat_rio_a__r.BillingPostalCode, Locat_rio_a__r.BillingState, Locat_rio_a__r.BillingStreet, Locat_rio_a__r.ShippingCity, Locat_rio_a__r.ShippingCountry, Locat_rio_a__r.ShippingPostalCode, Locat_rio_a__r.ShippingState, Locat_rio_a__r.ShippingStreet, Unidade_Hospitalar__c, Vendedor_do_Contrato__c FROM Contrato_de_Servi_o__c WHERE ID = :ativosToUpdate[0].Contrato_de_Servico__c];
        
        // Create the Order object
        Order pedidoRetorno = new Order(
            AccountId = contratoRel.Locat_rio_a__c,
            Contrato_de_Servi_o__c = contratoRel.ID,
            EffectiveDate = system.today(),
            Status = 'Rascunho',
            BillingCity = contratoRel.Locat_rio_a__r.BillingCity,
            BillingCountry = contratoRel.Locat_rio_a__r.BillingCountry,
            BillingPostalCode = contratoRel.Locat_rio_a__r.BillingPostalCode,
            BillingState = contratoRel.Locat_rio_a__r.BillingState,
            BillingStreet = contratoRel.Locat_rio_a__r.BillingStreet,
            Condicao_de_pagamento__c = 'Sem Mov. Financeiro',
            Departamento3__c = 'Locação',
            Entrega_parcial__c = 'Não Autorizada',
            Forma_de_pagamento2__c = 'Sem Mov. Financeiro',
            Frete__c = 'Transporte Próprio por conta do Destinatário',
            Ignora_validacao__c = true,
            Locado_em__c = '-',
            Natureza_de_Opera_o__c = 'REMESSA DE LOCAÇÃO',
            Necess_rio_Treinamento__c = 'NÃO',
            Pricebook2Id = '01s5A000004fbcR', // Use the correct Pricebook2Id
            ShippingCity = contratoRel.Locat_rio_a__r.ShippingCity,
            ShippingCountry = contratoRel.Locat_rio_a__r.ShippingCountry,
            ShippingPostalCode = contratoRel.Locat_rio_a__r.ShippingPostalCode,
            ShippingState = contratoRel.Locat_rio_a__r.ShippingState,
            ShippingStreet = contratoRel.Locat_rio_a__r.ShippingStreet,
            Unidade_Hospitalar__c = contratoRel.Unidade_Hospitalar__c,
            Vendedor__c = contratoRel.Vendedor_do_Contrato__c,
            Prioridade__c = 'NORMAL',
            Entrega_liberada_pelo_financeiro__c = 'SIM'
        );
        
        insert pedidoRetorno; // Insert the order before creating order items
        
        // Collect Product2Ids from ativosToUpdate
        Set<Id> productIds = new Set<Id>();
        for (Ativos_do_Contrato__c ativo : ativosToUpdate) {
            productIds.add(ativo.Ativo_Locado__r.Product2Id);
        }
        
        // Fetch PricebookEntries
        Map<Id, PricebookEntry> pricebookEntriesMap = new Map<Id, PricebookEntry>([
            SELECT Id, Product2Id, UnitPrice
            FROM PricebookEntry
            WHERE Pricebook2Id = '01s5A000004fbcR' AND Product2Id IN :productIds
        ]);
        
        // List to store OrderItems
        List<OrderItem> orderItems = new List<OrderItem>();
        
        // Iterate over the ativos to update and create order items
        for (Ativos_do_Contrato__c ativo : ativosToUpdate) {
            ativo.Equipamento_no_Cliente__c = status;
            if (status) {
                DateTime dataEntregaFormt = DateTime.newInstance(dataEntregaOuRetorno.year(), dataEntregaOuRetorno.month(), dataEntregaOuRetorno.day(), 12, 0, 0);
                ativo.Data_de_entrega__c = dataEntregaFormt;
            } else {
                ativo.Data_de_retorno__c = dataEntregaOuRetorno;
                
                // Create OrderItem
                PricebookEntry pbe = pricebookEntriesMap.get(ativo.Ativo_Locado__r.Product2Id);
                if (pbe != null) {
                    OrderItem itemPedido = new OrderItem(
                        OrderId = pedidoRetorno.Id,
                        PricebookEntryId = pbe.Id,
                        Quantity = 1, 
                        UnitPrice = pbe.UnitPrice,
                        Description = ativo.N_de_S_rie__c
                    );
                    orderItems.add(itemPedido);
                }
            }
        }
        update ativosToUpdate;
        if (!orderItems.isEmpty()) {
            insert orderItems;
        }
    }
    
    
    @AuraEnabled
    public static void substituirAtivo(Id ativoId, String novoNumeroDeSerie, Date dataSubstituicao) {
        Ativos_do_Contrato__c ativoSubstituido = [
            SELECT Id, N_de_S_rie__c, Contrato_de_Servico__c, Quantidade__c, Valor_Unitario_Mensal__c, Valor_Total_Mensal_Atual__c
            FROM Ativos_do_Contrato__c
            WHERE Id = :ativoId
            LIMIT 1
        ];
        ativoSubstituido.Equipamento_no_Cliente__c = false;
        ativoSubstituido.Data_de_Retorno__c = dataSubstituicao;
        ativoSubstituido.Substituido_por__c = novoNumeroDeSerie;
        update ativoSubstituido;
        
        DateTime dataSubstituicaoDatetime = DateTime.newInstance(dataSubstituicao.year(), dataSubstituicao.month(), dataSubstituicao.day(), 12, 0, 0);
        
        Asset novoAtivo = [
            SELECT Id
            FROM Asset
            WHERE SerialNumber = :novoNumeroDeSerie
            LIMIT 1
        ];
        
        Ativos_do_Contrato__c novoAtivoLocado = new Ativos_do_Contrato__c(Ativo_Locado__c = novoAtivo.Id, 
                                                                          Contrato_de_Servico__c = ativoSubstituido.Contrato_de_Servico__c, 
                                                                          Quantidade__c = ativoSubstituido.Quantidade__c, 
                                                                          Valor_Unitario_Mensal__c = ativoSubstituido.Valor_Unitario_Mensal__c, 
                                                                          Valor_Total_Mensal_Atual__c = ativoSubstituido.Valor_Total_Mensal_Atual__c,
                                                                          Data_de_Entrega__c = dataSubstituicaoDatetime
                                                                         );
        try{
            insert novoAtivoLocado;
        }
        catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }
}