force-app/main/default/objects/Asset/fields/ID_Tag__c.field-meta.xml
<CustomField>
    <fullName>ID_Tag__c</fullName>
    <description>Campo destinado a identificação do equipamento dentro da unidade de saúde.</description>
    <label>ID/Tag</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>-</fullName>
            </value>
            <value>
                <fullName>3M</fullName>
            </value>
            <value>
                <fullName>ABX</fullName>
            </value>
            <value>
                <fullName>AGFA</fullName>
            </value>
            <value>
                <fullName>AINCA</fullName>
            </value>
            <value>
                <fullName>AIR LIQUIDE</fullName>
            </value>
            <value>
                <fullName>AIRSEP</fullName>
            </value>
            <value>
                <fullName>AIR SHIELD</fullName>
            </value>
            <value>
                <fullName>AKTILITE</fullName>
            </value>
            <value>
                <fullName>ALERON</fullName>
            </value>
            <value>
                <fullName>ALOHA MED</fullName>
            </value>
            <value>
                <fullName>ALPHA MED</fullName>
            </value>
            <value>
                <fullName>AMCOR</fullName>
            </value>
            <value>
                <fullName>ANGIOTECH</fullName>
            </value>
            <value>
                <fullName>AOC</fullName>
            </value>
            <value>
                <fullName>APRAMED</fullName>
            </value>
            <value>
                <fullName>ARJO</fullName>
            </value>
            <value>
                <fullName>ARTHREX</fullName>
            </value>
            <value>
                <fullName>ASCLEPIOS</fullName>
            </value>
            <value>
                <fullName>ASPIRAMAX</fullName>
            </value>
            <value>
                <fullName>AUTOM</fullName>
            </value>
            <value>
                <fullName>BALMAK</fullName>
            </value>
            <value>
                <fullName>BARBI</fullName>
            </value>
            <value>
                <fullName>BAUMER</fullName>
            </value>
            <value>
                <fullName>BAXTER</fullName>
            </value>
            <value>
                <fullName>BBRAUN</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>BEACON</fullName>
            </value>
            <value>
                <fullName>BELTEC</fullName>
            </value>
            <value>
                <fullName>BENFER</fullName>
            </value>
            <value>
                <fullName>FANEM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/patrimonio__c.field-meta.xml
<CustomField>
    <fullName>patrimonio__c</fullName>
    <label>Patrimônio</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Tipo_de_Aquisi_o__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Aquisi_o__c</fullName>
    <label>Aquisição</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>COMODATO</fullName>
            </value>
            <value>
                <fullName>EMPRÉSTIMO</fullName>
            </value>
            <value>
                <fullName>LOCAÇÃO</fullName>
            </value>
            <value>
                <fullName>PROPRIA</fullName>
                <default>true</default>
                <label>PROPRIA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EvitaDuplicarAtivoTeste.cls
@isTest(SeeAllData=true)
public class EvitaDuplicarAtivoTeste {
    
    static testMethod void teste_1(){ 
        
        Asset ativo = new Asset(
            ACCOUNTID = Id.valueOf('0013100001roa96AAA') ,
            NAME = 'MACRO CENTRÍFUGA' ,
            SERIALNUMBER = 'SN0001' ,
            ID_Tag__c = 'ID0001',
            patrimonio__c = 'PT0001',
            STATUS = 'OPERACIONAL' ,
            RECORDTYPEID = Id.valueOf('01231000000tbAWAAY') ,
            MARCA__C = 'FANEM' ,
            TIPO_DE_AQUISI_O__C = 'PRÓPRIA' ,
            MODELO__C = '206 BL'
        );
        
        test.startTest();
        
        insert ativo;
        
        ativo.SERIALNUMBER = 'SN0002';
        update ativo;
         
        ativo.ID_Tag__c = 'ID0002';
        update ativo;
        
        ativo.patrimonio__c = 'PT0002';
        update ativo;
         
        test.stopTest();
    }
    
    
}