force-app/main/default/objects/Asset/fields/Imagem_do_Ativo__c.field-meta.xml
<CustomField>
    <fullName>Imagem_do_Ativo__c</fullName>
    <formula>Product2.Imagem_do_Produto__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Imagem do Ativo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>-</fullName>
            </value>
            <value>
                <fullName>3M</fullName>
            </value>
            <value>
                <fullName>ABX</fullName>
            </value>
            <value>
                <fullName>AGFA</fullName>
            </value>
            <value>
                <fullName>AINCA</fullName>
            </value>
            <value>
                <fullName>AIR LIQUIDE</fullName>
            </value>
            <value>
                <fullName>AIRSEP</fullName>
            </value>
            <value>
                <fullName>AIR SHIELD</fullName>
            </value>
            <value>
                <fullName>AKTILITE</fullName>
            </value>
            <value>
                <fullName>ALERON</fullName>
            </value>
            <value>
                <fullName>ALOHA MED</fullName>
            </value>
            <value>
                <fullName>ALPHA MED</fullName>
            </value>
            <value>
                <fullName>AMCOR</fullName>
            </value>
            <value>
                <fullName>ANGIOTECH</fullName>
            </value>
            <value>
                <fullName>AOC</fullName>
            </value>
            <value>
                <fullName>APRAMED</fullName>
            </value>
            <value>
                <fullName>ARJO</fullName>
            </value>
            <value>
                <fullName>ARTHREX</fullName>
            </value>
            <value>
                <fullName>ASCLEPIOS</fullName>
            </value>
            <value>
                <fullName>ASPIRAMAX</fullName>
            </value>
            <value>
                <fullName>AUTOM</fullName>
            </value>
            <value>
                <fullName>BALMAK</fullName>
            </value>
            <value>
                <fullName>BARBI</fullName>
            </value>
            <value>
                <fullName>BAUMER</fullName>
            </value>
            <value>
                <fullName>BAXTER</fullName>
            </value>
            <value>
                <fullName>BBRAUN</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>BEACON</fullName>
            </value>
            <value>
                <fullName>BELTEC</fullName>
            </value>
            <value>
                <fullName>BENFER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ativos_do_Contrato__c/Ativos_do_Contrato__c.object-meta.xml
<CustomObject>
    <label>Ativo do Contrato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>N° de Registro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ativos do Contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ativos_do_Contrato__c/fields/Aditivo_Contratual_Relacionado__c.field-meta.xml
<CustomField>
    <fullName>Aditivo_Contratual_Relacionado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Aditivo Contratual Relacionado</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Aditivos_Contratuais__c.Contrato_de_Servi_o_Relacionado__c</field>
            <operation>equals</operation>
            <valueField>$Source.Contrato_de_Servico__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Aditivos_Contratuais__c</referenceTo>
    <relationshipLabel>Ativos do Contrato</relationshipLabel>
    <relationshipName>Ativos_do_Contrato</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ativos_do_Contrato__c/fields/Ativo_Locado__c.field-meta.xml
<CustomField>
    <fullName>Ativo_Locado__c</fullName>
    <label>Ativo Locado</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Ativos do Contrato</relationshipLabel>
    <relationshipName>Ativos_do_Contrato</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ativos_do_Contrato__c/fields/Contrato_de_Servico__c.field-meta.xml
<CustomField>
    <fullName>Contrato_de_Servico__c</fullName>
    <label>Contrato de Serviço</label>
    <referenceTo>Contrato_de_Servi_o__c</referenceTo>
    <relationshipLabel>Ativos do Contrato</relationshipLabel>
    <relationshipName>Ativos_do_Contrato</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ativos_do_Contrato__c/fields/Equipamento_no_Cliente__c.field-meta.xml
<CustomField>
    <fullName>Equipamento_no_Cliente__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Equipamento no Cliente</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Ativos_do_Contrato__c/fields/Imagem_do_Ativo__c.field-meta.xml
<CustomField>
    <fullName>Imagem_do_Ativo__c</fullName>
    <formula>Ativo_Locado__r.Imagem_do_Ativo__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Imagem do Ativo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ativos_do_Contrato__c/fields/Item_do_Contrato__c.field-meta.xml
<CustomField>
    <fullName>Item_do_Contrato__c</fullName>
    <label>Item do Contrato</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ativos_do_Contrato__c/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <formula>TEXT(Ativo_Locado__r.Marca__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Marca</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ativos_do_Contrato__c/fields/Modelo__c.field-meta.xml
<CustomField>
    <fullName>Modelo__c</fullName>
    <formula>Ativo_Locado__r.Modelo__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Modelo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ativos_do_Contrato__c/fields/N_de_S_rie__c.field-meta.xml
<CustomField>
    <fullName>N_de_S_rie__c</fullName>
    <formula>Ativo_Locado__r.SerialNumber</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>N° de Série</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ativos_do_Contrato__c/fields/Observa_o_Descri_o__c.field-meta.xml
<CustomField>
    <fullName>Observa_o_Descri_o__c</fullName>
    <label>Descrição do Produto/Serviço</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Ativos_do_Contrato__c/fields/Valor_Total_Mensal__c.field-meta.xml
<CustomField>
    <fullName>Valor_Total_Mensal__c</fullName>
    <formula>Valor_Unitario_Mensal__c *  Quantidade__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valor Total Periódico</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>3GREEN</fullName>
            </value>
            <value>
                <fullName>7LIVES</fullName>
            </value>
            <value>
                <fullName>ABC</fullName>
            </value>
            <value>
                <fullName>ACCUMED</fullName>
            </value>
            <value>
                <fullName>ACROSS</fullName>
            </value>
            <value>
                <fullName>ACTE</fullName>
            </value>
            <value>
                <fullName>AEROGEN</fullName>
            </value>
            <value>
                <fullName>AGATA</fullName>
            </value>
            <value>
                <fullName>AGILE MED</fullName>
            </value>
            <value>
                <fullName>AIR LIQUIDE</fullName>
            </value>
            <value>
                <fullName>AIR SHIELD</fullName>
            </value>
            <value>
                <fullName>AJEL</fullName>
            </value>
            <value>
                <fullName>ALBAN</fullName>
            </value>
            <value>
                <fullName>ALIVE HEART</fullName>
            </value>
            <value>
                <fullName>ALLIAGE</fullName>
            </value>
            <value>
                <fullName>ALPHARAD</fullName>
            </value>
            <value>
                <fullName>ALVFLOR</fullName>
            </value>
            <value>
                <fullName>ALVIMÉDICA</fullName>
            </value>
            <value>
                <fullName>ANALYSER</fullName>
            </value>
            <value>
                <fullName>ANATONIC</fullName>
            </value>
            <value>
                <fullName>ANESTHESIA</fullName>
            </value>
            <value>
                <fullName>AOC</fullName>
            </value>
            <value>
                <fullName>APC</fullName>
            </value>
            <value>
                <fullName>APK</fullName>
            </value>
            <value>
                <fullName>APPLE</fullName>
            </value>
            <value>
                <fullName>ARJO</fullName>
            </value>
            <value>
                <fullName>ARJOHUNTLEIGH</fullName>
            </value>
            <value>
                <fullName>ARKTUS</fullName>
            </value>
            <value>
                <fullName>ARTIS</fullName>
            </value>
            <value>
                <fullName>ARTROCORP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Modelo__c.field-meta.xml
<CustomField>
    <fullName>Modelo__c</fullName>
    <label>Modelo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Quantidade__c.field-meta.xml
<CustomField>
    <fullName>Quantidade__c</fullName>
    <label>Quantidade</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Produto_da_Proposta_do_Contrato__c/Produto_da_Proposta_do_Contrato__c.object-meta.xml
<CustomObject>
    <label>Produto da Proposta do Contrato</label>
    <nameField>
        <displayFormat>Registro {000000}</displayFormat>
        <label>Registro n°</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Produtos da Proposta do Contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Produto_da_Proposta_do_Contrato__c/fields/C_digo_do_Produto__c.field-meta.xml
<CustomField>
    <fullName>C_digo_do_Produto__c</fullName>
    <formula>Produto_Ofertado__r.ProductCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Código do Produto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Produto_da_Proposta_do_Contrato__c/fields/Contrato_de_Servi_o_Relacionado__c.field-meta.xml
<CustomField>
    <fullName>Contrato_de_Servi_o_Relacionado__c</fullName>
    <label>Contrato de Serviço Relacionado</label>
    <referenceTo>Contrato_de_Servi_o__c</referenceTo>
    <relationshipLabel>Produtos da Proposta do Contrato</relationshipLabel>
    <relationshipName>Produtos_da_Proposta_do_Contrato</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Produto_da_Proposta_do_Contrato__c/fields/Descri_o_Observa_o__c.field-meta.xml
<CustomField>
    <fullName>Descri_o_Observa_o__c</fullName>
    <label>Descrição/Observação</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Produto_da_Proposta_do_Contrato__c/fields/Imagem_do_Produto__c.field-meta.xml
<CustomField>
    <fullName>Imagem_do_Produto__c</fullName>
    <formula>Produto_Ofertado__r.Imagem__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Imagem do Produto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Produto_da_Proposta_do_Contrato__c/fields/Item_de_Proposta__c.field-meta.xml
<CustomField>
    <fullName>Item_de_Proposta__c</fullName>
    <label>Item da Proposta</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Produto_da_Proposta_do_Contrato__c/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <formula>TEXT(Produto_Ofertado__r.Marca__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Marca</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Produto_da_Proposta_do_Contrato__c/fields/Modelo__c.field-meta.xml
<CustomField>
    <fullName>Modelo__c</fullName>
    <formula>Produto_Ofertado__r.Modelo__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Modelo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Produto_da_Proposta_do_Contrato__c/fields/Produto_Ofertado__c.field-meta.xml
<CustomField>
    <fullName>Produto_Ofertado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto Ofertado</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Produtos da Proposta do Contrato</relationshipLabel>
    <relationshipName>Produtos_da_Proposta_do_Contrato</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Produto_da_Proposta_do_Contrato__c/fields/Valor_Mensal__c.field-meta.xml
<CustomField>
    <fullName>Valor_Mensal__c</fullName>
    <label>Valor Unitário</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Produto_da_Proposta_do_Contrato__c/fields/Valor_Mensal_da_Proposta__c.field-meta.xml
<CustomField>
    <fullName>Valor_Mensal_da_Proposta__c</fullName>
    <formula>Valor_Mensal__c *  Quantidade__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valor da Proposta</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ContratoListagem.cls
public class ContratoListagem {
    public List<Produto_da_Proposta_do_Contrato__c> produtosproposta {get; set;}
        public List<Ativos_do_Contrato__c> ativoscontratos {get; set;}
    public List<ContentDocumentLink> anexosContrato {get;set;}
    public List<ContentVersion> idDownl {get;set;}
    public List<Gest_o_de_Documentos__c> documentos { get; set; }
    
    
    public ContratoListagem(ApexPages.StandardController controlador){
        
        documentos = GestaoDocumentos.obterDocumentosVigentes();
        
        produtosproposta = [
            SELECT Id,Produto_Ofertado__r.Name,Produto_Ofertado__r.Modelo__c, Produto_Ofertado__r.Marca__c,Produto_Ofertado__r.ProductCode,Produto_Ofertado__r.Imagem_do_Produto__c, Name,Item_de_Proposta__c, C_digo_do_Produto__c, Contrato_de_Servi_o_Relacionado__c, Descri_o_Observa_o__c, Imagem_do_Produto__c, Marca__c, Modelo__c, Produto_Ofertado__c, Quantidade__c, Valor_Mensal__c, Valor_Mensal_da_Proposta__c
            FROM Produto_da_Proposta_do_Contrato__c
            WHERE Contrato_de_Servi_o_Relacionado__c = :((SObject)controlador.getRecord()).Id
            ORDER BY Item_de_Proposta__c ASC
        ];

        
        ativoscontratos = [
            SELECT Id,Ativo_Locado__r.Name, Ativo_Locado__r.Product2Id, Item_do_Contrato__c,Ativo_Locado__r.Imagem_do_Ativo__c, Aditivo_Contratual_Relacionado__c, Ativo_Locado__c, Contrato_de_Servico__c, Observa_o_Descri_o__c, Equipamento_no_Cliente__c, Imagem_do_Ativo__c, Marca__c, Modelo__c, N_de_S_rie__c, Quantidade__c, Valor_Total_Mensal__c, Valor_Unitario_Mensal__c  
            FROM Ativos_do_Contrato__c
            WHERE Contrato_de_Servico__c = :((SObject)controlador.getRecord()).Id
            ORDER BY Item_do_Contrato__c ASC
        ];
        
        anexosContrato = [
            SELECT ContentDocumentId 
            FROM ContentDocumentLink
            WHERE LinkedEntityId = :((SObject)controlador.getRecord()).Id AND ContentDocumentId IN (SELECT ID FROM ContentDocument WHERE Title LIKE '%ANEXAR%')
        ];
        
        Set<ID> s1 = new Set<ID>();
        
        for(ContentDocumentLink CDL : anexosContrato){
            s1.add(CDL.ContentDocumentId);
        }
        
        idDownl = [SELECT ID, ContentUrl FROM ContentVersion WHERE ContentDocumentId IN :s1 ];
             
    }
}