force-app/main/default/objects/Vagas_Dispon_veis__c/Vagas_Dispon_veis__c.object-meta.xml
<CustomObject>
    <label>Vaga Disponível</label>
    <nameField>
        <displayFormat>V{0}</displayFormat>
        <label>Vaga Disponível</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vagas Disponíveis</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vagas_Dispon_veis__c/fields/Cargo_Ofertado__c.field-meta.xml
<CustomField>
    <fullName>Cargo_Ofertado__c</fullName>
    <label>Cargo Ofertado</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vagas_Dispon_veis__c/fields/Empresa__c.field-meta.xml
<CustomField>
    <fullName>Empresa__c</fullName>
    <label>Empresa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABC</fullName>
            </value>
            <value>
                <fullName>GDB</fullName>
            </value>
            <value>
                <fullName>Health</fullName>
            </value>
            <value>
                <fullName>Hospcom</fullName>
            </value>
            <value>
                <fullName>IZU</fullName>
            </value>
            <value>
                <fullName>Gestcom</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vagas_Dispon_veis__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aguardando aprovação</fullName>
                <default>true</default>
                <label>Aguardando aprovação</label>
            </value>
            <value>
                <fullName>Divulgação da Vaga</fullName>
            </value>
            <value>
                <fullName>Triagem de Candidatos</fullName>
            </value>
            <value>
                <fullName>Entrevista com RH</fullName>
            </value>
            <value>
                <fullName>Entrevista com Gestor</fullName>
            </value>
            <value>
                <fullName>Proposta e ASO</fullName>
            </value>
            <value>
                <fullName>Processo Admissional</fullName>
            </value>
            <value>
                <fullName>Assinatura de Documentos</fullName>
            </value>
            <value>
                <fullName>Finalizada</fullName>
            </value>
            <value>
                <fullName>Cancelada</fullName>
            </value>
            <value>
                <fullName>Análise de Entrevistas</fullName>
                <isActive>false</isActive>
                <label>Análise de Entrevistas</label>
            </value>
            <value>
                <fullName>Período de Contratação</fullName>
                <isActive>false</isActive>
                <label>Período de Contratação</label>
            </value>
            <value>
                <fullName>Período de Entrevistas</fullName>
                <isActive>false</isActive>
                <label>Período de Entrevistas</label>
            </value>
            <value>
                <fullName>Seleção para Entrevistas</fullName>
                <isActive>false</isActive>
                <label>Seleção para Entrevistas</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vagas_Dispon_veis__c/fields/V_nculo__c.field-meta.xml
<CustomField>
    <fullName>V_nculo__c</fullName>
    <label>Vínculo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CLT</fullName>
            </value>
            <value>
                <fullName>PJ</fullName>
            </value>
            <value>
                <fullName>Estágio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VagaValidacaoTest.cls
@isTest
public class VagaValidacaoTest {
	@isTest
    public static void teste(){
        Vagas_Dispon_veis__c vaga = new Vagas_Dispon_veis__c();
        vaga.Cargo_Ofertado__c = 'Cargo Teste';
        vaga.Empresa__c = 'HOSPCOM';
        vaga.V_nculo__c = 'CLT';
        insert vaga;
        vaga.Status__c = 'Proposta e ASO';
        update vaga;
        vaga.Status__c = 'Processo Admissional';
        update vaga;
 		vaga.Status__c = 'Assinatura de Documentos';
        update vaga;
        vaga.Status__c = 'Finalizada';
        update vaga;
        
    }
}