force-app/main/default/objects/Autentique__c/Autentique__c.object-meta.xml
<CustomObject>
    <label>Autentique</label>
    <nameField>
        <displayFormat>DOC {00000}</displayFormat>
        <label>Nome de Autentique</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Autentique</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Autentique__c/fields/Fase__c.field-meta.xml
<CustomField>
    <fullName>Fase__c</fullName>
    <label>Fase</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Autentique__c/fields/idDocAutentique__c.field-meta.xml
<CustomField>
    <fullName>idDocAutentique__c</fullName>
    <label>idDocAutentique</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Autentique__c/fields/Nome_do_Documento__c.field-meta.xml
<CustomField>
    <fullName>Nome_do_Documento__c</fullName>
    <label>Nome do Documento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Fase__c.field-meta.xml
<CustomField>
    <fullName>Fase__c</fullName>
    <label>Fase</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Order/fields/idDocAutentique__c.field-meta.xml
<CustomField>
    <fullName>idDocAutentique__c</fullName>
    <label>idDocAutentique</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/DocsAutentique.cls
public class DocsAutentique {
 
@future(callout=true)
    public static void busca(){
        
        List<Autentique__c> Docs = [SELECT idDocAutentique__c FROM Autentique__c];
        
        Set<String> ids = New Set<String>();
        Set<Id> idNovo = New Set<Id>();
        List<String> idAtt = New List<String>();
        List<String> fases = New List<String>();
        
        for(Autentique__c Aut : Docs){
                ids.add(Aut.idDocAutentique__c);
        }
        
        HttpRequest requ = new HttpRequest();
        requ.setMethod('POST');
        requ.setEndpoint('http://apphospcom.kinghost.net:21220/autentique/status/all');
        requ.setHeader('Content-Type','application/x-www-form-urlencoded;charset=UTF-8');
        requ.setBody('&token=hospcomApiDev!#');
        requ.setTimeout(120000);
        
        HttpResponse respons = new HttpResponse();
        respons = new Http().send(requ);
            
        System.Debug('RESPOSTA' + respons.getBody());
        
        List<Object> deserialized = (List<Object>)JSON.deserializeUntyped(respons.getBody());
            for(Object o: deserialized){
                Map<String, Object> obMap = (Map<String, Object>)o;
              
            String st = obMap.toString();
            String idDoc = st.substringAfter(', id=').substringBefore(', juridico=');
            String fase = st.substringAfter(', fase=').substringBefore(', financeiro');
            String doc = st.substringAfter(', docName=').substringBefore(', fase=');
                            
            system.debug(st);
                
                if(ids.contains(idDoc)){
                    idAtt.add(idDoc);
                    fases.add(fase);
                    //system.debug('true');
                    idAtt.sort();
                }
                else{
                   //system.debug('false');
					Autentique__c novo = new Autentique__c();
                    novo.idDocAutentique__c = idDoc;
                    novo.Nome_do_Documento__c = doc;
                    novo.Fase__c = fase;
                    insert novo;
                }
                
            }            
        
				       
        //idAtt.sort();
        
        system.debug('idatt:' + idAtt);
        
                List<Autentique__c> DocsAtt = [SELECT idDocAutentique__c FROM Autentique__c WHERE idDocAutentique__c IN : idAtt ORDER BY Name];
        //system.debug('docsAtt' + DocsAtt);
        
                integer index = 0;

        for(Autentique__c att : DocsAtt){
            att.Fase__c = fases[index];
            index++;
            update att;
        }

                   //system.debug(DocsAtt);

            }
}