force-app/main/default/objects/Avaliacao_de_Desempenho__c/Avaliacao_de_Desempenho__c.object-meta.xml
<CustomObject>
    <label>Avaliação de Desempenho</label>
    <nameField>
        <displayFormat>AD {000}</displayFormat>
        <label>Nº da Avaliação de Desempenho</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Avaliações de Desempenho</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Avaliacao_de_Desempenho__c/fields/CG10__c.field-meta.xml
<CustomField>
    <fullName>CG10__c</fullName>
    <label>CG10</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Avaliacao_de_Desempenho__c/fields/CG11__c.field-meta.xml
<CustomField>
    <fullName>CG11__c</fullName>
    <label>CG11</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Avaliacao_de_Desempenho__c/fields/CG12__c.field-meta.xml
<CustomField>
    <fullName>CG12__c</fullName>
    <label>CG12</label>
    <length>32072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Avaliacao_de_Desempenho__c/fields/CG13__c.field-meta.xml
<CustomField>
    <fullName>CG13__c</fullName>
    <label>CG13</label>
    <length>32020</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Avaliacao_de_Desempenho__c/fields/CG14__c.field-meta.xml
<CustomField>
    <fullName>CG14__c</fullName>
    <label>CG14</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Avaliacao_de_Desempenho__c/fields/CG15__c.field-meta.xml
<CustomField>
    <fullName>CG15__c</fullName>
    <label>CG15</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Avaliacao_de_Desempenho__c/fields/CG16__c.field-meta.xml
<CustomField>
    <fullName>CG16__c</fullName>
    <label>CG16</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Avaliacao_de_Desempenho__c/fields/CG1__c.field-meta.xml
<CustomField>
    <fullName>CG1__c</fullName>
    <label>CG1</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Avaliacao_de_Desempenho__c/fields/CG2__c.field-meta.xml
<CustomField>
    <fullName>CG2__c</fullName>
    <label>CG2</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Avaliacao_de_Desempenho__c/fields/CG3__c.field-meta.xml
<CustomField>
    <fullName>CG3__c</fullName>
    <label>CG3</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Avaliacao_de_Desempenho__c/fields/CG4__c.field-meta.xml
<CustomField>
    <fullName>CG4__c</fullName>
    <label>CG4</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Avaliacao_de_Desempenho__c/fields/CG5__c.field-meta.xml
<CustomField>
    <fullName>CG5__c</fullName>
    <label>CG5</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Avaliacao_de_Desempenho__c/fields/CG6__c.field-meta.xml
<CustomField>
    <fullName>CG6__c</fullName>
    <label>CG6</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Avaliacao_de_Desempenho__c/fields/CG7__c.field-meta.xml
<CustomField>
    <fullName>CG7__c</fullName>
    <label>CG7</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Avaliacao_de_Desempenho__c/fields/CG8__c.field-meta.xml
<CustomField>
    <fullName>CG8__c</fullName>
    <label>CG8</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Avaliacao_de_Desempenho__c/fields/CG9__c.field-meta.xml
<CustomField>
    <fullName>CG9__c</fullName>
    <label>CG9</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Avaliacao_de_Desempenho__c/fields/CGAD3__c.field-meta.xml
<CustomField>
    <fullName>CGAD3__c</fullName>
    <description>Pergunta 3 da seção Atitude de Dono (Colaborador ao Gestor)</description>
    <label>CGAD3</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Avaliacao_de_Desempenho__c/fields/CGHO3__c.field-meta.xml
<CustomField>
    <fullName>CGHO3__c</fullName>
    <description>Pergunta 3 da seção Honestidade (do colaborador ao gestor)</description>
    <label>CGHO3</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Avaliacao_de_Desempenho__c/fields/CGRESPEITO3__c.field-meta.xml
<CustomField>
    <fullName>CGRESPEITO3__c</fullName>
    <description>Pergunta 3 da seção Respeito (Colaborador ao gestor)</description>
    <label>CGRESPEITO3</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Avaliacao_de_Desempenho__c/fields/CGSO3__c.field-meta.xml
<CustomField>
    <fullName>CGSO3__c</fullName>
    <description>Pergunta 3 da seção Sangue no Olho (Colaborador ao Gestor)</description>
    <label>CGSO3</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Avaliacao_de_Desempenho__c/fields/Gestor__c.field-meta.xml
<CustomField>
    <fullName>Gestor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gestor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Avalia_es_de_Desempenho</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Avaliacao_de_Desempenho__c/fields/Nome_do_colaborador__c.field-meta.xml
<CustomField>
    <fullName>Nome_do_colaborador__c</fullName>
    <formula>Contato__r.FirstName + &apos; &apos; +  Contato__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nome do colaborador</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Avaliacao_de_Desempenho__c/fields/Referencia__c.field-meta.xml
<CustomField>
    <fullName>Referencia__c</fullName>
    <formula>IF(DATEVALUE(CreatedDate) &lt;  DATE(2022,05,31), 2021,
IF(DATEVALUE(CreatedDate) &gt;= DATE(2022,06,01) &amp;&amp;  DATEVALUE(CreatedDate) &lt;= DATE(2023,01,31), 2022,
IF(DATEVALUE(CreatedDate) &gt;= DATE(2023,11,01) &amp;&amp; DATEVALUE(CreatedDate) &lt; DATE(2024,02,29), 2023, 
IF(DATEVALUE(CreatedDate) &gt;= DATE(2024,06,01) &amp;&amp; DATEVALUE(CreatedDate) &lt; DATE(2025,02,28), 2024, 
IF(DATEVALUE(CreatedDate) &gt;= DATE(2025,07,01) &amp;&amp; DATEVALUE(CreatedDate) &lt; DATE(2025,07,31), 2025, 
null)))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Referência</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/Gestor__c.field-meta.xml
<CustomField>
    <fullName>Gestor__c</fullName>
    <label>Gestor</label>
    <relationshipName>Gestor</relationshipName>
    <restrictedAdminField>false</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

force-app/main/default/classes/AvaliacaoDesempenho.cls
public class AvaliacaoDesempenho {
    
    public List<AggregateResult> avaliacao {get;set;}
    public List<Avaliacao_de_Desempenho__c> comentarios {get;set;}
    public ID ide {get;set;} 

 public AvaliacaoDesempenho(ApexPages.StandardController controlador){
     
    ide = ApexPages.currentPage().getParameters().get('id');
    Avaliacao_de_Desempenho__c av = [SELECT OwnerId, Referencia__c FROM Avaliacao_de_Desempenho__c WHERE ID =: ide];
    
    avaliacao = [SELECT AVG(CG1__c) media1, AVG(CG2__c) media2, AVG(CG3__c) media3, AVG(CG4__c) media4, AVG(CG5__c) media5, AVG(CG6__c) media6, AVG(CG7__c) media7, AVG(CG8__c) media8, AVG(CG9__c) media9,
                                       AVG(CG10__c) media10, AVG(CG11__c) media11, AVG(CG14__c) media14, AVG(CG15__c) media15, AVG(CG16__c) media16, 
                 					   AVG(CGAD3__c) mediaAD3, AVG(CGHO3__c) mediaHO3, AVG(CGSO3__c) mediaSO3, AVG(CGRESPEITO3__c) mediaRESPEITO3,
                 					   Gestor__c gestor
                                       FROM Avaliacao_de_Desempenho__c
                 					   WHERE Referencia__c =: av.Referencia__c
                                       GROUP BY Gestor__c];
     
    comentarios = [SELECT CG12__c, CG13__c, Nome_do_colaborador__c FROM Avaliacao_de_Desempenho__c WHERE Gestor__r.Id =: av.OwnerId AND Referencia__c =: av.Referencia__c];
     
}
}