force-app/main/default/objects/Item_da_Transfer_ncia_de_Estoque__c/Item_da_Transfer_ncia_de_Estoque__c.object-meta.xml
<CustomObject>
    <label>Item da Transferência de Estoque</label>
    <nameField>
        <displayFormat>ITE={0000}</displayFormat>
        <label>Nome de Item da Transferência de Estoque</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens da Transferência de Estoque</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item_da_Transfer_ncia_de_Estoque__c/fields/Estoque_de_destino__c.field-meta.xml
<CustomField>
    <fullName>Estoque_de_destino__c</fullName>
    <label>Estoque de destino</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Estoques</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Item_da_Transfer_ncia_de_Estoque__c/fields/Estoque_de_origem__c.field-meta.xml
<CustomField>
    <fullName>Estoque_de_origem__c</fullName>
    <label>Estoque de origem</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Estoques</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Item_da_Transfer_ncia_de_Estoque__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Itens da Transferência de Estoque</relationshipLabel>
    <relationshipName>Itens_da_Transfer_ncia_de_Estoque</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Item_da_Transfer_ncia_de_Estoque__c/fields/Solicita_o_de_Transfer_ncia_de_Estoque__c.field-meta.xml
<CustomField>
    <fullName>Solicita_o_de_Transfer_ncia_de_Estoque__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Solicitação de Transferência de Estoque</label>
    <referenceTo>Solicitacao_transferencia_estoque__c</referenceTo>
    <relationshipLabel>Itens da Transferência de Estoque</relationshipLabel>
    <relationshipName>Itens_da_Transfer_ncia_de_Estoque</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/transferenciaEstoque.cls
public class transferenciaEstoque {
    @AuraEnabled
    public static string cria(string solicitacao, string produto, integer quantidade, string estoqueOrigem, string estoqueDestino){
        Item_da_Transfer_ncia_de_Estoque__c ite = new Item_da_Transfer_ncia_de_Estoque__c();
        ite.Solicita_o_de_Transfer_ncia_de_Estoque__c = solicitacao;
        ite.Produto__c = produto;
        ite.Quantidade__c = quantidade;
        ite.Estoque_de_origem__c = estoqueOrigem;
        ite.Estoque_de_destino__c = estoqueDestino;
        
        try{
            insert ite;
            return ite.Id;
            
        }
        catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }
}