force-app/main/default/objects/Product2/fields/Categoria_de_compra__c.field-meta.xml
<CustomField>
    <fullName>Categoria_de_compra__c</fullName>
    <label>Categoria de compra</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Categoria_de_compra</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Linha__c.field-meta.xml
<CustomField>
    <fullName>Linha__c</fullName>
    <label>Linha</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>APOIO A MOBILIDADE</fullName>
                <isActive>false</isActive>
                <label>APOIO A MOBILIDADE</label>
            </value>
            <value>
                <fullName>CAMAS HOSPITALARES</fullName>
            </value>
            <value>
                <fullName>CIRURGIA MINIMAMENTE INVASIVA</fullName>
            </value>
            <value>
                <fullName>CIRURGIA ROBÓTICA</fullName>
            </value>
            <value>
                <fullName>CUIDADOS PESSOAIS</fullName>
                <isActive>false</isActive>
                <label>CUIDADOS PESSOAIS</label>
            </value>
            <value>
                <fullName>ELETROCIRURGIA</fullName>
            </value>
            <value>
                <fullName>ENDOSCOPIA</fullName>
            </value>
            <value>
                <fullName>ESTERILIZACAO</fullName>
                <isActive>false</isActive>
                <label>ESTERILIZACAO</label>
            </value>
            <value>
                <fullName>IMAGEM</fullName>
                <isActive>false</isActive>
                <label>IMAGEM</label>
            </value>
            <value>
                <fullName>IMAGEM RAIO-X</fullName>
            </value>
            <value>
                <fullName>IMAGEM ULTRASSOM</fullName>
            </value>
            <value>
                <fullName>INFUSÃO</fullName>
                <isActive>false</isActive>
                <label>INFUSÃO</label>
            </value>
            <value>
                <fullName>LABORATORIAL</fullName>
            </value>
            <value>
                <fullName>MONITORES DE GRAU MEDICO</fullName>
            </value>
            <value>
                <fullName>NEONATOLOGIA</fullName>
            </value>
            <value>
                <fullName>OPME</fullName>
            </value>
            <value>
                <fullName>OUTROS</fullName>
            </value>
            <value>
                <fullName>PM</fullName>
            </value>
            <value>
                <fullName>PMLS</fullName>
            </value>
            <value>
                <fullName>SURGICAL</fullName>
            </value>
            <value>
                <fullName>VETERINÁRIA</fullName>
                <isActive>false</isActive>
                <label>VETERINÁRIA</label>
            </value>
            <value>
                <fullName>VETERINÁRIA IVD</fullName>
            </value>
            <value>
                <fullName>VETERINÁRIA MIS</fullName>
            </value>
            <value>
                <fullName>VETERINÁRIA PMLS</fullName>
            </value>
            <value>
                <fullName>VIAS AÉREAS DIFÍCEIS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>3GREEN</fullName>
            </value>
            <value>
                <fullName>7LIVES</fullName>
            </value>
            <value>
                <fullName>ABC</fullName>
            </value>
            <value>
                <fullName>ACCUMED</fullName>
            </value>
            <value>
                <fullName>ACROSS</fullName>
            </value>
            <value>
                <fullName>ACTE</fullName>
            </value>
            <value>
                <fullName>AEROGEN</fullName>
            </value>
            <value>
                <fullName>AGATA</fullName>
            </value>
            <value>
                <fullName>AGILE MED</fullName>
            </value>
            <value>
                <fullName>AIR LIQUIDE</fullName>
            </value>
            <value>
                <fullName>AIR SHIELD</fullName>
            </value>
            <value>
                <fullName>AJEL</fullName>
            </value>
            <value>
                <fullName>ALBAN</fullName>
            </value>
            <value>
                <fullName>ALIVE HEART</fullName>
            </value>
            <value>
                <fullName>ALLIAGE</fullName>
            </value>
            <value>
                <fullName>ALPHARAD</fullName>
            </value>
            <value>
                <fullName>ALVFLOR</fullName>
            </value>
            <value>
                <fullName>ALVIMÉDICA</fullName>
            </value>
            <value>
                <fullName>ANALYSER</fullName>
            </value>
            <value>
                <fullName>ANATONIC</fullName>
            </value>
            <value>
                <fullName>ANESTHESIA</fullName>
            </value>
            <value>
                <fullName>AOC</fullName>
            </value>
            <value>
                <fullName>APC</fullName>
            </value>
            <value>
                <fullName>APK</fullName>
            </value>
            <value>
                <fullName>APPLE</fullName>
            </value>
            <value>
                <fullName>ARJO</fullName>
            </value>
            <value>
                <fullName>ARJOHUNTLEIGH</fullName>
            </value>
            <value>
                <fullName>ARKTUS</fullName>
            </value>
            <value>
                <fullName>ARTIS</fullName>
            </value>
            <value>
                <fullName>ARTROCORP</fullName>
            </value>
            <value>
                <fullName>OUTROS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Modelo__c.field-meta.xml
<CustomField>
    <fullName>Modelo__c</fullName>
    <label>Modelo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/NCM_do_Produto__c.field-meta.xml
<CustomField>
    <fullName>NCM_do_Produto__c</fullName>
    <label>NCM do Produto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Tipo_do_Produto__c.field-meta.xml
<CustomField>
    <fullName>Tipo_do_Produto__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CONSUMÍVEL</fullName>
            </value>
            <value>
                <fullName>EQUIPAMENTO</fullName>
            </value>
            <value>
                <fullName>FERRAMENTA</fullName>
            </value>
            <value>
                <fullName>IMPLANTE</fullName>
            </value>
            <value>
                <fullName>INSTRUMENTAL</fullName>
            </value>
            <value>
                <fullName>INSUMO</fullName>
            </value>
            <value>
                <fullName>KIT SERVIÇO</fullName>
            </value>
            <value>
                <fullName>MÓDULO</fullName>
            </value>
            <value>
                <fullName>MOVEIS</fullName>
            </value>
            <value>
                <fullName>OPCIONAL</fullName>
            </value>
            <value>
                <fullName>PEÇA</fullName>
            </value>
            <value>
                <fullName>SERVIÇO</fullName>
            </value>
            <value>
                <fullName>SET CIRURGICO</fullName>
            </value>
            <value>
                <fullName>SOFTWARE</fullName>
            </value>
            <value>
                <fullName>ACESSÓRIO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Unidade_de_medida__c.field-meta.xml
<CustomField>
    <fullName>Unidade_de_medida__c</fullName>
    <label>Unidade de medida</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Valor_de_Venda__c.field-meta.xml
<CustomField>
    <fullName>Valor_de_Venda__c</fullName>
    <label>Valor de Venda</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/globalValueSets/Categoria_de_compra.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>ALIMENTAÇÃO</fullName>
    </customValue>
    <customValue>
        <fullName>ASSINATURAS JORNAIS, LIVROS E REVISTAS</fullName>
    </customValue>
    <customValue>
        <fullName>BRINDES</fullName>
    </customValue>
    <customValue>
        <fullName>CONFRATERNIZAÇÃO E EVENTOS</fullName>
    </customValue>
    <customValue>
        <fullName>CONSTRUÇÃO CIVIL</fullName>
    </customValue>
    <customValue>
        <fullName>CONSULTORIA E ASSESSORIAS</fullName>
    </customValue>
    <customValue>
        <fullName>CORREIOS E TELEGRÁFOS</fullName>
    </customValue>
    <customValue>
        <fullName>CURSOS E TREINAMENTOS</fullName>
    </customValue>
    <customValue>
        <fullName>DEDETIZAÇÃO, DESRATIZAÇÃO E DESCUPINIZAÇÃO</fullName>
    </customValue>
    <customValue>
        <fullName>EMBALAGEM</fullName>
    </customValue>
    <customValue>
        <fullName>EPIS</fullName>
    </customValue>
    <customValue>
        <fullName>FERRAMENTAS MANUAL</fullName>
    </customValue>
    <customValue>
        <fullName>FRETES E CARRETOS</fullName>
    </customValue>
    <customValue>
        <fullName>GRÁFICA</fullName>
    </customValue>
    <customValue>
        <fullName>HOSPEDAGEM</fullName>
    </customValue>
    <customValue>
        <fullName>IMPRESSÃO E CÓPIAS</fullName>
    </customValue>
    <customValue>
        <fullName>LAZER E ESPORTES</fullName>
    </customValue>
    <customValue>
        <fullName>LIMPEZA E CONSERVAÇÃO</fullName>
    </customValue>
    <customValue>
        <fullName>LOCAÇÃO DE IMOVEIS</fullName>
    </customValue>
    <customValue>
        <fullName>LOCAÇÃO DE MÁQUINAS E EQUIPAMENTOS</fullName>
    </customValue>
    <customValue>
        <fullName>LOCAÇÃO DE VEÍCULOS</fullName>
    </customValue>
    <customValue>
        <fullName>MANUTENÇÃO E MÁQUINAS E EQUIPAMENTOS</fullName>
    </customValue>
    <customValue>
        <fullName>MANUTENÇÃO PREDIAL</fullName>
    </customValue>
    <customValue>
        <fullName>MARKETING</fullName>
    </customValue>
    <customValue>
        <fullName>MATERIAL DE COPA</fullName>
    </customValue>
    <customValue>
        <fullName>MATERIAL DE INFORMÁTICA</fullName>
    </customValue>
    <customValue>
        <fullName>MATERIAL ELÉTRICO</fullName>
    </customValue>
    <customValue>
        <fullName>MATERIAL ELETRÔNICO</fullName>
    </customValue>
    <customValue>
        <fullName>MATERIAL ESCRITÓRIO</fullName>
    </customValue>
    <customValue>
        <fullName>MATERIAL LIMPEZA</fullName>
    </customValue>
    <masterLabel>Categoria de compra</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/produtosInsercao.cls
public class produtosInsercao {
    @AuraEnabled
    public static void inserirProdutos(String jsonString) {
        // Parseando a string JSON para uma lista de objetos
        List<Object> produtosList = (List<Object>) JSON.deserializeUntyped(jsonString);
        
        // Definindo o tamanho do lote para controlar quantos registros serão inseridos de cada vez
        Integer loteTamanho = 1; // Inserir um por vez
        
        // Processando os produtos em lotes
        for (Integer i = 0; i < produtosList.size(); i += loteTamanho) {
            List<Product2> produtosLote = new List<Product2>();
            
            for (Integer j = i; j < Math.min(produtosList.size(), i + loteTamanho); j++) {
                Map<String, Object> produtoMap = (Map<String, Object>) produtosList[j];
                try {
                    // Criando um novo registro de Product2
                    Product2 novoProduto = new Product2();
                    
                    // Mapeando os campos do JSON para os campos do objeto Product2
                    novoProduto.ProductCode = (String) produtoMap.get('Código do Fabricante');
                    novoProduto.Name = (String) produtoMap.get('Nome');
                    novoProduto.Marca__c = (String) produtoMap.get('Marca');
                    novoProduto.Modelo__c = (String) produtoMap.get('Modelo');
                    novoProduto.Linha__c = (String) produtoMap.get('Linha');
                    novoProduto.Family = (String) produtoMap.get('Família');
                    novoProduto.Tipo_do_Produto__c = (String) produtoMap.get('Tipo');
                    novoProduto.Valor_de_Venda__c = Decimal.valueOf((String) produtoMap.get('Valor de venda'));
                    novoProduto.Description = (String) produtoMap.get('Descrição');
                    novoProduto.NCM_do_Produto__c = (String) produtoMap.get('NCM');
                    novoProduto.IsActive = true;
                    
                    // Adicionando o produto à lista do lote
                    produtosLote.add(novoProduto);
                    
                } catch (Exception e) {
                    System.debug('Erro ao processar o produto: ' + e.getMessage());
                }
            }
            
            try {
                insert produtosLote;
            } catch (Exception e) {
                throw new AuraHandledException('Erro ao inserir lote de produtos: ' + e.getMessage());
            }
        }
    }
    @AuraEnabled
    public static void inserirProdutosConsumo(String jsonString) {
        // Parseando a string JSON para uma lista de objetos
        List<Object> produtosList = (List<Object>) JSON.deserializeUntyped(jsonString);
        
        // Definindo o tamanho do lote para controlar quantos registros serão inseridos de cada vez
        Integer loteTamanho = 1; // Inserir um por vez
        
        // Processando os produtos em lotes
        for (Integer i = 0; i < produtosList.size(); i += loteTamanho) {
            List<Product2> produtosLote = new List<Product2>();
            
            for (Integer j = i; j < Math.min(produtosList.size(), i + loteTamanho); j++) {
                Map<String, Object> produtoMap = (Map<String, Object>) produtosList[j];
                try {
                    // Criando um novo registro de Product2
                    Product2 novoProduto = new Product2();
                    
                    string random = produtosInsercao.gerarCodigo();
                    system.debug(random);
                    
                    // Mapeando os campos do JSON para os campos do objeto Product2
                    novoProduto.ProductCode = random;
                    novoProduto.Name = (String) produtoMap.get('Nome');
                    novoProduto.Modelo__c = (String) produtoMap.get('Modelo');
                    novoProduto.Categoria_de_compra__c = (String) produtoMap.get('Categoria de Compra');
                    novoProduto.Description = (String) produtoMap.get('Descrição');
                    novoProduto.Unidade_de_medida__c = (String) produtoMap.get('Unidade de Medida');
                    novoProduto.NCM_do_Produto__c = (String) produtoMap.get('NCM');                    
                    novoProduto.Valor_de_Venda__c = 0;                    
                    novoProduto.Linha__c = 'OUTROS';                    
                    novoProduto.Family = 'OUTROS';                    
                    novoProduto.IsActive = true;
                    
                    // Adicionando o produto à lista do lote
                    produtosLote.add(novoProduto);
                    
                } catch (Exception e) {
                    System.debug('Erro ao processar o produto: ' + e.getMessage());
                }
            }
            
            try {
                insert produtosLote;
            } catch (Exception e) {
                throw new AuraHandledException('Erro ao inserir lote de produtos: ' + e.getMessage());
            }
        }
    }
    public static String gerarCodigo() {
        // Prefixo fixo
        String prefixo = 'CON-';
        
        // Comprimento da parte aleatória da string (excluindo o prefixo)
        Integer comprimentoAleatorio = 10; // Ajuste conforme necessário
        
        // Gerar a parte aleatória
        String parteAleatoria = gerarParteAleatoria(comprimentoAleatorio);
        
        // Concatenar o prefixo com a parte aleatória
        return prefixo + parteAleatoria;
    }
    
    private static String gerarParteAleatoria(Integer comprimento) {
        // Caracteres possíveis para a parte aleatória
        String caracteres = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
        String resultado = '';
        
        // Gerar caracteres aleatórios
        for (Integer i = 0; i < comprimento; i++) {
            Integer index = (Integer) (Math.random() * caracteres.length());
            resultado += caracteres.substring(index, index + 1);
        }
        
        return resultado;
    }
}