force-app/main/default/objects/Product2/fields/Integrado__c.field-meta.xml
<CustomField>
    <fullName>Integrado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Integrado</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Tipo_do_Produto__c.field-meta.xml
<CustomField>
    <fullName>Tipo_do_Produto__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CONSUMÍVEL</fullName>
            </value>
            <value>
                <fullName>EQUIPAMENTO</fullName>
            </value>
            <value>
                <fullName>FERRAMENTA</fullName>
            </value>
            <value>
                <fullName>IMPLANTE</fullName>
            </value>
            <value>
                <fullName>INSTRUMENTAL</fullName>
            </value>
            <value>
                <fullName>INSUMO</fullName>
            </value>
            <value>
                <fullName>KIT SERVIÇO</fullName>
            </value>
            <value>
                <fullName>MÓDULO</fullName>
            </value>
            <value>
                <fullName>MOVEIS</fullName>
            </value>
            <value>
                <fullName>OPCIONAL</fullName>
            </value>
            <value>
                <fullName>PEÇA</fullName>
            </value>
            <value>
                <fullName>SERVIÇO</fullName>
            </value>
            <value>
                <fullName>SET CIRURGICO</fullName>
            </value>
            <value>
                <fullName>SOFTWARE</fullName>
            </value>
            <value>
                <fullName>ACESSÓRIO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Valor_de_Venda__c.field-meta.xml
<CustomField>
    <fullName>Valor_de_Venda__c</fullName>
    <label>Valor de Venda</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/SAPProductIntegrationTEST.cls
//Para rodar este teste desativar a trigger ProdutoPreenchimento e UpdateStandardPrices.
@isTest(seeAllData=true)
public class SAPProductIntegrationTEST {
	@isTest
    private static void SAPProductIntegration_TEST(){
        Test.startTest();

        Product2 updatedProduct = [SELECT Id, Observacoes__c, Integrado__c FROM Product2 WHERE Id = '01t5A000008DBk0QAG'];//01t5A000008DBk0QAG
        updatedProduct.Observacoes__c = updatedProduct.Observacoes__c + '.';
        update updatedProduct;

        //Product2 p = new Product2(Name='Test Product', Valor_de_Venda__c = 20000, Tipo_do_Produto__c='Peça', isActive=true);
        //insert p;
		//p.Name = 'Test';
		//update p;

        Test.stopTest();
    }    
     
}