force-app/main/default/objects/Product2/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>3GREEN</fullName>
            </value>
            <value>
                <fullName>7LIVES</fullName>
            </value>
            <value>
                <fullName>ABC</fullName>
            </value>
            <value>
                <fullName>ACCUMED</fullName>
            </value>
            <value>
                <fullName>ACROSS</fullName>
            </value>
            <value>
                <fullName>ACTE</fullName>
            </value>
            <value>
                <fullName>AEROGEN</fullName>
            </value>
            <value>
                <fullName>AGATA</fullName>
            </value>
            <value>
                <fullName>AGILE MED</fullName>
            </value>
            <value>
                <fullName>AIR LIQUIDE</fullName>
            </value>
            <value>
                <fullName>AIR SHIELD</fullName>
            </value>
            <value>
                <fullName>AJEL</fullName>
            </value>
            <value>
                <fullName>ALBAN</fullName>
            </value>
            <value>
                <fullName>ALIVE HEART</fullName>
            </value>
            <value>
                <fullName>ALLIAGE</fullName>
            </value>
            <value>
                <fullName>ALPHARAD</fullName>
            </value>
            <value>
                <fullName>ALVFLOR</fullName>
            </value>
            <value>
                <fullName>ALVIMÉDICA</fullName>
            </value>
            <value>
                <fullName>ANALYSER</fullName>
            </value>
            <value>
                <fullName>ANATONIC</fullName>
            </value>
            <value>
                <fullName>ANESTHESIA</fullName>
            </value>
            <value>
                <fullName>AOC</fullName>
            </value>
            <value>
                <fullName>APC</fullName>
            </value>
            <value>
                <fullName>APK</fullName>
            </value>
            <value>
                <fullName>APPLE</fullName>
            </value>
            <value>
                <fullName>ARJO</fullName>
            </value>
            <value>
                <fullName>ARJOHUNTLEIGH</fullName>
            </value>
            <value>
                <fullName>ARKTUS</fullName>
            </value>
            <value>
                <fullName>ARTIS</fullName>
            </value>
            <value>
                <fullName>ARTROCORP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Modelo__c.field-meta.xml
<CustomField>
    <fullName>Modelo__c</fullName>
    <label>Modelo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Tipo_do_Produto__c.field-meta.xml
<CustomField>
    <fullName>Tipo_do_Produto__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CONSUMÍVEL</fullName>
            </value>
            <value>
                <fullName>EQUIPAMENTO</fullName>
            </value>
            <value>
                <fullName>FERRAMENTA</fullName>
            </value>
            <value>
                <fullName>IMPLANTE</fullName>
            </value>
            <value>
                <fullName>INSTRUMENTAL</fullName>
            </value>
            <value>
                <fullName>INSUMO</fullName>
            </value>
            <value>
                <fullName>KIT SERVIÇO</fullName>
            </value>
            <value>
                <fullName>MÓDULO</fullName>
            </value>
            <value>
                <fullName>MOVEIS</fullName>
            </value>
            <value>
                <fullName>OPCIONAL</fullName>
            </value>
            <value>
                <fullName>PEÇA</fullName>
            </value>
            <value>
                <fullName>SERVIÇO</fullName>
            </value>
            <value>
                <fullName>SET CIRURGICO</fullName>
            </value>
            <value>
                <fullName>SOFTWARE</fullName>
            </value>
            <value>
                <fullName>ACESSÓRIO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProdutoCriacao.cls
public class ProdutoCriacao {
	
    @AuraEnabled
    public static String Inicializacao(){
		ValoresInicializacao valores = new ValoresInicializacao();
		
		valores.marcas.add(new Map<String, String>{'value' => '', 'label' => '-- Nenhuma --'});
        for(Schema.PicklistEntry campo : Product2.Marca__c.getDescribe().getPicklistValues())
            valores.marcas.add(new Map<String, String>{'value' => campo.getLabel(), 'label' => campo.getLabel()});
		
		valores.familias.add(new Map<String, String>{'value' => '', 'label' => '-- Nenhuma --'});
        for(Schema.PicklistEntry campo : Product2.Family.getDescribe().getPicklistValues())
            valores.familias.add(new Map<String, String>{'value' => campo.getLabel(), 'label' => campo.getLabel()});
		
		valores.tipos.add(new Map<String, String>{'value' => '', 'label' => '-- Nenhum --'});
        for(Schema.PicklistEntry campo : Product2.Tipo_do_Produto__c.getDescribe().getPicklistValues())
            valores.tipos.add(new Map<String, String>{'value' => campo.getLabel(), 'label' => campo.getLabel()});
		
		return JSON.serialize(valores);
	}
	public class ValoresInicializacao{
		String mostrar;
		List<Map<String, String>> marcas;
		List<Map<String, String>> familias;
		List<Map<String, String>> tipos;
		
		public ValoresInicializacao(){
			marcas = new List<Map<String, String>>();
			familias = new List<Map<String, String>>();
			tipos = new List<Map<String, String>>();
		}
	}
	
    @AuraEnabled
    public static String Criar(
		String codigo, String nome,  String marca, String modelo, 
		String familia, String tipo, String descricao, Integer valor
	){
		RetornoCriar retorno = new RetornoCriar();
		Savepoint checkpoint = Database.setSavepoint();
		
		Product2 produto;
		List<PricebookEntry> valores = new List<PricebookEntry>();
		try {
			
			// produto
			produto = new Product2(
				ProductCode = codigo,
				Name = nome,
				Marca__c = marca,
				Modelo__c = modelo,
				Family = familia,
				Tipo_do_Produto__c = tipo,
				Description	= descricao,
				IsActive = true
			);
			insert produto;
			
			// entrada padrão
			valores.clear();
			for(Pricebook2 catalogo : [SELECT Id FROM Pricebook2 WHERE IsStandard = true])
				valores.add(new PricebookEntry(
					Product2Id = produto.Id,
					Pricebook2Id = catalogo.Id,
					CurrencyIsoCode = 'BRL',
					UnitPrice = valor,
					UseStandardPrice = false,
					IsActive = true
				));
			if(valores.size()>0)
				insert valores;
			
			// outras entradas
			valores.clear();
			for(Pricebook2 catalogo : [SELECT Id FROM Pricebook2 WHERE IsActive = true AND IsStandard = false])
				valores.add(new PricebookEntry(
					Product2Id = produto.Id,
					Pricebook2Id = catalogo.Id,
					CurrencyIsoCode = 'BRL',
					UnitPrice = valor,
					UseStandardPrice = true,
					IsActive = true
				));
			if(valores.size()>0)
				insert valores;
			
		}
		catch (System.DMLException e){
			for(Integer i=0; i<e.getNumDml(); i++)
				retorno.mensagem += e.getDmlMessage(i);
			Database.rollback(checkpoint);
			return JSON.serialize(retorno);
		}
		retorno.produto = produto;
		
		return JSON.serialize(retorno);
	}
	public class RetornoCriar{
		String mensagem;
		String url_base;
		Product2 produto;
		
		public RetornoCriar(){
			mensagem = '';
			url_base = Site.getBaseUrl();			
		}
	}

}