force-app/main/default/objects/Product2/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>3GREEN</fullName>
            </value>
            <value>
                <fullName>7LIVES</fullName>
            </value>
            <value>
                <fullName>ABC</fullName>
            </value>
            <value>
                <fullName>ACCUMED</fullName>
            </value>
            <value>
                <fullName>ACROSS</fullName>
            </value>
            <value>
                <fullName>ACTE</fullName>
            </value>
            <value>
                <fullName>AEROGEN</fullName>
            </value>
            <value>
                <fullName>AGATA</fullName>
            </value>
            <value>
                <fullName>AGILE MED</fullName>
            </value>
            <value>
                <fullName>AIR LIQUIDE</fullName>
            </value>
            <value>
                <fullName>AIR SHIELD</fullName>
            </value>
            <value>
                <fullName>AJEL</fullName>
            </value>
            <value>
                <fullName>ALBAN</fullName>
            </value>
            <value>
                <fullName>ALIVE HEART</fullName>
            </value>
            <value>
                <fullName>ALLIAGE</fullName>
            </value>
            <value>
                <fullName>ALPHARAD</fullName>
            </value>
            <value>
                <fullName>ALVFLOR</fullName>
            </value>
            <value>
                <fullName>ALVIMÉDICA</fullName>
            </value>
            <value>
                <fullName>ANALYSER</fullName>
            </value>
            <value>
                <fullName>ANATONIC</fullName>
            </value>
            <value>
                <fullName>ANESTHESIA</fullName>
            </value>
            <value>
                <fullName>AOC</fullName>
            </value>
            <value>
                <fullName>APC</fullName>
            </value>
            <value>
                <fullName>APK</fullName>
            </value>
            <value>
                <fullName>APPLE</fullName>
            </value>
            <value>
                <fullName>ARJO</fullName>
            </value>
            <value>
                <fullName>ARJOHUNTLEIGH</fullName>
            </value>
            <value>
                <fullName>ARKTUS</fullName>
            </value>
            <value>
                <fullName>ARTIS</fullName>
            </value>
            <value>
                <fullName>ARTROCORP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AVULSO</fullName>
            </value>
            <value>
                <fullName>CONTRATO DE LOCAÇÃO</fullName>
                <default>true</default>
                <label>CONTRATO DE LOCAÇÃO</label>
            </value>
            <value>
                <fullName>CONTRATO DE SERVIÇO</fullName>
            </value>
            <value>
                <fullName>GARANTIA DE FABRICA</fullName>
            </value>
            <value>
                <fullName>GARANTIA DE FÁBRICA</fullName>
            </value>
            <value>
                <fullName>GARANTIA DE SERVIÇO</fullName>
            </value>
            <value>
                <fullName>INSTALAÇÃO</fullName>
            </value>
            <value>
                <fullName>COMODATO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <formula>TEXT( Asset.Marca__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Marca</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/T_cnico_Respons_vel__c.field-meta.xml
<CustomField>
    <fullName>T_cnico_Respons_vel__c</fullName>
    <inlineHelpText>Esse campo foi descontinuado. Selecione o técnico no campo Técnico executor</inlineHelpText>
    <label>Responsável pela O.T (LEGADO)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ALEXANDRE AMARAL</fullName>
            </value>
            <value>
                <fullName>ALON ROCHA DA SILVA</fullName>
            </value>
            <value>
                <fullName>AMANDA JORDÃO</fullName>
            </value>
            <value>
                <fullName>ANA CAROLINE</fullName>
                <label>ANA CAROLINE TALAVERA</label>
            </value>
            <value>
                <fullName>ANDRE BRANDAO</fullName>
            </value>
            <value>
                <fullName>ANDRESSA PETRILLA</fullName>
            </value>
            <value>
                <fullName>ANTONIO LEVI</fullName>
            </value>
            <value>
                <fullName>BEATRIZ MARIANO</fullName>
            </value>
            <value>
                <fullName>BRUNO VINICIUS</fullName>
            </value>
            <value>
                <fullName>CAIO AUGUSTO</fullName>
            </value>
            <value>
                <fullName>CARLA BREVIGLIERO</fullName>
            </value>
            <value>
                <fullName>CARLOS ALBERTO SANTANA</fullName>
            </value>
            <value>
                <fullName>CASSIANO SILVA</fullName>
            </value>
            <value>
                <fullName>CLEITON RIBEIRO</fullName>
            </value>
            <value>
                <fullName>CYLL RODRIGUES</fullName>
            </value>
            <value>
                <fullName>DANIEL BORGES</fullName>
            </value>
            <value>
                <fullName>DANIEL NOGUEIRA DE OLIVEIRA</fullName>
            </value>
            <value>
                <fullName>DANILO GUIMARÃES</fullName>
            </value>
            <value>
                <fullName>DANILO SUSANO</fullName>
            </value>
            <value>
                <fullName>DAVID QUEIROZ</fullName>
            </value>
            <value>
                <fullName>DEIBLY ARAUJO</fullName>
            </value>
            <value>
                <fullName>DENY REYNER</fullName>
            </value>
            <value>
                <fullName>DIMAS RODRIGUES</fullName>
            </value>
            <value>
                <fullName>DOUGLAS CARVALHO</fullName>
            </value>
            <value>
                <fullName>DOUGLAS SANTOS</fullName>
            </value>
            <value>
                <fullName>EDER VIEIRA</fullName>
            </value>
            <value>
                <fullName>EDMUNDO BUBLIZ</fullName>
            </value>
            <value>
                <fullName>EDUARDO RIBEIRO</fullName>
            </value>
            <value>
                <fullName>EMERSON CÉSAR</fullName>
            </value>
            <value>
                <fullName>FHELIPE AUGUSTO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Tipo_de_Servi_o__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Servi_o__c</fullName>
    <label>Tipo de Serviço</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CALIBRAÇÃO</fullName>
            </value>
            <value>
                <fullName>ENSAIO DE SEGURANÇA ELÉTRICA</fullName>
            </value>
            <value>
                <fullName>ENTREGA</fullName>
            </value>
            <value>
                <fullName>INSTALAÇÃO</fullName>
            </value>
            <value>
                <fullName>MANUTENÇÃO CORRETIVA</fullName>
            </value>
            <value>
                <fullName>MANUTENÇÃO PREVENTIVA</fullName>
            </value>
            <value>
                <fullName>OUTROS</fullName>
            </value>
            <value>
                <fullName>QUALIFICAÇÃO</fullName>
            </value>
            <value>
                <fullName>VERIFICAÇÃO FUNCIONAL</fullName>
            </value>
            <value>
                <fullName>DEMONSTRAÇÃO DE PRODUTOS</fullName>
            </value>
            <value>
                <fullName>TREINAMENTO DE ATIVOS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <formula>TEXT(Product2.Marca__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Marca</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ListaItensZerados.cls
public with sharing class ListaItensZerados {
	
	public 	list<WorkOrderLineItem> lista 		{get;set;}
    public 	String					url_base 	{get;set;}
	
	
	public ListaItensZerados(){ 
		this.url_base = URL.getSalesforceBaseUrl().toExternalForm() + Site.getPathPrefix();
	
		lista = new list<WorkOrderLineItem>();
		lista = [
			select  	id, LineItemNumber, PricebookEntry.Product2.Name,
						WorkOrder.WorkOrderNumber, WorkOrder.Tipo_de_Servi_o__c, WorkOrder.T_cnico_Respons_vel__c
			FROM		WorkOrderLineItem
			WHERE		(
							(UnitPrice = 0) 	OR 
							(UnitPrice = null)
						)
						AND
						(
							(WorkOrder.Categoria__c != 'GARANTIA DE FÁBRICA') AND
							(WorkOrder.Categoria__c != 'GARANTIA DE SERVIÇO') AND
							(WorkOrder.Categoria__c != 'CONTRATO DE SERVIÇO') AND
							(WorkOrder.Categoria__c != 'CONTRATO DE LOCAÇÃO')
						)
						AND 
						(
							NOT
							(
								WorkOrder.Tipo_de_Servi_o__c = 'INSTALAÇÃO'		AND
								(
									WorkOrder.Marca__c LIKE 'fanem'				OR
									WorkOrder.Marca__c LIKE 'intermed'			OR
									WorkOrder.Marca__c LIKE 'sercon'				
								)
							)
						)
						AND 	(NOT PricebookEntry.Product2.Name LIKE 'SERVIÇO DE INSTALAÇÃO')
						AND		WorkOrder.CreatedDate >= 2017-05-15T00:00:00.000+0000
			ORDER BY	WorkOrder.T_cnico_Respons_vel__c
		];  
	}
}