force-app/main/default/objects/OrderItem/fields/Data_de_Entrega_Fornecedor__c.field-meta.xml
<CustomField>
    <fullName>Data_de_Entrega_Fornecedor__c</fullName>
    <label>_Data de Entrega Fornecedor (old) (del)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Novo</fullName>
            </value>
            <value>
                <fullName>Transferência Interna</fullName>
            </value>
            <value>
                <fullName>Pendência Interna</fullName>
            </value>
            <value>
                <fullName>Em Separação</fullName>
            </value>
            <value>
                <fullName>Galpão - Em Separação</fullName>
            </value>
            <value>
                <fullName>Separado</fullName>
            </value>
            <value>
                <fullName>Reservado</fullName>
            </value>
            <value>
                <fullName>OPR - ANALISE DE COMPRA</fullName>
            </value>
            <value>
                <fullName>CMP - COTAÇÃO DE COMPRA</fullName>
            </value>
            <value>
                <fullName>CMP - AG. ENTREGA FORNECEDOR</fullName>
            </value>
            <value>
                <fullName>Recebido Fornecedor</fullName>
            </value>
            <value>
                <fullName>Recebido A.T.</fullName>
            </value>
            <value>
                <fullName>Aguardando Faturamento</fullName>
            </value>
            <value>
                <fullName>Aguardando conferência</fullName>
            </value>
            <value>
                <fullName>Atendido</fullName>
            </value>
            <value>
                <fullName>Faturado</fullName>
            </value>
            <value>
                <fullName>Aguardando Coleta</fullName>
            </value>
            <value>
                <fullName>Em Avaliação Técnica</fullName>
            </value>
            <value>
                <fullName>CMP - AG. COMPRA IMPORTAÇÃO</fullName>
            </value>
            <value>
                <fullName>CMP - AG. COMPRA NACIONAL</fullName>
            </value>
            <value>
                <fullName>Em rota de entrega</fullName>
            </value>
            <value>
                <fullName>Entregue Cliente</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
                <label>OPR - CANCELADO</label>
            </value>
            <value>
                <fullName>Devolvido</fullName>
            </value>
            <value>
                <fullName>Recebido Parcial</fullName>
            </value>
            <value>
                <fullName>Recebido Total</fullName>
            </value>
            <value>
                <fullName>CMP - EM PRODUÇÃO FORN.</fullName>
            </value>
            <value>
                <fullName>CMP - EM COLETA PORTO/FORNECEDOR</fullName>
            </value>
            <value>
                <fullName>Em trânsito</fullName>
            </value>
            <value>
                <fullName>CMP - EM DESEMBARAÇO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ItemPedVerClass.cls
public class ItemPedVerClass {
    
    public static String VerificaStatus(OrderItem item_de_pedido){
        String retorno = null;
        Order pedido = new Order();
        pedido = [
            SELECT	Status
            FROM	Order
            WHERE	Id = :item_de_pedido.OrderId
        ];
        if((pedido.Status == 'Rascunho') ||
           (pedido.Status == 'Aguardando Aprovação Comercial') ||
           (pedido.Status == 'Aguardando Aprovação Financeira') ||
           (pedido.Status == 'Cancelado/Reprovado')){ 
            if(item_de_pedido.Status__c != 'Novo')
      			retorno = 'Não é possível alterar Status do item. Pedido não aprovado (' + pedido.Status + ')';
		}
        return retorno;
    }

    public static String VerificaDataFornecedor(OrderItem item_de_pedido){
        String retorno = null;
        Order pedido = new Order();
        pedido = [
            SELECT	Status
            FROM	Order
            WHERE	Id = :item_de_pedido.OrderId
        ];
        if((pedido.Status == 'Rascunho') ||
           (pedido.Status == 'Aguardando Aprovação Comercial') ||
           (pedido.Status == 'Aguardando Aprovação Financeira') ||
           (pedido.Status == 'Cancelado/Reprovado')){ 
            if(item_de_pedido.Data_de_Entrega_Fornecedor__c != null)
      			retorno = 'Não é possível alterar Data do item. Pedido ainda não aprovado (' + pedido.Status + ')';
		}
        return retorno;
    }
           
}