force-app/main/default/objects/OrderItem/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <formula>TEXT(PricebookEntry.Product2.Marca__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Marca</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Modelo__c.field-meta.xml
<CustomField>
    <fullName>Modelo__c</fullName>
    <formula>PricebookEntry.Modelo__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Modelo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>3GREEN</fullName>
            </value>
            <value>
                <fullName>7LIVES</fullName>
            </value>
            <value>
                <fullName>ABC</fullName>
            </value>
            <value>
                <fullName>ACCUMED</fullName>
            </value>
            <value>
                <fullName>ACROSS</fullName>
            </value>
            <value>
                <fullName>ACTE</fullName>
            </value>
            <value>
                <fullName>AEROGEN</fullName>
            </value>
            <value>
                <fullName>AGATA</fullName>
            </value>
            <value>
                <fullName>AGILE MED</fullName>
            </value>
            <value>
                <fullName>AIR LIQUIDE</fullName>
            </value>
            <value>
                <fullName>AIR SHIELD</fullName>
            </value>
            <value>
                <fullName>AJEL</fullName>
            </value>
            <value>
                <fullName>ALBAN</fullName>
            </value>
            <value>
                <fullName>ALIVE HEART</fullName>
            </value>
            <value>
                <fullName>ALLIAGE</fullName>
            </value>
            <value>
                <fullName>ALPHARAD</fullName>
            </value>
            <value>
                <fullName>ALVFLOR</fullName>
            </value>
            <value>
                <fullName>ALVIMÉDICA</fullName>
            </value>
            <value>
                <fullName>ANALYSER</fullName>
            </value>
            <value>
                <fullName>ANATONIC</fullName>
            </value>
            <value>
                <fullName>ANESTHESIA</fullName>
            </value>
            <value>
                <fullName>AOC</fullName>
            </value>
            <value>
                <fullName>APC</fullName>
            </value>
            <value>
                <fullName>APK</fullName>
            </value>
            <value>
                <fullName>APPLE</fullName>
            </value>
            <value>
                <fullName>ARJO</fullName>
            </value>
            <value>
                <fullName>ARJOHUNTLEIGH</fullName>
            </value>
            <value>
                <fullName>ARKTUS</fullName>
            </value>
            <value>
                <fullName>ARTIS</fullName>
            </value>
            <value>
                <fullName>ARTROCORP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Modelo__c.field-meta.xml
<CustomField>
    <fullName>Modelo__c</fullName>
    <label>Modelo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PedInsFeed.cls
public class PedInsFeed {
    
    public static void FluxoInicial(OrderItem item_de_pedido){
		OrderItem item_completo = new OrderItem();
		item_completo = [
			SELECT	Order.Status, Product2.ProductCode, Product2.Name, Product2.Marca__c, Product2.Modelo__c
			FROM	OrderItem
			WHERE	Id = :item_de_pedido.Id
		];
        
		if(item_completo.Order.Status != 'Rascunho'){
		
			user usuario = new User();
			usuario = [SELECT CommunityNickName FROM User WHERE Id = :System.UserInfo.getUserId()];
			
			String mensagem = 'O item <b>'+item_completo.Product2.Name+'</b>, ';
			if(item_completo.Product2.ProductCode != null)
				mensagem += 'PN <b>'+item_completo.Product2.ProductCode+'</b>, ';
			if(item_completo.Product2.Marca__c != null)
				mensagem += 'marca '+item_completo.Product2.Marca__c+', ';
			if(item_completo.Product2.Modelo__c != null)
				mensagem += 'modelo '+item_completo.Product2.Modelo__c+', ';
			mensagem += 'R$ '+item_de_pedido.UnitPrice+', ';
			mensagem += 'Qtd. '+item_de_pedido.Quantity+', ';
			mensagem += 'foi deletado por <b>'+usuario.CommunityNickName+'</b>';		
			
			FeedItem publicacao = new FeedItem(
				ParentId = item_de_pedido.OrderId,
				Type = 'TextPost',
				IsRichText = true,
				Body =  mensagem,
				NetworkScope = 'AllNetworks',
				Visibility = 'AllUsers',
				Status = 'Published'
			);
			
			insert publicacao;
		}
    }
    
}