force-app/main/default/objects/Account/fields/Area_da_Saude__c.field-meta.xml
<CustomField>
    <fullName>Area_da_Saude__c</fullName>
    <inlineHelpText>Preencher para contas do tipo fornecedor</inlineHelpText>
    <label>Área da Saúde</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sim</fullName>
            </value>
            <value>
                <fullName>Não</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Data_de_cria_o_da_conta__c.field-meta.xml
<CustomField>
    <fullName>Data_de_cria_o_da_conta__c</fullName>
    <formula>CreatedDate</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Data de criação da conta</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Matriz__c.field-meta.xml
<CustomField>
    <fullName>Matriz__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Matriz</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contas (Matriz)</relationshipLabel>
    <relationshipName>Contas2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fornecedor__c/Fornecedor__c.object-meta.xml
<CustomObject>
    <label>Pedido de Compra</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número do Pedido de Compra</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pedidos de Compra</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fornecedor__c/fields/Comprador__c.field-meta.xml
<CustomField>
    <fullName>Comprador__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Comprador</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Fornecedores3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fornecedor__c/fields/Fornecedor__c.field-meta.xml
<CustomField>
    <fullName>Fornecedor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Fornecedor</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Fornecedores1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Paciente</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Pedidos (Paciente)</relationshipLabel>
    <relationshipName>Pedidos4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Faturamento_Feito__c.field-meta.xml
<CustomField>
    <fullName>Faturamento_Feito__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Empresa do grupo Hospcom que irá faturar o pedido.</inlineHelpText>
    <label>Faturamento feito</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Faturamentos Feitos (de pedidos)</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Gerente__c.field-meta.xml
<CustomField>
    <fullName>Gerente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gerente</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Pedidos1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Telefone_Contato__c.field-meta.xml
<CustomField>
    <fullName>Telefone_Contato__c</fullName>
    <label>Telefone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Referencia_bancaria__c/Referencia_bancaria__c.object-meta.xml
<CustomObject>
    <label>Referência bancária</label>
    <nameField>
        <displayFormat>RB-{0000}</displayFormat>
        <label>Referência bancária</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referências bancárias</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Referencia_bancaria__c/fields/Agencia__c.field-meta.xml
<CustomField>
    <fullName>Agencia__c</fullName>
    <label>Agência</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referencia_bancaria__c/fields/Banco__c.field-meta.xml
<CustomField>
    <fullName>Banco__c</fullName>
    <inlineHelpText>Nome do banco</inlineHelpText>
    <label>Banco</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referencia_bancaria__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Empresa</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Referências bancárias</relationshipLabel>
    <relationshipName>Refereias_bancarias</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Referencia_bancaria__c/fields/Conta_bancaria__c.field-meta.xml
<CustomField>
    <fullName>Conta_bancaria__c</fullName>
    <label>Conta</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referencia_bancaria__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contato</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Account.Id</field>
            <operation>equals</operation>
            <value>001i00000085QYb</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Referências bancárias</relationshipLabel>
    <relationshipName>Referencias_bancarias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Referencia_bancaria__c/fields/Gerente__c.field-meta.xml
<CustomField>
    <fullName>Gerente__c</fullName>
    <label>Gerente</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referencia_bancaria__c/fields/Tele_conta__c.field-meta.xml
<CustomField>
    <fullName>Tele_conta__c</fullName>
    <formula>Conta__r.Phone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Telefone conta</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referencia_bancaria__c/fields/Telefone_Contato__c.field-meta.xml
<CustomField>
    <fullName>Telefone_Contato__c</fullName>
    <formula>Contato__r.MobilePhone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Telefone Contato</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Referencia_bancaria__c/fields/Telefone_Gerente__c.field-meta.xml
<CustomField>
    <fullName>Telefone_Gerente__c</fullName>
    <label>Telefone Gerente</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ListagemFornecedoresDeUmComprador.cls
public with sharing class ListagemFornecedoresDeUmComprador {

    public Account conta {get; set;}
    public List<Fornecedor> fornecedores {get; set;} 
    public List<Cliente> clientes {get; set;}   
    public List<ReferenciaBancaria> referencias {get; set;}
    
    public class Fornecedor {
        public String idFornecedor {get; set;}
        public String fornecedorName {get; set;}
        public String telefoneFornecedor {get; set;}
        public Integer anosDesdeCriacao {get; set;} 
        public Integer numCompradores {get; set;}
        public String nomeContato {get;set;}
    }

    public class Cliente {
        public String idCliente {get; set;}
        public String clienteName {get; set;}
        public String telefoneCliente {get; set;}
        public Integer anosDesdeCriacao {get; set;} 
        public Integer numCompradores {get; set;}
        public String nomeContato {get;set;}
        public String tipoConta {get;set;}
    }

    public class ReferenciaBancaria {
        public String idReferencia {get; set;}
        public String nome {get; set;}
        public String agencia {get; set;}
        public String banco {get; set;}
        public String telefoneGerente {get; set;}
        public String telefoneContato {get; set;}
        public String teleConta {get; set;}
        public String gerente {get; set;}
        public String nomeContato {get; set;}
        public String conta_bancaria {get; set;}
    }

    public static String trataId(String idEmpresa){
        if (idEmpresa.length() > 15) {
            return idEmpresa.substring(0, 15);
        } else {
            return idEmpresa;
        }        
    }

    public ListagemFornecedoresDeUmComprador(ApexPages.StandardController controller) {
        Id objetoPai = ((SObject)controller.getRecord()).Id;

        if (objetoPai.getSObjectType().getDescribe().getName() == 'Account') {
            try {
                // Recuperar a Account com o campo Matriz__c
                Account conta = [
                    SELECT Id, Matriz__c
                    FROM Account
                    WHERE Id = :objetoPai
                    LIMIT 1
                ];

                listagemFornecedores(conta);
                listagemClientes(conta);
                listagemReferencia(conta); // Chamando o método para listar referências bancárias
            } catch (Exception e) {
                System.debug('Error: ' + e);
            }
        }
    }

    public void listagemFornecedores(Account conta) {
        this.conta = conta;
        Id contaIdRef = (conta.Matriz__c != null) ? conta.Matriz__c : conta.Id;
        fornecedores = new List<Fornecedor>();

        List<AggregateResult> resultados = [
            SELECT Fornecedor__r.Id idFornecedor, Fornecedor__r.Name fornecedorName, Fornecedor__r.Phone telefoneFornecedor, Fornecedor__r.Data_de_cria_o_da_conta__c dataEmpresa, COUNT(Id) numCompradores
            FROM Fornecedor__c
            WHERE Comprador__c = :contaIdRef AND Fornecedor__r.Area_da_Saude__c = 'Sim'
            GROUP BY Fornecedor__r.Id, Fornecedor__r.Name, Fornecedor__r.Phone, Fornecedor__r.Data_de_cria_o_da_conta__c 
            ORDER BY COUNT(Id) DESC
            LIMIT 5
        ];
        
        for(AggregateResult resultado : resultados) {
            Fornecedor fornecedor = new Fornecedor();
            fornecedor.idFornecedor = (String)resultado.get('idFornecedor');
            fornecedor.fornecedorName = (String)resultado.get('fornecedorName');
            fornecedor.telefoneFornecedor = (String)resultado.get('telefoneFornecedor');
            
            // Calculando a diferença em anos
            Date dataEmpresa = (Date)resultado.get('dataEmpresa');
            fornecedor.anosDesdeCriacao = Date.today().year() - dataEmpresa.year();
            if (Date.today().month() < dataEmpresa.month() || (Date.today().month() == dataEmpresa.month() && Date.today().day() < dataEmpresa.day())) {
                fornecedor.anosDesdeCriacao--;
            }
            
            fornecedor.numCompradores = (Integer)resultado.get('numCompradores');
            
            try {
                String nome = nomeContatoFunction((String)resultado.get('idFornecedor')); 
                fornecedor.nomeContato = nome;
            } catch(Exception e) {
                System.debug('ERRO ao consultar');
            }
            
            fornecedores.add(fornecedor);
        }
    }

    public void listagemClientes(Account conta) {
        Id contaIdRef = (conta.Matriz__c != null) ? conta.Matriz__c : conta.Id;

        List<AggregateResult> resultadosCliente = [            
            SELECT AccountId idCliente, Account.Name clienteName, Account.Type tipoConta, Account.Phone telefoneCliente, Account.Data_de_cria_o_da_conta__c dataEmpresa, COUNT(Id) numCompradores
            FROM Order  
            WHERE Faturamento_Feito__c = :contaIdRef AND Account.Type = 'CLIENTE' 
            GROUP BY AccountId, Account.Name, Account.Type, Account.Phone, Account.Data_de_cria_o_da_conta__c 
            ORDER BY COUNT(Id) DESC 
            LIMIT 5
        ];

        clientes = new List<Cliente>();
        
        if(resultadosCliente.size() > 0) {        
            for(AggregateResult resultadoCliente : resultadosCliente) {
                Cliente cliente = new Cliente();
                cliente.idCliente = (String)resultadoCliente.get('idCliente');
                cliente.clienteName = (String)resultadoCliente.get('clienteName');
                cliente.telefoneCliente = (String)resultadoCliente.get('telefoneCliente');
                cliente.tipoConta = (String)resultadoCliente.get('tipoConta');

                Date dataEmpresaCliente = (Date)resultadoCliente.get('dataEmpresa');
                cliente.anosDesdeCriacao = Date.today().year() - dataEmpresaCliente.year();
                if (Date.today().month() < dataEmpresaCliente.month() || (Date.today().month() == dataEmpresaCliente.month() && Date.today().day() < dataEmpresaCliente.day())) {
                    cliente.anosDesdeCriacao--;
                }

                cliente.numCompradores = (Integer)resultadoCliente.get('numCompradores');

                try {
                    String nomeCliente = nomeContatoFunction((String)resultadoCliente.get('idCliente')); 
                    cliente.nomeContato = nomeCliente;
                } catch(Exception e) {
                    System.debug('ERRO ao consultar cliente: ' + e);
                }

                clientes.add(cliente);
            }
        } else {
            clientes = null;
        }
    }

    public void listagemReferencia(Account conta) {
    Id contaIdRef = (conta.Matriz__c != null) ? conta.Matriz__c : conta.Id;

    List<Referencia_bancaria__c> referenciasBancarias = [
        SELECT Id, Name, Banco__c, Agencia__c, Telefone_Gerente__c, Telefone_Contato__c, Conta_bancaria__c, Tele_conta__c, Gerente__c, Conta__c, Contato__r.Name
        FROM Referencia_bancaria__c  
        WHERE Conta__c = :contaIdRef
        LIMIT 5
    ];

        
    referencias = new List<ReferenciaBancaria>();

    for (Referencia_bancaria__c referencia : referenciasBancarias) {
        ReferenciaBancaria ref = new ReferenciaBancaria();
        ref.idReferencia = referencia.Id;
        ref.nome = referencia.Name;
        ref.conta_bancaria = referencia.Conta_bancaria__c;
        ref.agencia = referencia.Agencia__c;
        ref.banco = referencia.Banco__c;
        ref.telefoneGerente = referencia.Telefone_Gerente__c;
        ref.telefoneContato = referencia.Telefone_Contato__c;
        ref.teleConta = referencia.Tele_conta__c;
        ref.gerente = referencia.Gerente__c;
        ref.nomeContato = referencia.Contato__r.Name;

        referencias.add(ref);
    }

    if (referencias.isEmpty()) {
        referencias = null;
    }
}


    public static String nomeContatoFunction(String idDoContato) {
        Contact contato = [
            SELECT Id, Name, AccountId
            FROM Contact
            WHERE AccountId = :idDoContato 
            ORDER BY CreatedDate DESC
            LIMIT 1
        ];

        if (contato != null) {
            return contato.Name;
        } else {
            return null;
        }
    }
}