force-app/main/default/objects/Account/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CLINICA</fullName>
            </value>
            <value>
                <fullName>FARMACÊUTICA</fullName>
            </value>
            <value>
                <fullName>GOVERNO</fullName>
            </value>
            <value>
                <fullName>HOSPITAL</fullName>
            </value>
            <value>
                <fullName>INDUSTRIA</fullName>
            </value>
            <value>
                <fullName>LABORATORIO</fullName>
            </value>
            <value>
                <fullName>ORGANIZAÇÃO SOCIAL</fullName>
            </value>
            <value>
                <fullName>ORGÃO GESTOR</fullName>
            </value>
            <value>
                <fullName>PLANO DE SAÚDE</fullName>
            </value>
            <value>
                <fullName>UNIVERSIDADE</fullName>
            </value>
            <value>
                <fullName>VETERINÁRIA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Especialidade__c.field-meta.xml
<CustomField>
    <fullName>Especialidade__c</fullName>
    <label>Especialidade</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACUPUNTURA</fullName>
            </value>
            <value>
                <fullName>AGROPECUARIA</fullName>
            </value>
            <value>
                <fullName>ALERGIA</fullName>
            </value>
            <value>
                <fullName>ALIMENTICIA</fullName>
            </value>
            <value>
                <fullName>ANESTESIOLOGIA</fullName>
            </value>
            <value>
                <fullName>ANGIOLOGIA</fullName>
            </value>
            <value>
                <fullName>CANCEROLOGIA</fullName>
            </value>
            <value>
                <fullName>CARDIOLOGIA</fullName>
            </value>
            <value>
                <fullName>CIRURGIA CARDIOVASCULAR</fullName>
            </value>
            <value>
                <fullName>CIRURGIA DA MÃO</fullName>
            </value>
            <value>
                <fullName>CIRURGIA DE CABEÇA E PESCOÇO</fullName>
            </value>
            <value>
                <fullName>CIRURGIA DO APARELHO DIGESTIVO</fullName>
            </value>
            <value>
                <fullName>CIRURGIA GERAL</fullName>
            </value>
            <value>
                <fullName>CIRURGIA PEDIATRICA</fullName>
            </value>
            <value>
                <fullName>CIRURGIA PLASTICA</fullName>
            </value>
            <value>
                <fullName>CIRURGIA TORACICA</fullName>
            </value>
            <value>
                <fullName>CIRURGIA VASCULAR</fullName>
            </value>
            <value>
                <fullName>CLINICA DE ESTÉTICA</fullName>
            </value>
            <value>
                <fullName>CLINICA DIAGNÓSTICA</fullName>
            </value>
            <value>
                <fullName>CLINICA MEDICA</fullName>
            </value>
            <value>
                <fullName>COLOPROCTOLOGIA</fullName>
            </value>
            <value>
                <fullName>DERMATOLOGIA</fullName>
            </value>
            <value>
                <fullName>EMERGENCIA</fullName>
            </value>
            <value>
                <fullName>ENDOCRINOLOGIA</fullName>
            </value>
            <value>
                <fullName>ENDOSCOPIA</fullName>
            </value>
            <value>
                <fullName>ESTERILIZAÇÃO</fullName>
            </value>
            <value>
                <fullName>FARMACEUTICA</fullName>
            </value>
            <value>
                <fullName>FARMACIA</fullName>
            </value>
            <value>
                <fullName>FUNDAÇÃO</fullName>
            </value>
            <value>
                <fullName>GASTROENTEROLOGIA</fullName>
            </value>
            <value>
                <fullName>PREFEITURA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <label>Lead</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Raz_o_Social__c.field-meta.xml
<CustomField>
    <fullName>Raz_o_Social__c</fullName>
    <label>Razão social</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status_receita__c.field-meta.xml
<CustomField>
    <fullName>Status_receita__c</fullName>
    <label>Status receita</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Conta_comercial.recordType-meta.xml
<RecordType>
    <fullName>Conta_comercial</fullName>
    <active>true</active>
    <description>Parceiro de negócio pessoa jurídica (CNPJ)</description>
    <label>Conta comercial</label>
</RecordType>

force-app/main/default/objects/Lead/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>Categoria</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>linha</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/linha.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CAMAS HOSPITALARES</fullName>
    </customValue>
    <customValue>
        <fullName>CIRURGIA MINIMAMENTE INVASIVA</fullName>
    </customValue>
    <customValue>
        <fullName>CIRURGIA ROBÓTICA</fullName>
    </customValue>
    <customValue>
        <fullName>ELETROCIRURGIA</fullName>
    </customValue>
    <customValue>
        <fullName>ENDOSCOPIA</fullName>
    </customValue>
    <customValue>
        <fullName>HUAWEI</fullName>
    </customValue>
    <customValue>
        <fullName>IMAGEM</fullName>
    </customValue>
    <customValue>
        <fullName>IMAGEM RAIO-X</fullName>
    </customValue>
    <customValue>
        <fullName>IMAGEM ULTRASSOM</fullName>
    </customValue>
    <customValue>
        <fullName>LOCAÇÃO</fullName>
    </customValue>
    <customValue>
        <fullName>MONITORES DE GRAU MEDICO</fullName>
    </customValue>
    <customValue>
        <fullName>NEONATOLOGIA</fullName>
    </customValue>
    <customValue>
        <fullName>OPME</fullName>
    </customValue>
    <customValue>
        <fullName>OUTROS</fullName>
    </customValue>
    <customValue>
        <fullName>PM</fullName>
    </customValue>
    <customValue>
        <fullName>PMLS</fullName>
    </customValue>
    <customValue>
        <fullName>SERVIÇO</fullName>
    </customValue>
    <customValue>
        <fullName>SURGICAL</fullName>
    </customValue>
    <customValue>
        <fullName>VETERINÁRIA</fullName>
    </customValue>
    <customValue>
        <fullName>VETERINÁRIA IVD</fullName>
    </customValue>
    <customValue>
        <fullName>VETERINÁRIA MIS</fullName>
    </customValue>
    <customValue>
        <fullName>VETERINÁRIA PMLS</fullName>
    </customValue>
    <customValue>
        <fullName>VIAS AÉREAS DIFÍCEIS</fullName>
    </customValue>
    <customValue>
        <fullName>VETQLAB</fullName>
    </customValue>
    <customValue>
        <fullName>INFUSÃO</fullName>
        <isActive>false</isActive>
        <label>INFUSÃO</label>
    </customValue>
    <customValue>
        <fullName>ESTERILIZACAO</fullName>
        <isActive>false</isActive>
        <label>ESTERILIZACAO</label>
    </customValue>
    <customValue>
        <fullName>CUIDADOS PESSOAIS</fullName>
        <isActive>false</isActive>
        <label>CUIDADOS PESSOAIS</label>
    </customValue>
    <customValue>
        <fullName>CMI</fullName>
        <isActive>false</isActive>
        <label>CMI</label>
    </customValue>
    <customValue>
        <fullName>LABORATORIAL</fullName>
        <isActive>false</isActive>
        <label>LABORATORIAL</label>
    </customValue>
    <customValue>
        <fullName>APOIO A MOBILIDADE</fullName>
        <isActive>false</isActive>
        <label>APOIO A MOBILIDADE</label>
    </customValue>
    <masterLabel>linha</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/AccountTriggerTest.cls
@isTest
public class AccountTriggerTest {
    
    @isTest
    static void criarDados(){
        Lead newLead = new Lead();
        newLead.LastName = 'HospCOm teste';
        insert newLead;

        Account contaSpe = new Account();
        contaSpe.Name = 'Hospcom Test';
        contaSpe.Type = 'CLIENTE FINAL';
        contaSpe.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Conta_comercial').getRecordTypeId();
        contaSpe.Phone = '(81) 99999-9991'; 
        contaSpe.Industry = 'ÓRGÃO GESTOR DE SAÚDE';
        contaSpe.Description = 'CÓDIGO E DESCRIÇÃO DA ATIVIDADE';
        contaSpe.CNPJ__c = '86.249.279/0001-67';
        contaSpe.Raz_o_Social__c = 'MUNICIPIO DE SINOP';
        contaSpe.Categoria__c = 'ORGÃO GESTOR';
        contaSpe.Status_receita__c = 'SUCESSO';
        contaSpe.Especialidade__c = 'PREFEITURA';
        contaSpe.Lead__c = 'blablablab';
        insert contaSpe;

        contaSpe.Phone = '(81) 99999-8221';
        update contaSpe;
    }
}