force-app/main/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Forma_de_pagamento2__c.field-meta.xml
<CustomField>
    <fullName>Forma_de_pagamento2__c</fullName>
    <label>Forma de pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Formas_de_pagamento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/E_mail_Contato__c.field-meta.xml
<CustomField>
    <fullName>E_mail_Contato__c</fullName>
    <label>E-mail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Order/fields/Faturamento_Feito__c.field-meta.xml
<CustomField>
    <fullName>Faturamento_Feito__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Empresa do grupo Hospcom que irá faturar o pedido.</inlineHelpText>
    <label>Faturamento feito</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Faturamentos Feitos (de pedidos)</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Forma_de_pagamento2__c.field-meta.xml
<CustomField>
    <fullName>Forma_de_pagamento2__c</fullName>
    <label>Forma de pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Natureza_de_Opera_o__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Formas_de_pagamento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Natureza_de_Opera_o__c.field-meta.xml
<CustomField>
    <fullName>Natureza_de_Opera_o__c</fullName>
    <label>Natureza de Operação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BONIFICAÇÃO</fullName>
            </value>
            <value>
                <fullName>DEMONSTRAÇÃO</fullName>
            </value>
            <value>
                <fullName>LOCAÇÃO</fullName>
            </value>
            <value>
                <fullName>EMPRÉSTIMO</fullName>
            </value>
            <value>
                <fullName>REMESSA DE LOCAÇÃO</fullName>
            </value>
            <value>
                <fullName>REMESSA DE TROCA</fullName>
            </value>
            <value>
                <fullName>REMESSA EM CONSIGNAÇÃO</fullName>
            </value>
            <value>
                <fullName>SERVIÇO</fullName>
            </value>
            <value>
                <fullName>VENDA</fullName>
            </value>
            <value>
                <fullName>VENDA DA CONSIGNAÇÃO</fullName>
            </value>
            <value>
                <fullName>RETORNO DE LOCAÇÃO</fullName>
            </value>
            <value>
                <fullName>EXPORTAÇÃO</fullName>
            </value>
            <value>
                <fullName>Baixa de estoque Interno</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Nome_Contato_Financeiro__c.field-meta.xml
<CustomField>
    <fullName>Nome_Contato_Financeiro__c</fullName>
    <label>Nome</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Telefone_Contato__c.field-meta.xml
<CustomField>
    <fullName>Telefone_Contato__c</fullName>
    <label>Telefone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Order/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PedidosVendedor</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/recordTypes/Hospcom.recordType-meta.xml
<RecordType>
    <fullName>Hospcom</fullName>
    <active>true</active>
    <description>Para faturamento das empresas do grupo Hospcom</description>
    <label>Hospcom</label>
</RecordType>

force-app/main/default/classes/dlrs_OrderTest.cls
/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
@IsTest
private class dlrs_OrderTest
{

    @IsTest
    private static void testTrigger()
    {
        // Cria uma conta parceira SEM ativar IsPartner ainda
        Account partnerAccount = new Account(
            Name = 'Teste Acct',
            Phone = '85999999999',
            BillingStreet = 'Av. Goiás, 123',
            BillingCity = 'Lapa',
            BillingState = 'Goiás',
            BillingCountry = 'Brasil',
            BillingPostalCode = '74000-000',
            CNPJ__c =  '05.743.288/0001-08'
        );
        insert partnerAccount;

        // Cria contatos
        Contact colaborador = new Contact(
            FirstName='Colaborador',
            LastName='Teste',
            AccountId = partnerAccount.Id,
            Email = 'colaborardor@teste.com'
        );
        insert colaborador;

        Contact gestor = new Contact(
            FirstName='Gestor',
            LastName='Teste',
            AccountId = partnerAccount.Id,
            Email = 'gestor@teste.com'
        );
        insert gestor;

        // Ativa IsPartner e cria usuários parceiros
        User dummyAdmin = [SELECT Id, name, isActive FROM User WHERE (Profile.Name = 'Administrador do sistema' OR Profile.Name = 'System Administrator' ) AND IsActive = true  LIMIT 1];

        System.runAs(dummyAdmin) {
            partnerAccount.IsPartner = true;
            update partnerAccount;

            Profile p = [SELECT Id FROM Profile WHERE Name='Partner Community User'];

            User colaborarUser = new User(
                Alias = 'testuser',
                Email = 'test.partner@example.com',
                EmailEncodingKey = 'UTF-8',
                LastName = 'Partner',
                FirstName = 'Test',
                LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US',
                ProfileId = p.Id,
                TimeZoneSidKey = 'America/Los_Angeles',
                UserName = 'test.partner@hospcom.com',
                ContactId = colaborador.Id,
                IsActive = true
            );
            insert colaborarUser;

            User gestorUser = new User(
                Alias = 'testGest',
                Email = 'test2.partner@example.com',
                EmailEncodingKey = 'UTF-8',
                LastName = 'Gestor',
                FirstName = 'Test',
                LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US',
                ProfileId = p.Id,
                TimeZoneSidKey = 'America/Los_Angeles',
                UserName = 'test2.partner@hospcom.com',
                ContactId = gestor.Id,
                IsActive = true
            );
            insert gestorUser;
        }

        User colaboradorUser = [SELECT Id FROM User WHERE ContactId = :colaborador.Id];

        // Conta e oportunidade
        Account acc = new Account(
            Name = 'Conta Teste',
            BillingStreet = 'Rua das Palmeiras, 456',
            BillingCity = 'Lapa',
            BillingState = 'Goiás',
            BillingCountry = 'Brasil',
            BillingPostalCode = '74000-001',
            CNPJ__c = '11.328.248/0001-00'
        );
        insert acc;

        Opportunity opp = new Opportunity(
            Name = 'Opp Teste',
            AccountId = acc.Id,
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(30)
        );
        insert opp;

    
       RecordType rt = [SELECT Id FROM RecordType WHERE DeveloperName = 'Hospcom' AND SobjectType = 'Order' LIMIT 1];
        // Pedido (Order)
        Order ped = new Order(
            Name = 'Pedido Teste',
            OpportunityId = opp.Id,
            AccountId = acc.Id,
            Status = 'Rascunho',
            EffectiveDate = Date.today(),
            OwnerId = colaboradorUser.Id,
            Nome_Contato_Financeiro__c = 'Financeiro',
            E_mail_Contato__c = 'contato@finaceiro.com',
            Telefone_Contato__c = '13999999999',
            Vendedor__c = colaboradorUser.Id,
            Faturamento_Feito__c = partnerAccount.Id,
            Forma_de_pagamento2__c = 'Sem Mov. Financeiro',
            RecordTypeId = rt.Id,
            Natureza_de_Opera_o__c = 'VENDA'
        );
       
      
        // Force the dlrs_OrderTrigger to be invoked, fails the test if org config or other Apex code prevents this.
        dlrs.RollupService.testHandler( ped);
    }
}