force-app/main/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Raz_o_Social__c.field-meta.xml
<CustomField>
    <fullName>Raz_o_Social__c</fullName>
    <label>Razão social</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fornecedor__c/Fornecedor__c.object-meta.xml
<CustomObject>
    <label>Pedido de Compra</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número do Pedido de Compra</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pedidos de Compra</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fornecedor__c/fields/Comprador__c.field-meta.xml
<CustomField>
    <fullName>Comprador__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Comprador</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Fornecedores3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fornecedor__c/fields/Fornecedor__c.field-meta.xml
<CustomField>
    <fullName>Fornecedor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Fornecedor</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Fornecedores1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fornecedor__c/fields/Observacoes_Cotacao__c.field-meta.xml
<CustomField>
    <fullName>Observacoes_Cotacao__c</fullName>
    <inlineHelpText>Parágrafo adicional para PDF de Solicitação de Cotação.</inlineHelpText>
    <label>Observações Cotação</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Fornecedor__c/fields/Pedido_de_compra__c.field-meta.xml
<CustomField>
    <fullName>Pedido_de_compra__c</fullName>
    <label>Cotação</label>
    <referenceTo>Pedido_de_compra__c</referenceTo>
    <relationshipName>Fornecedores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Item_de_fornecedor__c/Item_de_fornecedor__c.object-meta.xml
<CustomObject>
    <label>Item de pedido de compra</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Nº do item de pedido de compra</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens de pedido de compra</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Item_de_fornecedor__c/fields/Cotar__c.field-meta.xml
<CustomField>
    <fullName>Cotar__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cotar</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Item_de_fornecedor__c/fields/Descricao__c.field-meta.xml
<CustomField>
    <fullName>Descricao__c</fullName>
    <formula>Item_de_pedido_de_compra__r.Descri_o_da_linha__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Descrição</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Item_de_fornecedor__c/fields/Fornecedor__c.field-meta.xml
<CustomField>
    <fullName>Fornecedor__c</fullName>
    <label>Pedido de Compra</label>
    <referenceTo>Fornecedor__c</referenceTo>
    <relationshipLabel>Itens de pedido de compra</relationshipLabel>
    <relationshipName>Itens_de_fornecedor</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Item_de_fornecedor__c/fields/Item_de_pedido_de_compra__c.field-meta.xml
<CustomField>
    <fullName>Item_de_pedido_de_compra__c</fullName>
    <label>Item de cotação</label>
    <referenceTo>Item_de_pedido_de_compra__c</referenceTo>
    <relationshipName>Itens_de_fornecedor</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Item_de_fornecedor__c/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <formula>Item_de_pedido_de_compra__r.Marca__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Marca</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Item_de_fornecedor__c/fields/Modelo__c.field-meta.xml
<CustomField>
    <fullName>Modelo__c</fullName>
    <formula>Item_de_pedido_de_compra__r.Modelo__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Modelo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Item_de_fornecedor__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <formula>Item_de_pedido_de_compra__r.Produto__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Produto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Item_de_fornecedor__c/fields/Quantidade__c.field-meta.xml
<CustomField>
    <fullName>Quantidade__c</fullName>
    <label>Quantidade</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Item_de_pedido_de_compra__c/Item_de_pedido_de_compra__c.object-meta.xml
<CustomObject>
    <label>Item de cotação</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número do item de cotação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens de cotação</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Item_de_pedido_de_compra__c/fields/Descri_o_da_linha__c.field-meta.xml
<CustomField>
    <fullName>Descri_o_da_linha__c</fullName>
    <label>Descrição da linha</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Item_de_pedido_de_compra__c/fields/Pedido_de_compra__c.field-meta.xml
<CustomField>
    <fullName>Pedido_de_compra__c</fullName>
    <label>Cotação</label>
    <referenceTo>Pedido_de_compra__c</referenceTo>
    <relationshipLabel>Itens de cotação</relationshipLabel>
    <relationshipName>Itens_de_Pedido_de_Compra</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Item_de_pedido_de_compra__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Produtos_do_pedido</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Item_de_pedido_de_compra__c/fields/Quantidade_requisitada__c.field-meta.xml
<CustomField>
    <fullName>Quantidade_requisitada__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quantidade requisitada</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pedido_de_compra__c/Pedido_de_compra__c.object-meta.xml
<CustomObject>
    <label>Cotação de compra</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número da cotação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cotações de compra</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Pedido_de_compra__c/fields/Comprador__c.field-meta.xml
<CustomField>
    <fullName>Comprador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Comprador</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Pedidos_de_compra_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pedido_de_compra__c/fields/Descricao__c.field-meta.xml
<CustomField>
    <fullName>Descricao__c</fullName>
    <label>Descrição</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pedido_de_compra__c/fields/Entrega_CEP__c.field-meta.xml
<CustomField>
    <fullName>Entrega_CEP__c</fullName>
    <label>Entrega CEP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pedido_de_compra__c/fields/Entrega_Cidade__c.field-meta.xml
<CustomField>
    <fullName>Entrega_Cidade__c</fullName>
    <label>Entrega Cidade</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pedido_de_compra__c/fields/Entrega_Estado__c.field-meta.xml
<CustomField>
    <fullName>Entrega_Estado__c</fullName>
    <label>Entrega Estado</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pedido_de_compra__c/fields/Entrega_Pais__c.field-meta.xml
<CustomField>
    <fullName>Entrega_Pais__c</fullName>
    <label>Entrega País</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pedido_de_compra__c/fields/Entrega_Rua__c.field-meta.xml
<CustomField>
    <fullName>Entrega_Rua__c</fullName>
    <label>Entrega Rua</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pedido_de_compra__c/fields/Quantidade_requisitada__c.field-meta.xml
<CustomField>
    <fullName>Quantidade_requisitada__c</fullName>
    <label>Quantidade requisitada</label>
    <summarizedField>Item_de_pedido_de_compra__c.Quantidade_requisitada__c</summarizedField>
    <summaryForeignKey>Item_de_pedido_de_compra__c.Pedido_de_compra__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/AssistenteCotacaoPDF.cls
public with sharing class AssistenteCotacaoPDF{

	public Fornecedor__c 				fornecedor {get;set;}
	public List<Item_de_fornecedor__c> 	itens_fornecedor {get;set;}
	public List<Item_de_fornecedor__c> 	itens_fornecedor_cotar {get;set;}
			
	public Boolean 						tem_erros {get;set;}
	public List<String> 				erros {get;set;}
	
	public Boolean 						tem_produtos {get;set;}

	public AssistenteCotacaoPDF(ApexPages.StandardController controller) {
		Inicializa(controller);
	}
	
	public void Inicializa(ApexPages.StandardController controller){
		tem_erros = false;
		tem_produtos = true;

		fornecedor = (Fornecedor__c)controller.getRecord();
		fornecedor = [
			SELECT	Id, Name, Observacoes_Cotacao__c, 
					Pedido_de_compra__c, Pedido_de_compra__r.Name, Pedido_de_compra__r.Descricao__c, 
					Pedido_de_compra__r.Entrega_CEP__c, Pedido_de_compra__r.Entrega_Cidade__c, 
					Pedido_de_compra__r.Entrega_Estado__c, Pedido_de_compra__r.Entrega_Pais__c, 
					Pedido_de_compra__r.Entrega_Rua__c,
					Comprador__c, Comprador__r.Name, Comprador__r.CNPJ__c, Comprador__r.Raz_o_Social__c, 
					Fornecedor__c, Fornecedor__r.Name, Fornecedor__r.CNPJ__c, Fornecedor__r.Raz_o_Social__c
			FROM	Fornecedor__c
			WHERE	Id = :fornecedor.Id
		][0];
		fornecedor.Pedido_de_compra__r.Entrega_Estado__c = ConverteEstado(fornecedor.Pedido_de_compra__r.Entrega_Estado__c);
		
		itens_fornecedor = [
			SELECT 	Item_de_pedido_de_compra__r.Produto__r.ProductCode, Item_de_pedido_de_compra__r.Produto__r.Name,
					Item_de_pedido_de_compra__r.Produto__r.Modelo__c, Item_de_pedido_de_compra__r.Produto__r.Marca__c, 
					Item_de_pedido_de_compra__r.Produto__r.URL_da_Imagem__c,
					Item_de_pedido_de_compra__r.Descri_o_da_linha__c, Item_de_pedido_de_compra__r.Quantidade_requisitada__c,
					Cotar__c, Quantidade__c
			FROM	Item_de_fornecedor__c
			WHERE	Fornecedor__c = :fornecedor.Id
		];
		
		BuscaItensPDF();
	}
	
	public void BuscaItensPDF(){
		itens_fornecedor_cotar = [
			SELECT 	Item_de_pedido_de_compra__r.Produto__r.ProductCode, Item_de_pedido_de_compra__r.Produto__r.Name,
					Item_de_pedido_de_compra__r.Produto__r.Modelo__c, Item_de_pedido_de_compra__r.Produto__r.Marca__c,
					Item_de_pedido_de_compra__r.Descri_o_da_linha__c, Item_de_pedido_de_compra__r.Quantidade_requisitada__c,
					Cotar__c, Quantidade__c
			FROM	Item_de_fornecedor__c
			WHERE	Fornecedor__c = :fornecedor.Id AND
					Cotar__c = true
		];
	}
	
	public String ConverteEstado(String estado){
		
		if     (estado == 'Acre')                estado = 'AC';
		else if(estado == 'Alagoas')             estado = 'AL';
		else if(estado == 'Amapá')               estado = 'AP';
		else if(estado == 'Amazonas')            estado = 'AM';
		else if(estado == 'Bahia')               estado = 'BA';
		else if(estado == 'Ceará')               estado = 'CE';
		else if(estado == 'Distrito Federal')    estado = 'DF';
		else if(estado == 'Espírito Santo')      estado = 'ES';
		else if(estado == 'Goiás')               estado = 'GO';
		else if(estado == 'Maranhão')            estado = 'MA';
		else if(estado == 'Mato Grosso')         estado = 'MT';
		else if(estado == 'Mato Grosso do Sul')  estado = 'MS';
		else if(estado == 'Minas Gerais')        estado = 'MG';
		else if(estado == 'Pará')                estado = 'PA';
		else if(estado == 'Paraíba')             estado = 'PB';
		else if(estado == 'Paraná')              estado = 'PR';
		else if(estado == 'Pernambuco')          estado = 'PE';
		else if(estado == 'Piauí')               estado = 'PI';
		else if(estado == 'Rio de Janeiro')      estado = 'RJ';
		else if(estado == 'Rio Grande do Norte') estado = 'RN';
		else if(estado == 'Rio Grande do Sul')   estado = 'RS';
		else if(estado == 'Rondônia')            estado = 'RO';
		else if(estado == 'Roraima')             estado = 'RR';
		else if(estado == 'Santa Catarina')      estado = 'SC';
		else if(estado == 'São Paulo')           estado = 'SP';
		else if(estado == 'Sergipe')             estado = 'SE';
		else if(estado == 'Tocantins')           estado = 'TO';
		
		return estado;
	}
	
	public pageReference GeraPDF(){
		tem_produtos = true;
		try {
			update fornecedor;
		}
		catch (System.DMLException e){
			ApexPages.addMessages(e);
		}
		
		try {
			update itens_fornecedor;
		}
		catch (System.DMLException e){
			ApexPages.addMessages(e);
		}

		BuscaItensPDF();		
		PreparaErros();
		if(tem_erros)
			return null;
		else{
			tem_produtos = ((itens_fornecedor_cotar.size()>0)?true:false);
			if(!tem_produtos)
				return null;
			else{
                PageReference pagina = new PageReference('/apex/AssistenteCotacaoPDF'+'?id='+fornecedor.id);
				pagina.setAnchor('/apex/AssistenteCotacaoPDF'+'?id='+fornecedor.id);                
                pagina.setRedirect(true);
				return pagina;
			}
		}
	}
	
	public void PreparaErros(){
		tem_erros = ((ApexPages.getMessages().size()>0)?true:false);
        if(tem_erros){
            erros = new List<String>();
            for(Apexpages.Message mensagem: ApexPages.getMessages())
                erros.add(mensagem.getDetail());
        }
	}

}