force-app/main/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Demonstracao__c/Demonstracao__c.object-meta.xml
<CustomObject>
    <label>Comodato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comodatos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Demonstracao__c/fields/CEP__c.field-meta.xml
<CustomField>
    <fullName>CEP__c</fullName>
    <label>CEP</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demonstracao__c/fields/Cidade__c.field-meta.xml
<CustomField>
    <fullName>Cidade__c</fullName>
    <label>Cidade</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demonstracao__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Demonstracoes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demonstracao__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Demonstracoes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demonstracao__c/fields/Departamento__c.field-meta.xml
<CustomField>
    <fullName>Departamento__c</fullName>
    <label>Departamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Departamentos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Faturamento__c/Faturamento__c.object-meta.xml
<CustomObject>
    <label>Faturamento</label>
    <nameField>
        <label>Número</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Faturamentos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Faturamento__c/fields/Departamento3__c.field-meta.xml
<CustomField>
    <fullName>Departamento3__c</fullName>
    <label>Departamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Departamentos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Faturamento__c/fields/Departamento__c.field-meta.xml
<CustomField>
    <fullName>Departamento__c</fullName>
    <formula>TEXT(Pedido__r.Departamento__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Departamento (old)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Faturamento__c/fields/Faturamento_Feito__c.field-meta.xml
<CustomField>
    <fullName>Faturamento_Feito__c</fullName>
    <label>Faturamento Feito (del)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hospcom</fullName>
            </value>
            <value>
                <fullName>Fabricas</fullName>
            </value>
            <value>
                <fullName>Parceiros</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Faturamento__c/fields/Ordem_de_Trabalho__c.field-meta.xml
<CustomField>
    <fullName>Ordem_de_Trabalho__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Se Ordem de Trab.:
- Assistência : Corretiva : Avulso Unitário/Pacote/AddContrato (Serviço)
-*Assistência : Preventiva : Avulso Unitário (Serviço+Peça)
-*Assistência : Metrologia : Avulso Unitário (Serviço)</description>
    <label>Ordem de trabalho</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipName>Faturamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Faturamento__c/fields/Pedido__c.field-meta.xml
<CustomField>
    <fullName>Pedido__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Se Pedido de Oportunidade:
- Comercial Público (Produtos)
- Comercial Privado (Produtos)

Se Pedido de Ordem de Trab.:
- Assistência : Corretiva : Avulso Unitário/Pacote/AddContrato (Peças)</description>
    <label>Pedido</label>
    <referenceTo>Order</referenceTo>
    <relationshipName>Faturamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Condicao_de_pagamento__c.field-meta.xml
<CustomField>
    <fullName>Condicao_de_pagamento__c</fullName>
    <label>Condição de pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Condicoes_de_pagamento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Oportunidades (Contato)</relationshipLabel>
    <relationshipName>Oportunidades2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Departamento__c.field-meta.xml
<CustomField>
    <fullName>Departamento__c</fullName>
    <label>Departamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Departamentos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Forma_de_pagamento2__c.field-meta.xml
<CustomField>
    <fullName>Forma_de_pagamento2__c</fullName>
    <label>Forma de pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Formas_de_pagamento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Comercial.recordType-meta.xml
<RecordType>
    <fullName>Comercial</fullName>
    <active>true</active>
    <businessProcess>Padrão</businessProcess>
    <description>Processo de vendas comercial</description>
    <label>Comercial</label>
</RecordType>

force-app/main/default/objects/Order/fields/Al_quota_Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Al_quota_Vendedor__c</fullName>
    <label>Alíquota Customizada (Vendedor)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Order/fields/Condicao_de_pagamento__c.field-meta.xml
<CustomField>
    <fullName>Condicao_de_pagamento__c</fullName>
    <label>Condição de pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Natureza_de_Opera_o__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Condicoes_de_pagamento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Paciente</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Pedidos (Paciente)</relationshipLabel>
    <relationshipName>Pedidos4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Data_do_Pagamento__c.field-meta.xml
<CustomField>
    <fullName>Data_do_Pagamento__c</fullName>
    <inlineHelpText>Este campo deve ser preenchido apenas quando o pagamento for antecipado.</inlineHelpText>
    <label>Data do Pagamento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Demonstracao__c.field-meta.xml
<CustomField>
    <fullName>Demonstracao__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Comodato</label>
    <referenceTo>Demonstracao__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Departamento__c.field-meta.xml
<CustomField>
    <fullName>Departamento__c</fullName>
    <label>_Departamento (del)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Comercial</fullName>
            </value>
            <value>
                <fullName>Governo</fullName>
            </value>
            <value>
                <fullName>Serviço</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Faturamento_Feito__c.field-meta.xml
<CustomField>
    <fullName>Faturamento_Feito__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Empresa do grupo Hospcom que irá faturar o pedido.</inlineHelpText>
    <label>Faturamento feito</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Faturamentos Feitos (de pedidos)</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Forma_de_pagamento2__c.field-meta.xml
<CustomField>
    <fullName>Forma_de_pagamento2__c</fullName>
    <label>Forma de pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Natureza_de_Opera_o__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Formas_de_pagamento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Frete__c.field-meta.xml
<CustomField>
    <fullName>Frete__c</fullName>
    <label>Tipo de envio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipos_de_envio</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Ordem_de_trabalho__c.field-meta.xml
<CustomField>
    <fullName>Ordem_de_trabalho__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ordem de trabalho</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Status_Permissao__c.field-meta.xml
<CustomField>
    <fullName>Status_Permissao__c</fullName>
    <defaultValue>false</defaultValue>
    <label>_Status Permissão (del)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PedidosVendedor</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Acao_interna__c.field-meta.xml
<CustomField>
    <fullName>Acao_interna__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ação interna</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Cidade__c.field-meta.xml
<CustomField>
    <fullName>Cidade__c</fullName>
    <formula>Order.BillingCity</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cidade</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <formula>Order.Account.CNPJ__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CNPJ</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Ignorar_erros__c.field-meta.xml
<CustomField>
    <fullName>Ignorar_erros__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ignorar erros</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <formula>IF(
    Account.CNPJ__c &lt;&gt; &quot;&quot;, 
    Account.CNPJ__c, 
    IF(
        Account.CPF__pc &lt;&gt; &quot;&quot;, 
        Account.CPF__pc, 
        &quot;&quot;
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CNPJ/CPF</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Condicao_de_pagamento__c.field-meta.xml
<CustomField>
    <fullName>Condicao_de_pagamento__c</fullName>
    <label>Condição de pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Condicoes_de_pagamento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Demonstracao__c.field-meta.xml
<CustomField>
    <fullName>Demonstracao__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Comodato</label>
    <referenceTo>Demonstracao__c</referenceTo>
    <relationshipLabel>Ordens de trabalho</relationshipLabel>
    <relationshipName>Ordens_de_trabalho</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Departamento__c.field-meta.xml
<CustomField>
    <fullName>Departamento__c</fullName>
    <defaultValue>&apos;Serviço&apos;</defaultValue>
    <label>Departamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Departamentos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Faturamento__c.field-meta.xml
<CustomField>
    <fullName>Faturamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Faturamento (Representação)</label>
    <referenceTo>Faturamento__c</referenceTo>
    <relationshipLabel>Ordens de trabalho</relationshipLabel>
    <relationshipName>Ordens_de_trabalho</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Faturamento_Feito__c.field-meta.xml
<CustomField>
    <fullName>Faturamento_Feito__c</fullName>
    <label>Faturamento Feito</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HOSPCOM</fullName>
                <default>true</default>
                <label>HOSPCOM</label>
            </value>
            <value>
                <fullName>GDB</fullName>
            </value>
            <value>
                <fullName>HEALTH SOLUTION</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Forma_de_pagamento2__c.field-meta.xml
<CustomField>
    <fullName>Forma_de_pagamento2__c</fullName>
    <label>Forma de pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Formas_de_pagamento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Frete__c.field-meta.xml
<CustomField>
    <fullName>Frete__c</fullName>
    <label>Frete (old)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CIF</fullName>
            </value>
            <value>
                <fullName>FOB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Departamentos.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Administrativo</fullName>
    </customValue>
    <customValue>
        <fullName>Comercial</fullName>
    </customValue>
    <customValue>
        <fullName>Compras</fullName>
    </customValue>
    <customValue>
        <fullName>Contabilidade</fullName>
        <label>Contabilidade/Fiscal/DP</label>
    </customValue>
    <customValue>
        <fullName>Controladoria</fullName>
    </customValue>
    <customValue>
        <fullName>Desenvolvimento</fullName>
    </customValue>
    <customValue>
        <fullName>Diretoria Administrativa</fullName>
    </customValue>
    <customValue>
        <fullName>Diretoria de B.I e Growth</fullName>
    </customValue>
    <customValue>
        <fullName>Diretoria de Negocios</fullName>
    </customValue>
    <customValue>
        <fullName>Educação</fullName>
        <label>Educação Continuada</label>
    </customValue>
    <customValue>
        <fullName>Faturamento</fullName>
    </customValue>
    <customValue>
        <fullName>Financeiro</fullName>
    </customValue>
    <customValue>
        <fullName>Governo</fullName>
    </customValue>
    <customValue>
        <fullName>Jurídico</fullName>
    </customValue>
    <customValue>
        <fullName>Locação</fullName>
    </customValue>
    <customValue>
        <fullName>Logística</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Operações</fullName>
    </customValue>
    <customValue>
        <fullName>Outros</fullName>
    </customValue>
    <customValue>
        <fullName>Qualidade</fullName>
    </customValue>
    <customValue>
        <fullName>RH</fullName>
    </customValue>
    <customValue>
        <fullName>Serviço</fullName>
    </customValue>
    <customValue>
        <fullName>Departamento Pessoal</fullName>
        <isActive>false</isActive>
        <label>Departamento Pessoal</label>
    </customValue>
    <customValue>
        <fullName>Facilites</fullName>
        <isActive>false</isActive>
        <label>Facilites</label>
    </customValue>
    <customValue>
        <fullName>T.I.</fullName>
        <isActive>false</isActive>
        <label>T.I.</label>
    </customValue>
    <customValue>
        <fullName>OPME</fullName>
        <isActive>false</isActive>
        <label>OPME</label>
    </customValue>
    <customValue>
        <fullName>Manutenção</fullName>
        <isActive>false</isActive>
        <label>Manutenção</label>
    </customValue>
    <customValue>
        <fullName>Limpeza</fullName>
        <isActive>false</isActive>
        <label>Limpeza</label>
    </customValue>
    <customValue>
        <fullName>Fiscal</fullName>
        <isActive>false</isActive>
        <label>Fiscal</label>
    </customValue>
    <masterLabel>Departamentos</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/Tipos_de_envio.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Contratação do Frete por conta do Remetente (CIF)</fullName>
    </customValue>
    <customValue>
        <fullName>Contratação do Frete por conta do Destinatário (FOB)</fullName>
    </customValue>
    <customValue>
        <fullName>Contratação do Frete por conta de Terceiros</fullName>
    </customValue>
    <customValue>
        <fullName>Transporte Próprio por conta do Remetente</fullName>
    </customValue>
    <customValue>
        <fullName>Transporte Próprio por conta do Destinatário</fullName>
    </customValue>
    <customValue>
        <fullName>Sem Ocorrência de Transporte.</fullName>
    </customValue>
    <masterLabel>Tipos de envio</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SAPOrderIntegrationTEST.cls
@isTest(seeAllData=true)
public class SAPOrderIntegrationTEST {
	@isTest(seeAllData=true)
    private static void SAPOrderIntegration_TEST(){
        Test.startTest();

        Account a = new Account();
        a.Name = 'Teste';
        a.CNPJ__c = '51.461.458/0001-89';
        insert a;
       
        User u = new User();
        u.Username = '3e9100ffb8461f574a998f849d86dd7d@t.com';
        u.LastName = 'Teste';
        u.Email = 'e4e36da98f5950735b5e89c708544947@t.com';
        u.Alias = 'Teste';
        u.TimeZoneSidKey = 'GMT';
        u.LocaleSidKey = 'pt_BR';
        u.EmailEncodingKey = 'UTF-8';
        u.ProfileId = '00e6e000002JPriAAG'; 
        u.LanguageLocaleKey = 'pt_BR';
        u.Ignorar_erros__c = true;
        insert u;

		Contact c = new Contact();
        c.FirstName = 'TESTE';
        c.LastName = 'TESTE';
		insert c;        

        //Demonstracao__c d = new Demonstracao__c();
        //d.Conta__c = a.Id;
        //d.CEP__c = '77000-000';
        //d.Cidade__c = 'TESTE';
        //d.Contato__c = c.Id;
        //d.Departamento__c = 'Comercial';
        //insert d;
        
        Opportunity opp = new Opportunity();
        opp.Name = 'TESTE';
        opp.StageName = 'WIN';
        opp.CloseDate = Date.newInstance(2022,10,17);
        //opp.OwnerId = u.Id;
        insert opp;
        
		WorkOrder wo = new WorkOrder();
        wo.AccountId = a.Id;
		insert wo;
                
		//Order o = new Order();
		//o.RecordTypeId = '0126e000001YbEaAAK';
        //o.Status = 'Aprovado';
        //o.Name = 'Teste';
        //o.AccountId = a.Id;
        //o.Faturamento_Feito__c = a.Id;
        //o.Condicao_de_pagamento__c = 'À vista - Paga e Retira';
        //o.Forma_de_pagamento2__c = 'Recebimento via Transferência Bancária';
        //o.Frete__c = 'Contratação do Frete por conta do Remetente (CIF)';
        //o.Vendedor__c = u.Id;
        //o.Demonstracao__c = d.Id;
        //o.EffectiveDate = Date.newInstance(2022,08,17);
        //o.OwnerId = u.Id;
		//insert o;
        
        //Faturamento__c f = new Faturamento__c();
        //f.Pedido__c = o.Id;
        //insert f;

		Order o2 = new Order();
		o2.RecordTypeId = '0126e000001YbEaAAK';
        o2.Status = 'Aprovado';
        o2.Name = 'Teste';
        o2.AccountId = a.Id;
        o2.Faturamento_Feito__c = a.Id;
        o2.Condicao_de_pagamento__c = 'À vista - Paga e Retira';
        o2.Forma_de_pagamento2__c = 'Recebimento via Transferência Bancária';
        o2.Frete__c = 'Contratação do Frete por conta do Remetente (CIF)';
        o2.Vendedor__c = u.Id;
        o2.OpportunityId = opp.Id;
        o2.EffectiveDate = Date.newInstance(2023,08,17);
		insert o2;
        
		Order o3 = new Order();
		o3.RecordTypeId = '0126e000001YbEaAAK';
        o3.Status = 'Aprovado';
        o3.Name = 'Teste';
        o3.AccountId = a.Id;
        o3.Faturamento_Feito__c = a.Id;
        o3.Condicao_de_pagamento__c = 'À vista - Paga e Retira';
        o3.Forma_de_pagamento2__c = 'Recebimento via Transferência Bancária';
        o3.Frete__c = 'Contratação do Frete por conta do Remetente (CIF)';
        o3.Vendedor__c = u.Id;
        o3.Ordem_de_trabalho__c = wo.Id;
        o3.EffectiveDate = Date.newInstance(2023,08,17);
		//o3.OrderNumber = '00014857';
        insert o3;
        
        o3.Acao_interna__c = true;
        update o3;

        System.debug(o3.Name);
        
        Test.stopTest();
        

//        o.Name = 'Teste1';
//        update o;

//        Order o = new Order();
//        o.AccountId = '00175000007dYHKAA2';
//        o.Status_Permissao__c = false;
//        o.Al_quota_Vendedor__c = 1;
//        o.Acao_interna__c = false;
//        o.Pricebook2Id = '01si0000000I7SxAAK';
//        o.Condicao_de_pagamento__c = 'À Vista - Antecipado';
//        o.EffectiveDate = Date.newInstance(2022,03,19);
//        o.Data_do_Pagamento__c = Date.newInstance(2022,03,22);
//        o.Departamento3__c = 'Comercial';
//        o.Entrega_parcial__c = 'Autorizada';
//        o.Faturamento_Feito__c = '00175000007dYHKAA2';
//        o.Forma_de_pagamento2__c = 'Recebimento em Dinheiro';
//        o.CurrencyIsoCode = 'BRL';
//        o.Natureza_de_Opera_o__c = 'VENDA';
//        o.Necess_rio_Treinamento__c = 'NÃO';
//        o.AccountId = '00175000007dYHKAA2';
//        o.Nome_do_Pagador__c = 'Alvares Al';
//        o.Observacoes_Gerais__c = 'teste';
//        o.IsReductionOrder = false;
//        o.Per_odo_do_contrato_Fim__c = Date.newInstance(2022,03,31);
//        o.Periodo_do_contrato_inicio__c = Date.newInstance(2022,03,31);
//        o.Pesq_Satisfacao_Enviada__c = false;
//        o.Prazo_de_entrega__c = Date.newInstance(2022,03,17);
//        o.OwnerId = '00531000006UzZsAAK';
//        o.Status = 'Rascunho';
//        o.Frete__c = 'Contratação do Frete por conta do Remetente (CIF)';
//        o.RecordTypeId = '0126e000001YbEaAAK';
//        o.Total_Faturado__c = 0;
//        o.Valor_Recebido__c = 54.6;
//        o.Vendedor__c = '00531000006UzZsAAK';
//        insert o;

//        Product2 p = new Product2(Name='Teste',ProductCode='234234');
//        insert p;
        
//		OrderItem oi = new OrderItem(UnitPrice=5,Quantity=10, Status__c='Novo',	OrderId=o.Id);
//		insert oi;
        
//        o.Observacoes_Gerais__c = 'não teste';
//        update o;
        
    }    
}