force-app/main/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Raz_o_Social__c.field-meta.xml
<CustomField>
    <fullName>Raz_o_Social__c</fullName>
    <label>Razão social</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Cidade__c.field-meta.xml
<CustomField>
    <fullName>Cidade__c</fullName>
    <formula>Account.BillingCity</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cidade</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <formula>Account.BillingState</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Estado</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>-</fullName>
            </value>
            <value>
                <fullName>3M</fullName>
            </value>
            <value>
                <fullName>ABX</fullName>
            </value>
            <value>
                <fullName>AGFA</fullName>
            </value>
            <value>
                <fullName>AINCA</fullName>
            </value>
            <value>
                <fullName>AIR LIQUIDE</fullName>
            </value>
            <value>
                <fullName>AIRSEP</fullName>
            </value>
            <value>
                <fullName>AIR SHIELD</fullName>
            </value>
            <value>
                <fullName>AKTILITE</fullName>
            </value>
            <value>
                <fullName>ALERON</fullName>
            </value>
            <value>
                <fullName>ALOHA MED</fullName>
            </value>
            <value>
                <fullName>ALPHA MED</fullName>
            </value>
            <value>
                <fullName>AMCOR</fullName>
            </value>
            <value>
                <fullName>ANGIOTECH</fullName>
            </value>
            <value>
                <fullName>AOC</fullName>
            </value>
            <value>
                <fullName>APRAMED</fullName>
            </value>
            <value>
                <fullName>ARJO</fullName>
            </value>
            <value>
                <fullName>ARTHREX</fullName>
            </value>
            <value>
                <fullName>ASCLEPIOS</fullName>
            </value>
            <value>
                <fullName>ASPIRAMAX</fullName>
            </value>
            <value>
                <fullName>AUTOM</fullName>
            </value>
            <value>
                <fullName>BALMAK</fullName>
            </value>
            <value>
                <fullName>BARBI</fullName>
            </value>
            <value>
                <fullName>BAUMER</fullName>
            </value>
            <value>
                <fullName>BAXTER</fullName>
            </value>
            <value>
                <fullName>BBRAUN</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>BEACON</fullName>
            </value>
            <value>
                <fullName>BELTEC</fullName>
            </value>
            <value>
                <fullName>BENFER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/URL_da_Imagem__c.field-meta.xml
<CustomField>
    <fullName>URL_da_Imagem__c</fullName>
    <label>URL da Imagem</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Valor_Total__c.field-meta.xml
<CustomField>
    <fullName>Valor_Total__c</fullName>
    <formula>Quantity  *  Price</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valor Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <label>CPF</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dados_colaborador__c/Dados_colaborador__c.object-meta.xml
<CustomObject>
    <label>Dados colaborador</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Nº</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dados colaboradores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dados_colaborador__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Dados colaboradores</relationshipLabel>
    <relationshipName>Dados_colaboradores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demonstracao__c/Demonstracao__c.object-meta.xml
<CustomObject>
    <label>Comodato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comodatos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Demonstracao__c/fields/CEP__c.field-meta.xml
<CustomField>
    <fullName>CEP__c</fullName>
    <label>CEP</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demonstracao__c/fields/Cidade__c.field-meta.xml
<CustomField>
    <fullName>Cidade__c</fullName>
    <label>Cidade</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demonstracao__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Demonstracoes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demonstracao__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contato</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Demonstracoes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demonstracao__c/fields/Data_prevista__c.field-meta.xml
<CustomField>
    <fullName>Data_prevista__c</fullName>
    <label>Data Inicial</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Demonstracao__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <label>Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Estados</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Demonstracao__c/fields/Fornecedor__c.field-meta.xml
<CustomField>
    <fullName>Fornecedor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Fornecedor</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Demonstracoes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demonstracao__c/fields/Rua__c.field-meta.xml
<CustomField>
    <fullName>Rua__c</fullName>
    <label>Rua</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Demonstracao__c/fields/Tempo_de_demonstracao__c.field-meta.xml
<CustomField>
    <fullName>Tempo_de_demonstracao__c</fullName>
    <label>Tempo de demonstração</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demonstracao__c/fields/Testemunha__c.field-meta.xml
<CustomField>
    <fullName>Testemunha__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Testemunha</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Comodatos (Testemunha)</relationshipLabel>
    <relationshipName>Comodatos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demonstracao__c/fields/Valor_total__c.field-meta.xml
<CustomField>
    <fullName>Valor_total__c</fullName>
    <label>Valor total</label>
    <summarizedField>Produto_da_demonstracao__c.Valor__c</summarizedField>
    <summaryForeignKey>Produto_da_demonstracao__c.Demonstracao__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Demonstracao__c/recordTypes/Demonstracao.recordType-meta.xml
<RecordType>
    <fullName>Demonstracao</fullName>
    <active>false</active>
    <description>Para contratos de demonstração</description>
    <label>Demonstração</label>
</RecordType>

force-app/main/default/objects/Order/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Paciente</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Pedidos (Paciente)</relationshipLabel>
    <relationshipName>Pedidos4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Demonstracao__c.field-meta.xml
<CustomField>
    <fullName>Demonstracao__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Comodato</label>
    <referenceTo>Demonstracao__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Raz_o_Social__c.field-meta.xml
<CustomField>
    <fullName>Raz_o_Social__c</fullName>
    <formula>Account.Raz_o_Social__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>_Razão Social (del)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Tempo_de_demonstracao__c.field-meta.xml
<CustomField>
    <fullName>Tempo_de_demonstracao__c</fullName>
    <label>Tempo de demonstração</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Testemunha__c.field-meta.xml
<CustomField>
    <fullName>Testemunha__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Testemunha</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/recordTypes/Demonstracao.recordType-meta.xml
<RecordType>
    <fullName>Demonstracao</fullName>
    <active>true</active>
    <description>Exclusivo para pedidos de demonstração</description>
    <label>Demonstração</label>
</RecordType>

force-app/main/default/objects/Product2/fields/Fornecedor__c.field-meta.xml
<CustomField>
    <fullName>Fornecedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fornecedor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Produtos</relationshipLabel>
    <relationshipName>Produtos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Modelo__c.field-meta.xml
<CustomField>
    <fullName>Modelo__c</fullName>
    <label>Modelo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/URL_da_Imagem__c.field-meta.xml
<CustomField>
    <fullName>URL_da_Imagem__c</fullName>
    <defaultValue>&quot;https://hospcom.my.site.com/servlet/servlet.ImageServer?id=015310000080hog&amp;oid=00Di0000000JVhH&amp;lastMod=1502888568000&quot;</defaultValue>
    <label>URL da Imagem</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Valor_de_Venda__c.field-meta.xml
<CustomField>
    <fullName>Valor_de_Venda__c</fullName>
    <label>Valor de Venda</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Valor_Total__c.field-meta.xml
<CustomField>
    <fullName>Valor_Total__c</fullName>
    <formula>Valor_de_Venda__c +  Valor_dos_Acessorios__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valor Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Produto_da_demonstracao__c/Produto_da_demonstracao__c.object-meta.xml
<CustomObject>
    <label>Ativo do comodato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ativos do comodato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Produto_da_demonstracao__c/fields/Ativo__c.field-meta.xml
<CustomField>
    <fullName>Ativo__c</fullName>
    <label>Ativo</label>
    <referenceTo>Asset</referenceTo>
    <relationshipName>Produtos_da_demonstracao</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Produto_da_demonstracao__c/fields/Demonstracao__c.field-meta.xml
<CustomField>
    <fullName>Demonstracao__c</fullName>
    <label>Comodato</label>
    <referenceTo>Demonstracao__c</referenceTo>
    <relationshipName>Produtos_da_demonstracao</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Estados.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Acre</fullName>
    </customValue>
    <customValue>
        <fullName>Alagoas</fullName>
    </customValue>
    <customValue>
        <fullName>Amapá</fullName>
    </customValue>
    <customValue>
        <fullName>Amazonas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahia</fullName>
    </customValue>
    <customValue>
        <fullName>Ceará</fullName>
    </customValue>
    <customValue>
        <fullName>Distrito Federal</fullName>
    </customValue>
    <customValue>
        <fullName>Espírito Santo</fullName>
    </customValue>
    <customValue>
        <fullName>Geral</fullName>
    </customValue>
    <customValue>
        <fullName>Goiás</fullName>
    </customValue>
    <customValue>
        <fullName>Maranhão</fullName>
    </customValue>
    <customValue>
        <fullName>Mato Grosso</fullName>
    </customValue>
    <customValue>
        <fullName>Mato Grosso do Sul</fullName>
    </customValue>
    <customValue>
        <fullName>Minas Gerais</fullName>
    </customValue>
    <customValue>
        <fullName>Pará</fullName>
    </customValue>
    <customValue>
        <fullName>Paraíba</fullName>
    </customValue>
    <customValue>
        <fullName>Paraná</fullName>
    </customValue>
    <customValue>
        <fullName>Pernambuco</fullName>
    </customValue>
    <customValue>
        <fullName>Piauí</fullName>
    </customValue>
    <customValue>
        <fullName>Rio de Janeiro</fullName>
    </customValue>
    <customValue>
        <fullName>Rio Grande do Norte</fullName>
    </customValue>
    <customValue>
        <fullName>Rio Grande do Sul</fullName>
    </customValue>
    <customValue>
        <fullName>Rondônia</fullName>
    </customValue>
    <customValue>
        <fullName>Roraima</fullName>
    </customValue>
    <customValue>
        <fullName>Santa Catarina</fullName>
    </customValue>
    <customValue>
        <fullName>São Paulo</fullName>
    </customValue>
    <customValue>
        <fullName>Sergipe</fullName>
    </customValue>
    <customValue>
        <fullName>Tocantins</fullName>
    </customValue>
    <customValue>
        <fullName>Exterior</fullName>
    </customValue>
    <masterLabel>Estados</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DemonstracaoContrato.cls
public class DemonstracaoContrato {
    
    public Documento documento {get;set;}
    public Demonstracao__c demonstracao {get;set;}
    public List<Produto> produtos {get;set;}
    public string cpfTestemunha {get;set;}
    
    public DemonstracaoContrato(ApexPages.StandardController controlador){
        
        
        // demonstração
        demonstracao = [
            SELECT  Conta__r.RecordType.Name, Conta__r.Raz_o_Social__c, Conta__r.Name, Conta__r.CNPJ__c, Conta__r.CPF__pc, 
            Data_prevista__c, Tempo_de_demonstracao__c, Fornecedor__r.Raz_o_Social__c, Testemunha__r.CPF__c, Testemunha__r.AccountId, Testemunha__c,
            Fornecedor__r.CNPJ__c, Fornecedor__r.BillingCity, Valor_total__c, Rua__c, Cidade__c, Estado__c, CEP__c, 
            CurrencyISOCode
            FROM    Demonstracao__c
            WHERE   Id = :((SObject)controlador.getRecord()).Id
        ];
        demonstracao.Fornecedor__r.BillingCity = demonstracao.Fornecedor__r.BillingCity.toLowerCase().Capitalize();
        demonstracao.Estado__c = Util.ConverterEstado(demonstracao.Estado__c, 'sigla');
        
        if(demonstracao.Testemunha__r.CPF__c != ''){
            cpfTestemunha = demonstracao.Testemunha__r.CPF__c;
        }
        else{
            Dados_colaborador__c dados = [SELECT ID, CPF__c FROM Dados_colaborador__c WHERE Contato__c = :demonstracao.Testemunha__c LIMIT 1];
            cpfTestemunha = dados.CPF__c;
        }
        
        
        // itens
        List<Produto_da_demonstracao__c> itens = [
            SELECT  Ativo__r.Product2.URL_da_Imagem__c, Ativo__r.Product2.StockKeepingUnit, Ativo__r.Product2.Name, Ativo__r.Product2.Modelo__c, Ativo__r.Product2.Valor_de_venda__c,
            Ativo__r.Product2.Marca__c, Ativo__r.SerialNumber, Valor__c, Item__c, Item_Pai__c, Descricao__c
            FROM    Produto_da_Demonstracao__c
            WHERE   Demonstracao__c = :((SObject)controlador.getRecord()).Id
            ORDER BY Item__c ASC NULLS LAST
        ];
        
        List<Produto_da_demonstracao__c> itens_ordem = new List<Produto_da_Demonstracao__c>();
        for(Produto_da_Demonstracao__c item_equip : itens)
            if(item_equip.Item__c!=null && item_equip.Item_Pai__c==null){
                itens_ordem.add(item_equip);
                for(Produto_da_Demonstracao__c item_acess : itens)
                    if(item_acess.Item_Pai__c==item_equip.Item__c)
                    itens_ordem.add(item_acess);
            }
        for(Produto_da_Demonstracao__c item_vazio : itens)
            if(item_vazio.Item__c==null && item_vazio.Item_Pai__c==null)
            itens_ordem.add(item_vazio);
        
        produtos = new List<Produto>();
        Decimal subtotal = 0;
        for(Integer cont=0; cont<itens_ordem.size(); cont++){
            Produto produto = new Produto(itens_ordem[cont]);
            subtotal += itens_ordem[cont].Valor__c;
            
            String anterior = (cont==0?null:(itens_ordem[cont-1].Item_Pai__c==null?'equipamento':'acessorio'));
            String atual = (itens_ordem[cont].Item_Pai__c==null?'equipamento':'acessorio');
            String proximo = (cont==itens_ordem.size()-1?null:(itens_ordem[cont+1].Item_Pai__c==null?'equipamento':'acessorio'));
            
            if((atual=='equipamento'&& proximo=='acessorio') || ((anterior==null||anterior=='acessorio') && (atual=='equipamento' && (proximo=='equipamento'||proximo==null))))
                produto.cabecalho = true;
            if((anterior=='equipamento'||anterior=='acessorio') && atual=='acessorio' && (proximo=='equipamento'||proximo==null)){
                produto.subtotal = demonstracao.CurrencyISOCode+' '+String.valueOf(subtotal.format());
                if(!produto.subtotal.contains(',')) produto.subtotal += ',00';
                else if(produto.subtotal.substringAfter(',').length()==1) produto.subtotal += '0';
                subtotal = 0;
            }
            
            produtos.add(produto);
        }
        
        // documento
        documento = new Documento();
        if(demonstracao.Fornecedor__r.CNPJ__c == '27.476.124/0001-02')
            documento.timbrado = PageReference.forResource('TimbradoHealth').getUrl();
        else if(demonstracao.Fornecedor__r.CNPJ__c == '23.813.386/0001-56')
            documento.timbrado = PageReference.forResource('TimbradoGDB').getUrl();
        else
            documento.timbrado = PageReference.forResource('TimbradoHospcom').getUrl();     
        
        
    }
    
    public class Produto{
        public Boolean cabecalho{get;set;}
        public Produto_da_demonstracao__c item{get;set;}
        public String subtotal{get;set;}
        
        public Produto(Produto_da_demonstracao__c item){
            this.cabecalho = false;
            this.item = item;
            this.subtotal = null;
        }
    }
    
    public class Documento{
        public String timbrado{get;set;}
        public String data_atual{get;set;}
        public Date data_termino{get;set;}
        
        public Documento(){
            String  dia = String.valueOf((System.Now()).Day()), 
                mes = String.valueOf((System.Now()).Month()), 
                ano = String.valueOf((System.Now()).Year());
            if(mes == '1') mes = 'Janeiro';
            else if(mes == '2') mes = 'Fevereiro';
            else if(mes == '3') mes = 'Março';
            else if(mes == '4') mes = 'Abril';
            else if(mes == '5') mes = 'Maio';
            else if(mes == '6') mes = 'Junho';
            else if(mes == '7') mes = 'Julho';
            else if(mes == '8') mes = 'Agosto';
            else if(mes == '9') mes = 'Setembro';
            else if(mes == '10') mes = 'Outubro';
            else if(mes == '11') mes = 'Novembro';
            else if(mes == '12') mes = 'Dezembro';
            
            this.data_atual = dia + ' de ' + mes + ' de ' + ano;
        }
    }
    
}