force-app/main/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Raz_o_Social__c.field-meta.xml
<CustomField>
    <fullName>Raz_o_Social__c</fullName>
    <label>Razão social</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Gest_o_de_Documentos__c/Gest_o_de_Documentos__c.object-meta.xml
<CustomObject>
    <description>Objeto destinado ao controle da qualidade quanto a revisão e renovação dos documenos</description>
    <label>Gestão de Documento</label>
    <nameField>
        <displayFormat>GD - {0000}</displayFormat>
        <label>Nome de Gestão de Documentos</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gestão de Documentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order/fields/Faturamento_Feito__c.field-meta.xml
<CustomField>
    <fullName>Faturamento_Feito__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Empresa do grupo Hospcom que irá faturar o pedido.</inlineHelpText>
    <label>Faturamento feito</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Faturamentos Feitos (de pedidos)</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Participantes__c.field-meta.xml
<CustomField>
    <fullName>Participantes__c</fullName>
    <defaultValue>10</defaultValue>
    <label>Participantes</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Raz_o_Social__c.field-meta.xml
<CustomField>
    <fullName>Raz_o_Social__c</fullName>
    <formula>Account.Raz_o_Social__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>_Razão Social (del)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/recordTypes/Demonstracao.recordType-meta.xml
<RecordType>
    <fullName>Demonstracao</fullName>
    <active>true</active>
    <description>Exclusivo para pedidos de demonstração</description>
    <label>Demonstração</label>
</RecordType>

force-app/main/default/objects/OrderItem/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <formula>Order.Account.CNPJ__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CNPJ</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Descricao_da_linha__c.field-meta.xml
<CustomField>
    <fullName>Descricao_da_linha__c</fullName>
    <label>Descrição da linha</label>
    <length>16000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Item_Pai__c.field-meta.xml
<CustomField>
    <fullName>Item_Pai__c</fullName>
    <label>Item Pai</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <formula>TEXT(PricebookEntry.Product2.Marca__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Marca</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Modelo__c.field-meta.xml
<CustomField>
    <fullName>Modelo__c</fullName>
    <formula>PricebookEntry.Modelo__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Modelo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>3GREEN</fullName>
            </value>
            <value>
                <fullName>7LIVES</fullName>
            </value>
            <value>
                <fullName>ABC</fullName>
            </value>
            <value>
                <fullName>ACCUMED</fullName>
            </value>
            <value>
                <fullName>ACROSS</fullName>
            </value>
            <value>
                <fullName>ACTE</fullName>
            </value>
            <value>
                <fullName>AEROGEN</fullName>
            </value>
            <value>
                <fullName>AGATA</fullName>
            </value>
            <value>
                <fullName>AGILE MED</fullName>
            </value>
            <value>
                <fullName>AIR LIQUIDE</fullName>
            </value>
            <value>
                <fullName>AIR SHIELD</fullName>
            </value>
            <value>
                <fullName>AJEL</fullName>
            </value>
            <value>
                <fullName>ALBAN</fullName>
            </value>
            <value>
                <fullName>ALIVE HEART</fullName>
            </value>
            <value>
                <fullName>ALLIAGE</fullName>
            </value>
            <value>
                <fullName>ALPHARAD</fullName>
            </value>
            <value>
                <fullName>ALVFLOR</fullName>
            </value>
            <value>
                <fullName>ALVIMÉDICA</fullName>
            </value>
            <value>
                <fullName>ANALYSER</fullName>
            </value>
            <value>
                <fullName>ANATONIC</fullName>
            </value>
            <value>
                <fullName>ANESTHESIA</fullName>
            </value>
            <value>
                <fullName>AOC</fullName>
            </value>
            <value>
                <fullName>APC</fullName>
            </value>
            <value>
                <fullName>APK</fullName>
            </value>
            <value>
                <fullName>APPLE</fullName>
            </value>
            <value>
                <fullName>ARJO</fullName>
            </value>
            <value>
                <fullName>ARJOHUNTLEIGH</fullName>
            </value>
            <value>
                <fullName>ARKTUS</fullName>
            </value>
            <value>
                <fullName>ARTIS</fullName>
            </value>
            <value>
                <fullName>ARTROCORP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Modelo__c.field-meta.xml
<CustomField>
    <fullName>Modelo__c</fullName>
    <label>Modelo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/URL_da_Imagem__c.field-meta.xml
<CustomField>
    <fullName>URL_da_Imagem__c</fullName>
    <defaultValue>&quot;https://hospcom.my.site.com/servlet/servlet.ImageServer?id=015310000080hog&amp;oid=00Di0000000JVhH&amp;lastMod=1502888568000&quot;</defaultValue>
    <label>URL da Imagem</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/DemonstracaoRegistro2.cls
public class DemonstracaoRegistro2 {
	
	public Documento documento {get;set;}
	public Order demonstracao {get;set;}
	public List<Produto> produtos {get;set;}
	public Integer qtd {get;set;}
	public List<String> qtd_linhas {get;set;}
    public List<Gest_o_de_Documentos__c> documentos { get; set; }
	
	public DemonstracaoRegistro2(ApexPages.StandardController controlador){
        // demonstração
		demonstracao = [
			SELECT	Name, Account.RecordType.Name, Account.Raz_o_Social__c, Account.Name, Account.CNPJ__c, Account.CPF__pc, 
					Faturamento_feito__r.CNPJ__c, CurrencyISOCode, Participantes__c
			FROM	Order
			WHERE	Id = :((SObject)controlador.getRecord()).Id
		];
        
        
		documentos = GestaoDocumentos.obterDocumentosVigentes();
        
		if(Test.isRunningTest())
			qtd = 1;
		else 
            qtd = demonstracao.Participantes__c.intValue();
		qtd_linhas = new List<String>();
		for(Integer cont=1; cont<=qtd; cont++)
			qtd_linhas.add(String.valueOf(cont));
				
		
		// itens
		List<OrderItem> itens = [
			SELECT	Product2.URL_da_Imagem__c, Product2.StockKeepingUnit, Product2.Name, Product2.Modelo__c, 
					Product2.Marca__c, Description, TotalPrice, Item__c, Item_Pai__c, Descricao_da_linha__c
			FROM	OrderItem
			WHERE	OrderId = :((SObject)controlador.getRecord()).Id
			ORDER BY Item__c ASC NULLS LAST
		];
		
		List<OrderItem> itens_ordem = new List<OrderItem>();
		for(OrderItem item_equip : itens)
			if(item_equip.Item__c!=null && item_equip.Item_Pai__c==null){
				itens_ordem.add(item_equip);
				for(OrderItem item_acess : itens)
					if(item_acess.Item_Pai__c==item_equip.Item__c)
						itens_ordem.add(item_acess);
			}
		for(OrderItem item_vazio : itens)
			if(item_vazio.Item__c==null && item_vazio.Item_Pai__c==null)
				itens_ordem.add(item_vazio);
		
		produtos = new List<Produto>();
		Decimal subtotal = 0;
		for(Integer cont=0; cont<itens_ordem.size(); cont++){
			Produto produto = new Produto(itens_ordem[cont]);
			subtotal += itens_ordem[cont].TotalPrice;
			
			String anterior = (cont==0?null:(itens_ordem[cont-1].Item_Pai__c==null?'equipamento':'acessorio'));
			String atual = (itens_ordem[cont].Item_Pai__c==null?'equipamento':'acessorio');
			String proximo = (cont==itens_ordem.size()-1?null:(itens_ordem[cont+1].Item_Pai__c==null?'equipamento':'acessorio'));
			
			// if((atual=='equipamento'&& proximo=='acessorio') || ((anterior==null||anterior=='acessorio') && (atual=='equipamento' && (proximo=='equipamento'||proximo==null))))
			if(anterior==null)
				produto.cabecalho = true;
			if((anterior=='equipamento'||anterior=='acessorio') && atual=='acessorio' && (proximo=='equipamento'||proximo==null)){
				produto.subtotal = demonstracao.CurrencyISOCode+' '+String.valueOf(subtotal.format());
				if(!produto.subtotal.contains(',')) produto.subtotal += ',00';
				else if(produto.subtotal.substringAfter(',').length()==1) produto.subtotal += '0';
				subtotal = 0;
			}
			
			produtos.add(produto);
		}
		
		// documento
		documento = new Documento();
		if(demonstracao.Faturamento_feito__r.CNPJ__c == '27.476.124/0001-02')
			documento.timbrado = PageReference.forResource('TimbradoHealth').getUrl();
		else if(demonstracao.Faturamento_feito__r.CNPJ__c == '23.813.386/0001-56')
			documento.timbrado = PageReference.forResource('TimbradoGDB').getUrl();
		else
			documento.timbrado = PageReference.forResource('TimbradoHospcom').getUrl();	
	}
	
	public class Produto{
		public Boolean cabecalho{get;set;}
		public OrderItem item{get;set;}
		public String subtotal{get;set;}
		
		public Produto(OrderItem item){
			this.cabecalho = false;
			this.item = item;
			this.subtotal = null;
		}
	}
    
	public class Documento{
		public String timbrado{get;set;}
		
		public Documento(){}
	}
    
}