force-app/main/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/Contrato_de_Servi_o__c.object-meta.xml
<CustomObject>
    <label>Contrato de Serviço</label>
    <nameField>
        <label>Nome do Contrato</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contratos de Serviços</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Contato_do_Locat_rio__c.field-meta.xml
<CustomField>
    <fullName>Contato_do_Locat_rio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contato do Locatário</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contratos de Serviços</relationshipLabel>
    <relationshipName>Contratos_de_Servi_os</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Forma_de_pagamento2__c.field-meta.xml
<CustomField>
    <fullName>Forma_de_pagamento2__c</fullName>
    <label>Forma de pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Formas_de_pagamento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Forma_de_Pagamento__c.field-meta.xml
<CustomField>
    <fullName>Forma_de_Pagamento__c</fullName>
    <label>Forma de Pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A VISTA</fullName>
            </value>
            <value>
                <fullName>BOLETO</fullName>
            </value>
            <value>
                <fullName>DEPÓSITO BANCÁRIO</fullName>
            </value>
            <value>
                <fullName>DEPÓSITO BANCÁRIO ANTECIPADO</fullName>
            </value>
            <value>
                <fullName>CARTÃO CRÉDITO/DÉBITO 1X</fullName>
            </value>
            <value>
                <fullName>CARTÃO CRÉDITO/DÉBITO 2X</fullName>
            </value>
            <value>
                <fullName>CARTÃO CRÉDITO/DÉBITO 3X</fullName>
            </value>
            <value>
                <fullName>CARTÃO CRÉDITO/DÉBITO 4X</fullName>
            </value>
            <value>
                <fullName>CARTÃO CRÉDITO/DÉBITO 5X</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Condicao_de_pagamento__c.field-meta.xml
<CustomField>
    <fullName>Condicao_de_pagamento__c</fullName>
    <label>Condição de pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Condicoes_de_pagamento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Forma_de_pagamento2__c.field-meta.xml
<CustomField>
    <fullName>Forma_de_pagamento2__c</fullName>
    <label>Forma de pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Formas_de_pagamento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Condicao_de_pagamento__c.field-meta.xml
<CustomField>
    <fullName>Condicao_de_pagamento__c</fullName>
    <label>Condição de pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Natureza_de_Opera_o__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Condicoes_de_pagamento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Contrato_de_Servi_o__c.field-meta.xml
<CustomField>
    <fullName>Contrato_de_Servi_o__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato de Serviço</label>
    <referenceTo>Contrato_de_Servi_o__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/E_mail_Contato__c.field-meta.xml
<CustomField>
    <fullName>E_mail_Contato__c</fullName>
    <label>E-mail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Order/fields/Faturamento_Feito__c.field-meta.xml
<CustomField>
    <fullName>Faturamento_Feito__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Empresa do grupo Hospcom que irá faturar o pedido.</inlineHelpText>
    <label>Faturamento feito</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Faturamentos Feitos (de pedidos)</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Forma_de_pagamento2__c.field-meta.xml
<CustomField>
    <fullName>Forma_de_pagamento2__c</fullName>
    <label>Forma de pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Natureza_de_Opera_o__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Formas_de_pagamento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Forma_de_pagamento__c.field-meta.xml
<CustomField>
    <fullName>Forma_de_pagamento__c</fullName>
    <label>_Forma de pagamento (del)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A VISTA NO PEDIDO</fullName>
            </value>
            <value>
                <fullName>A VISTA CONTRA EMBARQUE</fullName>
            </value>
            <value>
                <fullName>FINANCIAMENTO BANCÁRIO</fullName>
            </value>
            <value>
                <fullName>OPEN ACCOUNT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Ignora_validacao__c.field-meta.xml
<CustomField>
    <fullName>Ignora_validacao__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ignora validação</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Natureza_de_Opera_o__c.field-meta.xml
<CustomField>
    <fullName>Natureza_de_Opera_o__c</fullName>
    <label>Natureza de Operação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BONIFICAÇÃO</fullName>
            </value>
            <value>
                <fullName>DEMONSTRAÇÃO</fullName>
            </value>
            <value>
                <fullName>LOCAÇÃO</fullName>
            </value>
            <value>
                <fullName>EMPRÉSTIMO</fullName>
            </value>
            <value>
                <fullName>REMESSA DE LOCAÇÃO</fullName>
            </value>
            <value>
                <fullName>REMESSA DE TROCA</fullName>
            </value>
            <value>
                <fullName>REMESSA EM CONSIGNAÇÃO</fullName>
            </value>
            <value>
                <fullName>SERVIÇO</fullName>
            </value>
            <value>
                <fullName>VENDA</fullName>
            </value>
            <value>
                <fullName>VENDA DA CONSIGNAÇÃO</fullName>
            </value>
            <value>
                <fullName>RETORNO DE LOCAÇÃO</fullName>
            </value>
            <value>
                <fullName>EXPORTAÇÃO</fullName>
            </value>
            <value>
                <fullName>Baixa de estoque Interno</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Nome_Contato_Financeiro__c.field-meta.xml
<CustomField>
    <fullName>Nome_Contato_Financeiro__c</fullName>
    <label>Nome</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Ordem_de_trabalho__c.field-meta.xml
<CustomField>
    <fullName>Ordem_de_trabalho__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ordem de trabalho</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Referente_a_Demonstra_o_loca_o__c.field-meta.xml
<CustomField>
    <fullName>Referente_a_Demonstra_o_loca_o__c</fullName>
    <inlineHelpText>Informe se esta venda está relacionada a uma demonstração ou locação anterior.</inlineHelpText>
    <label>Referente a Demonstração/locação?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SIM</fullName>
            </value>
            <value>
                <fullName>NÃO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Telefone_Contato__c.field-meta.xml
<CustomField>
    <fullName>Telefone_Contato__c</fullName>
    <label>Telefone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Order/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PedidosVendedor</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/recordTypes/Hospcom.recordType-meta.xml
<RecordType>
    <fullName>Hospcom</fullName>
    <active>true</active>
    <description>Para faturamento das empresas do grupo Hospcom</description>
    <label>Hospcom</label>
</RecordType>

force-app/main/default/objects/Quote/fields/Forma_de_pagamento__c.field-meta.xml
<CustomField>
    <fullName>Forma_de_pagamento__c</fullName>
    <label>Forma de pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Formas_de_pagamento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <formula>IF(
    Account.CNPJ__c &lt;&gt; &quot;&quot;, 
    Account.CNPJ__c, 
    IF(
        Account.CPF__pc &lt;&gt; &quot;&quot;, 
        Account.CPF__pc, 
        &quot;&quot;
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CNPJ/CPF</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Condicao_de_pagamento__c.field-meta.xml
<CustomField>
    <fullName>Condicao_de_pagamento__c</fullName>
    <label>Condição de pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Condicoes_de_pagamento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Contrato_de_Servi_o__c.field-meta.xml
<CustomField>
    <fullName>Contrato_de_Servi_o__c</fullName>
    <formula>Case.ContratodeServico__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contrato de Serviço</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Faturamento_Feito__c.field-meta.xml
<CustomField>
    <fullName>Faturamento_Feito__c</fullName>
    <label>Faturamento Feito</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HOSPCOM</fullName>
                <default>true</default>
                <label>HOSPCOM</label>
            </value>
            <value>
                <fullName>GDB</fullName>
            </value>
            <value>
                <fullName>HEALTH SOLUTION</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Forma_de_pagamento2__c.field-meta.xml
<CustomField>
    <fullName>Forma_de_pagamento2__c</fullName>
    <label>Forma de pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Formas_de_pagamento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Forma_de_pagamento__c.field-meta.xml
<CustomField>
    <fullName>Forma_de_pagamento__c</fullName>
    <label>Forma de pagamento (old)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A VISTA NO PEDIDO</fullName>
            </value>
            <value>
                <fullName>A VISTA CONTRA EMBARQUE</fullName>
            </value>
            <value>
                <fullName>FINANCIAMENTO BANCÁRIO</fullName>
            </value>
            <value>
                <fullName>OPEN ACCOUNT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Tecnico_executor__c.field-meta.xml
<CustomField>
    <fullName>Tecnico_executor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Técnico executor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Account.Id</field>
            <operation>equals</operation>
            <value>001i00000085QYbAAM</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Ordens de trabalho</relationshipLabel>
    <relationshipName>Ordens_de_trabalho</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PesquisaSatisfacaoTest.cls
@isTest
private class PesquisaSatisfacaoTest {

    /* ---------------------------------------------------------
       HELPERS
    --------------------------------------------------------- */

    // Busca dinamicamente um recordType válido de Order
    private static Id getOrderRecordType() {
        return [
            SELECT Id 
            FROM RecordType 
            WHERE SobjectType = 'Order'
            AND DeveloperName = 'Hospcom'
            LIMIT 1
        ].Id;
    }

    private static Account buildAccount() {
        return new Account(
            Name = 'Conta Teste',
            CNPJ__c = '11.111.111/0001-11',
            BillingCountry = 'Brasil',
            BillingState = 'Goiás',
            BillingCity = 'Goiânia',
            BillingStreet = 'Rua Teste 123',
            BillingPostalCode = '74000-000'
        );
    }

    private static Opportunity buildOpportunity(Id accId) {
        return new Opportunity(
            Name = 'Oportunidade Teste',
            AccountId = accId,
            StageName = '01 - Lead',
            CloseDate = Date.today()
        );
    }

    private static Contact buildContact(Id accId) {
        return new Contact(
            FirstName = 'Fulano',
            LastName  = 'Teste',
            AccountId = accId,
            MobilePhone = '62988887777'
        );
    }

    private static Quote buildQuote(Id oppId, Id contactId) {
        return new Quote(
            Name = 'Cotação Teste',
            Status = 'Rascunho',
            OpportunityId = oppId,
            ContactId = contactId,
            Forma_de_pagamento__c  = 'Pix',
            Condicao_de_pagamento__c = 'À Vista'
        );
    }

    private static Order buildOrder(Id accId, Id vendedorId, String natureza) {
        return new Order(
            RecordTypeId = getOrderRecordType(),
            Status = 'Em andamento',           // ← IMPORTANTE PARA COBERTURA
            Name = 'Pedido Teste ' + natureza,
            AccountId = accId,
            Faturamento_Feito__c = accId,
            Condicao_de_pagamento__c = 'À Vista',
            Forma_de_pagamento2__c = 'Pix',
            Referente_a_Demonstra_o_loca_o__c = 'NÃO',
            Natureza_de_Opera_o__c = natureza,
            Vendedor__c = vendedorId,
            EffectiveDate = Date.today(),
            OwnerId = vendedorId,
            Nome_Contato_Financeiro__c = 'Teste',
            Telefone_Contato__c = '1122223333',
            E_mail_Contato__c = 'teste@teste.com',
            Ignora_validacao__c = true
        );
    }

    /* ---------------------------------------------------------
       TESTES
    --------------------------------------------------------- */

    @isTest
    static void testVendaComQuote() {

        User u = [
            SELECT Id 
            FROM User 
            WHERE (Profile.Name = 'System Administrator' OR Profile.Name = 'Administrador do sistema')
            AND IsActive = true
            LIMIT 1
        ];

        System.runAs(u) {

            Account a = buildAccount();
            insert a;

            Contact c = buildContact(a.Id);
            insert c;

            Opportunity opp = buildOpportunity(a.Id);
            insert opp;

            Quote q = buildQuote(opp.Id, c.Id);
            insert q;

            Order o = buildOrder(a.Id, u.Id, 'VENDA');
            o.QuoteId = q.Id;
            insert o;

            Test.startTest();
            RecursiveHandler.IsNotRecursive2 = true;
            o.Status = 'Entregue Total';
            update o;
            Test.stopTest();

            System.assertEquals('Entregue Total', o.Status);
        }
    }

    @isTest
    static void testLocacaoComContrato() {

        User u = [
            SELECT Id 
            FROM User 
            WHERE (Profile.Name = 'System Administrator' OR Profile.Name = 'Administrador do sistema')
            AND IsActive = true
            LIMIT 1
        ];

        System.runAs(u) {

            Account a = buildAccount();
            insert a;

            Contact c = buildContact(a.Id);
            insert c;

            Contrato_de_Servi_o__c contrato = new Contrato_de_Servi_o__c(
                Contato_do_Locat_rio__c = c.Id
            );
            insert contrato;

            Order o = buildOrder(a.Id, u.Id, 'LOCAÇÃO');
            o.Contrato_de_Servi_o__c = contrato.Id;
            insert o;

            Test.startTest();
            RecursiveHandler.IsNotRecursive2 = true;
            o.Status = 'Entregue Total';
            update o;
            Test.stopTest();

            System.assertEquals('Entregue Total', o.Status);
        }
    }

    @isTest
    static void testServicoComWorkOrder() {

        User u = [
            SELECT Id 
            FROM User 
            WHERE (Profile.Name = 'System Administrator' OR Profile.Name = 'Administrador do sistema')
            AND IsActive = true
            LIMIT 1
        ];

        System.runAs(u) {

            Account a = buildAccount();
            insert a;

            Contact c = buildContact(a.Id);
            insert c;

            WorkOrder wo = new WorkOrder(
                ContactId = c.Id,
                Tecnico_executor__c = '0035A00003gVl4tQAC' 
            );
            insert wo;

            Order o = buildOrder(a.Id, u.Id, 'SERVIÇO');
            o.Ordem_de_trabalho__c = wo.Id;
            insert o;

            Test.startTest();
            RecursiveHandler.IsNotRecursive2 = true;
            o.Status = 'Entregue Total';
            update o;
            Test.stopTest();

            System.assertEquals('Entregue Total', o.Status);
        }
    }

    // Sem quote
    @isTest
    static void testVendaSemQuote() {

       User u = [
            SELECT Id 
            FROM User 
            WHERE (Profile.Name = 'System Administrator' OR Profile.Name = 'Administrador do sistema')
            AND IsActive = true
            LIMIT 1
        ];

        System.runAs(u) {

            Account a = buildAccount();
            insert a;

            Order o = buildOrder(a.Id, u.Id, 'VENDA');
            insert o;

            Test.startTest();
            RecursiveHandler.IsNotRecursive2 = true;
            o.Status = 'Entregue Total';
            update o;
            Test.stopTest();
        }
    }

    // Sem contrato
    @isTest
    static void testLocacaoSemContrato() {

        User u = [
            SELECT Id 
            FROM User 
            WHERE (Profile.Name = 'System Administrator' OR Profile.Name = 'Administrador do sistema')
            AND IsActive = true
            LIMIT 1
        ];

        System.runAs(u) {

            Account a = buildAccount();
            insert a;

            Order o = buildOrder(a.Id, u.Id, 'LOCAÇÃO');
            insert o;

            Test.startTest();
            RecursiveHandler.IsNotRecursive2 = true;
            o.Status = 'Entregue Total';
            update o;
            Test.stopTest();
        }
    }

    // Sem WorkOrder
    @isTest
    static void testServicoSemWorkOrder() {

        User u = [
            SELECT Id 
            FROM User 
            WHERE (Profile.Name = 'System Administrator' OR Profile.Name = 'Administrador do sistema')
            AND IsActive = true
            LIMIT 1
        ];

        System.runAs(u) {
            
            Account a = buildAccount();
            insert a;

            Order o = buildOrder(a.Id, u.Id, 'SERVIÇO');
            insert o;

            Test.startTest();
            RecursiveHandler.IsNotRecursive2 = true;
            o.Status = 'Entregue Total';
            update o;
            Test.stopTest();
        }
    }
}