force-app/main/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rascunho</fullName>
                <default>true</default>
                <label>Rascunho</label>
            </value>
            <value>
                <fullName>Aguardando Aprovação</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Reprovado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reserva_de_Sala__c/Reserva_de_Sala__c.object-meta.xml
<CustomObject>
    <label>Reserva</label>
    <nameField>
        <displayFormat>RES - {0000}</displayFormat>
        <label>Reserva</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reserva_de_Sala__c/fields/Frequencia__c.field-meta.xml
<CustomField>
    <fullName>Frequencia__c</fullName>
    <inlineHelpText>Quantas vezes essa reserva se repetirá?</inlineHelpText>
    <label>Frequência</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Reserva_de_Sala__c/fields/In_cio__c.field-meta.xml
<CustomField>
    <fullName>In_cio__c</fullName>
    <label>Início</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Reserva_de_Sala__c/fields/recorrencia__c.field-meta.xml
<CustomField>
    <fullName>recorrencia__c</fullName>
    <formula>if(Text(Reserva_recorrente__c) == &apos;Semanal&apos;, 7,
if(Text(Reserva_recorrente__c) == &apos;Quinzenal&apos;, 14, 
if(Text(Reserva_recorrente__c) == &apos;Quinzenal&apos;, 28, null)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Qual o tipo de recorrencia dessa reserva?</inlineHelpText>
    <label>Recorrencia</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Reserva_de_Sala__c/fields/Reserva_recorrente__c.field-meta.xml
<CustomField>
    <fullName>Reserva_recorrente__c</fullName>
    <defaultValue>&apos;Não Recorrente&apos;</defaultValue>
    <inlineHelpText>Exemplo: Suponha que façamos uma reserva da sala de reunião da sede da rua 89, do dia 04/03/2024 - 13:30 às 14:30 e essa reserva seja recorrente no &quot;Mês atual&quot;. Logo, todas as segundas-feiras do mês de Março no horario 13:30 às 14:30, serão reservados. Mas isso não se aplicará para o mês seguinte que Abriu.</inlineHelpText>
    <label>Reserva recorrente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Não Recorrente</fullName>
                <default>true</default>
                <label>Não Recorrente</label>
            </value>
            <value>
                <fullName>Semanal</fullName>
            </value>
            <value>
                <fullName>Quinzenal</fullName>
            </value>
            <value>
                <fullName>Mensal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reserva_de_Sala__c/fields/Sala__c.field-meta.xml
<CustomField>
    <fullName>Sala__c</fullName>
    <label>Sala</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Auditório</fullName>
            </value>
            <value>
                <fullName>Auditório Oeste</fullName>
            </value>
            <value>
                <fullName>Sala de Reunião</fullName>
            </value>
            <value>
                <fullName>Sala de Reunião 2</fullName>
            </value>
            <value>
                <fullName>Showroom</fullName>
            </value>
            <value>
                <fullName>Showroom &amp; Auditório</fullName>
            </value>
            <value>
                <fullName>Showroom VET</fullName>
            </value>
            <value>
                <fullName>Sala de Reunião 1 - Oeste</fullName>
            </value>
            <value>
                <fullName>Sala de Reunião 2 - Oeste</fullName>
            </value>
            <value>
                <fullName>Sala de Reunião 3 - Oeste</fullName>
            </value>
            <value>
                <fullName>Sala de Vídeo Conferência 1 - Oeste</fullName>
            </value>
            <value>
                <fullName>Sala de Vídeo Conferência 2 - Oeste</fullName>
            </value>
            <value>
                <fullName>Administrativo - Oeste</fullName>
            </value>
            <value>
                <fullName>Sala de Podcast</fullName>
                <isActive>false</isActive>
                <label>Sala de Podcast</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reserva_de_Sala__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Novo</fullName>
            </value>
            <value>
                <fullName>Em aprovação</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Em curso</fullName>
            </value>
            <value>
                <fullName>Finalizado</fullName>
            </value>
            <value>
                <fullName>Reprovado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reserva_de_Sala__c/fields/Termino__c.field-meta.xml
<CustomField>
    <fullName>Termino__c</fullName>
    <label>Término</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/ReservaSalaTeste.cls
@isTest(seeAllData=true)
public class ReservaSalaTeste {

    @isTest
    private static void teste(){

        Datetime dataInicio = Datetime.newInstance(2022, 12, 10, 12, 11, 11);
        Datetime dataTermino = Datetime.newInstance(2022, 12, 10, 12, 15, 15);

        Datetime dataInicio2 = Datetime.newInstance(2024, 12, 12, 12, 11, 11);
        Datetime dataTermino2 = Datetime.newInstance(2024, 12, 12, 12, 15, 15);

        Datetime dataInicio3 = Datetime.newInstance(2024, 12, 11, 12, 11, 11);
        Datetime dataTermino3 = Datetime.newInstance(2024, 12, 11, 12, 15, 15);
        
        
        Datetime dataInicio4 = Datetime.newInstance(2024, 03, 19, 19, 11, 11);
        Datetime dataTermino4 = Datetime.newInstance(2024, 03, 20, 19, 15, 15);

        Account a = new Account();
        a.Name = 'Teste';
        a.CNPJ__c = '51.461.458/0001-89';
         try{ 
             insert a;
             
        	 
         } catch (Exception e) {
            System.debug('Exceção ao criar reserva que se choca com a primeira: ' + e.getMessage());
        }
       

        Reserva_de_Sala__c rSala  = new Reserva_de_Sala__c();
        rSala.Sala__c = 'Showroom';
        rSala.In_cio__c = dataInicio;
        rSala.Termino__c = dataTermino;
        try{
        	insert rSala;
         } catch (Exception e) {
            System.debug('Exceção ao criar reserva que se choca com a primeira: ' + e.getMessage());
        }
        Reserva_de_Sala__c rSala2  = new Reserva_de_Sala__c();
        rSala2.Sala__c = 'Showroom';
        rSala2.In_cio__c = dataInicio2;
        rSala2.Termino__c = dataTermino2;
       
         try{
        	 insert rSala2;
             
             rSala2.In_cio__c = Datetime.newInstance(2024, 12, 12, 12, 17, 15);
             
             update rSala2;
         } catch (Exception e) {
            System.debug('Exceção ao criar reserva que se choca com a primeira: ' + e.getMessage());
        }

        Reserva_de_Sala__c rSala3  = new Reserva_de_Sala__c();
        rSala3.Sala__c = 'Showroom';
        rSala3.In_cio__c = dataInicio3;
        rSala3.Termino__c = dataTermino3;
         try{
        	 insert rSala3;
         } catch (Exception e) {
            System.debug('Exceção ao criar reserva que se choca com a primeira: ' + e.getMessage());
        }
        

        // Tentando criar uma reserva que ultrapassa um dia
        try {
            Reserva_de_Sala__c rSalaMaisDeUmDia  = new Reserva_de_Sala__c();
            rSalaMaisDeUmDia.Sala__c = 'Showroom';
            rSalaMaisDeUmDia.In_cio__c = Datetime.newInstance(2024, 12, 13, 12, 0, 0);
            rSalaMaisDeUmDia.Termino__c = Datetime.newInstance(2024, 12, 14, 12, 15, 0);
            insert rSalaMaisDeUmDia;
        } catch (Exception e) {
            System.debug('Exceção ao criar reserva que ultrapassa um dia: ' + e.getMessage());
        }

        // Atualizando a primeira reserva para verificar conflitos
        try {
            rSala.In_cio__c = dataInicio3;
            rSala.Termino__c = dataTermino3;
            update rSala;
        } catch (Exception e) {
            System.debug('Exceção ao atualizar a reserva: ' + e.getMessage());
        }
        
        //Teste sucesso
        try {
       		Reserva_de_Sala__c rSala4  = new Reserva_de_Sala__c();
            rSala4.In_cio__c = dataInicio4;
            rSala4.Termino__c = dataTermino4;
            insert rSala4;
        } catch (Exception e) {
            System.debug('Exceção ao atualizar a reserva: ' + e.getMessage());
        }

        // Tentando criar uma reserva que se choca com a primeira
        try {
            Reserva_de_Sala__c rSalaConflito  = new Reserva_de_Sala__c();
            rSalaConflito.Sala__c = 'Showroom';
            rSalaConflito.In_cio__c = dataInicio2;
            rSalaConflito.Termino__c = dataTermino2;
            insert rSalaConflito;
            
            System.debug('------------ Reserva salva  -----------------------');
            
        } catch (Exception e) {
            System.debug('---------------------------------- ' + e.getMessage());
        }
    }
    
    @isTest
    private static void teste2(){
        Reserva_de_Sala__c rs = [
            SELECT id, name, Sala__c, In_cio__c, Status__c, Termino__c,Frequencia__c,recorrencia__c,Reserva_recorrente__c, RecordType.name
            FROM Reserva_de_Sala__c 
            WHERE Status__c != 'Finalizado' AND Status__c != 'Reprovado'  AND Frequencia__c != null
            LIMIT 1
        ]; 
        
        try{ 
            
            System.debug('rs: ' + rs);
            Reserva.criaRecorrencia(rs); // Chamada para criar recorrência
            
        }catch (Exception e) {
            System.debug('Erro ao criar recorrência: ' + e.getMessage());
        }
        
    }
}