force-app/main/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <label>CPF</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Faturamento_Feito2__c.field-meta.xml
<CustomField>
    <fullName>Faturamento_Feito2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Faturamento feito</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>FORNECEDOR, DISTRIBUIDOR</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Faturamentos Feitos (de oportunidades)</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Prazo_de_garantia__c.field-meta.xml
<CustomField>
    <fullName>Prazo_de_garantia__c</fullName>
    <defaultValue>&quot;equipamentos 12 meses, acessórios 3 meses&quot;</defaultValue>
    <inlineHelpText>Ex: equipamentos 12 meses, acessórios 3 meses, etc...</inlineHelpText>
    <label>Prazo de garantia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Comercial.recordType-meta.xml
<RecordType>
    <fullName>Comercial</fullName>
    <active>true</active>
    <businessProcess>Padrão</businessProcess>
    <description>Processo de vendas comercial</description>
    <label>Comercial</label>
</RecordType>

force-app/main/default/objects/Quote/fields/Prazo_de_garantia__c.field-meta.xml
<CustomField>
    <fullName>Prazo_de_garantia__c</fullName>
    <defaultValue>&quot;Equipamentos &quot; + TEXT(12) + &quot; meses, acessórios &quot; + TEXT(3) + &quot; meses&quot;</defaultValue>
    <inlineHelpText>Ex: Equipamentos 12 meses, acessórios 3 meses, etc...</inlineHelpText>
    <label>Prazo de garantia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <formula>Contact.CPF__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CPF</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CotacaoPropostaTest.cls
@isTest(SeeAllData=true)
private class CotacaoPropostaTest {

    @isTest
    static void testCotacaoPropostaController() {
        
        // Conta principal com endereço (cliente)
        Account acc = new Account(
            Name = 'Conta Teste',
            CNPJ__c = '13.512.358/0001-45',
            BillingStreet = 'Rua dos Testes, 123',
            BillingCity = 'Goiânia',
            BillingStateCode = 'GO',
            BillingCountry = 'Brasil',
            BillingPostalCode = '74000-000',
            ShippingStreet = 'Rua das Entregas, 456',
            ShippingCity = 'Goiânia',
            ShippingStateCode = 'GO',
            ShippingCountry = 'Brasil',
            ShippingPostalCode = '74000-001'
        );
        insert acc;

        // Contato vinculado à conta
        Contact contato = new Contact(
            FirstName = 'João',
            LastName = 'Silva',
            CPF__c = '783.846.681-40',
            AccountId = acc.Id
        );
        insert contato;

        // Usuário dono da oportunidade
        User u = [SELECT Id FROM User WHERE Profile.Name = 'Administrador do sistema' OR Profile.Name = 'System Administrator' LIMIT 1];
        RecordType rtOpp = [SELECT Id FROM RecordType WHERE SObjectType = 'Opportunity' AND Name = 'Comercial' LIMIT 1];
        Product2 prod = [SELECT Id FROM Product2 LIMIT 1];
        Pricebook2 pb = [SELECT Id FROM Pricebook2 WHERE IsStandard = true LIMIT 1];
        PricebookEntry pbe = [SELECT Id FROM PricebookEntry WHERE Product2Id = :prod.Id AND Pricebook2Id = :pb.Id LIMIT 1];

        // CNPJs a serem testados
        List<String> cnpjs = new List<String>{
            '05.743.288/0001-08', // Hospcom
            '27.476.124/0001-02', // Health
            '23.813.386/0001-56'  // GDB
        };

        // Buscar as contas existentes com esses CNPJs
        Map<String, Account> contasFaturamento = new Map<String, Account>();
        for (Account a : [SELECT Id, CNPJ__c, Name FROM Account WHERE CNPJ__c IN :cnpjs]) {
            contasFaturamento.put(a.CNPJ__c, a);
        }

        // Garantir que todas foram encontradas
        for (String cnpj : cnpjs) {
            System.assert(contasFaturamento.containsKey(cnpj), 'Conta de faturamento com CNPJ ' + cnpj + ' não encontrada em produção.');
        }

        List<Quote> quotesToTest = new List<Quote>();

        for (String cnpj : cnpjs) {
            Account faturamento = contasFaturamento.get(cnpj);

            Opportunity opp = new Opportunity(
                Name = 'Oportunidade ' + cnpj,
                StageName = 'Prospecting',
                CloseDate = Date.today().addDays(30),
                OwnerId = u.Id,
                RecordTypeId = rtOpp.Id,
                AccountId = acc.Id,
                Faturamento_Feito2__c = faturamento.Id
            );
            insert opp;

            Quote quote = new Quote(
                Name = 'Cotação ' + cnpj,
                OpportunityId = opp.Id,
                ContactId = contato.Id,
                ExpirationDate = Date.today().addDays(15),
                Prazo_de_garantia__c = 'Equipamento 12 meses, Peça 6 meses',
                CurrencyISOCode = 'BRL',
                Pricebook2Id = pb.Id
            );
            insert quote;
            quotesToTest.add(quote);

            QuoteLineItem qli = new QuoteLineItem(
                QuoteId = quote.Id,
                Product2Id = prod.Id,
                PricebookEntryId = pbe.Id,
                UnitPrice = 100,
                Quantity = 2,
                Item__c = 1
            );
            insert qli;

            OpportunityContactRole ocr = new OpportunityContactRole(
                OpportunityId = opp.Id,
                ContactId = contato.Id,
                Role = 'Signatário da proposta (Hospcom)'
            );
            insert ocr;
        }

        Test.startTest();
        for (Quote qt : quotesToTest) {
            ApexPages.StandardController stdCtrl = new ApexPages.StandardController(qt);
            CotacaoProposta controller = new CotacaoProposta(stdCtrl);

            System.assertNotEquals(null, controller.cotacao, 'Cotação não pode ser nula');
            System.assert(controller.produtos.size() > 0, 'Deve haver produtos');
            System.assertNotEquals(null, controller.documento, 'Documento não pode ser nulo');
            System.assertNotEquals(null, controller.documento.timbrado, 'Timbrado deve estar preenchido');
        }
        Test.stopTest();
    }
}