force-app/main/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Raz_o_Social__c.field-meta.xml
<CustomField>
    <fullName>Raz_o_Social__c</fullName>
    <label>Razão social</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Contrato_de_Servi_o__c.field-meta.xml
<CustomField>
    <fullName>Contrato_de_Servi_o__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato de Serviço</label>
    <referenceTo>ServiceContract</referenceTo>
    <relationshipLabel>Ativos</relationshipLabel>
    <relationshipName>Ativos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ativos_do_Contrato__c/Ativos_do_Contrato__c.object-meta.xml
<CustomObject>
    <label>Ativo do Contrato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>N° de Registro</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ativos do Contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ativos_do_Contrato__c/fields/Ativo_Locado__c.field-meta.xml
<CustomField>
    <fullName>Ativo_Locado__c</fullName>
    <label>Ativo Locado</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Ativos do Contrato</relationshipLabel>
    <relationshipName>Ativos_do_Contrato</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ativos_do_Contrato__c/fields/Contrato_de_Servico__c.field-meta.xml
<CustomField>
    <fullName>Contrato_de_Servico__c</fullName>
    <label>Contrato de Serviço</label>
    <referenceTo>Contrato_de_Servi_o__c</referenceTo>
    <relationshipLabel>Ativos do Contrato</relationshipLabel>
    <relationshipName>Ativos_do_Contrato</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ativos_do_Contrato__c/fields/Equipamento_no_Cliente__c.field-meta.xml
<CustomField>
    <fullName>Equipamento_no_Cliente__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Equipamento no Cliente</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Ativos_do_Contrato__c/fields/Valor_Total_Mensal__c.field-meta.xml
<CustomField>
    <fullName>Valor_Total_Mensal__c</fullName>
    <formula>Valor_Unitario_Mensal__c *  Quantidade__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valor Total Periódico</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Ativos_do_Contrato__c/fields/Valor_Unitario_Mensal__c.field-meta.xml
<CustomField>
    <fullName>Valor_Unitario_Mensal__c</fullName>
    <label>Valor Unitário Periódico</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/Contrato_de_Servi_o__c.object-meta.xml
<CustomObject>
    <label>Contrato de Serviço</label>
    <nameField>
        <label>Nome do Contrato</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contratos de Serviços</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Contato_do_Locat_rio__c.field-meta.xml
<CustomField>
    <fullName>Contato_do_Locat_rio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contato do Locatário</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contratos de Serviços</relationshipLabel>
    <relationshipName>Contratos_de_Servi_os</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Dura_o_do_Contrato_meses__c.field-meta.xml
<CustomField>
    <fullName>Dura_o_do_Contrato_meses__c</fullName>
    <label>Duração do Contrato</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Emails_para_faturamento__c.field-meta.xml
<CustomField>
    <fullName>Emails_para_faturamento__c</fullName>
    <label>Emails para faturamento</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Forma_de_pagamento2__c.field-meta.xml
<CustomField>
    <fullName>Forma_de_pagamento2__c</fullName>
    <label>Forma de pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Formas_de_pagamento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Locador_a__c.field-meta.xml
<CustomField>
    <fullName>Locador_a__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Locador(a)/Contratada</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contratos de Serviços (Locador(a))</relationshipLabel>
    <relationshipName>Contratos_de_Servi_os1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Locat_rio_a__c.field-meta.xml
<CustomField>
    <fullName>Locat_rio_a__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Locatário(a)/Contratante</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contratos de Locação</relationshipLabel>
    <relationshipName>Contratos_de_Servi_os2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Primeiro_faturamento__c.field-meta.xml
<CustomField>
    <fullName>Primeiro_faturamento__c</fullName>
    <label>Data do primeiro faturamento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Status_do_Contrato__c.field-meta.xml
<CustomField>
    <fullName>Status_do_Contrato__c</fullName>
    <label>Status do Contrato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AGUARDANDO ACEITAÇÃO DA PROPOSTA</fullName>
            </value>
            <value>
                <fullName>AGUARDANDO ASSINATURA DO CONTRATO</fullName>
            </value>
            <value>
                <fullName>CANCELADO</fullName>
            </value>
            <value>
                <fullName>CONCLUÍDO</fullName>
            </value>
            <value>
                <fullName>CONCLUÍDO (COM PENDENCIAS)</fullName>
            </value>
            <value>
                <fullName>CONTRATO VIGENTE</fullName>
            </value>
            <value>
                <fullName>PERDIDO</fullName>
            </value>
            <value>
                <fullName>SEPARAÇÃO/ENTREGA</fullName>
            </value>
            <value>
                <fullName>EM CALIBRAÇÃO</fullName>
            </value>
            <value>
                <fullName>AGUARDANDO DOCUMENTAÇÕES ASSINADAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Tipo_de_Entrega__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Entrega__c</fullName>
    <label>Tipo de Entrega</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipos_de_envio</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Comentarios__c.field-meta.xml
<CustomField>
    <fullName>Comentarios__c</fullName>
    <label>Comentários</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Order/fields/Condicao_de_pagamento__c.field-meta.xml
<CustomField>
    <fullName>Condicao_de_pagamento__c</fullName>
    <label>Condição de pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Natureza_de_Opera_o__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Condicoes_de_pagamento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Contrato_de_Servi_o__c.field-meta.xml
<CustomField>
    <fullName>Contrato_de_Servi_o__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato de Serviço</label>
    <referenceTo>Contrato_de_Servi_o__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Data_de_Vencimento__c.field-meta.xml
<CustomField>
    <fullName>Data_de_Vencimento__c</fullName>
    <description>data de vencimento do pedido</description>
    <inlineHelpText>data de vencimento do pedido</inlineHelpText>
    <label>Data de Vencimento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Departamento3__c.field-meta.xml
<CustomField>
    <fullName>Departamento3__c</fullName>
    <label>Departamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Departamentos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/E_mail_Contato__c.field-meta.xml
<CustomField>
    <fullName>E_mail_Contato__c</fullName>
    <label>E-mail</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Order/fields/Entrega_parcial__c.field-meta.xml
<CustomField>
    <fullName>Entrega_parcial__c</fullName>
    <label>Entrega parcial</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Autorizada</fullName>
            </value>
            <value>
                <fullName>Não Autorizada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Faturamento_Feito__c.field-meta.xml
<CustomField>
    <fullName>Faturamento_Feito__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Empresa do grupo Hospcom que irá faturar o pedido.</inlineHelpText>
    <label>Faturamento feito</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Faturamentos Feitos (de pedidos)</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Forma_de_pagamento2__c.field-meta.xml
<CustomField>
    <fullName>Forma_de_pagamento2__c</fullName>
    <label>Forma de pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Natureza_de_Opera_o__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Formas_de_pagamento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Frete__c.field-meta.xml
<CustomField>
    <fullName>Frete__c</fullName>
    <label>Tipo de envio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipos_de_envio</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Ignora_validacao__c.field-meta.xml
<CustomField>
    <fullName>Ignora_validacao__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ignora validação</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Locado_em__c.field-meta.xml
<CustomField>
    <fullName>Locado_em__c</fullName>
    <label>Locado em:</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Natureza_de_Opera_o__c.field-meta.xml
<CustomField>
    <fullName>Natureza_de_Opera_o__c</fullName>
    <label>Natureza de Operação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BONIFICAÇÃO</fullName>
            </value>
            <value>
                <fullName>DEMONSTRAÇÃO</fullName>
            </value>
            <value>
                <fullName>LOCAÇÃO</fullName>
            </value>
            <value>
                <fullName>EMPRÉSTIMO</fullName>
            </value>
            <value>
                <fullName>REMESSA DE LOCAÇÃO</fullName>
            </value>
            <value>
                <fullName>REMESSA DE TROCA</fullName>
            </value>
            <value>
                <fullName>REMESSA EM CONSIGNAÇÃO</fullName>
            </value>
            <value>
                <fullName>SERVIÇO</fullName>
            </value>
            <value>
                <fullName>VENDA</fullName>
            </value>
            <value>
                <fullName>VENDA DA CONSIGNAÇÃO</fullName>
            </value>
            <value>
                <fullName>RETORNO DE LOCAÇÃO</fullName>
            </value>
            <value>
                <fullName>EXPORTAÇÃO</fullName>
            </value>
            <value>
                <fullName>Baixa de estoque Interno</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Necess_rio_Treinamento__c.field-meta.xml
<CustomField>
    <fullName>Necess_rio_Treinamento__c</fullName>
    <label>Necessário Treinamento?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SIM</fullName>
            </value>
            <value>
                <fullName>NÃO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Per_odo_do_contrato_Fim__c.field-meta.xml
<CustomField>
    <fullName>Per_odo_do_contrato_Fim__c</fullName>
    <label>Período faturado (Fim)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Periodo_do_contrato_inicio__c.field-meta.xml
<CustomField>
    <fullName>Periodo_do_contrato_inicio__c</fullName>
    <label>Período faturado (inicio)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Prazo_de_entrega__c.field-meta.xml
<CustomField>
    <fullName>Prazo_de_entrega__c</fullName>
    <label>Prazo de entrega</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Raz_o_Social__c.field-meta.xml
<CustomField>
    <fullName>Raz_o_Social__c</fullName>
    <formula>Account.Raz_o_Social__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>_Razão Social (del)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/recordTypes/Hospcom.recordType-meta.xml
<RecordType>
    <fullName>Hospcom</fullName>
    <active>true</active>
    <description>Para faturamento das empresas do grupo Hospcom</description>
    <label>Hospcom</label>
</RecordType>

force-app/main/default/objects/OrderItem/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <formula>Order.Account.CNPJ__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CNPJ</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Prazo_de_entrega__c.field-meta.xml
<CustomField>
    <fullName>Prazo_de_entrega__c</fullName>
    <label>Prazo de entrega</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Quantidade__c.field-meta.xml
<CustomField>
    <fullName>Quantidade__c</fullName>
    <label>Quantidade</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Departamentos.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Administrativo</fullName>
    </customValue>
    <customValue>
        <fullName>Comercial</fullName>
    </customValue>
    <customValue>
        <fullName>Compras</fullName>
    </customValue>
    <customValue>
        <fullName>Contabilidade</fullName>
        <label>Contabilidade/Fiscal/DP</label>
    </customValue>
    <customValue>
        <fullName>Controladoria</fullName>
    </customValue>
    <customValue>
        <fullName>Desenvolvimento</fullName>
    </customValue>
    <customValue>
        <fullName>Diretoria Administrativa</fullName>
    </customValue>
    <customValue>
        <fullName>Diretoria de B.I e Growth</fullName>
    </customValue>
    <customValue>
        <fullName>Diretoria de Negocios</fullName>
    </customValue>
    <customValue>
        <fullName>Educação</fullName>
        <label>Educação Continuada</label>
    </customValue>
    <customValue>
        <fullName>Faturamento</fullName>
    </customValue>
    <customValue>
        <fullName>Financeiro</fullName>
    </customValue>
    <customValue>
        <fullName>Governo</fullName>
    </customValue>
    <customValue>
        <fullName>Jurídico</fullName>
    </customValue>
    <customValue>
        <fullName>Locação</fullName>
    </customValue>
    <customValue>
        <fullName>Logística</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Operações</fullName>
    </customValue>
    <customValue>
        <fullName>Outros</fullName>
    </customValue>
    <customValue>
        <fullName>Qualidade</fullName>
    </customValue>
    <customValue>
        <fullName>RH</fullName>
    </customValue>
    <customValue>
        <fullName>Serviço</fullName>
    </customValue>
    <customValue>
        <fullName>Departamento Pessoal</fullName>
        <isActive>false</isActive>
        <label>Departamento Pessoal</label>
    </customValue>
    <customValue>
        <fullName>Facilites</fullName>
        <isActive>false</isActive>
        <label>Facilites</label>
    </customValue>
    <customValue>
        <fullName>T.I.</fullName>
        <isActive>false</isActive>
        <label>T.I.</label>
    </customValue>
    <customValue>
        <fullName>OPME</fullName>
        <isActive>false</isActive>
        <label>OPME</label>
    </customValue>
    <customValue>
        <fullName>Manutenção</fullName>
        <isActive>false</isActive>
        <label>Manutenção</label>
    </customValue>
    <customValue>
        <fullName>Limpeza</fullName>
        <isActive>false</isActive>
        <label>Limpeza</label>
    </customValue>
    <customValue>
        <fullName>Fiscal</fullName>
        <isActive>false</isActive>
        <label>Fiscal</label>
    </customValue>
    <masterLabel>Departamentos</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/globalValueSets/Tipos_de_envio.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Contratação do Frete por conta do Remetente (CIF)</fullName>
    </customValue>
    <customValue>
        <fullName>Contratação do Frete por conta do Destinatário (FOB)</fullName>
    </customValue>
    <customValue>
        <fullName>Contratação do Frete por conta de Terceiros</fullName>
    </customValue>
    <customValue>
        <fullName>Transporte Próprio por conta do Remetente</fullName>
    </customValue>
    <customValue>
        <fullName>Transporte Próprio por conta do Destinatário</fullName>
    </customValue>
    <customValue>
        <fullName>Sem Ocorrência de Transporte.</fullName>
    </customValue>
    <masterLabel>Tipos de envio</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ContratoServicoService.cls
public with sharing class ContratoServicoService {
    final static List<String> FORMAS_PAGAMENTOS_ADIANTADOS = new List<String>{
            'Boleto Bancário',
            'Transferência Bancária',
            'Pix',
            'Dinheiro',
            'E-commerce',
            'Cruzamento de Saldos (Permuta) Recebido',
            'Sem Mov. Financeiro',
            'Cartao Credito / Debito'
        };
    
    public static void processaContratos(List<Contrato_de_servi_o__c> novosContratos, Map<Id, Contrato_de_servi_o__c> antigosContratosMap) {
        List<Order> pedidos = new List<Order>();
        List<OrderItem> itensPedidos = new List<OrderItem>();
        Set<String> codigosProdutos = new Set<String>();
        Map<String, String> nomesProdutos = new Map<String, String>();
        Map<String, Decimal> quantidades = new Map<String, Decimal>();
        Map<String, Decimal> valoresTotais = new Map<String, Decimal>();
        PedidoData dados = new PedidoData();
        String emails;

        for (Contrato_de_servi_o__c contrato : novosContratos) {
            Contrato_de_servi_o__c contratoAntigo = antigosContratosMap.get(contrato.Id);
            
            if (deveCriarPedido(contrato, contratoAntigo)) {
                dados = preparaDadosContrato(contrato);
                emails = contrato.Emails_para_faturamento__c;
                processaAtivosContrato(contrato, codigosProdutos, nomesProdutos, quantidades, valoresTotais);
                criaPedidosPorMes(contrato, dados, pedidos, emails);
            }
        }

        if (!pedidos.isEmpty()) {
            insert pedidos;
            Map<String, PricebookEntry> pbes = buscaPBEs(codigosProdutos);
            criaOrderItems(pedidos, pbes, quantidades, valoresTotais, nomesProdutos, dados, itensPedidos, emails);
            insert itensPedidos;
            update pedidos;
        }
    }

    public static Boolean deveCriarPedido(Contrato_de_servi_o__c atual, Contrato_de_servi_o__c antigo) {
        return atual.Status_do_Contrato__c == 'CONTRATO VIGENTE' &&
               antigo.Status_do_Contrato__c != 'CONTRATO VIGENTE' &&
               atual.Id != 'a1YU4000000qY7FMAU';
    }

    public static PedidoData preparaDadosContrato(Contrato_de_servi_o__c contrato) {
        PedidoData dados = new PedidoData();
        dados.contato = [SELECT ID, FirstName, Email, MobilePhone, Phone FROM Contact WHERE ID = :contrato.Contato_do_Locat_rio__c LIMIT 1];
        dados.locatario = [SELECT Id, Name, BillingStreet, BillingCity, BillingState, BillingPostalCode, BillingCountry, 
                           ShippingStreet, ShippingCity, ShippingState, ShippingPostalCode, ShippingCountry, CurrencyIsoCode 
                           FROM Account WHERE ID = :contrato.Locat_rio_a__c LIMIT 1];
        dados.locador = [SELECT Id, Name, Raz_o_Social__c, CNPJ__c FROM Account WHERE id = :contrato.Locador_a__c LIMIT 1];
        dados.dadosBancarios = getDadosBancarios(String.valueOf(contrato.Forma_de_pagamento2__c));
        String cond = contrato.Condicao_de_pagamento__c;
        dados.numeroDias = (cond == 'À Vista') ? 0 : Integer.valueOf(cond.split(' ')[0]);
        dados.telefone = (dados.contato.MobilePhone != null && dados.contato.MobilePhone != '') ? dados.contato.MobilePhone : dados.contato.Phone;
        dados.dataInicial = Date.today();
        return dados;
    }

    public static void processaAtivosContrato(
        Contrato_de_servi_o__c contrato,
        Set<String> codigosProdutos,
        Map<String, String> nomesProdutos,
        Map<String, Decimal> quantidades,
        Map<String, Decimal> valoresTotais
    ) {
        List<Ativos_do_Contrato__c> ativos = [
            SELECT Ativo_Locado__r.Product2.ProductCode, Ativo_Locado__r.Product2.Name, Valor_Total_Mensal__c, 
                   Valor_Unitario_Mensal__c, Quantidade__c, CurrencyIsoCode
            FROM Ativos_do_Contrato__c 
            WHERE Contrato_de_Servico__c = :contrato.Id AND Equipamento_no_cliente__c = true
        ];

        for (Ativos_do_Contrato__c ativo : ativos) {
            String codigo = ativo.Ativo_Locado__r.Product2.ProductCode + 'LOCACAO';
            codigosProdutos.add(codigo);
            nomesProdutos.put(codigo, ativo.Ativo_Locado__r.Product2.Name);

            Decimal qtd = quantidades.get(codigo) != null ? quantidades.get(codigo) : 0;
            Decimal val = valoresTotais.get(codigo) != null ? valoresTotais.get(codigo) : 0;
            quantidades.put(codigo, qtd + ativo.Quantidade__c);
            valoresTotais.put(codigo, val + ativo.Valor_Total_Mensal__c);
        }
    }

    public static void criaPedidosPorMes(
        Contrato_de_servi_o__c contrato,
        PedidoData dados,
        List<Order> pedidos,
        String emails
    ) {
        for (Integer i = 0; i < contrato.Dura_o_do_Contrato_meses__c; i++) {
            Date vencimento = contrato.Primeiro_faturamento__c.addMonths(i).addDays(dados.numeroDias);
            Order pedido = new Order(
                AccountId = contrato.Locat_rio_a__c,
                Contrato_de_Servi_o__c = contrato.Id,
                EffectiveDate = dados.dataInicial.addMonths(i),
                Prazo_de_Entrega__c = contrato.Primeiro_faturamento__c.addMonths(i),
                Periodo_do_contrato_inicio__c = contrato.Primeiro_faturamento__c.addMonths(i),
                Per_odo_do_contrato_Fim__c = contrato.Primeiro_faturamento__c.addMonths(i + 1),
                Status = 'Rascunho',
                Data_de_vencimento__c = vencimento,
                BillingCity = dados.locatario.BillingCity,
                BillingCountry = dados.locatario.BillingCountry,
                BillingPostalCode = dados.locatario.BillingPostalCode,
                BillingState = dados.locatario.BillingState,
                BillingStreet = dados.locatario.BillingStreet,
                Comentarios__c = 'Pedido criado automaticamente a partir da aprovação do contrato.',
                Condicao_de_pagamento__c = contrato.Condicao_de_pagamento__c,
                Departamento3__c = 'Locação',
                E_mail_Contato__c = dados.contato.Email,
                Entrega_parcial__c = 'Não Autorizada',
                Faturamento_Feito__c = contrato.Locador_a__c,
                Forma_de_pagamento2__c = contrato.Forma_de_pagamento2__c,
                Frete__c = contrato.Tipo_de_Entrega__c,
                Ignora_validacao__c = true,
                Locado_em__c = '-',
                Natureza_de_Opera_o__c = 'LOCAÇÃO',
                Necess_rio_Treinamento__c = 'NÃO',
                Nome_Contato_Financeiro__c = dados.contato.FirstName,
                Pricebook2Id = '01s5A000004fbcR',
                ShippingCity = dados.locatario.ShippingCity,
                ShippingCountry = dados.locatario.ShippingCountry,
                ShippingPostalCode = dados.locatario.ShippingPostalCode,
                ShippingState = dados.locatario.ShippingState,
                ShippingStreet = dados.locatario.ShippingStreet,
                Telefone_Contato__c = dados.telefone,
                Unidade_Hospitalar__c = contrato.Unidade_Hospitalar__c,
                Vendedor__c = contrato.Vendedor_do_Contrato__c,
                Prioridade__c = 'NORMAL',
                Entrega_liberada_pelo_financeiro__c = 'NÃO',
                Pedido_da_Linha_de_OPME__c = 'NÃO',
                CurrencyIsoCode = contrato.CurrencyIsoCode
            );
            pedidos.add(pedido);
        }
    }

    public static Map<String, PricebookEntry> buscaPBEs(Set<String> codigos) {
        Map<String, PricebookEntry> result = new Map<String, PricebookEntry>();
        for (PricebookEntry p : [
            SELECT Id, Product2Id, Product2.ProductCode, CurrencyIsoCode, UnitPrice 
            FROM PricebookEntry 
            WHERE Product2.ProductCode IN :codigos AND Pricebook2Id = '01s5A000004fbcR'
        ]) {
            result.put(p.Product2.ProductCode + 'LOCACAO', p);
        }
        return result;
    }

    public static void criaOrderItems(
        List<Order> pedidos,
        Map<String, PricebookEntry> pbes,
        Map<String, Decimal> quantidades,
        Map<String, Decimal> valores,
        Map<String, String> nomes,
        PedidoData info,
        List<OrderItem> itens,
        String emails
    ) {
        for (Order pedido : pedidos) {
            Integer index = 1;
            for (String codigo : quantidades.keySet()) {
                Decimal qtd = quantidades.get(codigo);
                Decimal total = valores.get(codigo);
                Decimal precoUnit = total / qtd;

                PricebookEntry pbe = pbes.get(codigo);
                OrderItem item = new OrderItem(
                    OrderId = pedido.Id,
                    Product2Id = (pbe != null ? pbe.Product2Id : '01t6e000009ZTsV'),
                    PricebookEntryId = (pbe != null ? pbe.Id : '01u6e000019dnXM'),
                    Quantity = qtd,
                    UnitPrice = precoUnit,
                    Item__c = index++,
                    Status__c = 'Novo'
                );
                itens.add(item);
            }

            pedido.Observacoes_Gerais__c = gerarObservacoes(quantidades, nomes, pedido.Periodo_do_contrato_inicio__c, pedido.Per_odo_do_contrato_Fim__c, info,  emails);
        }
    }

    public static String gerarObservacoes(Map<String, Decimal> quantidades, Map<String, String> nomes, Date inicio, Date fim, PedidoData info, String emails) {
        String obs = 'REFERENTE A LOCAÇÃO DE ';
    
        for (String codigo : quantidades.keySet()) {
            obs += quantidades.get(codigo) + ' ' + nomes.get(codigo) + '\n';
        }
        
        obs += 'PERÍODO: ' + formatDate(inicio) + ' A ' + formatDate(fim) +  '\n';
        
        if(info.dadosBancarios.pagamentoAdiantado == true){
            obs += 'ENVIAR PARA : ' + emails + '\n';
        } else {
            obs += 'Empresa: ' + info.locador.Raz_o_Social__c + '\n'
                + 'Banco: ' + info.dadosBancarios.banco + '\n'
                + 'Agência: ' + info.dadosBancarios.agencia + '\n'
                + 'Conta Corrente: ' + info.dadosBancarios.contaCorrente + '\n'
                + 'CNPJ: ' + info.locador.CNPJ__c + '\n'
                + 'ENVIAR PARA : ' + emails + '\n';
        }

        return obs;
    }

    public static String formatDate(Date d) {
         return (d.day() < 10 ? '0' + String.valueOf(d.day()) : String.valueOf(d.day())) + '/' + 
           (d.month() < 10 ? '0' + String.valueOf(d.month()) : String.valueOf(d.month())) + '/' + 
           String.valueOf(d.year());
    }

    public static DadosBancarios getDadosBancarios(String original){

        DadosBancarios dados = new DadosBancarios();

        if(FORMAS_PAGAMENTOS_ADIANTADOS.contains(original)){
            dados.pagamentoAdiantado = true;
            return dados;
        }

        if(original == 'R- Banco Caixa Econômica Federal Ag.2512 C/C 4001-4 - Hospcom'){
            dados.banco = 'Caixa Econômica Federal';
            dados.agencia = '2512';
            dados.contaCorrente = '4001-4';
            return dados;
        }
        
        String modificado = original.replace('Ag: ', '');
        String modificado2 = modificado.replace('Cc: ', ' - ');
        List<String> partes = modificado2.split(' - ');

        dados.banco = partes[1];
        dados.agencia = partes[2];
        dados.contaCorrente = partes[3];

        return dados;
    }

    public class PedidoData {
        public Contact contato;
        public Account locatario;
        public Account locador;
        public Integer numeroDias;
        public String telefone;
        public Date dataInicial;
        public DadosBancarios dadosBancarios;
    }

    public class DadosBancarios {
        public String banco;
        public String agencia;
        public String contaCorrente;
        public Boolean pagamentoAdiantado;
    }
}