force-app/main/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Raz_o_Social__c.field-meta.xml
<CustomField>
    <fullName>Raz_o_Social__c</fullName>
    <label>Razão social</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>-</fullName>
            </value>
            <value>
                <fullName>3M</fullName>
            </value>
            <value>
                <fullName>ABX</fullName>
            </value>
            <value>
                <fullName>AGFA</fullName>
            </value>
            <value>
                <fullName>AINCA</fullName>
            </value>
            <value>
                <fullName>AIR LIQUIDE</fullName>
            </value>
            <value>
                <fullName>AIRSEP</fullName>
            </value>
            <value>
                <fullName>AIR SHIELD</fullName>
            </value>
            <value>
                <fullName>AKTILITE</fullName>
            </value>
            <value>
                <fullName>ALERON</fullName>
            </value>
            <value>
                <fullName>ALOHA MED</fullName>
            </value>
            <value>
                <fullName>ALPHA MED</fullName>
            </value>
            <value>
                <fullName>AMCOR</fullName>
            </value>
            <value>
                <fullName>ANGIOTECH</fullName>
            </value>
            <value>
                <fullName>AOC</fullName>
            </value>
            <value>
                <fullName>APRAMED</fullName>
            </value>
            <value>
                <fullName>ARJO</fullName>
            </value>
            <value>
                <fullName>ARTHREX</fullName>
            </value>
            <value>
                <fullName>ASCLEPIOS</fullName>
            </value>
            <value>
                <fullName>ASPIRAMAX</fullName>
            </value>
            <value>
                <fullName>AUTOM</fullName>
            </value>
            <value>
                <fullName>BALMAK</fullName>
            </value>
            <value>
                <fullName>BARBI</fullName>
            </value>
            <value>
                <fullName>BAUMER</fullName>
            </value>
            <value>
                <fullName>BAXTER</fullName>
            </value>
            <value>
                <fullName>BBRAUN</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>BEACON</fullName>
            </value>
            <value>
                <fullName>BELTEC</fullName>
            </value>
            <value>
                <fullName>BENFER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/patrimonio__c.field-meta.xml
<CustomField>
    <fullName>patrimonio__c</fullName>
    <label>Patrimônio</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/URL_da_Imagem__c.field-meta.xml
<CustomField>
    <fullName>URL_da_Imagem__c</fullName>
    <label>URL da Imagem</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <label>CPF</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Condicao_de_pagamento__c.field-meta.xml
<CustomField>
    <fullName>Condicao_de_pagamento__c</fullName>
    <label>Condição de pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Natureza_de_Opera_o__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Condicoes_de_pagamento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Forma_de_pagamento2__c.field-meta.xml
<CustomField>
    <fullName>Forma_de_pagamento2__c</fullName>
    <label>Forma de pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Natureza_de_Opera_o__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Formas_de_pagamento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Prazo_de_entrega__c.field-meta.xml
<CustomField>
    <fullName>Prazo_de_entrega__c</fullName>
    <label>Prazo de entrega</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Raz_o_Social__c.field-meta.xml
<CustomField>
    <fullName>Raz_o_Social__c</fullName>
    <formula>Account.Raz_o_Social__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>_Razão Social (del)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/recordTypes/Hospcom.recordType-meta.xml
<RecordType>
    <fullName>Hospcom</fullName>
    <active>true</active>
    <description>Para faturamento das empresas do grupo Hospcom</description>
    <label>Hospcom</label>
</RecordType>

force-app/main/default/objects/Product2/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>3GREEN</fullName>
            </value>
            <value>
                <fullName>7LIVES</fullName>
            </value>
            <value>
                <fullName>ABC</fullName>
            </value>
            <value>
                <fullName>ACCUMED</fullName>
            </value>
            <value>
                <fullName>ACROSS</fullName>
            </value>
            <value>
                <fullName>ACTE</fullName>
            </value>
            <value>
                <fullName>AEROGEN</fullName>
            </value>
            <value>
                <fullName>AGATA</fullName>
            </value>
            <value>
                <fullName>AGILE MED</fullName>
            </value>
            <value>
                <fullName>AIR LIQUIDE</fullName>
            </value>
            <value>
                <fullName>AIR SHIELD</fullName>
            </value>
            <value>
                <fullName>AJEL</fullName>
            </value>
            <value>
                <fullName>ALBAN</fullName>
            </value>
            <value>
                <fullName>ALIVE HEART</fullName>
            </value>
            <value>
                <fullName>ALLIAGE</fullName>
            </value>
            <value>
                <fullName>ALPHARAD</fullName>
            </value>
            <value>
                <fullName>ALVFLOR</fullName>
            </value>
            <value>
                <fullName>ALVIMÉDICA</fullName>
            </value>
            <value>
                <fullName>ANALYSER</fullName>
            </value>
            <value>
                <fullName>ANATONIC</fullName>
            </value>
            <value>
                <fullName>ANESTHESIA</fullName>
            </value>
            <value>
                <fullName>AOC</fullName>
            </value>
            <value>
                <fullName>APC</fullName>
            </value>
            <value>
                <fullName>APK</fullName>
            </value>
            <value>
                <fullName>APPLE</fullName>
            </value>
            <value>
                <fullName>ARJO</fullName>
            </value>
            <value>
                <fullName>ARJOHUNTLEIGH</fullName>
            </value>
            <value>
                <fullName>ARKTUS</fullName>
            </value>
            <value>
                <fullName>ARTIS</fullName>
            </value>
            <value>
                <fullName>ARTROCORP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Modelo__c.field-meta.xml
<CustomField>
    <fullName>Modelo__c</fullName>
    <label>Modelo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/URL_da_Imagem__c.field-meta.xml
<CustomField>
    <fullName>URL_da_Imagem__c</fullName>
    <defaultValue>&quot;https://hospcom.my.site.com/servlet/servlet.ImageServer?id=015310000080hog&amp;oid=00Di0000000JVhH&amp;lastMod=1502888568000&quot;</defaultValue>
    <label>URL da Imagem</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Solution/recordTypes/Ordem_de_Trabalho.recordType-meta.xml
<RecordType>
    <fullName>Ordem_de_Trabalho</fullName>
    <active>true</active>
    <businessProcess>Ordem de Trabalho</businessProcess>
    <label>Ordem de Trabalho</label>
</RecordType>

force-app/main/default/objects/WorkOrder/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <formula>IF(
    Account.CNPJ__c &lt;&gt; &quot;&quot;, 
    Account.CNPJ__c, 
    IF(
        Account.CPF__pc &lt;&gt; &quot;&quot;, 
        Account.CPF__pc, 
        &quot;&quot;
    )
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CNPJ/CPF</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Condicao_de_pagamento__c.field-meta.xml
<CustomField>
    <fullName>Condicao_de_pagamento__c</fullName>
    <label>Condição de pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Condicoes_de_pagamento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Data_de_emissao__c.field-meta.xml
<CustomField>
    <fullName>Data_de_emissao__c</fullName>
    <label>Data de emissao</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Data_de_validade__c.field-meta.xml
<CustomField>
    <fullName>Data_de_validade__c</fullName>
    <label>Data de validade</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Declara_es__c.field-meta.xml
<CustomField>
    <fullName>Declara_es__c</fullName>
    <label>Declarações</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Faturamento_Feito2__c.field-meta.xml
<CustomField>
    <fullName>Faturamento_Feito2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Faturado por (empresa)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Faturamentos Feitos (de ordens de trabalho)</relationshipLabel>
    <relationshipName>Ordens_de_trabalho</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Forma_de_pagamento2__c.field-meta.xml
<CustomField>
    <fullName>Forma_de_pagamento2__c</fullName>
    <label>Forma de pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Formas_de_pagamento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Frete2__c.field-meta.xml
<CustomField>
    <fullName>Frete2__c</fullName>
    <label>Tipo de envio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipos_de_envio</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <formula>TEXT( Asset.Marca__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Marca</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Modelo__c.field-meta.xml
<CustomField>
    <fullName>Modelo__c</fullName>
    <formula>Asset.Modelo__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Modelo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Patrimonio__c.field-meta.xml
<CustomField>
    <fullName>Patrimonio__c</fullName>
    <formula>Asset.patrimonio__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Patrimônio</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Prazo_de_entrega__c.field-meta.xml
<CustomField>
    <fullName>Prazo_de_entrega__c</fullName>
    <label>Prazo de entrega</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Prazo_de_garantia__c.field-meta.xml
<CustomField>
    <fullName>Prazo_de_garantia__c</fullName>
    <label>Prazo de garantia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Item_Pai__c.field-meta.xml
<CustomField>
    <fullName>Item_Pai__c</fullName>
    <label>Item Pai</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <formula>TEXT(Product2.Marca__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Marca</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Modelo__c.field-meta.xml
<CustomField>
    <fullName>Modelo__c</fullName>
    <formula>Product2.Modelo__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Modelo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Tipos_de_envio.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Contratação do Frete por conta do Remetente (CIF)</fullName>
    </customValue>
    <customValue>
        <fullName>Contratação do Frete por conta do Destinatário (FOB)</fullName>
    </customValue>
    <customValue>
        <fullName>Contratação do Frete por conta de Terceiros</fullName>
    </customValue>
    <customValue>
        <fullName>Transporte Próprio por conta do Remetente</fullName>
    </customValue>
    <customValue>
        <fullName>Transporte Próprio por conta do Destinatário</fullName>
    </customValue>
    <customValue>
        <fullName>Sem Ocorrência de Transporte.</fullName>
    </customValue>
    <masterLabel>Tipos de envio</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/OrdemDeTrabalhoProposta.cls
public class OrdemDeTrabalhoProposta {
        
        public Documento documento {get;set;}
        public WorkOrder ordem_de_trabalho {get;set;}
        public List<Produto> produtos {get;set;}
        
        public OrdemDeTrabalhoProposta(ApexPages.StandardController controlador){
                
                // ordem de trabalho
                ordem_de_trabalho = [
                        SELECT  WorkOrderNumber, GrandTotal, Condicao_de_pagamento__c, Forma_de_pagamento2__c,
                                        Frete2__c, Prazo_de_Entrega__c,  Prazo_de_garantia__c, Data_de_emissao__c, Data_de_validade__c, CurrencyISOCode,
                                        Account.BillingStreet, Account.BillingCity, Account.BillingStateCode, Account.BillingCountry, Account.BillingPostalCode,
                                        Account.ShippingStreet, Account.ShippingCity, Account.ShippingStateCode, Account.ShippingCountry, Account.ShippingPostalCode,
                                        Account.Name, Account.CNPJ__c, Contact.Name, Contact.CPF__c,
                                        Asset.Name, Asset.Marca__c, Asset.Modelo__c, Asset.SerialNumber, Asset.patrimonio__c, 
                                        Faturamento_Feito2__r.CNPJ__c, Faturamento_Feito2__r.Raz_o_Social__c,
                                        Declara_es__c
                        FROM    WorkOrder
                        WHERE   Id = :((SObject)controlador.getRecord()).Id
                ];
                
                // itens
                List<WorkOrderLineItem> itens = [
                        SELECT  Product2.URL_da_Imagem__c, Product2.StockKeepingUnit, Product2.Name, Product2.Modelo__c, 
                                        Product2.Marca__c, UnitPrice, Quantity, Subtotal, Discount, TotalPrice, Item__c, Item_Pai__c,
                                        Description
                        FROM    WorkOrderLineItem
                        WHERE   WorkOrderId = :((SObject)controlador.getRecord()).Id
                        ORDER BY Item__c ASC NULLS LAST
                ];
                
                List<WorkOrderLineItem> itens_ordem = new List<WorkOrderLineItem>();
                for(WorkOrderLineItem item_equip : itens)
                        if(item_equip.Item__c!=null && item_equip.Item_Pai__c==null){
                                itens_ordem.add(item_equip);
                                for(WorkOrderLineItem item_acess : itens)
                                        if(item_acess.Item_Pai__c==item_equip.Item__c)
                                                itens_ordem.add(item_acess);
                        }
                for(WorkOrderLineItem item_vazio : itens)
                        if(item_vazio.Item__c==null && item_vazio.Item_Pai__c==null)
                                itens_ordem.add(item_vazio);
                
                produtos = new List<Produto>();
                Decimal subtotal = 0;
                for(Integer cont=0; cont<itens_ordem.size(); cont++){
                        Produto produto = new Produto(itens_ordem[cont]);
                        subtotal += itens_ordem[cont].TotalPrice;
                        
                        String anterior = (cont==0?null:(itens_ordem[cont-1].Item_Pai__c==null?'equipamento':'acessorio'));
                        String atual = (itens_ordem[cont].Item_Pai__c==null?'equipamento':'acessorio');
                        String proximo = (cont==itens_ordem.size()-1?null:(itens_ordem[cont+1].Item_Pai__c==null?'equipamento':'acessorio'));
                        
                        if((atual=='equipamento'&& proximo=='acessorio') || ((anterior==null||anterior=='acessorio') && (atual=='equipamento' && (proximo=='equipamento'||proximo==null))))
                                produto.cabecalho = true;
                        if((anterior=='equipamento'||anterior=='acessorio') && atual=='acessorio' && (proximo=='equipamento'||proximo==null)){
                                produto.subtotal = ordem_de_trabalho.CurrencyISOCode+' '+String.valueOf(subtotal.format());
                                if(!produto.subtotal.contains(',')) produto.subtotal += ',00';
                                else if(produto.subtotal.substringAfter(',').length()==1) produto.subtotal += '0';
                                subtotal = 0;
                        }
                        
                        produtos.add(produto);
                }
                
                // documento
                documento = new Documento();
                if(ordem_de_trabalho.Faturamento_Feito2__r.CNPJ__c == '27.476.124/0001-02'){
                        documento.timbrado = PageReference.forResource('TimbradoHealth').getUrl();
                        documento.sobre = PageReference.forResource('SobreHealth').getUrl();
                        documento.empresa_nome = 'HEALTH SOLUTION COMERCIO E SERIVÇOS - EIRELE - ME';
                        documento.empresa_dados = 'inscrita no CNPJ sob N° 27.476.124/0001-02, sediada na Rua 89, N° 717, Qd. F45A, Lt. 81/83, Setor Sul, Goiânia - GO, CEP 74093-140';
                        documento.empresa_bancario = 'Banco do Brasil - Agência 1610-1 - Conta Corrente 128.057-0';                       
                }
                else if(ordem_de_trabalho.Faturamento_Feito2__r.CNPJ__c == '23.813.386/0001-56'){
                        documento.timbrado = PageReference.forResource('TimbradoGDB').getUrl();
                        documento.sobre = PageReference.forResource('SobreGDB').getUrl();
                        documento.empresa_nome = 'GDB COMÉRCIO E SERVIÇOS - EIRELI - EPP';
                        documento.empresa_dados = 'inscrita no CNPJ sob N° 23.813.386/0001-56, sediada na Rua Antônio Viera, N° 76, Jardim Bela Vista, Campo Grande - MS, CEP 79003-071';
                        documento.empresa_bancario = 'Banco do Brasil - Agência 1242-4 - Conta Corrente 47391-X';
                }
                else if(ordem_de_trabalho.Faturamento_Feito2__r.CNPJ__c == '05.743.288/0001-08'){
                        documento.timbrado = PageReference.forResource('TimbradoHospcom').getUrl();
                        documento.sobre = PageReference.forResource('SobreHospcom').getUrl();
                        documento.empresa_nome = 'HOSPCOM EQUIPAMENTOS HOSPITALARES - EIRELI';
                        documento.empresa_dados = 'inscrita no CNPJ sob N° 05.743.288/0001-08, sediada na Rua 104, N° 74, Setor Sul, Goiânia - GO, CEP 74083-300';
                        documento.empresa_bancario = 'Banco do Brasil - Agência 1242-4 - Conta Corrente 69869-5';
                }else{
                        documento.timbrado = PageReference.forResource('TimbradoHospcom').getUrl();
                        documento.sobre = PageReference.forResource('SobreHospcom').getUrl();
                        documento.empresa_nome = 'HOSPCOM EQUIPAMENTOS HOSPITALARES - EIRELI';
                        documento.empresa_dados = 'inscrita no CNPJ sob N° 05.743.288/0001-08, sediada na Rua 104, N° 74, Setor Sul, Goiânia - GO, CEP 74083-300';
                }
                
                documento.titulo = 'P  r  o  p  o  s  t  a     d  e     S  e  r  v  i  ç  o';
                
        }
        
        public class Produto{
                public Boolean cabecalho{get;set;}
                public WorkOrderLineItem item{get;set;}
                public String subtotal{get;set;}
                
                public Produto(WorkOrderLineItem item){
                        this.cabecalho = false;
                        this.item = item;
                        this.subtotal = null;
                }
        }
    
        public class Documento{
                public String timbrado{get;set;}
                public String sobre{get;set;}
                public String titulo{get;set;}
                public String empresa_nome {get;set;}
                public String empresa_dados {get;set;}
                public String empresa_bancario {get;set;}
                
                public Documento(){}
        }
    
}