force-app/main/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/NIT__c.field-meta.xml
<CustomField>
    <fullName>NIT__c</fullName>
    <inlineHelpText>Formato XXX.XXX.XXX - Y</inlineHelpText>
    <label>NIT</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <label>CPF</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Condicao_de_pagamento__c.field-meta.xml
<CustomField>
    <fullName>Condicao_de_pagamento__c</fullName>
    <label>Condição de pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Condicoes_de_pagamento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Prazo_de_entrega__c.field-meta.xml
<CustomField>
    <fullName>Prazo_de_entrega__c</fullName>
    <label>Prazo de entrega pedido</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Prazo_de_garantia__c.field-meta.xml
<CustomField>
    <fullName>Prazo_de_garantia__c</fullName>
    <defaultValue>&quot;equipamentos 12 meses, acessórios 3 meses&quot;</defaultValue>
    <inlineHelpText>Ex: equipamentos 12 meses, acessórios 3 meses, etc...</inlineHelpText>
    <label>Prazo de garantia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Prazo_de_garantia_acessorios__c.field-meta.xml
<CustomField>
    <fullName>Prazo_de_garantia_acessorios__c</fullName>
    <defaultValue>TEXT(3) + &apos; meses&apos;</defaultValue>
    <label>Prazo de garantia dos acessórios</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Prazo_de_garantia_dos_equipamentos__c.field-meta.xml
<CustomField>
    <fullName>Prazo_de_garantia_dos_equipamentos__c</fullName>
    <defaultValue>TEXT(12) + &apos; meses&apos;</defaultValue>
    <label>Prazo de garantia dos equipamentos</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Condicao_de_pagamento__c.field-meta.xml
<CustomField>
    <fullName>Condicao_de_pagamento__c</fullName>
    <label>Condição de pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Natureza_de_Opera_o__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Condicoes_de_pagamento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Forma_de_pagamento__c.field-meta.xml
<CustomField>
    <fullName>Forma_de_pagamento__c</fullName>
    <label>_Forma de pagamento (del)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A VISTA NO PEDIDO</fullName>
            </value>
            <value>
                <fullName>A VISTA CONTRA EMBARQUE</fullName>
            </value>
            <value>
                <fullName>FINANCIAMENTO BANCÁRIO</fullName>
            </value>
            <value>
                <fullName>OPEN ACCOUNT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Frete__c.field-meta.xml
<CustomField>
    <fullName>Frete__c</fullName>
    <label>Tipo de envio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipos_de_envio</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Prazo_de_entrega__c.field-meta.xml
<CustomField>
    <fullName>Prazo_de_entrega__c</fullName>
    <label>Prazo de entrega</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/recordTypes/Hospcom.recordType-meta.xml
<RecordType>
    <fullName>Hospcom</fullName>
    <active>true</active>
    <description>Para faturamento das empresas do grupo Hospcom</description>
    <label>Hospcom</label>
</RecordType>

force-app/main/default/objects/Quote/fields/Forma_de_pagamento__c.field-meta.xml
<CustomField>
    <fullName>Forma_de_pagamento__c</fullName>
    <label>Forma de pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Formas_de_pagamento</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Frete__c.field-meta.xml
<CustomField>
    <fullName>Frete__c</fullName>
    <label>Tipo de envio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tipos_de_envio</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Prazo_de_Entrega__c.field-meta.xml
<CustomField>
    <fullName>Prazo_de_Entrega__c</fullName>
    <label>Prazo de entrega</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Prazo_de_garantia__c.field-meta.xml
<CustomField>
    <fullName>Prazo_de_garantia__c</fullName>
    <defaultValue>&quot;Equipamentos &quot; + TEXT(12) + &quot; meses, acessórios &quot; + TEXT(3) + &quot; meses&quot;</defaultValue>
    <inlineHelpText>Ex: Equipamentos 12 meses, acessórios 3 meses, etc...</inlineHelpText>
    <label>Prazo de garantia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Prazo_de_garantia_acessorios__c.field-meta.xml
<CustomField>
    <fullName>Prazo_de_garantia_acessorios__c</fullName>
    <defaultValue>TEXT(3) + &apos; meses&apos;</defaultValue>
    <inlineHelpText>Ex: 3 meses</inlineHelpText>
    <label>Prazo de garantia dos acessórios</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Prazo_de_garantia_dos_equipamentos__c.field-meta.xml
<CustomField>
    <fullName>Prazo_de_garantia_dos_equipamentos__c</fullName>
    <defaultValue>TEXT(12) + &apos; meses&apos;</defaultValue>
    <inlineHelpText>Ex: 12 meses</inlineHelpText>
    <label>Prazo de garantia dos equipamentos</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Tem_entrada__c.field-meta.xml
<CustomField>
    <fullName>Tem_entrada__c</fullName>
    <label>Tem entrada</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sim</fullName>
            </value>
            <value>
                <fullName>Não</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Tipos_de_envio.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Contratação do Frete por conta do Remetente (CIF)</fullName>
    </customValue>
    <customValue>
        <fullName>Contratação do Frete por conta do Destinatário (FOB)</fullName>
    </customValue>
    <customValue>
        <fullName>Contratação do Frete por conta de Terceiros</fullName>
    </customValue>
    <customValue>
        <fullName>Transporte Próprio por conta do Remetente</fullName>
    </customValue>
    <customValue>
        <fullName>Transporte Próprio por conta do Destinatário</fullName>
    </customValue>
    <customValue>
        <fullName>Sem Ocorrência de Transporte.</fullName>
    </customValue>
    <masterLabel>Tipos de envio</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CotacaoBotoes.cls
public with sharing class CotacaoBotoes {
    
    
    @AuraEnabled
    public static Boolean validaStatus(String cot_id){
        Quote cotacao = [
        SELECT Status
        FROM Quote 
        WHERE Id = :cot_id
    ];
        
        return cotacao.Status != 'Rascunho' &&
            cotacao.Status != 'Aguardando Aprovação' &&
            cotacao.Status != 'Reprovado';
    }
    
    @AuraEnabled
    public static String ValidarPreenchimento(String cot_id){
        String retorno='';
        List<String> erros = new List<String>();
        
        // campos
        Quote cotacao = [
            SELECT  Forma_de_pagamento__c, Tem_entrada__c, Condicao_de_pagamento__c, Frete__c, Prazo_de_Entrega__c, Prazo_de_garantia__c, ContactId, Prazo_de_garantia_dos_equipamentos__c, Prazo_de_garantia_acessorios__c,
                    ExpirationDate, Contact.CPF__c, Account.NIT__c, Account.CNPJ__c, Account.RG__pc, OpportunityId, Opportunity.RecordType.Name,(
                        SELECT  Id
                        FROM    QuoteLineItems
                    )
            FROM    Quote 
            WHERE   Id = :cot_id
        ];
        if(cotacao.Condicao_de_pagamento__c==null)
            erros.add('Condição de pagamento');
        if(cotacao.Frete__c==null)
            erros.add('Tipo de envio');
        if(cotacao.Tem_entrada__c==null)
            erros.add('Tem entrada');
        if(cotacao.Prazo_de_garantia__c==null)
            erros.add('Prazo de garantia');
        if(cotacao.ContactId==null)
            erros.add('Nome do contato');
        if(cotacao.Prazo_de_garantia_dos_equipamentos__c==null)
            erros.add('Prazo de garantia dos equipamentos');
        if(cotacao.Prazo_de_garantia_acessorios__c==null)
            erros.add('Prazo de garantia dos acessórios');
        if(cotacao.Account.CNPJ__c==null && cotacao.Account.RG__pc==null && cotacao.Account.NIT__c ==null)
            erros.add('RG do cliente');
        //if(cotacao.Account.NIT__c == null && cotacao.Contact.CPF__c == null)
        //erros.add('CPF do cliente');
        if(erros.size()>0)
            retorno += '<br/> - Preencha os campos: ' + String.join(erros, ', ') + '.';
        
        // produtos
        if(cotacao.QuoteLineItems.size()==0)
            retorno += '<br/> - Adicione produtos na Cotação.';
        
        if(cotacao.ExpirationDate < system.today())
            retorno += '<br/> A data de validade não pode ser inferior à data de hoje.';
        
        // signatario
        if(cotacao.Opportunity.RecordType.Name=='Licitação'){
            List<OpportunityContactRole> signatario = [
                SELECT  Id
                FROM    OpportunityContactRole
                WHERE   Role = 'Signatário da proposta (Hospcom)' AND
                        OpportunityId = :cotacao.OpportunityId
                ORDER BY LastModifiedDate DESC
                LIMIT   1
            ];
            if(signatario.size()!=1)
                retorno += '<br/> - Atribua um signatário à oportunidade.';
        }
        
        // mensagem
        if(retorno!='')
            retorno = 'Revise os seguintes pontos para gerar a proposta: ' + retorno;
        
        return retorno;
    }
    
    @AuraEnabled
    public static Boolean VerificarLicitacao(String cot_id){
        return ([SELECT Opportunity.RecordType.Name FROM Quote WHERE Id = :cot_id].Opportunity.RecordType.Name=='Licitação')?true:false;
    }
    
    @AuraEnabled
    public static void SalvarPdfProposta(String cot_id){
        
        PageReference prop_pag = new PageReference('/apex/CotacaoProposta');
        prop_pag.getParameters().put('Id', cot_id);
        
        Blob prop_blob = (!Test.isRunningTest() ? prop_pag.getContent() : Blob.valueOf('teste'));
        
        String prop_nome = [SELECT Name FROM Quote WHERE Id = :cot_id].Name;
        
        ContentVersion prop_ver = new ContentVersion(
            PathOnClient = prop_nome+' ('+System.Now().format('yyyy-MM-dd\' \'hh:mm:ss')+').pdf',
        Title = prop_nome+' ('+System.Now().format('yyyy-MM-dd\' \'hh:mm:ss')+')',
        VersionData = prop_blob
            );
        insert prop_ver;
        
        prop_ver = [SELECT contentDocumentId FROM ContentVersion WHERE Id = :prop_ver.Id];
        ContentDocumentLink prop_link = new ContentDocumentLink(
            ContentDocumentId = prop_ver.ContentDocumentId,
        LinkedEntityId = cot_id,
        ShareType = 'I',
        Visibility = 'AllUsers'
            );
        insert prop_link;
    }
    
    @AuraEnabled
    public static void SalvarPdfCotacao(String cot_id){
        
        PageReference prop_pag = new PageReference('/apex/CotacaoContrato');
        prop_pag.getParameters().put('Id', cot_id);
        
        Blob prop_blob = (!Test.isRunningTest() ? prop_pag.getContent() : Blob.valueOf('teste'));
        
        String prop_nome = [SELECT Name FROM Quote WHERE Id = :cot_id].Name;
        
        ContentVersion prop_ver = new ContentVersion(
            PathOnClient = prop_nome+' ('+System.Now().format('yyyy-MM-dd\' \'hh:mm:ss')+').pdf',
        Title = prop_nome+' ('+System.Now().format('yyyy-MM-dd\' \'hh:mm:ss')+')',
        VersionData = prop_blob
            );
        insert prop_ver;
        
        prop_ver = [SELECT contentDocumentId FROM ContentVersion WHERE Id = :prop_ver.Id];
        ContentDocumentLink prop_link = new ContentDocumentLink(
            ContentDocumentId = prop_ver.ContentDocumentId,
        LinkedEntityId = cot_id,
        ShareType = 'I',
        Visibility = 'AllUsers'
            );
        insert prop_link;
    }
}