force-app/main/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Raz_o_Social__c.field-meta.xml
<CustomField>
    <fullName>Raz_o_Social__c</fullName>
    <label>Razão social</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>-</fullName>
            </value>
            <value>
                <fullName>3M</fullName>
            </value>
            <value>
                <fullName>ABX</fullName>
            </value>
            <value>
                <fullName>AGFA</fullName>
            </value>
            <value>
                <fullName>AINCA</fullName>
            </value>
            <value>
                <fullName>AIR LIQUIDE</fullName>
            </value>
            <value>
                <fullName>AIRSEP</fullName>
            </value>
            <value>
                <fullName>AIR SHIELD</fullName>
            </value>
            <value>
                <fullName>AKTILITE</fullName>
            </value>
            <value>
                <fullName>ALERON</fullName>
            </value>
            <value>
                <fullName>ALOHA MED</fullName>
            </value>
            <value>
                <fullName>ALPHA MED</fullName>
            </value>
            <value>
                <fullName>AMCOR</fullName>
            </value>
            <value>
                <fullName>ANGIOTECH</fullName>
            </value>
            <value>
                <fullName>AOC</fullName>
            </value>
            <value>
                <fullName>APRAMED</fullName>
            </value>
            <value>
                <fullName>ARJO</fullName>
            </value>
            <value>
                <fullName>ARTHREX</fullName>
            </value>
            <value>
                <fullName>ASCLEPIOS</fullName>
            </value>
            <value>
                <fullName>ASPIRAMAX</fullName>
            </value>
            <value>
                <fullName>AUTOM</fullName>
            </value>
            <value>
                <fullName>BALMAK</fullName>
            </value>
            <value>
                <fullName>BARBI</fullName>
            </value>
            <value>
                <fullName>BAUMER</fullName>
            </value>
            <value>
                <fullName>BAXTER</fullName>
            </value>
            <value>
                <fullName>BBRAUN</fullName>
            </value>
            <value>
                <fullName>BD</fullName>
            </value>
            <value>
                <fullName>BEACON</fullName>
            </value>
            <value>
                <fullName>BELTEC</fullName>
            </value>
            <value>
                <fullName>BENFER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/URL_da_Imagem__c.field-meta.xml
<CustomField>
    <fullName>URL_da_Imagem__c</fullName>
    <label>URL da Imagem</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Checklist_do_Ativo__c/Checklist_do_Ativo__c.object-meta.xml
<CustomObject>
    <label>Item de Checklist do Ativo</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Nome de Checklist do Ativo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens de Checklist do Ativo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Checklist_do_Ativo__c/fields/Ativo__c.field-meta.xml
<CustomField>
    <fullName>Ativo__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Checklist_do_Ativo__c/fields/Ativo_Relacionado__c.field-meta.xml
<CustomField>
    <fullName>Ativo_Relacionado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ativo Relacionado</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Itens de Checklist do Ativo</relationshipLabel>
    <relationshipName>Itens_de_Checklist_do_Ativo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Checklist_do_Ativo__c/fields/Conforme__c.field-meta.xml
<CustomField>
    <fullName>Conforme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Conforme</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Checklist_do_Ativo__c/fields/N_o_Conforme__c.field-meta.xml
<CustomField>
    <fullName>N_o_Conforme__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Não Conforme</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Checklist_do_Ativo__c/fields/Nome_do_Item__c.field-meta.xml
<CustomField>
    <fullName>Nome_do_Item__c</fullName>
    <label>Nome do Item</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Checklist_do_Ativo__c/fields/Quantidade__c.field-meta.xml
<CustomField>
    <fullName>Quantidade__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Quantidade</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Demonstracao__c/Demonstracao__c.object-meta.xml
<CustomObject>
    <label>Comodato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comodatos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Demonstracao__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Demonstracoes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demonstracao__c/fields/Fornecedor__c.field-meta.xml
<CustomField>
    <fullName>Fornecedor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Fornecedor</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Demonstracoes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demonstracao__c/recordTypes/Demonstracao.recordType-meta.xml
<RecordType>
    <fullName>Demonstracao</fullName>
    <active>false</active>
    <description>Para contratos de demonstração</description>
    <label>Demonstração</label>
</RecordType>

force-app/main/default/objects/Order/fields/Demonstracao__c.field-meta.xml
<CustomField>
    <fullName>Demonstracao__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Comodato</label>
    <referenceTo>Demonstracao__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Raz_o_Social__c.field-meta.xml
<CustomField>
    <fullName>Raz_o_Social__c</fullName>
    <formula>Account.Raz_o_Social__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>_Razão Social (del)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/recordTypes/Demonstracao.recordType-meta.xml
<RecordType>
    <fullName>Demonstracao</fullName>
    <active>true</active>
    <description>Exclusivo para pedidos de demonstração</description>
    <label>Demonstração</label>
</RecordType>

force-app/main/default/objects/Product2/fields/Fornecedor__c.field-meta.xml
<CustomField>
    <fullName>Fornecedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fornecedor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Produtos</relationshipLabel>
    <relationshipName>Produtos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>3GREEN</fullName>
            </value>
            <value>
                <fullName>7LIVES</fullName>
            </value>
            <value>
                <fullName>ABC</fullName>
            </value>
            <value>
                <fullName>ACCUMED</fullName>
            </value>
            <value>
                <fullName>ACROSS</fullName>
            </value>
            <value>
                <fullName>ACTE</fullName>
            </value>
            <value>
                <fullName>AEROGEN</fullName>
            </value>
            <value>
                <fullName>AGATA</fullName>
            </value>
            <value>
                <fullName>AGILE MED</fullName>
            </value>
            <value>
                <fullName>AIR LIQUIDE</fullName>
            </value>
            <value>
                <fullName>AIR SHIELD</fullName>
            </value>
            <value>
                <fullName>AJEL</fullName>
            </value>
            <value>
                <fullName>ALBAN</fullName>
            </value>
            <value>
                <fullName>ALIVE HEART</fullName>
            </value>
            <value>
                <fullName>ALLIAGE</fullName>
            </value>
            <value>
                <fullName>ALPHARAD</fullName>
            </value>
            <value>
                <fullName>ALVFLOR</fullName>
            </value>
            <value>
                <fullName>ALVIMÉDICA</fullName>
            </value>
            <value>
                <fullName>ANALYSER</fullName>
            </value>
            <value>
                <fullName>ANATONIC</fullName>
            </value>
            <value>
                <fullName>ANESTHESIA</fullName>
            </value>
            <value>
                <fullName>AOC</fullName>
            </value>
            <value>
                <fullName>APC</fullName>
            </value>
            <value>
                <fullName>APK</fullName>
            </value>
            <value>
                <fullName>APPLE</fullName>
            </value>
            <value>
                <fullName>ARJO</fullName>
            </value>
            <value>
                <fullName>ARJOHUNTLEIGH</fullName>
            </value>
            <value>
                <fullName>ARKTUS</fullName>
            </value>
            <value>
                <fullName>ARTIS</fullName>
            </value>
            <value>
                <fullName>ARTROCORP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Modelo__c.field-meta.xml
<CustomField>
    <fullName>Modelo__c</fullName>
    <label>Modelo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Quantidade__c.field-meta.xml
<CustomField>
    <fullName>Quantidade__c</fullName>
    <label>Quantidade</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/URL_da_Imagem__c.field-meta.xml
<CustomField>
    <fullName>URL_da_Imagem__c</fullName>
    <defaultValue>&quot;https://hospcom.my.site.com/servlet/servlet.ImageServer?id=015310000080hog&amp;oid=00Di0000000JVhH&amp;lastMod=1502888568000&quot;</defaultValue>
    <label>URL da Imagem</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Produto_da_demonstracao__c/Produto_da_demonstracao__c.object-meta.xml
<CustomObject>
    <label>Ativo do comodato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ativos do comodato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Produto_da_demonstracao__c/fields/Ativo__c.field-meta.xml
<CustomField>
    <fullName>Ativo__c</fullName>
    <label>Ativo</label>
    <referenceTo>Asset</referenceTo>
    <relationshipName>Produtos_da_demonstracao</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Produto_da_demonstracao__c/fields/Demonstracao__c.field-meta.xml
<CustomField>
    <fullName>Demonstracao__c</fullName>
    <label>Comodato</label>
    <referenceTo>Demonstracao__c</referenceTo>
    <relationshipName>Produtos_da_demonstracao</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Produto_da_demonstracao__c/fields/Descricao__c.field-meta.xml
<CustomField>
    <fullName>Descricao__c</fullName>
    <label>Descrição</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Produto_da_demonstracao__c/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Produto_da_demonstracao__c/fields/Item_pai__c.field-meta.xml
<CustomField>
    <fullName>Item_pai__c</fullName>
    <label>Item pai</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Produto_da_demonstracao__c/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <formula>TEXT(Ativo__r.Product2.Marca__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Marca</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Produto_da_demonstracao__c/fields/Valor__c.field-meta.xml
<CustomField>
    <fullName>Valor__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Valor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/DemonstracaoChecklist.cls
public class DemonstracaoChecklist {
	
	public Documento documento {get;set;}
	public Demonstracao__c demonstracao {get;set;}
	public List<Produto> produtos {get;set;}
	public String tipo_check {get;set;}
    public List<Asset> Ativos {get;set;}
    public Asset ativo {get;set;}
    
	public DemonstracaoChecklist(ApexPages.StandardController controlador){
		tipo_check = System.currentPageReference().getParameters().get('tipo');
        Ativos = [SELECT ID, NAME, SerialNumber, Product2.Modelo__c, Product2.Marca__c, Description, Product2.URL_da_Imagem__c, Product2.StockKeepingUnit, (SELECT Name, Nome_do_Item__c, Quantidade__c, Conforme__c, N_o_Conforme__c From Itens_de_Checklist_do_Ativo__r) FROM ASSET WHERE ID IN (SELECT Ativo__c FROM Produto_da_demonstracao__c WHERE Demonstracao__c =:((SObject)controlador.getRecord()).Id) ORDER BY Name DESC ];
		
		// demonstração
		demonstracao = [
			SELECT	Name, Conta__r.RecordType.Name, Conta__r.Raz_o_Social__c, Conta__r.Name, Conta__r.CNPJ__c, Conta__r.CPF__pc, 
					Fornecedor__r.CNPJ__c, CurrencyISOCode
			FROM	Demonstracao__c
			WHERE	Id = :((SObject)controlador.getRecord()).Id
		];
		
		// itens
		List<Produto_da_demonstracao__c> itens = [
			SELECT	Ativo__r.Product2.URL_da_Imagem__c, Ativo__r.Product2.StockKeepingUnit, Ativo__r.Product2.Name, Ativo__r.Product2.Modelo__c, Ativo__r.Id, 
					Ativo__r.Product2.Marca__c, Ativo__r.SerialNumber, Valor__c, Item__c, Item_Pai__c, Descricao__c        
                    
			FROM	Produto_da_Demonstracao__c
			WHERE	Demonstracao__c = :((SObject)controlador.getRecord()).Id
			ORDER BY Item__c ASC NULLS LAST
		];
        
		List<Produto_da_demonstracao__c> itens_ordem = new List<Produto_da_Demonstracao__c>();
		for(Produto_da_Demonstracao__c item_equip : itens)
			if(item_equip.Item__c!=null && item_equip.Item_Pai__c==null){
				itens_ordem.add(item_equip);
                
				for(Produto_da_Demonstracao__c item_acess : itens)
					if(item_acess.Item_Pai__c==item_equip.Item__c)
						itens_ordem.add(item_acess);
			}

		for(Produto_da_Demonstracao__c item_vazio : itens)
			if(item_vazio.Item__c==null && item_vazio.Item_Pai__c==null)
				itens_ordem.add(item_vazio);
		
		produtos = new List<Produto>();
		Decimal subtotal = 0;
		for(Integer cont=0; cont<itens_ordem.size(); cont++){
			Produto produto = new Produto(itens_ordem[cont]);
			subtotal += itens_ordem[cont].Valor__c;
			
			String anterior = (cont==0?null:(itens_ordem[cont-1].Item_Pai__c==null?'equipamento':'acessorio'));
			String atual = (itens_ordem[cont].Item_Pai__c==null?'equipamento':'acessorio');
			String proximo = (cont==itens_ordem.size()-1?null:(itens_ordem[cont+1].Item_Pai__c==null?'equipamento':'acessorio'));
			
			if((atual=='equipamento'&& proximo=='acessorio') || ((anterior==null||anterior=='acessorio') && (atual=='equipamento' && (proximo=='equipamento'||proximo==null))))
				produto.cabecalho = true;
			if((anterior=='equipamento'||anterior=='acessorio') && atual=='acessorio' && (proximo=='equipamento'||proximo==null)){
				produto.subtotal = demonstracao.CurrencyISOCode+' '+String.valueOf(subtotal.format());
				if(!produto.subtotal.contains(',')) produto.subtotal += ',00';
				else if(produto.subtotal.substringAfter(',').length()==1) produto.subtotal += '0';
				subtotal = 0;
			}
			
			produtos.add(produto);
		}
		
		// documento
		documento = new Documento();
		if(demonstracao.Fornecedor__r.CNPJ__c == '27.476.124/0001-02')
			documento.timbrado = PageReference.forResource('TimbradoHealth').getUrl();
		else if(demonstracao.Fornecedor__r.CNPJ__c == '23.813.386/0001-56')
			documento.timbrado = PageReference.forResource('TimbradoGDB').getUrl();
		else
			documento.timbrado = PageReference.forResource('TimbradoHospcom').getUrl();	
	}
	
	public class Produto{
		public Boolean cabecalho{get;set;}
		public Produto_da_demonstracao__c item{get;set;}
		public String subtotal{get;set;}
		
		public Produto(Produto_da_demonstracao__c item){
			this.cabecalho = false;
			this.item = item;
			this.subtotal = null;
		}
	}
    
	public class Documento{
		public String timbrado{get;set;}
		
		public Documento(){}
	}
    
}