force-app/main/default/objects/Account/fields/Raz_o_Social__c.field-meta.xml
<CustomField>
    <fullName>Raz_o_Social__c</fullName>
    <label>Razão social</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Brinde__c/Brinde__c.object-meta.xml
<CustomObject>
    <label>Brinde</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Nome do Brinde</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brindes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Brinde__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Brindes</relationshipLabel>
    <relationshipName>Brindes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AprovaBrindeTest.cls
@isTest
public class AprovaBrindeTest {

    @isTest
    public static void test() {
        List<String> estados = new List<String>{'Ceará', 'Acre', 'Distrito Federal', 'Mato Grosso do Sul'};
            
        for(Integer i = 0; i < estados.size(); i++) {
            Account a = new Account();
            a.Name = 'teste ' + i;
            a.Raz_o_Social__c = 'teste';
            a.Ownership = 'PRIVADO';
            a.Type = 'CLIENTE FINAL';
            a.BillingState = estados[i];
            insert a;

            Brinde__c b = new Brinde__c();
            b.Conta__c = a.Id;
            insert b;


        }

    }
}