force-app/main/default/objects/Account/fields/Raz_o_Social__c.field-meta.xml
<CustomField>
    <fullName>Raz_o_Social__c</fullName>
    <label>Razão social</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Transportadora__c.field-meta.xml
<CustomField>
    <fullName>Transportadora__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Utilizado para vincular contas de transportadora da empresa</inlineHelpText>
    <label>Transportadora</label>
    <referenceTo>Transportadora__c</referenceTo>
    <relationshipLabel>Contas</relationshipLabel>
    <relationshipName>Contas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fornecedor__c/Fornecedor__c.object-meta.xml
<CustomObject>
    <label>Pedido de Compra</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número do Pedido de Compra</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pedidos de Compra</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fornecedor__c/fields/Descricao_do_pagamento__c.field-meta.xml
<CustomField>
    <fullName>Descricao_do_pagamento__c</fullName>
    <label>Descrição do pagamento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fornecedor__c/fields/Forma_de_pagamento__c.field-meta.xml
<CustomField>
    <fullName>Forma_de_pagamento__c</fullName>
    <label>Forma de pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dinheiro</fullName>
            </value>
            <value>
                <fullName>Depósito Bancário</fullName>
            </value>
            <value>
                <fullName>Depósito Antecipado</fullName>
            </value>
            <value>
                <fullName>Boleto</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Cartão de Crédito</fullName>
            </value>
            <value>
                <fullName>Cartão de Débito</fullName>
            </value>
            <value>
                <fullName>Permuta</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fornecedor__c/fields/Fornecedor__c.field-meta.xml
<CustomField>
    <fullName>Fornecedor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Fornecedor</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Fornecedores1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fornecedor__c/fields/Pedido_de_compra__c.field-meta.xml
<CustomField>
    <fullName>Pedido_de_compra__c</fullName>
    <label>Cotação</label>
    <referenceTo>Pedido_de_compra__c</referenceTo>
    <relationshipName>Fornecedores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Fornecedor__c/fields/Prazo_de_recebimento__c.field-meta.xml
<CustomField>
    <fullName>Prazo_de_recebimento__c</fullName>
    <inlineHelpText>Previsão de entrega definida com base na data de aprovação da cotação + quantidade de dias de entrega.</inlineHelpText>
    <label>Previsão de entrega</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Fornecedor__c/fields/Tipo_de_Frete__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Frete__c</fullName>
    <label>Tipo de Frete</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CIF</fullName>
            </value>
            <value>
                <fullName>FOB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fornecedor__c/fields/Transportadora__c.field-meta.xml
<CustomField>
    <fullName>Transportadora__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Transportadora</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Fornecedores2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fornecedor__c/fields/Valor_do_frete__c.field-meta.xml
<CustomField>
    <fullName>Valor_do_frete__c</fullName>
    <label>Valor do frete</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Item_de_fornecedor__c/Item_de_fornecedor__c.object-meta.xml
<CustomObject>
    <label>Item de pedido de compra</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Nº do item de pedido de compra</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens de pedido de compra</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Item_de_fornecedor__c/fields/Codigo_do_produto__c.field-meta.xml
<CustomField>
    <fullName>Codigo_do_produto__c</fullName>
    <formula>Item_de_pedido_de_compra__r.Codigo_do_produto__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Código do produto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Item_de_fornecedor__c/fields/Descricao__c.field-meta.xml
<CustomField>
    <fullName>Descricao__c</fullName>
    <formula>Item_de_pedido_de_compra__r.Descri_o_da_linha__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Descrição</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Item_de_fornecedor__c/fields/Fornecedor__c.field-meta.xml
<CustomField>
    <fullName>Fornecedor__c</fullName>
    <label>Pedido de Compra</label>
    <referenceTo>Fornecedor__c</referenceTo>
    <relationshipLabel>Itens de pedido de compra</relationshipLabel>
    <relationshipName>Itens_de_fornecedor</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Item_de_fornecedor__c/fields/Item_de_pedido_de_compra__c.field-meta.xml
<CustomField>
    <fullName>Item_de_pedido_de_compra__c</fullName>
    <label>Item de cotação</label>
    <referenceTo>Item_de_pedido_de_compra__c</referenceTo>
    <relationshipName>Itens_de_fornecedor</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Item_de_fornecedor__c/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <formula>Item_de_pedido_de_compra__r.Marca__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Marca</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Item_de_fornecedor__c/fields/Modelo__c.field-meta.xml
<CustomField>
    <fullName>Modelo__c</fullName>
    <formula>Item_de_pedido_de_compra__r.Modelo__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Modelo</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Item_de_fornecedor__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <formula>Item_de_pedido_de_compra__r.Produto__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Produto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Item_de_fornecedor__c/fields/Quantidade__c.field-meta.xml
<CustomField>
    <fullName>Quantidade__c</fullName>
    <label>Quantidade</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Item_de_fornecedor__c/fields/Valor_unit_da_ultima_compra__c.field-meta.xml
<CustomField>
    <fullName>Valor_unit_da_ultima_compra__c</fullName>
    <label>Valor unit. da última compra</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Item_de_fornecedor__c/fields/Valor_unit_inicial_de_negociacao__c.field-meta.xml
<CustomField>
    <fullName>Valor_unit_inicial_de_negociacao__c</fullName>
    <label>Valor unit. inicial de negociação</label>
    <precision>13</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Item_de_fornecedor__c/fields/Valor_unitario__c.field-meta.xml
<CustomField>
    <fullName>Valor_unitario__c</fullName>
    <label>Valor unitário</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Item_de_pedido_de_compra__c/Item_de_pedido_de_compra__c.object-meta.xml
<CustomObject>
    <label>Item de cotação</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número do item de cotação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens de cotação</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Item_de_pedido_de_compra__c/fields/Codigo_do_produto__c.field-meta.xml
<CustomField>
    <fullName>Codigo_do_produto__c</fullName>
    <formula>Produto__r.ProductCode</formula>
    <label>Código do produto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Item_de_pedido_de_compra__c/fields/Pedido_de_compra__c.field-meta.xml
<CustomField>
    <fullName>Pedido_de_compra__c</fullName>
    <label>Cotação</label>
    <referenceTo>Pedido_de_compra__c</referenceTo>
    <relationshipLabel>Itens de cotação</relationshipLabel>
    <relationshipName>Itens_de_Pedido_de_Compra</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Item_de_pedido_de_compra__c/fields/Prazo_de_recebimento__c.field-meta.xml
<CustomField>
    <fullName>Prazo_de_recebimento__c</fullName>
    <label>Prazo de recebimento</label>
    <summarizedField>Item_de_fornecedor__c.Prazo_de_recebimento__c</summarizedField>
    <summaryFilterItems>
        <field>Item_de_fornecedor__c.Comprar__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Item_de_fornecedor__c.Item_de_pedido_de_compra__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Item_de_pedido_de_compra__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Produtos_do_pedido</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Item_de_pedido_de_compra__c/fields/Valor_unitario__c.field-meta.xml
<CustomField>
    <fullName>Valor_unitario__c</fullName>
    <label>Valor unitário</label>
    <summarizedField>Item_de_fornecedor__c.Valor_unitario__c</summarizedField>
    <summaryFilterItems>
        <field>Item_de_fornecedor__c.Comprar__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>Item_de_fornecedor__c.Item_de_pedido_de_compra__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order/fields/Forma_de_pagamento__c.field-meta.xml
<CustomField>
    <fullName>Forma_de_pagamento__c</fullName>
    <label>_Forma de pagamento (del)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A VISTA NO PEDIDO</fullName>
            </value>
            <value>
                <fullName>A VISTA CONTRA EMBARQUE</fullName>
            </value>
            <value>
                <fullName>FINANCIAMENTO BANCÁRIO</fullName>
            </value>
            <value>
                <fullName>OPEN ACCOUNT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Prazo_de_recebimento__c.field-meta.xml
<CustomField>
    <fullName>Prazo_de_recebimento__c</fullName>
    <inlineHelpText>Do Fornecedor a Hospcom, maior prazo dentre os itens.</inlineHelpText>
    <label>_Prazo de recebimento (del)</label>
    <summarizedField>OrderItem.Prazo_de_recebimento__c</summarizedField>
    <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order/fields/Raz_o_Social__c.field-meta.xml
<CustomField>
    <fullName>Raz_o_Social__c</fullName>
    <formula>Account.Raz_o_Social__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>_Razão Social (del)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Tipo_de_Frete__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Frete__c</fullName>
    <label>_Tipo de frete (del)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FOB</fullName>
            </value>
            <value>
                <fullName>CIF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/recordTypes/Hospcom.recordType-meta.xml
<RecordType>
    <fullName>Hospcom</fullName>
    <active>true</active>
    <description>Para faturamento das empresas do grupo Hospcom</description>
    <label>Hospcom</label>
</RecordType>

force-app/main/default/objects/Pedido_de_compra__c/Pedido_de_compra__c.object-meta.xml
<CustomObject>
    <label>Cotação de compra</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número da cotação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cotações de compra</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Pedido_de_compra__c/fields/Descricao__c.field-meta.xml
<CustomField>
    <fullName>Descricao__c</fullName>
    <label>Descrição</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AssistenteTomadaPrecos.cls
public class AssistenteTomadaPrecos {

	public Id 								registro_pai_id {get;set;}
	public Fornecedor__c					fornecedor{get;set;}
	public List<Item_de_fornecedor__c>		itens_fornecedor{get;set;}
	
	public List<String> 					etapa {get;set;}
	public List<String>						etapas{get;set;}
	
	public Boolean 							tem_erros {get;set;}
	public List<String> 					erros {get;set;}
	
	public Boolean 							tem_produtos {get;set;}
	
	public AssistenteTomadaPrecos(ApexPages.StandardController controller) {
		Inicializa(controller);
		ObtemFornecedorItens();
	}
	
	public void Inicializa(ApexPages.StandardController controller){
		registro_pai_id = ((SObject)controller.getRecord()).Id;
		fornecedor = new Fornecedor__c();
		itens_fornecedor = new List<Item_de_fornecedor__c>();
		
		etapa = new List<String>();
		etapas = new List<String>();
		etapas.add('Preço');
		SetaEtapa('preço', 'Insira valores, prazo, e demais informações da cotação');
		
		tem_erros = false;
	}
	
	public void SetaEtapa(String nome_etapa, String cabecalho){
		etapa.clear();
		etapa.add(nome_etapa);
		etapa.add(cabecalho);
	}
	
	public void ObtemFornecedorItens(){
		fornecedor = [
			SELECT 	Id, Fornecedor__r.Name, Pedido_de_compra__r.Name, Pedido_de_compra__r.Descricao__c, Forma_de_pagamento__c, Descricao_do_pagamento__c, Pedido_de_compra__c,
					Prazo_de_recebimento__c, Tipo_de_Frete__c, Transportadora__c, Name, Fornecedor__r.Raz_o_Social__c, Valor_do_frete__c
			FROM 	Fornecedor__c
			WHERE	Id = :registro_pai_id
		];
		
		itens_fornecedor = [
			SELECT	Id, Name, Produto__c, Codigo_do_produto__c, Marca__c, Modelo__c, Quantidade__c, Valor_unitario__c, Valor_unit_da_ultima_compra__c,Valor_unit_inicial_de_negociacao__c,
					Item_de_pedido_de_compra__r.Produto__r.URL_da_Imagem__c,
            		Fornecedor__r.Tipo__c
			FROM	Item_de_fornecedor__c
			WHERE	Fornecedor__c = :registro_pai_id
			ORDER BY Produto__c
		];
		
		tem_produtos = ((itens_fornecedor.size()>0)?true:false);
	}
	
	
	public pageReference Efetiva(){
		try {
			update fornecedor;
		}
		catch (System.DMLException e){
			ApexPages.addMessages(e);
		}
		
		try {
			update itens_fornecedor;
		}
		catch (System.DMLException e){
			ApexPages.addMessages(e);
		}

		PreparaErros();
		if(tem_erros)
			return null;
		else
			return new PageReference('https://hospcom.my.site.com/Sales/s/pedido-de-compra/'+ String.valueOf(fornecedor.Pedido_de_compra__c) + '/' + fornecedor.Pedido_de_compra__r.Name + '?tabset-39928=2');
	}
	
	public void PreparaErros(){
		tem_erros = ((ApexPages.getMessages().size()>0)?true:false);
        if(tem_erros){
            erros = new List<String>();
            for(Apexpages.Message mensagem: ApexPages.getMessages())
                erros.add(mensagem.getDetail());
        }
	}

}