force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rascunho</fullName>
                <default>true</default>
                <label>Rascunho</label>
            </value>
            <value>
                <fullName>Aguardando Aprovação</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Reprovado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Descricao_de_pagamento__c.field-meta.xml
<CustomField>
    <fullName>Descricao_de_pagamento__c</fullName>
    <label>_Descrição de pagamento (del)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Order/fields/Entrega_Parcial_Autorizada__c.field-meta.xml
<CustomField>
    <fullName>Entrega_Parcial_Autorizada__c</fullName>
    <label>_Entrega parcial (del)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Autorizada</fullName>
            </value>
            <value>
                <fullName>Não Autorizada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Faturamento_Feito__c.field-meta.xml
<CustomField>
    <fullName>Faturamento_Feito__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Empresa do grupo Hospcom que irá faturar o pedido.</inlineHelpText>
    <label>Faturamento feito</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Faturamentos Feitos (de pedidos)</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Forma_de_pagamento__c.field-meta.xml
<CustomField>
    <fullName>Forma_de_pagamento__c</fullName>
    <label>_Forma de pagamento (del)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A VISTA NO PEDIDO</fullName>
            </value>
            <value>
                <fullName>A VISTA CONTRA EMBARQUE</fullName>
            </value>
            <value>
                <fullName>FINANCIAMENTO BANCÁRIO</fullName>
            </value>
            <value>
                <fullName>OPEN ACCOUNT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Prazo_Prometido__c.field-meta.xml
<CustomField>
    <fullName>Prazo_Prometido__c</fullName>
    <inlineHelpText>Prazo de entrega inicial ao cliente.</inlineHelpText>
    <label>_Prazo prometido (del)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Tipo_de_Frete__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Frete__c</fullName>
    <label>_Tipo de frete (del)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FOB</fullName>
            </value>
            <value>
                <fullName>CIF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Data_de_Entrega_Fornecedor__c.field-meta.xml
<CustomField>
    <fullName>Data_de_Entrega_Fornecedor__c</fullName>
    <label>_Data de Entrega Fornecedor (old) (del)</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Novo</fullName>
            </value>
            <value>
                <fullName>Transferência Interna</fullName>
            </value>
            <value>
                <fullName>Pendência Interna</fullName>
            </value>
            <value>
                <fullName>Em Separação</fullName>
            </value>
            <value>
                <fullName>Galpão - Em Separação</fullName>
            </value>
            <value>
                <fullName>Separado</fullName>
            </value>
            <value>
                <fullName>Reservado</fullName>
            </value>
            <value>
                <fullName>OPR - ANALISE DE COMPRA</fullName>
            </value>
            <value>
                <fullName>CMP - COTAÇÃO DE COMPRA</fullName>
            </value>
            <value>
                <fullName>CMP - AG. ENTREGA FORNECEDOR</fullName>
            </value>
            <value>
                <fullName>Recebido Fornecedor</fullName>
            </value>
            <value>
                <fullName>Recebido A.T.</fullName>
            </value>
            <value>
                <fullName>Aguardando Faturamento</fullName>
            </value>
            <value>
                <fullName>Aguardando conferência</fullName>
            </value>
            <value>
                <fullName>Atendido</fullName>
            </value>
            <value>
                <fullName>Faturado</fullName>
            </value>
            <value>
                <fullName>Aguardando Coleta</fullName>
            </value>
            <value>
                <fullName>Em Avaliação Técnica</fullName>
            </value>
            <value>
                <fullName>CMP - AG. COMPRA IMPORTAÇÃO</fullName>
            </value>
            <value>
                <fullName>CMP - AG. COMPRA NACIONAL</fullName>
            </value>
            <value>
                <fullName>Em rota de entrega</fullName>
            </value>
            <value>
                <fullName>Entregue Cliente</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
                <label>OPR - CANCELADO</label>
            </value>
            <value>
                <fullName>Devolvido</fullName>
            </value>
            <value>
                <fullName>Recebido Parcial</fullName>
            </value>
            <value>
                <fullName>Recebido Total</fullName>
            </value>
            <value>
                <fullName>CMP - EM PRODUÇÃO FORN.</fullName>
            </value>
            <value>
                <fullName>CMP - EM COLETA PORTO/FORNECEDOR</fullName>
            </value>
            <value>
                <fullName>Em trânsito</fullName>
            </value>
            <value>
                <fullName>CMP - EM DESEMBARAÇO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PedOtmSqltest.cls
@isTest(seeAllData=true)
public class PedOtmSqltest { 
	
    static testMethod void testaPedido(){ 
        test.startTest();
        	
		Order pedido = new Order(
            OpportunityId = '0065A00000ipo7VQAQ',			// test:006f000000HTDtY prod:0065A00000ipo7VQAQ
            EffectiveDate = System.today(),
            Prazo_Prometido__c = System.today()+3,
            Status = 'Ativo',
            Faturamento_Feito__c = '001i00000085QYbAAM',	// test:001i00000085QYb prod:001i00000085QYbAAM
            AccountId = '001i000000UYewbAAD',				// test:001i000000UYewb prod:001i000000UYewbAAD
            Forma_de_pagamento__c = 'OPEN ACCOUNT',
            Descricao_de_Pagamento__c = 'em 3 vezes',
            Tipo_de_Frete__c = 'CIF',
            Entrega_Parcial_Autorizada__c = 'Não Autorizada'
        );
        
        insert pedido;
        
        test.stopTest();
    }
    
    static testMethod void testaItemPedido(){ 
        test.startTest();
        	
		OrderItem item_pedido = new OrderItem();
        item_pedido = [
            SELECT	Id, Status__c, Data_de_Entrega_Fornecedor__c
            FROM	OrderItem
            WHERE 	Id = '8025A000003S0MF'		//test:802f00000001TGg prod:8025A000003S0MF
        ];
        
        item_pedido.Status__c = 'Aguardando Entrega Fornecedor';
        item_pedido.Data_de_Entrega_Fornecedor__c = System.today()+3;
        update item_pedido;
        
        test.stopTest();
    }
    

    static testMethod void testaItemPedido2(){ 
        test.startTest();
        	
		OrderItem item_pedido = new OrderItem();
        item_pedido = [
            SELECT	Id, Status__c, Data_de_Entrega_Fornecedor__c
            FROM	OrderItem
            WHERE 	Id = '8025A000003S0MF'		//test:802f00000001TGg prod:8025A000003S0MF
        ];
        
        item_pedido.Status__c = 'Entregue';
        item_pedido.Data_de_Entrega_Fornecedor__c = System.today()+3;
        update item_pedido;
        
        test.stopTest();
    }
    

}