force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rascunho</fullName>
                <default>true</default>
                <label>Rascunho</label>
            </value>
            <value>
                <fullName>Aguardando Aprovação</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Reprovado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Colaborador_ativo__c.field-meta.xml
<CustomField>
    <fullName>Colaborador_ativo__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Colaborador ativo?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Destinatario__c/Destinatario__c.object-meta.xml
<CustomObject>
    <label>Destinatário</label>
    <nameField>
        <displayFormat>DES-{00000}</displayFormat>
        <label>Destinatário</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Destinatários</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Solicitacao_de_Tranferencia_Hospcoins__c/Solicitacao_de_Tranferencia_Hospcoins__c.object-meta.xml
<CustomObject>
    <description>Esse obj faz a validação das tranferencias hospcoins do programa valeu. 
Os colobaradores fazem a Solicitação de Tranferencia e essa solicitação cai para o RH.
Quando aprovado, a tranferencia é efetuada, caso ao contrario o colaborador é notificado sobre a reprovação
e a justificativa da mesma</description>
    <label>Solicitação de Transferência Hospcoins</label>
    <nameField>
        <displayFormat>STH - {0000}</displayFormat>
        <label>Solicitação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solicitações de Transferências</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Solicitacao_de_Tranferencia_Hospcoins__c/fields/Destinatario__c.field-meta.xml
<CustomField>
    <fullName>Destinatario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Destinatário</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Solicitações de Transferências</relationshipLabel>
    <relationshipName>Solicitacoes_de_Transferencias</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Solicitacao_de_Tranferencia_Hospcoins__c/fields/Justificativa__c.field-meta.xml
<CustomField>
    <fullName>Justificativa__c</fullName>
    <label>Justificativa de envio</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Solicitacao_de_Tranferencia_Hospcoins__c/fields/Remetente_Externo__c.field-meta.xml
<CustomField>
    <fullName>Remetente_Externo__c</fullName>
    <inlineHelpText>Usado para armazenar o nome de remetente que não possuem uma conta no Salesforce</inlineHelpText>
    <label>Remetente (Externo)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Solicitacao_de_Tranferencia_Hospcoins__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pendente</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/programaValeuTest.cls
@isTest(seeAllData=true)
public class programaValeuTest {
    @isTest
    private static void testa(){ 
        programaValeu.envia('0036e00004Hl2lk', 'justificativa', '0036e00004Fczvv', '00531000006UzZsAAK');
    }  
    @isTest
    private static void testa2(){
        programaValeu.executeSoql('SELECT ID FROM ACCOUNT LIMIT 1');
    }
    @isTest
    private static void testa3(){
        try{
            programaValeu.envia('0036e00004Hl2lk', 'justificativa', '0036e00004Fczvv', '00531000006UzZsAAK');
        }
        catch(DmlException e){}
    }       
    @isTest
    private static void testa4(){
        programaValeu.dummy('0036e00004Hl2lk'); 
    }
     @isTest
    private static void testa5(){
        programaValeu.dummy2('0036e00004Hl2lk'); 
    }
      @isTest
    private static void testa6(){
        programaValeu.dummy3('0036e00004Hl2lk'); 
    }
       @isTest
    private static void testa7(){
        programaValeu.dummy4('0036e00004Hl2lk'); 
    }
         @isTest
    private static void testa8(){
        programaValeu.dummy5('0036e00004Hl2lk'); 
    }
         @isTest
    private static void testa9(){
        programaValeu.dummy6('0036e00004Hl2lk'); 
    }
         @isTest
    private static void testa10(){
        programaValeu.dummy7('0036e00004Hl2lk'); 
    }
         @isTest
    private static void testa11(){
        programaValeu.dummy9('0036e00004Hl2lk'); 
    }
    
@isTest
    static void testaTriggerComSolicitacao() {
        // Busca um contato ativo existente
        Contact contato = [SELECT Id FROM Contact WHERE Colaborador_Ativo__c = true LIMIT 1];
        
      
        // Cria uma solicitação com status inicial
        Solicitacao_de_Tranferencia_Hospcoins__c solicitacao = new Solicitacao_de_Tranferencia_Hospcoins__c(
            Destinatario__c = contato.Id,
            Justificativa__c = 'Justificativa direta',
            Status__c = 'Pendente',
            Remetente_Externo__c = 'Nome de Teste'
        );
        insert solicitacao;

        // Atualiza para 'Aprovado' para acionar o trigger
        solicitacao.Status__c = 'Aprovado';
        update solicitacao;      
    }
}