force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rascunho</fullName>
                <default>true</default>
                <label>Rascunho</label>
            </value>
            <value>
                <fullName>Aguardando Aprovação</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Reprovado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recrutamento__c/Recrutamento__c.object-meta.xml
<CustomObject>
    <label>Recrutamento</label>
    <nameField>
        <displayFormat>R{0}</displayFormat>
        <label>Número do Recrutamento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recrutamentos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Recrutamento__c/fields/Contato_do_Colaborador__c.field-meta.xml
<CustomField>
    <fullName>Contato_do_Colaborador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contato do Colaborador</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Recrutamentos (Contato do Colaborador)</relationshipLabel>
    <relationshipName>Recrutamentos1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recrutamento__c/fields/Data_de_Admissao__c.field-meta.xml
<CustomField>
    <fullName>Data_de_Admissao__c</fullName>
    <label>Data de Admissão</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Recrutamento__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em Análise</fullName>
                <default>true</default>
                <label>Em Análise</label>
            </value>
            <value>
                <fullName>Selecionado</fullName>
            </value>
            <value>
                <fullName>Reprovado</fullName>
            </value>
            <value>
                <fullName>Cadastro de Reserva</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recrutamento__c/fields/Telefone_emergencia__c.field-meta.xml
<CustomField>
    <fullName>Telefone_emergencia__c</fullName>
    <label>Telefone para contato em caso de emergên</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/classes/RecrutamentoTriggerHandlerTest.cls
@isTest
public with sharing class RecrutamentoTriggerHandlerTest {

    @testSetup
    static void makeData() {
        // Cria uma Account e um Contacto para associar aos Recrutamentos
        Account partnerAccount = new Account(
            Name = 'Teste Acct',
            Phone = '85999999999'
        );
        insert partnerAccount;

        // Cria o contato
        Contact colaborador = new Contact(
            FirstName='Colaborador',
            LastName='Teste',
            AccountId = partnerAccount.Id,
            Email = 'colaborardor@teste.com'
        );
        insert colaborador;

        // Recrutamento válido que deve gerar avaliações
        Recrutamento__c recrutamentoValido = new Recrutamento__c(
            Status__c = 'Aprovado',
            Data_de_Admissao__c = Date.today(),
            Contato_do_Colaborador__c = colaborador.Id,
            Telefone_emergencia__c = '85111111111'
        );
        insert recrutamentoValido;
    }

    @isTest
    public static void testUpdateTrigger(){
        
        Recrutamento__c Recrutamento = [SELECT Id FROM Recrutamento__c LIMIT 1];

        Test.startTest();
        update Recrutamento;
        Test.stopTest();
    }
}