force-app/main/default/objects/Cargo__c/Cargo__c.object-meta.xml
<CustomObject>
    <label>Cargo</label>
    <nameField>
        <label>Título do Cargo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cargos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/fields/Cargo__c.field-meta.xml
<CustomField>
    <fullName>Cargo__c</fullName>
    <label>Cargo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Administrador Hospitalar</fullName>
            </value>
            <value>
                <fullName>Analista de Compras</fullName>
            </value>
            <value>
                <fullName>Analista de desenvolvimento</fullName>
            </value>
            <value>
                <fullName>Analista de Finanças</fullName>
            </value>
            <value>
                <fullName>Anestesista</fullName>
            </value>
            <value>
                <fullName>Assistente Social</fullName>
            </value>
            <value>
                <fullName>Auxiliar Administrativo</fullName>
            </value>
            <value>
                <fullName>Auxiliar de Farmácia</fullName>
            </value>
            <value>
                <fullName>Cardiologista</fullName>
            </value>
            <value>
                <fullName>Chefe de gabinete</fullName>
            </value>
            <value>
                <fullName>Cirurgião</fullName>
            </value>
            <value>
                <fullName>Coordenador Administrativo</fullName>
            </value>
            <value>
                <fullName>Coordenador de Manutenção</fullName>
            </value>
            <value>
                <fullName>Diretor Administrativo</fullName>
            </value>
            <value>
                <fullName>Diretor Médico</fullName>
            </value>
            <value>
                <fullName>Endocrinologista</fullName>
            </value>
            <value>
                <fullName>Enfermeiro</fullName>
            </value>
            <value>
                <fullName>Engenheiro</fullName>
            </value>
            <value>
                <fullName>Farmacêutico</fullName>
            </value>
            <value>
                <fullName>Fisioterapeuta</fullName>
            </value>
            <value>
                <fullName>Gerente Administrativo</fullName>
            </value>
            <value>
                <fullName>Gerente de Enfermagem</fullName>
            </value>
            <value>
                <fullName>Gerente de Manutenção</fullName>
            </value>
            <value>
                <fullName>Geriatra</fullName>
            </value>
            <value>
                <fullName>Ginecologista</fullName>
            </value>
            <value>
                <fullName>Hematologista</fullName>
            </value>
            <value>
                <fullName>Infectologista</fullName>
            </value>
            <value>
                <fullName>Médico</fullName>
            </value>
            <value>
                <fullName>Neurologista</fullName>
            </value>
            <value>
                <fullName>Nutricionista</fullName>
            </value>
            <value>
                <fullName>Outros</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <label>CPF</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ContatosValidacaoZapEmail_Test.cls
@isTest(seealldata = true)
public class ContatosValidacaoZapEmail_Test {

    @isTest
    static void testConsultaWhatsapp() {
        
        Contact contatoTeste = new Contact();
        contatoTeste.AccountId = '001i00000085QYb';//0015300000R5SUL
        contatoTeste.FirstName = 'class';
        contatoTeste.LastName = 'teste';
        contatoTeste.Cargo__c = 'Outros';
        contatoTeste.Title = 'Executivo de vendas';
        contatoTeste.CPF__c = '617.259.750-76'; 
        contatoTeste.Phone = '(62) 99999-5702';
        contatoTeste.Email = 'sousawitor@gmail.com';

        insert contatoTeste;

        Test.setMock(HttpCalloutMock.class, new MonkverificaWhatsapp());

        ValidacoesContato.consultaWhatsapp(contatoTeste.Phone,contatoTeste.MobilePhone,contatoTeste.Id );
        ValidacoesContato.consultaEmail(contatoTeste.Email,contatoTeste.Id);
    }    
}