force-app/main/default/objects/Email__c/Email__c.object-meta.xml
<CustomObject>
    <label>E-mail</label>
    <nameField>
        <label>Titulo do email</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>E-mails</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Feedback_360__c/Feedback_360__c.object-meta.xml
<CustomObject>
    <label>Feedback 360º</label>
    <nameField>
        <label>Assunto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Feedbacks 360º</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Feedback_360__c/fields/Descricao__c.field-meta.xml
<CustomField>
    <fullName>Descricao__c</fullName>
    <description>Forneça a descrição completa do problema</description>
    <inlineHelpText>Detalhes a serem incluídos: Recursos, O que aconteceu, Resultado esperado, Mensagem de erro, Etapas a reproduzir.</inlineHelpText>
    <label>Descrição</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Feedback_360__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Elogio</fullName>
            </value>
            <value>
                <fullName>BUG</fullName>
            </value>
            <value>
                <fullName>MELHORIA</fullName>
            </value>
            <value>
                <fullName>NOVO RECURSO</fullName>
            </value>
            <value>
                <fullName>Sugestão</fullName>
            </value>
            <value>
                <fullName>Reclamação</fullName>
            </value>
            <value>
                <fullName>SOLICITAÇÃO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Feedback360Controller.cls
public with sharing class Feedback360Controller {
    public  String Email				{get;set;}
    public  String Assunto				{get;set;}
    public  String Tipo					{get;set;}
    public  String Descricao			{get;set;}
	
    public 	String 	Mensagem			{get;set;}
    public 	String  Cor					{get;set;}
    
    public Feedback360Controller(){
        Mensagem = '';
    }
    
    public void Salvar(){
        
        if(Assunto =='' || Descricao == '' || Tipo == null){
            Mensagem = 'Os seguintes campos são obrigatórios: Assunto, Tipo e Descrição';
            Cor = 'danger';	
        }
        else{
            Feedback_360__c registro = new Feedback_360__c(
                Name = assunto,
                Tipo__c = tipo,
                Descricao__c = 	descricao,
                Email__c = email
            );
            insert registro;
            Mensagem = 'Registro inserido com sucesso! Agradecemos seu feedback.';
            Cor = 'success';
        }           
    }
}