force-app/main/default/objects/Analise_de_Mercado__c/Analise_de_Mercado__c.object-meta.xml
<CustomObject>
    <label>Análise de Mercado</label>
    <nameField>
        <displayFormat>AM {00000}</displayFormat>
        <label>Nº</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Análises de Mercado</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Analise_de_Mercado__c/fields/Concorrente__c.field-meta.xml
<CustomField>
    <fullName>Concorrente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Concorrente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Análises de Mercado</relationshipLabel>
    <relationshipName>Analises_de_Mercado</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Analise_de_Mercado__c/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Análises de Mercado</relationshipLabel>
    <relationshipName>Analises_de_Mercado</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Fornecedor__c/Fornecedor__c.object-meta.xml
<CustomObject>
    <label>Pedido de Compra</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número do Pedido de Compra</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pedidos de Compra</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Fornecedor__c/fields/Fornecedor__c.field-meta.xml
<CustomField>
    <fullName>Fornecedor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Fornecedor</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Fornecedores1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fornecedor__c/fields/Status_do_PC__c.field-meta.xml
<CustomField>
    <fullName>Status_do_PC__c</fullName>
    <label>Status do PC</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rascunho</fullName>
                <default>true</default>
                <label>Rascunho</label>
            </value>
            <value>
                <fullName>Em cotação</fullName>
            </value>
            <value>
                <fullName>Em andamento</fullName>
            </value>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Finalizado parcial</fullName>
            </value>
            <value>
                <fullName>Finalizado total</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Erro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fornecedor__c/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Pedidos_de_Compra</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Goal__c/Goal__c.object-meta.xml
<CustomObject>
    <label>Meta</label>
    <nameField>
        <label>Meta</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metas</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Goal__c/fields/Final__c.field-meta.xml
<CustomField>
    <fullName>Final__c</fullName>
    <label>Final</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Inicio__c.field-meta.xml
<CustomField>
    <fullName>Inicio__c</fullName>
    <label>Início</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Linha__c.field-meta.xml
<CustomField>
    <fullName>Linha__c</fullName>
    <label>Linha</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>linha</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Meta__c.field-meta.xml
<CustomField>
    <fullName>Meta__c</fullName>
    <label>Meta</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Periodo__c.field-meta.xml
<CustomField>
    <fullName>Periodo__c</fullName>
    <formula>IF( Final__c -  Inicio__c &gt; 31 &amp;&amp; Final__c -  Inicio__c &lt;= 94, &apos;Trimestral&apos;, IF(Final__c -  Inicio__c &gt; 94, &apos;Anual&apos;, &apos;Mensal&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Período</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Goal__c/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Metas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Forecast__c.field-meta.xml
<CustomField>
    <fullName>Forecast__c</fullName>
    <formula>IF(Propriedade_da_conta__c == &apos;PRIVADO&apos; || Propriedade_da_conta__c == &apos;&apos;,
IF(TEXT(StageName) = &apos;COMITED&apos;, Amount,
IF(TEXT(StageName) = &apos;WIN&apos;, 0,
IF(TEXT(StageName) = &apos;UPSIDE HIGH&apos;, Amount * 0.35,
IF(TEXT(StageName) = &apos;UPSIDE&apos;, Amount * 0.2,
IF(TEXT(StageName) = &apos;OPEN&apos;, Amount * 0.1, Amount* 0))))),

IF(Propriedade_da_conta__c == &apos;PUBLICO&apos; || Propriedade_da_conta__c == &apos;FILANTROPIA&apos;,
IF(TEXT(StageName) = &apos;WIN&apos;, 0,
IF(TEXT(StageName) = &apos;COMITED&apos; &amp;&amp; TEXT(Sub_Fase__c) != &apos;GARANTIDO&apos;, Amount * 0.4,
IF(TEXT(StageName) = &apos;COMITED&apos; &amp;&amp; TEXT(Sub_Fase__c) = &apos;GARANTIDO&apos;, Amount ,
IF(TEXT(StageName) = &apos;UPSIDE HIGH&apos;, Amount * 0.2,
IF(TEXT(StageName) = &apos;UPSIDE&apos;, Amount * 0.1,
IF(TEXT(StageName) = &apos;OPEN&apos;, Amount * 0, Amount * 0)))))), null)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Forecast</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Linha__c.field-meta.xml
<CustomField>
    <fullName>Linha__c</fullName>
    <label>Linha</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>linha</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sub_Fase__c.field-meta.xml
<CustomField>
    <fullName>Sub_Fase__c</fullName>
    <label>Subfase</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>COTAÇÃO PRÉVIA</fullName>
            </value>
            <value>
                <fullName>ABORTADO</fullName>
            </value>
            <value>
                <fullName>AGUARDANDO ANÁLISE</fullName>
            </value>
            <value>
                <fullName>AGUARDANDO CONTRATO</fullName>
            </value>
            <value>
                <fullName>AGUARDANDO EMPENHO</fullName>
            </value>
            <value>
                <fullName>AGUARDANDO HOMOLOGAÇÃO/ADJUDICADO</fullName>
            </value>
            <value>
                <fullName>AGUARDANDO PARTICIPAÇÃO</fullName>
            </value>
            <value>
                <fullName>EM ANDAMENTO</fullName>
            </value>
            <value>
                <fullName>CANCELADO</fullName>
            </value>
            <value>
                <fullName>DUPLICADO</fullName>
            </value>
            <value>
                <fullName>LOCAÇÃO</fullName>
            </value>
            <value>
                <fullName>ESTIMATIVA DE PREÇOS</fullName>
            </value>
            <value>
                <fullName>FINALIZADO TOTAL</fullName>
            </value>
            <value>
                <fullName>IMPUGNAÇÃO/ESCLARECIMENTOS</fullName>
            </value>
            <value>
                <fullName>PERDIDO</fullName>
            </value>
            <value>
                <fullName>RECURSO</fullName>
            </value>
            <value>
                <fullName>SUSPENSO</fullName>
            </value>
            <value>
                <fullName>FINALIZADO PARCIAL</fullName>
            </value>
            <value>
                <fullName>AGUARDANDO HABILITAÇÃO</fullName>
            </value>
            <value>
                <fullName>AGUARDANDO ENTREGA</fullName>
            </value>
            <value>
                <fullName>CONTRARRAZÃO DE RECURSO</fullName>
            </value>
            <value>
                <fullName>NEGÓCIO FUTURO</fullName>
            </value>
            <value>
                <fullName>COMODATO</fullName>
            </value>
            <value>
                <fullName>GARANTIDO</fullName>
            </value>
            <value>
                <fullName>AGUARDANDO DECISÃO DE RECURSO</fullName>
            </value>
            <value>
                <fullName>AGUARDANDO CONTRATO/EMPENHO</fullName>
                <isActive>false</isActive>
                <label>AGUARDANDO CONTRATO/EMPENHO</label>
            </value>
            <value>
                <fullName>PREVISTO</fullName>
                <isActive>false</isActive>
                <label>PREVISTO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Data_de_ativacao__c.field-meta.xml
<CustomField>
    <fullName>Data_de_ativacao__c</fullName>
    <formula>IF(RecordTypeId= &apos;0125A000001dyU3&apos;,  DATEVALUE(CreatedDate),  DATEVALUE(Inicio_Ativo__c ))</formula>
    <label>Data de ativação</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PedidosVendedor</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/recordTypes/Hospcom.recordType-meta.xml
<RecordType>
    <fullName>Hospcom</fullName>
    <active>true</active>
    <description>Para faturamento das empresas do grupo Hospcom</description>
    <label>Hospcom</label>
</RecordType>

force-app/main/default/objects/User/fields/Linha__c.field-meta.xml
<CustomField>
    <fullName>Linha__c</fullName>
    <label>Linha</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>linha</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Linha__c.field-meta.xml
<CustomField>
    <fullName>Linha__c</fullName>
    <formula>Asset.Linha__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Linha</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/T_cnico_Respons_vel__c.field-meta.xml
<CustomField>
    <fullName>T_cnico_Respons_vel__c</fullName>
    <inlineHelpText>Esse campo foi descontinuado. Selecione o técnico no campo Técnico executor</inlineHelpText>
    <label>Responsável pela O.T (LEGADO)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ALEXANDRE AMARAL</fullName>
            </value>
            <value>
                <fullName>ALON ROCHA DA SILVA</fullName>
            </value>
            <value>
                <fullName>AMANDA JORDÃO</fullName>
            </value>
            <value>
                <fullName>ANA CAROLINE</fullName>
                <label>ANA CAROLINE TALAVERA</label>
            </value>
            <value>
                <fullName>ANDRE BRANDAO</fullName>
            </value>
            <value>
                <fullName>ANDRESSA PETRILLA</fullName>
            </value>
            <value>
                <fullName>ANTONIO LEVI</fullName>
            </value>
            <value>
                <fullName>BEATRIZ MARIANO</fullName>
            </value>
            <value>
                <fullName>BRUNO VINICIUS</fullName>
            </value>
            <value>
                <fullName>CAIO AUGUSTO</fullName>
            </value>
            <value>
                <fullName>CARLA BREVIGLIERO</fullName>
            </value>
            <value>
                <fullName>CARLOS ALBERTO SANTANA</fullName>
            </value>
            <value>
                <fullName>CASSIANO SILVA</fullName>
            </value>
            <value>
                <fullName>CLEITON RIBEIRO</fullName>
            </value>
            <value>
                <fullName>CYLL RODRIGUES</fullName>
            </value>
            <value>
                <fullName>DANIEL BORGES</fullName>
            </value>
            <value>
                <fullName>DANIEL NOGUEIRA DE OLIVEIRA</fullName>
            </value>
            <value>
                <fullName>DANILO GUIMARÃES</fullName>
            </value>
            <value>
                <fullName>DANILO SUSANO</fullName>
            </value>
            <value>
                <fullName>DAVID QUEIROZ</fullName>
            </value>
            <value>
                <fullName>DEIBLY ARAUJO</fullName>
            </value>
            <value>
                <fullName>DENY REYNER</fullName>
            </value>
            <value>
                <fullName>DIMAS RODRIGUES</fullName>
            </value>
            <value>
                <fullName>DOUGLAS CARVALHO</fullName>
            </value>
            <value>
                <fullName>DOUGLAS SANTOS</fullName>
            </value>
            <value>
                <fullName>EDER VIEIRA</fullName>
            </value>
            <value>
                <fullName>EDMUNDO BUBLIZ</fullName>
            </value>
            <value>
                <fullName>EDUARDO RIBEIRO</fullName>
            </value>
            <value>
                <fullName>EMERSON CÉSAR</fullName>
            </value>
            <value>
                <fullName>FHELIPE AUGUSTO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/linha.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CAMAS HOSPITALARES</fullName>
    </customValue>
    <customValue>
        <fullName>CIRURGIA MINIMAMENTE INVASIVA</fullName>
    </customValue>
    <customValue>
        <fullName>CIRURGIA ROBÓTICA</fullName>
    </customValue>
    <customValue>
        <fullName>ELETROCIRURGIA</fullName>
    </customValue>
    <customValue>
        <fullName>ENDOSCOPIA</fullName>
    </customValue>
    <customValue>
        <fullName>HUAWEI</fullName>
    </customValue>
    <customValue>
        <fullName>IMAGEM</fullName>
    </customValue>
    <customValue>
        <fullName>IMAGEM RAIO-X</fullName>
    </customValue>
    <customValue>
        <fullName>IMAGEM ULTRASSOM</fullName>
    </customValue>
    <customValue>
        <fullName>LOCAÇÃO</fullName>
    </customValue>
    <customValue>
        <fullName>MONITORES DE GRAU MEDICO</fullName>
    </customValue>
    <customValue>
        <fullName>NEONATOLOGIA</fullName>
    </customValue>
    <customValue>
        <fullName>OPME</fullName>
    </customValue>
    <customValue>
        <fullName>OUTROS</fullName>
    </customValue>
    <customValue>
        <fullName>PM</fullName>
    </customValue>
    <customValue>
        <fullName>PMLS</fullName>
    </customValue>
    <customValue>
        <fullName>SERVIÇO</fullName>
    </customValue>
    <customValue>
        <fullName>SURGICAL</fullName>
    </customValue>
    <customValue>
        <fullName>VETERINÁRIA</fullName>
    </customValue>
    <customValue>
        <fullName>VETERINÁRIA IVD</fullName>
    </customValue>
    <customValue>
        <fullName>VETERINÁRIA MIS</fullName>
    </customValue>
    <customValue>
        <fullName>VETERINÁRIA PMLS</fullName>
    </customValue>
    <customValue>
        <fullName>VIAS AÉREAS DIFÍCEIS</fullName>
    </customValue>
    <customValue>
        <fullName>VETQLAB</fullName>
    </customValue>
    <customValue>
        <fullName>INFUSÃO</fullName>
        <isActive>false</isActive>
        <label>INFUSÃO</label>
    </customValue>
    <customValue>
        <fullName>ESTERILIZACAO</fullName>
        <isActive>false</isActive>
        <label>ESTERILIZACAO</label>
    </customValue>
    <customValue>
        <fullName>CUIDADOS PESSOAIS</fullName>
        <isActive>false</isActive>
        <label>CUIDADOS PESSOAIS</label>
    </customValue>
    <customValue>
        <fullName>CMI</fullName>
        <isActive>false</isActive>
        <label>CMI</label>
    </customValue>
    <customValue>
        <fullName>LABORATORIAL</fullName>
        <isActive>false</isActive>
        <label>LABORATORIAL</label>
    </customValue>
    <customValue>
        <fullName>APOIO A MOBILIDADE</fullName>
        <isActive>false</isActive>
        <label>APOIO A MOBILIDADE</label>
    </customValue>
    <masterLabel>linha</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/ApexHelperController.cls
public with sharing class ApexHelperController {
    @AuraEnabled
    public static List<sObject> executeSoql(String soql) {
        List<sObject> result = Database.query(soql);
        return result;
        
    }
    
    @AuraEnabled
    public static Map<String, String> obterTiposDeRegistros(String nomeObjeto) {
        Map<String, String> tiposDeRegistros = new Map<String, String>();
        
        // Consultar os metadados do objeto
        Map<String, Schema.SObjectType> globalDescribe = Schema.getGlobalDescribe();
        Schema.SObjectType objectType = globalDescribe.get(nomeObjeto);
        if (objectType != null) {
            Schema.DescribeSObjectResult objDescribe = objectType.getDescribe();
            
            // Obter informações sobre os tipos de registros
            Map<String, Schema.RecordTypeInfo> recordTypes = objDescribe.getRecordTypeInfosByName();
            
            for (String recordTypeName : recordTypes.keySet()) {
                Schema.RecordTypeInfo recordTypeInfo = recordTypes.get(recordTypeName);
                tiposDeRegistros.put(recordTypeName, recordTypeInfo.getRecordTypeId());
            }
        }
        
        return tiposDeRegistros;
    }
    
    
    
    
    
    
    @AuraEnabled
    public static List<String> listagem(String nomeObjeto,  String nomeCampo){
        // String nomeObjeto = 'WorkOrder';
        //String nomeCampo = 'T_cnico_Respons_vel__c';
        List<String> valoresListaOpcao = new List<String>();
        
        // Consultar os metadados do campo
        Map<String, Schema.SObjectType> globalDescribe = Schema.getGlobalDescribe();
        Schema.SObjectType objectType = globalDescribe.get(nomeObjeto);
        if (objectType != null) {
            Schema.DescribeSObjectResult objDescribe = objectType.getDescribe();
            Map<String, Schema.SObjectField> fields = objDescribe.fields.getMap();
            
            // Verificar se o campo existe e é do tipo picklist
            if (fields.containsKey(nomeCampo)) {
                Schema.DescribeFieldResult fieldDescribe = fields.get(nomeCampo).getDescribe();
                
                if (fieldDescribe.getType() == Schema.DisplayType.PICKLIST) {
                    List<Schema.PicklistEntry> picklistValues = fieldDescribe.getPicklistValues();
                    
                    // Adicionar valores à lista
                    for (Schema.PicklistEntry entry : picklistValues) {
                        valoresListaOpcao.add(entry.getValue());
                    }
                } else {
                    System.debug('O campo não é um picklist.');
                }
            } else {
                System.debug('O campo não existe no objeto.');
            }
        }
        
        System.debug(valoresListaOpcao);
        
        return valoresListaOpcao;
    }
    
    
    @AuraEnabled
    public static string saveDoc(String text, String name, String dataType, String contentType, String folderName){
        
        List<Folder> pastaLog = ([SELECT id FROM Folder WHERE Name = :folderName]);
        
        Document doc = new Document(
            Name = name,
            Body = Blob.valueOf(text),
            ContentType = contentType,
            Type = dataType,
            IsPublic = true,
            FolderId = pastaLog[0].Id        
        );
        insert doc;
        
        return doc.Id;
    }    
    
    
    
    
    @AuraEnabled
    public static void changeStatusPurchaseOrder(String id){
        Fornecedor__c f = new Fornecedor__c();
        f.id = id;
        f.Status_do_PC__c = 'Ativo';
        update f;
    }
    
    @AuraEnabled
    public static void changeStatusSalesOrder(String id){
        Order o = new Order();
        o.id = id;
        //o.Acao_interna__c = true;
        //update o;
        
        o.Status = 'Ativo';
        
        Util.AcaoInterna(true);
        update o;
        
        if(o.OpportunityId != null) {
            Opportunity opp = new Opportunity();
            opp.id = o.OpportunityId;
            opp.StageName = 'WIN';
            opp.Sub_Fase__c = 'FINALIZADO TOTAL';
            update opp;
        }
        
        Util.AcaoInterna(false);
        
        
        //update o;
        
        //o.Acao_interna__c = false;
        //update o;
    }
    
    @AuraEnabled
    public static void updateOrderAdress(string id, string type, string street, string city, string state, string postalcode){
        Order o = new Order();
        o.Id = id;
        if (type == 'Cobranca') {
            o.BillingStreet = street;
            o.BillingCity = city;
            o.BillingState = state;
            o.BillingPostalCode = postalcode;
        }
        if (type == 'Entrega') {
            o.ShippingStreet = street;
            o.ShippingCity = city;
            o.ShippingState = state;
            o.ShippingPostalCode = postalcode;
        }
        update o;
    }
    @AuraEnabled
    public static String uploadPDF(String fileName, String pagina, String idPC) {
        PageReference pdf = new PageReference('/apex/' + pagina);
        pdf.getParameters().put('id', idPC);
        
        Blob pdfBody;
        
        if (!Test.isRunningTest()) {
            pdfBody = pdf.getContentAsPDF();
        } else {
            pdfBody = Blob.valueOf('Teste');
        }
        String base64PDF = EncodingUtil.base64Encode(pdfBody);
        system.debug(base64PDF);     
        
        // URL do endpoint do WordPress
        String url = 'http://integracao.hospcom.net:21220/uploadPDFWP';
        
        // Credenciais de autenticação
        
        // Configurar o HTTP request
        HttpRequest req = new HttpRequest();
        req.setEndpoint(url);
        req.setMethod('POST');
        
        String body = '{"file":"' + base64PDF + '","nomeArquivo":"' + fileName + '"}';
        
        system.debug(body);
        
        req.setBody(body);
        
        // Enviar a solicitação HTTP
        Http http = new Http();
        HttpResponse res;
        
        try {
            res = http.send(req);
            System.debug('Response Status: ' + res.getStatus());
            System.debug('Response Body: ' + res.getBody());
            if (res.getStatusCode() == 200) { // Código de status 200 indica criação bem-sucedida
                string resposta = res.getBody();
                string link = resposta.substringAfter('"rendered":"').substringBefore('","r');
                return link;
            } else {
                throw new CalloutException('Failed to upload PDF: ' + res.getStatus());
            }
        } catch (Exception e) {
            throw new CalloutException('Exception: ' + e.getMessage());
        }
    }
    @AuraEnabled
    public static String sendToChatGPT(String ownerId) {
        try {
            // Get the current month
            Date today = Date.today();
            Date startOfMonth = today.toStartOfMonth();
            Date endOfMonth = Date.newInstance(today.year(), today.month(), Date.daysInMonth(today.year(), today.month()));
            
            // Query opportunities
            List<Opportunity> opportunities = [
                SELECT Id, Account.Name, Forecast__c, CloseDate, Owner.Name, StageName
                FROM Opportunity
                WHERE CloseDate >= :startOfMonth
                AND CloseDate <= :endOfMonth
                AND OwnerId = :ownerId
                AND StageName NOT IN('LOSS')
            ];
            
            // Query goals
            List<Goal__c> goals = [
                SELECT Id, Meta__c
                FROM Goal__c
                WHERE Vendedor__c = :ownerId
                AND Inicio__c >= :startOfMonth
                AND Final__c <= :endOfMonth
                AND Periodo__c = 'Mensal'
                AND Linha__c = ''
            ];
            
            // Query orders to get total sales
            List<Order> orders = [
                SELECT TotalAmount
                FROM Order
                WHERE Vendedor__c = :ownerId
                AND Status IN ('Ativo', 'Em Andamento', 'Entregue Parcial', 'Entregue Total')
                AND Data_de_ativacao__c >= :startOfMonth
                AND Data_de_ativacao__c <= :endOfMonth
            ];
            
            // Calculate total sales from orders
            Decimal totalSales = 0;
            for (Order ord : orders) {
                totalSales += ord.TotalAmount;
            }
            
            // Create JSON data
            Map<String, Object> jsonData = new Map<String, Object>();
            List<Map<String, Object>> oppDetails = new List<Map<String, Object>>();
            
            for (Opportunity opp : opportunities) {
                oppDetails.add(new Map<String, Object> {
                    'Id' => opp.Id,
                        'AccountName' => opp.Account.Name,
                        'StageName' => opp.StageName,
                        'Forecast' => opp.Forecast__c,
                        'CloseDate' => opp.CloseDate.format(), // Format Date to String
                        'Vendedor' => opp.Owner.Name // Format Date to String
                        });
            }
            
            jsonData.put('opportunities', oppDetails);
            Decimal goal = (goals.size() > 0) ? goals[0].Meta__c : 0;
            jsonData.put('goal', goal);
            jsonData.put('totalSales', totalSales); // Add total sales to the JSON data
            
            String jsonPayload = JSON.serialize(jsonData);
            System.debug('JSON Payload: ' + jsonPayload);
            
            // Configure request for ChatGPT
            Http http = new Http();
            HttpRequest request = new HttpRequest();
            request.setEndpoint('https://api.openai.com/v1/chat/completions');
            request.setMethod('POST');
            request.setHeader('Content-Type', 'application/json');
            request.setHeader('Authorization', 'Bearer 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'); // Replace with your API key
            request.setTimeout(120000);  // Set timeout to 120 seconds (in milliseconds)
            
            // Messages for ChatGPT
            List<Map<String, String>> messages = new List<Map<String, String>>();
            messages.add(new Map<String, String>{ 'role' => 'system', 'content' => 'Você é um assistente útil que analisa dados financeiros.' });
            messages.add(new Map<String, String>{ 'role' => 'user', 'content' => 'Analise os dados fornecidos. Determine o total do forecast para o mês atual e compare com a meta (que é o ' + goal +', informando quanto falta para atingi-la. Os dados informam o nome do vendedor, o StageName da opp (OPEN, UPSIDE, UPSIDE HIGH, COMITED) quanto mais próximo de committed, melhor, realce as fases em que a opp está, e diga o nome do vendedor na análise retornada. Sua análise deve ser estritamente relacionada com os dados fornecidos, caso voce nao saiba, consulte novamente sua base e entenda do assunto, nao gere informações aleatorias. O correto é analisar o valor já vendido e somá-lo com o forecast (que é a previsão do que vai vender ainda).  O total de vendas já realizadas é: ' + totalSales + '. Aqui estão os dados: ' + jsonPayload });
            
            Map<String, Object> body = new Map<String, Object> {
                'model' => 'gpt-4',
                    'messages' => messages,
                    'max_tokens' => 150
                    };
                        
                        request.setBody(JSON.serialize(body));
            System.debug('Request Body: ' + JSON.serialize(body));
            
            // Send the request
            HttpResponse response = http.send(request);
            if (response.getStatusCode() == 200) {
                // Deserialize the response to access only the content
                ChatGPTResponse chatResponse = (ChatGPTResponse)JSON.deserialize(response.getBody(), ChatGPTResponse.class);
                
                // Debugging only the content of the first choice message
                if (chatResponse.choices != null && !chatResponse.choices.isEmpty()) {
                    System.debug('ChatGPT Response Content: ' + chatResponse.choices[0].message.content);
                    return chatResponse.choices[0].message.content; // Return the content of the response
                } else {
                    System.debug('No content found in the response');
                    return 'Nenhuma resposta recebida.';
                }
            } else {
                System.debug('Response Error: ' + response.getBody());
                return 'Erro: ' + response.getStatusCode() + ' - ' + response.getBody();
            }
        } catch (Exception e) {
            System.debug('Exception: ' + e.getMessage());
            return 'Erro ao enviar requisição: ' + e.getMessage();
        }
    }
    // Top-level class for ChatGPTResponse
    public class ChatGPTResponse {
        public List<ChatGPTChoice> choices;
    }
    
    // Top-level class for ChatGPTChoice
    public class ChatGPTChoice {
        public ChatGPTMessage message;
    }
    
    // Top-level class for ChatGPTMessage
    public class ChatGPTMessage {
        public String role;
        public String content;
    }
    //Devolução de itens
    @AuraEnabled
    public static void updateRecords(String recordsJson) {
        List<Item_da_Solicita_o_de_devolu_o__c> records = 
            (List<Item_da_Solicita_o_de_devolu_o__c>)JSON.deserialize(recordsJson, List<Item_da_Solicita_o_de_devolu_o__c>.class);
        
        update records;
    }
    @AuraEnabled
    public static void saveConcorrentesApex(String concorrentes, Id oportunidadeId, id produto) {
        system.debug(concorrentes + ' ' + oportunidadeId + ' ' + produto);
        List<Analise_de_Mercado__c> analisesToInsert = new List<Analise_de_Mercado__c>();
        List<ConcorrenteData> concorrenteList = (List<ConcorrenteData>) JSON.deserialize(concorrentes, List<ConcorrenteData>.class);
        
        // Prepara os concorrentes para inserção
        for (ConcorrenteData conc : concorrenteList) {
            Analise_de_Mercado__c am = new Analise_de_Mercado__c();
            am.Concorrente__c = conc.accountId;  // ID da conta
            am.Oportunidade__c = oportunidadeId;
            am.Produto_da_oportunidade__c = produto;
            am.Situacao__c = conc.situacao;
            am.Motivo__c = conc.motivo;
            am.Modelo_ofertado__c = conc.modelo;
            if (conc.precoUnitario != null && !String.isBlank(conc.precoUnitario)) {
                try {
                    String precoStr = conc.precoUnitario.replaceAll('\\.', '').replaceAll(',', '.');
                    am.Preco_unitario__c = Decimal.valueOf(precoStr.trim());
                } catch (Exception e) {
                    throw new AuraHandledException('Valor unitário inválido: ' + conc.precoUnitario + ' -> ' + e.getMessage());
                }
            }
            
            if (conc.precoTotal != null && !String.isBlank(conc.precoTotal)) {
                try {
                    String precoTotalStr = conc.precoTotal.replaceAll('\\.', '').replaceAll(',', '.');
                    am.Valor_total__c = Decimal.valueOf(precoTotalStr.trim());
                } catch (Exception e) {
                    throw new AuraHandledException('Valor total inválido: ' + conc.precoTotal + ' -> ' + e.getMessage());
                }
            }
            am.Marca__c = conc.marca; 
            am.Observacoes__c = conc.obs;
            analisesToInsert.add(am);
            
        }
        
        // Insere os concorrentes no Salesforce
        if (!analisesToInsert.isEmpty()) {
            try{
                insert analisesToInsert;
            }
            catch(Exception e){
                throw new AuraHandledException(e.getMessage());
            }
        }
    }
    
    // Classe interna para representar os dados do concorrente
    public class ConcorrenteData {
        @AuraEnabled public String accountId { get; set; }
        @AuraEnabled public String marca { get; set; }
        @AuraEnabled public String motivo { get; set; }
        @AuraEnabled public String situacao { get; set; }
        @AuraEnabled public String modelo { get; set; }
        @AuraEnabled public String precoUnitario { get; set; }
        @AuraEnabled public String precoTotal { get; set; }
        @AuraEnabled public String obs { get; set; }
    }
}