force-app/main/default/objects/L_M_D__c/L_M_D__c.object-meta.xml
<CustomObject>
    <description>Lista Mestre de Documentação</description>
    <label>L.M.D</label>
    <nameField>
        <label>Empresa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>L.M.D</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/L_M_D__c/fields/Conta_Relacionada__c.field-meta.xml
<CustomField>
    <fullName>Conta_Relacionada__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta Relacionada</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>L.M.D</relationshipLabel>
    <relationshipName>L_M_D</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/L_M_D__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Em aprovação</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PSQ__c/PSQ__c.object-meta.xml
<CustomObject>
    <label>Procedimento do Sistema de Qualidade</label>
    <nameField>
        <label>Título do Documento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Procedimentos do Sistema de Qualidade</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PSQ__c/fields/L_M_D__c.field-meta.xml
<CustomField>
    <fullName>L_M_D__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>L.M.D</label>
    <referenceTo>L_M_D__c</referenceTo>
    <relationshipLabel>Procedimentos do Sistema de Qualidade (L.M.D)</relationshipLabel>
    <relationshipName>Procedimentos_do_Sistema_de_Qualidade</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PSQ__c/fields/PSQ__c.field-meta.xml
<CustomField>
    <fullName>PSQ__c</fullName>
    <displayFormat>PSQ - {0000}</displayFormat>
    <label>PSQ</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/PSQ__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Elaboração</fullName>
                <default>true</default>
                <label>Elaboração</label>
            </value>
            <value>
                <fullName>Revisão</fullName>
            </value>
            <value>
                <fullName>Aprovação</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Em vigência</fullName>
            </value>
            <value>
                <fullName>Obsoleto</fullName>
            </value>
            <value>
                <fullName>Em aprovação</fullName>
                <isActive>false</isActive>
                <label>Em aprovação</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PSQ__c/recordTypes/PSQ.recordType-meta.xml
<RecordType>
    <fullName>PSQ</fullName>
    <active>true</active>
    <description>Procedimento do Sistema de Qualidade</description>
    <label>PSQ</label>
</RecordType>

force-app/main/default/classes/listagem_lmd_test.cls
@isTest
public class listagem_lmd_test {

    //LMD Sandbox: 0015300000R5SUL
    //LMD Produção: 001i00000085QYb
    @isTest
    static void testListagem_hr() {
        
        L_M_D__c lmd = new L_M_D__c(Conta_Relacionada__c = '001i00000085QYb', Name = 'nome');
        insert lmd;

        PSQ__c psq = new PSQ__c(L_M_D__c = lmd.Id, Status__c = 'Em vigência');
        insert psq;

        ApexPages.StandardController controller = new ApexPages.StandardController(lmd);

        listagem_lmd listagem = new listagem_lmd(controller);

        listagem.listagem_lmd(lmd);

    }
}