force-app/main/default/objects/Reserva_de_Sala__c/Reserva_de_Sala__c.object-meta.xml
<CustomObject>
    <label>Reserva</label>
    <nameField>
        <displayFormat>RES - {0000}</displayFormat>
        <label>Reserva</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Reserva_de_Sala__c/fields/Frequencia__c.field-meta.xml
<CustomField>
    <fullName>Frequencia__c</fullName>
    <inlineHelpText>Quantas vezes essa reserva se repetirá?</inlineHelpText>
    <label>Frequência</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Reserva_de_Sala__c/fields/In_cio__c.field-meta.xml
<CustomField>
    <fullName>In_cio__c</fullName>
    <label>Início</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Reserva_de_Sala__c/fields/recorrencia__c.field-meta.xml
<CustomField>
    <fullName>recorrencia__c</fullName>
    <formula>if(Text(Reserva_recorrente__c) == &apos;Semanal&apos;, 7,
if(Text(Reserva_recorrente__c) == &apos;Quinzenal&apos;, 14, 
if(Text(Reserva_recorrente__c) == &apos;Quinzenal&apos;, 28, null)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Qual o tipo de recorrencia dessa reserva?</inlineHelpText>
    <label>Recorrencia</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Reserva_de_Sala__c/fields/Reserva__c.field-meta.xml
<CustomField>
    <fullName>Reserva__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reserva</label>
    <referenceTo>Reserva_de_Sala__c</referenceTo>
    <relationshipLabel>Reservas</relationshipLabel>
    <relationshipName>Reservas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Reserva_de_Sala__c/fields/Sala__c.field-meta.xml
<CustomField>
    <fullName>Sala__c</fullName>
    <label>Sala</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Auditório</fullName>
            </value>
            <value>
                <fullName>Auditório Oeste</fullName>
            </value>
            <value>
                <fullName>Sala de Reunião</fullName>
            </value>
            <value>
                <fullName>Sala de Reunião 2</fullName>
            </value>
            <value>
                <fullName>Showroom</fullName>
            </value>
            <value>
                <fullName>Showroom &amp; Auditório</fullName>
            </value>
            <value>
                <fullName>Showroom VET</fullName>
            </value>
            <value>
                <fullName>Sala de Reunião 1 - Oeste</fullName>
            </value>
            <value>
                <fullName>Sala de Reunião 2 - Oeste</fullName>
            </value>
            <value>
                <fullName>Sala de Reunião 3 - Oeste</fullName>
            </value>
            <value>
                <fullName>Sala de Vídeo Conferência 1 - Oeste</fullName>
            </value>
            <value>
                <fullName>Sala de Vídeo Conferência 2 - Oeste</fullName>
            </value>
            <value>
                <fullName>Administrativo - Oeste</fullName>
            </value>
            <value>
                <fullName>Sala de Podcast</fullName>
                <isActive>false</isActive>
                <label>Sala de Podcast</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reserva_de_Sala__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Novo</fullName>
            </value>
            <value>
                <fullName>Em aprovação</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Em curso</fullName>
            </value>
            <value>
                <fullName>Finalizado</fullName>
            </value>
            <value>
                <fullName>Reprovado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Reserva_de_Sala__c/fields/Termino__c.field-meta.xml
<CustomField>
    <fullName>Termino__c</fullName>
    <label>Término</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/Reserva.cls
public class Reserva {
    
    // Adicionando tratamento de erros mais específico
    public static void criaRecorrencia(Reserva_de_Sala__c rs){
    
            for(Integer i = 1; i <= rs.Frequencia__c; i++){
                Reserva_de_Sala__c novaRS = new Reserva_de_Sala__c();
                novaRS.In_cio__c = rs.In_cio__c.addDays((Integer.valueOf(rs.recorrencia__c) * i));
                novaRS.Termino__c = rs.Termino__c.addDays((Integer.valueOf(rs.recorrencia__c) * i));
                novaRS.Sala__c = rs.Sala__c;
                //novaRS.recorrente__c = true;
                novaRS.Status__c = rs.Status__c;
                novaRS.RecordTypeId = rs.RecordTypeId;
                novaRS.Reserva__c = rs.id;
                
            try {
                insert novaRS;
            } catch (Exception e) {
                
                System.debug('Erro ao criar recorrência: ' + e.getMessage());
                //throw new CustomException('Erro ao criar recorrência: ' + e.getMessage());
            }
                
            }
        
    }
    
}