force-app/main/default/objects/PSQ__c/PSQ__c.object-meta.xml
<CustomObject>
    <label>Procedimento do Sistema de Qualidade</label>
    <nameField>
        <label>Título do Documento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Procedimentos do Sistema de Qualidade</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PSQ__c/fields/Aplicao__c.field-meta.xml
<CustomField>
    <fullName>Aplicao__c</fullName>
    <label>Aplicação</label>
    <length>97306</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PSQ__c/fields/Condi_es_Gerais__c.field-meta.xml
<CustomField>
    <fullName>Condi_es_Gerais__c</fullName>
    <label>Condições Gerais</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/PSQ__c/fields/Defini_es__c.field-meta.xml
<CustomField>
    <fullName>Defini_es__c</fullName>
    <label>Definições</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/PSQ__c/fields/Elaborador__c.field-meta.xml
<CustomField>
    <fullName>Elaborador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Elaborador</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Procedimentos_do_Sistema_de_Qualidade</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PSQ__c/fields/Equipamentos_e_Softwares__c.field-meta.xml
<CustomField>
    <fullName>Equipamentos_e_Softwares__c</fullName>
    <label>Equipamentos e Softwares</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/PSQ__c/fields/Formul_rios_Anexos_e_Documentos__c.field-meta.xml
<CustomField>
    <fullName>Formul_rios_Anexos_e_Documentos__c</fullName>
    <label>Formulários, Anexos e Documentos</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PSQ__c/fields/Objetivo__c.field-meta.xml
<CustomField>
    <fullName>Objetivo__c</fullName>
    <label>Objetivo</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/PSQ__c/fields/PSQ__c.field-meta.xml
<CustomField>
    <fullName>PSQ__c</fullName>
    <displayFormat>PSQ - {0000}</displayFormat>
    <label>PSQ</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/PSQ__c/fields/Refer_ncia__c.field-meta.xml
<CustomField>
    <fullName>Refer_ncia__c</fullName>
    <label>Referência</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PSQ__c/fields/Registros__c.field-meta.xml
<CustomField>
    <fullName>Registros__c</fullName>
    <label>Registros</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/PSQ__c/fields/Responsabilidade_e_Autoridade__c.field-meta.xml
<CustomField>
    <fullName>Responsabilidade_e_Autoridade__c</fullName>
    <label>Responsabilidade e Autoridade</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/PSQ__c/fields/Revisor__c.field-meta.xml
<CustomField>
    <fullName>Revisor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Revisor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Procedimentos_do_Sistema_de_Qualidade2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PSQ__c/recordTypes/PSQ.recordType-meta.xml
<RecordType>
    <fullName>PSQ</fullName>
    <active>true</active>
    <description>Procedimento do Sistema de Qualidade</description>
    <label>PSQ</label>
</RecordType>

force-app/main/default/objects/Registros__c/Registros__c.object-meta.xml
<CustomObject>
    <description>Objeto utilizado para fazer o controle de sobre etapas de Tarefa</description>
    <label>Registro</label>
    <nameField>
        <label>Registro</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Registros</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/PSQcriaAtualizacaoTeste.cls
@isTest
public class PSQcriaAtualizacaoTeste {
       /*static void testAtualizaLMD() {
        
        List<Map<String, String>> fileList = new List<Map<String, String>>();
        
        Map<String, String> file1 = new Map<String, String>();
        file1.put('file', 'JVBERi0xLjIgDQo5IDAgb2JqDQo8PA0KPj4NCnN0cmVhbQ0KQlQvIDMyIFRmKCAgSGVsbG8gV29ybGQgICApJyBFVA0KZW5kc3RyZWFtDQplbmRvYmoNCjQgMCBvYmoNCjw8DQovVHlwZSAvUGFnZQ0KL1BhcmVudCA1IDAgUg0KL0NvbnRlbnRzIDkgMCBSDQo+Pg0KZW5kb2JqDQo1IDAgb2JqDQo8PA0KL0tpZHMgWzQgMCBSIF0NCi9Db3VudCAxDQovVHlwZSAvUGFnZXMNCi9NZWRpYUJveCBbIDAgMCAyNTAgNTAgXQ0KPj4NCmVuZG9iag0KMyAwIG9iag0KPDwNCi9QYWdlcyA1IDAgUg0KL1R5cGUgL0NhdGFsb2cNCj4+DQplbmRvYmoNCnRyYWlsZXINCjw8DQovUm9vdCAzIDAgUg0KPj4NCiUlRU9G');
        file1.put('ex', 'pdf');
        Map<String, String> file2 = new Map<String, String>();
        file2.put('file', 'JVBERi0xLjIgDQo5IDAgb2JqDQo8PA0KPj4NCnN0cmVhbQ0KQlQvIDMyIFRmKCAgSGVsbG8gV29ybGQgICApJyBFVA0KZW5kc3RyZWFtDQplbmRvYmoNCjQgMCBvYmoNCjw8DQovVHlwZSAvUGFnZQ0KL1BhcmVudCA1IDAgUg0KL0NvbnRlbnRzIDkgMCBSDQo+Pg0KZW5kb2JqDQo1IDAgb2JqDQo8PA0KL0tpZHMgWzQgMCBSIF0NCi9Db3VudCAxDQovVHlwZSAvUGFnZXMNCi9NZWRpYUJveCBbIDAgMCAyNTAgNTAgXQ0KPj4NCmVuZG9iag0KMyAwIG9iag0KPDwNCi9QYWdlcyA1IDAgUg0KL1R5cGUgL0NhdGFsb2cNCj4+DQplbmRvYmoNCnRyYWlsZXINCjw8DQovUm9vdCAzIDAgUg0KPj4NCiUlRU9G');
        file2.put('ex', 'pdf');
        
        // Crie uma instância do objeto PSQ
        PSQ__c novoRegistroPSQ = new PSQ__c();
        
        Map<String, String> psq = new Map<String, String>();
        
        // Adicionando variáveis ao mapa
        
        
        psq.put('revisor__c', '00531000006UzZsAAK');
        psq.put('revisor__c', '00531000006UzZsAAK');
        psq.put('elaborador__c', '00531000006UzZsAAK');
        psq.put('C_digo_do_Documento__c', 'T 2-0');
        psq.put('N_da_Revis_o__c', 'Tes-0');
        psq.put('Objetivo__c', '');
        psq.put('Aplicao__c', '');
        psq.put('Defini_es__c', '');
        psq.put('Equipamentos_e_Softwares__c', '');
        psq.put('Condi_es_Gerais__c', '5.1esmos;\n 5.2. Utilizar marcadores em ordes externos.');
        psq.put('Responsabilidade_e_Autoridade__c', '<pjghjhgfjfghj>/p>');
        psq.put('Refer_ncia__c', '');
        psq.put('Formul_rios_Anexos_e_Documentos__c', 's;');
        psq.put('Registros__c', 'Relacione aqui os  houver.');
        psq.put('Id', 'a0h6e00000KCEubAAH');
        fileList.add(file1);
        fileList.add(file2);
        
        List<String> f = new List<String>();
        List<String> b = new List<String>();
        
        // modelos
        List<Map<String, String>> empresas = new List<Map<String, String>>();
        
        Map<String, String> empresa1 = new Map<String, String>();
        empresa1.put('id', '001i00000085QYb');
        empresa1.put('nome', 'HOSPCOM1');
        Map<String, String> empresa2 = new Map<String, String>();
        empresa2.put('id', '001i00000085QYb');
        empresa2.put('nome', 'HOSPCOM1');
        empresas.add(empresa1);
        empresas.add(empresa2);
        
        try{
            //a0g530000062hwWAAQ sandbox
            ////a0g6e00000JW5s6AAD Produção
            //
            PSQcriaAtualizacao.criaPSQ(empresas, psq, fileList,'a0g6e00000JW5s6AAD');           
            PSQcriaAtualizacao.gambiarra();
        }catch(Exception e){
            System.debug('Error: ' + e.getMessage());
        }
    }*/
    @isTest
 
    static void aaa(){
        PSQcriaAtualizacao.gambiarra();
        PSQcriaAtualizacao.gambiarra2();
    }
}