force-app/main/default/objects/Item_Requerido__c/Item_Requerido__c.object-meta.xml
<CustomObject>
    <label>Item Requerido</label>
    <nameField>
        <displayFormat>Item{0000}</displayFormat>
        <label>Nome de Item Requerido</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens Requeridos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Item_Requerido__c/fields/Requisi_o_Interna_Relacionada__c.field-meta.xml
<CustomField>
    <fullName>Requisi_o_Interna_Relacionada__c</fullName>
    <label>Requisição Interna Relacionada</label>
    <referenceTo>Requisi_o_Interna__c</referenceTo>
    <relationshipLabel>Itens Requeridos</relationshipLabel>
    <relationshipName>Itens_Requeridos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Item_Requerido__c/fields/Status_do_Item__c.field-meta.xml
<CustomField>
    <fullName>Status_do_Item__c</fullName>
    <label>Status do Item</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NOVO</fullName>
                <default>true</default>
                <label>NOVO</label>
            </value>
            <value>
                <fullName>AGUARDANDO COMPRA FORNECEDOR</fullName>
            </value>
            <value>
                <fullName>AGUARDANDO ENTREGA FORNECEDOR</fullName>
            </value>
            <value>
                <fullName>FINALIZADO</fullName>
            </value>
            <value>
                <fullName>RECEBIDO FORNECEDOR</fullName>
            </value>
            <value>
                <fullName>CANCELADO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/atualizaItemRequisicao.cls
public class atualizaItemRequisicao {
   @AuraEnabled
    public static void atualizaItem(string idsItens, string statusAtual){
        
        String idsItensQ = idsItens ;
        
        List<String> lstIds =   idsItensQ.split(',');//separa cada id de itens e adciona em uma lista.
        
        List <Item_Requerido__c> itensParaAtualizar = [SELECT name, id ,Status_do_Item__c , Requisi_o_Interna_Relacionada__c, Quantidade__c FROM Item_Requerido__c WHERE id IN :lstIds ];
        
        
        
        for(Integer i = 0; i < itensParaAtualizar.size(); i++ ){
            
            itensParaAtualizar[i].Status_do_Item__c = statusAtual;
            
            update  itensParaAtualizar[i];
            
        }
        
        String a = 'a';
        String b = 'b';
        String c = 'c';
        String d = 'd';
        
       System.debug(itensParaAtualizar); 
    }
}