force-app/main/default/objects/Membro_Interno_do_Evento__c/Membro_Interno_do_Evento__c.object-meta.xml
<CustomObject>
    <label>Membro Interno do Evento</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Membros Internos do Evento</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Membro_Interno_do_Evento__c/fields/Contato__c.field-meta.xml
<CustomField>
    <fullName>Contato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Apenas quando o participante não tiver acesso ao Salesforce.</inlineHelpText>
    <label>Contato</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.Account.Name</field>
            <operation>equals</operation>
            <value>HOSPCOM</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Membros Internos do Evento</relationshipLabel>
    <relationshipName>Membros_Internos_do_Evento</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Membro_Interno_do_Evento__c/fields/Empresa__c.field-meta.xml
<CustomField>
    <fullName>Empresa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Empresa</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Membros Internos do Evento</relationshipLabel>
    <relationshipName>Membros_Internos_do_Evento</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Membro_Interno_do_Evento__c/fields/Evento__c.field-meta.xml
<CustomField>
    <fullName>Evento__c</fullName>
    <label>Evento</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Responsáveis pelo evento</relationshipLabel>
    <relationshipName>Membros_da_Equipe_do_Evento</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Treinamento_ImpedeCriacaoDeDuplicadas_T.cls
@isTest(seeAllData=true)
private class Treinamento_ImpedeCriacaoDeDuplicadas_T {
	
    @isTest 
    static void Teste1(){         
	
		Membro_Interno_do_Evento__c novoMembro = new Membro_Interno_do_Evento__c();
        
        novoMembro.Evento__c = '701U4000000Vy81IAC';
        novoMembro.Contato__c = '0036e00004FczvvAAB';
        novoMembro.Empresa__c = '001i00000085QYbAAM';
	
        try{
        	insert novoMembro;
        }catch(Exception e){
            System.debug('Error: '+ e);
        }
        Membro_Interno_do_Evento__c novoMembro2 = new Membro_Interno_do_Evento__c();
        
        novoMembro2.Evento__c = '701U4000000Vy81IAC';
        novoMembro2.Contato__c = '0036e00004FczvvAAB';
        novoMembro2.Empresa__c = '001i00000085QYbAAM';

        try{
            insert novoMembro2;
        }catch(Exception e){
            System.debug('Error: '+ e);
        }
        
    }
 	
}