force-app/main/default/objects/Cliente__c/Cliente__c.object-meta.xml
<CustomObject>
    <label>Empresa cliente</label>
    <nameField>
        <label>Nome de Cliente:</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empresas_cliente</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cliente__c/fields/E_Mail__c.field-meta.xml
<CustomField>
    <fullName>E_Mail__c</fullName>
    <label>E-Mail</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/Contrato_de_Servi_o__c.object-meta.xml
<CustomObject>
    <label>Contrato de Serviço</label>
    <nameField>
        <label>Nome do Contrato</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contratos de Serviços</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contratos de Locação</relationshipLabel>
    <relationshipName>Contratos_de_Servi_os</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Contato_do_Locat_rio__c.field-meta.xml
<CustomField>
    <fullName>Contato_do_Locat_rio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contato do Locatário</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contratos de Serviços</relationshipLabel>
    <relationshipName>Contratos_de_Servi_os</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Dura_o_do_Contrato_meses__c.field-meta.xml
<CustomField>
    <fullName>Dura_o_do_Contrato_meses__c</fullName>
    <label>Duração do Contrato</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/N_mero_da_Proposta_Contrato__c.field-meta.xml
<CustomField>
    <fullName>N_mero_da_Proposta_Contrato__c</fullName>
    <displayFormat>{0000000}</displayFormat>
    <label>Número da Proposta/Contrato</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Pesq_Satisfacao_Enviada__c.field-meta.xml
<CustomField>
    <fullName>Pesq_Satisfacao_Enviada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pesquisa de Satisfação Enviada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Tipo_da_Dura_o__c.field-meta.xml
<CustomField>
    <fullName>Tipo_da_Dura_o__c</fullName>
    <label>Tipo da Duração</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>dia(s)</fullName>
            </value>
            <value>
                <fullName>mes(es)</fullName>
            </value>
            <value>
                <fullName>procedimento(s)</fullName>
            </value>
            <value>
                <fullName>serviço(s)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Contrato_de_Servi_o__c.field-meta.xml
<CustomField>
    <fullName>Contrato_de_Servi_o__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato de Serviço</label>
    <referenceTo>Contrato_de_Servi_o__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Departamento3__c.field-meta.xml
<CustomField>
    <fullName>Departamento3__c</fullName>
    <label>Departamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Departamentos</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Natureza_de_Opera_o__c.field-meta.xml
<CustomField>
    <fullName>Natureza_de_Opera_o__c</fullName>
    <label>Natureza de Operação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BONIFICAÇÃO</fullName>
            </value>
            <value>
                <fullName>DEMONSTRAÇÃO</fullName>
            </value>
            <value>
                <fullName>LOCAÇÃO</fullName>
            </value>
            <value>
                <fullName>EMPRÉSTIMO</fullName>
            </value>
            <value>
                <fullName>REMESSA DE LOCAÇÃO</fullName>
            </value>
            <value>
                <fullName>REMESSA DE TROCA</fullName>
            </value>
            <value>
                <fullName>REMESSA EM CONSIGNAÇÃO</fullName>
            </value>
            <value>
                <fullName>SERVIÇO</fullName>
            </value>
            <value>
                <fullName>VENDA</fullName>
            </value>
            <value>
                <fullName>VENDA DA CONSIGNAÇÃO</fullName>
            </value>
            <value>
                <fullName>RETORNO DE LOCAÇÃO</fullName>
            </value>
            <value>
                <fullName>EXPORTAÇÃO</fullName>
            </value>
            <value>
                <fullName>Baixa de estoque Interno</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Ordem_de_trabalho__c.field-meta.xml
<CustomField>
    <fullName>Ordem_de_trabalho__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ordem de trabalho</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/recordTypes/Hospcom.recordType-meta.xml
<RecordType>
    <fullName>Hospcom</fullName>
    <active>true</active>
    <description>Para faturamento das empresas do grupo Hospcom</description>
    <label>Hospcom</label>
</RecordType>

force-app/main/default/objects/Quote/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <formula>IF(Opportunity.Account.CNPJ__c != null, Opportunity.Account.Name, Opportunity.Account.FirstName + &apos; &apos; + Opportunity.Account.LastName)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cliente</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Contrato_de_Servi_o__c.field-meta.xml
<CustomField>
    <fullName>Contrato_de_Servi_o__c</fullName>
    <formula>Case.ContratodeServico__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contrato de Serviço</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/E_mail__c.field-meta.xml
<CustomField>
    <fullName>E_mail__c</fullName>
    <formula>Contact.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>E-mail do Contato</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Pesq_Satisfacao_Enviada__c.field-meta.xml
<CustomField>
    <fullName>Pesq_Satisfacao_Enviada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pesquisa de Satisfação Enviada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Departamentos.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Administrativo</fullName>
    </customValue>
    <customValue>
        <fullName>Comercial</fullName>
    </customValue>
    <customValue>
        <fullName>Compras</fullName>
    </customValue>
    <customValue>
        <fullName>Contabilidade</fullName>
        <label>Contabilidade/Fiscal/DP</label>
    </customValue>
    <customValue>
        <fullName>Controladoria</fullName>
    </customValue>
    <customValue>
        <fullName>Desenvolvimento</fullName>
    </customValue>
    <customValue>
        <fullName>Diretoria Administrativa</fullName>
    </customValue>
    <customValue>
        <fullName>Diretoria de B.I e Growth</fullName>
    </customValue>
    <customValue>
        <fullName>Diretoria de Negocios</fullName>
    </customValue>
    <customValue>
        <fullName>Educação</fullName>
        <label>Educação Continuada</label>
    </customValue>
    <customValue>
        <fullName>Faturamento</fullName>
    </customValue>
    <customValue>
        <fullName>Financeiro</fullName>
    </customValue>
    <customValue>
        <fullName>Governo</fullName>
    </customValue>
    <customValue>
        <fullName>Jurídico</fullName>
    </customValue>
    <customValue>
        <fullName>Locação</fullName>
    </customValue>
    <customValue>
        <fullName>Logística</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing</fullName>
    </customValue>
    <customValue>
        <fullName>Operações</fullName>
    </customValue>
    <customValue>
        <fullName>Outros</fullName>
    </customValue>
    <customValue>
        <fullName>Qualidade</fullName>
    </customValue>
    <customValue>
        <fullName>RH</fullName>
    </customValue>
    <customValue>
        <fullName>Serviço</fullName>
    </customValue>
    <customValue>
        <fullName>Departamento Pessoal</fullName>
        <isActive>false</isActive>
        <label>Departamento Pessoal</label>
    </customValue>
    <customValue>
        <fullName>Facilites</fullName>
        <isActive>false</isActive>
        <label>Facilites</label>
    </customValue>
    <customValue>
        <fullName>T.I.</fullName>
        <isActive>false</isActive>
        <label>T.I.</label>
    </customValue>
    <customValue>
        <fullName>OPME</fullName>
        <isActive>false</isActive>
        <label>OPME</label>
    </customValue>
    <customValue>
        <fullName>Manutenção</fullName>
        <isActive>false</isActive>
        <label>Manutenção</label>
    </customValue>
    <customValue>
        <fullName>Limpeza</fullName>
        <isActive>false</isActive>
        <label>Limpeza</label>
    </customValue>
    <customValue>
        <fullName>Fiscal</fullName>
        <isActive>false</isActive>
        <label>Fiscal</label>
    </customValue>
    <masterLabel>Departamentos</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/PesquisaSatisf.cls
global class PesquisaSatisf {

    Public Static List<String> orderEmail; 

    //Pesquisa de Satisfação Dep. Comercial
    
    @future(callout=true)
    public static void enviar(id oid){
        Order pedido = [SELECT OrderNumber, QuoteId, Contrato_de_Servi_o__c, Departamento3__c, Ordem_de_trabalho__c, Natureza_de_Opera_o__c, Pesq_Satisfacao_Enviada__c FROM Order WHERE Id =: oid];
        Account conta;
        Contact contato;
        
        if(pedido.QuoteId != null && pedido.Departamento3__c == 'Comercial'){
            Quote cotacao = [SELECT ContactId FROM Quote WHERE Id =: pedido.QuoteId];
        	contato = [SELECT Name, Email FROM Contact WHERE Id =: cotacao.ContactId];
          
			HttpRequest r = new HttpRequest();
            r.setEndpoint('https://app.binds.co/api/seeds');
            Blob headerValue = Blob.valueOf('desenvolvimento@hospcom.net' + ':' + 'hosp@3241');
            String authorizationHeader = 'BASIC ' + EncodingUtil.base64Encode(headerValue);
            r.setHeader('Authorization', authorizationHeader);
            r.setHeader('Content-Type', 'application/json');
            r.setMethod('POST');
            r.setBody('{"collector": "611d6cd5adc7fcb5e6411880","from": {"name":"'+ contato.Name 	 +'","email": "'+ contato.Email +'"},"metadata": {"pedido": "'+ pedido.OrderNumber +'"}}');
     
            HttpResponse response = new HttpResponse();
          try {
            response = new Http().send(r);
            }
          catch(System.CalloutException e)  {
                System.debug('Callout error: '+ e);
                System.debug(response.toString());                
            }
		        
        Integer statusCode = response.getStatusCode();
        System.debug('TESTEAQUI ' + statusCode);
        
        if(statusCode == 201){
            integer test = 1;
           pedido.Pesq_Satisfacao_Enviada__c = true;
        
        	try{
                update pedido;
        		}
            catch(Exception e) {
                System.debug('ERRO: '+ e);
        		}

        }                    
            System.Debug(LoggingLevel.INFO,'#### response: ' + response);
            System.Debug(LoggingLevel.INFO,'#### response.getBody: ' + response.getBody()); 
            System.Debug(LoggingLevel.INFO,'#### response.getStatus: ' + response.getStatusCode()); 

    }
    }
    
    // Pesquisa de Satisfação Dep. de Serviços
    
    @future(callout=true)
    public static void enviarSERV(id oid){
        WorkOrder OT = [SELECT WorkOrderNumber, ContactId, E_mail__c, Pesq_Satisfacao_Enviada__c FROM WorkOrder WHERE Id =: oid];
        Contact contato = [SELECT Name FROM Contact WHERE ID =: OT.ContactId];
        
          
			HttpRequest r = new HttpRequest();
            r.setEndpoint('https://app.binds.co/api/seeds');
            Blob headerValue = Blob.valueOf('desenvolvimento@hospcom.net' + ':' + 'hosp@3241');
            String authorizationHeader = 'BASIC ' + EncodingUtil.base64Encode(headerValue);
            r.setHeader('Authorization', authorizationHeader);
            r.setHeader('Content-Type', 'application/json');
            r.setMethod('POST');
            r.setBody('{"collector": "612e4442adc7fcb5e62db209","from": {"name":"'+ contato.Name +'","email": "'+ OT.E_mail__c +'"},"metadata": {"pedido": "'+ OT.WorkOrderNumber +'"}}');
     
            HttpResponse response = new HttpResponse();
          try {
            response = new Http().send(r);
            }
          catch(System.CalloutException e)  {
                System.debug('Callout error: '+ e);
                System.debug(response.toString());                
            }
		        
        Integer statusCode = response.getStatusCode();
        System.debug('TESTEAQUI ' + statusCode);
        
        if(statusCode == 201){
            integer test = 1;
           OT.Pesq_Satisfacao_Enviada__c = true;
        
        	try{
                update OT;
        		}
            catch(Exception e) {
                System.debug('ERRO: '+ e);
        		}

        }                    
            System.Debug(LoggingLevel.INFO,'#### response: ' + response);
            System.Debug(LoggingLevel.INFO,'#### response.getBody: ' + response.getBody()); 
            System.Debug(LoggingLevel.INFO,'#### response.getStatus: ' + response.getStatusCode()); 

    }
    
    // Pesquisa de Satisfação Dep. de Locação

    @future(callout=true)
    public static void enviarLOCAC(id oid){
        Contrato_de_Servi_o__c CL = [SELECT Name, Cliente__c, N_mero_da_Proposta_Contrato__c, Contato_do_Locat_rio__c, Dura_o_do_Contrato_meses__c, Tipo_da_Dura_o__c, Pesq_Satisfacao_Enviada__c FROM Contrato_de_Servi_o__c WHERE Id =: oid];
        string nome;
        string email;
        
        if(CL.Contato_do_Locat_rio__c != null){ 
            Contact contato = [SELECT Name, Email FROM Contact WHERE ID =: CL.Contato_do_Locat_rio__c];
            nome = contato.Name;
            email = contato.Email;
        }
        else{
            Account conta = [SELECT Name, PersonEmail FROM Account WHERE Id =: CL.Cliente__c];
            nome = conta.Name;
            email = conta.PersonEmail;
        }
        
			HttpRequest r = new HttpRequest();
            r.setEndpoint('https://app.binds.co/api/seeds');
            Blob headerValue = Blob.valueOf('desenvolvimento@hospcom.net' + ':' + 'hosp@3241');
            String authorizationHeader = 'BASIC ' + EncodingUtil.base64Encode(headerValue);
            r.setHeader('Authorization', authorizationHeader);
            r.setHeader('Content-Type', 'application/json');
            r.setMethod('POST');
            r.setBody('{"collector": "612e456eadc7fcb5e62ead02","from": {"name":"'+ nome +'","email": "'+ email +'"},"metadata": {"pedido": "'+ CL.N_mero_da_Proposta_Contrato__c +'"}}');
     
            HttpResponse response = new HttpResponse();
          try {
            response = new Http().send(r);
            }
          catch(System.CalloutException e)  {
                System.debug('Callout error: '+ e);
                System.debug(response.toString());                
            }
		        
        Integer statusCode = response.getStatusCode();
        System.debug('TESTEAQUI ' + statusCode);
        
        if(statusCode == 201){
            integer test = 1;
           CL.Pesq_Satisfacao_Enviada__c = true;
        
        	try{
                update CL;
        		}
            catch(Exception e) {
                System.debug('ERRO: '+ e);
        		}

        }                    
            System.Debug(LoggingLevel.INFO,'#### response: ' + response);
            System.Debug(LoggingLevel.INFO,'#### response.getBody: ' + response.getBody()); 
            System.Debug(LoggingLevel.INFO,'#### response.getStatus: ' + response.getStatusCode()); 


    }
    }