force-app/main/default/objects/Cliente__c/Cliente__c.object-meta.xml
<CustomObject>
    <label>Empresa cliente</label>
    <nameField>
        <label>Nome de Cliente:</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Empresas_cliente</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contrato_de_Servi_o__c/Contrato_de_Servi_o__c.object-meta.xml
<CustomObject>
    <label>Contrato de Serviço</label>
    <nameField>
        <label>Nome do Contrato</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contratos de Serviços</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Cl_usula_D_cima_Editada__c.field-meta.xml
<CustomField>
    <fullName>Cl_usula_D_cima_Editada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cláusula Décima Editada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Cl_usula_D_cima_Primeira_Editada__c.field-meta.xml
<CustomField>
    <fullName>Cl_usula_D_cima_Primeira_Editada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cláusula Décima Primeira Editada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Cl_usula_Nona_Editada__c.field-meta.xml
<CustomField>
    <fullName>Cl_usula_Nona_Editada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cláusula Nona Editada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Cl_usula_Oitava_Editada__c.field-meta.xml
<CustomField>
    <fullName>Cl_usula_Oitava_Editada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cláusula Oitava Editada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Cl_usula_Primeira_Editada__c.field-meta.xml
<CustomField>
    <fullName>Cl_usula_Primeira_Editada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cláusula Primeira Editada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Cl_usula_Quarta_Editada__c.field-meta.xml
<CustomField>
    <fullName>Cl_usula_Quarta_Editada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cláusula Quarta Editada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Cl_usula_Quinta_Editada__c.field-meta.xml
<CustomField>
    <fullName>Cl_usula_Quinta_Editada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cláusula Quinta Editada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Cl_usula_S_tima_Editada__c.field-meta.xml
<CustomField>
    <fullName>Cl_usula_S_tima_Editada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cláusula Sétima Editada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Cl_usula_Segunda_Editada__c.field-meta.xml
<CustomField>
    <fullName>Cl_usula_Segunda_Editada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cláusula Segunda Editada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Cl_usula_Sexta_Editada__c.field-meta.xml
<CustomField>
    <fullName>Cl_usula_Sexta_Editada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cláusula Sexta Editada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Cl_usula_Terceira_Editada__c.field-meta.xml
<CustomField>
    <fullName>Cl_usula_Terceira_Editada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cláusula Terceira Editada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contratos de Locação</relationshipLabel>
    <relationshipName>Contratos_de_Servi_os</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Contrato_de_AltoFluxo__c.field-meta.xml
<CustomField>
    <fullName>Contrato_de_AltoFluxo__c</fullName>
    <label>Contrato de AltoFluxo?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SIM</fullName>
            </value>
            <value>
                <fullName>NÃO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Internado_no_Hospital__c.field-meta.xml
<CustomField>
    <fullName>Internado_no_Hospital__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Este campo deve ser preenchido apenas quando o campo Contrato de Alto Fluxo for igual a &quot;SIM&quot;.</inlineHelpText>
    <label>Internado no Hospital</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contratos de Serviços (Internado no Hospital)</relationshipLabel>
    <relationshipName>Contratos_de_Servi_os3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Locador_a__c.field-meta.xml
<CustomField>
    <fullName>Locador_a__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Locador(a)/Contratada</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contratos de Serviços (Locador(a))</relationshipLabel>
    <relationshipName>Contratos_de_Servi_os1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Locat_rio_a__c.field-meta.xml
<CustomField>
    <fullName>Locat_rio_a__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Locatário(a)/Contratante</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contratos de Locação</relationshipLabel>
    <relationshipName>Contratos_de_Servi_os2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestedeContratoLocacao.cls
@isTest(seeAllData=true)
private class TestedeContratoLocacao {
    
    // Teste de classes
    @isTest private static void Teste2(){
        Contrato_de_Servi_o__c testecontrato2 = new Contrato_de_Servi_o__c(
            Locador_a__c = '0015A00001yGbVZQA0', 
            Locat_rio_a__c = '0015A00001yGbVZQA0', 
            Cliente__c = '0015A00001yGbVZQA0',
            Internado_no_Hospital__c = '0015A00001yGbVZQA0',
            RecordTypeId = '0126e000001YbJL',                                //Teste:0127i000001xkgy Prod: 0126e000001YbJL
            Cl_usula_Primeira_Editada__c = false,
            Cl_usula_Segunda_Editada__c = false,
            Cl_usula_Terceira_Editada__c = false,
            Cl_usula_Quarta_Editada__c = false,
            Cl_usula_Quinta_Editada__c = false,
            Cl_usula_Sexta_Editada__c = false,
            Cl_usula_S_tima_Editada__c = false,
            Cl_usula_Oitava_Editada__c = false,
            Cl_usula_Nona_Editada__c = false,
            Cl_usula_D_cima_Editada__c = false,
            Cl_usula_D_cima_Primeira_Editada__c = false
      
        );
        insert testecontrato2;       
    } 
    @isTest private static void Teste1(){
        Contrato_de_Servi_o__c testecontrato = new Contrato_de_Servi_o__c(
            Locador_a__c = '0015A00001yGbVZQA0', 
            Locat_rio_a__c = '0015A00001yGbVZQA0', 
            Cliente__c = '0015A00001yGbVZQA0',
            Internado_no_Hospital__c = '0015A00001yGbVZQA0',
            RecordTypeId = '0125A000001Qydf',
            Cl_usula_Primeira_Editada__c = false,
            Cl_usula_Segunda_Editada__c = false,
            Cl_usula_Terceira_Editada__c = false,
            Cl_usula_Quarta_Editada__c = false,
            Cl_usula_Quinta_Editada__c = false,
            Cl_usula_Sexta_Editada__c = false,
            Cl_usula_S_tima_Editada__c = false,
            Cl_usula_Oitava_Editada__c = false,
            Cl_usula_Nona_Editada__c = false,
            Cl_usula_D_cima_Editada__c = false,
            Cl_usula_D_cima_Primeira_Editada__c = false,
            Contrato_de_AltoFluxo__c = 'SIM'
      
        );
        insert testecontrato;       
    }
    @isTest private static void Teste3(){
        Contrato_de_Servi_o__c testecontrato3 = new Contrato_de_Servi_o__c(
            Locador_a__c = '0015A00001yGbVZQA0', 
            Locat_rio_a__c = '0015A00001yGbVZQA0', 
            Cliente__c = '0015A00001yGbVZQA0',
            Internado_no_Hospital__c = '0015A00001yGbVZQA0',
            RecordTypeId = '0125A000001Qydf',
            Cl_usula_Primeira_Editada__c = false,
            Cl_usula_Segunda_Editada__c = false,
            Cl_usula_Terceira_Editada__c = false,
            Cl_usula_Quarta_Editada__c = false,
            Cl_usula_Quinta_Editada__c = false,
            Cl_usula_Sexta_Editada__c = false,
            Cl_usula_S_tima_Editada__c = false,
            Cl_usula_Oitava_Editada__c = false,
            Cl_usula_Nona_Editada__c = false,
            Cl_usula_D_cima_Editada__c = false,
            Cl_usula_D_cima_Primeira_Editada__c = false,
            Contrato_de_AltoFluxo__c = 'NÃO'
      
        );
        insert testecontrato3;       
    } 
    
    
}