force-app/main/default/objects/Recebimentos__c/Recebimentos__c.object-meta.xml
<CustomObject>
    <label>Recebimento</label>
    <nameField>
        <label>Número do Recebimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recebimentos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Recebimentos__c/fields/Numero_Faturamento__c.field-meta.xml
<CustomField>
    <fullName>Numero_Faturamento__c</fullName>
    <label>Numero Faturamento</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recebimentos__c/fields/Numero_Pedido__c.field-meta.xml
<CustomField>
    <fullName>Numero_Pedido__c</fullName>
    <label>Numero Pedido</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recebimentos__c/fields/Titulo_SAP__c.field-meta.xml
<CustomField>
    <fullName>Titulo_SAP__c</fullName>
    <label>N. Titulo SAP</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recebimentos__c/fields/Vendedor_do_recebimento__c.field-meta.xml
<CustomField>
    <fullName>Vendedor_do_recebimento__c</fullName>
    <label>Vendedor do recebimento</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RecebimentoPreencheVinculosTest.cls
@isTest(seeAllData=true)
public class RecebimentoPreencheVinculosTest {

    @isTest
    static void testRecebimentoPreencheVinculos() {
        // Criar registros de Recebimentos__c
        Recebimentos__c recebimento1 = new Recebimentos__c(
            Name = '12344',
            Numero_Pedido__c = '00015553',
            Numero_Faturamento__c = ''
        );

        
       insert recebimento1;
    }
    
    @isTest
    static void testRecebimentoPreencheVinculos2() {
        // Criar registros de Recebimentos__c
        Recebimentos__c recebimento1 = new Recebimentos__c(
            Name = '12344',
            Numero_Pedido__c = '00015553',
            Numero_Faturamento__c = '26040',
            Titulo_SAP__c = '1054',
            Vendedor_do_recebimento__c = 'Karlla Roberta Cunha Barbosa'
        );

        
       insert recebimento1;
        
        recebimento1.Vendedor_do_recebimento__c = 'Tatiane Oliveira';
        update recebimento1;
    }
}