force-app/main/default/objects/Recebimentos__c/Recebimentos__c.object-meta.xml
<CustomObject>
    <label>Recebimento</label>
    <nameField>
        <label>Número do Recebimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recebimentos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Recebimentos__c/fields/Data_do_Recebimento__c.field-meta.xml
<CustomField>
    <fullName>Data_do_Recebimento__c</fullName>
    <label>Data do Recebimento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Recebimentos__c/fields/NF_Representacao__c.field-meta.xml
<CustomField>
    <fullName>NF_Representacao__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>NF de referência utilizada para cobrança de comissões.</inlineHelpText>
    <label>NF Representaçao</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <filterItems>
            <field>Faturamento__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Representação</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Parceiro</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Faturamento__c</referenceTo>
    <relationshipLabel>Recebimentos das NFs de Fabricantes</relationshipLabel>
    <relationshipName>NF_Representacao</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recebimentos__c/fields/Nota_Fiscal1__c.field-meta.xml
<CustomField>
    <fullName>Nota_Fiscal1__c</fullName>
    <label>Número do Faturamento</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(3 AND 6) OR (4 AND 6) OR (1 AND 6) OR (5 AND 7) OR (2 AND 6)</booleanFilter>
        <filterItems>
            <field>Faturamento__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Serviços (Mão de Obra)</value>
        </filterItems>
        <filterItems>
            <field>Faturamento__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vendas (Hospcom)</value>
        </filterItems>
        <filterItems>
            <field>Faturamento__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Representação</value>
        </filterItems>
        <filterItems>
            <field>Faturamento__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Serviços (Fábrica)</value>
        </filterItems>
        <filterItems>
            <field>Faturamento__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vendas (Fábrica)</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Hospcom</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Parceiro</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Faturamento__c</referenceTo>
    <relationshipLabel>Recebimentos</relationshipLabel>
    <relationshipName>Recebimentos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Recebimentos__c/fields/Valor_Acrescimo__c.field-meta.xml
<CustomField>
    <fullName>Valor_Acrescimo__c</fullName>
    <label>Valor Acréscimo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Recebimentos__c/fields/Valor_Comissao__c.field-meta.xml
<CustomField>
    <fullName>Valor_Comissao__c</fullName>
    <label>Valor Comissão</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Recebimentos__c/fields/Valor_Desconto__c.field-meta.xml
<CustomField>
    <fullName>Valor_Desconto__c</fullName>
    <label>Valor Desconto</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Recebimentos__c/fields/Valor_Recebido__c.field-meta.xml
<CustomField>
    <fullName>Valor_Recebido__c</fullName>
    <label>Valor Recebido</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/RecebimentoTeste.cls
@isTest(seeAllData=true)
private class RecebimentoTeste {
	   
    @isTest static void Teste1(){ 
		Recebimentos__c recebimento = new Recebimentos__c(
			NF_Representacao__c	 = 'a085A00001lcyqO', // prod:a085A00001lcyqO test:a085A00001lcXyS
			Nota_Fiscal1__c = 'a085A00001lcyqT', 	  // prod:a085A00001lcyqT test:a085A00001lcXyh
			Data_do_Recebimento__c = System.Today(),
			Valor_Recebido__c = 100,
			Valor_Desconto__c = 0,
			Valor_Acrescimo__c = 0,
			Valor_Comissao__c = 10,
			RecordTypeId = '0125A000001YZgJQAW'
		);
		insert recebimento;
		
		recebimento.NF_Representacao__c = 'a085A00001lcXyS'; // xxx prod:a085A00001lcXyS test:a081g000001jPpw
		update recebimento;

		delete recebimento;
    }
	
    @isTest static void Teste2(){ 
		Recebimentos__c recebimento = new Recebimentos__c(
			//NF_Representacao__c	 = 'a085A00001lcyqO', // prod:a085A00001lcyqO test:a085A00001lcXyS
			Nota_Fiscal1__c = 'a085A00001lcyqT', 	  // prod:a085A00001lcyqT test:a085A00001lcXyh
			Data_do_Recebimento__c = System.Today(),
			Valor_Recebido__c = 100,
			Valor_Desconto__c = 0,
			Valor_Acrescimo__c = 0,
			Valor_Comissao__c = 10,
			RecordTypeId = '0125A000001YZgJQAW'
		);
		insert recebimento;
		
		recebimento.NF_Representacao__c = 'a085A00001lcXyS'; // xxx prod:a085A00001lcXyS test:a081g000001jPpw
		update recebimento;

		delete recebimento;
    }
	
    @isTest static void Teste3(){ 
		Recebimentos__c recebimento = new Recebimentos__c(
			NF_Representacao__c	 = 'a085A00001lcyqO', // prod:a085A00001lcyqO test:a085A00001lcXyS
			Nota_Fiscal1__c = 'a085A00001lcyqT', 	  // prod:a085A00001lcyqT test:a085A00001lcXyh
			Data_do_Recebimento__c = System.Today(),
			Valor_Recebido__c = 100,
			Valor_Desconto__c = 0,
			Valor_Acrescimo__c = 0,
			Valor_Comissao__c = 10,
			RecordTypeId = '0125A000001YZgJQAW'
		);
		insert recebimento;
		
		recebimento.NF_Representacao__c = null; // xxx prod:a085A00001lcXyS test:a081g000001jPpw
		update recebimento;

		delete recebimento;
    }
	
    @isTest static void Teste4(){ 
		Recebimentos__c recebimento = new Recebimentos__c(
			NF_Representacao__c	 = 'a085A00001lcyqO', // prod:a085A00001lcyqO test:a085A00001lcXyS
			Nota_Fiscal1__c = 'a085A00001lcyqT', 	  // prod:a085A00001lcyqT test:a085A00001lcXyh
			Data_do_Recebimento__c = System.Today(),
			Valor_Recebido__c = 100,
			Valor_Desconto__c = 0,
			Valor_Acrescimo__c = 0,
			Valor_Comissao__c = 10,
			RecordTypeId = '0125A000001YZgJQAW'
		);
		insert recebimento;
		
		recebimento.Valor_Recebido__c = 200;
		update recebimento;

		delete recebimento;
    }
	
    @isTest static void Teste5(){ 
		Recebimentos__c recebimento = new Recebimentos__c(
			NF_Representacao__c	 = 'a085A00001lcyqO', // prod:a085A00001lcyqO test:a085A00001lcXyS
			Nota_Fiscal1__c = 'a085A00001lcyqT', 	  // prod:a085A00001lcyqT test:a085A00001lcXyh
			Data_do_Recebimento__c = System.Today(),
			Valor_Recebido__c = 100,
			Valor_Desconto__c = 0,
			Valor_Acrescimo__c = 0,
			Valor_Comissao__c = 10,
			RecordTypeId = '0125A000001YZgJQAW'
		);
		insert recebimento;
		
		recebimento.Valor_Comissao__c = 50;
		update recebimento;

		delete recebimento;
    }
	
}