force-app/main/default/objects/Contrato_de_compra__c/Contrato_de_compra__c.object-meta.xml
<CustomObject>
    <label>Contrato de Compra</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Nº de Contrato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contratos de Compra</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Nota_buscada__c/Nota_buscada__c.object-meta.xml
<CustomObject>
    <label>Nota recebida</label>
    <nameField>
        <label>Nº da Nota</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notas recebidas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Nota_buscada__c/fields/Data_de_vencimento__c.field-meta.xml
<CustomField>
    <fullName>Data_de_vencimento__c</fullName>
    <label>Data de vencimento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Nota_buscada__c/fields/Lancada__c.field-meta.xml
<CustomField>
    <fullName>Lancada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lançada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Nota_buscada__c/fields/Link_PDF__c.field-meta.xml
<CustomField>
    <fullName>Link_PDF__c</fullName>
    <label>Link PDF</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Nota_buscada__c/fields/Natureza_de_Operacao__c.field-meta.xml
<CustomField>
    <fullName>Natureza_de_Operacao__c</fullName>
    <label>Natureza de Operação</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Nota_buscada__c/fields/Valor_da_nota__c.field-meta.xml
<CustomField>
    <fullName>Valor_da_nota__c</fullName>
    <label>Valor da nota</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Nota_buscada__c/fields/XML__c.field-meta.xml
<CustomField>
    <fullName>XML__c</fullName>
    <label>XML</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Nota_fiscal_de_compra__c/Nota_fiscal_de_compra__c.object-meta.xml
<CustomObject>
    <label>Nota fiscal de contrato de compra</label>
    <nameField>
        <label>Nº da Nota</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notas fiscais de contrato de compra</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Nota_fiscal_de_compra__c/fields/Chave_de_Acesso__c.field-meta.xml
<CustomField>
    <fullName>Chave_de_Acesso__c</fullName>
    <label>Chave de Acesso</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Nota_fiscal_de_compra__c/fields/Contrato_de_compra__c.field-meta.xml
<CustomField>
    <fullName>Contrato_de_compra__c</fullName>
    <label>Contrato de compra</label>
    <referenceTo>Contrato_de_compra__c</referenceTo>
    <relationshipName>Notas_fiscais_do_contrato</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Nota_fiscal_de_compra__c/fields/Data_de_emissao__c.field-meta.xml
<CustomField>
    <fullName>Data_de_emissao__c</fullName>
    <label>Data de emissão</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Nota_fiscal_de_compra__c/fields/Data_de_vencimento__c.field-meta.xml
<CustomField>
    <fullName>Data_de_vencimento__c</fullName>
    <label>Vencimento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Nota_fiscal_de_compra__c/fields/URL_Anexo__c.field-meta.xml
<CustomField>
    <fullName>URL_Anexo__c</fullName>
    <label>URL Anexo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Nota_fiscal_de_compra__c/fields/Valor_da_nota_fiscal__c.field-meta.xml
<CustomField>
    <fullName>Valor_da_nota_fiscal__c</fullName>
    <label>Valor da nota fiscal</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Nota_fiscal_de_pedido_de_compra__c/Nota_fiscal_de_pedido_de_compra__c.object-meta.xml
<CustomObject>
    <label>Nota fiscal de pedido de compra</label>
    <nameField>
        <label>Nº da Nota Fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notas fiscais de pedido de compra</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Nota_fiscal_de_pedido_de_compra__c/fields/Contrato_de_Compra__c.field-meta.xml
<CustomField>
    <fullName>Contrato_de_Compra__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Será vinculado automaticamente caso o pedido de compra esteja vinculado a um contrato.</inlineHelpText>
    <label>Contrato de Compra</label>
    <referenceTo>Contrato_de_compra__c</referenceTo>
    <relationshipName>Notas_fiscais_de_compra</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Nota_fiscal_de_pedido_de_compra__c/fields/Data_de_emissao__c.field-meta.xml
<CustomField>
    <fullName>Data_de_emissao__c</fullName>
    <label>Data de emissão</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Nota_fiscal_de_pedido_de_compra__c/fields/Lancada__c.field-meta.xml
<CustomField>
    <fullName>Lancada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lançada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Nota_fiscal_de_pedido_de_compra__c/fields/Pedido_de_Compra__c.field-meta.xml
<CustomField>
    <fullName>Pedido_de_Compra__c</fullName>
    <label>Pedido de Compra</label>
    <referenceTo>Fornecedor__c</referenceTo>
    <relationshipName>Notas_fiscais_de_compra</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Nota_fiscal_de_pedido_de_compra__c/fields/URL_Anexo__c.field-meta.xml
<CustomField>
    <fullName>URL_Anexo__c</fullName>
    <label>URL Anexo</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Nota_fiscal_de_pedido_de_compra__c/fields/Valor_da_nota__c.field-meta.xml
<CustomField>
    <fullName>Valor_da_nota__c</fullName>
    <label>Valor da nota</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Pedido_de_compra__c/Pedido_de_compra__c.object-meta.xml
<CustomObject>
    <label>Cotação de compra</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número da cotação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cotações de compra</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/XMLtoPDF.cls
public class XMLtoPDF {
    @AuraEnabled
    public static String salvaDANFE(string idNota) {
        
        Nota_buscada__c nota = [SELECT ID, XML__c, Natureza_de_operacao__c FROM Nota_buscada__c WHERE ID =: idNota];
        
        string xml = nota.XML__c;
        
        if(nota.Natureza_de_Operacao__c != 'Serviço'){
            
            // Realiza a chamada para a API que retorna o PDF em base64
            HttpRequest req = new HttpRequest();
            req.setEndpoint('https://ws.meudanfe.com/api/v1/get/nfe/xmltodanfepdf/API'); 
            req.setHeader('Content-Type','text/plain'); 
            req.setBody(xml);
            req.setMethod('POST');
            
            Http http = new Http();
            HttpResponse res = http.send(req);
            
            if (res.getStatusCode() == 200) {
                // Limpa a string base64 de possíveis caracteres inválidos
                String base64Pdf = res.getBody().replace('"', '').replace('\n', '').replace('\r', '');
                
                // Decodifica o base64 em um blob
                Blob pdfBlob = EncodingUtil.base64Decode(base64Pdf);
                
                // Cria um novo documento no Salesforce
                Document doc = new Document();
                doc.Name = 'Arquivo PDF NF ' + xml.substringAfter('<nNF>').substringBefore('</nNF>');
                doc.Body = pdfBlob;
                doc.FolderId = '00lU4000007jOzr'; // Salva na pasta
                doc.IsPublic = true; // Deixe público para gerar o link
                doc.ContentType = 'application/pdf';
                insert doc;
                
                
                // Construindo a URL do documento manualmente
                String baseUrl = 'https://' + System.Url.getOrgDomainUrl().getHost();
                String documentUrl = baseUrl + '/servlet/servlet.FileDownload?file=' + doc.Id;
                system.debug('URL: ' + documentUrl);
                nota.Link_PDF__c =  documentUrl;
                update nota;            
                return documentUrl;
                
                
            } else {
                throw new CalloutException('Erro ao buscar o PDF: ' + res.getStatus());
            }
        }
        else{
            string base64Convertido = gerarPDFBase64(xml);
            String base64Pdf = base64Convertido.replace('"', '').replace('\n', '').replace('\r', '');
            
            // Decodifica o base64 em um blob
            Blob pdfBlob = EncodingUtil.base64Decode(base64Pdf);
            // Cria um novo documento no Salesforce
            Document doc = new Document();
            doc.Name = 'Arquivo PDF NFS ' + xml.substringAfter('<Numero>').substringBefore('</Numero>');
            doc.Body = pdfBlob;
            doc.FolderId = '00lU4000007jOzr'; // Salva na pasta
            doc.IsPublic = true; // Deixe público para gerar o link
            doc.ContentType = 'application/pdf';
            insert doc;
            
            // Construindo a URL do documento manualmente
            String baseUrl = 'https://' + System.Url.getOrgDomainUrl().getHost();
            String documentUrl = baseUrl + '/servlet/servlet.FileDownload?file=' + doc.Id;
            system.debug('URL: ' + documentUrl);
            nota.Link_PDF__c =  documentUrl;
            update nota;            
            return documentUrl;
        }
    }
    @AuraEnabled
    public static void lancaNota(string idNota, string idPedido){
        
        Nota_buscada__c nota = [SELECT ID, Name, Chave_de_Acesso__c, Data_de_emissao__c, Valor_da_nota__c, Link_PDF__c, Data_de_vencimento__c FROM Nota_buscada__c WHERE ID =: idNota];
        
        Nota_fiscal_de_pedido_de_compra__c nfpc = new Nota_fiscal_de_pedido_de_compra__c();
        
        nfpc.Name = nota.Name;
        nfpc.Chave_de_Acesso__c = nota.Chave_de_Acesso__c;
        nfpc.Data_de_emissao__c = nota.Data_de_emissao__c;
        nfpc.Data_de_vencimento__c = nota.Data_de_vencimento__c;
        nfpc.Valor_da_nota__c = nota.Valor_da_nota__c;
        nfpc.Pedido_de_Compra__c = idPedido;
        nfpc.URL_Anexo__c = nota.Link_PDF__c;
        
        nota.Lancada__c = true;
        
        try{
            insert nfpc;
            update nota;
        }
        catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled
    public static void lancaNotaContrato(string idNota, string idContrato){
        
        Nota_buscada__c nota = [SELECT ID, Name, Chave_de_Acesso__c, Data_de_emissao__c, Valor_da_nota__c, Link_PDF__c, Data_de_vencimento__c FROM Nota_buscada__c WHERE ID =: idNota];
        
        Nota_fiscal_de_compra__c nfpc = new Nota_fiscal_de_compra__c();
        
        nfpc.Name = nota.Name;
        nfpc.Chave_de_Acesso__c = nota.Chave_de_Acesso__c;
        nfpc.Data_de_emissao__c = nota.Data_de_emissao__c;
        nfpc.Data_de_vencimento__c = nota.Data_de_vencimento__c;
        nfpc.Valor_da_nota_fiscal__c = nota.Valor_da_nota__c;
        nfpc.Contrato_de_compra__c = idContrato;
        nfpc.URL_Anexo__c = nota.Link_PDF__c;
        
        nota.Lancada__c = true;
        
        try{
            insert nfpc;
            update nota;
        }
        catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }
    public static String gerarPDFBase64(String xmlString) {
        
        
        
        String nomePrestador = xmlString.substringAfter('</IdentificacaoPrestador><RazaoSocial>').substringBefore('</RazaoSocial>');
        String cnpjPrestador = xmlString.substringAfter('<IdentificacaoPrestador><CpfCnpj><Cnpj>').substringBefore('</Cnpj>');
        String cnpjPrestadorFormat =  cnpjPrestador.substring(0, 2) + '.' +
            cnpjPrestador.substring(2, 5) + '.' +
            cnpjPrestador.substring(5, 8) + '/' +
            cnpjPrestador.substring(8, 12) + '-' +
            cnpjPrestador.substring(12, 14);
        String enderecoPrestador =  xmlString.substringAfter('<Cep>').substringBefore('</Cep>')  + '/' + xmlString.substringAfter('<Uf>').substringBefore('</Uf>');
        String nomeTomador = xmlString.substringAfter('</IdentificacaoTomador><RazaoSocial>').substringBefore('</RazaoSocial>');
        String cnpjTomador = xmlString.substringAfter('<IdentificacaoTomador><CpfCnpj><Cnpj>').substringBefore('</Cnpj>');
        String cnpjTomadorFormat =  cnpjTomador.substring(0, 2) + '.' +
            cnpjTomador.substring(2, 5) + '.' +
            cnpjTomador.substring(5, 8) + '/' +
            cnpjTomador.substring(8, 12) + '-' +
            cnpjTomador.substring(12, 14);
        String enderecoTomador = '';
        String servico = xmlString.substringAfter('<Discriminacao>').substringBefore('</Discriminacao>');
        String valor = xmlString.substringAfter('<ValorServicos>').substringBefore('</ValorServicos>');
        String nNFSe = xmlString.substringAfter('<Numero>').substringBefore('</Numero>');
        String dataEmissao = xmlString.substringAfter('<DataEmissao>').substringBefore('</DataEmissao>');
        String codigoVerificacao = xmlString.substringAfter('<CodigoVerificacao>').substringBefore('</CodigoVerificacao>');
        
        
        Datetime dt = Date.valueOf(dataEmissao.substringBefore('T'));
        
        // Extrair a data no formato DD/MM/AAAA
        String formattedDate = dt.format('dd/MM/yyyy');
        
        
        // Passando os valores para a página Visualforce
        PageReference pdfPage = Page.GerarPDFXML;
        pdfPage.getParameters().put('prestador', nomePrestador);
        pdfPage.getParameters().put('cnpjPrestador', cnpjPrestadorFormat);
        pdfPage.getParameters().put('enderecoPrestador', enderecoPrestador);
        pdfPage.getParameters().put('tomador', nomeTomador);
        pdfPage.getParameters().put('cnpjTomador', cnpjTomadorFormat);
        pdfPage.getParameters().put('enderecoTomador', enderecoTomador);
        pdfPage.getParameters().put('servico', servico);
        pdfPage.getParameters().put('valor', valor);
        pdfPage.getParameters().put('nNFSe', nNFSe);
        pdfPage.getParameters().put('dataEmissao', formattedDate);
        pdfPage.getParameters().put('codigoVerificacao', codigoVerificacao);
        
        // Geração do PDF
        Blob pdfBlob;
        
        if(!test.isRunningTest()){
           pdfBlob = pdfPage.getContentAsPDF();
        }
        else{
            pdfBlob = Blob.valueOf('Teste');
        }
        
        // Conversão para Base64
        String base64String = EncodingUtil.base64Encode(pdfBlob);
        
        system.debug(base64String);
        return base64String;
    }
}