force-app/main/default/objects/User/fields/Variacao__c.field-meta.xml
<CustomField>
    <fullName>Variacao__c</fullName>
    <label>Variação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Variacoes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Variacoes__c.field-meta.xml
<CustomField>
    <fullName>Variacoes__c</fullName>
    <label>Variações</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Variacoes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Variacoes.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Camas Hospitalares - Analytics</fullName>
    </customValue>
    <customValue>
        <fullName>Camas Hospitalares - Base Instalada</fullName>
    </customValue>
    <customValue>
        <fullName>Camas Hospitalares - Forecast</fullName>
    </customValue>
    <customValue>
        <fullName>Camas Hospitalares - Performance Geral</fullName>
    </customValue>
    <customValue>
        <fullName>Camas Hospitalares - Qualidade</fullName>
    </customValue>
    <customValue>
        <fullName>Camas Hospitalares - Vendedores</fullName>
    </customValue>
    <customValue>
        <fullName>CMI - Analytics</fullName>
    </customValue>
    <customValue>
        <fullName>CMI - Base Instalada</fullName>
    </customValue>
    <customValue>
        <fullName>CMI - Demonstrações</fullName>
    </customValue>
    <customValue>
        <fullName>CMI - Forecast</fullName>
    </customValue>
    <customValue>
        <fullName>CMI - Performance Geral</fullName>
    </customValue>
    <customValue>
        <fullName>CMI - Qualidade</fullName>
    </customValue>
    <customValue>
        <fullName>CMI - Vendedores</fullName>
    </customValue>
    <customValue>
        <fullName>Comercial - Demo Rápida</fullName>
    </customValue>
    <customValue>
        <fullName>Comercial - Meta Vendedores</fullName>
    </customValue>
    <customValue>
        <fullName>Comercial - Performance</fullName>
    </customValue>
    <customValue>
        <fullName>Comercial - Qualidade</fullName>
    </customValue>
    <customValue>
        <fullName>Comercial - Representação</fullName>
    </customValue>
    <customValue>
        <fullName>Comercial - São Paulo - Geral</fullName>
    </customValue>
    <customValue>
        <fullName>Compras - Consumo - Performance</fullName>
    </customValue>
    <customValue>
        <fullName>Compras - Consumo - Qualidade</fullName>
    </customValue>
    <customValue>
        <fullName>Compras - Contratos</fullName>
    </customValue>
    <customValue>
        <fullName>Compras - KPIs</fullName>
    </customValue>
    <customValue>
        <fullName>Compras - Novos relatórios</fullName>
    </customValue>
    <customValue>
        <fullName>Compras - OPME</fullName>
    </customValue>
    <customValue>
        <fullName>Compras - Revenda - Performance</fullName>
    </customValue>
    <customValue>
        <fullName>Compras - Revenda - Qualidade</fullName>
    </customValue>
    <customValue>
        <fullName>Desenvolvimento</fullName>
    </customValue>
    <customValue>
        <fullName>Diretoria - Clientes</fullName>
    </customValue>
    <customValue>
        <fullName>Diretoria - Comercial</fullName>
    </customValue>
    <masterLabel>Variações</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/HomeBotoes.cls
public with sharing class HomeBotoes {
    
    @AuraEnabled
    public static String PrepararPainel(){
		ValoresPrepararPainel valores = new ValoresPrepararPainel();

		User usuario = [SELECT Variacoes__c, Variacao__c FROM User WHERE Id = :UserInfo.GetUserId()];
		valores.paineis = usuario.Variacoes__c.split('\\;');
		valores.painel = usuario.Variacao__c;
		
		return JSON.serialize(valores);
	}public class ValoresPrepararPainel{
		List<String> paineis;
		String painel;

		public ValoresPrepararPainel(){}
	}
	
	@AuraEnabled
	public static String AlterarPainel(String config){
		RetornoAlterarPainel retorno = new RetornoAlterarPainel();
		
		User usuario = [SELECT Variacao__c FROM User WHERE Id = :UserInfo.GetUserId()];
		
		Savepoint checkpoint = Database.setSavepoint();
		usuario.Variacao__c = config;
		try {
			update usuario;
		}
		catch (System.DMLException e){
			for(Integer i=0; i<e.getNumDml(); i++)
				retorno.mensagem += e.getDmlMessage(i);
			Database.rollback(checkpoint);
			return JSON.serialize(retorno);
		}
		
		return JSON.serialize(retorno);
	}public class RetornoAlterarPainel{
		String mensagem;
		
		public RetornoAlterarPainel(){
			mensagem = '';
		}
	}
}