force-app/main/default/objects/WorkOrderLineItem/fields/C_digo_do_Produto__c.field-meta.xml
<CustomField>
    <fullName>C_digo_do_Produto__c</fullName>
    <formula>Product2.ProductCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Código fabricante</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Imagem__c.field-meta.xml
<CustomField>
    <fullName>Imagem__c</fullName>
    <formula>Product2.Imagem_do_Produto__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Imagem</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Nome_do_produto__c.field-meta.xml
<CustomField>
    <fullName>Nome_do_produto__c</fullName>
    <formula>Product2.Name</formula>
    <label>Nome do produto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrderLineItem/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Itens de linha da ordem de trabalho</relationshipLabel>
    <relationshipName>Itens_de_linha_da_ordem_de_trabalho</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ItensLinhaOT_Relacionamento.cls
public class ItensLinhaOT_Relacionamento {

    public static List<WorkOrderLineItem> itens(String idOt){
        
        List<WorkOrderLineItem> itensList = [SELECT ID,  Produto__c, LineItemNumber,  Nome_do_produto__c, Imagem__c, C_digo_do_Produto__c
                                            FROM WorkOrderLineItem
                                            WHERE WorkOrderId =:  idOt
                                            
                                            ];
        

        return itensList; 
        
    }
}