force-app/main/default/objects/Faturamento__c/Faturamento__c.object-meta.xml
<CustomObject>
    <label>Faturamento</label>
    <nameField>
        <label>Número</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Faturamentos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Faturamento__c/fields/Faturamento_Feito2__c.field-meta.xml
<CustomField>
    <fullName>Faturamento_Feito2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Faturamento feito</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Faturamento (Faturamento Feito)</relationshipLabel>
    <relationshipName>Faturamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Faturamento__c/fields/Nome_da_Conta2__c.field-meta.xml
<CustomField>
    <fullName>Nome_da_Conta2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Nome da conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Faturamentos</relationshipLabel>
    <relationshipName>Faturas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Faturamento__c/fields/Procedencia__c.field-meta.xml
<CustomField>
    <fullName>Procedencia__c</fullName>
    <label>Procedência (automático)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Contrato de Serviço</fullName>
            </value>
            <value>
                <fullName>Contrato de Locação</fullName>
            </value>
            <value>
                <fullName>Serviço Avulso (Contrato de Serviço)</fullName>
            </value>
            <value>
                <fullName>Serviço Avulso (Contrato de Locação)</fullName>
            </value>
            <value>
                <fullName>Serviço Avulso</fullName>
            </value>
            <value>
                <fullName>Comercial</fullName>
            </value>
            <value>
                <fullName>Governo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recebimentos__c/Recebimentos__c.object-meta.xml
<CustomObject>
    <label>Recebimento</label>
    <nameField>
        <label>Número do Recebimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recebimentos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Recebimentos__c/fields/Data_do_Recebimento__c.field-meta.xml
<CustomField>
    <fullName>Data_do_Recebimento__c</fullName>
    <label>Data do Recebimento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Recebimentos__c/fields/NF_Representacao__c.field-meta.xml
<CustomField>
    <fullName>NF_Representacao__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>NF de referência utilizada para cobrança de comissões.</inlineHelpText>
    <label>NF Representaçao</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <filterItems>
            <field>Faturamento__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Representação</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Parceiro</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Faturamento__c</referenceTo>
    <relationshipLabel>Recebimentos das NFs de Fabricantes</relationshipLabel>
    <relationshipName>NF_Representacao</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recebimentos__c/fields/Nota_Fiscal1__c.field-meta.xml
<CustomField>
    <fullName>Nota_Fiscal1__c</fullName>
    <label>Número do Faturamento</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(3 AND 6) OR (4 AND 6) OR (1 AND 6) OR (5 AND 7) OR (2 AND 6)</booleanFilter>
        <filterItems>
            <field>Faturamento__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Serviços (Mão de Obra)</value>
        </filterItems>
        <filterItems>
            <field>Faturamento__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vendas (Hospcom)</value>
        </filterItems>
        <filterItems>
            <field>Faturamento__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Representação</value>
        </filterItems>
        <filterItems>
            <field>Faturamento__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Serviços (Fábrica)</value>
        </filterItems>
        <filterItems>
            <field>Faturamento__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Vendas (Fábrica)</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Hospcom</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>equals</operation>
            <value>Parceiro</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Faturamento__c</referenceTo>
    <relationshipLabel>Recebimentos</relationshipLabel>
    <relationshipName>Recebimentos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Recebimentos__c/fields/Procedencia__c.field-meta.xml
<CustomField>
    <fullName>Procedencia__c</fullName>
    <formula>TEXT(Nota_Fiscal1__r.Procedencia__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Procedência v1</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recebimentos__c/fields/Valor_Acrescimo__c.field-meta.xml
<CustomField>
    <fullName>Valor_Acrescimo__c</fullName>
    <label>Valor Acréscimo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Recebimentos__c/fields/Valor_Desconto__c.field-meta.xml
<CustomField>
    <fullName>Valor_Desconto__c</fullName>
    <label>Valor Desconto</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Recebimentos__c/fields/Valor_Recebido__c.field-meta.xml
<CustomField>
    <fullName>Valor_Recebido__c</fullName>
    <label>Valor Recebido</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Recebimentos__c/fields/Valor_Total__c.field-meta.xml
<CustomField>
    <fullName>Valor_Total__c</fullName>
    <formula>Valor_Recebido__c +  Valor_Desconto__c +  Valor_Acrescimo__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valor Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Recebimentos__c/recordTypes/Parceiro.recordType-meta.xml
<RecordType>
    <fullName>Parceiro</fullName>
    <active>true</active>
    <description>Recebimentos sobre NFs de parceiros.</description>
    <label>Parceiro</label>
</RecordType>

force-app/main/default/classes/FaturamentoAdicionarRecebimento.cls
public class FaturamentoAdicionarRecebimento {

	public List<cRecebimento> 	c_recebimentos {get; set;}
	public Integer 				qtd_recebimentos {get;set;}
	public String 				pesquisa {get; set;}
	public String 				mensagem {get; set;}
	public Id 					filtro_conta_id, faturamento_id;

	public FaturamentoAdicionarRecebimento(ApexPages.StandardController controller) {
		c_recebimentos = new List<cRecebimento>();
		pesquisa = '';
		mensagem = '';
		faturamento_id = ((SObject)controller.getRecord()).Id;
		filtro_conta_id = ObtemFaturamento(faturamento_id);
		
		Pesquisar();
	}
	
	public Id ObtemFaturamento(Id faturamento_id){
		return [
			SELECT 	Nome_da_Conta2__c
			FROM	Faturamento__c
			WHERE	Id = :faturamento_id
		][0].Nome_da_Conta2__c;		
	}
	
	public void Pesquisar(){
		List<Recebimentos__c> recebimentos = new List<Recebimentos__c>();
        String pesquisa_sql = '%'+pesquisa+'%';
		recebimentos = [
			SELECT 	Id, Name, Data_do_Recebimento__c, Valor_Recebido__c, Valor_Desconto__c, Valor_Acrescimo__c, Valor_Total__c, RecordType.Name, Procedencia__c,
					Nota_Fiscal1__r.Name, Nota_Fiscal1__r.Faturamento_Feito2__r.Name, Nota_Fiscal1__r.Nome_da_Conta2__r.Name
			FROM  	Recebimentos__c 
			WHERE	RecordType.Name = 'Parceiro'	AND
					NF_Representacao__c = null		AND
					Nota_Fiscal1__r.Faturamento_Feito2__c = :filtro_conta_id	AND
					Name LIKE :pesquisa_sql
		];
		
        c_recebimentos.clear();
		for(Recebimentos__c recebimento : recebimentos)
			c_recebimentos.add(new cRecebimento(recebimento));
		
		qtd_recebimentos = c_recebimentos.size();
	}
	
	public void Adicionar() {
		List<Recebimentos__c> recebimentos = new List<Recebimentos__c>();
        for(cRecebimento c_recebimento : c_recebimentos){
			if(c_recebimento.caixa == true){
				c_recebimento.corpo.NF_Representacao__c = faturamento_id;
				recebimentos.add(c_recebimento.corpo);
			}
		}
		if(recebimentos.size()>0)
			update recebimentos;
		mensagem = recebimentos.size() + ' item(s) adicionado(s)';
		
		Pesquisar();
	}
	
	public class cRecebimento {
		public Recebimentos__c 	corpo 	{get; set;}
		public Boolean 			caixa 	{get; set;}

		public cRecebimento(Recebimentos__c recebimento) {
			corpo 	= recebimento;
			caixa 	= false;
		}
	}
}