force-app/main/default/objects/Faturamento__c/Faturamento__c.object-meta.xml
<CustomObject>
    <label>Faturamento</label>
    <nameField>
        <label>Número</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Faturamentos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Faturamento__c/fields/Nome_da_Conta2__c.field-meta.xml
<CustomField>
    <fullName>Nome_da_Conta2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Nome da conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Faturamentos</relationshipLabel>
    <relationshipName>Faturas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Faturamento__c/fields/Oportunidade__c.field-meta.xml
<CustomField>
    <fullName>Oportunidade__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Se Oportunidade:
- Contrato de Serviços Corretiva/Preventiva/Metrologia (Serviço+Peça)
- Assistência : Preventiva : Avulso Pacote (Serviço+Peça)
- Assistência : Metrologia : Avulso Pacote (Serviço)</description>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Pagamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Faturamento__c/fields/Ordem_de_Trabalho__c.field-meta.xml
<CustomField>
    <fullName>Ordem_de_Trabalho__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Se Ordem de Trab.:
- Assistência : Corretiva : Avulso Unitário/Pacote/AddContrato (Serviço)
-*Assistência : Preventiva : Avulso Unitário (Serviço+Peça)
-*Assistência : Metrologia : Avulso Unitário (Serviço)</description>
    <label>Ordem de trabalho</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipName>Faturamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Faturamento__c/fields/Pedido__c.field-meta.xml
<CustomField>
    <fullName>Pedido__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Se Pedido de Oportunidade:
- Comercial Público (Produtos)
- Comercial Privado (Produtos)

Se Pedido de Ordem de Trab.:
- Assistência : Corretiva : Avulso Unitário/Pacote/AddContrato (Peças)</description>
    <label>Pedido</label>
    <referenceTo>Order</referenceTo>
    <relationshipName>Faturamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Ordem_de_trabalho__c.field-meta.xml
<CustomField>
    <fullName>Ordem_de_trabalho__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ordem de trabalho</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Faturamento__c.field-meta.xml
<CustomField>
    <fullName>Faturamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Faturamento (Representação)</label>
    <referenceTo>Faturamento__c</referenceTo>
    <relationshipLabel>Ordens de trabalho</relationshipLabel>
    <relationshipName>Ordens_de_trabalho</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FatuAutConClass.cls
public class FatuAutConClass {
    
    public static String FluxoInicial(Faturamento__c faturamento){
        String retorno = null;
        String msg_erro = 'Informe esse campo';
        
        if(faturamento.Nome_da_Conta2__c == null){
            
            if(faturamento.Pedido__c != null){
                Order pedido = new order();
                pedido = ObtemPedido(faturamento.Pedido__c);
                if(pedido.AccountId != null)
                    faturamento.Nome_da_Conta2__c = pedido.AccountId;
                else
                    retorno = msg_erro;
            }
            
            else if(faturamento.Oportunidade__c != null){
                Opportunity oportunidade = new Opportunity();
                oportunidade = ObtemOpp(faturamento.Oportunidade__c);
                if(oportunidade.AccountId != null)
                    faturamento.Nome_da_Conta2__c = oportunidade.AccountId;
                else
                    retorno = msg_erro;
            }
            
            else if(faturamento.Ordem_de_Trabalho__c != null){
                WorkOrder ordem_de_trabalho = new WorkOrder();
                ordem_de_trabalho = ObtemOt(faturamento.Ordem_de_Trabalho__c);
                if(ordem_de_trabalho.AccountId != null)
                    faturamento.Nome_da_Conta2__c = ordem_de_trabalho.AccountId;
                else
                    retorno = msg_erro;
            }
            
            else{
                retorno = msg_erro;
            }
        }
        
        return retorno;
    }
    
    public static Order ObtemPedido(Id pedido_id){
    	Order pedido = new order();
        pedido = [
            SELECT	Id, AccountId	
            FROM 	Order
            WHERE	Id = :pedido_id
        ];
        return pedido;
    }  
    
    public static Opportunity ObtemOpp(Id oportunidade_id){
    	Opportunity oportunidade = new Opportunity();
        oportunidade = [
            SELECT	Id, AccountId	
            FROM 	Opportunity
            WHERE	Id = :oportunidade_id
        ];
        return oportunidade;
    }  
    
    public static WorkOrder ObtemOt(Id ordem_de_trabalho_id){
    	WorkOrder ordem_de_trabalho = new WorkOrder();
        ordem_de_trabalho = [
            SELECT	Id, AccountId	
            FROM 	WorkOrder
            WHERE	Id = :ordem_de_trabalho_id
        ];
        return ordem_de_trabalho;
    }  
    
}