force-app/main/default/objects/Faturamento__c/Faturamento__c.object-meta.xml
<CustomObject>
    <label>Faturamento</label>
    <nameField>
        <label>Número</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Faturamentos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Faturamento__c/fields/Pedido__c.field-meta.xml
<CustomField>
    <fullName>Pedido__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Se Pedido de Oportunidade:
- Comercial Público (Produtos)
- Comercial Privado (Produtos)

Se Pedido de Ordem de Trab.:
- Assistência : Corretiva : Avulso Unitário/Pacote/AddContrato (Peças)</description>
    <label>Pedido</label>
    <referenceTo>Order</referenceTo>
    <relationshipName>Faturamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Gerente__c.field-meta.xml
<CustomField>
    <fullName>Gerente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gerente</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Pedidos1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Natureza_de_Opera_o__c.field-meta.xml
<CustomField>
    <fullName>Natureza_de_Opera_o__c</fullName>
    <label>Natureza de Operação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BONIFICAÇÃO</fullName>
            </value>
            <value>
                <fullName>DEMONSTRAÇÃO</fullName>
            </value>
            <value>
                <fullName>LOCAÇÃO</fullName>
            </value>
            <value>
                <fullName>EMPRÉSTIMO</fullName>
            </value>
            <value>
                <fullName>REMESSA DE LOCAÇÃO</fullName>
            </value>
            <value>
                <fullName>REMESSA DE TROCA</fullName>
            </value>
            <value>
                <fullName>REMESSA EM CONSIGNAÇÃO</fullName>
            </value>
            <value>
                <fullName>SERVIÇO</fullName>
            </value>
            <value>
                <fullName>VENDA</fullName>
            </value>
            <value>
                <fullName>VENDA DA CONSIGNAÇÃO</fullName>
            </value>
            <value>
                <fullName>RETORNO DE LOCAÇÃO</fullName>
            </value>
            <value>
                <fullName>EXPORTAÇÃO</fullName>
            </value>
            <value>
                <fullName>Baixa de estoque Interno</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Valor_Recebido__c.field-meta.xml
<CustomField>
    <fullName>Valor_Recebido__c</fullName>
    <inlineHelpText>Este campo deve ser preenchido apenas quando o pagamento for antecipado.</inlineHelpText>
    <label>Valor Recebido</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PedidosVendedor</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recebimentos__c/Recebimentos__c.object-meta.xml
<CustomObject>
    <label>Recebimento</label>
    <nameField>
        <label>Número do Recebimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recebimentos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Recebimentos__c/fields/Comissao_Gerente_Paga__c.field-meta.xml
<CustomField>
    <fullName>Comissao_Gerente_Paga__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Comissão Gerente Paga</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Recebimentos__c/fields/ComissaoGerente__c.field-meta.xml
<CustomField>
    <fullName>ComissaoGerente__c</fullName>
    <formula>Valor_Recebido__c * Aliquota_Gerente__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Comissão Gerente</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Recebimentos__c/fields/ComissaoPaga__c.field-meta.xml
<CustomField>
    <fullName>ComissaoPaga__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Comissão Paga</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Recebimentos__c/fields/ComissaoVendedor__c.field-meta.xml
<CustomField>
    <fullName>ComissaoVendedor__c</fullName>
    <formula>Valor_Pago__c *  AliquotaVendedor__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Comissão Vendedor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Recebimentos__c/fields/Data_do_Recebimento__c.field-meta.xml
<CustomField>
    <fullName>Data_do_Recebimento__c</fullName>
    <label>Data do Recebimento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Recebimentos__c/fields/Gerente__c.field-meta.xml
<CustomField>
    <fullName>Gerente__c</fullName>
    <formula>Titulo__r.Faturamento__r.Pedido__r.Gerente__r.FirstName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gerente</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Recebimentos__c/fields/Pedido__c.field-meta.xml
<CustomField>
    <fullName>Pedido__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pedido</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Recebimentos</relationshipLabel>
    <relationshipName>Recebimentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recebimentos__c/fields/Titulo__c.field-meta.xml
<CustomField>
    <fullName>Titulo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Título</label>
    <referenceTo>Titulo__c</referenceTo>
    <relationshipLabel>Recebimentos</relationshipLabel>
    <relationshipName>Recebimentos_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recebimentos__c/fields/Valor_Recebido__c.field-meta.xml
<CustomField>
    <fullName>Valor_Recebido__c</fullName>
    <label>Valor Recebido</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Recebimentos__c/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <formula>Pedido__r.Vendedor__r.FirstName + &apos; &apos; +  Pedido__r.Vendedor__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vendedor do pedido</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Titulo__c/Titulo__c.object-meta.xml
<CustomObject>
    <label>Título</label>
    <nameField>
        <label>Número do Título</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Títulos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Titulo__c/fields/Faturamento__c.field-meta.xml
<CustomField>
    <fullName>Faturamento__c</fullName>
    <label>Faturamento</label>
    <referenceTo>Faturamento__c</referenceTo>
    <relationshipLabel>Títulos</relationshipLabel>
    <relationshipName>Titulos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Titulo__c/fields/Gerente__c.field-meta.xml
<CustomField>
    <fullName>Gerente__c</fullName>
    <label>Gerente</label>
    <length>140</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Titulo__c/fields/Pedido__c.field-meta.xml
<CustomField>
    <fullName>Pedido__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pedido</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Títulos</relationshipLabel>
    <relationshipName>T_tulos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Titulo__c/fields/Titulo__c.field-meta.xml
<CustomField>
    <fullName>Titulo__c</fullName>
    <label>Titulo</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Titulo__c/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <label>Vendedor</label>
    <length>140</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Comiss.cls
public class Comiss {
    public list <Recebimentos__c> Records{get;set;}
    public String colaborador {get;set;}
    public String gerente {get;set;}
    public String operacao {get;set;}
    public date startDate {get;set;}
	public date endDate {get;set;}
    public Boolean teste {get;set;}
    public Boolean teste2 {get;set;}
    public Boolean teste3 {get;set;}    
    public String pago {get;set;}
    public Boolean print {get;set;}

    public Boolean mostrarprem {get;set;}
    public Comiss(){
        teste =true;
        teste2 =false;
        teste3 =false;        
        mostrarprem = false;
        print=false;
    }
    public void show(){
        teste = true;
        pago = 'todas';
        teste3=false;
    }
    public void page(){
        mostrarprem=true;
    }
        public void print(){
        print=true;
            teste=false;
    }
	public void pageclose(){
        mostrarprem=false;
    }    
    public void close(){
        teste = false;
        teste3 = true;        
    }
    public void search() {
        if (pago == 'true'){
            string searchquery= 'SELECT Name, Id, Vendedor__c, Valor_Recebido__c, ComissaoVendedor__c, ComissaoPaga__c, Titulo__c,' + 
              + 'Data_do_Recebimento__c, Comissao_Gerente_Paga__c, Gerente__c, ComissaoGerente__c, Titulo__r.Faturamento__r.Pedido__r.OrderNumber, Titulo__r.Faturamento__r.Pedido__r.Natureza_de_Opera_o__c '+
              + 'FROM Recebimentos__c WHERE (Gerente__c =:gerente or Gerente__c like \'%'+gerente+'%\') and (Vendedor__c =:colaborador or Vendedor__c like \'%'+colaborador+'%\') and (ComissaoPaga__c = true) and (Titulo__r.Faturamento__r.Pedido__r.Natureza_de_Opera_o__c =:operacao or Titulo__r.Faturamento__r.Pedido__r.Natureza_de_Opera_o__c like \'%'+operacao+'%\') and (Data_do_Recebimento__c >=: startDate and Data_do_Recebimento__c <=: endDate) ' +
              + 'ORDER BY Data_do_Recebimento__c';       
        Records = Database.query(searchquery); 
        teste2 = true;
        }
        else if (pago == 'false'){
            string searchquery= 'SELECT Name, Id, Vendedor__c, Valor_Recebido__c, ComissaoVendedor__c, ComissaoPaga__c, Titulo__c, ' + 
              + 'Data_do_Recebimento__c, Comissao_Gerente_Paga__c, Gerente__c, ComissaoGerente__c, Titulo__r.Faturamento__r.Pedido__r.OrderNumber, Titulo__r.Faturamento__r.Pedido__r.Natureza_de_Opera_o__c '+
              + 'FROM Recebimentos__c WHERE (Gerente__c =:gerente or Gerente__c like \'%'+gerente+'%\') and (Vendedor__c =:colaborador or Vendedor__c like \'%'+colaborador+'%\') and (ComissaoPaga__c = false) and (Titulo__r.Faturamento__r.Pedido__r.Natureza_de_Opera_o__c =:operacao or Titulo__r.Faturamento__r.Pedido__r.Natureza_de_Opera_o__c like \'%'+operacao+'%\') and (Data_do_Recebimento__c >=: startDate and Data_do_Recebimento__c <=: endDate) ' +
              + 'ORDER BY Data_do_Recebimento__c';       
        Records = Database.query(searchquery); 
        teste2 = true;
        }       
        else{
         string searchquery= 'SELECT Name, Id, Vendedor__c, Valor_Recebido__c, ComissaoVendedor__c, ComissaoPaga__c, Titulo__c, ' + 
              + 'Data_do_Recebimento__c, Gerente__c, Comissao_Gerente_Paga__c, ComissaoGerente__c, Titulo__r.Faturamento__r.Pedido__r.OrderNumber, Titulo__r.Faturamento__r.Pedido__r.Natureza_de_Opera_o__c '+
              + 'FROM Recebimentos__c WHERE (Gerente__c =:gerente or Gerente__c like \'%'+gerente+'%\') and (Vendedor__c =:colaborador or Vendedor__c like \'%'+colaborador+'%\') and (Titulo__r.Faturamento__r.Pedido__r.Natureza_de_Opera_o__c =:operacao or Titulo__r.Faturamento__r.Pedido__r.Natureza_de_Opera_o__c like \'%'+operacao+'%\') and (Data_do_Recebimento__c >=: startDate and Data_do_Recebimento__c <=: endDate) ' +
              + 'ORDER BY Data_do_Recebimento__c';       
        Records = Database.query(searchquery); 
        teste2 = true;   
        }

    }
    public void clear(){
        if (Records != null){
            Records.clear();
            colaborador = null;
            operacao = null;
            gerente = null;
            teste2 = false;
            pago = 'todas';
        }
    }
    public void save() {
		update Records;
    }
     public PageReference cancel() {
   // System.Debug('GETURL ::: '+ApexPages.currentPage().getUrl());
        return null;
    }
    }