force-app/main/default/objects/Faturamento__c/Faturamento__c.object-meta.xml
<CustomObject>
    <label>Faturamento</label>
    <nameField>
        <label>Número</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Faturamentos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Meta__mdt/Meta__mdt.object-meta.xml
<CustomObject>
    <description>Metas de recebimentos dos departamentos.</description>
    <label>Meta</label>
    <pluralLabel>Metas</pluralLabel>
</CustomObject>

force-app/main/default/objects/Meta__mdt/fields/Premiacao__c.field-meta.xml
<CustomField>
    <fullName>Premiacao__c</fullName>
    <label>Premiação (%)</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Meta__mdt/fields/Valor__c.field-meta.xml
<CustomField>
    <fullName>Valor__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Valor</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order/fields/Departamento__c.field-meta.xml
<CustomField>
    <fullName>Departamento__c</fullName>
    <label>_Departamento (del)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Comercial</fullName>
            </value>
            <value>
                <fullName>Governo</fullName>
            </value>
            <value>
                <fullName>Serviço</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Natureza_de_Opera_o__c.field-meta.xml
<CustomField>
    <fullName>Natureza_de_Opera_o__c</fullName>
    <label>Natureza de Operação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BONIFICAÇÃO</fullName>
            </value>
            <value>
                <fullName>DEMONSTRAÇÃO</fullName>
            </value>
            <value>
                <fullName>LOCAÇÃO</fullName>
            </value>
            <value>
                <fullName>EMPRÉSTIMO</fullName>
            </value>
            <value>
                <fullName>REMESSA DE LOCAÇÃO</fullName>
            </value>
            <value>
                <fullName>REMESSA DE TROCA</fullName>
            </value>
            <value>
                <fullName>REMESSA EM CONSIGNAÇÃO</fullName>
            </value>
            <value>
                <fullName>SERVIÇO</fullName>
            </value>
            <value>
                <fullName>VENDA</fullName>
            </value>
            <value>
                <fullName>VENDA DA CONSIGNAÇÃO</fullName>
            </value>
            <value>
                <fullName>RETORNO DE LOCAÇÃO</fullName>
            </value>
            <value>
                <fullName>EXPORTAÇÃO</fullName>
            </value>
            <value>
                <fullName>Baixa de estoque Interno</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Valor_Recebido__c.field-meta.xml
<CustomField>
    <fullName>Valor_Recebido__c</fullName>
    <inlineHelpText>Este campo deve ser preenchido apenas quando o pagamento for antecipado.</inlineHelpText>
    <label>Valor Recebido</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PedidosVendedor</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recebimentos__c/Recebimentos__c.object-meta.xml
<CustomObject>
    <label>Recebimento</label>
    <nameField>
        <label>Número do Recebimento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recebimentos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Recebimentos__c/fields/ComissaoPaga__c.field-meta.xml
<CustomField>
    <fullName>ComissaoPaga__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Comissão Paga</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Recebimentos__c/fields/ComissaoVendedor__c.field-meta.xml
<CustomField>
    <fullName>ComissaoVendedor__c</fullName>
    <formula>Valor_Pago__c *  AliquotaVendedor__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Comissão Vendedor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Recebimentos__c/fields/Data_do_Recebimento__c.field-meta.xml
<CustomField>
    <fullName>Data_do_Recebimento__c</fullName>
    <label>Data do Recebimento</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Recebimentos__c/fields/Pedido__c.field-meta.xml
<CustomField>
    <fullName>Pedido__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pedido</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Recebimentos</relationshipLabel>
    <relationshipName>Recebimentos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recebimentos__c/fields/Titulo__c.field-meta.xml
<CustomField>
    <fullName>Titulo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Título</label>
    <referenceTo>Titulo__c</referenceTo>
    <relationshipLabel>Recebimentos</relationshipLabel>
    <relationshipName>Recebimentos_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recebimentos__c/fields/Valor_Recebido__c.field-meta.xml
<CustomField>
    <fullName>Valor_Recebido__c</fullName>
    <label>Valor Recebido</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Recebimentos__c/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <formula>Pedido__r.Vendedor__r.FirstName + &apos; &apos; +  Pedido__r.Vendedor__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vendedor do pedido</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Titulo__c/Titulo__c.object-meta.xml
<CustomObject>
    <label>Título</label>
    <nameField>
        <label>Número do Título</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Títulos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Titulo__c/fields/Departamento__c.field-meta.xml
<CustomField>
    <fullName>Departamento__c</fullName>
    <label>Departamento</label>
    <length>140</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Titulo__c/fields/Faturamento__c.field-meta.xml
<CustomField>
    <fullName>Faturamento__c</fullName>
    <label>Faturamento</label>
    <referenceTo>Faturamento__c</referenceTo>
    <relationshipLabel>Títulos</relationshipLabel>
    <relationshipName>Titulos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Titulo__c/fields/Pedido__c.field-meta.xml
<CustomField>
    <fullName>Pedido__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pedido</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Títulos</relationshipLabel>
    <relationshipName>T_tulos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Titulo__c/fields/Titulo__c.field-meta.xml
<CustomField>
    <fullName>Titulo__c</fullName>
    <label>Titulo</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Titulo__c/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <label>Vendedor</label>
    <length>140</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Departamento_Premiacao__c.field-meta.xml
<CustomField>
    <fullName>Departamento_Premiacao__c</fullName>
    <label>Departamento Premiação</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Governo</fullName>
            </value>
            <value>
                <fullName>Comercial</fullName>
            </value>
            <value>
                <fullName>Serviço</fullName>
            </value>
            <value>
                <fullName>Locação</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Peso_Premiacao__c.field-meta.xml
<CustomField>
    <fullName>Peso_Premiacao__c</fullName>
    <label>Peso Premiação</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PremiacoesClass.cls
public class PremiacoesClass {
    public list <Recebimentos__c> Records{get;set;}
    public String departamento {get;set;}
    public date startDate {get;set;}
	public date endDate {get;set;}
    public Boolean showfiltros {get;set;}
    public Boolean show {get;set;}
    public Boolean showA {get;set;}
    public list <Meta__mdt> Metas{get;set;}
    public list <User> Users{get;set;}
    public PremiacoesClass(){
        show=false;
        showA=false;
        showfiltros=true;
        Metas = [SELECT Valor__c, Premiacao__c, MasterLabel FROM Meta__mdt];
    }
    public void search() {
        string MetasQ = 'SELECT MasterLabel, Valor__c, Premiacao__c FROM Meta__mdt WHERE MasterLabel like \'%'+departamento+'%\'  Order By Valor__c';
		Metas = Database.query(MetasQ);
        String Premiados = 'SELECT Name, Peso_Premiacao__c, Departamento_Premiacao__c FROM USER WHERE Departamento_Premiacao__c includes (:departamento) ORDER BY Name';	
       	Users = Database.query(Premiados);
        show=true;
          string searchquery= 'SELECT Name, Id, Vendedor__c, Valor_Recebido__c, ComissaoVendedor__c, ComissaoPaga__c, ' + 
              + 'Data_do_Recebimento__c, Departamento__c, Titulo__r.Faturamento__r.Pedido__c, Titulo__r.Faturamento__r.Pedido__r.Natureza_de_Opera_o__c '+
              + 'FROM Recebimentos__c WHERE Departamento__c like \'%'+departamento+'%\' and (Data_do_Recebimento__c >=: startDate and Data_do_Recebimento__c <=: endDate) ORDER BY Data_do_Recebimento__c';
        Records = Database.query(searchquery);
    }
    public void clear(){
        if (Records != null){
            Records.clear();
            show=false;
            departamento = ' ';
            startDate = null;
            endDate = null;
        }
    }
    public void fechar(){
        showfiltros=false;
        showA=true;
    }
    public void abrir(){
        showfiltros=true;
        showA=false;
    }
      public PageReference passValue() {
          return null;
      }
}