force-app/main/default/objects/Entrada_de_Estoque__c/Entrada_de_Estoque__c.object-meta.xml
<CustomObject>
    <label>Entrada de Estoque</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Entradas de Estoque</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Entrada_de_Estoque__c/fields/Estoque__c.field-meta.xml
<CustomField>
    <fullName>Estoque__c</fullName>
    <label>Estoque</label>
    <referenceTo>Estoque__c</referenceTo>
    <relationshipLabel>Entradas de Estoque</relationshipLabel>
    <relationshipName>Entradas_de_Estoque</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Entrada_de_Estoque__c/fields/Pedido__c.field-meta.xml
<CustomField>
    <fullName>Pedido__c</fullName>
    <label>Pedido</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Entrada_de_Estoque__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Entradas de Estoque</relationshipLabel>
    <relationshipName>Entradas_de_Estoque</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Estoque__c/Estoque__c.object-meta.xml
<CustomObject>
    <label>Estoque</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estoques</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/SimpleEntradaDeEstoqueTriggerTest.cls
@isTest
public class SimpleEntradaDeEstoqueTriggerTest {   
    @isTest 
    static void testDuplicatePrevention() {
        try { 
            // Simulação de estoque e produto usando os IDs fornecidos
            estoque__c estoque = new estoque__c(id = 'a1A5A00000CYT09');
            Product2 produto = new Product2(id = '01t6e000009nWFt');
            
            // Criação da entrada de estoque
            Entrada_de_Estoque__c novaEntrada = new Entrada_de_Estoque__c(
                Produto__c = produto.Id, 
                Estoque__c = estoque.Id
            );
            
            // Insere a nova entrada de estoque para testar a trigger
            insert novaEntrada;
            
            List<Entrada_de_Estoque__c> entradas = [
                SELECT Id, Pedido__c, Estoque__c 
                FROM Entrada_de_Estoque__c 
                WHERE Id = :novaEntrada.Id
            ];
      
          
            
        } catch(Exception e) {
            System.debug('error: ' + e);      
        }
    }
}