force-app/main/default/objects/Consumivel_de_comodato__c/Consumivel_de_comodato__c.object-meta.xml
<CustomObject>
    <label>Consumível de comodato</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Nº</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Consumíveis de comodato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Consumivel_de_comodato__c/fields/Quantidade_vinculada__c.field-meta.xml
<CustomField>
    <fullName>Quantidade_vinculada__c</fullName>
    <label>Quantidade vinculada</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Quantidade_vinculada_comodato__c.field-meta.xml
<CustomField>
    <fullName>Quantidade_vinculada_comodato__c</fullName>
    <label>Quantidade vinculada (comodato)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vinculo_consumivel_requerido__c/Vinculo_consumivel_requerido__c.object-meta.xml
<CustomObject>
    <label>Vínculo consumível requerido</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Nº</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vinculo consumíveis requeridos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vinculo_consumivel_requerido__c/fields/Ativo_do_comodato__c.field-meta.xml
<CustomField>
    <fullName>Ativo_do_comodato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ativo do comodato</label>
    <referenceTo>Produto_da_demonstracao__c</referenceTo>
    <relationshipLabel>Vinculo consumíveis requeridos</relationshipLabel>
    <relationshipName>Vinculo_consum_veis_requeridos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vinculo_consumivel_requerido__c/fields/Consum_vel_de_comodato__c.field-meta.xml
<CustomField>
    <fullName>Consum_vel_de_comodato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Consumível de comodato</label>
    <referenceTo>Consumivel_de_comodato__c</referenceTo>
    <relationshipLabel>Vinculo consumíveis requeridos</relationshipLabel>
    <relationshipName>Vinculo_consum_veis_requeridos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vinculo_de_venda_consumivel__c/Vinculo_de_venda_consumivel__c.object-meta.xml
<CustomObject>
    <label>Vínculo de venda consumível</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Nº</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vínculos de venda consumível</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vinculo_de_venda_consumivel__c/fields/Ativo_do_comodato__c.field-meta.xml
<CustomField>
    <fullName>Ativo_do_comodato__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ativo do comodato</label>
    <referenceTo>Produto_da_demonstracao__c</referenceTo>
    <relationshipLabel>Vínculos de venda consumível</relationshipLabel>
    <relationshipName>V_nculos_de_venda_consum_vel</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vinculo_de_venda_consumivel__c/fields/Produto_do_pedido__c.field-meta.xml
<CustomField>
    <fullName>Produto_do_pedido__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto do pedido</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Vínculos de venda consumível</relationshipLabel>
    <relationshipName>V_nculos_de_venda_consum_vel</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/vinculaConsumiveis.cls
public class vinculaConsumiveis {
    @AuraEnabled
    public static String sendSelectedItems(String comodatoItemId, List<String> orderItemIds, Integer quantity) {
        // Lógica para processar os IDs recebidos
        System.debug('ID do item de Comodato: ' + comodatoItemId);
        System.debug('IDs dos itens de pedido: ' + orderItemIds);
        
        List<Vinculo_de_venda_consumivel__c> vinculos = new List<Vinculo_de_venda_consumivel__c>();
        List<OrderItem> orderItemsToUpdate = new List<OrderItem>();  // Lista para armazenar os OrderItems a serem atualizados
        
        // Consultando todos os OrderItems que precisam ser atualizados
        List<OrderItem> orderItems = [SELECT Id, Quantidade_vinculada_comodato__c FROM OrderItem WHERE Id IN :orderItemIds];
        
        for (String orderItemId : orderItemIds) {
            Vinculo_de_venda_consumivel__c vvc = new Vinculo_de_venda_consumivel__c();
            vvc.Produto_do_pedido__c = orderItemId;
            vvc.Ativo_do_comodato__c = comodatoItemId;
            vvc.Quantidade__c = quantity;
            vinculos.add(vvc);
            
            // Encontrando o OrderItem correspondente e somando a quantidade
            for (OrderItem oi : orderItems) {
                if (oi.Id == orderItemId) {
                    // Atualizando o campo Quantidade_vinculada_comodato__c
                    oi.Quantidade_vinculada_comodato__c = (oi.Quantidade_vinculada_comodato__c != null ? oi.Quantidade_vinculada_comodato__c : 0) + quantity;
                    orderItemsToUpdate.add(oi);
                }
            }
        }
        
        try {
            // Inserindo os novos vínculos
            // Atualizando os OrderItems com as novas quantidades
            if (!orderItemsToUpdate.isEmpty()) {
                update orderItemsToUpdate;
            }
            insert vinculos;       
            
            
            return 'Success';
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled
    public static String sendSelectedItems2(String comodatoItemId, List<String> consumiveis, Integer quantity) {
        // Lógica para processar os IDs recebidos
        System.debug('ID do item de Comodato: ' + comodatoItemId);
        System.debug('IDs dos itens de pedido: ' + consumiveis);
        
        List<Vinculo_consumivel_requerido__c> vinculos = new List<Vinculo_consumivel_requerido__c>();
        List<Consumivel_de_comodato__c> consumiveisToUpdate = new List<Consumivel_de_comodato__c>();  // Lista para armazenar os OrderItems a serem atualizados
        
        // Consultando todos os OrderItems que precisam ser atualizados
        List<Consumivel_de_comodato__c> consumiveisIds = [SELECT Id, Quantidade_vinculada__c FROM Consumivel_de_comodato__c WHERE Id IN :consumiveis];
        
        for (String consumivelId : consumiveis) {
            Vinculo_consumivel_requerido__c vvc = new Vinculo_consumivel_requerido__c();
            vvc.Consum_vel_de_comodato__c = consumivelId;
            vvc.Ativo_do_comodato__c = comodatoItemId;
            vvc.Quantidade__c = quantity;
            vinculos.add(vvc);
            
            // Encontrando o OrderItem correspondente e somando a quantidade
            for (Consumivel_de_comodato__c oi : consumiveisIds) {
                if (oi.Id == consumivelId) {
                    // Atualizando o campo Quantidade_vinculada_comodato__c
                    oi.Quantidade_vinculada__c = (oi.Quantidade_vinculada__c != null ? oi.Quantidade_vinculada__c : 0) + quantity;
                    consumiveisToUpdate.add(oi);
                }
            }
        }
        
        try {
            // Inserindo os novos vínculos
            // Atualizando os OrderItems com as novas quantidades
            if (!consumiveisToUpdate.isEmpty()) {
                update consumiveisToUpdate;
            }
            insert vinculos;       
            
            
            return 'Success';
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled(cacheable=true)
    public static List<sObject> executeSoql(String soql) {
        List<sObject> result = Database.query(soql);
        return result;
        
    }
}