force-app/main/default/objects/Pedido_de_compra__c/Pedido_de_compra__c.object-meta.xml
<CustomObject>
    <label>Cotação de compra</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número da cotação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cotações de compra</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Pedido_de_compra__c/fields/Data_de_aprova_o__c.field-meta.xml
<CustomField>
    <fullName>Data_de_aprova_o__c</fullName>
    <label>Data de aprovação</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Pedido_de_compra__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1 - Rascunho</fullName>
                <default>true</default>
                <label>1 - Rascunho</label>
            </value>
            <value>
                <fullName>2 - Em Andamento</fullName>
            </value>
            <value>
                <fullName>3 - Em Aprovação</fullName>
            </value>
            <value>
                <fullName>4 - Em aprovação financeira</fullName>
            </value>
            <value>
                <fullName>5 - Concluído</fullName>
            </value>
            <value>
                <fullName>6 - Reprovado</fullName>
            </value>
            <value>
                <fullName>7 - Cancelado</fullName>
            </value>
            <value>
                <fullName>4 - Compra em Andamento</fullName>
                <isActive>false</isActive>
                <label>4 - Compra em Andamento</label>
            </value>
            <value>
                <fullName>4 - Concluído</fullName>
                <isActive>false</isActive>
                <label>4 - Concluído</label>
            </value>
            <value>
                <fullName>5 - Reprovado</fullName>
                <isActive>false</isActive>
                <label>5 - Reprovado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Pedido_compra_dataAprovacao_Test.cls
@isTest(seeAllData=true)
private class Pedido_compra_dataAprovacao_Test {

    @isTest
    static void testAtualizacaoDataAprovacao() {
       
        List<Pedido_de_compra__c> pedidoTeste = [SELECT Id, name, Data_de_aprova_o__c, Status__c FROM Pedido_de_compra__c WHERE id = 'a1e6e00002qdyQWAAY' LIMIT 1];
        
        // Verifica se há registros retornados pela consulta
        if (!pedidoTeste.isEmpty()) {
            System.debug('Cotação de compra: ' + pedidoTeste[0]);

            pedidoTeste[0].Data_de_aprova_o__c = null;
            update pedidoTeste[0];
        } else {
            System.debug('Nenhum registro encontrado para a consulta.');
        }
    }
}