force-app/main/default/objects/Transacao__c/Transacao__c.object-meta.xml
<CustomObject>
    <label>Transação</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transações</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transacao__c/fields/Adiantamento__c.field-meta.xml
<CustomField>
    <fullName>Adiantamento__c</fullName>
    <label>Adiantamento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Tipo__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Não</fullName>
            </value>
            <value>
                <fullName>Sim</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transacao__c/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Tipo__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passagem</fullName>
            </value>
            <value>
                <fullName>KM rodado</fullName>
            </value>
            <value>
                <fullName>Combustível</fullName>
            </value>
            <value>
                <fullName>Pedágio</fullName>
            </value>
            <value>
                <fullName>Estacionamento</fullName>
            </value>
            <value>
                <fullName>Taxi/Uber</fullName>
            </value>
            <value>
                <fullName>Locação</fullName>
            </value>
            <value>
                <fullName>Manutenção</fullName>
            </value>
            <value>
                <fullName>Hospedagem</fullName>
            </value>
            <value>
                <fullName>Alimentação</fullName>
            </value>
            <value>
                <fullName>Inscrição</fullName>
            </value>
            <value>
                <fullName>Outro</fullName>
            </value>
            <value>
                <fullName>Estorno</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transacao__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quitação</fullName>
            </value>
            <value>
                <fullName>Requisição</fullName>
            </value>
            <value>
                <fullName>Estorno</fullName>
                <isActive>false</isActive>
                <label>Estorno</label>
            </value>
            <value>
                <fullName>Reembolso</fullName>
                <isActive>false</isActive>
                <label>Reembolso</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Transacao__c/fields/Valor__c.field-meta.xml
<CustomField>
    <fullName>Valor__c</fullName>
    <label>Valor</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transacao__c/fields/Valor_valido__c.field-meta.xml
<CustomField>
    <fullName>Valor_valido__c</fullName>
    <label>Valor válido</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transacao__c/fields/Viagem__c.field-meta.xml
<CustomField>
    <fullName>Viagem__c</fullName>
    <label>Viagem</label>
    <referenceTo>Viagem__c</referenceTo>
    <relationshipName>Despesas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Viagem__c/Viagem__c.object-meta.xml
<CustomObject>
    <label>Viagem</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Viagens</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/ViagemTransacoes.cls
public class ViagemTransacoes{
	
    @AuraEnabled
    public static String ObterTransacoes(String viagem_id){
		Retorno retorno = new Retorno();
		List<Transacao__c> transacoes = [
			SELECT	Categoria__c, Valor__c, Tipo__c, Adiantamento__c, Valor_valido__c 
			FROM	Transacao__c
			WHERE 	Viagem__c = :viagem_id
		];
		
		for(Transacao__c transacao : transacoes){
			Boolean existe = false;
			for(Resumo resumo : retorno.resumos)
				if(resumo.despesa == transacao.Categoria__C)
					existe = true;
			if(!existe){
				Resumo resumo = new Resumo();
				resumo.despesa = transacao.Categoria__C;
				retorno.resumos.add(resumo);
			}
		}
		
		for(Transacao__c transacao : transacoes){
			for(Resumo resumo : retorno.resumos){
				if(resumo.despesa == transacao.Categoria__C){
					if(transacao.Tipo__c == 'Requisição'){
						resumo.requisitado += transacao.Valor__c;
						if(transacao.Adiantamento__c=='Sim')
							resumo.adiantado += transacao.Valor__c;
					}else{
						resumo.quitado += transacao.Valor__c;
						resumo.validado += transacao.Valor_valido__c;
					}
					resumo.saldo = resumo.validado - (resumo.adiantado*-1);
				}
			}
		}
		
		return JSON.serialize(retorno);
	}
	public class Retorno{
		List<Resumo> resumos;

		public Retorno(){
			resumos = new List<Resumo>();
		}
	}
	public class Resumo{
		String despesa;
		Decimal requisitado=0;
		Decimal adiantado=0;
		Decimal quitado=0;
		Decimal validado=0;
		Decimal saldo=0;
	}
}