force-app/main/default/objects/Lead/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <label>CPF</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LeadValidacaoTest.cls
@isTest
public class LeadValidacaoTest {
    @isTest
    static void testCreateLead() {
        // Criação de um novo lead
        Lead newLead = new Lead();
        newLead.FirstName = 'John';
        newLead.LastName = 'Doe';
        newLead.Company = 'Acme Inc.';
        newLead.Email = 'john.doe@acme.com';
        newLead.MobilePhone = '884613559';
        newLead.CPF__c = '884613559';
        newLead.CNPJ__c = '884613559';
        newLead.Phone = '884613559';
        newLead.Fax = '884613559';
        newLead.WebSite = '.';
        
        // Chama o método de criação de lead
        Test.startTest();
        try{
            insert newLead;
        }
        catch(DmlException e){}
        Test.stopTest();
        

    }
}