force-app/main/default/objects/Opportunity/fields/Contrato_de_Servico__c.field-meta.xml
<CustomField>
    <fullName>Contrato_de_Servico__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato de serviço (excluir)</label>
    <referenceTo>ServiceContract</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Faturamento_Feito2__c.field-meta.xml
<CustomField>
    <fullName>Faturamento_Feito2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Faturamento feito</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>FORNECEDOR, DISTRIBUIDOR</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Faturamentos Feitos (de oportunidades)</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ServiceContract/fields/Faturamento_feito__c.field-meta.xml
<CustomField>
    <fullName>Faturamento_feito__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Faturamento feito</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Faturamentos Feitos (de contratos de serviço)</relationshipLabel>
    <relationshipName>Contratos_de_Servi_o</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OppAtuFatClass.cls
public class OppAtuFatClass {
    
    public static String FluxoInicial(Opportunity oportunidade){
        String retorno = null;
        String msg_erro = 'Informe esse campo';
        
        if(oportunidade.Faturamento_Feito2__c == null){
            
            if(oportunidade.Contrato_de_Servico__c != null){
                ServiceContract contrato_de_servico = new ServiceContract();
                contrato_de_servico = ObtemContr(oportunidade.Contrato_de_Servico__c);
                if(contrato_de_servico.Faturamento_feito__c != null)
                    oportunidade.Faturamento_Feito2__c = contrato_de_servico.Faturamento_feito__c;
                else
                    retorno = msg_erro;
            }
            
            else{
                retorno = msg_erro;
            }
        }
        
        return retorno;
    }
    
    public static ServiceContract ObtemContr(Id contrato_de_servico_id){
    	ServiceContract contrato_de_servico = new ServiceContract();
        contrato_de_servico = [
            SELECT	Id, Faturamento_feito__c	
            FROM 	ServiceContract
            WHERE	Id = :contrato_de_servico_id
        ];
        return contrato_de_servico;
    }  
    
}