force-app/main/default/objects/Opportunity/fields/Data_e_hora_do_procedimento__c.field-meta.xml
<CustomField>
    <fullName>Data_e_hora_do_procedimento__c</fullName>
    <label>Data e hora do procedimento</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Instrumentador_2__c.field-meta.xml
<CustomField>
    <fullName>Instrumentador_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Instrumentador 3</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Oportunidades1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Instrumentador_3__c.field-meta.xml
<CustomField>
    <fullName>Instrumentador_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Instrumentador 2</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Oportunidades2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Instrumentador__c.field-meta.xml
<CustomField>
    <fullName>Instrumentador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Instrumentador</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OportunidadeValidacaoTest.cls
@isTest(seeAllData=true)
public class OportunidadeValidacaoTest {
	@isTest
    static void testCreateOpp(){
        Opportunity opp = new Opportunity();
        opp.Name = 'OPP Teste';
        opp.Data_e_hora_do_procedimento__c = system.now();
        opp.RecordTypeID = '0126e000001lAu7';
        opp.StageName = 'OPEN';
        opp.CloseDate = system.today() + 30;
        opp.Instrumentador__c = '005i0000005d2fF';
        opp.Instrumentador_2__c = '005i0000005d2fF';
        opp.Instrumentador_3__c = '005i0000005d2fF';
            
		Test.startTest();
        try{
            insert opp;
        }
        catch(DmlException e){}
        Test.stopTest();
    }
}