force-app/main/default/objects/Opportunity/fields/Faturamento_Feito2__c.field-meta.xml
<CustomField>
    <fullName>Faturamento_Feito2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Faturamento feito</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>FORNECEDOR, DISTRIBUIDOR</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Faturamentos Feitos (de oportunidades)</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Numero_OP__c.field-meta.xml
<CustomField>
    <fullName>Numero_OP__c</fullName>
    <label>Número da oportunidade</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sub_Fase__c.field-meta.xml
<CustomField>
    <fullName>Sub_Fase__c</fullName>
    <label>Subfase</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>StageName</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>COTAÇÃO PRÉVIA</fullName>
            </value>
            <value>
                <fullName>ABORTADO</fullName>
            </value>
            <value>
                <fullName>AGUARDANDO ANÁLISE</fullName>
            </value>
            <value>
                <fullName>AGUARDANDO CONTRATO</fullName>
            </value>
            <value>
                <fullName>AGUARDANDO EMPENHO</fullName>
            </value>
            <value>
                <fullName>AGUARDANDO HOMOLOGAÇÃO/ADJUDICADO</fullName>
            </value>
            <value>
                <fullName>AGUARDANDO PARTICIPAÇÃO</fullName>
            </value>
            <value>
                <fullName>EM ANDAMENTO</fullName>
            </value>
            <value>
                <fullName>CANCELADO</fullName>
            </value>
            <value>
                <fullName>DUPLICADO</fullName>
            </value>
            <value>
                <fullName>LOCAÇÃO</fullName>
            </value>
            <value>
                <fullName>ESTIMATIVA DE PREÇOS</fullName>
            </value>
            <value>
                <fullName>FINALIZADO TOTAL</fullName>
            </value>
            <value>
                <fullName>IMPUGNAÇÃO/ESCLARECIMENTOS</fullName>
            </value>
            <value>
                <fullName>PERDIDO</fullName>
            </value>
            <value>
                <fullName>RECURSO</fullName>
            </value>
            <value>
                <fullName>SUSPENSO</fullName>
            </value>
            <value>
                <fullName>FINALIZADO PARCIAL</fullName>
            </value>
            <value>
                <fullName>AGUARDANDO HABILITAÇÃO</fullName>
            </value>
            <value>
                <fullName>AGUARDANDO ENTREGA</fullName>
            </value>
            <value>
                <fullName>CONTRARRAZÃO DE RECURSO</fullName>
            </value>
            <value>
                <fullName>NEGÓCIO FUTURO</fullName>
            </value>
            <value>
                <fullName>COMODATO</fullName>
            </value>
            <value>
                <fullName>GARANTIDO</fullName>
            </value>
            <value>
                <fullName>AGUARDANDO DECISÃO DE RECURSO</fullName>
            </value>
            <value>
                <fullName>AGUARDANDO CONTRATO/EMPENHO</fullName>
                <isActive>false</isActive>
                <label>AGUARDANDO CONTRATO/EMPENHO</label>
            </value>
            <value>
                <fullName>PREVISTO</fullName>
                <isActive>false</isActive>
                <label>PREVISTO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Abreviacoes__c.field-meta.xml
<CustomField>
    <fullName>Abreviacoes__c</fullName>
    <label>Abreviações</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Analise_Tecnica__c.field-meta.xml
<CustomField>
    <fullName>Analise_Tecnica__c</fullName>
    <label>Análise Técnica</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Codigo_fabricante__c.field-meta.xml
<CustomField>
    <fullName>Codigo_fabricante__c</fullName>
    <formula>PricebookEntry.Product2.ProductCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Código fabricante</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Cumprimento_com_o_edital__c.field-meta.xml
<CustomField>
    <fullName>Cumprimento_com_o_edital__c</fullName>
    <label>Cumprimento com o edital</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Total</fullName>
            </value>
            <value>
                <fullName>Parcial</fullName>
            </value>
            <value>
                <fullName>Não cumpre</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Descricao_do_Especialista__c.field-meta.xml
<CustomField>
    <fullName>Descricao_do_Especialista__c</fullName>
    <label>Descritivo para proposta</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Enviado_questionameto_ou_impugna_o__c.field-meta.xml
<CustomField>
    <fullName>Enviado_questionameto_ou_impugna_o__c</fullName>
    <inlineHelpText>Enviado questionamento ou impugnação para melhoria dos filtros?</inlineHelpText>
    <label>Enviado questionamento ou impugnação?</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Interposicoes__c.field-meta.xml
<CustomField>
    <fullName>Interposicoes__c</fullName>
    <label>Interposições</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Item_do_edital__c.field-meta.xml
<CustomField>
    <fullName>Item_do_edital__c</fullName>
    <label>Item do edital</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Item_Pai__c.field-meta.xml
<CustomField>
    <fullName>Item_Pai__c</fullName>
    <label>Item pai</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Itens_que_justificam__c.field-meta.xml
<CustomField>
    <fullName>Itens_que_justificam__c</fullName>
    <inlineHelpText>Itens que justifiquem a escolha de marca e modelo.</inlineHelpText>
    <label>Itens que justifiquem</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Marcas_que_atendem__c.field-meta.xml
<CustomField>
    <fullName>Marcas_que_atendem__c</fullName>
    <label>Marcas que atendem</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Marcas_que_nao_atendem__c.field-meta.xml
<CustomField>
    <fullName>Marcas_que_nao_atendem__c</fullName>
    <label>Marcas que não atendem</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Nome_do_Fabricante__c.field-meta.xml
<CustomField>
    <fullName>Nome_do_Fabricante__c</fullName>
    <formula>Text( PricebookEntry.Product2.Marca__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Marca</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Perdido__c.field-meta.xml
<CustomField>
    <fullName>Perdido__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Perdido</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <formula>PricebookEntry.Product2.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Produto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Resposta_doorgao_e_novos_filtros__c.field-meta.xml
<CustomField>
    <fullName>Resposta_doorgao_e_novos_filtros__c</fullName>
    <inlineHelpText>RESPOSTA DO ÓRGÃO E NOVOS FILTROS SE APLICÁVEL</inlineHelpText>
    <label>Resposta do órgão e novos filtros</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Subtotal__c.field-meta.xml
<CustomField>
    <fullName>Subtotal__c</fullName>
    <label>Subtotal</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Subtotal_Unit__c.field-meta.xml
<CustomField>
    <fullName>Subtotal_Unit__c</fullName>
    <label>Subtotal Unit</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Valor_original_perdido__c.field-meta.xml
<CustomField>
    <fullName>Valor_original_perdido__c</fullName>
    <label>Valor original (perdido)</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Modelo__c.field-meta.xml
<CustomField>
    <fullName>Modelo__c</fullName>
    <label>Modelo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Valor_de_Venda__c.field-meta.xml
<CustomField>
    <fullName>Valor_de_Venda__c</fullName>
    <label>Valor de Venda</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/AnaliseItensEdital.cls
public with sharing class AnaliseItensEdital {
    @AuraEnabled
    public Id opportunityId { get; set; }
    public List<OpportunityLineItemWrapper> opportunityLineItems { get; set; }
    public Opportunity oportunidade { get; set;}
    
    // Construtor da classe
    public AnaliseItensEdital() {
        // Atribuir o ID da oportunidade se estiver presente
        this.opportunityId = ApexPages.currentPage().getParameters().get('id');
        
        // Verificar se o opportunityId está presente antes de chamar os métodos
        if (opportunityId != null) {
            this.oportunidade = getOpp(); // Recuperar a oportunidade
            this.opportunityLineItems = getOpportunityLineItems(); // Recuperar os OpportunityLineItems
        }
    }
    
    public class OpportunityLineItemWrapper {
        public OpportunityLineItem parentItem { get; set; }
        public List<OpportunityLineItem> childItems { get; set; }
    }
    
    // Método para buscar a oportunidade
    public Opportunity getOpp() {
        Opportunity opp = [SELECT ID, Name, Account.Name, Numero_OP__c, StageName, Sub_Fase__c, Account.BillingCity, Account.BillingState, Amount, CloseDate, Faturamento_Feito2__r.Name FROM Opportunity WHERE ID = :opportunityId LIMIT 1];
        return opp;
    }
    
    // Método para buscar os OpportunityLineItems agrupados por item pai
    public List<OpportunityLineItemWrapper> getOpportunityLineItems() {
        Map<Decimal, OpportunityLineItemWrapper> itemMap = new Map<Decimal, OpportunityLineItemWrapper>();
        
        // Query para obter os OpportunityLineItems
        List<OpportunityLineItem> lineItems = [
            SELECT Id, CreatedDate, Name, Quantity, UnitPrice, TotalPrice, Item__c, Item_pai__c, 
            Codigo_fabricante__c, Produto__c, Cumprimento_com_o_edital__c, Analise_Tecnica__c, 
            Nome_do_Fabricante__c, Interposicoes__c, Product2.Modelo__c, Perdido__c, Abreviacoes__c, 
            Valor_original_perdido__c, Itens_que_justificam__c, Marcas_que_atendem__c, Marcas_que_nao_atendem__c, Item_do_edital__c, 
            Enviado_questionameto_ou_impugna_o__c, Resposta_doorgao_e_novos_filtros__c, 
            Product2.Valor_de_Venda__c, Descricao_do_Especialista__c, CreatedBy.FirstName, CreatedBy.LastName
            FROM OpportunityLineItem
            WHERE OpportunityId = :opportunityId
            ORDER BY Item_pai__c, Name
        ];
        
        for (OpportunityLineItem item : lineItems) {
            // Verificar se é um item pai
            if (item.Item_pai__c == null) {
                // Se for um item pai, criar ou recuperar o wrapper
                if (!itemMap.containsKey(item.Item__c)) {
                    OpportunityLineItemWrapper wrapper = new OpportunityLineItemWrapper();
                    wrapper.parentItem = item;
                    wrapper.childItems = new List<OpportunityLineItem>();
                    itemMap.put(item.Item__c, wrapper);
                }
            } else {
                // Se for um item filho, adicionar ao grupo do item pai
                if (!itemMap.containsKey(item.Item_pai__c)) {
                    OpportunityLineItemWrapper wrapper = new OpportunityLineItemWrapper();
                    wrapper.parentItem = null;
                    wrapper.childItems = new List<OpportunityLineItem>();
                    itemMap.put(item.Item_pai__c, wrapper);
                }
                itemMap.get(item.Item_pai__c).childItems.add(item);
            }
        }
        
        // Atualizar o Subtotal e Subtotal_Unit para cada item pai
        for (OpportunityLineItemWrapper wrapper : itemMap.values()) {
            if (wrapper.parentItem != null) {
                Decimal sub = 0;
                for (OpportunityLineItem child : wrapper.childItems) {
                    if (child.TotalPrice != null) {
                        sub += child.TotalPrice;
                    }
                }
                OpportunityLineItem pai = wrapper.parentItem;
                
                // Atualizar Subtotal e Subtotal_Unit dinamicamente
                if (pai.Quantity != null && pai.Quantity > 0) {
                    pai.Subtotal_Unit__c = (sub + (pai.TotalPrice != null ? pai.TotalPrice : 0)) / pai.Quantity;
                } else {
                    pai.Subtotal_Unit__c = 0;
                }
                pai.Subtotal__c = sub + (pai.TotalPrice != null ? pai.TotalPrice : 0);
            }
        }
        
        return itemMap.values();
    }
     public static string dummy(String dummy) {
        string result = 'a';
        string result1 = 'a';
        string result2 = 'a';
        string result3 = 'a';
        string result4 = 'a';
        string result5 = 'a';
        string result6 = 'a';
        string result7 = 'a';
        string result8 = 'a';
        string result9 = 'a';
        string result10 = 'a';
        string result11 = 'a';
        string result12 = 'a';
        string result13 = 'a';
        string result14 = 'a';
        string result15 = 'a';
        string result16 = 'a';
        string result17 = 'a';
        string result18 = 'a';
        string result19 = 'a';
        string result20 = 'a';
        string result21 = 'a';
        string result22 = 'a';
        string result23 = 'a';
        string result24 = 'a';
        string result25 = 'a';
        string result26 = 'a';
        string result27 = 'a';
        string result28 = 'a';
        string result29 = 'a';
        
        return result;
    }
}