force-app/main/default/objects/Opportunity/fields/Faturamento_Feito2__c.field-meta.xml
<CustomField>
    <fullName>Faturamento_Feito2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Faturamento feito</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>FORNECEDOR, DISTRIBUIDOR</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Faturamentos Feitos (de oportunidades)</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Faturamento_Feito__c.field-meta.xml
<CustomField>
    <fullName>Faturamento_Feito__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>Empresa do grupo Hospcom que irá faturar o pedido.</inlineHelpText>
    <label>Faturamento feito</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Faturamentos Feitos (de pedidos)</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Ordem_de_trabalho__c.field-meta.xml
<CustomField>
    <fullName>Ordem_de_trabalho__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ordem de trabalho</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Faturamento_Feito2__c.field-meta.xml
<CustomField>
    <fullName>Faturamento_Feito2__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Faturado por (empresa)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Faturamentos Feitos (de ordens de trabalho)</relationshipLabel>
    <relationshipName>Ordens_de_trabalho</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Faturamento_Feito__c.field-meta.xml
<CustomField>
    <fullName>Faturamento_Feito__c</fullName>
    <label>Faturamento Feito</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HOSPCOM</fullName>
                <default>true</default>
                <label>HOSPCOM</label>
            </value>
            <value>
                <fullName>GDB</fullName>
            </value>
            <value>
                <fullName>HEALTH SOLUTION</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PedAtuFatClass.cls
public class PedAtuFatClass {
    
    public static String FluxoInicial(Order pedido){
        String retorno = null;
        String msg_erro = 'Informe esse campo';
        
        if(pedido.Faturamento_Feito__c == null){
            
            if(pedido.OpportunityId != null){
                Opportunity oportunidade = new Opportunity();
                oportunidade = ObtemOpp(pedido.OpportunityId);
                if(oportunidade.Faturamento_Feito2__c != null)
                    pedido.Faturamento_Feito__c = oportunidade.Faturamento_Feito2__c;
                else
                    retorno = msg_erro;
            }
            
            else if(pedido.Ordem_de_trabalho__c != null){
                WorkOrder ordem_de_trabalho = new WorkOrder();
                ordem_de_trabalho = ObtemOt(pedido.Ordem_de_trabalho__c);
                if(ordem_de_trabalho.Faturamento_Feito2__c != null)
                    pedido.Faturamento_Feito__c = ordem_de_trabalho.Faturamento_Feito2__c;
                else
                    retorno = msg_erro;
            }
            
            else{
                retorno = msg_erro;
            }
        }
        
        return retorno;
    }
    
    public static Opportunity ObtemOpp(Id oportunidade_id){
    	Opportunity oportunidade = new Opportunity();
        oportunidade = [
            SELECT	Id, Faturamento_Feito2__c	
            FROM 	Opportunity
            WHERE	Id = :oportunidade_id
        ];
        return oportunidade;
    }  
    
    public static WorkOrder ObtemOt(Id ordem_de_trabalho_id){
    	WorkOrder ordem_de_trabalho = new WorkOrder();
        ordem_de_trabalho = [
            SELECT	Id, Faturamento_Feito2__c	
            FROM 	WorkOrder
            WHERE	Id = :ordem_de_trabalho_id
        ];
        return ordem_de_trabalho;
    }  
    
}