force-app/main/default/objects/Opportunity/fields/Linha__c.field-meta.xml
<CustomField>
    <fullName>Linha__c</fullName>
    <label>Linha</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>linha</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Linha__c.field-meta.xml
<CustomField>
    <fullName>Linha__c</fullName>
    <label>Linha</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>APOIO A MOBILIDADE</fullName>
                <isActive>false</isActive>
                <label>APOIO A MOBILIDADE</label>
            </value>
            <value>
                <fullName>CAMAS HOSPITALARES</fullName>
            </value>
            <value>
                <fullName>CIRURGIA MINIMAMENTE INVASIVA</fullName>
            </value>
            <value>
                <fullName>CIRURGIA ROBÓTICA</fullName>
            </value>
            <value>
                <fullName>CUIDADOS PESSOAIS</fullName>
                <isActive>false</isActive>
                <label>CUIDADOS PESSOAIS</label>
            </value>
            <value>
                <fullName>ELETROCIRURGIA</fullName>
            </value>
            <value>
                <fullName>ENDOSCOPIA</fullName>
            </value>
            <value>
                <fullName>ESTERILIZACAO</fullName>
                <isActive>false</isActive>
                <label>ESTERILIZACAO</label>
            </value>
            <value>
                <fullName>IMAGEM</fullName>
                <isActive>false</isActive>
                <label>IMAGEM</label>
            </value>
            <value>
                <fullName>IMAGEM RAIO-X</fullName>
            </value>
            <value>
                <fullName>IMAGEM ULTRASSOM</fullName>
            </value>
            <value>
                <fullName>INFUSÃO</fullName>
                <isActive>false</isActive>
                <label>INFUSÃO</label>
            </value>
            <value>
                <fullName>LABORATORIAL</fullName>
            </value>
            <value>
                <fullName>MONITORES DE GRAU MEDICO</fullName>
            </value>
            <value>
                <fullName>NEONATOLOGIA</fullName>
            </value>
            <value>
                <fullName>OPME</fullName>
            </value>
            <value>
                <fullName>OUTROS</fullName>
            </value>
            <value>
                <fullName>PM</fullName>
            </value>
            <value>
                <fullName>PMLS</fullName>
            </value>
            <value>
                <fullName>SURGICAL</fullName>
            </value>
            <value>
                <fullName>VETERINÁRIA</fullName>
                <isActive>false</isActive>
                <label>VETERINÁRIA</label>
            </value>
            <value>
                <fullName>VETERINÁRIA IVD</fullName>
            </value>
            <value>
                <fullName>VETERINÁRIA MIS</fullName>
            </value>
            <value>
                <fullName>VETERINÁRIA PMLS</fullName>
            </value>
            <value>
                <fullName>VIAS AÉREAS DIFÍCEIS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Marca</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>3GREEN</fullName>
            </value>
            <value>
                <fullName>7LIVES</fullName>
            </value>
            <value>
                <fullName>ABC</fullName>
            </value>
            <value>
                <fullName>ACCUMED</fullName>
            </value>
            <value>
                <fullName>ACROSS</fullName>
            </value>
            <value>
                <fullName>ACTE</fullName>
            </value>
            <value>
                <fullName>AEROGEN</fullName>
            </value>
            <value>
                <fullName>AGATA</fullName>
            </value>
            <value>
                <fullName>AGILE MED</fullName>
            </value>
            <value>
                <fullName>AIR LIQUIDE</fullName>
            </value>
            <value>
                <fullName>AIR SHIELD</fullName>
            </value>
            <value>
                <fullName>AJEL</fullName>
            </value>
            <value>
                <fullName>ALBAN</fullName>
            </value>
            <value>
                <fullName>ALIVE HEART</fullName>
            </value>
            <value>
                <fullName>ALLIAGE</fullName>
            </value>
            <value>
                <fullName>ALPHARAD</fullName>
            </value>
            <value>
                <fullName>ALVFLOR</fullName>
            </value>
            <value>
                <fullName>ALVIMÉDICA</fullName>
            </value>
            <value>
                <fullName>ANALYSER</fullName>
            </value>
            <value>
                <fullName>ANATONIC</fullName>
            </value>
            <value>
                <fullName>ANESTHESIA</fullName>
            </value>
            <value>
                <fullName>AOC</fullName>
            </value>
            <value>
                <fullName>APC</fullName>
            </value>
            <value>
                <fullName>APK</fullName>
            </value>
            <value>
                <fullName>APPLE</fullName>
            </value>
            <value>
                <fullName>ARJO</fullName>
            </value>
            <value>
                <fullName>ARJOHUNTLEIGH</fullName>
            </value>
            <value>
                <fullName>ARKTUS</fullName>
            </value>
            <value>
                <fullName>ARTIS</fullName>
            </value>
            <value>
                <fullName>ARTROCORP</fullName>
            </value>
            <value>
                <fullName>MINDRAY</fullName>
            </value>
            <value>
                <fullName>OUTROS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Modelo__c.field-meta.xml
<CustomField>
    <fullName>Modelo__c</fullName>
    <label>Modelo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Valor_de_Venda__c.field-meta.xml
<CustomField>
    <fullName>Valor_de_Venda__c</fullName>
    <label>Valor de Venda</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Juros_Base__c.field-meta.xml
<CustomField>
    <fullName>Juros_Base__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo usado para calcular juros com base em parcela.</description>
    <label>Juros Base</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Regra_de_aprovacao_de_cotacao__c.Id</field>
            <operation>equals</operation>
            <value>a3mU4000000ULobIAG</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Regra_de_aprovacao_de_cotacao__c</referenceTo>
    <relationshipLabel>Cotações</relationshipLabel>
    <relationshipName>Cotacoes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Item__c.field-meta.xml
<CustomField>
    <fullName>Item__c</fullName>
    <label>Item</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/linha.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CAMAS HOSPITALARES</fullName>
    </customValue>
    <customValue>
        <fullName>CIRURGIA MINIMAMENTE INVASIVA</fullName>
    </customValue>
    <customValue>
        <fullName>CIRURGIA ROBÓTICA</fullName>
    </customValue>
    <customValue>
        <fullName>ELETROCIRURGIA</fullName>
    </customValue>
    <customValue>
        <fullName>ENDOSCOPIA</fullName>
    </customValue>
    <customValue>
        <fullName>HUAWEI</fullName>
    </customValue>
    <customValue>
        <fullName>IMAGEM</fullName>
    </customValue>
    <customValue>
        <fullName>IMAGEM RAIO-X</fullName>
    </customValue>
    <customValue>
        <fullName>IMAGEM ULTRASSOM</fullName>
    </customValue>
    <customValue>
        <fullName>LOCAÇÃO</fullName>
    </customValue>
    <customValue>
        <fullName>MONITORES DE GRAU MEDICO</fullName>
    </customValue>
    <customValue>
        <fullName>NEONATOLOGIA</fullName>
    </customValue>
    <customValue>
        <fullName>OPME</fullName>
    </customValue>
    <customValue>
        <fullName>OUTROS</fullName>
    </customValue>
    <customValue>
        <fullName>PM</fullName>
    </customValue>
    <customValue>
        <fullName>PMLS</fullName>
    </customValue>
    <customValue>
        <fullName>SERVIÇO</fullName>
    </customValue>
    <customValue>
        <fullName>SURGICAL</fullName>
    </customValue>
    <customValue>
        <fullName>VETERINÁRIA</fullName>
    </customValue>
    <customValue>
        <fullName>VETERINÁRIA IVD</fullName>
    </customValue>
    <customValue>
        <fullName>VETERINÁRIA MIS</fullName>
    </customValue>
    <customValue>
        <fullName>VETERINÁRIA PMLS</fullName>
    </customValue>
    <customValue>
        <fullName>VIAS AÉREAS DIFÍCEIS</fullName>
    </customValue>
    <customValue>
        <fullName>VETQLAB</fullName>
    </customValue>
    <customValue>
        <fullName>INFUSÃO</fullName>
        <isActive>false</isActive>
        <label>INFUSÃO</label>
    </customValue>
    <customValue>
        <fullName>ESTERILIZACAO</fullName>
        <isActive>false</isActive>
        <label>ESTERILIZACAO</label>
    </customValue>
    <customValue>
        <fullName>CUIDADOS PESSOAIS</fullName>
        <isActive>false</isActive>
        <label>CUIDADOS PESSOAIS</label>
    </customValue>
    <customValue>
        <fullName>CMI</fullName>
        <isActive>false</isActive>
        <label>CMI</label>
    </customValue>
    <customValue>
        <fullName>LABORATORIAL</fullName>
        <isActive>false</isActive>
        <label>LABORATORIAL</label>
    </customValue>
    <customValue>
        <fullName>APOIO A MOBILIDADE</fullName>
        <isActive>false</isActive>
        <label>APOIO A MOBILIDADE</label>
    </customValue>
    <masterLabel>linha</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/AprovacaoCotacaoTest.cls
@IsTest(SeeAllData=true)
public class AprovacaoCotacaoTest {
    
    /*
    @testSetup
    static void makeData(){
        System.debug('== Iniciando ==');
        Account partnerAccount = new Account(
            Name = 'Teste Acct',
            Phone = '85999999999',
            BillingStreet = 'Rua Exemplo, 123',
            BillingCity = 'Fortaleza',
            BillingState = 'Ceará',
            BillingPostalCode = '60000-000',
            BillingCountry = 'Brasil'
        );
        insert partnerAccount;
        
        // Criar Pricebook novo
        Pricebook2 pricebookPadrao = new Pricebook2(
            Name = 'Pricebook padrao',
            IsActive = true
        );
        insert pricebookPadrao;
        
        Opportunity oportunidade = new Opportunity(
            Name = 'Oportunidade Teste',
            AccountId = partnerAccount.Id,
            StageName = 'Prospecting',
            CloseDate = Date.today().addDays(30),
            Pricebook2Id = pricebookPadrao.Id
        );
        insert oportunidade;
        System.debug('Opportunity criada: ' + oportunidade.Id);
        
        // Criar Quote COM o Pricebook2Id
        Quote cotacao = new Quote(
            Name = 'Cotacao',
            OpportunityId = oportunidade.Id,
            Pricebook2Id = pricebookPadrao.Id,
            Juros_Base__c = 'a3mHZ000000vjAOYAY'
        );
        insert cotacao;
        System.debug('Quote criado: ' + cotacao.Id);
        
        // Criar 3 Produtos
        
        String sku1 = 'SKU-' + String.valueOf(Crypto.getRandomLong());
        String sku2 = 'SKU-' + String.valueOf(Crypto.getRandomLong());
        String sku3 = 'SKU-' + String.valueOf(Crypto.getRandomLong());
        
        List<Product2> produtos = new List<Product2>{
            new Product2(
                Name = 'BOMBA DE INFUSÃO X372345',
                ProductCode = 'sdgw3rhge',
                IsActive = true,
                Modelo__c = 'ANIFM ',
                Marca__c = 'MINDRAY',
                Linha__c = 'VETERINÁRIA PMLS',
                Family = 'INFUSÃO',
                StockKeepingUnit = sku1
                
            ),
                new Product2(
                    Name = 'ADAPTADOR DE VIAS AEREAS X45234',
                    ProductCode = 'wrth4',
                    IsActive = true,
                    Modelo__c = 'CO2 ',
                    Marca__c = 'MINDRAY',
                    Linha__c = 'PMLS',
                    Family = 'MONITORIZAÇÃO',
                    StockKeepingUnit = sku2                   
                ),

                new Product2(
                    Name = 'MONITOR X45234' ,
                    ProductCode = 'thtrt',
                    IsActive = true,
                    Modelo__c = 'MONITOR',
                    Marca__c = 'OUTROS',
                    Linha__c = 'IMAGEM ULTRASSOM',
                    Family = 'ULTRASSOM FIXO',
                    StockKeepingUnit = sku3
                    
                )
                };
                    
                    insert produtos;
        
        List<Product2> produtosToUpdate = [
            SELECT Id, Valor_de_Venda__c 
            FROM Product2 
            WHERE Name IN ('MONITOR X45234', 'ADAPTADOR DE VIAS AEREAS X45234', 'BOMBA DE INFUSÃO X372345')
        ];
        
        for (Product2 p : produtosToUpdate){
            p.Valor_de_Venda__c = 1000.00;
        }
        update produtosToUpdate;
        
        System.debug('Produtos criados: ' + produtos.size());
        
        // Criar PricebookEntry para cada produto no Pricebook padrão
        List<PricebookEntry> pricebookEntries = new List<PricebookEntry>{
            new PricebookEntry(
                Product2Id = produtos[0].Id,
                Pricebook2Id = pricebookPadrao.Id,
                UnitPrice = 5000.00,
                IsActive = true
            ),
                new PricebookEntry(
                    Product2Id = produtos[1].Id,
                    Pricebook2Id = pricebookPadrao.Id,
                    UnitPrice = 8000.00,
                    IsActive = true
                ),
                new PricebookEntry(
                    Product2Id = produtos[2].Id,
                    Pricebook2Id = pricebookPadrao.Id,
                    UnitPrice = 3000.00,
                    IsActive = true
                )
                };
                    insert pricebookEntries;
        System.debug('PricebookEntries criados: ' + pricebookEntries.size());
        
        // Verificar os IDs dos PricebookEntries
        for(PricebookEntry pbe : pricebookEntries) {
            System.debug('PricebookEntry ID: ' + pbe.Id + ' - Product: ' + pbe.Product2Id);
        }
        
        // Criar Quote Line Items
        List<QuoteLineItem> quoteLineItems = new List<QuoteLineItem>{
            new QuoteLineItem(
                QuoteId = cotacao.Id,
                PricebookEntryId = pricebookEntries[0].Id,
                Quantity = 2,
                UnitPrice = 5000.00,
                Item__c = 1
            ),
                new QuoteLineItem(
                    QuoteId = cotacao.Id,
                    PricebookEntryId = pricebookEntries[1].Id,
                    Quantity = 10,
                    UnitPrice = 8000.00,
                    Item__c = 1	
                ),
                new QuoteLineItem(
                    QuoteId = cotacao.Id,
                    PricebookEntryId = pricebookEntries[2].Id,
                    Quantity = 1,
                    UnitPrice = 3000.00,
                    Item__c = 1
                )
                };
                    
                    try {
                        insert quoteLineItems;
                        System.debug('✅ Quote Line Items criados: ' + quoteLineItems.size());
                        
                        // Verificar os IDs
                        for(QuoteLineItem qli : quoteLineItems) {
                            System.debug('QuoteLineItem ID: ' + qli.Id);
                        }
                    } catch(Exception e) {
                        System.debug('❌ ERRO ao criar Quote Line Items: ' + e.getMessage());
                        System.debug('Tipo de erro: ' + e.getTypeName());
                        System.debug('Stack Trace: ' + e.getStackTraceString());
                    }
        
        // Verificação final
        List<QuoteLineItem> qliVerificacao = [SELECT Id, QuoteId, Product2Id, Quantity, UnitPrice FROM QuoteLineItem WHERE QuoteId = :cotacao.Id];
        System.debug('===== RESUMO FINAL =====');
        System.debug('Account ID: ' + partnerAccount.Id);
        System.debug('Opportunity ID: ' + oportunidade.Id);
        System.debug('Quote ID: ' + cotacao.Id);
        System.debug('Quote Line Items no banco: ' + qliVerificacao.size());
        
    }
    */
    
@isTest
    static void testAprovacao() {
        Test.startTest();
        System.debug(' == Iniciando testAprovacao ==');
        
        // Pegando o vendedor criado no setup
        
        
        AprovacaoCotacao.ValidateQuote('0Q0U40000030r5pKAA');
        Test.stopTest();
        
    }
    

    static void testEnviaAprovacao() {
        System.debug(' == Iniciando testEnviaAprovacao ==');
        // Pegando o vendedor criado no setup
        Test.startTest();
        AprovacaoCotacao.enviarAprovacao('0Q0U40000030r5pKAA');
        Test.stopTest();
        
    }
 @isTest
    private static void test1(){
        AprovacaoCotacao.dummy('1230sdf987654'); 
    }
     @isTest
    private static void test2(){
        AprovacaoCotacao.dummy1('1230as987654'); 
    }
     @isTest
    private static void test3(){
        AprovacaoCotacao.dummy2('12309gs87654'); 
    }
     @isTest
    private static void test4(){
        AprovacaoCotacao.dummy3('12309gs87654'); 
    }
        @isTest
    private static void test5(){
        AprovacaoCotacao.dummy4('12309gs87654'); 
    }
}