force-app/main/default/objects/Opportunity/fields/Ordem_de_trabalho_Relacionada__c.field-meta.xml
<CustomField>
    <fullName>Ordem_de_trabalho_Relacionada__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Ordem de Trabalho a qual essa Oportunidade pertence.</description>
    <inlineHelpText>Ordem de Trabalho a qual essa Oportunidade pertence.</inlineHelpText>
    <label>Ordem de trabalho (excluir)</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Oportunidades (desativado)</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Ordem_de_trabalho__c.field-meta.xml
<CustomField>
    <fullName>Ordem_de_trabalho__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Ordem de trabalho</label>
    <referenceTo>WorkOrder</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Status_Permissao__c.field-meta.xml
<CustomField>
    <fullName>Status_Permissao__c</fullName>
    <defaultValue>false</defaultValue>
    <label>_Status Permissão (del)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Sub_Status__c.field-meta.xml
<CustomField>
    <fullName>Sub_Status__c</fullName>
    <description>Parecer final da OT.</description>
    <inlineHelpText>Parecer final da OT.</inlineHelpText>
    <label>Sub-Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FINALIZADO</fullName>
            </value>
            <value>
                <fullName>NÃO AUTORIZADO</fullName>
            </value>
            <value>
                <fullName>SEM CONSERTO</fullName>
            </value>
            <value>
                <fullName>NÃO APRESENTOU DEFEITO</fullName>
            </value>
            <value>
                <fullName>GARANTIA DE SERVIÇO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OrdemDeTrabalhoCascata.cls
public class OrdemDeTrabalhoCascata {
	
	public static List<Order>		pedidos_de_venda;
    
	// métodos externos -------------------------------------------------------------------
	
	public static Void Status(WorkOrder ordem_de_trabalho){
        if(pedidos_de_venda==null)
            ObtemPedidosDeVenda(ordem_de_trabalho.Id);
        
        String novo_status = null;
		if(ordem_de_trabalho.Status == 'AGUARDANDO FATURAMENTO')
			novo_status  = 'Aguardando Faturamento Cliente';
		else if(ordem_de_trabalho.Status == 'DISPONIVEL PARA ENTREGA')
			novo_status = 'Faturado';
		else if(ordem_de_trabalho.Status == 'ENTREGUE' || 
			   (ordem_de_trabalho.Status == 'FECHADO CONCLUÍDO' && ordem_de_trabalho.Sub_status__c == 'FINALIZADO'))
			novo_status = 'Entregue';
		else if(ordem_de_trabalho.Status == 'FECHADO CONCLUÍDO' && ordem_de_trabalho.Sub_status__c != 'FINALIZADO')
			novo_status = 'Cancelado';

        for(Integer cont=0; cont<pedidos_de_venda.size(); cont++){
            pedidos_de_venda[cont].Status = novo_status;
			pedidos_de_venda[cont].Status_Permissao__c = true;
		}
	}
		
	public static Void Efetivar(){
		if(pedidos_de_venda!=null && pedidos_de_venda.size()>0){
			update pedidos_de_venda;
			
			if(pedidos_de_venda[0].Status_Permissao__c==true)
				for(Integer cont=0; cont<pedidos_de_venda.size();cont++)
					pedidos_de_venda[cont].Status_Permissao__c=false;
			update pedidos_de_venda;
		}
	}
	
	// métodos internos -------------------------------------------------------------------
	
    static Void ObtemPedidosDeVenda(Id ordem_de_trabalho_id){
		pedidos_de_venda = new List<Order>();
		
		// pedidos da ot
		List<Order> pedidos_ot = new List<Order>();
        pedidos_ot = [
            SELECT	Id, Status	
            FROM 	Order
            WHERE	Ordem_de_trabalho__c = :ordem_de_trabalho_id
        ];
		if(pedidos_ot.size()>0)
			pedidos_de_venda.addAll(pedidos_ot);
		
		// pedidos das opps da ot
		List<Opportunity> oportunidades_ot = new List<Opportunity>();
		List<Id> oportunidade_ot_id = new List<Id>();
		oportunidades_ot = [
			SELECT	Id
			FROM 	Opportunity
			WHERE	Ordem_de_trabalho_Relacionada__c = :ordem_de_trabalho_id
		];
		if(oportunidades_ot.size()>0){
			for(Opportunity oportunidade_temp : oportunidades_ot)
				oportunidade_ot_id.add(oportunidade_temp.Id);
			List<Order> pedidos_opp_ot = new List<Order>();
			pedidos_opp_ot = [
				SELECT	Id, Status	
				FROM 	Order
				WHERE	OpportunityId IN :oportunidade_ot_id
			];
			if(pedidos_opp_ot.size()>0)
				pedidos_de_venda.addAll(pedidos_opp_ot);
		}
		
	}
    
}