force-app/main/default/objects/Contact/fields/Alergia__c.field-meta.xml
<CustomField>
    <fullName>Alergia__c</fullName>
    <label>Alergia</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Tipo_Sanguineo__c.field-meta.xml
<CustomField>
    <fullName>Tipo_Sanguineo__c</fullName>
    <label>Tipo Sanguíneo</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ColaboradoresController.cls
public class ColaboradoresController {
    public List <Contact> colaboradores				{get;set;}
    public List <Contact> colaboradoresAniv 		{get;set;}
    
    public ColaboradoresController(){
        
        colaboradores = [SELECT FirstName, LastName, Tipo_Sanguineo__c, Alergia__c, Department, Title, MobilePhone, BirthDate From Contact Where AccountId = '001i00000085QYb'  order By Name];
        
        colaboradoresAniv = [SELECT FirstName, Title, MobilePhone, Department, BirthDate From Contact Where AccountId = '001i00000085QYb' and BirthDate = THIS_MONTH  order By Name];
    }
}