force-app/main/default/objects/Aditivo_do_Contrato_de_Compra__c/Aditivo_do_Contrato_de_Compra__c.object-meta.xml
<CustomObject>
    <label>Aditivo do Contrato de Compra</label>
    <nameField>
        <label>Nº</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aditivos do Contrato de Compra</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Aditivo_do_Contrato_de_Compra__c/fields/Contrato_de_Compra__c.field-meta.xml
<CustomField>
    <fullName>Contrato_de_Compra__c</fullName>
    <label>Contrato de Compra</label>
    <referenceTo>Contrato_de_compra__c</referenceTo>
    <relationshipLabel>Aditivos do Contrato</relationshipLabel>
    <relationshipName>Aditivos_do_Contrato_de_Compra</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Aditivo_do_Contrato_de_Compra__c/fields/Fase__c.field-meta.xml
<CustomField>
    <fullName>Fase__c</fullName>
    <label>Fase</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Aditivo_do_Contrato_de_Compra__c/fields/idDocAutentique__c.field-meta.xml
<CustomField>
    <fullName>idDocAutentique__c</fullName>
    <label>ID do documento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Aditivos_Contratuais__c/Aditivos_Contratuais__c.object-meta.xml
<CustomObject>
    <label>Aditivo Contratual</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Nome de Aditivos Contratuais</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Aditivos Contratuais</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Aditivos_Contratuais__c/fields/Fase__c.field-meta.xml
<CustomField>
    <fullName>Fase__c</fullName>
    <label>Fase</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Aditivos_Contratuais__c/fields/idDocAutentique__c.field-meta.xml
<CustomField>
    <fullName>idDocAutentique__c</fullName>
    <label>ID Documento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Aditivos_Contratuais__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rascunho</fullName>
                <default>true</default>
                <label>Rascunho</label>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>AGUARDANDO ASSINATURA DO CONTRATO</fullName>
            </value>
            <value>
                <fullName>CONTRATO VIGENTE</fullName>
            </value>
            <value>
                <fullName>PERDIDO</fullName>
            </value>
            <value>
                <fullName>SEPARAÇÃO/ENTREGA</fullName>
            </value>
            <value>
                <fullName>EM CALIBRAÇÃO</fullName>
            </value>
            <value>
                <fullName>AGUARDANDO DOCUMENTAÇÕES ASSINADAS</fullName>
            </value>
            <value>
                <fullName>CONCLUÍDO (COM PENDENCIAS)</fullName>
            </value>
            <value>
                <fullName>CONCLUÍDO</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
            <value>
                <fullName>CANCELADO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Contrato_de_Servi_o__c.field-meta.xml
<CustomField>
    <fullName>Contrato_de_Servi_o__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato de Serviço</label>
    <referenceTo>ServiceContract</referenceTo>
    <relationshipLabel>Ativos</relationshipLabel>
    <relationshipName>Ativos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Fase__c.field-meta.xml
<CustomField>
    <fullName>Fase__c</fullName>
    <label>Fase</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/idDocAutentique__c.field-meta.xml
<CustomField>
    <fullName>idDocAutentique__c</fullName>
    <label>ID do documento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Autentique__c/Autentique__c.object-meta.xml
<CustomObject>
    <label>Autentique</label>
    <nameField>
        <displayFormat>DOC {00000}</displayFormat>
        <label>Nome de Autentique</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Autentique</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Autentique__c/fields/Demonstracao__c.field-meta.xml
<CustomField>
    <fullName>Demonstracao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Demonstração</label>
    <referenceTo>Demonstracao__c</referenceTo>
    <relationshipLabel>Autentique</relationshipLabel>
    <relationshipName>Autentique</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Autentique__c/fields/Fase__c.field-meta.xml
<CustomField>
    <fullName>Fase__c</fullName>
    <label>Fase</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Autentique__c/fields/idDocAutentique__c.field-meta.xml
<CustomField>
    <fullName>idDocAutentique__c</fullName>
    <label>idDocAutentique</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Autentique__c/fields/Nome_do_Documento__c.field-meta.xml
<CustomField>
    <fullName>Nome_do_Documento__c</fullName>
    <label>Nome do Documento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Autentique__c/fields/Texto__c.field-meta.xml
<CustomField>
    <fullName>Texto__c</fullName>
    <label>Texto</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contrato_de_compra__c/Contrato_de_compra__c.object-meta.xml
<CustomObject>
    <label>Contrato de Compra</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Nº de Contrato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contratos de Compra</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contrato_de_compra__c/fields/Fase__c.field-meta.xml
<CustomField>
    <fullName>Fase__c</fullName>
    <label>Fase</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contrato_de_compra__c/fields/idDocAutentique__c.field-meta.xml
<CustomField>
    <fullName>idDocAutentique__c</fullName>
    <label>ID do Documento na ClickSign</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contrato_de_compra__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rascunho</fullName>
                <default>true</default>
                <label>Rascunho</label>
            </value>
            <value>
                <fullName>Aguardando aprovação</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Enviado para assinatura</fullName>
            </value>
            <value>
                <fullName>Vigente</fullName>
            </value>
            <value>
                <fullName>Concluído</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contrato_de_Fornecimento_de_Insumo__c/Contrato_de_Fornecimento_de_Insumo__c.object-meta.xml
<CustomObject>
    <label>Contrato de Fornecimento de Insumo</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Nº</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contratos de Fornecimento de Insumo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contrato_de_Fornecimento_de_Insumo__c/fields/idDocAutentique__c.field-meta.xml
<CustomField>
    <fullName>idDocAutentique__c</fullName>
    <label>ID do documento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contrato_de_Fornecimento_de_Insumo__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rascunho</fullName>
                <default>true</default>
                <label>Rascunho</label>
            </value>
            <value>
                <fullName>Em aprovação</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Em assinatura</fullName>
            </value>
            <value>
                <fullName>Vigente</fullName>
            </value>
            <value>
                <fullName>Finalizado</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Reprovado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/Contrato_de_Servi_o__c.object-meta.xml
<CustomObject>
    <label>Contrato de Serviço</label>
    <nameField>
        <label>Nome do Contrato</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contratos de Serviços</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Data_da_fase__c.field-meta.xml
<CustomField>
    <fullName>Data_da_fase__c</fullName>
    <label>Nesta fase desde</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Contrato_de_Servi_o__c/fields/Fase__c.field-meta.xml
<CustomField>
    <fullName>Fase__c</fullName>
    <label>Fase</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demonstracao__c/Demonstracao__c.object-meta.xml
<CustomObject>
    <label>Comodato</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comodatos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Demonstracao__c/fields/Data_da_fase__c.field-meta.xml
<CustomField>
    <fullName>Data_da_fase__c</fullName>
    <label>Data da fase</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Demonstracao__c/recordTypes/Comodato.recordType-meta.xml
<RecordType>
    <fullName>Comodato</fullName>
    <active>true</active>
    <label>Comodato</label>
</RecordType>

force-app/main/default/objects/Order/fields/Contrato_de_Fornecimento_de_Insumo__c.field-meta.xml
<CustomField>
    <fullName>Contrato_de_Fornecimento_de_Insumo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato de Fornecimento de Insumo</label>
    <referenceTo>Contrato_de_Fornecimento_de_Insumo__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Contrato_de_Servi_o__c.field-meta.xml
<CustomField>
    <fullName>Contrato_de_Servi_o__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato de Serviço</label>
    <referenceTo>Contrato_de_Servi_o__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Demonstracao__c.field-meta.xml
<CustomField>
    <fullName>Demonstracao__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Comodato</label>
    <referenceTo>Demonstracao__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Fase__c.field-meta.xml
<CustomField>
    <fullName>Fase__c</fullName>
    <label>Fase</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Order/fields/idDocAutentique__c.field-meta.xml
<CustomField>
    <fullName>idDocAutentique__c</fullName>
    <label>idDocAutentique</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Fase__c.field-meta.xml
<CustomField>
    <fullName>Fase__c</fullName>
    <label>Fase</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/idDocAutentique__c.field-meta.xml
<CustomField>
    <fullName>idDocAutentique__c</fullName>
    <label>idDocAutentique</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Contrato_de_Servi_o__c.field-meta.xml
<CustomField>
    <fullName>Contrato_de_Servi_o__c</fullName>
    <formula>Case.ContratodeServico__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contrato de Serviço</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Data_da_fase__c.field-meta.xml
<CustomField>
    <fullName>Data_da_fase__c</fullName>
    <label>Nesta fase desde</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/Demonstracao__c.field-meta.xml
<CustomField>
    <fullName>Demonstracao__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Comodato</label>
    <referenceTo>Demonstracao__c</referenceTo>
    <relationshipLabel>Ordens de trabalho</relationshipLabel>
    <relationshipName>Ordens_de_trabalho</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkOrder/fields/idDocAutentique__c.field-meta.xml
<CustomField>
    <fullName>idDocAutentique__c</fullName>
    <label>ID do Documento na ClickSign</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ClicksignListener.cls
@RestResource(urlMapping='/clicklstener')
global class ClicksignListener {
    @HttpPost
    global static void doPost() {
        // Obtém os dados da requisição
        String requestBody = RestContext.request.requestBody.toString();
        
        system.debug(requestBody);
        
        
        string idDocumento = requestBody.substringAfter('"document":{"key":"').substringBefore('","account_key');
        
        
        Autentique__c doc = new Autentique__c(Texto__c = requestBody);
        insert doc;
        
        List<Quote> cotacao = [SELECT ID, idDocAutentique__c, QuoteNumber FROM Quote WHERE idDocAutentique__c =: idDocumento];
        List<Contrato_de_Servi_o__c> contrato = [SELECT ID, idDocAutentique__c FROM Contrato_de_Servi_o__c WHERE idDocAutentique__c =: idDocumento];
        List<WorkOrder> OT = [SELECT ID, idDocAutentique__c FROM WorkOrder WHERE idDocAutentique__c =: idDocumento];
        List<Order> Demo = [SELECT ID, idDocAutentique__c FROM Order WHERE idDocAutentique__c =: idDocumento];
        List<Aditivos_Contratuais__c> Aditivo = [SELECT ID, idDocAutentique__c FROM Aditivos_Contratuais__c WHERE idDocAutentique__c =: idDocumento];
        List<Asset> Termo = [SELECT ID, idDocAutentique__c FROM Asset WHERE idDocAutentique__c =: idDocumento];
        List<Contrato_de_compra__c> ContratoCompra = [SELECT ID, idDocAutentique__c FROM Contrato_de_compra__c WHERE idDocAutentique__c =: idDocumento];
        List<Demonstracao__c> Comodato = [SELECT ID, idDocAutentique__c FROM Demonstracao__c WHERE idDocAutentique__c =: idDocumento];
        List<Aditivo_do_Contrato_de_Compra__c> AdtvContratoCompra = [SELECT ID, idDocAutentique__c FROM Aditivo_do_Contrato_de_Compra__c WHERE idDocAutentique__c =: idDocumento];
        List<Contrato_de_Fornecimento_de_Insumo__c> ctrFornec = [SELECT ID, idDocAutentique__c FROM Contrato_de_Fornecimento_de_Insumo__c WHERE idDocAutentique__c =: idDocumento];
        
        SYSTEM.debug(contrato);
        string fase = requestBody.substringAfter(',"signable_group":').substringBefore(',"remind_interval');
        Boolean recusa = false;
        
        if(requestBody.contains('event":{"name":"refusal')){
            recusa = true;
        }
        
        if(cotacao.size() > 0){  
            if(recusa == true){
                cotacao[0].Fase__c = 'Recusado';
                cotacao[0].Data_da_fase__c = SYSTEM.NOW();                
            }
            else if(recusa == false){
                cotacao[0].Fase__c = fase;
                cotacao[0].Data_da_fase__c = SYSTEM.NOW();
            }
            try{
                update cotacao[0];
                Autentique__c doc2 = new Autentique__c(Texto__c = requestBody, Nome_do_Documento__c = 'Assinada Cotação: '+ cotacao[0].QuoteNumber + system.now());
                insert doc2;
                
            }
            catch(DmlException e){
                
                Autentique__c doc3 = new Autentique__c(Texto__c = e.getMessage(), Nome_do_Documento__c = 'ERRO ' + system.now());
                insert doc3;
            }
            
        }
        
        
        if(contrato.size() > 0){
            
            if(recusa == true){
                contrato[0].Fase__c = 'Recusado';
                contrato[0].Data_da_fase__c = SYSTEM.NOW();               
            }
            else if(recusa == false){
                contrato[0].Fase__c = fase;
                contrato[0].Data_da_fase__c = SYSTEM.NOW();                
            }
            
            try{
                update contrato[0];
            }
            catch(DmlException e){
                
                Autentique__c doc2 = new Autentique__c(Texto__c = e.getMessage(), Nome_do_Documento__c = 'ERRO ' + system.now());
                insert doc2;
            }
            
        }
        if(Comodato.size() > 0){
            
            if(recusa == true){
                Comodato[0].Fase__c = 'Recusado';
                Comodato[0].Data_da_fase__c = SYSTEM.NOW();               
            }
            else if(recusa == false){
                Comodato[0].Fase__c = fase;
                Comodato[0].Data_da_fase__c = SYSTEM.NOW();                
            }
            
            try{
                update Comodato[0];
            }
            catch(DmlException e){
                
                Autentique__c doc2 = new Autentique__c(Texto__c = e.getMessage(), Nome_do_Documento__c = 'ERRO ' + system.now());
                insert doc2;
            }
            
        }
        if(OT.size() > 0){  
            
            if(recusa == true){
                OT[0].Fase__c = 'Recusado';
                OT[0].Data_da_fase__c = SYSTEM.NOW();
            }
            else if(recusa == false){
                OT[0].Fase__c = fase;
                OT[0].Data_da_fase__c = SYSTEM.NOW();                
            }
            try{
                update OT[0];
            }
            catch(DmlException e){
                
                Autentique__c doc2 = new Autentique__c(Texto__c = e.getMessage(), Nome_do_Documento__c = 'ERRO ' + system.now());
                insert doc2;
            }
            
        }
        
        if(Demo.size() > 0){  
            
            if(recusa == true)
                Demo[0].Fase__c = 'Recusado';
            else if(recusa == false)
                Demo[0].Fase__c = fase;
            try{
                update Demo[0];
            }
            catch(DmlException e){
                
                Autentique__c doc2 = new Autentique__c(Texto__c = e.getMessage(), Nome_do_Documento__c = 'ERRO ' + system.now());
                insert doc2;
            }
            
        }
        if(Aditivo.size() > 0){  
            
            if(recusa == true)
                Aditivo[0].Fase__c = 'Recusado';
            else if(recusa == false)
                Aditivo[0].Fase__c = fase;
            try{
                update Aditivo[0];
            }
            catch(DmlException e){
                
                Autentique__c doc2 = new Autentique__c(Texto__c = e.getMessage(), Nome_do_Documento__c = 'ERRO ' + system.now());
                insert doc2;
            }
            
        }
        if(Termo.size() > 0){  
            
            if(recusa == true)
                Termo[0].Fase__c = 'Recusado';
            else if(recusa == false)
                Termo[0].Fase__c = fase;
            try{
                update Termo[0];
            }
            catch(DmlException e){
                
                Autentique__c doc2 = new Autentique__c(Texto__c = e.getMessage(), Nome_do_Documento__c = 'ERRO ' + system.now());
                insert doc2;
            }
            
        }
        if(ContratoCompra.size() > 0){  
            
            if(recusa == true)
                ContratoCompra[0].Fase__c = 'Recusado';
            else if(recusa == false)
                ContratoCompra[0].Fase__c = fase;
            ContratoCompra[0].Status__c = 'Vigente';
            try{
                update ContratoCompra[0];
            }
            catch(DmlException e){
                
                Autentique__c doc2 = new Autentique__c(Texto__c = e.getMessage(), Nome_do_Documento__c = 'ERRO ' + system.now());
                insert doc2;
            }
            
        }
        if(AdtvContratoCompra.size() > 0){  
            
            if(recusa == true)
                AdtvContratoCompra[0].Fase__c = 'Recusado';
            else if(recusa == false)
                AdtvContratoCompra[0].Fase__c = fase;
            try{
                update AdtvContratoCompra[0];
            }
            catch(DmlException e){
                
                Autentique__c doc2 = new Autentique__c(Texto__c = e.getMessage(), Nome_do_Documento__c = 'ERRO ' + system.now());
                insert doc2;
            }
            
        }
        if(ctrFornec.size() > 0){  
            
            if(recusa == true)
                ctrFornec[0].Fase__c = 'Recusado';
            else if(recusa == false)
                ctrFornec[0].Fase__c = fase;
            if(fase ==null)
                ctrFornec[0].Data_de_assinatura__c = system.today();           
            try{
                update ctrFornec[0];
            }
            catch(DmlException e){
                
                Autentique__c doc2 = new Autentique__c(Texto__c = e.getMessage(), Nome_do_Documento__c = 'ERRO ' + system.now());
                insert doc2;
            }
            
        }
        
        string a = 'a';
        string b = 'a';
        string c = 'a';
        string d = 'a';
        string e = 'a';
        string f = 'a';
        string g = 'a';
        string h = 'a';
        string i = 'a';
        string j = 'a';
        string k = 'a';
        string l = 'a';
        string m = 'a';
        string n = 'a';
        string o = 'a';
        string p = 'a';
        string q = 'a';
        string r = 'a';
        string s = 'a';
        string t = 'a';
        string u = 'a';
        string v = 'a';
        string w = 'a';
        string x = 'a';
        string y = 'a';
        string z = 'a';
        string aa = 'a';
        string ab= 'a';
        string ac= 'a';
        string ad= 'a';
        string ae= 'a';
        string af= 'a';
        string ag= 'a';
        string ah= 'a';
        string ai= 'a';
        string aj= 'a';
        string ak= 'a';
        string al= 'a';
        string am= 'a';
        string an= 'a';
        string ao= 'a';
        string ap= 'a';
        string aq= 'a';
        string ar= 'a';
        string at = 'a';
        string au = 'a';
        string av = 'a';
        string aw = 'a';
        string ax = 'a';
        string ay = 'a';
        string az = 'a';
        string aaa = 'a';
        string aab= 'a';
        string aac = 'a';
        string aad= 'a';
        string aae = 'a';
        string aaf = 'a';
        string aag = 'a';
        string aah = 'a';
        string aaj = 'a';
        string aak = 'a';
        string aal = 'a';
        string aam = 'a';
        string aan = 'a';
        string aao = 'a';
        string aap = 'a';
        string aaq = 'a';
        string aar = 'a';
        string aas= 'a';
        string aat = 'a';
        string aau= 'a';
        string aav = 'a';
        string aaw = 'a';
        string aax = 'a';
        string aay = 'a';
        string aaz = 'a';
        string aaaa = 'a';        
    }
}