force-app/main/default/objects/Nota_fiscal_de_pedido_de_compra__c/Nota_fiscal_de_pedido_de_compra__c.object-meta.xml
<CustomObject>
    <label>Nota fiscal de pedido de compra</label>
    <nameField>
        <label>Nº da Nota Fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notas fiscais de pedido de compra</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Nota_fiscal_de_pedido_de_compra__c/fields/Data_de_emissao__c.field-meta.xml
<CustomField>
    <fullName>Data_de_emissao__c</fullName>
    <label>Data de emissão</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Nota_fiscal_de_pedido_de_compra__c/fields/Pedido_de_Compra__c.field-meta.xml
<CustomField>
    <fullName>Pedido_de_Compra__c</fullName>
    <label>Pedido de Compra</label>
    <referenceTo>Fornecedor__c</referenceTo>
    <relationshipName>Notas_fiscais_de_compra</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Nota_fiscal_de_pedido_de_compra__c/fields/Valor_da_nota__c.field-meta.xml
<CustomField>
    <fullName>Valor_da_nota__c</fullName>
    <label>Valor da nota</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Pedido_de_compra__c/Pedido_de_compra__c.object-meta.xml
<CustomObject>
    <label>Cotação de compra</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Número da cotação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cotações de compra</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/NotaValidacaoTest.cls
@isTest(seeAllData=true)
public class NotaValidacaoTest {
    @isTest public static void teste(){
        test.startTest();
        Nota_fiscal_de_pedido_de_compra__c nfc = new Nota_fiscal_de_pedido_de_compra__c(Name = '111', 
                                                                                        Pedido_de_compra__c = 'a1b6e000006hXP7AAM', 
                                                                                        Valor_da_nota__c = 100, 
                                                                                        Data_de_emissao__c = date.parse('11/02/2023'));
        try{
            insert nfc;
        }
        catch(DmlException e){
            
        }
        test.stopTest();
        
    }
    @isTest public static void teste2(){
        test.startTest();
        Nota_fiscal_de_pedido_de_compra__c nfc = new Nota_fiscal_de_pedido_de_compra__c(Name = '62151',
                                                                                        Pedido_de_compra__c = 'a1b6e000006hXP7AAM', 
                                                                                        Valor_da_nota__c = 100, 
                                                                                        Data_de_emissao__c = SYSTEM.TODAY());
        try{
            insert nfc;
        }
        catch(DmlException e){
            
        }
        test.stopTest();
        
    }
}