force-app/main/default/objects/Avaliacao_de_Experiencia__c/Avaliacao_de_Experiencia__c.object-meta.xml
<CustomObject>
    <description>Objeto Criado para efetuar a avaliação do periodo de experiencia do colaborador</description>
    <label>Avaliação de Experiencia</label>
    <nameField>
        <displayFormat>AF-{0000}</displayFormat>
        <label>Avaliação de Experiência</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Avaliações de Experiencia</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Avaliacao_de_Experiencia__c/fields/Avaliacao_Finalizada__c.field-meta.xml
<CustomField>
    <fullName>Avaliacao_Finalizada__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo que controla se a avaliação foi concluida e impede a edição da avalição</description>
    <label>Avaliação Finalizada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Avaliacao_de_Experiencia__c/fields/Data_Fim__c.field-meta.xml
<CustomField>
    <fullName>Data_Fim__c</fullName>
    <description>Data final da avaliação</description>
    <label>Data Fim</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Avaliacao_de_Experiencia__c/fields/Gestor2__c.field-meta.xml
<CustomField>
    <fullName>Gestor2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gestor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Avaliações de Experiencia (Gestor)</relationshipLabel>
    <relationshipName>Avalia_es_de_Experiencia</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Avaliacao_de_Experiencia__c/fields/Nome_do_Colaborador__c.field-meta.xml
<CustomField>
    <fullName>Nome_do_Colaborador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nome do Colaborador</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Avaliações de Experiencia</relationshipLabel>
    <relationshipName>AvaliacoesExperiencia</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CienteAvaliacaoExperienciaControllerTest.cls
@isTest
public class CienteAvaliacaoExperienciaControllerTest {
    
      @testSetup
    static void makeData(){

        // Cria uma conta parceira SEM ativar IsPartner ainda
        Account partnerAccount = new Account(
            Name = 'Teste Acct',
            Phone = '85999999999'
        );
        insert partnerAccount;

        // Cria o contato
        Contact colaborador = new Contact(
            FirstName='Colaborador',
            LastName='Teste',
            AccountId = partnerAccount.Id,
            Email = 'colaborardor@teste.com'
        );
        insert colaborador;

        Contact gestor = new Contact(
            FirstName='Gestor',
            LastName='Teste',
            AccountId = partnerAccount.Id,
            Email = 'gestor@teste.com'
        );
        insert gestor;

        // Agora ativa o IsPartner e cria o usuário em System.runAs
        User dummyAdmin = [SELECT Id, name, isActive FROM User WHERE (Profile.Name = 'Administrador do sistema' OR Profile.Name = 'System Administrator' ) AND IsActive = true  LIMIT 1];

        System.runAs(dummyAdmin) {
            // Atualiza o IsPartner da conta
            partnerAccount.IsPartner = true;
            update partnerAccount;

            // Busca o perfil
            Profile p = [SELECT Id FROM Profile WHERE Name='Partner Community User'];

            // Cria o usuário parceiro
            User colaborarUser = new User(
                Alias = 'testuser',
                Email = 'test.partner@example.com',
                EmailEncodingKey = 'UTF-8',
                LastName = 'Partner',
                FirstName = 'Test',
                LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US',
                ProfileId = p.Id,
                TimeZoneSidKey = 'America/Los_Angeles',
                UserName = 'test.partner@hospcom.com',
                ContactId = colaborador.Id,
                IsActive = true
            );
            insert colaborarUser;

            User gestorUser = new User(
                Alias = 'testGest',
                Email = 'test2.partner@example.com',
                EmailEncodingKey = 'UTF-8',
                LastName = 'Gestor',
                FirstName = 'Test',
                LanguageLocaleKey = 'en_US',
                LocaleSidKey = 'en_US',
                ProfileId = p.Id,
                TimeZoneSidKey = 'America/Los_Angeles',
                UserName = 'test2.partner@hospcom.com',
                ContactId = gestor.Id,
                IsActive = true
            );
            insert gestorUser;
        }

        Avaliacao_de_Experiencia__c avaliacao = new Avaliacao_de_Experiencia__c(
            Nome_do_Colaborador__c = colaborador.Id, 
            Avaliacao_Finalizada__c = true,
            Gestor2__c = gestor.Id,
            Data_Fim__c = Date.today().addDays(1)
        );
        insert avaliacao;

        Avaliacao_de_Experiencia__c avaliacaoVencendo = new Avaliacao_de_Experiencia__c(
            Nome_do_Colaborador__c = colaborador.Id, 
            Avaliacao_Finalizada__c = false,
            Gestor2__c = gestor.Id,
            Data_Fim__c = Date.today().addDays(1)
        );
        insert avaliacaoVencendo;
    }



    @IsTest
    static void TestSaveAvaliacao() {
        Avaliacao_de_Experiencia__c avaliacao = [SELECT Id FROM Avaliacao_de_Experiencia__c LIMIT 1];

        Test.startTest();
            CienteAvaliacaoExperienciaController.saveAvaliacao(avaliacao.id);
        Test.stopTest();
    }

    @IsTest
    static void TestGetAvaliacao() {

        Avaliacao_de_Experiencia__c avaliacao = [SELECT Id FROM Avaliacao_de_Experiencia__c LIMIT 1];

        Test.startTest();
            CienteAvaliacaoExperienciaController.getAvaliacao(avaliacao.id);
        Test.stopTest();
    }
}