force-app/main/default/objects/Avaliacao_de_Experiencia__c/Avaliacao_de_Experiencia__c.object-meta.xml
<CustomObject>
    <description>Objeto Criado para efetuar a avaliação do periodo de experiencia do colaborador</description>
    <label>Avaliação de Experiencia</label>
    <nameField>
        <displayFormat>AF-{0000}</displayFormat>
        <label>Avaliação de Experiência</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Avaliações de Experiencia</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Avaliacao_de_Experiencia__c/fields/Aprovado__c.field-meta.xml
<CustomField>
    <fullName>Aprovado__c</fullName>
    <label>Aprovado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sim</fullName>
            </value>
            <value>
                <fullName>Não</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Avaliacao_de_Experiencia__c/fields/Avaliacao_Finalizada__c.field-meta.xml
<CustomField>
    <fullName>Avaliacao_Finalizada__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo que controla se a avaliação foi concluida e impede a edição da avalição</description>
    <label>Avaliação Finalizada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Avaliacao_de_Experiencia__c/fields/Justificativa_1__c.field-meta.xml
<CustomField>
    <fullName>Justificativa_1__c</fullName>
    <label>Justificativa 1</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Avaliacao_de_Experiencia__c/fields/Justificativa_2__c.field-meta.xml
<CustomField>
    <fullName>Justificativa_2__c</fullName>
    <label>Justificativa 2</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Avaliacao_de_Experiencia__c/fields/Justificativa_3__c.field-meta.xml
<CustomField>
    <fullName>Justificativa_3__c</fullName>
    <label>Justificativa 3</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Avaliacao_de_Experiencia__c/fields/Justificativa_4__c.field-meta.xml
<CustomField>
    <fullName>Justificativa_4__c</fullName>
    <label>Justificativa 4</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Avaliacao_de_Experiencia__c/fields/Justificativa_5__c.field-meta.xml
<CustomField>
    <fullName>Justificativa_5__c</fullName>
    <label>Justificativa 5</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Avaliacao_de_Experiencia__c/fields/Justificativa_6__c.field-meta.xml
<CustomField>
    <fullName>Justificativa_6__c</fullName>
    <label>Justificativa 6</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Avaliacao_de_Experiencia__c/fields/Justificativa_7__c.field-meta.xml
<CustomField>
    <fullName>Justificativa_7__c</fullName>
    <label>Justificativa 7</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Avaliacao_de_Experiencia__c/fields/Justificativa_8__c.field-meta.xml
<CustomField>
    <fullName>Justificativa_8__c</fullName>
    <label>Justificativa 8</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Avaliacao_de_Experiencia__c/fields/Observacoes__c.field-meta.xml
<CustomField>
    <fullName>Observacoes__c</fullName>
    <label>Observações</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Avaliacao_de_Experiencia__c/fields/Pergunta_1__c.field-meta.xml
<CustomField>
    <fullName>Pergunta_1__c</fullName>
    <description>(Gestcom/Hospcom)
Valor: Atitude de Dono
Pegunta: Demonstrou proatividade, responsabilidade e comprometimento em relação ao seu trabalho?</description>
    <label>Pergunta 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AvaliacaoExperiencia</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Avaliacao_de_Experiencia__c/fields/Pergunta_2__c.field-meta.xml
<CustomField>
    <fullName>Pergunta_2__c</fullName>
    <description>(Gestcom/Hospcom)
Valor: Atitude de Dono
Pegunta: Procurou soluções e tomou iniciativas para resolver ou melhorar processos?</description>
    <label>Pergunta 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AvaliacaoExperiencia</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Avaliacao_de_Experiencia__c/fields/Pergunta_3__c.field-meta.xml
<CustomField>
    <fullName>Pergunta_3__c</fullName>
    <description>(Gestcom/Hospcom)
Valor: Melhoria Contínua
Pegunta: Demonstrou abertura e receptividade ao receber críticas ou sugestões de melhoria?</description>
    <label>Pergunta 3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AvaliacaoExperiencia</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Avaliacao_de_Experiencia__c/fields/Pergunta_4__c.field-meta.xml
<CustomField>
    <fullName>Pergunta_4__c</fullName>
    <description>(Gestcom/Hospcom)
Valor: Melhoria Contínua
Pegunta: Teve curiosidade para buscar e aprender o máximo de atividades possíveis?</description>
    <label>Pergunta 4</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AvaliacaoExperiencia</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Avaliacao_de_Experiencia__c/fields/Pergunta_5__c.field-meta.xml
<CustomField>
    <fullName>Pergunta_5__c</fullName>
    <description>(Gestcom/Hospcom)
Valor: Respeito
Pegunta: Respeitou as pessoas e os processos sem colocar empecilhos?</description>
    <label>Pergunta 5</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AvaliacaoExperiencia</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Avaliacao_de_Experiencia__c/fields/Pergunta_6__c.field-meta.xml
<CustomField>
    <fullName>Pergunta_6__c</fullName>
    <description>(Gestcom/Hospcom)
Valor: Respeito
Pegunta: Suas ações foram realizadas com todos com cortesia e respeito?</description>
    <label>Pergunta 6</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AvaliacaoExperiencia</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Avaliacao_de_Experiencia__c/fields/Pergunta_7__c.field-meta.xml
<CustomField>
    <fullName>Pergunta_7__c</fullName>
    <description>(Gestcom/Hospcom)
Valor: Sangue no Olho
Pegunta: Teve atitude e arregaçou as mangas para colocar a mão na massa e começar a entregar o resultado?</description>
    <label>Pergunta 7</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AvaliacaoExperiencia</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Avaliacao_de_Experiencia__c/fields/Pergunta_8__c.field-meta.xml
<CustomField>
    <fullName>Pergunta_8__c</fullName>
    <description>(Gestcom/Hospcom)
Valor: Honestidade
Pegunta: Demonstrou transparência em suas comunicações e ações no ambiente de trabalho?</description>
    <label>Pergunta 8</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AvaliacaoExperiencia</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Avaliacao_de_Experiencia__c/fields/Periodo_da_Avaliacao__c.field-meta.xml
<CustomField>
    <fullName>Periodo_da_Avaliacao__c</fullName>
    <label>Período da Avaliação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1º Período (45 Dias)</fullName>
            </value>
            <value>
                <fullName>2º Período (90 Dias)</fullName>
            </value>
            <value>
                <fullName>1º Período</fullName>
                <isActive>false</isActive>
                <label>1º Período</label>
            </value>
            <value>
                <fullName>2º Período</fullName>
                <isActive>false</isActive>
                <label>2º Período</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/AvaliacaoExperiencia.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Não Atendeu</fullName>
    </customValue>
    <customValue>
        <fullName>Atendeu Parcialmente</fullName>
    </customValue>
    <customValue>
        <fullName>Atendeu Totalmente</fullName>
    </customValue>
    <customValue>
        <fullName>Superou</fullName>
    </customValue>
    <masterLabel>Avaliação de Experiencia</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FormularioAvaliacaoExperienciaController.cls
public with sharing class FormularioAvaliacaoExperienciaController {
    
    @AuraEnabled
    public static String saveRespostas(Id recordId,String respostasJSON, String justificativasJSON, String aprovado, String observacoes){


        Map<String, Object> respostas = (Map<String, Object> ) JSON.deserializeUntyped(respostasJSON);

        Map<String, Object> justificativas = (Map<String, Object>) JSON.deserializeUntyped(justificativasJSON);

        System.debug('recordId: ' + recordId);
        System.debug('respostas: ' + respostas);
        System.debug('justificativasJSON: ' + justificativasJSON);


        Avaliacao_de_Experiencia__c avaliacao = [SELECT Id, 
                                                        Pergunta_1__c, 
                                                        Pergunta_2__c, 
                                                        Pergunta_3__c, 
                                                        Pergunta_4__c, 
                                                        Pergunta_5__c, 
                                                        Pergunta_6__c, 
                                                        Pergunta_7__c, 
                                                        Pergunta_8__c,
                                                        Justificativa_1__c,
                                                        Justificativa_2__c,
                                                        Justificativa_3__c,
                                                        Justificativa_4__c,
                                                        Justificativa_5__c,
                                                        Justificativa_6__c,
                                                        Justificativa_7__c,
                                                        Justificativa_8__c,
                                                        Observacoes__c,
                                                        Avaliacao_Finalizada__c
                                                 FROM Avaliacao_de_Experiencia__c
                                                 WHERE Id =: recordId];

        avaliacao.Pergunta_1__c = (String)respostas.get('Pergunta_1__c');
        avaliacao.Pergunta_2__c = (String)respostas.get('Pergunta_2__c');
        avaliacao.Pergunta_3__c = (String)respostas.get('Pergunta_3__c');
        avaliacao.Pergunta_4__c = (String)respostas.get('Pergunta_4__c');
        avaliacao.Pergunta_5__c = (String)respostas.get('Pergunta_5__c');
        avaliacao.Pergunta_6__c = (String)respostas.get('Pergunta_6__c');
        avaliacao.Pergunta_7__c = (String)respostas.get('Pergunta_7__c');
        avaliacao.Pergunta_8__c = (String)respostas.get('Pergunta_8__c');
        avaliacao.Justificativa_1__c = (String)justificativas.get('Justificativa_1__c');
        avaliacao.Justificativa_2__c = (String)justificativas.get('Justificativa_2__c');
        avaliacao.Justificativa_3__c = (String)justificativas.get('Justificativa_3__c');
        avaliacao.Justificativa_4__c = (String)justificativas.get('Justificativa_4__c');
        avaliacao.Justificativa_5__c = (String)justificativas.get('Justificativa_5__c');
        avaliacao.Justificativa_6__c = (String)justificativas.get('Justificativa_6__c');
        avaliacao.Justificativa_7__c = (String)justificativas.get('Justificativa_7__c');
        avaliacao.Justificativa_8__c = (String)justificativas.get('Justificativa_8__c');
        avaliacao.Observacoes__c = observacoes;
        avaliacao.Avaliacao_Finalizada__c = true;
        avaliacao.Aprovado__c = aprovado;

        System.debug(avaliacao);

        update avaliacao;

        return 'success';
    }

    @AuraEnabled
    public static Avaliacao_de_Experiencia__c getRespostas(Id recordId){

        return [SELECT  Id, 
                        Pergunta_1__c, 
                        Pergunta_2__c, 
                        Pergunta_3__c, 
                        Pergunta_4__c, 
                        Pergunta_5__c, 
                        Pergunta_6__c, 
                        Pergunta_7__c, 
                        Pergunta_8__c ,
                        Justificativa_1__c, 
                        Justificativa_2__c, 
                        Justificativa_3__c,
                        Justificativa_4__c,
                        Justificativa_5__c,
                        Justificativa_6__c,
                        Justificativa_7__c,
                        Justificativa_8__c,
                        Avaliacao_Finalizada__c,
                        Periodo_da_Avaliacao__c,
                        Observacoes__c,
                        Aprovado__c
                FROM Avaliacao_de_Experiencia__c
                WHERE Id =: recordId];
    }
}