force-app/main/default/objects/Avaliacao_de_Experiencia__c/Avaliacao_de_Experiencia__c.object-meta.xml
<CustomObject>
    <description>Objeto Criado para efetuar a avaliação do periodo de experiencia do colaborador</description>
    <label>Avaliação de Experiencia</label>
    <nameField>
        <displayFormat>AF-{0000}</displayFormat>
        <label>Avaliação de Experiência</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Avaliações de Experiencia</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Avaliacao_de_Experiencia__c/fields/Aprovado__c.field-meta.xml
<CustomField>
    <fullName>Aprovado__c</fullName>
    <label>Aprovado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sim</fullName>
            </value>
            <value>
                <fullName>Não</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Avaliacao_de_Experiencia__c/fields/Avaliacao_Finalizada__c.field-meta.xml
<CustomField>
    <fullName>Avaliacao_Finalizada__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo que controla se a avaliação foi concluida e impede a edição da avalição</description>
    <label>Avaliação Finalizada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Avaliacao_de_Experiencia__c/fields/Ciente__c.field-meta.xml
<CustomField>
    <fullName>Ciente__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ciente</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Avaliacao_de_Experiencia__c/fields/Data_de_Ciencia__c.field-meta.xml
<CustomField>
    <fullName>Data_de_Ciencia__c</fullName>
    <label>Data de Ciência</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Avaliacao_de_Experiencia__c/fields/NotificacaoNomeColaborador__c.field-meta.xml
<CustomField>
    <fullName>NotificacaoNomeColaborador__c</fullName>
    <formula>Nome_do_Colaborador__r.FirstName + &apos; &apos; + Nome_do_Colaborador__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Notificação - Nome do Colaborador</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Avaliacao_de_Experiencia__c/fields/Periodo_da_Avaliacao__c.field-meta.xml
<CustomField>
    <fullName>Periodo_da_Avaliacao__c</fullName>
    <label>Período da Avaliação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1º Período (45 Dias)</fullName>
            </value>
            <value>
                <fullName>2º Período (90 Dias)</fullName>
            </value>
            <value>
                <fullName>1º Período</fullName>
                <isActive>false</isActive>
                <label>1º Período</label>
            </value>
            <value>
                <fullName>2º Período</fullName>
                <isActive>false</isActive>
                <label>2º Período</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CienteAvaliacaoExperienciaController.cls
public with sharing class CienteAvaliacaoExperienciaController {
    
    @AuraEnabled
    public static String saveAvaliacao(id recordId){
        Avaliacao_de_Experiencia__c avaliacao = [SELECT Id, 
                                                        Ciente__c, 
                                                        Data_de_Ciencia__c,
                                                        Avaliacao_Finalizada__c,
                                                        Aprovado__c
                                                 FROM Avaliacao_de_Experiencia__c
                                                 WHERE Id =: recordId];

       avaliacao.Ciente__c = true;
       avaliacao.Data_de_Ciencia__c = Date.today();

        try {
            update avaliacao;
            return 'Success';
        } catch (exception e) {
            return e.getMessage();
        }
        
                                                    
    }


    @AuraEnabled
    public static Avaliacao_de_Experiencia__c getAvaliacao(Id recordId){

        return [SELECT  Id, 
                        Periodo_da_Avaliacao__c, 
                        NotificacaoNomeColaborador__c,
                        Ciente__c,
                        Data_de_Ciencia__c, 
                        Aprovado__c
                FROM Avaliacao_de_Experiencia__c
                WHERE Id =: recordId];
    }
}