force-app/main/default/objects/Forecast_Salvo__c/Forecast_Salvo__c.object-meta.xml
<CustomObject>
    <label>Forecast Salvo</label>
    <nameField>
        <displayFormat>FS {000}</displayFormat>
        <label>Nº</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forecasts Salvos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Forecast_Salvo__c/fields/Linha__c.field-meta.xml
<CustomField>
    <fullName>Linha__c</fullName>
    <label>Linha</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Linha__c.field-meta.xml
<CustomField>
    <fullName>Linha__c</fullName>
    <label>Linha</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>linha</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Regi_o__c.field-meta.xml
<CustomField>
    <fullName>Regi_o__c</fullName>
    <label>Região</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Acre</fullName>
            </value>
            <value>
                <fullName>Alagoas</fullName>
            </value>
            <value>
                <fullName>Amapá</fullName>
            </value>
            <value>
                <fullName>Amazonas</fullName>
            </value>
            <value>
                <fullName>Bahia</fullName>
            </value>
            <value>
                <fullName>Ceará</fullName>
            </value>
            <value>
                <fullName>Distrito Federal</fullName>
            </value>
            <value>
                <fullName>Espírito Santo</fullName>
            </value>
            <value>
                <fullName>Goiás</fullName>
            </value>
            <value>
                <fullName>Maranhão</fullName>
            </value>
            <value>
                <fullName>Mato Grosso</fullName>
            </value>
            <value>
                <fullName>Mato Grosso do Sul</fullName>
            </value>
            <value>
                <fullName>Minas Gerais</fullName>
            </value>
            <value>
                <fullName>Pará</fullName>
            </value>
            <value>
                <fullName>Paraíba</fullName>
            </value>
            <value>
                <fullName>Paraná</fullName>
            </value>
            <value>
                <fullName>Pernambuco</fullName>
            </value>
            <value>
                <fullName>Piauí</fullName>
            </value>
            <value>
                <fullName>Rio de Janeiro</fullName>
            </value>
            <value>
                <fullName>Rio Grande do Norte</fullName>
            </value>
            <value>
                <fullName>Rio Grande do Sul</fullName>
            </value>
            <value>
                <fullName>Rondônia</fullName>
            </value>
            <value>
                <fullName>Roraima</fullName>
            </value>
            <value>
                <fullName>Santa Catarina</fullName>
            </value>
            <value>
                <fullName>São Paulo</fullName>
            </value>
            <value>
                <fullName>Sergipe</fullName>
            </value>
            <value>
                <fullName>Tocantins</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Regiao_Nome__c.field-meta.xml
<CustomField>
    <fullName>Regiao_Nome__c</fullName>
    <formula>IF(
Id == &apos;006U400000H3B6q&apos;, &apos;Região Norte&apos;,
IF(
TEXT(Oportunidade_OPME__c) == &apos;Sim&apos;, &apos;Exclusiva&apos;,
IF(
Estado__c = &quot;São Paulo&quot;
, &quot;Região SP&quot;,
IF(
OR(
Estado__c = &quot;Acre&quot;,
Estado__c = &quot;Amazonas&quot;,
Estado__c = &quot;Amapá&quot;,
Estado__c = &quot;Pará&quot;,
Estado__c = &quot;Rondônia&quot;,
Estado__c = &quot;Roraima&quot;
), &quot;Região Norte&quot;,
IF(
OR(
Estado__c = &quot;Mato Grosso&quot;,
Estado__c = &quot;Mato Grosso do Sul&quot;
), &quot;Região MT/MS&quot;,
IF(
OR(
Estado__c = &quot;Rio de Janeiro&quot;, 
Estado__c = &quot;Espírito Santo&quot;, 
Estado__c = &quot;Paraná&quot;, 
Estado__c = &quot;Santa Catarina&quot;, 
Estado__c = &quot;Rio Grande do Sul&quot; 
), &quot;Região RJ/ES/Sul&quot;,
IF(
OR(
Estado__c = &quot;Minas Gerais&quot;, 
Estado__c = &quot;Ceará&quot;, 
Estado__c = &quot;Piauí&quot;, 
Estado__c = &quot;Rio Grande do Norte&quot;, 
Estado__c = &quot;Piauí&quot;,
Estado__c = &quot;Paraíba&quot;,
Estado__c = &quot;Pernambuco&quot;,
Estado__c = &quot;Sergipe&quot;,
Estado__c = &quot;Maranhão&quot;,
Estado__c = &quot;Bahia&quot;,
Estado__c = &quot;Alagoas&quot; 
), &quot;Região NE/MG&quot;,
IF(
Estado__c = &quot;Distrito Federal&quot;,
&quot;Região DF&quot;,
IF(Pais__c = &apos;Colômbia&apos;, &apos;Colômbia&apos;,
&quot;Região GO/TO&quot;
)))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Região (Nome)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Forecast_Item__c.field-meta.xml
<CustomField>
    <fullName>Forecast_Item__c</fullName>
    <formula>IF(
  Opportunity.Propriedade_da_conta__c == &apos;PRIVADO&apos; || Opportunity.Propriedade_da_conta__c == &apos;&apos;,
  IF(TEXT(Opportunity.StageName) = &apos;COMITED&apos;, TotalPrice,
  IF(TEXT(Opportunity.StageName) = &apos;WIN&apos;, 0,
  IF(TEXT(Opportunity.StageName) = &apos;UPSIDE HIGH&apos;,
     IF(Opportunity.Probability &gt; 90, TotalPrice, 0),
  0))),  /* UPSIDE, OPEN e demais estágios = 0 */

IF(Opportunity.Propriedade_da_conta__c == &apos;PUBLICO&apos; || Opportunity.Propriedade_da_conta__c == &apos;FILANTROPIA&apos;,
IF(TEXT(Opportunity.StageName) = &apos;WIN&apos;, 0, 
IF(TEXT(Opportunity.StageName) = &apos;COMITED&apos; &amp;&amp; TEXT(Opportunity.Sub_Fase__c) != &apos;GARANTIDO&apos;, TotalPrice * 0.4,
IF(TEXT(Opportunity.StageName) = &apos;COMITED&apos; &amp;&amp; TEXT(Opportunity.Sub_Fase__c) = &apos;GARANTIDO&apos;, TotalPrice, 
IF(TEXT(Opportunity.StageName) = &apos;UPSIDE HIGH&apos;, TotalPrice * 0.2, 
IF(TEXT(Opportunity.StageName) = &apos;UPSIDE&apos;, TotalPrice * 0.1, 
IF(TEXT(Opportunity.StageName) = &apos;OPEN&apos;, TotalPrice * 0, TotalPrice * 0)))))), null)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Forecast Item</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Linha__c.field-meta.xml
<CustomField>
    <fullName>Linha__c</fullName>
    <formula>TEXT(PricebookEntry.Product2.Linha__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Linha</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Data_de_ativacao__c.field-meta.xml
<CustomField>
    <fullName>Data_de_ativacao__c</fullName>
    <formula>IF(RecordTypeId= &apos;0125A000001dyU3&apos;,  DATEVALUE(CreatedDate),  DATEVALUE(Inicio_Ativo__c ))</formula>
    <label>Data de ativação</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Linha_Locacao__c.field-meta.xml
<CustomField>
    <fullName>Linha_Locacao__c</fullName>
    <formula>IF(TEXT(Contrato_de_Servi_o__r.Subtipo__c) = &apos;Linha VETERINÁRIA&apos;, &apos;VETERINÁRIA PMLS&apos;,
IF(TEXT(Contrato_de_Servi_o__r.Subtipo__c) = &apos;Linha DEA&apos;, &apos;PMLS&apos;,
IF(TEXT(Contrato_de_Servi_o__r.Subtipo__c) = &apos;Linha PMLS&apos;, &apos;PMLS&apos;,
IF(TEXT(Contrato_de_Servi_o__r.Subtipo__c) = &apos;Linha ULTRASSOM&apos;, &apos;IMAGEM ULTRASSOM&apos;,
IF(TEXT(Contrato_de_Servi_o__r.Subtipo__c) = &apos;Linha VIAS AÉREAS DIFÍCEIS&apos;, &apos;VIAS AÉREAS DIFÍCEIS&apos;,
IF(TEXT(Contrato_de_Servi_o__r.Subtipo__c) = &apos;Linha SURGICAL&apos;, &apos;SURGICAL&apos;,
IF(TEXT(Contrato_de_Servi_o__r.Subtipo__c) = &apos;Linha OPME&apos;, &apos;OPME&apos;,
&quot;&quot;)))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Linha Locacao</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Natureza_de_Opera_o__c.field-meta.xml
<CustomField>
    <fullName>Natureza_de_Opera_o__c</fullName>
    <label>Natureza de Operação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BONIFICAÇÃO</fullName>
            </value>
            <value>
                <fullName>DEMONSTRAÇÃO</fullName>
            </value>
            <value>
                <fullName>LOCAÇÃO</fullName>
            </value>
            <value>
                <fullName>EMPRÉSTIMO</fullName>
            </value>
            <value>
                <fullName>REMESSA DE LOCAÇÃO</fullName>
            </value>
            <value>
                <fullName>REMESSA DE TROCA</fullName>
            </value>
            <value>
                <fullName>REMESSA EM CONSIGNAÇÃO</fullName>
            </value>
            <value>
                <fullName>SERVIÇO</fullName>
            </value>
            <value>
                <fullName>VENDA</fullName>
            </value>
            <value>
                <fullName>VENDA DA CONSIGNAÇÃO</fullName>
            </value>
            <value>
                <fullName>RETORNO DE LOCAÇÃO</fullName>
            </value>
            <value>
                <fullName>EXPORTAÇÃO</fullName>
            </value>
            <value>
                <fullName>Baixa de estoque Interno</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Regi_o__c.field-meta.xml
<CustomField>
    <fullName>Regi_o__c</fullName>
    <formula>IF(
OR(OPME__c &gt; 0, Huawei__c &gt; 0), &apos;Exclusiva&apos;,
IF(
AND(
OpportunityId != &apos;006U4000003toGz&apos;,
OpportunityId != &apos;006U40000052kwj&apos;,
OpportunityId != &apos;006U4000005yCoD&apos;,
OpportunityId != &apos;006U4000003uLo1&apos;,
OpportunityId != &apos;006U4000008Uw1x&apos;,
OpportunityId != &apos;006U400000Go7Rj&apos;,
BillingState = &quot;São Paulo&quot;
), &quot;Região SP&quot;,
IF(
OR(
BillingState == &quot;Acre&quot;, 
BillingState == &quot;Amazonas&quot;, 
BillingState == &quot;Amapá&quot;, 
BillingState == &quot;Pará&quot;, 
BillingState == &quot;Rondônia&quot;, 
BillingState == &quot;Roraima&quot;,
OpportunityId == &apos;006U4000003toGz&apos;,
OpportunityId == &apos;006U4000005rhLj&apos;,
OpportunityId == &apos;006U40000052kwj&apos;,
OpportunityId == &apos;006U4000005yCoD&apos;,
OpportunityId == &apos;006U4000003uLo1&apos;,
OpportunityId == &apos;006U4000008Uw1x&apos;
), &quot;Região Norte&quot;,
IF(
OR(
BillingState = &quot;Rio de Janeiro&quot;, 
BillingState = &quot;Espírito Santo&quot;, 
BillingState = &quot;Paraná&quot;, 
BillingState = &quot;Santa Catarina&quot;, 
BillingState = &quot;Rio Grande do Sul&quot; 
), &quot;Região RJ/ES/Sul&quot;,
IF(
OR(
BillingState = &quot;Mato Grosso&quot;, 
BillingState = &quot;Mato Grosso do Sul&quot; 
), &quot;Região MT/MS&quot;,
IF(
BillingState = &quot;Distrito Federal&quot;,
&quot;Região DF&quot;,
IF(
OR(
BillingState = &quot;Minas Gerais&quot;, 
BillingState = &quot;Ceará&quot;, 
BillingState = &quot;Piauí&quot;, 
BillingState = &quot;Rio Grande do Norte&quot;, 
BillingState = &quot;Piauí&quot;,
BillingState = &quot;Paraíba&quot;,
BillingState = &quot;Pernambuco&quot;,
BillingState = &quot;Sergipe&quot;,
BillingState = &quot;Maranhão&quot;,
BillingState = &quot;Bahia&quot;,
BillingState = &quot;Alagoas&quot; 
), &quot;Região NE/MG&quot;,
&quot;Região GO/TO&quot;
)))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Região</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Linha__c.field-meta.xml
<CustomField>
    <fullName>Linha__c</fullName>
    <formula>IF( Order.VETERIN_RIA__c &gt; 0, &apos;VETERINÁRIA PMLS&apos;,
IF( AND(Order.Linha_Locacao__c != &apos;&apos;, TEXT(Order.Natureza_de_Opera_o__c) = &apos;LOCAÇÃO&apos;, OR(TEXT(Product2.Linha__c) == &apos;&apos;, TEXT(Product2.Linha__c) == &apos;OUTROS&apos;)), Order.Linha_Locacao__c,  TEXT(Product2.Linha__c)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Linha</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Linha__c.field-meta.xml
<CustomField>
    <fullName>Linha__c</fullName>
    <label>Linha</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>APOIO A MOBILIDADE</fullName>
                <isActive>false</isActive>
                <label>APOIO A MOBILIDADE</label>
            </value>
            <value>
                <fullName>CAMAS HOSPITALARES</fullName>
            </value>
            <value>
                <fullName>CIRURGIA MINIMAMENTE INVASIVA</fullName>
            </value>
            <value>
                <fullName>CIRURGIA ROBÓTICA</fullName>
            </value>
            <value>
                <fullName>CUIDADOS PESSOAIS</fullName>
                <isActive>false</isActive>
                <label>CUIDADOS PESSOAIS</label>
            </value>
            <value>
                <fullName>ELETROCIRURGIA</fullName>
            </value>
            <value>
                <fullName>ENDOSCOPIA</fullName>
            </value>
            <value>
                <fullName>ESTERILIZACAO</fullName>
                <isActive>false</isActive>
                <label>ESTERILIZACAO</label>
            </value>
            <value>
                <fullName>IMAGEM</fullName>
                <isActive>false</isActive>
                <label>IMAGEM</label>
            </value>
            <value>
                <fullName>IMAGEM RAIO-X</fullName>
            </value>
            <value>
                <fullName>IMAGEM ULTRASSOM</fullName>
            </value>
            <value>
                <fullName>INFUSÃO</fullName>
                <isActive>false</isActive>
                <label>INFUSÃO</label>
            </value>
            <value>
                <fullName>LABORATORIAL</fullName>
            </value>
            <value>
                <fullName>MONITORES DE GRAU MEDICO</fullName>
            </value>
            <value>
                <fullName>NEONATOLOGIA</fullName>
            </value>
            <value>
                <fullName>OPME</fullName>
            </value>
            <value>
                <fullName>OUTROS</fullName>
            </value>
            <value>
                <fullName>PM</fullName>
            </value>
            <value>
                <fullName>PMLS</fullName>
            </value>
            <value>
                <fullName>SURGICAL</fullName>
            </value>
            <value>
                <fullName>VETERINÁRIA</fullName>
                <isActive>false</isActive>
                <label>VETERINÁRIA</label>
            </value>
            <value>
                <fullName>VETERINÁRIA IVD</fullName>
            </value>
            <value>
                <fullName>VETERINÁRIA MIS</fullName>
            </value>
            <value>
                <fullName>VETERINÁRIA PMLS</fullName>
            </value>
            <value>
                <fullName>VIAS AÉREAS DIFÍCEIS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/linha.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CAMAS HOSPITALARES</fullName>
    </customValue>
    <customValue>
        <fullName>CIRURGIA MINIMAMENTE INVASIVA</fullName>
    </customValue>
    <customValue>
        <fullName>CIRURGIA ROBÓTICA</fullName>
    </customValue>
    <customValue>
        <fullName>ELETROCIRURGIA</fullName>
    </customValue>
    <customValue>
        <fullName>ENDOSCOPIA</fullName>
    </customValue>
    <customValue>
        <fullName>HUAWEI</fullName>
    </customValue>
    <customValue>
        <fullName>IMAGEM</fullName>
    </customValue>
    <customValue>
        <fullName>IMAGEM RAIO-X</fullName>
    </customValue>
    <customValue>
        <fullName>IMAGEM ULTRASSOM</fullName>
    </customValue>
    <customValue>
        <fullName>LOCAÇÃO</fullName>
    </customValue>
    <customValue>
        <fullName>MONITORES DE GRAU MEDICO</fullName>
    </customValue>
    <customValue>
        <fullName>NEONATOLOGIA</fullName>
    </customValue>
    <customValue>
        <fullName>OPME</fullName>
    </customValue>
    <customValue>
        <fullName>OUTROS</fullName>
    </customValue>
    <customValue>
        <fullName>PM</fullName>
    </customValue>
    <customValue>
        <fullName>PMLS</fullName>
    </customValue>
    <customValue>
        <fullName>SERVIÇO</fullName>
    </customValue>
    <customValue>
        <fullName>SURGICAL</fullName>
    </customValue>
    <customValue>
        <fullName>VETERINÁRIA</fullName>
    </customValue>
    <customValue>
        <fullName>VETERINÁRIA IVD</fullName>
    </customValue>
    <customValue>
        <fullName>VETERINÁRIA MIS</fullName>
    </customValue>
    <customValue>
        <fullName>VETERINÁRIA PMLS</fullName>
    </customValue>
    <customValue>
        <fullName>VIAS AÉREAS DIFÍCEIS</fullName>
    </customValue>
    <customValue>
        <fullName>VETQLAB</fullName>
    </customValue>
    <customValue>
        <fullName>INFUSÃO</fullName>
        <isActive>false</isActive>
        <label>INFUSÃO</label>
    </customValue>
    <customValue>
        <fullName>ESTERILIZACAO</fullName>
        <isActive>false</isActive>
        <label>ESTERILIZACAO</label>
    </customValue>
    <customValue>
        <fullName>CUIDADOS PESSOAIS</fullName>
        <isActive>false</isActive>
        <label>CUIDADOS PESSOAIS</label>
    </customValue>
    <customValue>
        <fullName>CMI</fullName>
        <isActive>false</isActive>
        <label>CMI</label>
    </customValue>
    <customValue>
        <fullName>LABORATORIAL</fullName>
        <isActive>false</isActive>
        <label>LABORATORIAL</label>
    </customValue>
    <customValue>
        <fullName>APOIO A MOBILIDADE</fullName>
        <isActive>false</isActive>
        <label>APOIO A MOBILIDADE</label>
    </customValue>
    <masterLabel>linha</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/ForecastSalvoScheduler.cls
global class ForecastSalvoScheduler implements Schedulable {
    
    global void execute(SchedulableContext sc) {
        Map<String, Decimal> byLinhaRegiao = new Map<String, Decimal>();
        Map<String, Decimal> byLinhaGeral = new Map<String, Decimal>();
        
        // Pega o mês atual no formato yyyy-MM
        Integer mes = Date.today().month();
        String mesStr = mes < 10 ? '0' + String.valueOf(mes) : String.valueOf(mes);
        String mesAtual = String.valueOf(Date.today().year()) + '-' + mesStr;
        
        
        // === Forecasts de oportunidades ===
        List<OpportunityLineItem> forecastItems = [
            SELECT Forecast_Item__c, Product2.Linha__c, Opportunity.Regiao_Nome__c
            FROM OpportunityLineItem
            WHERE Opportunity.CloseDate = THIS_MONTH
        ];
        
        for (OpportunityLineItem item : forecastItems) {
            String linha = item.Product2.Linha__c;
            String regiao = item.Opportunity.Regiao_Nome__c;
            Decimal valor = item.Forecast_Item__c != null ? item.Forecast_Item__c : 0;
            
            if (linha != null) {
                String key = linha + '||' + regiao;
                
                Decimal atualRegiao = byLinhaRegiao.containsKey(key) ? byLinhaRegiao.get(key) : 0;
                byLinhaRegiao.put(key, atualRegiao + valor);
                
                Decimal atualGeral = byLinhaGeral.containsKey(linha) ? byLinhaGeral.get(linha) : 0;
                byLinhaGeral.put(linha, atualGeral + valor);
            }
        }
        
        // === Pedidos com EffectiveDate e naturezas específicas ===
        List<OrderItem> orderItems = [
            SELECT TotalPrice, Linha__c, Order.Regi_o__c
            FROM OrderItem
            WHERE Order.Data_de_ativacao__c = THIS_MONTH
            AND Order.Natureza_de_Opera_o__c IN ('locação', 'serviço', 'venda')
            AND Order.Status IN ('Atendido Parcial', 'Atendido Total','Ativo','Em Andamento','Entregue Parcial', 'Entregue Total')
        ];
        
        for (OrderItem item : orderItems) {
            String linha = item.Linha__c;
            String regiao = item.Order.Regi_o__c;
            Decimal valor = item.TotalPrice != null ? item.TotalPrice : 0;
            
            if (linha != null) {
                String key = linha + '||' + regiao;
                
                Decimal atualRegiao = byLinhaRegiao.containsKey(key) ? byLinhaRegiao.get(key) : 0;
                byLinhaRegiao.put(key, atualRegiao + valor);
                
                Decimal atualGeral = byLinhaGeral.containsKey(linha) ? byLinhaGeral.get(linha) : 0;
                byLinhaGeral.put(linha, atualGeral + valor);
            }
        }
        
        // === Pedidos de locação com status específicos ===
        List<OrderItem> orderItensLocacao = [
            SELECT TotalPrice, Linha__c, Order.Regi_o__c, Order.Status, Order.Linha_Locacao__c
            FROM OrderItem
            WHERE Order.EffectiveDate = THIS_MONTH
            AND Order.Natureza_de_Opera_o__c = 'locação'
            AND Order.Status IN ('Aguardando Aprovação Financeira', 'Aprovado', 'Rascunho')
        ];
        
        for (OrderItem item : orderItensLocacao) {
            String linha = item.Order.Linha_Locacao__c;
            String regiao = item.Order.Regi_o__c;
            Decimal valor = item.TotalPrice != null ? item.TotalPrice : 0;
            
            if (linha != null) {
                String key = linha + '||' + regiao;
                
                Decimal atualRegiao = byLinhaRegiao.containsKey(key) ? byLinhaRegiao.get(key) : 0;
                byLinhaRegiao.put(key, atualRegiao + valor);
                
                Decimal atualGeral = byLinhaGeral.containsKey(linha) ? byLinhaGeral.get(linha) : 0;
                byLinhaGeral.put(linha, atualGeral + valor);
            }
        }
        
        // === Criar registros por Linha + Região ===
        List<Forecast_Salvo__c> registros = new List<Forecast_Salvo__c>();
        
        for (String key : byLinhaRegiao.keySet()) {
            List<String> partes = key.split('\\|\\|');
            String linha = partes[0];
            String regiao = partes.size() > 1 ? partes[1] : null;
            
            registros.add(new Forecast_Salvo__c(
                Linha__c = linha,
                Regiao__c = regiao,
                Valor__c = byLinhaRegiao.get(key)
                //Mes__c = mesAtual
            ));
        }
        
        // === Criar registros gerais (por Linha apenas) ===
        for (String linha : byLinhaGeral.keySet()) {
            registros.add(new Forecast_Salvo__c(
                Linha__c = linha,
                Valor__c = byLinhaGeral.get(linha)
                //Mes__c = mesAtual
            ));
        }
        
        if (!registros.isEmpty()) {
            insert registros;
        }
    }
}